### DISCUSSION TITLE
Proper way to configure Calico Whisker for Ingress exposure?

### DISCUSSION THREAD

**Discussion by ViliusS** [projectcalico/calico#10395] [Q&A] [answered]
I'm trying to expose Calico Whisker through Ingress-NGINX load balancer instead of port forwarding. I've done the ingress part, but I've stumbled upon default Network Policy which forbids traffic from the Ingress-NGINX to reach port 8081.

I have tried to modify default `whisker` Network Policy which I assume is managed by the operator, however it get's overwritten after few seconds. To workaround this issue I have created an additional Network Policy object:

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: whisker-ingress
  namespace: calico-system
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          projectcalico.org/name: ingress-nginx
      podSelector:
        matchLabels:
          app.kubernetes.io/component: controller
          app.kubernetes.io/name: ingress-nginx
    ports:
    - port: 8081
      protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/name: whisker
  policyTypes:
  - Ingress
```

Is this the correct way to expose Whisker through Ingress-NGINX load balancer or is there any way to configure default Network Policy through operator using `operator.tigera.io/v1 kind: Whisker` CRD?
