### DISCUSSION TITLE
Calico BGPConfiguration cidr matching Metallb IPAddressPool

### DISCUSSION THREAD

**Discussion by Sediket** [projectcalico/calico#9126] [Q&A]
Hello, I have a question on the BGPConfiguration aligning with Metallb IPAddressPool.  In our metallb IPAddressPool, we used a range in the format of:
```
spec:
  addresses:
  - 172.70.0.150-172.70.0.179
```

For the BGPConfiguration for the serviceLoadBalancerIPs all of the examples specify a cidr network specifically and no ranges, do I have to include a cidr network that surrounds this range? or can I use the same format?

like this?:
```
kind: BGPConfiguration
metadata:
  name: default
spec:
  serviceLoadBalancerIPs:
  - cidr: 172.70.0.150-172.70.0.179
```

or does it have to be like this to surround the range of 172.70.0.150-172.70.0.179?

```
kind: BGPConfiguration
metadata:
  name: default
spec:
  serviceLoadBalancerIPs:
  - cidr: 172.70.0.128/26
```

Thanks!
