### ISSUE TITLE
Calico Network Policy Nullifies Existing Kubernetes Network Policy

### ISSUE THREAD

**Issue by Evesy** [projectcalico/calico#10168]
## Expected Behavior
Kubernetes Network Policy and Calico Network Policy should work together when both are used in a cluster

## Current Behavior
Adding a specific Calico Network Policy is stopping a previously working Kubernetes Network Policy

## Steps to Reproduce (for bugs)
1. Cluster with an existing Calico Network Policy to set default deny cluster wide: 
  ```apiVersion: crd.projectcalico.org/v1
kind: GlobalNetworkPolicy
metadata:
  name: default-deny
spec:
  namespaceSelector: name not in {"kube-system"}
  types:
  - Ingress
  - Egress
```
2. This has the intended effect of blocking all traffic.
3. Add a Kubernetes Network Policy allowing access to kube-dns:
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default
  namespace: default
spec:
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
```
4. Pods in the `default` namespace can now perform DNS lookups, as expected. However everything else, e.g. HTTPS requests to public IP's fail
5. Add another Calico Global Network Policy to allow all TCP traffic to certain networks:
```
apiVersion: crd.projectcalico.org/v1
kind: GlobalNetworkPolicy
metadata:
  name: allow-some-public-ips
spec:
  // Same result with an order <1000
  order: 2000
  types:
    - Egress
  egress:
    - action: Allow
      destination:
        nets:
        - 172.67.191.233/32
        - 104.21.92.106/32
        - 188.114.96.0/32
        - 188.114.97.0/32
        ports:
        - 443
      protocol: TCP
```
6. The workload can now reach the public IP's over HTTPS, however can no longer perform DNS lookups

I've compared the resulting iptables for a workload before and after the additional global policy is added and the difference is minimal:

**Before:**
```
-A cali-fw-calicf3f09731cb -m comment --comment "cali:pBx47JZ8fx5U0OZr" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A cali-fw-calicf3f09731cb -m comment --comment "cali:_pCCqwhG5K5Bb096" -m conntrack --ctstate INVALID -j DROP
-A cali-fw-calicf3f09731cb -m comment --comment "cali:_CQ93PAdcoKeUiTB" -j MARK --set-xmark 0x0/0x30000
-A cali-fw-calicf3f09731cb -p udp -m comment --comment "cali:geQCJ3j9vUsyfBLQ" -m comment --comment "Drop VXLAN encapped packets originating in workloads" -m multiport --dports 4789 -j DROP
-A cali-fw-calicf3f09731cb -p ipencap -m comment --comment "cali:l461X4AN9F2MDhDP" -m comment --comment "Drop IPinIP encapped packets originating in workloads" -j DROP
-A cali-fw-calicf3f09731cb -m comment --comment "cali:0KlgBVWpMXpTScvp" -m mark --mark 0x0/0x20000 -j cali-po-_nVst35oKLk7w_qFeHtI
-A cali-fw-calicf3f09731cb -m comment --comment "cali:uaHdOdYGfrCj2_sb" -m comment --comment "Return if policy accepted" -m mark --mark 0x10000/0x10000 -j RETURN
-A cali-fw-calicf3f09731cb -m comment --comment "cali:UakwyA92qoMRa7BX" -m mark --mark 0x0/0x20000 -j cali-po-default-deny
-A cali-fw-calicf3f09731cb -m comment --comment "cali:D0tZO7UaLVVu3E5L" -m comment --comment "Return if policy accepted" -m mark --mark 0x10000/0x10000 -j RETURN
-A cali-fw-calicf3f09731cb -m comment --comment "cali:P_XYDDCeqJlTN5Kt" -m comment --comment "Drop if no policies passed packet" -m mark --mark 0x0/0x20000 -j DROP
-A cali-fw-calicf3f09731cb -m comment --comment "cali:MRZmHUTHLzbwUmBZ" -j cali-pro-kns.default
-A cali-fw-calicf3f09731cb -m comment --comment "cali:-523vv5yQaEmabcX" -m comment --comment "Return if profile accepted" -m mark --mark 0x10000/0x10000 -j RETURN
-A cali-fw-calicf3f09731cb -m comment --comment "cali:LJD7061SAhakqIQ2" -j cali-pro-ksa.default.default
-A cali-fw-calicf3f09731cb -m comment --comment "cali:Xim8K_1tMgNG_HJY" -m comment --comment "Return if profile accepted" -m mark --mark 0x10000/0x10000 -j RETURN
-A cali-fw-calicf3f09731cb -m comment --comment "cali:lsZ0ZtjBPQxVk9oV" -m comment --comment "Drop if no profiles matched" -j DROP
```

**After**:
```
-A cali-fw-calicf3f09731cb -m comment --comment "cali:pBx47JZ8fx5U0OZr" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A cali-fw-calicf3f09731cb -m comment --comment "cali:_pCCqwhG5K5Bb096" -m conntrack --ctstate INVALID -j DROP
-A cali-fw-calicf3f09731cb -m comment --comment "cali:_CQ93PAdcoKeUiTB" -j MARK --set-xmark 0x0/0x30000
-A cali-fw-calicf3f09731cb -p udp -m comment --comment "cali:geQCJ3j9vUsyfBLQ" -m comment --comment "Drop VXLAN encapped packets originating in workloads" -m multiport --dports 4789 -j DROP
-A cali-fw-calicf3f09731cb -p ipencap -m comment --comment "cali:l461X4AN9F2MDhDP" -m comment --comment "Drop IPinIP encapped packets originating in workloads" -j DROP
-A cali-fw-calicf3f09731cb -m comment --comment "cali:0KlgBVWpMXpTScvp" -m mark --mark 0x0/0x20000 -j cali-po-_nVst35oKLk7w_qFeHtI
-A cali-fw-calicf3f09731cb -m comment --comment "cali:uaHdOdYGfrCj2_sb" -m comment --comment "Return if policy accepted" -m mark --mark 0x10000/0x10000 -j RETURN
-A cali-fw-calicf3f09731cb -m comment --comment "cali:PFz-_TfkOQfP0Nd9" -m mark --mark 0x0/0x20000 -j cali-po-_lPC0yYNMS1sw-G2-gvC
-A cali-fw-calicf3f09731cb -m comment --comment "cali:31ABLqFZa6k6RXV6" -m comment --comment "Return if policy accepted" -m mark --mark 0x10000/0x10000 -j RETURN
-A cali-fw-calicf3f09731cb -m comment --comment "cali:Ym-K6gJGNbjkDsbH" -m mark --mark 0x0/0x20000 -j cali-po-default-deny
-A cali-fw-calicf3f09731cb -m comment --comment "cali:qjhkOZulhyRZzOmn" -m comment --comment "Return if policy accepted" -m mark --mark 0x10000/0x10000 -j RETURN
-A cali-fw-calicf3f09731cb -m comment --comment "cali:nKKzOgSPUGON0imh" -m comment --comment "Drop if no policies passed packet" -m mark --mark 0x0/0x20000 -j DROP
-A cali-fw-calicf3f09731cb -m comment --comment "cali:WGg2XXkqkEdf8iOG" -j cali-pro-kns.default
-A cali-fw-calicf3f09731cb -m comment --comment "cali:hPZ_4_cj4RmSKJr2" -m comment --comment "Return if profile accepted" -m mark --mark 0x10000/0x10000 -j RETURN
-A cali-fw-calicf3f09731cb -m comment --comment "cali:20s60RZCKExwREqm" -j cali-pro-ksa.default.default
-A cali-fw-calicf3f09731cb -m comment --comment "cali:uWdjDU6xMFuNC2AY" -m comment --comment "Return if profile accepted" -m mark --mark 0x10000/0x10000 -j RETURN
-A cali-fw-calicf3f09731cb -m comment --comment "cali:7o9ySLOea3wOgEhT" -m comment --comment "Drop if no profiles matched" -j DROP
```

`cali-po-_nVst35oKLk7w_qFeHtI` is the rule for the Kubernetes Network Policy that allows access to kube-dns

`cali-po-_lPC0yYNMS1sw-G2-gvC` is the rule for the new Calico Global Network Policy that allows access to those public IP's.

I'm unsure how this changes anything, as the first rule still matches, which should set the right mark and should exit the chain `-j RETURN` before the new rule is evaluated. And even if the order was the other way round, all rules should be considered before hitting the default deny.

## Context
Attempting to add some global allow rules that should apply to all workloads, that should be additive to the existing Kubernetes network policies.

## Your Environment

* Calico version: Node: gke.gcr.io/calico/node:v3.28.2-gke.4, Typha: gke.gcr.io/calico/typha:v3.28.2-gke.4
* Calico dataplane (iptables, windows etc.): iptables v1.8.9 (nf_tables), OS: COS 117, Kernel: 6.6.56+
* Orchestrator version (e.g. kubernetes, mesos, rkt): GKE

**Comment by caseydavenport** [comment]
@Evesy I agree what you've describe should work.

I have to point you at this issue regarding the use of `crd.projectcalico.org/v1` vs `projectcalico.org/v3`: https://github.com/projectcalico/calico/issues/6412

Quite possible your GNP is invalid in some way but you are bypassing validation.

**Comment by Evesy** [comment]
Typing out the steps above has led me to figure it out, the clue was the differing response in the `dig` output the second time round. The latter added policy is `allow egress to these IP's on :443, block everything else`, and doesn't have the explicit `kube-system` exclusion, so `kube-dns/core-dns` as a result is failing to perform the lookups
```
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: allow-outbound-443
spec:
  order: 2000
  types:
    - Egress
  egress:
    - action: Allow
      destination:
        nets:
        - 172.67.191.233/32
        - 104.21.92.106/32
        - 188.114.96.0/32
        - 188.114.97.0/32
        ports:
        - 443
      protocol: TCP
```

Apologies for wasting your time!
