### ISSUE TITLE
Calico node can't resolve in-cluster domain names

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico#1019]
User *andrewmyhre* on the kubernetes slack hit an issue where his Calico instance couldn't resolve his etcd nodes because they were in cluster.  Another user, *qiujian* suggested using `dnsPolicy: ClusterFirstWithHostNet` in the container spec to allow Calico to resolve via kube-dns.

Is this something we should add to our manifests?

## Expected Behavior
Calico can resolve etcd via an in-cluster domain name.

## Current Behavior
Needs the above tweak to the manifest.

## Possible Solution
Add the tweak tot he manifest.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context
I haven't tested the tweak myself, it was only suggested on the k8s slack.

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt): k8s
* Operating System and version:
* Link to your project (optional):

**Comment by caseydavenport** [comment]
```
dnsPolicy: ClusterFirstWithHostNet
```

I think we've been holding out on trying this because it was added in k8s v1.6 and didn't want to break compat with v1.5 in our checked-in manifests.

This is probably the right fix, but needs testing in a few environments to make sure it doesn't have follow-on consequences.

**Comment by fasaxc** [comment]
Any bootstrapping concerns?  Does kube-dns get networked by calico itself?

**Comment by caseydavenport** [comment]
> Any bootstrapping concerns? Does kube-dns get networked by calico itself?

Yeah, it does :/

**Comment by caseydavenport** [comment]
I think this should just be closed - we can't do this by default because it relies on non-standard DNS settings to make kube-dns run in host networking.

**Comment by alwaysastudent** [comment]
@caseydavenport - I am facing this issue on my current k8s cluster setup with Calico VXLAN. 

I have 3 worker nodes. And I can't resolve domain names from daemonset pods that have enabled `hostNetwork: true` and `dnsPolicy: ClusterFirstWithHostNet`. This works very rarely sometimes, but mostly it flakes. 

Can you please help me troubleshoot this?

I can easily reproduce this with the following manifests.

```
# test manifest to prove dns resolutions fail with a hostNetwork on calico-vxlan
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dnsutils
  namespace: default
  labels:
    k8s-app: dnsutils
spec:
  selector:
    matchLabels:
      k8s-app: dnsutils
  template:
    metadata:
      labels:
        k8s-app: dnsutils
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
          name: dnsutils
          command:
          - sleep
          - "60000"
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  namespace: default
  labels:
    run: my-nginx
spec:
  ports:
  - port: 7865
    protocol: TCP
  selector:
    run: my-nginx
```
Apply the above manifest on a cluster which has around 3 worker nodes.

```
$ for p in $(kubectl get pods -l k8s-app=dnsutils -o name); do kubectl exec -i -t pod/dnsutils-9mpv9 nslookup my-nginx; done


fails like below

+ kubectl exec -i -t pod/dnsutils-qtm6r nslookup my-nginx
;; connection timed out; no servers could be reached
command terminated with exit code 1

+ kubectl exec -i -t pod/dnsutils-tp94d nslookup my-nginx
;; connection timed out; no servers could be reached
command terminated with exit code 1

+ kubectl exec -i -t pod/dnsutils-wstbr nslookup my-nginx
;; connection timed out; no servers could be reached
command terminated with exit code 1

```


It resolves just fine if don't set

```
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
```
