### ISSUE TITLE
Connection to the datastore is unauthorized error=connection is unauthorized: Unauthorized

### ISSUE THREAD

**Issue by junlintianxiazhifulinzhongguo** [projectcalico/calico#10211]
Operating environment
```
[root@k8s-master-01 net.d]# kubectl get nodes -o wide
NAME            STATUS   ROLES                  AGE   VERSION    INTERNAL-IP       EXTERNAL-IP   OS-IMAGE        KERNEL-VERSION             CONTAINER-RUNTIME
k8s-master-01   Ready    control-plane,worker   10d   v1.28.13   192.168.30.121    <none>        Anolis OS 8.9   5.10.134-18.an8.x86_64     containerd://1.7.13
k8s-master-02   Ready    control-plane          10d   v1.28.13   192.168.30.122    <none>        Anolis OS 8.9   5.10.134-18.an8.x86_64     containerd://1.7.13
k8s-master-03   Ready    control-plane          10d   v1.28.13   192.168.171.231   <none>        Anolis OS 8.9   5.10.134-16.2.an8.x86_64   containerd://1.7.13
k8s-work-01     Ready    worker                 10d   v1.28.13   192.168.171.232   <none>        Anolis OS 8.9   5.10.134-18.an8.x86_64     containerd://1.7.13
[root@k8s-master-01 net.d]#

```
Cluster status

```
[root@k8s-master-01 ~]# kubectl get pods -A
NAMESPACE     NAME                                       READY   STATUS              RESTARTS           AGE
default       nginx-deployment-54b6f7ddf9-4z2hq          1/1     Running             0                  10d
kube-system   calico-kube-controllers-568d4f5458-hlq9m   0/1     ContainerCreating   0                  4d23h
kube-system   calico-node-nwtbg                          0/1     CrashLoopBackOff    1400 (4m52s ago)   4d23h
kube-system   calico-node-qw7xx                          0/1     CrashLoopBackOff    804 (4m45s ago)    2d20h
kube-system   calico-node-vw9cn                          0/1     CrashLoopBackOff    1401 (4m33s ago)   4d23h
kube-system   calico-node-xpmzn                          0/1     CrashLoopBackOff    1400 (4m49s ago)   4d23h
kube-system   coredns-64c9584d7c-5r4kp                   1/1     Running             0                  10d
kube-system   coredns-64c9584d7c-sv67q                   1/1     Running             0                  10d
kube-system   kube-apiserver-k8s-master-01               1/1     Running             0                  10d
kube-system   kube-apiserver-k8s-master-02               1/1     Running             0                  10d
kube-system   kube-apiserver-k8s-master-03               1/1     Running             0                  10d
kube-system   kube-controller-manager-k8s-master-01      1/1     Running             9 (6d1h ago)       10d
kube-system   kube-controller-manager-k8s-master-02      1/1     Running             5 (6d1h ago)       10d
kube-system   kube-controller-manager-k8s-master-03      1/1     Running             1 (6d1h ago)       10d
kube-system   kube-proxy-cgbff                           1/1     Running             0                  10d
kube-system   kube-proxy-gj5ck                           1/1     Running             0                  10d
kube-system   kube-proxy-qxph7                           1/1     Running             0                  10d
kube-system   kube-proxy-wljtp                           1/1     Running             0                  10d
kube-system   kube-scheduler-k8s-master-01               1/1     Running             8 (6d1h ago)       10d
kube-system   kube-scheduler-k8s-master-02               1/1     Running             5 (6d1h ago)       10d
kube-system   kube-scheduler-k8s-master-03               1/1     Running             1 (6d1h ago)       10d
kube-system   kube-vip-k8s-master-01                     1/1     Running             12 (5d19h ago)     10d
kube-system   nodelocaldns-4wwvr                         1/1     Running             0                  10d
kube-system   nodelocaldns-5hwcz                         1/1     Running             0                  10d
kube-system   nodelocaldns-jplkd                         1/1     Running             0                  10d
kube-system   nodelocaldns-rcbz8                         1/1     Running             0                  10d
[root@k8s-master-01 ~]#

```
Error log
```
[root@k8s-master-01 ~]# kubectl logs -n kube-system     calico-node-nwtbg
Defaulted container "calico-node" out of: calico-node, upgrade-ipam (init), install-cni (init), mount-bpffs (init)
2025-04-14 03:11:21.323 [INFO][9] startup/startup.go 445: Early log level set to info
2025-04-14 03:11:21.323 [INFO][9] startup/utils.go 126: Using NODENAME environment for node name k8s-master-02
2025-04-14 03:11:21.323 [INFO][9] startup/utils.go 138: Determined node name: k8s-master-02
2025-04-14 03:11:21.323 [INFO][9] startup/startup.go 95: Starting node k8s-master-02 with version v3.27.4
2025-04-14 03:11:21.324 [INFO][9] startup/startup.go 450: Checking datastore connection
2025-04-14 03:11:21.332 [WARNING][9] startup/startup.go 462: Connection to the datastore is unauthorized error=connection is unauthorized: Unauthorized
2025-04-14 03:11:21.332 [WARNING][9] startup/utils.go 48: Terminating
Calico node failed to start
[root@k8s-master-01 ~]#

```
Description：
I have installed a single node k8s cluster using kubekey, Etcd was installed through binary and not deployed through containerization in k8s. After the cluster deployment was successful, I updated the k8s CA certificate and then updated the certificates of other components. After updating, I verified that the cluster had no issues. Later on, I found through adding nodes that I could add work and master nodes, but I couldn't add etcd nodes. When adding etcd nodes at the same time, the above error would be reported:
The following situation is normal:
```
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: k8s-master-01, address: 192.168.30.121, internalAddress: 192.168.30.121, user: root, password: "Demo@2023"}
  - {name: k8s-master-02, address: 192.168.30.122, internalAddress: 192.168.30.122, user: root, password: "Demo@2023"}
  - {name: k8s-master-03, address: 192.168.171.231, internalAddress: 192.168.171.231, user: root, password: "Demo@2023"}
  - {name: k8s-work-01, address: 192.168.171.232, internalAddress: 192.168.171.232, user: root, password: "Demo@2023"}
  roleGroups:
    etcd:
    - k8s-master-01
    control-plane:
    - k8s-master-01
    - k8s-master-02
    - k8s-master-03
    worker:
    - k8s-master-01
    - k8s-work-01
  controlPlaneEndpoint:
    ## Internal loadbalancer for apiservers
    internalLoadbalancer: kube-vip

    domain: lb.kubesphere.local
    address: "192.168.30.120"
    port: 6443
  system:
    # The ntp servers of chrony.
    ntpServers:
      - ntp.aliyun.com
      - k8s-master-01 # Set the node name in `hosts` as ntp server if no public ntp servers access.
    timezone: "Asia/Shanghai"
  kubernetes:
    version: v1.28.13
    clusterName: cluster.local
    autoRenewCerts: true
    containerManager: containerd
  etcd:
    type: kubekey
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    ## multus support. https://github.com/k8snetworkplumbingwg/multus-cni
    multusCNI:
      enabled: false
  registry:
    privateRegistry: ""
    namespaceOverride: ""
    registryMirrors: []
    insecureRegistries: []
  addons: []


```
The following situation will be problematic:
```
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: k8s-master-01, address: 192.168.30.121, internalAddress: 192.168.30.121, user: root, password: "Demo@2023"}
  - {name: k8s-master-02, address: 192.168.30.122, internalAddress: 192.168.30.122, user: root, password: "Demo@2023"}
  - {name: k8s-master-03, address: 192.168.171.231, internalAddress: 192.168.171.231, user: root, password: "Demo@2023"}
  - {name: k8s-work-01, address: 192.168.171.232, internalAddress: 192.168.171.232, user: root, password: "Demo@2023"}
  roleGroups:
    etcd:
    - k8s-master-01
    - k8s-master-02
    - k8s-master-03
    control-plane:
    - k8s-master-01
    - k8s-master-02
    - k8s-master-03
    worker:
    - k8s-master-01
    - k8s-work-01
  controlPlaneEndpoint:
    ## Internal loadbalancer for apiservers
    internalLoadbalancer: kube-vip

    domain: lb.kubesphere.local
    address: "192.168.30.120"
    port: 6443
  system:
    # The ntp servers of chrony.
    ntpServers:
      - ntp.aliyun.com
      - k8s-master-01 # Set the node name in `hosts` as ntp server if no public ntp servers access.
    timezone: "Asia/Shanghai"
  kubernetes:
    version: v1.28.13
    clusterName: cluster.local
    autoRenewCerts: true
    containerManager: containerd
  etcd:
    type: kubekey
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    ## multus support. https://github.com/k8snetworkplumbingwg/multus-cni
    multusCNI:
      enabled: false
  registry:
    privateRegistry: ""
    namespaceOverride: ""
    registryMirrors: []
    insecureRegistries: []
  addons: []


```

I tried uninstalling Calico and reinstalling it, but still got the same error. I tried downloading the latest Calico deployment from the official website again, but it also reported an error
I have verified that the content of Calico's certificate is consistent with that of CA's certificate
```
[root@k8s-master-01 net.d]# cat calico-kubeconfig
# Kubeconfig file for Calico CNI plugin.
apiVersion: v1
kind: Config
clusters:
- name: local
  cluster:
    server: https://[10.233.0.1]:443
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJTXM3OTBQK1p2K2N3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBME1ET3MHpOVEEwTURFd09UTXhNek5hTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUQrbFFvZjFZbE9hVExrQnVtSUFHdU5WWjhTZU1zemNubFVXU2JEcGppOG9IQ0xWa3pQSmhClYVGxnT3F1dHl2OVY3S3BRNTVqQ1JiTEtqL3g3NWR0RTdVbnczVU02anlFcVJWanI0bUhZNVl5QnFRRQorWjFUS0IrL0p2bDdSdGZDTTBIS1FaaHpDWDFtTU14WHpqQVNxUWUzV1RxNmV3Y2k5UkV0MmRaMEFZR1ZLL2xvCkEyTWF0K0JBSHBlZytGbGpETTJGN1B1NOY24vcjd4NXV3RHN1dklmL00zenRpTDhEMHdRU1cKVHJxSlZiMDI0SCtNVXdnWXlrWm5Sb0tmL3c4WUFSeER2WkgrQ2dsQmhMMTB1NnJzVFZVL3h5THVwUXNDL1c4Vwo2RmtMcUhIVlU3aDJueGZUTEphNEwxSWxLTG9QQWdNQkFBR2pXVEJYTUE0R0ExVWREd0REFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRL3lOQThxOTIwQlJGdzAyTGVpQTc4aGxLTXZqQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQXByT2RjV3FubQpLUThJdXc1aHdRSWUvTiZm5DZGpub2R0RUJKbXRzcDdtRXNaQjBIZ1lpY0N2d3BPNzBPSDNGCmVXZ3MzdGNuMCt1NnlPTDRyTWcxTnBZcEZUOHVNWU9WanF2bUt6NTJXZzZoMU5VV3h6QWtWUmxuR3ROd3JoZSsKazg3dCtIR2x0WFgzTXowUXVRY0lIajBReVFMMTB1YjJnN09VWjFKdFRyc3RVAvOXcvSkk2TQpTeElmTDNYWTZsalNqeXJmOTdPS0dBT21rZThiODByOS8yYjEweExDRlFxZ0crVVJKajFhbkl3dHAvc3IwM3VuCnZuVUdyaGtpOGdYWStFS1Vzd0IwUGhyNmFETEVYVGpGTTMwalJWbUZOMHhPK29SeDExMzNmUHFwOVRWcDdPWnAKWThpbExS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
users:
- name: calico
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6ImF6NEUweHEyYVVkcndDWnBCR1FSWXg5WEFkdkkyY2dpc3V6TzBXLTByVUkifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzQ0NDQwOTMDQzNTQ1MzAsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsInNlcnZpY2VhY2NvdW50Ijp7Im5hbWUiOiJjYWxpY28tY25pLXBsdWdpbiNzQxNTRmLTM1MTctNDE2MC05OWJjLTEyYTBjMjQ1OWYzYyJ9fSwibmJmIjoxNzQ0MzU0NTMwLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZS1zeXN0ZW06Y2FsaWNvLWNuaS1wbHVnaW4ifQ.sKmm8WLjegKMdc24W_K9o2p01SNcE_-EBWK2KtJipVmXfAS8glpQRT25kv1RcKfe-dPQPLn4NuACy2jHQRQfidY189dTU93HVWp_Ls11SnfJ52ZQVkccw2m8H61VqiRghi0Knrine4P9I9MNz46VDFNPM-YAsfH4nnix807wV5G22irekbZoYQ4vrNF25N0jnp-SqcyauDv4wmImt-oxkC57HGFf06CDSCGjG96NXyk8V6RD0apazedBic7NYTS4l_NRXJ__QO2EdbUA4nHAdfdKfbrM6_mkmnp3NXb9_hMXN-sTHyTZRQ04VQ
contexts:
- name: calico-context
  context:
    cluster: local
    user: calico
current-context: calico-context[root@k8s-master-01 net.d]#
[root@k8s-master-01 net.d]#
[root@k8s-master-01 net.d]#
[root@k8s-master-01 net.d]#
[root@k8s-master-01 net.d]#
[root@k8s-master-01 net.d]#
[root@k8s-master-01 net.d]#
[root@k8s-master-01 net.d]#
[root@k8s-master-01 net.d]#
[root@k8s-master-01 net.d]# echo "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJTXM3OTBQK1p2K2N3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBME1UZ3MHpOVEEwTURFd09UTXhNek5hTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUQrbFFvZjFZbE9hVExrQnVtSUFHdU5WWjhTZU1zemNubFVXU2JEcGppOG9IQ0xWa3pQSmNjlYVGxnT3F1dHl2OVY3S3BRNTVqQ1JiTEtqL3g3NWR0RTdVbnczVU02anlFcVJWanI0bUhZNVl5QnFRRQorWjFUS0IrL0p2bDdSdGZDTTBIS1FaaHpDWDFtTU14WHpqQVNxUWUzV1RxNmV3Y2k5UkV0MmRaMEFZR1ZLL2xvCkEyTWF0K0JBSHBlZytGbGpETTJGNFK1NOY24vcjd4NXV3RHN1dklmL00zenRpTDhEMHdRU1cKVHJxSlZiMDI0SCtNVXdnWXlrWm5Sb0tmL3c4WUFSeER2WkgrQ2dsQmhMMTB1NnJzVFZVL3h5THVwUXNDL1c4Vwo2RmtMcUhIVlU3aDJueGZUTEphNEwxSWxLTG9QQWdNQkFBR2pXVEJYTUE0R0ExVWRENwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRL3lOQThxOTIwQlJGdzAyTGVpQTc4aGxLTXZqQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQXByT2RjV3FubQpLUThJdXc1aHdRSWUzdiZm5DZGpub2R0RUJKbXRzcDdtRXNaQjBIZ1lpY0N2d3BPNzBPSDNGCmVXZ3MzdGNuMCt1NnlPTDRyTWcxTnBZcEZUOHVNWU9WanF2bUt6NTJXZzZoMU5VV3h6QWtWUmxuR3ROd3JoZSsKazg3dCtIR2x0WFgzTXowUXVRY0lIajBReVFMMTB1YjJnN09VWjFKdFQlc3RVAvOXcvSkk2TQpTeElmTDNYWTZsalNqeXJmOTdPS0dBT21rZThiODByOS8yYjEweExDRlFxZ0crVVJKajFhbkl3dHAvc3IwM3VuCnZuVUdyaGtpOGdYWStFS1Vzd0IwUGhyNmFETEVYVGpGTTMwalJWbUZOMHhPK29SeDExMzNmUHFwOVRWcDdPWnAKWThpbtLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K" | base64 -d
-----BEGIN CERTIFICATE-----
MIIDBTCCAe2gAwIBAgIIMs790P+Zv+cwDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE
AxMKa3ViZXJuZXRlczAeFw0yNTA0MDMwOTI2MzNaFw0zNTA0MDEwOTMxMzNaMBUx
EzARBgNVBAMTCmt1YmVybmV0ZXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
AoIBAQD+lQof1YlOaTLkBumIAGuNVZ8SeMszcnlUWSbDpji8oHCLVkzPJhB7mQUN
bt269XTlgOqutyv9V7KpQ55jCRbLKj/x75dtE7Unw3UM6jyEqRVjr4mHY5YyBqQE
+Z1TKB+/Jvl7RtfCM0HKQZhzCX1mMMxXzjASqQe3WTq6ewci9REt2dZ0AYGVK/lo
A2Mat+BAHpeg+FljDM2F7PrG16LjYUbE+SNcn/r7x5uwDsuvIf/M3ztiL8D0wQSW
TrqJVb024H+MUwgYykZnRoKf/w8YARxDvZH+CglBhL10u6rsTVU/xyLupQsC/W8W
6FkLqHHVU7h2nxfTLJa4L1IlKLoPAgMBAAGjWTBXMA4GA1UdDwEB/wQEAwICpDAP
BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQ/yNA8q920BRFw02LeiA78hlKMvjAV
BgNVHREEDjAMggprdWJlcm5ldGVzMA0GCSqGSIb3DQEBCwUAA4IBAQAprOdcWqnm
KQ8Iuw5hwQIe/MJqpl+fUvs7bfnCdjnodtEBJmtsp7mEsZB0HgYicCvwpO70OH3F
eWgs3tcn0+u6yOL4rMg1NpYpFT8uMYOVjqvmKz52Wg6h1NUWxzAkVRlnGtNwrhe+
k87t+HGltXX3Mz0QuQcIHj0QyQL10ub2g7OUZ1JtTrg1qJ9L/gmBW7EP/9w/JI6M
SxIfL3XY6ljSjyrf97OKGAOmke8b80r9/2b10xLCFQqgG+URJj1anIwtp/sr03un
vnUGrhki8gXY+EKUswB0Phr6aDLEXTjFM30jRVmFN0xO+oRx1133fPqp9TVp7OZp
Y8ilLSTk5LTt
-----END CERTIFICATE-----
[root@k8s-master-01 net.d]#
[root@k8s-master-01 net.d]#
[root@k8s-master-01 net.d]#
[root@k8s-master-01 net.d]#
[root@k8s-master-01 net.d]# cat /etc/kubernetes/pki/ca.crt
-----BEGIN CERTIFICATE-----
MIIDBTCCAe2gAwIBAgIIMs790P+Zv+cwDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE
AxMKa3ViZXJuZXRlczAeFw0yNTA0MDMwOTI2MzNaFw0zNTA0MDEwOTMxMzNaMBUx
EzARBgNVBAMTCmt1YmVybmV0ZXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
AoIBAQD+lQof1YlOaTLkBumIAGuNVZ8SeMszcnlUWSbDpji8oHCLVkzPJhB7mQUN
bt269XTlgOqutyv9V7KpQ55jCRbLKj/x75dtE7Unw3UM6jyEqRVjr4mHY5YyBqQE
+Z1TKB+/Jvl7RtfCM0HKQZhzCX1mMMxXzjASqQe3WTq6ewci9REt2dZ0AYGVK/lo
A2Mat+BAHpeg+FljDM2F7PrG16LjYUbE+SNcn/r7x5uwDsuvIf/M3ztiL8D0wQSW
TrqJVb024H+MUwgYykZnRoKf/w8YARxDvZH+CglBhL10u6rsTVU/xyLupQsC/W8W
6FkLqHHVU7h2nxfTLJa4L1IlKLoPAgMBAAGjWTBXMA4GA1UdDwEB/wQEAwICpDAP
BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQ/yNA8q920BRFw02LeiA78hlKMvjAV
BgNVHREEDjAMggprdWJlcm5ldGVzMA0GCSqGSIb3DQEBCwUAA4IBAQAprOdcWqnm
KQ8Iuw5hwQIe/MJqpl+fUvs7bfnCdjnodtEBJmtsp7mEsZB0HgYicCvwpO70OH3F
eWgs3tcn0+u6yOL4rMg1NpYpFT8uMYOVjqvmKz52Wg6h1NUWxzAkVRlnGtNwrhe+
k87t+HGltXX3Mz0QuQcIHj0QyQL10ub2g7OUZ1JtTrg1qJ9L/gmBW7EP/9w/JI6M
SxIfL3XY6ljSjyrf97OKGAOmke8b80r9/2b10xLCFQqgG+URJj1anIwtp/sr03un
vnUGrhki8gXY+EKUswB0Phr6aDLEXTjFM30jRVmFN0xO+oRx1133fPqp9TVp7OZp
Y8ilLSTk5LTt
-----END CERTIFICATE-----
[root@k8s-master-01 net.d]#

```
Finally, it was found that in a normal cluster, the server addresses of Calico and the currently problematic Calico are different. In the incorrect k8s, the Calico configuration file has an additional [] and the certificate authority data is missing double quotation marks。
Calico configuration in normal cluster state:
```
[root@k8s-master-1 ~]# cat /etc/cni/net.d/calico-kubeconfig
# Kubeconfig file for Calico CNI plugin. Installed by calico/node.
apiVersion: v1
kind: Config
clusters:
- name: local
  cluster:
    server: https://10.233.0.1:443
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJQ0hJajFVV05CMjR3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBeU1UUXdPRFU1TVRaYUZ3MHpOVEF5TVRJd09UQTBNVFphTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUMvSnVQTklmS1ZzR01DY2VFVmRFZzJ2cnNzbXBWbVUwMWRRTVJTZU1RQkphTmtOMlRqQkw3a0NJMmgKRmd1cFp6QnhNNGZXdkxsN0h1ZVRVRm5DRGxiSFFRMVA4VEZONy9YK3dLMWFhdWVOOXJxNkpKcTNkQldHUklNcApvMGZRV053MkpXbnA0MHZ5Y3pVYzBCcVJMejNZQUhKOTQ1MGNncDBnOUpUM3VVWXRWRGx4dld1K3Vzanp1c2hICnFlTWNzcksza2hjRWNBbklKZkU1SHVrbmlscU04S1Z5bHNTUFFrQkt4SXNqaCtHTmpENWhBa0pBcVJMV3pHVlcKM1AyYnYvemkvbDIyN0tWWW9WbVhvcHhweFJra253RjdXN3JiVW5ZYmJ2WjVVcVlkYXFEN1pkdUJQMTM1dFBKVAoyNXBKdzFBcHZNdnVuVXY1cjVDZkRUVHU2MFUxQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSVTZEZFlVbklaOGJnNWVRbTZSYUpLdFFMUHd6QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQXBpU3Z6VlBYbApSb1NmY3ZVNTE5ZU93UXpVVXpsRVUrY3ByRHhhdFU0U0pHMVJ5TEhROGUwM0xvc25YWWdHU0d4QjBqK25rM2VvCmE0ZUxtZGZTdkR0T04wVVdPNGl0RWV6aXI4ZzMxMjQwSjNCVCt6Wjc0UGlNZEcwRFdyT2JrTTJ0cjltMTJyYkoKUVhxQTJuUXFQQitrK2IwSFhmaE9kQVVlMzErcUYzMmg3b3ZmK0xaVmNVSXhoR3FrQmJYRURIdC96aGtSZ0hzLwpyTEp3TWRoMURuL2JmOWNQeGtHb2lMSUIwbUZicktLOWNVeWI3UmcrZGR6TEFXK0N1RVZuVVVJTCtIY01pK3puCjNDNm5uQVhOTDJORnFvZ1YwaUw4ZFNid2piMEFYWlpJak1ya3czb3l2UG90WDZrMXkyNzNyWDVCM0ZTR29IclcKNE9nMmRBQXFobFJGCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
users:
- name: calico
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjBoTXZGVkhZc3Y3RUNjWUQyNS1TNk0wSkpNTkpWRi1tc0V4cUdfbElPRFEifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzQ0NjY3NDEwLCJpYXQiOjE3NDQ1ODEwMTAsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsInNlcnZpY2VhY2NvdW50Ijp7Im5hbWUiOiJjYWxpY28tY25pLXBsdWdpbiIsInVpZCI6IjhlMGU3Y2ZlLTY4NzMtNDJkMC04NmRlLWUwZGE3OWIzNmJlYSJ9fSwibmJmIjoxNzQ0NTgxMDEwLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZS1zeXN0ZW06Y2FsaWNvLWNuaS1wbHVnaW4ifQ.aF4uVRcBsSSfiSM2H7O3eJSJDvfEsVBCVU7ZZ8ipl_-djVPfyJatbnggb-XQiHgn7jY0cX2vAjWsxx7jwZmLk-DnAoeAsQsLiE6HoYCy5yX2H32o_mK8_ibsaFwdbewrwCAg_iECqDcW1YxK7Qaexv9nqBHQErhL4Qb2-Z5BhdOuOs1LDWCXTwKEC96b5-pAEnAjkcigzxTOFMCoEvC7-tpij5NLnxq5wuucfwlt2-hcYhi9JJl8-jhUbEzkutqjr4kBXhkIKMGYKdsW0F8fi9KBTlmUHaucqycAENina4tE_IzFb83kD4QmjCLUUpi99Oxi5z4kWDlLIZMKMV3hqg
contexts:
- name: calico-context
  context:
    cluster: local
    user: calico
current-context: calico-context[root@k8s-master-1 ~]#

```
Calico configuration with incorrect cluster status:
```
[root@k8s-master-01 net.d]# cat calico-kubeconfig
# Kubeconfig file for Calico CNI plugin.
apiVersion: v1
kind: Config
clusters:
- name: local
  cluster:
    server: https://[10.233.0.1]:443
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJTXM3OTBQK1p2K2N3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBME1ET3MHpOVEEwTURFd09UTXhNek5hTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUQrbFFvZjFZbE9hVExrQnVtSUFHdU5WWjhTZU1zemNubFVXU2JEcGppOG9IQ0xWa3pQSmhClYVGxnT3F1dHl2OVY3S3BRNTVqQ1JiTEtqL3g3NWR0RTdVbnczVU02anlFcVJWanI0bUhZNVl5QnFRRQorWjFUS0IrL0p2bDdSdGZDTTBIS1FaaHpDWDFtTU14WHpqQVNxUWUzV1RxNmV3Y2k5UkV0MmRaMEFZR1ZLL2xvCkEyTWF0K0JBSHBlZytGbGpETTJGN1B1NOY24vcjd4NXV3RHN1dklmL00zenRpTDhEMHdRU1cKVHJxSlZiMDI0SCtNVXdnWXlrWm5Sb0tmL3c4WUFSeER2WkgrQ2dsQmhMMTB1NnJzVFZVL3h5THVwUXNDL1c4Vwo2RmtMcUhIVlU3aDJueGZUTEphNEwxSWxLTG9QQWdNQkFBR2pXVEJYTUE0R0ExVWREd0REFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRL3lOQThxOTIwQlJGdzAyTGVpQTc4aGxLTXZqQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQXByT2RjV3FubQpLUThJdXc1aHdRSWUvTiZm5DZGpub2R0RUJKbXRzcDdtRXNaQjBIZ1lpY0N2d3BPNzBPSDNGCmVXZ3MzdGNuMCt1NnlPTDRyTWcxTnBZcEZUOHVNWU9WanF2bUt6NTJXZzZoMU5VV3h6QWtWUmxuR3ROd3JoZSsKazg3dCtIR2x0WFgzTXowUXVRY0lIajBReVFMMTB1YjJnN09VWjFKdFRyc3RVAvOXcvSkk2TQpTeElmTDNYWTZsalNqeXJmOTdPS0dBT21rZThiODByOS8yYjEweExDRlFxZ0crVVJKajFhbkl3dHAvc3IwM3VuCnZuVUdyaGtpOGdYWStFS1Vzd0IwUGhyNmFETEVYVGpGTTMwalJWbUZOMHhPK29SeDExMzNmUHFwOVRWcDdPWnAKWThpbExS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
users:
- name: calico
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6ImF6NEUweHEyYVVkcndDWnBCR1FSWXg5WEFkdkkyY2dpc3V6TzBXLTByVUkifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzQ0NDQwOTMDQzNTQ1MzAsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsInNlcnZpY2VhY2NvdW50Ijp7Im5hbWUiOiJjYWxpY28tY25pLXBsdWdpbiNzQxNTRmLTM1MTctNDE2MC05OWJjLTEyYTBjMjQ1OWYzYyJ9fSwibmJmIjoxNzQ0MzU0NTMwLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZS1zeXN0ZW06Y2FsaWNvLWNuaS1wbHVnaW4ifQ.sKmm8WLjegKMdc24W_K9o2p01SNcE_-EBWK2KtJipVmXfAS8glpQRT25kv1RcKfe-dPQPLn4NuACy2jHQRQfidY189dTU93HVWp_Ls11SnfJ52ZQVkccw2m8H61VqiRghi0Knrine4P9I9MNz46VDFNPM-YAsfH4nnix807wV5G22irekbZoYQ4vrNF25N0jnp-SqcyauDv4wmImt-oxkC57HGFf06CDSCGjG96NXyk8V6RD0apazedBic7NYTS4l_NRXJ__QO2EdbUA4nHAdfdKfbrM6_mkmnp3NXb9_hMXN-sTHyTZRQ04VQ
contexts:
- name: calico-context
  context:
    cluster: local
    user: calico
current-context: calico-context
[root@k8s-master-01 net.d]#
```
