### ISSUE TITLE
Parsing value for FailsafeInboundHostPorts: "[]" (from environment variable) panic: runtime error: slice bounds out of range [:-1]

### ISSUE THREAD

**Issue by logabot** [projectcalico/calico#10338]
Try to set `FailsafeInboundHostPorts` and `FailsafeOutboundHostPorts` to empty list via environment variables. 

## Expected Behavior
FailsafeInboundHostPorts: []
FailsafeOutboundHostPorts: []

## Current Behavior
Pod had env:
```yaml
    - name: FELIX_FAILSAFEINBOUNDHOSTPORTS
       value: '[]'
    - name: FELIX_FAILSAFEOUTBOUNDHOSTPORTS
       value: '[]'
```
or 
```yaml
    - name: FELIX_FAILSAFEINBOUNDHOSTPORTS
       value: "'[]'"
    - name: FELIX_FAILSAFEOUTBOUNDHOSTPORTS
       value: "'[]'"
```
get error
```
2025-05-01 16:22:38.160 [INFO][25] tunnel-ip-allocator/config_params.go 695: Parsing value for FailsafeInboundHostPorts: [] (from environment variable)
panic: runtime error: slice bounds out of range [:-1]
```

## Steps to Reproduce (for bugs)
Kubespray:
1. Set 
  ```yaml
  calico_node_extra_envs:
    FELIX_FAILSAFEINBOUNDHOSTPORTS: "[]"
    FELIX_FAILSAFEOUTBOUNDHOSTPORTS: "[]"
  ```
2. deploy cluster

## Context
I try to disable all default port after cluster setup and globalNetworkPolicies applied 

## Your Environment
* Calico version 3.29.1
* Calico dataplane (iptables, windows etc.) iptables
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes via kubespray
* Operating System and version: Ubuntu 20.04
