### ISSUE TITLE
[Clarification] BGP in VXLAN mode

### ISSUE THREAD

**Issue by leleobhz** [projectcalico/calico#10337]
Calico documentation states VXLAN configured cluster does not need BGP to internal communication. But Calico supports serviceExternalIPs and serviceLoadBalancerIPs that needs to be announced if configured even if Calico runs in VXLAN mode. This behavior is not clear on documentation and in my cluster does not work - and I dont know if its a mistake made in configuration or a Calico issue.

## Expected Behavior
Running Calico with following objects must lead calico to use VXLAN/eBPF overlay/dataplane and announce serviceExternalIPs and serviceLoadBalancerIPs address to external BGP peer:

Installation:

```
cni:
  type: Calico
calicoNetwork:
  linuxDataplane: BPF
  bgp: Enabled
  ipPools:
  # ---- podCIDRv4 ---- #
  - cidr: 10.244.0.0/16
    name: podcidr-v4
    encapsulation: VXLANCrossSubnet
    natOutgoing: Enabled
  # ---- podCIDRv6 ---- #
  - cidr: fd00::/108
    name: podcidr-v6
    encapsulation: VXLANCrossSubnet
    natOutgoing: Enabled
  # ---- PureLBv4 ---- #
  - cidr: 192.168.50.0/24
    name: purelb-v4
    disableNewAllocations: true
  # ---- PureLBv6 ---- #
  - cidr: fd53:9ef0:8683:50::/120
    name: purelb-v6
    disableNewAllocations: true
  # ---- EOF ---- #
  nodeAddressAutodetectionV4:
    interface: "br0"
  nodeAddressAutodetectionV6:
    cidrs:
      - fc00:d33d:b112:50::0/124

```

BGPConfiguration:

```
apiVersion: crd.projectcalico.org/v1
kind: BGPConfiguration
metadata:
  name: default
spec:
  asNumber: 64524
  logSeverityScreen: debug
  serviceExternalIPs:
  - cidr: "fd53:9ef0:8683:50::/120"
  - cidr: "192.168.50.0/24"
  serviceLoadBalancerIPs:
  - cidr: "fd53:9ef0:8683:50::/120"
  - cidr: "192.168.50.0/24"
```

BGPPeers:

```
apiVersion: crd.projectcalico.org/v1
kind: BGPPeer
metadata:
  name: astra-v4
spec:
  sourceAddress: none
  peerIP: 192.168.42.1
  asNumber: 64524
---
apiVersion: crd.projectcalico.org/v1
kind: BGPPeer
metadata:
  name: astra-v6
spec:
  sourceAddress: none
  peerIP: fc00:d33d:b112:50::f
  asNumber: 64524
```

## Your Environment
* Calico version: v3.29.3
* Calico dataplane (iptables, windows etc.): eBPF
* Orchestrator version (e.g. kubernetes, mesos, rkt): v1.32.4+k0s
* Operating System and version: Linux 6.14.4-1-cachyos-server
