### ISSUE TITLE
Converting from iptables to nftables fails

### ISSUE THREAD

**Issue by frozenprocess** [projectcalico/calico#10348]
## Expected Behavior
In a cluster where users try to migrate from iptables or eBPF dataplane to nftables things should go smoothly, this is important since kuberentes 1.33 offers nftables as a GA option. 

## Current Behavior
Currently if you update your environment and kube-proxy then try to change Calico dataplane to nftables the operator will face an error which can't be fix.

Error
```
kubectl get tigerastatus calico -o yaml
apiVersion: operator.tigera.io/v1
kind: TigeraStatus
metadata:
  creationTimestamp: "2025-05-02T21:41:58Z"
  generation: 1
  name: calico
  resourceVersion: "3258"
  uid: a9059be0-10bb-4a28-ba4e-c33fee8e717d
spec: {}
status:
  conditions:
  - lastTransitionTime: "2025-05-02T21:56:38Z"
    message: 'Invalid Installation provided: spec.calicoNetwork.linuxPolicySetupTimeoutSeconds
      is supported only for the Iptables and BPF Linux dataplanes'
```

## Possible Solution
Operator should know that we want to migrate and skip the fact that an iptables/ebpf value is causing a problem.

```
kubectl patch installation.operator.tigera.io default --type merge -p '{"spec":{"calicoNetwork":{"linuxPolicySetupTimeoutSeconds":null}}}'
```
## Steps to Reproduce (for bugs)
Given that Kubernetes v1.33 has GA support for nftables some Calico users might want to convert from iptables to nftables. In such a case the operator will throw a tantrum and won't complete the transition.

## How to reproduce it
create a cluster
```
kind create cluster --config - <<EOF
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true
  kubeProxyMode: "nftables"
nodes:
- role: control-plane
- role: worker
EOF
```

```
kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.29.3/manifests/tigera-operator.yaml
```

```
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  # Configures Calico networking.
  calicoNetwork:
    ipPools:
    - name: default-ipv4-ippool
      blockSize: 26
      cidr: 10.244.0.0/16
      encapsulation: VXLANCrossSubnet
      natOutgoing: Enabled
      nodeSelector: all()
---
https://docs.tigera.io/calico/latest/reference/installation/api#operator.tigera.io/v1.APIServer
apiVersion: operator.tigera.io/v1
kind: APIServer
metadata:
  name: default
spec: {}
```

```
kubectl get tigerastatus
```

```
kubectl patch installation.operator.tigera.io default --type merge -p '{"spec":{"calicoNetwork":{"linuxDataplane":"Nftables"}}}'
```
watch operator roar!
```
kubectl get tigerastatus calico -o yaml
```

## Context
I enable Calico community users learn about cool things that Calico offfers and I was trying to convert an iptables cluster to nftables which resulted in a boom!

## Your Environment
* Calico version 3.29.
* Calico dataplane iptables -> nftables
* Orchestrator version Kubernetes v1.32.9
* Operating System and version: Fedora 42 atm
* Link to your project (optional): :D github.com/projectcaico/calico
