### ISSUE TITLE
Manage Calico Whisker integration with load balancer using Tigera Operator CRDs

### ISSUE THREAD

**Issue by ViliusS** [projectcalico/calico#10405]
Current default configuration of Calico Whisker allows it to be reachable only through port forwarding. If one wants to expose it through load balancer (let's say Ingress-NGINX) the network policies need to be adjusted, see https://github.com/orgs/projectcalico/discussions/10395.

It would be great if at least for Tigera Operator this could be controlled through CRDs. Something along the lines:
```
apiVersion: operator.tigera.io/v1
kind: Whisker
metadata:
  name: default
spec:
  ingress: true
  ingressMatch:
    podSelector:
      matchLabels:
        app.kubernetes.io/component: controller
        app.kubernetes.io/name: ingress-nginx
```

This would automatically adjust current Whisker network policy to allow traffic from load balancer to port 8081, or it could create additional managed network policy. Maybe it could be even automated without the need to specify ingress load balancer labels, I'm not sure.

Ideally CRD could be expanded to create Ingress object in addition to Network Policy. This would require to specify hostnames, TLS settings, ingressClassName and similar, so is more complicated, but managing all Kubernetes objects related to Calico would make sense.

Kubernetes Dashboard has similar options https://github.com/kubernetes/dashboard/blob/b0c1c0fa27602c5dfc496fbad4896bc6079ffd04/charts/kubernetes-dashboard/values.yaml#L103-L104. They use Helm though, but the idea is the same - to have fully managed parameters for integration with ingress load balancer.
