### ISSUE TITLE
Multiple GlobalNetworkPolicies are not additive

### ISSUE THREAD

**Issue by Markieta** [projectcalico/calico#10409]
With the following 2 GlobalNetworkPolicies with an overlapping selection, they do not work in union. Instead, one overrides the other. Is this intended behavior? I want most namespaces to have access to `kube-dns` but not all `egress`. Is there a better way to do this?

```YAML
---
apiVersion: crd.projectcalico.org/v1
kind: GlobalNetworkPolicy
metadata:
  name: base
spec:
  namespaceSelector: has(example)
  types:
    - Egress
  egress:
    - action: Allow
      protocol: UDPLite
      destination:
        namespaceSelector: projectcalico.org/name == "kube-system"
        selector: k8s-app == "kube-dns"
        ports:
          - 53
---
apiVersion: crd.projectcalico.org/v1
kind: GlobalNetworkPolicy
metadata:
  name: egress
spec:
  namespaceSelector: has(example)
  types:
    - Egress
  egress:
    - action: Allow
      protocol: TCP
      destination:
        nets:
          - 0.0.0.0/0
        ports:
          - 443
```
