### ISSUE TITLE
cannot access nodeport service from non pod running node

### ISSUE THREAD

**Issue by mosaicwang** [projectcalico/calico#10427]
## Expected Behavior

access nodeport service(skooner) from any node ip,include master node ip
## Current Behavior

only can access nodeport service from node ip which POD runs
## Possible Solution

after stop firewall,then can access nodeport service from any node ip
## Steps to Reproduce (for bugs)

1.kubeadm init 
2.kubectl apply -f calico.yaml
3.kubectl apply -f ingress-nginx-controller.yaml	# controller version v1.12.2
4.kuectl apply -f metrics-server.yaml	# metrics-server version v0.7.2
5.kubectl apply -f kubernetes-skooner-auth.yaml
6.kubectl apply -f kubernetes-skooner-nodeport.yaml
7.kubectl apply -f kubernetes-skooner-skooner.yaml

kubernetes-skooner-nodeport.yaml
```
kind: Service
apiVersion: v1
metadata:
  name: skooner-nodeport
  namespace: kube-system
spec:
  type: NodePort
  ports:
    - name: http
      port: 4654
      targetPort: 4654  
  selector:
    k8s-app: skooner
```

kubernetes-skooner-skooner.yaml
```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: skooner
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: skooner
  template:
    metadata:
      labels:
        k8s-app: skooner
    spec:
      containers:
      - name: skooner
        image: ghcr.io/skooner-k8s/skooner:stable
        ports:
        - containerPort: 4654
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /
            port: 4654
          initialDelaySeconds: 30
          timeoutSeconds: 30
      nodeSelector:
        'kubernetes.io/os': linux
```
kubectl get pod -A
```
NAMESPACE       NAME                                        READY   STATUS      RESTARTS       AGE
ingress-nginx   ingress-nginx-admission-create-hp7r2        0/1     Completed   0              129m
ingress-nginx   ingress-nginx-admission-patch-5ml2s         0/1     Completed   0              128m
ingress-nginx   ingress-nginx-controller-64c84dfdb8-bk7vt   1/1     Running     0              129m
kube-system     calico-kube-controllers-79949b87d-br5c4     1/1     Running     1 (130m ago)   142m
kube-system     calico-node-ch2sh                           1/1     Running     0              134m
kube-system     calico-node-mhzg5                           1/1     Running     1 (130m ago)   142m
kube-system     coredns-6766b7b6bb-j224x                    1/1     Running     1 (130m ago)   143m
kube-system     coredns-6766b7b6bb-wm2cl                    1/1     Running     1 (130m ago)   143m
kube-system     etcd-myserver1                              1/1     Running     1 (130m ago)   143m
kube-system     kube-apiserver-myserver1                    1/1     Running     1 (130m ago)   143m
kube-system     kube-controller-manager-myserver1           1/1     Running     1 (130m ago)   143m
kube-system     kube-proxy-92pf5                            1/1     Running     1 (130m ago)   143m
kube-system     kube-proxy-gng92                            1/1     Running     0              134m
kube-system     kube-scheduler-myserver1                    1/1     Running     1 (130m ago)   143m
kube-system     metrics-server-cc7c84c79-xbs4t              1/1     Running     0              129m
kube-system     skooner-5845c48d74-d95f4                    1/1     Running     0              128m
```
kubectl get svc -A
```
NAMESPACE       NAME                                 TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
default         kubernetes                           ClusterIP   10.96.0.1       <none>        443/TCP                      142m
ingress-nginx   ingress-nginx-controller             NodePort    10.111.91.51    <none>        80:32246/TCP,443:32416/TCP   127m
ingress-nginx   ingress-nginx-controller-admission   ClusterIP   10.99.132.210   <none>        443/TCP                      127m
kube-system     kube-dns                             ClusterIP   10.96.0.10      <none>        53/UDP,53/TCP,9153/TCP       142m
kube-system     metrics-server                       ClusterIP   10.99.198.205   <none>        443/TCP                      128m
kube-system     skooner                              ClusterIP   10.108.220.58   <none>        80/TCP                       127m
kube-system     skooner-nodeport                     NodePort    10.98.113.15    <none>        4654:32505/TCP               127m
```
----at master node----
```
curl -v 192.168.186.40:32505
*   Trying 192.168.186.40:32505...
* connect to 192.168.186.40 port 32505 failed: No route to host
* Failed to connect to 192.168.186.40 port 32505: No route to host
* Closing connection 0
curl: (7) Failed to connect to 192.168.186.40 port 32505: No route to host
```

---at worker node---
```
curl -v 192.168.186.41:32505
*   Trying 192.168.186.41:32505...
* Connected to 192.168.186.41 (192.168.186.41) port 32505 (#0)
> GET / HTTP/1.1
> Host: 192.168.186.41:32505
> User-Agent: curl/7.76.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Cache-Control: public, max-age=0
< Last-Modified: Wed, 13 Sep 2023 20:57:13 GMT
< ETag: W/"9ee-18a90557028"
< Content-Type: text/html; charset=UTF-8
< Content-Length: 2542
< Date: Sat, 17 May 2025 06:00:34 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
```

## Your Environment

- windows 10 + VMware workstation(2 VMs) with NAT
- OS : centos 9 stream (vm in VMworkstation)
- kernel : 5.14.0-522.el9.x86_64
- k8s ver : v1.32.4
- calico ver : v3.29.3
-  Calico dataplane : iptables

OS firewall :
- open port in public zone : 6443/tcp 10250/tcp 10259/tcp 10257/tcp 2379-2380/tcp 30000-32767/tcp 9099-9100/tcp 4789/udp 4799/udp
- trust source in trusted zone : 10.96.0.0/12 172.16.0.0/16

k8s cluster :
- master node : 192.168.186.40
- worker node : 192.168.186.41

K8s setting :
- podsubnet : 172.16.0.0/16

calico setting :
- calico_backend: "vxlan"	# enable vxlan,disable BGP
- CALICO_IPV4POOL_IPIP : Never	# disable IPIP
- CALICO_IPV4POOL_VXLAN : CrossSubnet
- CALICO_IPV4POOL_NAT_OUTGOING : true
- FELIX_VXLANPORT : 4799 # not default port for https://github.com/projectcalico/calico/issues/9433
