### ISSUE TITLE
Selectors aren't working for ingress source configuration

### ISSUE THREAD

**Issue by andrewmyhre** [projectcalico/calico#1044]
Applying a source selector to an ingress is failing to allow traffic by label.

## Expected Behavior
Take this network policy:
```
- apiVersion: v1
  kind: policy
  metadata:
    name: asv1.default-access
  spec:
    order: 800
    egress:
    - action: allow
      destination: {}
      source: {}
    ingress:
    - action: allow
      destination: {}
      source:
        selector: calico/k8s_ns == 'asv1'
    selector: calico/k8s_ns == 'asv1'
```
If pod 'A' and pod 'B' are both in the namespace 'asv1', pod B should allow traffic from pod A and vice versa.

## Current Behavior
Pods in the 'asv1' namespace don't allow traffic from one another. Some other source rules do allow traffic (detailed in steps to reproduce) but the `selector` rule does not.

## Steps to Reproduce (for bugs)
1. Provision a kubernetes cluster with calico as the overlay network. Configure calico to use the kubernetes etcd datastore.
1. Create a namespace 'asv1'
2. Create a calico policy to allow kube-system pods to talk to each other:
```
- apiVersion: v1
  kind: policy
  metadata:
    name: kube-system.allow-kube-system
  spec:
    egress:
    - action: allow
      destination: {}
      source: {}
    ingress:
    - action: allow
      destination: {}
      source: {}
    order: 1000
    selector: calico/k8s_ns == 'kube-system'
```
3. Create a policy to allow dns lookups
```
- apiVersion: v1
  kind: policy
  metadata:
    name: allow-dns
  spec:
    egress:
    - action: allow
      destination:
        ports:
        - 53
      protocol: udp
      source: {}
    order: 400
    selector: has(calico/k8s_ns)
```
4. Create an nginx deployment and service in the asv1 namespace
```
kubectl run -n asv1 nginx --image=alpine-nginx --replicas 2
kubectl expose -n asv1 deployment nginx --port 80
```
5. Create a busybox pod in the asv1 namespace
```
kubectl run --rm -it busybox -i busybox /bin/sh
```
6. You should be able to get the default page for the nginx service
```
wget -q --timeout=2 nginx -O -
```
(Should return html with "<h2>Website served by Nginx...")
7. Apply a calico network policy which only allows traffic from the namespace asv1
```
- apiVersion: v1
  kind: policy
  metadata:
    name: asv1.default-access
  spec:
    order: 800
    egress:
    - action: allow
      destination: {}
      source: {}
    ingress:
    - action: allow
      destination: {}
      source:
        selector: calico/k8s_ns == 'asv1'
    selector: calico/k8s_ns == 'asv1'
```
8. Repeat steps 5 & 6. This time you'll see:
`wget: download timed out`
9. Update the network policy to allow requests by cidr:
- apiVersion: v1
  kind: policy
  metadata:
    name: asv1.default-access
  spec:
    order: 800
    egress:
    - action: allow
      destination: {}
      source: {}
    ingress:
    - action: allow
      destination: {}
      source:
        nets: 0.0.0.0/0
    selector: calico/k8s_ns == 'asv1'
```
Repeat steps 5 & 6 and you'll get good responses
9. Update the network policy to allow requests from the cluster ip of the nginx *service*. Repeat steps 5 & 6 and you'll get failures.
10. Update the network policy to allow requests from the cluster ip of one the nginx *pods*. Repeat steps 5 & 6 and you'll get good responses. 
11. Update the network policy to remove the select (`source: {}`) and you'll get good responses.

(I find it easier to leave a busybox shell session open with this command running:
`while true; do echo $(date); wget -q --timeout=1 10.200.18.68 -O
 -; sleep 1; done`)

## Context
I'm trying to set up a kubernetes cluster for multi-tenancy where all namespaces by default deny all ingress and egress with other namespaces (with some exceptions like cluster dns lookups) and I can explicitly allow communication between namespaces by creating ingress and egress rules on the respective namespaces. I'm starting at the beginning so in this case I'm just trying to implement a policy where pods within the namespace 'asv1' are able to communicate with each other as normal but the namespace is their entire world.

The ingress source selector is failing to allow traffic by any method other than CIDR, which is only matching on the pod IP.

## Your Environment
* Calico version: v2.4.1
* Orchestrator version: kubernetes 1.7.4
* Operating System and version: Ubuntu 14.04

**Comment by tmjd** [comment]
Previously in slack you confirmed that you were using Calico v2.4 but you've listed Calico version: 1.5.6 (which as best as I can tell would be the CNI plugin from Calico v2.0.2).
If you are using an older version could you please upgrade and try what you are attempting again.
Thanks.

**Comment by andrewmyhre** [comment]
I was mistaken, I'm running v2.4.1. I've updated the report

**Comment by andrewmyhre** [comment]
Output of `calicoctl get weps -o yaml`
```
- apiVersion: v1
  kind: workloadEndpoint
  metadata:
    activeInstanceID: 3cde4c3106ead51481430bd1971dfe1564e6ecd0b8a47c211001b4c0e7801636
    labels:
      calico/k8s_ns: kube-system
      k8s-app: kube-dns-autoscaler
      pod-template-hash: "2704840207"
    name: eth0
    node: ip-10-205-84-186
    orchestrator: k8s
    workload: kube-system.kube-dns-autoscaler-2704840207-4ggx0
  spec:
    interfaceName: calif4ee23bf796
    ipNetworks:
    - 10.200.57.1/32
    mac: e2:c8:61:b4:53:99
    profiles:
    - k8s_ns.kube-system
- apiVersion: v1
  kind: workloadEndpoint
  metadata:
    activeInstanceID: 348d8664d909175e16cd4a319827fd60a3ae8e008b505a0c4a7c059f29b57572
    labels:
      app: kubernetes-dashboard
      calico/k8s_ns: kube-system
      pod-template-hash: "4214572558"
    name: eth0
    node: ip-10-205-84-186
    orchestrator: k8s
    workload: kube-system.kubernetes-dashboard-4214572558-bbpq8
  spec:
    interfaceName: calia703dae43c6
    ipNetworks:
    - 10.200.57.2/32
    mac: 1e:16:47:25:19:1c
    profiles:
    - k8s_ns.kube-system
- apiVersion: v1
  kind: workloadEndpoint
  metadata:
    activeInstanceID: c83b8b700bad2205e273f81e3faced60ae89bb4ce81dc87f38aac9c2e4c56b42
    labels:
      calico/k8s_ns: asv1
      pod-template-hash: "30724775"
      run: nginx
    name: eth0
    node: ip-10-205-86-251
    orchestrator: k8s
    workload: asv1.nginx-30724775-bvt1l
  spec:
    interfaceName: cali006493e1bba
    ipNetworks:
    - 10.200.18.68/32
    mac: a6:5f:fa:20:47:7e
    profiles:
    - k8s_ns.asv1
- apiVersion: v1
  kind: workloadEndpoint
  metadata:
    activeInstanceID: 366a2bcdc5de737d0b9959011f3b971d8d137653ba0db9086a67e872e0206e78
    labels:
      calico/k8s_ns: default
      k8s-app: default-http-backend
      pod-template-hash: "3793308053"
    name: eth0
    node: ip-10-205-86-251
    orchestrator: k8s
    workload: default.default-http-backend-3793308053-df3n6
  spec:
    interfaceName: cali50e81c08cf3
    ipNetworks:
    - 10.200.18.65/32
    mac: 5a:f7:3b:8b:1e:b3
    profiles:
    - k8s_ns.default
- apiVersion: v1
  kind: workloadEndpoint
  metadata:
    activeInstanceID: 93bf618b5fb3943b6411a0fb2cfca25787400b9d3239852bcb2b661427211010
    labels:
      calico/k8s_ns: kube-system
      k8s-app: kube-dns
      pod-template-hash: "1216661399"
    name: eth0
    node: ip-10-205-92-238
    orchestrator: k8s
    workload: kube-system.kube-dns-1216661399-6n3d9
  spec:
    interfaceName: cali472e74caa1b
    ipNetworks:
    - 10.200.55.65/32
    mac: ca:85:30:5b:de:68
    profiles:
    - k8s_ns.kube-system
- apiVersion: v1
  kind: workloadEndpoint
  metadata:
    activeInstanceID: 0b37190afe67d376cd402fb1df04bbabf900ad70fc183c1e0b449a38e9075a49
    labels:
      calico/k8s_ns: asv1
      pod-template-hash: "30724775"
      run: nginx
    name: eth0
    node: ip-10-205-93-46
    orchestrator: k8s
    workload: asv1.nginx-30724775-cvfgf
  spec:
    interfaceName: cali9e5f8666c4c
    ipNetworks:
    - 10.200.96.69/32
    mac: 76:ab:f3:97:56:80
    profiles:
    - k8s_ns.asv1
- apiVersion: v1
  kind: workloadEndpoint
  metadata:
    activeInstanceID: 26d4c31df7ca544c915d69bb950c013dcb26a61601b919490733e552983c744d
    labels:
      calico/k8s_ns: kube-system
      k8s-app: nginx-ingress-controller
      pod-template-hash: "1142157752"
    name: eth0
    node: ip-10-205-93-46
    orchestrator: k8s
    workload: kube-system.nginx-ingress-controller-1142157752-pj0cq
  spec:
    interfaceName: cali591eef9db8e
    ipNetworks:
    - 10.200.96.65/32
    mac: 2a:50:55:0b:c3:59
    profiles:
    - k8s_ns.kube-system
- apiVersion: v1
  kind: workloadEndpoint
  metadata:
    activeInstanceID: 7bafb8290648753a6b182196b4636175c03443a233e23e4c088de2ae7825497a
    labels:
      calico/k8s_ns: asv1
      pod-template-hash: "1415667276"
      run: access
    name: eth0
    node: ip-10-205-95-23
    orchestrator: k8s
    workload: asv1.access-1415667276-qgzsr
  spec:
    interfaceName: calif79a5445bb8
    ipNetworks:
    - 10.200.201.199/32
    mac: 9a:8b:68:92:30:b6
    profiles:
    - k8s_ns.asv1
- apiVersion: v1
  kind: workloadEndpoint
  metadata:
    activeInstanceID: 2d6ebd132ef09a7ca882bde914b45510cb857f48d2c33d2f330cc11945ef8063
    labels:
      calico/k8s_ns: kube-system
      k8s-app: kube-dns
      pod-template-hash: "1216661399"
    name: eth0
    node: ip-10-205-95-82
    orchestrator: k8s
    workload: kube-system.kube-dns-1216661399-8fxz6
  spec:
    interfaceName: cali691a05604ae
    ipNetworks:
    - 10.200.210.1/32
    mac: 3a:c0:e4:f0:34:de
    profiles:
    - k8s_ns.kube-system
```

**Comment by andrewmyhre** [comment]
Output of `calicoctl get policies -o yaml`

```
- apiVersion: v1
  kind: policy
  metadata:
    name: allow-dns
  spec:
    egress:
    - action: allow
      destination:
        ports:
        - 53
      protocol: udp
      source: {}
    order: 400
    selector: has(calico/k8s_ns)
- apiVersion: v1
  kind: policy
  metadata:
    name: asv1.default-access
  spec:
    egress:
    - action: allow
      destination: {}
      source: {}
    ingress:
    - action: allow
      destination: {}
      source: {}
    order: 800
    selector: calico/k8s_ns == 'asv1'
- apiVersion: v1
  kind: policy
  metadata:
    name: asv2.default-access
  spec:
    egress:
    - action: allow
      destination:
        selector: calico/k8s_ns == 'asv1'
      source: {}
    ingress:
    - action: allow
      destination: {}
      source: {}
    order: 800
    selector: calico/k8s_ns == 'asv2'
- apiVersion: v1
  kind: policy
  metadata:
    name: kube-system.allow-kube-system
  spec:
    egress:
    - action: allow
      destination: {}
      source: {}
    ingress:
    - action: allow
      destination: {}
      source: {}
    order: 1000
    selector: calico/k8s_ns == 'kube-system'
```
