### ISSUE TITLE
Role Biding and Secret access issue in Calico V0.30.0 and V0.30.1

### ISSUE THREAD

**Issue by valereColleville** [projectcalico/calico#10507]
In the chart version 0.30 and above, a secret retrieval system has been added but the role binding is not targeting the correct service account.

## Expected Behavior
No error on the log for secret access and reconciliation.

## Current Behavior
A lot off error in reconciliation system around access a secret
```{"level":"error","ts":"2025-06-04T08:41:40Z","logger":"controller_installation",
"msg":"Failed to create or update object",
"component":"*certificatemanagement.component",
"key":{"name":"node-certs","namespace":"calico-cni"},
"error":"secrets \"node-certs\" is forbidden: User \"system:serviceaccount:calico-cni:tigera-operator\" 
cannot update resource \"secrets\" in API group \"\" in the namespace \"calico-cni\"",
"stacktrace":"github.com/tigera/operator/pkg/controller/utils.(*componentHandler).CreateOrUpdateOrDelete\n\t/go/src/github.com/tigera/operator/pkg/controller/utils/component.go:347\ngithub.com/tigera/operator/pkg/controller/installation.(*ReconcileInstallation).Reconcile\n\t/go/src/github.com/tigera/operator/pkg/controller/installation/core_controller.go:1499\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.2/pkg/internal/controller/controller.go:118\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.2/pkg/internal/controller/controller.go:328\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.2/pkg/internal/controller/controller.go:288\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.2/pkg/internal/controller/controller.go:249"}
```

## Possible Solution
Correct the 

## Steps to Reproduce (for bugs)

1. Install calico version 0.29.3
2. Upgrade to 0.30.0 
3. Operator start failing reconciliation
4.

## Context
Bypassed by adding a custom role biding outside official chart, but would be better having it corrected.

## Your Environment

* Calico version : 0.30.0
* Calico dataplane (iptables, windows etc.) : Policy-Only
* Orchestrator version (e.g. kubernetes, mesos, rkt): EKS v1.31

Issue seems to be on that file: 
charts/tigera-operator/templates/tigera-operator/02-rolebinding-tigera-operator-secrets.yaml
````
subjects:
  - kind: ServiceAccount
    name: {{.Release.Namespace}}
    namespace: {{.Release.Namespace}}
```
But the service account affected to tigera-operator is : 
```
metadata:
  name: tigera-operator
  namespace: {{.Release.Namespace}}
````

So the rolebiding doesn't map correctly (at least to my understanding)

Thanks!

**Comment by valereColleville** [comment]
I can also add that some issues comes from the attempt to access secret inside the other namespace (the one generated by the helm calico-system). 
So complete workaround for me was to add 2 Roles: 
````
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tigera-operator-secrets-correct
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: tigera-operator
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: tigera-operator-secrets
  apiGroup: rbac.authorization.k8s.io

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tigera-operator-secrets-system-correct
  namespace: calico-system
subjects:
  - kind: ServiceAccount
    name: tigera-operator
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: tigera-operator-secrets
  apiGroup: rbac.authorization.k8s.io

````

But would be better to have them included in the chart if possible.
