### ISSUE TITLE
Using ip pool annotations on namespaces and node selectors within the ip pools

### ISSUE THREAD

**Issue by bshekar2191** [projectcalico/calico#10502]
When IP Pool annotation is used in namespaces using "[cni.projectcalico.org/ipv6pools"='["pool-amer-west", "pool-amer-east"]], and the pool-amer-west ippool has a nodeSelector set to match 'AMER-WEST' nodes and pool-amer-east ippool has a nodeSelector set to match 'AMER-EAST nodes', Calico/ K8s is allocating IPs from either pools in both regions. 
No vulnerability

## Expected Behavior
I was hoping that Calico understands that this namespace can use both IP Pools based on the annotation and then look at the node selector on each IP Pool and use that pool accordingly in Amer East or Amer West

## Current Behavior
It is using the same pool (pool-amer-west) in all the nodes for that namespace

## Possible Solution
Perhaps allow us to use both namespace annotations and ip pool node selectors together to finally choose which ippool to use

## Steps to Reproduce (for bugs)
This is perhaps not a bug

## Context
Here's what I'm trying to achieve: 
I have two regions  : AMER-EAST and AMER-WEST and they're using separate IP blocks for addressing (10.10.0.0/16 for AMER-EAST and 10.20.0.0/16 for AMER-WEST )
In addition, I want to do IP Pool per namespace for security.
Example: NS1 should use IP Pool 1 (CIDR 10.10.0.0/24 with node selector AMER-EAST ) in AMER-EAST nodes and IP Pool 2 (CIDR 10.20.0.0/24 with node selector AMER-WEST) in AMER-WEST nodes
Likewise NS2  should use IP Pool 3 (CIDR 10.10.1.0/24 with node selector AMER-EAST ) in AMER-EAST nodes and IP Pool 4 (CIDR 10.20.1.0/24 with node selector AMER-WEST) in AMER-WEST nodes
Is that possible with calico? Or do you have any other suggestions/ creative solutions?

## Your Environment

* Calico version : Calico Open Source - Latest
* Calico dataplane (iptables, windows etc.)
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes 1.32
* Operating System and version: Linux
* Link to your project (optional):

**Comment by stevegaossou** [comment]
Hi @bshekar2191, as you alluded to in the description of this issue, this behaviour is not a bug.  

Currently, you can only use the [per-namespace annotation](https://docs.tigera.io/calico/latest/reference/configure-cni-plugins#specifying-ip-pools-on-a-per-namespace-or-per-pod-basis) and the [IP pool node selector](https://docs.tigera.io/calico/latest/reference/configure-cni-plugins#using-ip-pools-node-selectors) mechanisms independently from each other. Combining these two mechanisms together (i.e. "use one of these IP pools, depending on which node you land on") is not something that is supported right now. 

However, this is something that would be nice-to-have. So if someone wants to submit a PR, please do. 

One note, before anyone writes any code, we should decide on what the API / config model would be and how it would interact with existing options. We can open this up for discussion on this issue.

**Comment by PersistentJZH** [comment]
Hi @stevegaossou @bshekar2191, I want to try this，before I start code, maybe we can have a discussion first. I wrote a proposal below, and we can discuss based on this proposal.

**1. Core Issue**
When Calico IPAM encountered IP pools specified by namespace annotations, it unconditionally used those pools, completely ignoring each pool's nodeSelector. This prevented intelligent IP allocation based on node location.

**2. Solution**
Consider modifying the [determinePools function](https://github.com/projectcalico/calico/blob/master/libcalico-go/lib/ipam/ipam.go#L303C1-L304C1) to add node-aware pool selection logic. can add a configuration option, `EnableNodeAwareSelection=true/false`, to control pool selection behavior.

**3. Example:**

### 1. Create IP Pools

```yaml
# Create NS1 IP Pools
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: pool-ns1-east
spec:
  cidr: 10.10.0.0/24
  nodeSelector: region == "AMER-EAST"
  blockSize: 26
  natOutgoing: true
  ipipMode: CrossSubnet
  vxlanMode: Never
  # enable node aware selection
  enableNodeAwareSelection: true
---
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: pool-ns1-west
spec:
  cidr: 10.20.0.0/24
  nodeSelector: region == "AMER-WEST"
  blockSize: 26
  natOutgoing: true
  ipipMode: CrossSubnet
  vxlanMode: Never
  # enable node aware selection
  enableNodeAwareSelection: true
---
# Create NS2 IP Pools
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: pool-ns2-east
spec:
  cidr: 10.10.1.0/24
  nodeSelector: region == "AMER-EAST"
  blockSize: 26
  natOutgoing: true
  ipipMode: CrossSubnet
  vxlanMode: Never
  # enable node aware selection
  enableNodeAwareSelection: true
---
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: pool-ns2-west
spec:
  cidr: 10.20.1.0/24
  nodeSelector: region == "AMER-WEST"
  blockSize: 26
  natOutgoing: true
  ipipMode: CrossSubnet
  vxlanMode: Never
  # enable node aware selection
  enableNodeAwareSelection: true

```

### 2. Create NS

```yaml
# NS1
apiVersion: v1
kind: Namespace
metadata:
  name: ns1
  annotations:
    cni.projectcalico.org/ipv4pools: '["pool-ns1-east", "pool-ns1-west"]'
---
# NS2
apiVersion: v1
kind: Namespace
metadata:
  name: ns2
  annotations:
    cni.projectcalico.org/ipv4pools: '["pool-ns2-east", "pool-ns2-west"]'

```

### 3. Expected results

```
=== IP allocation results ===
NS1 Pods:
10.10.0.5 (AMER-EAST)  ← from pool-ns1-east (10.10.0.0/24)
10.20.0.5 (AMER-WEST)  ← from pool-ns1-west (10.20.0.0/24)

NS2 Pods:
10.10.1.5 (AMER-EAST)  ← from pool-ns2-east (10.10.1.0/24)
10.20.1.5 (AMER-WEST)  ← from pool-ns2-west (10.20.1.0/24)

```

Note:

1. When EnableNodeAwareSelection=false, pool selection behavior remains the same as it is now, which improves compatibility.
2. Perhaps could also consider enabling this feature via an environment variable (e.g., CALICO_NODE_AWARE_POOL_SELECTION=true)?

**Comment by bshekar2191** [comment]
I love it, in order to avoid backwards compatibility and to not break other deployments, perhaps we can set EnableNodeAwareSelection=false by default and only enable it when needed?

**Comment by PersistentJZH** [comment]
> I love it, in order to avoid backwards compatibility and to not break other deployments, perhaps we can set EnableNodeAwareSelection=false by default and only enable it when needed?

yes, it should be like this

**Comment by caseydavenport** [comment]
```yaml
# Create NS1 IP Pools
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: pool-ns1-east
spec:
  cidr: 10.10.0.0/24
  nodeSelector: region == "AMER-EAST"
  namespaceSelector: ns == "one"
```

One other potential option to discuss would be to introduce a new `namespaceSelector` field within the IP pool itself - this way, the definition of where this pool applies would be in a singular place. The `nodeSelector` and `namespaceSelector` could be combined with a logical `AND`, and since it's a new field it would be backwards compatible by default (i.e., empty means current behavior).

In either configuration model, we would need / want to define what happens in the case of one IP pool with both nodeSelector and namespaceSelector, and another IP pool that only has one of the two.

For example, if you have two IP pools with nodeSelectors in namespace NS1 and one IP pool with no node selector in pool NS1, should the third pool ever be used? I would assume it would only be used on nodes that don't match any other node selector?

**Comment by bshekar2191** [comment]
> # Create NS1 IP Pools
> apiVersion: projectcalico.org/v3
> kind: IPPool
> metadata:
>   name: pool-ns1-east
> spec:
>   cidr: 10.10.0.0/24
>   nodeSelector: region == "AMER-EAST"
>   namespaceSelector: ns == "one"
> One other potential option to discuss would be to introduce a new `namespaceSelector` field within the IP pool itself - this way, the definition of where this pool applies would be in a singular place. The `nodeSelector` and `namespaceSelector` could be combined with a logical `AND`, and since it's a new field it would be backwards compatible by default (i.e., empty means current behavior).
> 
> In either configuration model, we would need / want to define what happens in the case of one IP pool with both nodeSelector and namespaceSelector, and another IP pool that only has one of the two.
> 
> For example, if you have two IP pools with nodeSelectors in namespace NS1 and one IP pool with no node selector in pool NS1, should the third pool ever be used? I would assume it would only be used on nodes that don't match any other node selector?

This is the kinda solution that metallb cni uses by the way. In this solution, do you mean we skip annotating the namespace with an IP pool altogether and control everything from the IP Pool config? By extension, do you mean we keep today's behavior where when we do annotate a namespace with an IP pool it will still ignore the ippool selectors (both node Selector and namespace Selector? )
With regards to your other question, yes, your solution seems good. Here's an example: 
Lets say Pool1 has nodeSelector: region=Amer-West and namespaceSelector: ns=NS1 
and Pool2 has only namespaceSelector: ns=NS1,
Then, Pool1 will be used for pods scheduled for NS1 on only the nodes that have label region=Amer-West and 
Pool2 will be used for pods scheduled for NS1 on all other nodes in the cluster. 

@caseydavenport @PersistentJZH  I feel either solution works well for this problem. But the question about keeping/ overriding the namespace annotation unconditional application remains.

**Comment by caseydavenport** [comment]
> This is the kinda solution that metallb cni uses by the way. In this solution, do you mean we skip annotating the namespace with an IP pool altogether and control everything from the IP Pool config? By extension, do you mean we keep today's behavior where when we do annotate a namespace with an IP pool it will still ignore the ippool selectors (both node Selector and namespace Selector? )

Yeah, this is exactly what I was thinking. I like that it doesn't change the behavior of the namespace annotation, as I think it's a bit confusing to have the same configuration behave different ways based on another field.

So, if you wanted the behavior you're describing, you'd simply opt-out of the Namespace annotation altogether.

**Comment by PersistentJZH** [comment]
@caseydavenport @bshekar2191 
yes, I think introducing the **namespaceSelector** field is a better solution. It can be used alongside the **nodeSelector** field, making the configuration more concise and clear and as @caseydavenport  said : the definition of where this pool applies would be in a singular place.

one thing that needs to be determined first is: Shouldn't we introduce both the **namespaceSelector** and **EnableNodeAwareSelection** fields? Perhaps only the **namespaceSelector** field is needed? 


If only the **namespaceSelector** field is introduced, we should discuss how the new field affects the behavior of pool select. We can discuss based on the following configuration model: 




```yaml
# pool east prod
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: pool-east-prod
spec:
  cidr: 10.0.0.0/24
  nodeSelector: "region == east"
  namespaceSelector: "env == prod"

#pool west prod
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: pool-west-prod
spec:
  cidr: 10.1.0.0/24
  nodeSelector: "region == west"
  namespaceSelector: "env == prod"

# pool west
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: pool-west
spec:
  cidr: 10.2.0.0/24
  nodeSelector: "region == west"
  
# pool east
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: pool-east
spec:
  cidr: 10.3.0.0/24
  nodeSelector: "region == east"
  
# pool prod
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: pool-prod
spec:
  cidr: 10.4.0.0/24
  namespaceSelector: "env == prod"
  
  
# pool dev
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: pool-dev
spec:
  cidr: 10.5.0.0/24
  namespaceSelector: "env == dev"
  
  
# pool global
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: pool-global
spec:
  cidr: 10.6.0.0/24
  
  
---
# ns prod
apiVersion: v1
kind: Namespace
metadata:
  name: prod-app
  labels:
    env: prod
  annotations:
    cni.projectcalico.org/ipv4pools: '["pool-east-prod", "pool-west-prod","pool-east","pool-west"]'

---

# node west
apiVersion: v1
kind: Node
metadata:
  name: node-west
  labels:
    region: west

---
# pod west
apiVersion: v1
kind: Pod
metadata:
  name: west-prod-pod
  namespace: prod-app
spec:
  nodeName: node-west
  containers:
  - name: app
    image: nginx

```

do you think 
west-prod-pod will get ip from **[pool-west-prod,pool-west]** ? (not backwards compatible)
or
west-prod-pod will get ip from **[pool-west-prod,pool-west,pool-east]** ? (backwards compatible)
or 
west-prod-pod will get ip from **[pool-west-prod]** ?
or are there other options?
