### ISSUE TITLE
TLS handshake problem between calico-node and goldmane pods

### ISSUE THREAD

**Issue by Sabo-kun** [projectcalico/calico#10522]
I have installed calico networking by means of the tigera-operator helm chart.

In the latest upgrade, version v3.30.1 was installed, enabling Whisker and Goldmane for observability (great improvement!).

I am experiencing TLS handshake errors from calico-node pods to goldmane with the default configuration (no custom certificates are used).

Here's a sample of error logs:

```
W0605 13:33:52.279436      62 logging.go:55] [core] [Channel #1 SubChannel #2]grpc: addrConn.createTransport failed to connect to {Addr: "[172.20.53.137:7443](http://172.20.53.137:7443/)", ServerName: "goldmane.calico-system.svc:7443", }. Err: connection error: desc = "error reading server preface: remote error: tls: certificate required"
```

## Expected Behavior

The communication should already be configured by the tigera operator to use a client certificates, since the Goldmane server is requiring it

## Current Behavior

TLS handshake error prevents metrics from being sent, then they cannot be seen in Whisker 

## Steps to Reproduce (for bugs)

Before to upgrade, the CRDs were upgraded with the command reported in the official documentation:
kubectl apply --server-side --force-conflicts -f https://raw.githubusercontent.com/projectcalico/calico/v3.30.1/manifests/operator-crds.yaml

helm upgrade calico  projectcalico/tigera-operator --version v3.30.1 --values ./values.yaml -n tigera-operator

This is the values file I used:

```
installation:
  enabled: true
  registry: XXX.dkr.ecr.eu-west-1.amazonaws.com/
  imagePath: docker-hub/calico

tigeraOperator:
  image: quay/tigera/operator
  registry: XXX.dkr.ecr.eu-west-1.amazonaws.com
calicoctl:
  image: docker-hub/calico/ctl

goldmane:
  enabled: true

whisker:
  enabled: true

defaultFelixConfiguration:
  enabled: false
```

Everything is configured and apparently working (at least according to the pod state). Unfortunately, I noticed the following errors:
```
W0605 13:33:52.279436      62 logging.go:55] [core] [Channel #1 SubChannel #2]grpc: addrConn.createTransport failed to connect to {Addr: "[172.20.53.137:7443](http://172.20.53.137:7443/)", ServerName: "goldmane.calico-system.svc:7443", }. Err: connection error: desc = "error reading server preface: remote error: tls: certificate required"
```

From the calico-node trying to export flow logs to Goldmane

Therefore, when I access Whisker UI no data is shown

I confirmed (with an ephemeral container attached to calico-node pod and running openssl s_client command) that the Goldmane server is reachable and that it is actually requiring a client certificate

## Your Environment
* Calico version v3.30.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes (EKS)
* Operating System and version: Bottlerocket-based AMI
