### ISSUE TITLE
Calico 3.30 fails to establish network due to failure to reach service IPs

### ISSUE THREAD

**Issue by phoerious** [projectcalico/calico#10582]
Perhaps this is just me being unable to configure Calico correctly, but after upgrading to 3.30 I couldn't get any network connection in any new pod not running in host network mode.

I have kube-proxy configured in nftables mode (previously iptables mode) and it manages services IPs in the range 10.42.0.0/16. Calico manages pod IPs in the range 10.23.0.0/16 (that's my one and only IPPool) with IPIP encapsulation.

On the host and in pods that were already running before the upgrade, I can reach the 10.42.x.x service IPs. I can also reach any existing 10.23.x.x pod IPs, but not any for newly created pods. Inside the new pod, I cannot talk to anything that doesn't run on the same host.

Here's what I could find out trying to debug this:

- `ip route get 10.23.x.x` inside a pod gives me a 169.254.1.1 link-local hop (which is expected according to the docs).
- On startup, the Goldmane pods tries to reach the kube-apiserver via its internal 10.42.0.1 service IP, which fails.
- The calico-node containers try to reach the Goldmane pod via its 10.42.x.x service IP, which fails as well.
- Only the the calico-node running on the same host can reach Goldmane.
- Manually cleaning up the caliXXX and tunl0 interfaces doesn't change anything.
- Killing the kube-proxy services and switching to eBPF mode doesn't change anything either (10.42.x.x still unreachable).

For the time being, I downgraded back to Calico 3.29, which works.

Here's my tigera-operator Helm values.yaml:

```yaml
installation:
  enabled: true
  kubernetesProvider: ''
  cni:
    type: Calico
  calicoNetwork:
    # BPF is preferred, since it makes kube-proxy obsolete,
    # but it is incompatible with Docker port forwardings.
    linuxDataplane: Nftables
    #linuxDataplane: BPF
    bgp: Enabled
    mtu: 8980
    nodeAddressAutodetectionV4:
      canReach: 1.1.1.1
    ipPools:
      - cidr: 10.23.0.0/16
        blockSize: 26
        encapsulation: IPIP
        nodeSelector: all()
  # Pull explicitly from registry-1 to avoid chicken-egg problems
  # with our docker.io pull-through cache.
  registry: docker.io.passthrough.local

goldmane:
  enabled: true
whisker:
  enabled: true
defaultFelixConfiguration:
  enabled: true
  # Checksum offloading broken with our NICs (couldn't find any real fix)
  featureDetectOverride: "ChecksumOffloadBroken=true"
  # Not exactly sure what this does, but setting it to Enabled doesn't change anything
  nftablesMode: Disabled

priorityClassName: system-node-critical
apiServer:
  enabled: false
```

## Your Environment

* Calico version 3.30 (installed via tigera-operator Helm chart)
* Calico dataplane nftables (but same with iptables)
* Orchestrator version Kubernetes 1.32.5:
* Operating System and version: Ubuntu 22.04/24.04
