### ISSUE TITLE
Should kubernetes master  run calico?

### ISSUE THREAD

**Issue by TracyBin** [projectcalico/calico#1096]
hi, all
    I deployed the k8s high availability environment based on the centos version script provided by the community. The environment information is as follows
```
10.12.2.227 master-1
10.12.2.228 master-2
10.12.2.229 master-3
10.12.2.225 node-1
10.12.2.226 node-2

kubelet version 1.6.6
docker 1.13.1
calico/node image 2.5.0 [https://docs.projectcalico.org/v2.5/getting-started/kubernetes/installation/hosted/hosted](url) 
```
And everything seems to be right.
```
Every 5.0s:  sudo local/bin/kubectl get pods,services --all-namespaces -o wide                                                                                                                                                        Fri Sep  8 23:31:23 2017

NAMESPACE     NAME                                           READY     STATUS    RESTARTS   AGE       IP               NODE
kube-system   po/calico-node-1b8h1                           2/2       Running   0          4h        10.12.2.226      node-2
kube-system   po/calico-node-26hz5                           2/2       Running   0          4h        10.12.2.225      node-1
kube-system   po/calico-policy-controller-1746561077-2k7s5   1/1       Running   0          4h        10.12.2.226      node-2
kube-system   po/heapster-2929994463-gv0lh                   1/1       Running   0          4h        192.168.84.130   node-1
kube-system   po/kube-dns-3119898146-122xx                   3/3       Running   0          4h        192.168.247.1    node-2
kube-system   po/kubernetes-dashboard-908585402-21pch        1/1       Running   0          4h        192.168.84.129   node-1
kube-system   po/monitoring-influxdb-3324367400-91j14        1/1       Running   0          4h        192.168.247.2    node-2

NAMESPACE     NAME                       CLUSTER-IP	  EXTERNAL-IP   PORT(S)         AGE	  SELECTOR
default       svc/kubernetes             10.254.0.1	  <none>        443/TCP         4h        <none>
kube-system   svc/heapster               10.254.102.37    <none>        80/TCP          4h        k8s-app=heapster
kube-system   svc/kube-dns               10.254.0.2	  <none>        53/UDP,53/TCP   4h        k8s-app=kube-dns
kube-system   svc/kubernetes-dashboard   10.254.88.153    <nodes>	80:31546/TCP    4h        k8s-app=kubernetes-dashboard
kube-system   svc/monitoring-influxdb    10.254.217.141   <none>        8086/TCP        4h        k8s-app=influxdb
```
But I found apiserver can not to access heapster.When I access the url [http://10.12.2.227:8080/api/v1/proxy/namespaces/kube-system/services/heapster/api/v1/model/namespaces/default/pods/](url) through the browser,the return is timeout.
```
Error: 'dial tcp 192.168.84.130:8082: getsockopt: connection timed out'
Trying to reach: 'http://192.168.84.130:8082/
```
Heapster's pod ip is 192.168.84.130.Because the master does not have calico installed, it can not be routed to the pod on the node. So when I reuse the three master as node to deploy ha environment，everything is ok.
```
http://10.12.2.227:8080/api/v1/proxy/namespaces/kube-system/services/heapster/api/v1/model/namespaces/default/pods/
[

    "nginx-1-admin-kubernetes-2916616502-wld9j",
    "nginx-1-admin-kubernetes-2916616502-0vfpm"

]
```
I checked the calico file and found the following comment.
```
containers:
        # Runs calico/node container on each Kubernetes node.  This
        # container programs network policy and routes on each
        # host.
        - name: calico-node
          image: quay.io/calico/node:v2.5.0
```
```
 # This container installs the Calico CNI binaries
        # and CNI network config file on each node.
        - name: install-cni
          image: quay.io/calico/cni:v1.10.0
          command: ["/install-cni.sh"]
```
So calico cni should run on master and node.But the master does not have a kubelet installed,how calico to run?

**Comment by tmjd** [comment]
If the API server or anything running on the master(s) needs to access a pod then yes Calico needs to run on the master and one way to do that would be to run kubelet on the master.  Kubeadm allows this by having a taint that prevents 'regular' pods from running but a toleration can be added to the calico manifest  that allows it to run on the master.

Here is a snippet from a Calico manifest for kubeadm showing the toleration:
```
    spec:
      hostNetwork: true
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
```
(the hostNetwork is not important here but that is how it appears in the manifest)

**Comment by TracyBin** [comment]
@tmjd Thank you for your time! I have solved this problem according to your proposal.
> install-master.sh
```
${KUBECTL} taint nodes master-1 node-role.kubernetes.io/master=master:NoSchedule  --overwrite=true
		${KUBECTL} taint nodes master-2 node-role.kubernetes.io/master=master:NoSchedule  --overwrite=true
		${KUBECTL} taint nodes master-3 node-role.kubernetes.io/master=master:NoSchedule  --overwrite=true
```
> calico.yaml
```
tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          value: "master"
          effect: NoSchedule
```

**Comment by debovema** [comment]
Was useful for me.
Thanks

**Comment by apsega** [comment]
Adding the following helped (`value: "master" not needed)`:
```
kind: DaemonSet
apiVersion: extensions/v1beta1
<...>
spec:
<...>
  template:
  <...>
    spec:
      hostNetwork: true
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
```
