### ISSUE TITLE
calico cause kube-adm  repeat CrashLoopBackOff

### ISSUE THREAD

**Issue by justlooks** [projectcalico/calico#1105]
```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T09:14:02Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T08:56:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

# rpm -qa|grep kube
kubernetes-cni-0.5.1-0.x86_64
kubelet-1.7.5-0.x86_64
kubeadm-1.7.5-0.x86_64
kubectl-1.7.5-0.x86_64

# cat /etc/redhat-release
CentOS Linux release 7.2.1511 (Core)
```

i test calico on my 2-node cluster build by kubeadm,and i use following calico deploy file like document says ,but i find my kube-dns in CrashLoopBackOff , is it a bug?
```
NAMESPACE     NAME                                       READY     STATUS             RESTARTS   AGE       IP              NODE
kube-system   calico-etcd-gnr9l                          1/1       Running            0          22m       10.161.233.80   k8s-node2
kube-system   calico-node-l6sbk                          2/2       Running            1          22m       10.165.97.219   k8s-node1
kube-system   calico-node-qgkjj                          2/2       Running            0          22m       10.161.233.80   k8s-node2
kube-system   calico-policy-controller-336633499-fzrs2   1/1       Running            0          22m       10.165.97.219   k8s-node1
kube-system   etcd-k8s-node2                             1/1       Running            0          29m       10.161.233.80   k8s-node2
kube-system   kube-apiserver-k8s-node2                   1/1       Running            0          29m       10.161.233.80   k8s-node2
kube-system   kube-controller-manager-k8s-node2          1/1       Running            0          29m       10.161.233.80   k8s-node2
kube-system   kube-dns-2425271678-h99l2                  1/3       CrashLoopBackOff   27         36m       10.68.36.65     k8s-node1
kube-system   kube-proxy-2dfqx                           1/1       Running            0          36m       10.161.233.80   k8s-node2
kube-system   kube-proxy-cm2wm                           1/1       Running            0          36m       10.165.97.219   k8s-node1
kube-system   kube-scheduler-k8s-node2                   1/1       Running            0          29m       10.161.233.80   k8s-node2

# kubectl describe pod kube-dns-2425271678-h99l2 --namespace kube-system
Name:           kube-dns-2425271678-h99l2
Namespace:      kube-system
Node:           k8s-node1/10.165.97.219
Start Time:     Wed, 13 Sep 2017 20:27:52 +0800
Labels:         k8s-app=kube-dns
                pod-template-hash=2425271678
Annotations:    kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"kube-system","name":"kube-dns-2425271678","uid":"aad5ab74-987e-11e7-98ad-00163e02...
                scheduler.alpha.kubernetes.io/critical-pod=
Status:         Running
IP:             10.68.36.65
Created By:     ReplicaSet/kube-dns-2425271678
Controlled By:  ReplicaSet/kube-dns-2425271678
Containers:
  kubedns:
    Container ID:       docker://8f0bb566ffaca94fcd6772bbe2d457395b15bde237e9cb4f4e96f0a6d839761e
    Image:              gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.4
    Image ID:           docker://sha256:3e08c89ee4257323acd3620d7ca6acf6335281afe88f4aa39dc86c48246f5f1b
    Ports:              10053/UDP, 10053/TCP, 10055/TCP
    Args:
      --domain=cluster.local.
      --dns-port=10053
      --config-dir=/kube-dns-config
      --v=2
    State:              Waiting
      Reason:           CrashLoopBackOff
    Last State:         Terminated
      Reason:           Error
      Exit Code:        255
      Started:          Wed, 13 Sep 2017 21:00:35 +0800
      Finished:         Wed, 13 Sep 2017 21:01:35 +0800
    Ready:              False
    Restart Count:      9
    Limits:
      memory:   170Mi
    Requests:
      cpu:      100m
      memory:   70Mi
    Liveness:   http-get http://:10054/healthcheck/kubedns delay=60s timeout=5s period=10s #success=1 #failure=5
    Readiness:  http-get http://:8081/readiness delay=3s timeout=5s period=10s #success=1 #failure=3
    Environment:
      PROMETHEUS_PORT:  10055
    Mounts:
      /kube-dns-config from kube-dns-config (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-dns-token-x2v6m (ro)
  dnsmasq:
    Container ID:       docker://58e1a0ca05e7e71dd530f5b858608916322e8e468a3c49186572aefabc124314
    Image:              gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.4
    Image ID:           docker://sha256:1813641c1a74c23cda52caffabc4cb8be6a0e8292a41ca029171d9216d6589c3
    Ports:              53/UDP, 53/TCP
    Args:
      -v=2
      -logtostderr
      -configDir=/etc/k8s/dns/dnsmasq-nanny
      -restartDnsmasq=true
      --
      -k
      --cache-size=1000
      --log-facility=-
      --server=/cluster.local/127.0.0.1#10053
      --server=/in-addr.arpa/127.0.0.1#10053
      --server=/ip6.arpa/127.0.0.1#10053
    State:              Running
      Started:          Wed, 13 Sep 2017 21:01:33 +0800
    Last State:         Terminated
      Reason:           Error
      Exit Code:        137
      Started:          Wed, 13 Sep 2017 20:59:26 +0800
      Finished:         Wed, 13 Sep 2017 21:01:32 +0800
    Ready:              True
    Restart Count:      9
    Requests:
      cpu:              150m
      memory:           20Mi
    Liveness:           http-get http://:10054/healthcheck/dnsmasq delay=60s timeout=5s period=10s #success=1 #failure=5
    Environment:        <none>
    Mounts:
      /etc/k8s/dns/dnsmasq-nanny from kube-dns-config (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-dns-token-x2v6m (ro)
  sidecar:
    Container ID:       docker://b856fd8130b28117add1445050140c4a311cf4b830c6380dab76b02b6d90eb23
    Image:              gcr.io/google_containers/k8s-dns-sidecar-amd64:1.14.4
    Image ID:           docker://sha256:db8241b72199d1918a732ca214a00b375150d0840c850729ed344e40149261e5
    Port:               10054/TCP
    Args:
      --v=2
      --logtostderr
      --probe=kubedns,127.0.0.1:10053,kubernetes.default.svc.cluster.local,5,A
      --probe=dnsmasq,127.0.0.1:53,kubernetes.default.svc.cluster.local,5,A
    State:              Waiting
      Reason:           CrashLoopBackOff
    Last State:         Terminated
      Reason:           Error
      Exit Code:        2
      Started:          Wed, 13 Sep 2017 20:58:03 +0800
      Finished:         Wed, 13 Sep 2017 20:59:42 +0800
    Ready:              False
    Restart Count:      9
    Requests:
      cpu:              10m
      memory:           20Mi
    Liveness:           http-get http://:10054/metrics delay=60s timeout=5s period=10s #success=1 #failure=5
    Environment:        <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-dns-token-x2v6m (ro)
Conditions:
  Type          Status
  Initialized   True
  Ready         False
  PodScheduled  True
Volumes:
  kube-dns-config:
    Type:       ConfigMap (a volume populated by a ConfigMap)
    Name:       kube-dns
    Optional:   true
  kube-dns-token-x2v6m:
    Type:       Secret (a volume populated by a Secret)
    SecretName: kube-dns-token-x2v6m
    Optional:   false
QoS Class:      Burstable
Node-Selectors: <none>
Tolerations:    CriticalAddonsOnly
                node-role.kubernetes.io/master:NoSchedule
                node.alpha.kubernetes.io/notReady:NoExecute for 300s
                node.alpha.kubernetes.io/unreachable:NoExecute for 300s
Events:
  FirstSeen     LastSeen        Count   From                    SubObjectPath                   Type            Reason                  Message
  ---------     --------        -----   ----                    -------------                   --------        ------                  -------
  36m           35m             8       default-scheduler                                       Warning         FailedScheduling        no nodes available to schedule pods
  34m           34m             1       default-scheduler                                       Normal          Scheduled               Successfully assigned kube-dns-2425271678-h99l2 to k8s-node1
  34m           34m             1       kubelet, k8s-node1                                      Normal          SuccessfulMountVolume   MountVolume.SetUp succeeded for volume "kube-dns-config"
  34m           34m             1       kubelet, k8s-node1                                      Normal          SuccessfulMountVolume   MountVolume.SetUp succeeded for volume "kube-dns-token-x2v6m"
  34m           28m             22      kubelet, k8s-node1                                      Normal          SandboxChanged          Pod sandbox changed, it will be killed and re-created.
  25m           25m             1       kubelet, k8s-node1      spec.containers{kubedns}        Normal          Killing                 Killing container with id docker://kubedns:pod "kube-dns-2425271678-h99l2_kube-system(aaddd75f-987e-11e7-98ad-00163e02455f)" container "kubedns" is unhealthy, it will be killed and re-created.
  27m           12m             8       kubelet, k8s-node1      spec.containers{kubedns}        Warning         Unhealthy               Liveness probe failed: Get http://10.68.36.65:10054/healthcheck/kubedns: dial tcp 10.68.36.65:10054: connect: invalid argument
  28m           4m              10      kubelet, k8s-node1      spec.containers{sidecar}        Normal          Pulled                  Container image "gcr.io/google_containers/k8s-dns-sidecar-amd64:1.14.4" already present on machine
  28m           4m              10      kubelet, k8s-node1      spec.containers{sidecar}        Normal          Started                 Started container
  28m           4m              10      kubelet, k8s-node1      spec.containers{sidecar}        Normal          Created                 Created container
  12m           3m              47      kubelet, k8s-node1      spec.containers{dnsmasq}        Warning         BackOff                 Back-off restarting failed container
  27m           2m              41      kubelet, k8s-node1      spec.containers{sidecar}        Warning         Unhealthy               Liveness probe failed: Get http://10.68.36.65:10054/metrics: dial tcp 10.68.36.65:10054: connect: invalid argument
  25m           2m              10      kubelet, k8s-node1      spec.containers{sidecar}        Normal          Killing                 Killing container with id docker://sidecar:pod "kube-dns-2425271678-h99l2_kube-system(aaddd75f-987e-11e7-98ad-00163e02455f)" container "sidecar" is unhealthy, it will be killed and re-created.
  28m           1m              10      kubelet, k8s-node1      spec.containers{kubedns}        Normal          Pulled                  Container image "gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.4" already present on machine
  28m           1m              10      kubelet, k8s-node1      spec.containers{kubedns}        Normal          Created                 Created container
  28m           1m              10      kubelet, k8s-node1      spec.containers{kubedns}        Normal          Started                 Started container
  27m           1m              37      kubelet, k8s-node1      spec.containers{dnsmasq}        Warning         Unhealthy               Liveness probe failed: Get http://10.68.36.65:10054/healthcheck/dnsmasq: dial tcp 10.68.36.65:10054: connect: invalid argument
  28m           53s             70      kubelet, k8s-node1      spec.containers{kubedns}        Warning         Unhealthy               Readiness probe failed: Get http://10.68.36.65:8081/readiness: dial tcp 10.68.36.65:8081: connect: invalid argument
  28m           53s             10      kubelet, k8s-node1      spec.containers{dnsmasq}        Normal          Pulled                  Container image "gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.4" already present on machine
  26m           53s             9       kubelet, k8s-node1      spec.containers{dnsmasq}        Normal          Killing                 Killing container with id docker://dnsmasq:pod "kube-dns-2425271678-h99l2_kube-system(aaddd75f-987e-11e7-98ad-00163e02455f)" container "dnsmasq" is unhealthy, it will be killed and re-created.
  28m           52s             10      kubelet, k8s-node1      spec.containers{dnsmasq}        Normal          Started                 Started container
  28m           52s             10      kubelet, k8s-node1      spec.containers{dnsmasq}        Normal          Created                 Created container
  22m           7s              88      kubelet, k8s-node1      spec.containers{kubedns}        Warning         BackOff                 Back-off restarting failed container
  34m           7s              124     kubelet, k8s-node1                                      Warning         FailedSync              Error syncing pod
  11m           7s              43      kubelet, k8s-node1      spec.containers{sidecar}        Warning         BackOff                 Back-off restarting failed container


```

```
# Calico Version v2.5.1
# https://docs.projectcalico.org/v2.5/releases#v2.5.1
# This manifest includes the following component versions:
#   calico/node:v2.5.1
#   calico/cni:v1.10.0
#   calico/kube-policy-controller:v0.7.0

# This ConfigMap is used to configure a self-hosted Calico installation.
kind: ConfigMap
apiVersion: v1
metadata:
  name: calico-config
  namespace: kube-system
data:
  # The location of your etcd cluster.  This uses the Service clusterIP
  # defined below.
  etcd_endpoints: "http://10.96.232.136:6666"

  # Configure the Calico backend to use.
  calico_backend: "bird"

  # The CNI network configuration to install on each node.
  cni_network_config: |-
    {
        "name": "k8s-pod-network",
        "cniVersion": "0.1.0",
        "type": "calico",
        "etcd_endpoints": "__ETCD_ENDPOINTS__",
        "log_level": "info",
        "mtu": 1500,
        "ipam": {
            "type": "calico-ipam"
        },
        "policy": {
            "type": "k8s",
             "k8s_api_root": "https://__KUBERNETES_SERVICE_HOST__:__KUBERNETES_SERVICE_PORT__",
             "k8s_auth_token": "__SERVICEACCOUNT_TOKEN__"
        },
        "kubernetes": {
            "kubeconfig": "/etc/cni/net.d/__KUBECONFIG_FILENAME__"
        }
    }

---

# This manifest installs the Calico etcd on the kubeadm master.  This uses a DaemonSet
# to force it to run on the master even when the master isn't schedulable, and uses
# nodeSelector to ensure it only runs on the master.
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: calico-etcd
  namespace: kube-system
  labels:
    k8s-app: calico-etcd
spec:
  template:
    metadata:
      labels:
        k8s-app: calico-etcd
      annotations:
        # Mark this pod as a critical add-on; when enabled, the critical add-on scheduler
        # reserves resources for critical add-on pods so that they can be rescheduled after
        # a failure.  This annotation works in tandem with the toleration below.
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      # Only run this pod on the master.
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      # Allow this pod to be rescheduled while the node is in "critical add-ons only" mode.
      # This, along with the annotation above marks this pod as a critical add-on.
      - key: CriticalAddonsOnly
        operator: Exists
      nodeSelector:
        node-role.kubernetes.io/master: ""
      hostNetwork: true
      containers:
        - name: calico-etcd
          image: quay.io/coreos/etcd:v3.1.10
          env:
            - name: CALICO_ETCD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          command: ["/bin/sh","-c"]
          args: ["/usr/local/bin/etcd --name=calico --data-dir=/var/etcd/calico-data --advertise-client-urls=http://$CALICO_ETCD_IP:6666 --listen-client-urls=http://0.0.0.0:6666 --listen-peer-urls=http://0.0.0.0:6667"]
          volumeMounts:
            - name: var-etcd
              mountPath: /var/etcd
      volumes:
        - name: var-etcd
          hostPath:
            path: /var/etcd

---

# This manifest installs the Service which gets traffic to the Calico
# etcd.
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: calico-etcd
  name: calico-etcd
  namespace: kube-system
spec:
  # Select the calico-etcd pod running on the master.
  selector:
    k8s-app: calico-etcd
  # This ClusterIP needs to be known in advance, since we cannot rely
  # on DNS to get access to etcd.
  clusterIP: 10.96.232.136
  ports:
    - port: 6666

---

# This manifest installs the calico/node container, as well
# as the Calico CNI plugins and network config on
# each master and worker node in a Kubernetes cluster.
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: calico-node
  namespace: kube-system
  labels:
    k8s-app: calico-node
spec:
  selector:
    matchLabels:
      k8s-app: calico-node
  template:
    metadata:
      labels:
        k8s-app: calico-node
      annotations:
        # Mark this pod as a critical add-on; when enabled, the critical add-on scheduler
        # reserves resources for critical add-on pods so that they can be rescheduled after
        # a failure.  This annotation works in tandem with the toleration below.
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      hostNetwork: true
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      # Allow this pod to be rescheduled while the node is in "critical add-ons only" mode.
      # This, along with the annotation above marks this pod as a critical add-on.
      - key: CriticalAddonsOnly
        operator: Exists
      serviceAccountName: calico-cni-plugin
      containers:
        # Runs calico/node container on each Kubernetes node.  This
        # container programs network policy and routes on each
        # host.
        - name: calico-node
          image: quay.io/calico/node:v2.5.1
          env:
            # The location of the Calico etcd cluster.
            - name: ETCD_ENDPOINTS
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_endpoints
            # Enable BGP.  Disable to enforce policy only.
            - name: CALICO_NETWORKING_BACKEND
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: calico_backend
            # Cluster type to identify the deployment type
            - name: CLUSTER_TYPE
              value: "kubeadm,bgp"
            # Disable file logging so `kubectl logs` works.
            - name: CALICO_DISABLE_FILE_LOGGING
              value: "true"
            # Set Felix endpoint to host default action to ACCEPT.
            - name: FELIX_DEFAULTENDPOINTTOHOSTACTION
              value: "ACCEPT"
            # Configure the IP Pool from which Pod IPs will be chosen.
            - name: CALICO_IPV4POOL_CIDR
              value: "10.68.0.0/16"
            - name: CALICO_IPV4POOL_IPIP
              value: "always"
            # Disable IPv6 on Kubernetes.
            - name: FELIX_IPV6SUPPORT
              value: "false"
            # Set MTU for tunnel device used if ipip is enabled
            - name: FELIX_IPINIPMTU
              value: "1440"
            # Set Felix logging to "info"
            - name: FELIX_LOGSEVERITYSCREEN
              value: "info"
            # Auto-detect the BGP IP address.
            - name: IP
              value: ""
            - name: FELIX_HEALTHENABLED
              value: "true"
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: 250m
          livenessProbe:
            httpGet:
              path: /liveness
              port: 9099
            periodSeconds: 10
            initialDelaySeconds: 10
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /readiness
              port: 9099
            periodSeconds: 10
          volumeMounts:
            - mountPath: /lib/modules
              name: lib-modules
              readOnly: true
            - mountPath: /var/run/calico
              name: var-run-calico
              readOnly: false
        # This container installs the Calico CNI binaries
        # and CNI network config file on each node.
        - name: install-cni
          image: quay.io/calico/cni:v1.10.0
          command: ["/install-cni.sh"]
          env:
            # The location of the Calico etcd cluster.
            - name: ETCD_ENDPOINTS
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_endpoints
            # The CNI network config to install on each node.
            - name: CNI_NETWORK_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: cni_network_config
          volumeMounts:
            - mountPath: /host/opt/cni/bin
              name: cni-bin-dir
            - mountPath: /host/etc/cni/net.d
              name: cni-net-dir
      volumes:
        # Used by calico/node.
        - name: lib-modules
          hostPath:
            path: /lib/modules
        - name: var-run-calico
          hostPath:
            path: /var/run/calico
        # Used to install CNI.
        - name: cni-bin-dir
          hostPath:
            path: /opt/cni/bin
        - name: cni-net-dir
          hostPath:
            path: /etc/cni/net.d

---

# This manifest deploys the Calico policy controller on Kubernetes.
# See https://github.com/projectcalico/k8s-policy
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: calico-policy-controller
  namespace: kube-system
  labels:
    k8s-app: calico-policy
spec:
  # The policy controller can only have a single active instance.
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      name: calico-policy-controller
      namespace: kube-system
      labels:
        k8s-app: calico-policy-controller
      annotations:
        # Mark this pod as a critical add-on; when enabled, the critical add-on scheduler
        # reserves resources for critical add-on pods so that they can be rescheduled after
        # a failure.  This annotation works in tandem with the toleration below.
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      # The policy controller must run in the host network namespace so that
      # it isn't governed by policy that would prevent it from working.
      hostNetwork: true
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      # Allow this pod to be rescheduled while the node is in "critical add-ons only" mode.
      # This, along with the annotation above marks this pod as a critical add-on.
      - key: CriticalAddonsOnly
        operator: Exists
      serviceAccountName: calico-policy-controller
      containers:
        - name: calico-policy-controller
          image: quay.io/calico/kube-policy-controller:v0.7.0
          env:
            # The location of the Calico etcd cluster.
            - name: ETCD_ENDPOINTS
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_endpoints
            # The location of the Kubernetes API.  Use the default Kubernetes
            # service for API access.
            - name: K8S_API
              value: "https://kubernetes.default:443"
            # Since we're running in the host namespace and might not have KubeDNS
            # access, configure the container's /etc/hosts to resolve
            # kubernetes.default to the correct service clusterIP.
            - name: CONFIGURE_ETC_HOSTS
              value: "true"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: calico-cni-plugin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: calico-cni-plugin
subjects:
- kind: ServiceAccount
  name: calico-cni-plugin
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: calico-cni-plugin
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources:
      - pods
      - nodes
    verbs:
      - get
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: calico-cni-plugin
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: calico-policy-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: calico-policy-controller
subjects:
- kind: ServiceAccount
  name: calico-policy-controller
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: calico-policy-controller
  namespace: kube-system
rules:
  - apiGroups:
    - ""
    - extensions
    resources:
      - pods
      - namespaces
      - networkpolicies
    verbs:
      - watch
      - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: calico-policy-controller
  namespace: kube-system
```
