### ISSUE TITLE
stars policy demo default-deny.yaml kicks a ValidationError on k8s-v1.8.0-rc.1 

### ISSUE THREAD

**Issue by 2ffs2nns** [projectcalico/calico#1135]
## Expected Behavior
Users should be able to run through the Stars Policy Demo on kubernetes v1.8.0-rc.1 w/out any policy validation errors.

## Current Behavior
Enabling the isolation policies results in a validation error
```
kubectl create -n stars -f https://docs.projectcalico.org/v2.6/getting-started/kubernetes/tutorials/stars-policy/policies/default-deny.yaml

error: error validating "default-deny.yaml": error validating data: ValidationError(NetworkPolicy.spec): missing required field "podSelector" in io.k8s.api.extensions.v1beta1.NetworkPolicySpec; if you choose to ignore these errors, turn validation off with --validate=false
```
 
## Possible Solution
Adding a default podSelector catch-all label removes the ValidationError. Running through the demo with the proposed fix on a kubernetes-v1.7.6 also works as expected.

```
kind: NetworkPolicy
apiVersion: extensions/v1beta1
metadata:
  name: default-deny
spec:
  podSelector:
    matchLabels:
```

## Your Environment

* Calico version v2.6.0-rc2
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes v1.8.0-rc.1
