### ISSUE TITLE
Does calico open firewalld? 

### ISSUE THREAD

**Issue by ryobot** [projectcalico/calico#1214]
In my environment, it seems that firewalld does not effect .
I do not feel sure calico is a cause of this problem.
However,  no-calico(not installed) server is still firewalld protected.
Please review my calico env and give me comments.

## Expected Behavior

serverA's eth1 should be protected as firewalld zone(dmz)
only 443,179,10054,6443

## Steps to Reproduce (for bugs)

1.kubernetes install
2.calico install(no ipip)
3.nmap to neighbor

## Your Environment

calico version
v2.5.1

calicoctl get node
````
ETCD_ENDPOINTS=http://localhost:6666 calicoctl get node -o yaml
- apiVersion: v1
  kind: node
  metadata:
    name: serverA.domain
  spec:
    bgp:
      ipv4Address: 172.22.1.10/16
- apiVersion: v1
  kind: node
  metadata:
    name: serverB.domain
  spec:
    bgp:
      ipv4Address: 172.22.1.12/16
- apiVersion: v1
  kind: node
  metadata:
    name: serverC.domain
  spec:
    bgp:
      ipv4Address: 172.22.1.13/16
````

kubectl get node
````
NAME                                STATUS    AGE       VERSION
serverA.domain    Ready     2d        v1.7.5
serverB.domain   Ready     2d        v1.7.5
serverC.domain   Ready     2d        v1.7.5
````

kubectl get pod
````
NAME                                                       READY     STATUS    RESTARTS   AGE
calico-etcd-ccjbq                                          1/1       Running   0          2d
calico-node-s34nw                                          2/2       Running   2          2d
calico-node-wcpls                                          2/2       Running   2          2d
calico-node-xd58r                                          2/2       Running   2          2d
calico-policy-controller-336633499-pmpf9                   1/1       Running   0          2d
kube-apiserver-ssl02-serverA.domain            1/1       Running   0          2d
kube-controller-manager-serverA.domain   1/1       Running   1          2d
kube-dns-3261008397-qj0r1                                  3/3       Running   0          2d
kube-proxy-36pfd                                           1/1       Running   0          2d
kube-proxy-60498                                           1/1       Running   0          2d
kube-proxy-g0f4h                                           1/1       Running   0          2d
kube-scheduler-ssl02-k8s-serverA.domain           1/1       Running   1          2d
........
````

serverA interfaces
````
$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether fa:16:3e:c2:80:f0 brd ff:ff:ff:ff:ff:ff
    inet 192.168.129.10/24 brd 192.168.129.255 scope global dynamic eth0
       valid_lft 3278086sec preferred_lft 3278086sec
    inet6 fe80::f816:3eff:fec2:80f0/64 scope link
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether fa:16:3e:77:c7:10 brd ff:ff:ff:ff:ff:ff
    inet 172.22.1.10/16 brd 172.22.255.255 scope global dynamic eth1
       valid_lft 3278086sec preferred_lft 3278086sec
    inet6 fe80::7226:4c46:cbeb:4b73/64 scope link
       valid_lft forever preferred_lft forever
4: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN
    link/ether 02:42:e9:8e:2c:86 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
5: caliada6cadca62@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP
    link/ether 9a:8e:ef:db:42:38 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::988e:efff:fedb:4238/64 scope link
       valid_lft forever preferred_lft forever
6: califbdfdc0aa29@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP
    link/ether 16:c2:d0:54:74:c8 brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 fe80::14c2:d0ff:fe54:74c8/64 scope link
       valid_lft forever preferred_lft forever
7: cali24c55e6b389@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP
    link/ether 7a:01:f0:13:88:a5 brd ff:ff:ff:ff:ff:ff link-netnsid 2
    inet6 fe80::7801:f0ff:fe13:88a5/64 scope link
       valid_lft forever preferred_lft forever
8: cali4c9ab9b77e8@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP
    link/ether 0a:7e:e2:f8:a4:6e brd ff:ff:ff:ff:ff:ff link-netnsid 3
    inet6 fe80::87e:e2ff:fef8:a46e/64 scope link
       valid_lft forever preferred_lft forever
9: calicb66c99de43@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP
    link/ether 22:52:55:87:23:65 brd ff:ff:ff:ff:ff:ff link-netnsid 4
    inet6 fe80::2052:55ff:fe87:2365/64 scope link
       valid_lft forever preferred_lft forever
10: calie6abaa8b30c@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP
    link/ether 26:c8:59:2b:a9:24 brd ff:ff:ff:ff:ff:ff link-netnsid 5
    inet6 fe80::24c8:59ff:fe2b:a924/64 scope link
       valid_lft forever preferred_lft forever
````

serverA firewalld
````
block
  target: %%REJECT%%
  icmp-block-inversion: no
  interfaces:
  sources:
  services:
  ports:
  protocols:
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:


dmz (active)
  target: default
  icmp-block-inversion: no
  interfaces: eth1
  sources:
  services: ssh
  ports: 179/tcp 10054/tcp 6443/tcp
  protocols:
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:
        rule family="ipv4" source address="xxx.xxx.0.0/16" port port="443" protocol="tcp" accept
        rule family="ipv4" source address="yyy.yyy.0.0/16" port port="443" protocol="tcp" accept
        rule family="ipv4" port port="22" protocol="tcp" reject

drop
  target: DROP
  icmp-block-inversion: no
  interfaces:
  sources:
  services:
  ports:
  protocols:
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:


external
  target: default
  icmp-block-inversion: no
  interfaces:
  sources:
  services: ssh
  ports:
  protocols:
  masquerade: yes
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:


home
  target: default
  icmp-block-inversion: no
  interfaces:
  sources:
  services: ssh mdns samba-client dhcpv6-client
  ports:
  protocols:
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:


internal
  target: default
  icmp-block-inversion: no
  interfaces:
  sources:
  services: ssh mdns samba-client dhcpv6-client
  ports:
  protocols:
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:


public (active)
  target: default
  icmp-block-inversion: no
  interfaces: eth0
  sources: 192.168.129.0/24 192.168.129.10 192.168.129.12 192.168.129.13
  services: dhcpv6-client ssh nfs
  ports: 10050/tcp 4194/tcp 4001/tcp 2379/tcp 2380/tcp 10255/tcp 6666/tcp 10250/tcp 8080/tcp 5000/tcp 6443/tcp 10051/tcp 24225/tcp 24225/udp
  protocols:
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:


trusted
  target: ACCEPT
  icmp-block-inversion: no
  interfaces:
  sources:
  services:
  ports:
  protocols:
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:


work
  target: default
  icmp-block-inversion: no
  interfaces:
  sources:
  services: ssh dhcpv6-client
  ports:
  protocols:
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:
````

nmap to serverA(eth1)
There are too much open port.
````
$ sudo nmap -P0 -n -sS -T4 -p 1-65535 '172.22.1.10 '

Starting Nmap 6.40 ( http://nmap.org ) at 2017-10-19 17:15 JST
Nmap scan report for 172.22.1.10  (172.22.1.10)
Host is up (0.00041s latency).
Not shown: 65511 closed ports
PORT      STATE SERVICE
22/tcp    open  ssh
80/tcp    open  http
111/tcp   open  rpcbind
179/tcp   open  bgp
443/tcp   open  https
514/tcp   open  shell
2049/tcp  open  nfs
5000/tcp  open  upnp
5432/tcp  open  postgresql
6443/tcp  open  unknown
6666/tcp  open  irc
6667/tcp  open  irc
8181/tcp  open  unknown
9099/tcp  open  unknown
10050/tcp open  unknown
10051/tcp open  unknown
10080/tcp open  unknown
10250/tcp open  unknown
10255/tcp open  unknown
10256/tcp open  unknown
18080/tcp open  unknown
20048/tcp open  unknown
33336/tcp open  unknown
44084/tcp open  unknown
MAC Address: FA:16:3E:77:C7:10 (Unknown)

Nmap done: 1 IP address (1 host up) scanned in 1.71 seconds
````

os version
cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core)
