### ISSUE TITLE
selector inside EntityRule not working for network policy

### ISSUE THREAD

**Issue by song-jiang** [projectcalico/calico#1338]
## Step to reproduce
1. Create 3 workloads on host1 & host2 in namespace `nsb` with label `ns: nsb`. Create 1 workload on host1 in namespace `nsa` with label `ns: nsa`
2. Create network policy 
```
  apiVersion: projectcalico.org/v2
  kind: NetworkPolicy
  metadata:
    name: nsa-100-deny-from-nsb
    namespace: nsa
  spec:
    egress: []
    ingress:
    - action: deny
       protocol: tcp
       source:
         selector: ns == 'nsb'
    order: 100
```
3. Policy created successfully but workload with label `ns: nsb` still can access workload in namespace `nsa`.
4. Checked iptables, looking fine. Checked ipset on host1, there is an ipset corresponding to the policy but no ip in it.
5. If I create the same policy with GlobalNetworkPolicy, ipset got correct ips in it and works as expected.

## Context
Calico-node st for policy namespaces.

## Your Environment
```
/ # /code/filesystem/bin/calico-felix --version
Version:            3.0.0-alpha1-38-g7903adf8
Full git commit ID: 7903adf86737a3654660986bc9017bb30ce9f41a
Build date:         2017-11-10T08:00:33+0000

/ # /code/dist/calicoctl --version
calicoctl version v2.0.0-alpha1-20-g1c0ac4d5, build 1c0ac4d5
```
