### ISSUE TITLE
kubernetes networkpolicy with only egress will deny all ingress traffic ?

### ISSUE THREAD

**Issue by 420691301** [projectcalico/calico#1360]
When I create kubernetes networkpolicy which the `policyTypes `field set egress only, i find the selected pods does not allow any ingress traffic.
## Expected Behavior

I think it should only changes egress traffic,not ingress traffic.
## Current Behavior

The selected pods does not allow any ingress traffic.
## Possible Solution

It works well when I add the networkpolicy which default allow all ingress traffic.
## Steps to Reproduce (for bugs)

I create the  networkpolicy below

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    user: admin
  name: test
  namespace: test
spec:
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: wordpress-mysql
  podSelector:
    matchLabels:
      app: wordpress
  policyTypes:
  - Egress
```

no policies exist before this policy.  
```
[root@m1 ~]# calicoctl get policy -o yaml
- apiVersion: v1
  kind: policy
  metadata:
    name: knp.default.test.test
  spec:
    egress:
    - action: allow
      destination:
        selector: calico/k8s_ns == 'test' && app == 'wordpress-mysql'
      source: {}
    order: 1000
    selector: calico/k8s_ns == 'test' && app == 'wordpress'
    types:
    - egress
```

and wordpress pod does not allow any ingress traffic. When I delete the networkpolicy ,it works well. Is the reason that the pocliy `knp.default.test.test` of calico does not have the ingress field? Is it BUG, or default design ?

## Context

I also found the kubernetes networkpolicy with only ingress may changes egress traffic policy.
Eg. there is a kubernetes networkpolicy `test`
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    user: admin
  name: test
  namespace: test
spec:
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: wordpress-mysql
  podSelector:
    matchLabels:
      app: wordpress
  policyTypes:
  - Egress
```
And wordpress only can access wordpress-mysql by this policy. But the networkpolicy blow will allow all egress traffic of wordpress. The networkpolicy is expected to set the ingress traffic only .

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    user: admin
  name: test2
  namespace: test
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: busybox
  podSelector:
    matchLabels:
      app: wordpress
  policyTypes:
  - Ingress
```
```
[root@m1 ~]# calicoctl get policy -o yaml
- apiVersion: v1
  kind: policy
  metadata:
    name: knp.default.test.test
  spec:
    egress:
    - action: allow
      destination:
        selector: calico/k8s_ns == 'test' && app == 'wordpress-mysql'
      source: {}
    order: 1000
    selector: calico/k8s_ns == 'test' && app == 'wordpress'
    types:
    - egress
- apiVersion: v1
  kind: policy
  metadata:
    name: knp.default.test.test2
  spec:
    egress:
    - action: allow
      destination: {}
      source: {}
    ingress:
    - action: allow
      destination: {}
      source:
        selector: calico/k8s_ns == 'test' && app == 'busybox'
    order: 1000
    selector: calico/k8s_ns == 'test' && app == 'wordpress'
    types:
    - ingress
```
So the `egress `field of `knp.default.test.test2` leads to this.Is it Bug ,or default ? I don't think settting ingress policy should change egress policy. Or something I misstake?

```
...
metadata:
    name: knp.default.test.test2
  spec:
    egress:
    - action: allow
      destination: {}
      source: {}
...
```

## Your Environment

* Calico version:v2.6.2
* Orchestrator version (e.g. kubernetes, mesos, rkt):
kubernets 1.8 / hyperkube v1.8.2
* Operating System and version:
Centos 7
* Link to your project (optional):

**Comment by 420691301** [comment]
I try [Advanced network policy](https://docs.projectcalico.org/v2.6/getting-started/kubernetes/tutorials/advanced-policy), in `4. Deny all egress traffic` part , `nslookup nginx` also can get IP of nginx service.I think something wrong with my cluster. I guess maybe the calico policy is wrong.
my calico policy:

```
- apiVersion: v1
  kind: policy
  metadata:
    name: knp.default.advanced-policy-demo.access-nginx
  spec:
    egress:
    - action: allow
      destination: {}
      source: {}
    ingress:
    - action: allow
      destination: {}
      source:
        selector: calico/k8s_ns == 'advanced-policy-demo'
    order: 1000
    selector: calico/k8s_ns == 'advanced-policy-demo' && run == 'nginx'
    types:
    - ingress
- apiVersion: v1
  kind: policy
  metadata:
    name: knp.default.advanced-policy-demo.default-deny-egress
  spec:
    order: 1000
    selector: calico/k8s_ns == 'advanced-policy-demo'
    types:
    - egress
- apiVersion: v1
  kind: policy
  metadata:
    name: knp.default.advanced-policy-demo.default-deny-ingress
  spec:
    egress:
    - action: allow
      destination: {}
      source: {}
    order: 1000
    selector: calico/k8s_ns == 'advanced-policy-demo'
    types:
    - ingress
```
