### ISSUE TITLE
error: You must be logged in to the server (the server has asked for the client to provide credentials ( pods/log calico-node-w622p))

### ISSUE THREAD

**Issue by JinsYin** [projectcalico/calico#1380]
I'm using [this tutorial](https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/hosted/hosted) to deploy calico on kubernetes. But I have the following issues:

```bash
$ kubectl get pod -n kube-system | grep calico
calico-kube-controllers-6767db6bdc-8jl9s   1/1       Running            0          4m
calico-node-6wg94                          1/2       CrashLoopBackOff   5          4m
calico-node-rw6j8                          1/2       CrashLoopBackOff   5          4m

$ kubectl -n kube-system logs -f calico-node-6wg94
Error from server (BadRequest): a container name must be specified for pod calico-node-6wg94, choose one of: [calico-node install-cni]
```

env:

```
centos 7.3
kubernetes 1.8.2 (bare metal)
etcd 3.2.6
```

my `calico-rbac.yaml`:

```yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: calico-kube-controllers
rules:
  - apiGroups:
    - ""
    - extensions
    resources:
    - pods
    - namespaces
    - networkpolicies
    verbs:
    - watch
    - list
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: calico-kube-controllers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: calico-kube-controllers
subjects:
- kind: ServiceAccount
  name: calico-kube-controllers
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: calico-node
rules:
  - apiGroups: [""]
    resources:
    - pods
    - nodes
    verbs:
    - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: calico-node
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: calico-node
subjects:
- kind: ServiceAccount
  name: calico-node
  namespace: kube-system
```

my `calico.yaml`:

```yaml
# Calico Version v2.6.2
# https://docs.projectcalico.org/v2.6/releases#v2.6.2
# This manifest includes the following component versions:
#   calico/node:v2.6.2
#   calico/cni:v1.11.0
#   calico/kube-controllers:v1.0.0

# This ConfigMap is used to configure a self-hosted Calico installation.
kind: ConfigMap
apiVersion: v1
metadata:
  name: calico-config
  namespace: kube-system
data:
  # Configure this with the location of your etcd cluster.
  etcd_endpoints: "https://172.72.4.11:2379，https://172.72.4.12:2379，https://172.72.4.13:2379"

  # Configure the Calico backend to use.
  calico_backend: "bird"

  # The CNI network configuration to install on each node.
  cni_network_config: |-
    {
        "name": "k8s-pod-network",
        "cniVersion": "0.1.0",
        "type": "calico",
        "etcd_endpoints": "__ETCD_ENDPOINTS__",
        "etcd_key_file": "__ETCD_KEY_FILE__",
        "etcd_cert_file": "__ETCD_CERT_FILE__",
        "etcd_ca_cert_file": "__ETCD_CA_CERT_FILE__",
        "log_level": "info",
        "mtu": 1500,
        "ipam": {
            "type": "calico-ipam"
        },
        "policy": {
            "type": "k8s",
            "k8s_api_root": "https://__KUBERNETES_SERVICE_HOST__:__KUBERNETES_SERVICE_PORT__",
            "k8s_auth_token": "__SERVICEACCOUNT_TOKEN__"
        },
        "kubernetes": {
            "kubeconfig": "__KUBECONFIG_FILEPATH__"
        }
    }

  # If you're using TLS enabled etcd uncomment the following.
  # You must also populate the Secret below with these files.
  etcd_ca: "/calico-secrets/etcd-ca"   # "/calico-secrets/etcd-ca"
  etcd_cert: "/calico-secrets/etcd-cert" # "/calico-secrets/etcd-cert"
  etcd_key: "/calico-secrets/etcd-key"  # "/calico-secrets/etcd-key"

---

# The following contains k8s Secrets for use with a TLS enabled etcd cluster.
# For information on populating Secrets, see http://kubernetes.io/docs/user-guide/secrets/
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: calico-etcd-secrets
  namespace: kube-system
data:
  # Populate the following files with etcd TLS configuration if desired, but leave blank if
  # not using TLS for etcd.
  # This self-hosted install expects three files with the following names.  The values
  # should be base64 encoded strings of the entire contents of each file.
  etcd-key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBbys3bmFSWlIxK01uY3RGclJFRDRWR05jVXZtR2lwQ1pPdlZYcVpmQ3VLQ05Rb1ZiCk05V2ZoeXlzRk5tQXBFVUNWU3pqYS9yVWJ2QWlsOGRzZE5GODRoSDdlcVBRQmN2QTY1SjFvelYvTTdmcUIzWGQKWWVuV1pXa1lLRkFPM3B4cHp6NEZjNkNUMmFFQ1Q2Y2JBVUJpR0tCNXNmdlYxb2wreDhMZnE3RXY5ZldXams4egpSSlhXbUdsY1I4SVFZNEJsUmloZGhYZk1uaVlMZzNIeHZaZDVPSStxeG9mTTFDT0hVaUNEdm9xU2p6UFpGREZMClVYWTNIUE9TVzFtYkg4OEhOOTRWTzB0b00zYWNWVUhqZTVRdDAzdmlvR0s5YlpSaG9XYmxuazYxYTlTclcvWTUKUk1tN1R3anVPM2hUL3hwZ2tQSzh1Vld4YWpnUDNSb2ZSVEJSd3dJREFRQUJBb0lCQURBNVpFdk9yQTdWSE5LeQo5bG9pdnFxY2ZCbFFuQnFCQlFLS0Q5cXM4VFE4enJGRjU1bHMrenZaa1Zta3ppb0V2dlh0ZVkxWFFVek5TVy9hCjAzWGQ5bDNPcW1yZWE2QjQydXl4cmZkd0VsWlZnUHZtMlZRblpORjZSQWYvM1EveGRWTG96TlBCNWh4OE4rRFUKcUtZS21aRGpERW1tYXJac3hpWGZsc3E4R2Y3QllvTFd2VFdydzVEd1R4cklOSURkVExWTXpTNVFOOTBabnErbwpCeFRTa0k0TE1WZXFLK1dvdStmUVB0TVBUYjJPVW8wSHJjWXZMcThrSzZrYWcvL3lyaGpzTGxwcGlFYUNQcXpSCi9xaUg5UUNaSlJTZ2cwN1lZV1lQblNnL1h1MDJMM0lKd3hDeWFpRGtyTEQ4VDd4NWtFcGloZExvK1h6Q2FwUmUKM0xzR3hyRUNnWUVBMVdhMmpONzVzaXVXSm1KVzFURnFISmFmeDB2SGJEY0c1Wk9Ma3Z4Y1JjU0xrQWFzZTgzUApVblR3VjNQdjB5UldCOCtoQVNoWkhyNEtyNDBSVkgzNm5zejliOTdUNkV5NEZGdlBKbmg5VnZqbTlMR3RtbHhlCmxSYm10d1JPVHNKUVR2VXFmNk5QdW85UEhLVGJyaU1vajFDLzVab1pld09pUGpUSmR4M0dLNGtDZ1lFQXhLaEQKZDJ5NlNDS3RyeklqbWlhVHVGMWw1WDlsbHE2Ull6MitUOUY1emhhOGpjSVVxT1JoVk9Yek9vV3FtdXFLVWRCdwpPV2Vha1Q0UFpaV0RlSkV5SFhPRXJJemxUaWluSGswNlZseGFqYlVZRXZoQ3BoK0t3THI3SnpVSllBZERYY1FyCk9XRUhWL3hpcytOdDI0SUgwc1BtTVdLRll0a2FIREdTTXZ2MXcrc0NnWUJlYkZJOXhyTnBPSXY1YyszRDYxZHUKU3Q5cnlZWDF4ZXRSVFpXbWRlOUdGNDlCTFJMSXZPb05MQnprTlRKYWxHdFVqWFJLRk5aS0dnQ1VhTERRVitXNgp1aTB4Z01EMnVtdUE1cGFrQ1JBOG1XbG52KzUycklSVko0cnlVLzlxTGVSbTYyZmdqaHhMQ2ZvUlRJaS9abU1kCjlyYlNHdnRIU1BaUzIveUFyalh2TVFLQmdRQzF3WHBSZHprWUVJME1Ia0FQYWRZZmtKcnJxSG9nOFFqSWV6bFkKbGhlSXBUVHhvODNxWnVHYVVNa2pib1RHbHp6dDdzSzZHNG9jOFFuVDdvTExQUTdmYjNQUThvdkFXQXhWRWpWMwp1ZldyZ1JOVi9RUEVlK1NHeW9uenE2NFZoY0Q2ZWFNbGJnc1dnOXBKdmtvN2xZdGJmZGxVRFdXUWZXMEhYNzFxCng3cFdyd0tCZ0Z3MXpBakdXWEtTNS9MRmdWbHNJZitnNGVHT1BnRDlhcDh5Qzc2cklrVklQTHJVblQ0c0UvcVUKQWp5eWV0UzA4aEV4aThBSHN4OTJETGZjck5XN2VDVUdHeDZRU1dTamRPL2Zpcm9EdE4veUNtZjd3NTBIeHdTcwpMaHcvRFVTbGI2ZVB5S1phVTg4eUhMd2pZbnZkYXpwa3hqUVlObTFabE90TkpQUzVpNXVPCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
  etcd-cert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ5akNDQXQ2Z0F3SUJBZ0lVYnZhdmxmRGpHS0s5VnQxWE03dUZUcG5YMk13d0RRWUpLb1pJaHZjTkFRRUwKQlFBd1pURUxNQWtHQTFVRUJoTUNRMDR4RVRBUEJnTlZCQWdUQ0ZOb1lXNW5TR0ZwTVJFd0R3WURWUVFIRXdoVAphR0Z1WjBoaGFURU1NQW9HQTFVRUNoTURhemh6TVEwd0N3WURWUVFMRXdSd1lXRnpNUk13RVFZRFZRUURFd3ByCmRXSmxjbTVsZEdWek1CNFhEVEUzTVRFeE1UQXpOVEl3TUZvWERUSTNNVEV3T1RBek5USXdNRm93WHpFTE1Ba0cKQTFVRUJoTUNRMDR4RVRBUEJnTlZCQWdUQ0ZOb1lXNW5TR0ZwTVJFd0R3WURWUVFIRXdoVGFHRnVaMGhoYVRFTQpNQW9HQTFVRUNoTURhemh6TVEwd0N3WURWUVFMRXdSd1lXRnpNUTB3Q3dZRFZRUURFd1JsZEdOa01JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQW8rN25hUlpSMStNbmN0RnJSRUQ0VkdOY1V2bUcKaXBDWk92VlhxWmZDdUtDTlFvVmJNOVdmaHl5c0ZObUFwRVVDVlN6amEvclVidkFpbDhkc2RORjg0aEg3ZXFQUQpCY3ZBNjVKMW96Vi9NN2ZxQjNYZFllbldaV2tZS0ZBTzNweHB6ejRGYzZDVDJhRUNUNmNiQVVCaUdLQjVzZnZWCjFvbCt4OExmcTdFdjlmV1dqazh6UkpYV21HbGNSOElRWTRCbFJpaGRoWGZNbmlZTGczSHh2WmQ1T0krcXhvZk0KMUNPSFVpQ0R2b3FTanpQWkZERkxVWFkzSFBPU1cxbWJIODhITjk0Vk8wdG9NM2FjVlVIamU1UXQwM3Zpb0dLOQpiWlJob1dibG5rNjFhOVNyVy9ZNVJNbTdUd2p1TzNoVC94cGdrUEs4dVZXeGFqZ1AzUm9mUlRCUnd3SURBUUFCCm80R2pNSUdnTUE0R0ExVWREd0VCL3dRRUF3SUZvREFkQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUIKQlFVSEF3SXdEQVlEVlIwVEFRSC9CQUl3QURBZEJnTlZIUTRFRmdRVXRPRXpUbkNyaE43SkZiNGtoVDg4OFdXVwo5blF3SHdZRFZSMGpCQmd3Rm9BVVJIRUZnajc1Y29lMDNNaFR2VTNaS0ozMVJQQXdJUVlEVlIwUkJCb3dHSWNFCmZ3QUFBWWNFckVnRUM0Y0VyRWdFREljRXJFZ0VEVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBVkczUkc4QTcKelovMlYxZEEyWUxBVTZJckR4bU8rWHNSY0NOa1RIMGNOeXNLMXB1bGUzN0ptT0hmaGFjQWRBL2Nwck9NWHZZYwpxK0RvKzFkUXY5Vi92b0tLaTd3TDJXS1J3ejJGVGd3ZUNpK2JlckVrQXJRSWl3a2owSjZCUVFQM1ZIdXQ2bmFuCnNYSnVKTkZLakwra2dDRWJzR2EvV3d4S2c1bW1aTnc5MHF3UHNQMTNXa2dpVk1JWmZSOGJnbTdycmdqRUtlZSsKQmZTYnhvSHlTMmlyRHNDNGFPUTBwa2MrOGFyc1RtYWxlU1Ewa21wUmg1QmlxRFpSaENsNkdHeExMZnFqaWZEVworQ0psZFRNK1A5d1VDaEVvYVFRTjN3L21MMUhpZ3kraUFYVnFUNWtGaUo3MGhkYVdEZkdUMFFVZFMzNmtNbCtmCkZPL25WRlg4bHZ2UlBBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  etcd-ca: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR2akNDQXFhZ0F3SUJBZ0lVWVVnWVdhMnpwUThOczRJTEQzaVR2OVZ1WG0wd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1pURUxNQWtHQTFVRUJoTUNRMDR4RVRBUEJnTlZCQWdUQ0ZOb1lXNW5TR0ZwTVJFd0R3WURWUVFIRXdoVAphR0Z1WjBoaGFURU1NQW9HQTFVRUNoTURhemh6TVEwd0N3WURWUVFMRXdSd1lXRnpNUk13RVFZRFZRUURFd3ByCmRXSmxjbTVsZEdWek1CNFhEVEUzTVRFeE1UQXlNREV3TUZvWERUSXlNVEV4TURBeU1ERXdNRm93WlRFTE1Ba0cKQTFVRUJoTUNRMDR4RVRBUEJnTlZCQWdUQ0ZOb1lXNW5TR0ZwTVJFd0R3WURWUVFIRXdoVGFHRnVaMGhoYVRFTQpNQW9HQTFVRUNoTURhemh6TVEwd0N3WURWUVFMRXdSd1lXRnpNUk13RVFZRFZRUURFd3ByZFdKbGNtNWxkR1Z6Ck1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBczhsNnFKSVhxQUpFVzlDbktOWEUKUSs5eVQ1OWxtQWNEOElNREpRbmpicEVUejJxbFltZGw2Zml6NEU5K0Y1a2N1MWpNRXRlejFKdC8zQWJ5SDF1KwpHcURwRU05SzhTYzcxb2pJQm9lV3J4L09jT1QxUXNHQVVqQngrOHBDSUdYNS9UQ1hEVTJpbG95T3lZOHRiUXR2ClEwa2I4YkpOK3RVeEZPTmtxVk1pZU0vQnVlRWwvbllyenlhK2NTU2w1dUIwQWVhWVlwU1VJYWUrekcyTkFtc2kKS08vMm9zVjBFVVZVbjNweEZUS3BFd2E2dFhmWE5jUnVXb2FwbmFuOGppTW5DZWNHdURjd2VTb21TM3BUYit1NQoydkg5ZkhUTEFTWDh3dmphdFN1ZDVwL3FhcU5OMGZJMmkxVExLOVMzN210QU9kUkxsSGx4Z25nOXZmakt4dDBHCmNRSURBUUFCbzJZd1pEQU9CZ05WSFE4QkFmOEVCQU1DQVFZd0VnWURWUjBUQVFIL0JBZ3dCZ0VCL3dJQkFqQWQKQmdOVkhRNEVGZ1FVUkhFRmdqNzVjb2UwM01oVHZVM1pLSjMxUlBBd0h3WURWUjBqQkJnd0ZvQVVSSEVGZ2o3NQpjb2UwM01oVHZVM1pLSjMxUlBBd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFLbVJCNk81SUZlaVVEaW51UFlXCmh2cVJlb2syRlJMTkUrSHJiMXJSUjYrdnRZNUhld3o4d0FzbW8xcTJCdTdmQ3N2dVhYQ0ZDNmVCbDR2K1VtS28KQlVXd2U4b3NOcUJVTm1UK2RFVkhDYVNGQlJiWmpqQlRlcTAwVWk5c1pUMGxOZmQvTVlYM2IyT21TakxBZkZhWQorYVFlaTF5amZwbUhuUFJTZ3BuV2d3NjJSdjczYnZNUUljR0Z0MitMRU5PdGlJZnk2RXMrVjN3VFlOYTFBcTVwCk40MCtWdENEbWkvN0FUcjU1MkhlTkl3TUlON21vZXc5RStoSGgwRGM4b1JKYkNVQXJ0Z0haR3NhcVB5RlZJK3QKOXVxUjcvN0Nlbm9wMndhcGFxd1hNMjMwUDdpdXZpM3ZMTkVlUms1SHNFU0UyUFdDcWw0LzNadGkvUktraGduNwpCa2c9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K

---

# This manifest installs the calico/node container, as well
# as the Calico CNI plugins and network config on
# each master and worker node in a Kubernetes cluster.
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: calico-node
  namespace: kube-system
  labels:
    k8s-app: calico-node
spec:
  selector:
    matchLabels:
      k8s-app: calico-node
  template:
    metadata:
      labels:
        k8s-app: calico-node
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        scheduler.alpha.kubernetes.io/tolerations: |
          [{"key": "dedicated", "value": "master", "effect": "NoSchedule" },
           {"key":"CriticalAddonsOnly", "operator":"Exists"}]
    spec:
      hostNetwork: true
      serviceAccountName: calico-node
      # Minimize downtime during a rolling upgrade or deletion; tell Kubernetes to do a "force
      # deletion": https://kubernetes.io/docs/concepts/workloads/pods/pod/#termination-of-pods.
      terminationGracePeriodSeconds: 0
      containers:
        # Runs calico/node container on each Kubernetes node.  This
        # container programs network policy and routes on each
        # host.
        - name: calico-node
          image: calico/node:v2.6.2
          env:
            # The location of the Calico etcd cluster.
            - name: ETCD_ENDPOINTS
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_endpoints
            # Choose the backend to use.
            - name: CALICO_NETWORKING_BACKEND
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: calico_backend
            # Cluster type to identify the deployment type
            - name: CLUSTER_TYPE
              value: "k8s,bgp"
            # Disable file logging so `kubectl logs` works.
            - name: CALICO_DISABLE_FILE_LOGGING
              value: "true"
            # Set Felix endpoint to host default action to ACCEPT.
            - name: FELIX_DEFAULTENDPOINTTOHOSTACTION
              value: "ACCEPT"
            # Configure the IP Pool from which Pod IPs will be chosen.
            - name: CALICO_IPV4POOL_CIDR
              value: "10.1.0.0/16"
            - name: CALICO_IPV4POOL_IPIP
              value: "always"
            # Disable IPv6 on Kubernetes.
            - name: FELIX_IPV6SUPPORT
              value: "false"
            # Set Felix logging to "info"
            - name: FELIX_LOGSEVERITYSCREEN
              value: "info"
            # Set MTU for tunnel device used if ipip is enabled
            - name: FELIX_IPINIPMTU
              value: "1440"
            # Location of the CA certificate for etcd.
            - name: ETCD_CA_CERT_FILE
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_ca
            # Location of the client key for etcd.
            - name: ETCD_KEY_FILE
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_key
            # Location of the client certificate for etcd.
            - name: ETCD_CERT_FILE
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_cert
            # Auto-detect the BGP IP address.
            - name: IP
              value: ""
            - name: FELIX_HEALTHENABLED
              value: "true"
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: 250m
          livenessProbe:
            httpGet:
              path: /liveness
              port: 9099
            periodSeconds: 10
            initialDelaySeconds: 10
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /readiness
              port: 9099
            periodSeconds: 10
          volumeMounts:
            - mountPath: /lib/modules
              name: lib-modules
              readOnly: true
            - mountPath: /var/run/calico
              name: var-run-calico
              readOnly: false
            - mountPath: /calico-secrets
              name: etcd-certs
        # This container installs the Calico CNI binaries
        # and CNI network config file on each node.
        - name: install-cni
          image: calico/cni:v1.11.0
          command: ["/install-cni.sh"]
          env:
            # The location of the Calico etcd cluster.
            - name: ETCD_ENDPOINTS
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_endpoints
            # The CNI network config to install on each node.
            - name: CNI_NETWORK_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: cni_network_config
          volumeMounts:
            - mountPath: /host/opt/cni/bin
              name: cni-bin-dir
            - mountPath: /host/etc/cni/net.d
              name: cni-net-dir
            - mountPath: /calico-secrets
              name: etcd-certs
      volumes:
        # Used by calico/node.
        - name: lib-modules
          hostPath:
            path: /lib/modules
        - name: var-run-calico
          hostPath:
            path: /var/run/calico
        # Used to install CNI.
        - name: cni-bin-dir
          hostPath:
            path: /opt/cni/bin
        - name: cni-net-dir
          hostPath:
            path: /etc/cni/net.d
        # Mount in the etcd TLS secrets.
        - name: etcd-certs
          secret:
            secretName: calico-etcd-secrets

---

# This manifest deploys the Calico Kubernetes controllers.
# See https://github.com/projectcalico/kube-controllers
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: calico-kube-controllers
  namespace: kube-system
  labels:
    k8s-app: calico-kube-controllers
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ''
    scheduler.alpha.kubernetes.io/tolerations: |
      [{"key": "dedicated", "value": "master", "effect": "NoSchedule" },
       {"key":"CriticalAddonsOnly", "operator":"Exists"}]
spec:
  # The controllers can only have a single active instance.
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      name: calico-kube-controllers
      namespace: kube-system
      labels:
        k8s-app: calico-kube-controllers
    spec:
      # The controllers must run in the host network namespace so that
      # it isn't governed by policy that would prevent it from working.
      hostNetwork: true
      serviceAccountName: calico-kube-controllers
      containers:
        - name: calico-kube-controllers
          image: calico/kube-controllers:v1.0.0
          env:
            # The location of the Calico etcd cluster.
            - name: ETCD_ENDPOINTS
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_endpoints
            # Location of the CA certificate for etcd.
            - name: ETCD_CA_CERT_FILE
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_ca
            # Location of the client key for etcd.
            - name: ETCD_KEY_FILE
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_key
            # Location of the client certificate for etcd.
            - name: ETCD_CERT_FILE
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_cert
          volumeMounts:
            # Mount in the etcd TLS secrets.
            - mountPath: /calico-secrets
              name: etcd-certs
      volumes:
        # Mount in the etcd TLS secrets.
        - name: etcd-certs
          secret:
            secretName: calico-etcd-secrets

---

# This deployment turns off the old "policy-controller". It should remain at 0 replicas, and then
# be removed entirely once the new kube-controllers deployment has been deployed above.
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: calico-policy-controller
  namespace: kube-system
  labels:
    k8s-app: calico-policy
spec:
  # Turn this deployment off in favor of the kube-controllers deployment above.
  replicas: 0
  strategy:
    type: Recreate
  template:
    metadata:
      name: calico-policy-controller
      namespace: kube-system
      labels:
        k8s-app: calico-policy
    spec:
      hostNetwork: true
      serviceAccountName: calico-kube-controllers
      containers:
        - name: calico-policy-controller
          image: calico/kube-controllers:v1.0.0
          env:
            # The location of the Calico etcd cluster.
            - name: ETCD_ENDPOINTS
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_endpoints
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: calico-kube-controllers
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: calico-node
  namespace: kube-system
```
