### ISSUE TITLE
Exposing the IPIP tunnel value in the ConfigMap instead hardcoding in the DaemonSet

### ISSUE THREAD

**Issue by igoratencompass** [projectcalico/calico#1482]
This is a feature request.
### Description
I have noticed in `calico.yml` file that the Calico MTU is an option in the` ConfigMap`:
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: calico-config
  namespace: kube-system
data:
  cni_network_config: |-
    {
        "name": "k8s-pod-network",
        "cniVersion": "0.1.0",
        "type": "calico",
        ...
        "mtu": 1500,
        ...
    }
```
but then in the `DaemonSet` there is another environment value for the ipip tunnel that I think should be closely coupled with the above one:
```
kind: DaemonSet
apiVersion: extensions/v1beta1
...
      containers:
        # Runs calico/node container on each Kubernetes node.  This
        # container programs network policy and routes on each
        # host.
        - name: calico-node
          env:
          ...
            # Set MTU for tunnel device used if ipip is enabled
            - name: FELIX_IPINIPMTU
              value: "1440"
          ...
```
and maybe worth moving this variable into the `ConfigMap` too. The reasoning behind this is the users in AWS for example would for sure want the MTU bumped to 9000 after which the FELIX_IPINIPMTU would/should follow with 8940 so they don't miss on improved tunnel performance.

Also maybe worth mentioning this fact in the documentation since as it is now it can easily happen that users would modify the mtu value but easily oversee the FELIX_IPINIPMTU one.
