### ISSUE TITLE
Few pods are rebooting constantlly with calico v3.0.1

### ISSUE THREAD

**Issue by amit2277** [projectcalico/calico#1581]
Hello members, 

We have used ipxe/matchbox and bootkube to setup k8s cluster with versions given below. 
Coreos: 1576.4.0
Kubelet: v1.9.0
Etcdv3: 3.2
Calico:2.6.2 & 3.0.1

While using calico v2.6.2, it is working fine. When we tried to upgrade calico with v3.0.1. Did little changes as per our requirements for etcd key and IP range but listed bellow pods keep crashing and restarting. 
kube-controller-manager, Kube-scheduler, Kube-DNS and Kube-API server are not stable. 

We have not done any changes in kubeconfig files. only changed calico.yaml file. which is attached below. 

old calico file set used 
[v2.6.2.zip](https://github.com/projectcalico/calico/files/1606656/v2.6.2.zip)

new calico file set used. 
[v3.0.1.zip](https://github.com/projectcalico/calico/files/1606657/v3.0.1.zip)

Latest **_calico.yaml_** file (Reference used from https://docs.projectcalico.org/v3.0/getting-started/kubernetes/installation/hosted/hosted)

```
# Calico Version v3.0.1
# https://docs.projectcalico.org/v3.0/releases#v3.0.1
# This manifest includes the following component versions:
#   calico/node:v3.0.1
#   calico/cni:v2.0.0
#   calico/kube-controllers:v2.0.0

# This ConfigMap is used to configure a self-hosted Calico installation.
kind: ConfigMap
apiVersion: v1
metadata:
  name: calico-config
  namespace: kube-system
data:
  # Configure this with the location of your etcd cluster.
  etcd_endpoints: "https://node1.example.com:2379,https://node2.example.com:2379,https://node3.example.com:2379"

  # Configure the Calico backend to use.
  calico_backend: "bird"
  kubeconfig: "/etc/kubernetes/kubeconfig"
  etcd_ca_dir: "/etc/ssl/etcd"

  # The CNI network configuration to install on each node.
  cni_network_config: |-
    {
      "name": "k8s-pod-network",
      "cniVersion": "0.3.0",
      "plugins": [
        {
            "type": "calico",
            "etcd_endpoints": "__ETCD_ENDPOINTS__",
            "etcd_key_file": "__ETCD_KEY_FILE__",
            "etcd_cert_file": "__ETCD_CERT_FILE__",
            "etcd_ca_cert_file": "__ETCD_CA_CERT_FILE__",
            "log_level": "info",
            "ipam": {
                "type": "host-local",
                "subnet": "usePodCidr"
            },
            "policy": {
                "type": "k8s",
                "k8s_api_root": "https://__KUBERNETES_SERVICE_HOST__:__KUBERNETES_SERVICE_PORT__",
                "k8s_auth_token": "__SERVICEACCOUNT_TOKEN__"
            },
            "kubernetes": {
                "kubeconfig": "__KUBECONFIG_FILEPATH__"
            }
        },
        {
          "type": "portmap",
          "snat": true,
          "capabilities": {"portMappings": true}
        }
      ]
    }

  # If you're using TLS enabled etcd uncomment the following.
  # You must also populate the Secret below with these files.
  etcd_ca: "/calico-secrets/etcd-ca"   # "/calico-secrets/etcd-ca"
  etcd_cert: "/calico-secrets/etcd-cert" # "/calico-secrets/etcd-cert"
  etcd_key: "/calico-secrets/etcd-key"  # "/calico-secrets/etcd-key"

---

# The following contains k8s Secrets for use with a TLS enabled etcd cluster.
# For information on populating Secrets, see http://kubernetes.io/docs/user-guide/secrets/
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: calico-etcd-secrets
  namespace: kube-system
data:
  # Populate the following files with etcd TLS configuration if desired, but leave blank if
  # not using TLS for etcd.
  # This self-hosted install expects three files with the following names.  The values
  # should be base64 encoded strings of the entire contents of each file.
    etcd-key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBM1AxRC9GSGJBR1RmWG90WkZmYm5JNHdsZXdzR3I2Q3A5Z210czl2NGI0NmRlOXliClBXa3FjQVhCVmZiOWxERDNIYVdFd0c3MVh6cUh6NXo3dHZFbFpMditKMTVjS0xHRFNyNVl5aG04cjBZK2h4TUcKUkZHK0s2WHAyZy8reHNoV1podzk3TDY5WjY2b3pSWGtpYjVSM1Zaait5Q3VjdkVzQmVjTGZsdDZWVk5DU2hFVAovTXBpd0tPZmQ4czhwU1FqMFJ1OXNzQTdmQ0dQNjdXNUhxZmpadEZ5OXRGWldkZk9ONDFlaTY3RXo1UE1sMUdZClAvUnUzVW9LenhCSkNSRWhneHRwQ2xHRGQxNy8vTVVMajlhME03U2J2N1VhVnJtbEFKUlN1R09GMkNTT0VydmoKSWFFaWVDUGFEaGx2RU1HQldOc1pFM3lBS2dpaXV5aE1LT3JRRXdJREFRQUJBb0lCQVFEUTVwbGQ3QU1hWEVETApIdThYMUU2clM5QWlnRW5SdkE3dWhqZXR6a01MTWNXdFVOMXZML3J0Nm9MWXdLTDFjMVFtc2xETG1CaGI3UGgxClNmQ28vMHhaN1Z4VDJ0OURtSXFFSFd2Um9JSzlMYW51QmczbWgxODk0NWtzaWZKTjl4TzFjdjBXenpnOHl0N0cKLytzS1N0OFlYSkltMHI0VjZlV3pyclV1dlVyblhBcjdKaUxQMytnck5ET3M1MU9hRkE3MGljaXVZa0E2dTVYcApIVFc2eCtqdDl1a2c2WDlEUENKaXFqa1UwWEY4N21KTTJoZGhNMis4NVYwS2NORWNPVFRUcVBkK2l2R1Q0NHJrCjZsM1NzYkUrKzNBYkN3Mjk5TWY3akdxdjV3aGZBSGdMa0ZWeUhOZjQ2c0p1em1QTlBpNUJaTEhJZWJZNVlTeW4KdzV4UHZVQUJBb0dCQU9HSTdid0xmMHh4ekhsZjN4SkJsTStnL1Rvcis3NlI2R1Q1VHZScS8wTGo5WTl5dmFhYQpnWTBhTnR1TjA0TkNMZDE1VGVvcUNSeEhkaVJTZjl4Z2VMeFlGMFAvTEV3aXJEZXUwS1RPMGR6Q2hvNlMzMVd2CjJMNnd1blNLVXRhSEE4RVRrS2tEaTFscUw3VnRWZDdGTUttVVhFRGFLeGRzMXpvNGdJN256OEVSQW9HQkFQclgKSm1TdGxHQlB4L0ppNnhzTFZITFVnMGtjemhTWXlUc3hJZUZ0MmF0bFh6czRHV0lxZHFDNURlOHBMMVJGRVhEOAorSy8wMFJJZS95cEJpQnk4cHQ3RWk4U2RwYytJdGRRcm5uQ05IcjRkOURRNUJUUDBGMXE5aE5FOGlaT0YrL0g0CnlZRDd3dmVDa2d2dFkzeWNXZHBwK0l6dUIrVFRUNm9QYWhwRDZMN2pBb0dCQU1qWXd6WVNXeFE5eDZWVFhubUkKazdodm12TkNGaGU1SW1kQnFqRjZVOFpDOGYwRVpxWkd0Qlp2Z09qM0hhU251K2FlejJjNGRoS01CVWNGZlQ1SgpYMXdEYXZ5djhzZituTFdkNWNyUE1BOVQ0TFo1VDVDa1gvWTV0bUp3aUtMcGE4dDIyLzNYM1RJTW9WNEZkMUpDCjh6b2htQ0pjNThFZHVYSHN2WGdHTW5xeEFvR0JBSk5nWDExZG9zU25lem1OSnNjZjlBRDNuUjhTdm4zWmVybTkKVjBPa2ovUWt2andEN040QlJ1dU5ib05xdGpVVDAzaUlHUEVBck9teHJvZThNdVYzYmErSzJQZXZEQ0dRR0F6TgpoK3htN1g0VUNVdTVpTFlLbnNJZ2dXMlIzTjhCSkpMNWNpTEhTTGkxVFd1V2tSSkFwb1l1SnV0ZVd1TDF5R09KClpQU0RtN2F6QW9HQUVRaGcweFQ3MGdMRTJCOHRkKzU1QVpVTlFiQm9NTEdUYkROeG9WdEoyVG10TCtVSldhVEYKK3ZYWVNNMkNrcWpsTXV0ZGZXamE3c1IzZXE0dVRHUUFwaU5hbVFwK29pUGplRkliREFid0VMTmZzOVBHaDRRTQpmTDNqeDlhME1kWXRLa0ZScnRTSk8wYzg2U1d2U1RDU0hxb3VDSWJJMXRta2dQSDlkVlM0NnRVPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
    etcd-cert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURjRENDQWxpZ0F3SUJBZ0lJV2RUZDNzbHhrSWt3RFFZSktvWklodmNOQVFFTEJRQXdWREV0TUNzR0ExVUUKQ2hNa1ptTXhZVGhpT1RNdE1qWXpaQzAwWVdWakxUZzJOVGd0TmpCbFpqUTBaV1ZpTjJZd01SRXdEd1lEVlFRTApFd2hpYjI5MGEzVmlaVEVRTUE0R0ExVUVBeE1IYTNWaVpTMWpZVEFlRncweE56RXlNall4TVRRMk16SmFGdzB4Ck9ERXlNall4TVRRMk16VmFNQ1V4RFRBTEJnTlZCQW9UQkdWMFkyUXhGREFTQmdOVkJBTVRDMlYwWTJRdGMyVnkKZG1WeU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBM1AxRC9GSGJBR1RmWG90WgpGZmJuSTR3bGV3c0dyNkNwOWdtdHM5djRiNDZkZTl5YlBXa3FjQVhCVmZiOWxERDNIYVdFd0c3MVh6cUh6NXo3CnR2RWxaTHYrSjE1Y0tMR0RTcjVZeWhtOHIwWStoeE1HUkZHK0s2WHAyZy8reHNoV1podzk3TDY5WjY2b3pSWGsKaWI1UjNWWmoreUN1Y3ZFc0JlY0xmbHQ2VlZOQ1NoRVQvTXBpd0tPZmQ4czhwU1FqMFJ1OXNzQTdmQ0dQNjdXNQpIcWZqWnRGeTl0RlpXZGZPTjQxZWk2N0V6NVBNbDFHWVAvUnUzVW9LenhCSkNSRWhneHRwQ2xHRGQxNy8vTVVMCmo5YTBNN1NidjdVYVZybWxBSlJTdUdPRjJDU09FcnZqSWFFaWVDUGFEaGx2RU1HQldOc1pFM3lBS2dpaXV5aE0KS09yUUV3SURBUUFCbzNVd2N6QU9CZ05WSFE4QkFmOEVCQU1DQmFBd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSApBd0VHQ0NzR0FRVUZCd01DTUVJR0ExVWRFUVE3TURtQ0VXNXZaR1V4TG1WNFlXMXdiR1V1WTI5dGdoRnViMlJsCk1pNWxlR0Z0Y0d4bExtTnZiWUlSYm05a1pUTXVaWGhoYlhCc1pTNWpiMjB3RFFZSktvWklodmNOQVFFTEJRQUQKZ2dFQkFKVWhaU2N2MGpkL1lFYmU0Y0JkMXJtSFBiRlVnampGU0V1WnJMdVRhb2VEUUluMExLNU1Yc2xQRlN1YQpvSFNFZ3Q1NVU3RkdMZ1ZJSmtvU0tUcSsxbU03NGNqbTJETFhORUR2VG8yZ2VuYW5YQk1WcksvaWJPVVVNZ3RzCnFMV3NLaXdUWFBGV05id3cwN250QjV1L0RxTStNZExiOUNSNjVMNGFweG41L05Kc2lRMWFibnY3c3dieEQrTVEKSlVCRjkxeUJOZjQwTVFXWnVRUFNSenlYbURlTkdJUDNiMXd2RzJzWnB6cHJoRnNGSEtpVlB2eVN6bU0rOWF1QgpSSmdHeFFXV2I3VGdQZlpyWlB2TEdEQ1NuVzROQm9ZUmZjMklrSUVjR2pGaE1XNmUrdHpCdUIyTnlkaDNmdVVnCjh1WnZsZDF4Wkx0WUtoNXhDT1g4REtiSTZTMD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    etcd-ca: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURSakNDQWk2Z0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREJVTVMwd0t3WURWUVFLRXlSbVl6RmgKT0dJNU15MHlOak5rTFRSaFpXTXRPRFkxT0MwMk1HVm1ORFJsWldJM1pqQXhFVEFQQmdOVkJBc1RDR0p2YjNScgpkV0psTVJBd0RnWURWUVFERXdkcmRXSmxMV05oTUI0WERURTNNVEl5TmpFeE5EWXpNbG9YRFRJM01USXlOREV4Ck5EWXpNbG93VkRFdE1Dc0dBMVVFQ2hNa1ptTXhZVGhpT1RNdE1qWXpaQzAwWVdWakxUZzJOVGd0TmpCbFpqUTAKWldWaU4yWXdNUkV3RHdZRFZRUUxFd2hpYjI5MGEzVmlaVEVRTUE0R0ExVUVBeE1IYTNWaVpTMWpZVENDQVNJdwpEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTDJ4SUlZYjczbW9HTjc5MmwvRnVuNnJlNGlSCkV6ZVZKeE5VSzM4Q29WbDZiL0M2aU5VUG11RFAzVkJkV0YwelZkN2NRaGhidlgyRmdVNVBZcjJBaTNhaTVJU3gKSEdUZ0lqRmwwM2hWaUNJQVZUVHVUbmRyM0ZaQmZwRXpmbzMwMEZ2djMya1pFQm5nUlNqK2YvdktPVXFVL0Q3Sgo2aHdRK3VLbkdXeTVKR2huenVaL1FPRXZvaEJRVys4dXdESHBtZFNYREtkdHFxWGJRbmRnSDM0Nng0OVJjeUl0ClBkY1FUb1pHODFQaWgvSE9uS1locHlJUSt4bDNveVJxR21VSWQxNW9wbk8rUjNKSUxYK2hLVXFzdkNSUUlEV2gKdDdGVzI1d3ZrU2VZNnJHbmZEVWNwMWR1QnB6L01XWlpwVStqejdqbVlxOUF2Qmduc2wwakxLRjlIdDhDQXdFQQpBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3RFFZSktvWklodmNOCkFRRUxCUUFEZ2dFQkFMSVBYK2g2UFZGeXdIbGpaazZxNEt5bm9vN3IrMlJSdXEwWUw4cG55MWt2aTF1ejl3WE8KZUQvYUk5TVlOR3BPd1hneHlVVUg4bDU4OGF3Qk5jYzNuSGhRaVd3cjB5WmlpY1RLUTIwZCtYSnkzNnBMNDYzNgowakVMZjM0dDNaZEJJbXA1Qldra3lENU5xNngySCtFeGlaV2ZCL3h4VS9LU1h4WWlrZ3hmZHBMV2wzTENEMFdrCjJxQldMaGpldnI2bHJOZnkwbks1cG9jOGErZFZZNHl6Wk9BeDBoUmM0Ni83RjRyQkZiWGwvSE5aUXRzcXYwcUoKbXc3WUJnZGRzSm5wekZtYmRaWUxPdTZaNlRla3pWdjF3eDhoR1oxb1YveXFjMjNKT01JV09PckhJd1FUa2ZkcgpFR2RlcGhyQllpaTdDL1d4Nnk5cVlwc0pQeXBrSi8vdTh1ND0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=

---

# This manifest installs the calico/node container, as well
# as the Calico CNI plugins and network config on
# each master and worker node in a Kubernetes cluster.
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: calico-node
  namespace: kube-system
  labels:
    k8s-app: calico-node
spec:
  selector:
    matchLabels:
      k8s-app: calico-node
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        k8s-app: calico-node
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        scheduler.alpha.kubernetes.io/tolerations: |
          [{"key": "dedicated", "value": "master", "effect": "NoSchedule" },
           {"key":"CriticalAddonsOnly", "operator":"Exists"}]
    spec:
      hostNetwork: true
      serviceAccountName: calico-node
      # Minimize downtime during a rolling upgrade or deletion; tell Kubernetes to do a "force
      # deletion": https://kubernetes.io/docs/concepts/workloads/pods/pod/#termination-of-pods.
      terminationGracePeriodSeconds: 0
      containers:
        # Runs calico/node container on each Kubernetes node.  This
        # container programs network policy and routes on each
        # host.
        - name: calico-node
          image: quay.io/calico/node:v3.0.1
          env:
            # The location of the Calico etcd cluster.
            - name: ETCD_ENDPOINTS
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_endpoints
            # Choose the backend to use.
            - name: CALICO_NETWORKING_BACKEND
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: calico_backend
            # Cluster type to identify the deployment type
            - name: CLUSTER_TYPE
              value: "k8s,bgp"
            # Disable file logging so `kubectl logs` works.
            - name: CALICO_DISABLE_FILE_LOGGING
              value: "true"
            # Set noderef for node controller.
            - name: CALICO_K8S_NODE_REF
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            # Set Felix endpoint to host default action to ACCEPT.
            - name: FELIX_DEFAULTENDPOINTTOHOSTACTION
              value: "ACCEPT"
            # Configure the IP Pool from which Pod IPs will be chosen.
            - name: CALICO_IPV4POOL_CIDR
              value: "172.16.0.0/16"
            - name: CALICO_IPV4POOL_IPIP
              value: "Always"
            # Disable IPv6 on Kubernetes.
            - name: FELIX_IPV6SUPPORT
              value: "false"
            # Set Felix logging to "info"
            - name: FELIX_LOGSEVERITYSCREEN
              value: "info"
            # Location of the CA certificate for etcd.
            - name: ETCD_CA_CERT_FILE
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_ca
            # Location of the client key for etcd.
            - name: ETCD_KEY_FILE
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_key
            # Location of the client certificate for etcd.
            - name: ETCD_CERT_FILE
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_cert
            # Auto-detect the BGP IP address.
            - name: IP
              value: "autodetect"
            - name: IP_AUTODETECTION_METHOD
              value: "can-reach=192.168.53.80"
            - name: FELIX_HEALTHENABLED
              value: "true"
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: 250m
          livenessProbe:
            httpGet:
              path: /liveness
              port: 9099
            periodSeconds: 10
            initialDelaySeconds: 10
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /readiness
              port: 9099
            periodSeconds: 10
          volumeMounts:
            - mountPath: /lib/modules
              name: lib-modules
              readOnly: true
            - mountPath: /var/run/calico
              name: var-run-calico
              readOnly: false
            - mountPath: /calico-secrets
              name: etcd-certs
        # This container installs the Calico CNI binaries
        # and CNI network config file on each node.
        - name: install-cni
          image: quay.io/calico/cni:v2.0.0
          command: ["/install-cni.sh"]
          env:
            # Name of the CNI config file to create.
            - name: CNI_CONF_NAME
              value: "10-calico.conflist"
            # The location of the Calico etcd cluster.
            - name: ETCD_ENDPOINTS
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_endpoints
            # The CNI network config to install on each node.
            - name: CNI_NETWORK_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: cni_network_config
            - name: CNI_NET_DIR
              value: "/etc/kubernetes/cni/net.d"
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - mountPath: /host/opt/cni/bin
              name: cni-bin-dir
            - mountPath: /host/etc/cni/net.d
              name: cni-net-dir
            - mountPath: /calico-secrets
              name: etcd-certs
      volumes:
        # Used by calico/node.
        - name: lib-modules
          hostPath:
            path: /lib/modules
        - name: var-run-calico
          hostPath:
            path: /var/run/calico
        # Used to install CNI.
        - name: cni-bin-dir
          hostPath:
            path: /opt/cni/bin
        - name: cni-net-dir
          hostPath:
            path: /etc/kubernetes/cni/net.d
        # Mount in the etcd TLS secrets.
        - name: etcd-certs
          secret:
            secretName: calico-etcd-secrets

---

# This manifest deploys the Calico Kubernetes controllers.
# See https://github.com/projectcalico/kube-controllers
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: calico-kube-controllers
  namespace: kube-system
  labels:
    k8s-app: calico-kube-controllers
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ''
    scheduler.alpha.kubernetes.io/tolerations: |
      [{"key": "dedicated", "value": "master", "effect": "NoSchedule" },
       {"key":"CriticalAddonsOnly", "operator":"Exists"}]
spec:
  # The controllers can only have a single active instance.
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      name: calico-kube-controllers
      namespace: kube-system
      labels:
        k8s-app: calico-kube-controllers
    spec:
      # The controllers must run in the host network namespace so that
      # it isn't governed by policy that would prevent it from working.
      hostNetwork: true
      serviceAccountName: calico-kube-controllers
      containers:
        - name: calico-kube-controllers
          image: quay.io/calico/kube-controllers:v2.0.0
          env:
            # The location of the Calico etcd cluster.
            - name: ETCD_ENDPOINTS
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_endpoints
            # Location of the CA certificate for etcd.
            - name: ETCD_CA_CERT_FILE
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_ca
            # Location of the client key for etcd.
            - name: ETCD_KEY_FILE
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_key
            # Location of the client certificate for etcd.
            - name: ETCD_CERT_FILE
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_cert
            # Choose which controllers to run.
            - name: ENABLED_CONTROLLERS
              value: policy,profile,workloadendpoint,node
          volumeMounts:
            # Mount in the etcd TLS secrets.
            - mountPath: /calico-secrets
              name: etcd-certs
      volumes:
        # Mount in the etcd TLS secrets.
        - name: etcd-certs
          secret:
            secretName: calico-etcd-secrets

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: calico-kube-controllers
  namespace: kube-system

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: calico-node
  namespace: kube-system
```

I would highly appreciate if you please guide me to resolve this issue.

Thanks in advance
