### ISSUE TITLE
ipBlock ingress rule selector is not working, while others (label based) are

### ISSUE THREAD

**Issue by piontec** [projectcalico/calico#1733]
## Expected Behavior
I have a simple NetworkPolicy defined by k8s NetworkPolicy object:
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: test-netpol
  name: echo-netpol
spec:
  podSelector:
    matchLabels:
      app: piontec-echo
  policyTypes:
  - Ingress
  ingress:
  - from:
    - ipBlock:
        cidr: 10.0.0.0/8
    ports:
    - protocol: TCP
      port: 8080
```
I expect this to generate calico policy, which allows traffic from 10.0.0.0/8 prefix.

## Current Behavior
The NetworkPolicy object above generates the following policy in calico:
```
# calicoctl get policies test-netpol.echo-netpol -o yaml
- apiVersion: v1
  kind: policy
  metadata:
    name: test-netpol.echo-netpol
  spec:
    egress:
    - action: allow
      destination: {}
      source: {}
    order: 1000
    selector: calico/k8s_ns == 'test-netpol' && app == 'piontec-echo'
```
which seems to be missing a whole "ingress" block in "spec".

## Steps to Reproduce (for bugs)
1. Install kubernetes 1.8.5 with calico 1.5.0.
2. Create Network Policy object in k8s as above.
Please let me know how to provide more detailed debug info for you.

## Your Environment
* Calico version:
```
# calicoctl version
Client Version:    v1.5.0
Build date:        2017-08-29T04:02:07+0000
Git commit:        118b8ae1
Cluster Version:   v2.5.0
Cluster Type:      kubespray,bgp
```
* Orchestrator version (e.g. kubernetes, mesos, rkt):
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1+coreos.0", GitCommit:"59359d9fdce74738ac9a672d2f31e9a346c5cece", GitTreeState:"clean", BuildDate:"2017-10-12T21:53:13Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.5+coreos.0", GitCommit:"b8e596026feda7b97f4337b115d1a9a250afa8ac", GitTreeState:"clean", BuildDate:"2017-12-12T11:01:08Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
* Operating System and version:
Ubuntu 16.04.4 LTS with kernel 4.14.16-041416-generic
