### ISSUE TITLE
egress rules are not working when defined by NetworkPolicy object

### ISSUE THREAD

**Issue by piontec** [projectcalico/calico#1734]
## Expected Behavior
Since both kubernetes 1.8 and calico 1.5 support egress rules definition, I suppose examples below should be working.

## Current Behavior
I tested the following NetworkPolicy objects created with k8s.

1. Deny all egress
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: test-netpol
  name: echo-netpol-tester
spec:
  podSelector: {}
  policyTypes:
  - Egress
```

2. Allow egress by CIDR block
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: test-netpol
  name: echo-netpol-tester
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 10.0.0.0/8
```

3. Allow egress by label
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: test-netpol
  name: echo-netpol-tester
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: piontec-echo
```

Each one of them generates calico policy with "allow all egress":
```
- apiVersion: v1
  kind: policy
  metadata:
    name: test-netpol.echo-netpol-tester
  spec:
    egress:
    - action: allow
      destination: {}
      source: {}
    order: 1000
    selector: calico/k8s_ns == 'test-netpol'
    types:
    - ingress
    - egress
```

## Steps to Reproduce (for bugs)
1. Install kubernetes 1.8.5 with calico 1.5.0.
2. Create Network Policy objects in k8s as above.
Please let me know how to provide more detailed debug info for you.

## Your Environment
* Calico version:
```
# calicoctl version
Client Version:    v1.5.0
Build date:        2017-08-29T04:02:07+0000
Git commit:        118b8ae1
Cluster Version:   v2.5.0
Cluster Type:      kubespray,bgp
```
* Orchestrator version (e.g. kubernetes, mesos, rkt):
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1+coreos.0", GitCommit:"59359d9fdce74738ac9a672d2f31e9a346c5cece", GitTreeState:"clean", BuildDate:"2017-10-12T21:53:13Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.5+coreos.0", GitCommit:"b8e596026feda7b97f4337b115d1a9a250afa8ac", GitTreeState:"clean", BuildDate:"2017-12-12T11:01:08Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
* Operating System and version:
Ubuntu 16.04.4 LTS with kernel 4.14.16-041416-generic
