### ISSUE TITLE
Confusing profile example in docs

### ISSUE THREAD

**Issue by tomdee** [projectcalico/calico#1766]
The example on https://docs.projectcalico.org/v3.0/reference/calicoctl/resources/profile

The example
```
apiVersion: projectcalico.org/v3
kind: Profile
metadata:
  name: profile1
  labels:
    profile: profile1 
spec:
  ingress:
  - action: Deny
    source:
      nets:
      - 10.0.20.0/24
  - action: Allow
    source:
      selector: profile == 'profile1'
  egress:
  - action: Allow 

```

It's kinda confusing having a label called "profile: profile1" and a selector referecing it. It makes it seems like profile is some kind of special selector when it's just a label.
