### ISSUE TITLE
container unreachable by ping from remote host

### ISSUE THREAD

**Issue by tykytyzy** [projectcalico/calico#1904]
I'm trying to configure my mesos tasks with calico network, the tasks will always suspend at deploying status and finally re-deployed due to healthcheck failure.

New containers are reachable only from host nodes(ping), while ping from other nodes -- say marathon master nodes, it always got no response. Net captures indicates the container host node received the ping packets, but somehow got no response when forwarding the packets to calico network.

My ping test environment is as below: 

Mesos physical network: 192.168.3.0/24
Calico network: 10.88.0.0/16

Test ping from a marathon host 192.168.3.157 to a container 10.88.85.31, which is hosted on mesos agent node 192.168.3.220, net capture screenshot as below:
![image](https://user-images.githubusercontent.com/8538835/38859434-97ad0b82-4260-11e8-9741-fc1941d8ffbf.png)

Calico cluster info are as below:
calico nodes:
```
- apiVersion: v1
  kind: node
  metadata:
    name: mesos-agent-1
  spec:
    bgp:
      ipv4Address: 192.168.3.220/32
- apiVersion: v1
  kind: node
  metadata:
    name: mesos-master-2
  spec:
    bgp:
      ipv4Address: 192.168.3.209/32
- apiVersion: v1
  kind: node
  metadata:
    name: mesos-master-3
  spec:
    bgp:
      ipv4Address: 192.168.3.213/32
- apiVersion: v1
  kind: node
  metadata:
    name: mesos-master-1
  spec:
    bgp:
      ipv4Address: 192.168.3.157/32
```

node status is ok on hosts
```
IPv4 BGP status
+---------------+-------------------+-------+----------+-------------+
| PEER ADDRESS  |     PEER TYPE     | STATE |  SINCE   |    INFO     |
+---------------+-------------------+-------+----------+-------------+
| 192.168.3.209 | node-to-node mesh | up    | 03:21:22 | Established |
| 192.168.3.213 | node-to-node mesh | up    | 03:20:24 | Established |
| 192.168.3.220 | node-to-node mesh | up    | 03:29:12 | Established |
+---------------+-------------------+-------+----------+-------------+
```

ip pool:
```
- apiVersion: v1
  kind: ipPool
  metadata:
    cidr: 10.88.0.0/16
  spec:
    nat-outgoing: true
- apiVersion: v1
  kind: ipPool
  metadata:
    cidr: fd80:24e2:f998:72d6::/64
  spec: {}
```

workloadendpoint
```
- apiVersion: v1
  kind: workloadEndpoint
  metadata:
    name: 8e3b4cb75f8ca9bdeaa97bb851b22dd63aeafffa06c4572697911d95de91fb9b
    node: ln-update-mesos-master-1
    orchestrator: libnetwork
    workload: libnetwork
  spec:
    interfaceName: cali8e3b4cb75f8
    ipNetworks:
    - 10.88.85.37/32
    mac: ee:ee:ee:ee:ee:ee
    profiles:
    - calico-net

```
The containers are created and able to run so I don't think its a problem of task json, all the mesos master/agents are configured with calico nodes, and the route list seems been properly maintained.

route list on the marathon host 192.168.3.157
```
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         192.168.3.1     0.0.0.0         UG    0      0        0 eth0
10.88.85.0      docker3.mxnavi. 255.255.255.192 UG    0      0        0 eth0
169.254.169.254 192.168.3.185   255.255.255.255 UGH   0      0        0 eth0
172.17.0.0      *               255.255.0.0     U     0      0        0 docker0
192.168.3.0     *               255.255.255.0   U     0      0        0 eth0

```
route list on the container host 192.168.3.220
```
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         192.168.3.1     0.0.0.0         UG    0      0        0 eth0
10.88.85.0      *               255.255.255.192 U     0      0        0 *
10.88.85.31     *               255.255.255.255 UH    0      0        0 cali7c1363ae754
169.254.169.254 192.168.3.185   255.255.255.255 UGH   0      0        0 eth0
172.17.0.0      *               255.255.0.0     U     0      0        0 docker0
192.168.3.0     *               255.255.255.0   U     0      0        0 eth0 

```

**Comment by tykytyzy** [comment]
The container recieved syn packet form marathon master but didn't reply to it.

netstat from marathon master

# netstat -antp | grep 10.88.85.54
tcp6       0      1 192.168.3.157:52957     10.88.85.54:80          SYN_SENT    11861/java 

netstat -antp 
# netstat -antp
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.11:38982        0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      1/nginx: master pro 
tcp        0      0 10.88.85.54:80          192.168.3.157:52954     SYN_RECV    -                   
tcp        0      0 10.88.85.54:80          192.168.3.213:41544     SYN_RECV    -                   
tcp        0      0 10.88.85.54:80          192.168.3.213:41547     SYN_RECV    -                   
tcp        0      0 10.88.85.54:80          192.168.3.157:52953     SYN_RECV    -                   
tcp        0      0 10.88.85.54:80          192.168.3.213:41546     SYN_RECV    -                   
tcp        0      0 10.88.85.54:80          192.168.3.213:41545     SYN_RECV    -              

and from the container, remote hosts are reachable

# ping 192.168.3.157
PING 192.168.3.157 (192.168.3.157) 56(84) bytes of data.
64 bytes from 192.168.3.157: icmp_seq=1 ttl=63 time=0.723 ms
64 bytes from 192.168.3.157: icmp_seq=2 ttl=63 time=0.728 ms
64 bytes from 192.168.3.157: icmp_seq=3 ttl=63 time=0.510 ms

although I allowed all traffics in the profile, still cannot reach containers from marathon master

profile

- apiVersion: v1
  kind: profile
  metadata:
    name: calico-net
  spec:
    egress:
    - action: allow
      destination:
        net: 0.0.0.0/0
      source:
        net: 0.0.0.0/0
    ingress:
    - action: allow
      destination:
        net: 0.0.0.0/0
      source:
        net: 0.0.0.0/0
		
net.ipv4.ip_forward is enabled on the container hosts, could it be the firewall rule mess that cause the problem?
Any suggestion pls let me know.

**Comment by tykytyzy** [comment]
The container recieved syn packet form marathon master but didn't reply to it.

netstat from marathon master

:/# netstat -antp | grep 10.88.85.54
tcp6       0      1 192.168.3.157:52957     10.88.85.54:80          SYN_SENT    11861/java 

netstat -antp 
:/# netstat -antp
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.11:38982        0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      1/nginx: master pro 
tcp        0      0 10.88.85.54:80          192.168.3.157:52954     SYN_RECV    -                   
tcp        0      0 10.88.85.54:80          192.168.3.213:41544     SYN_RECV    -                   
tcp        0      0 10.88.85.54:80          192.168.3.213:41547     SYN_RECV    -                   
tcp        0      0 10.88.85.54:80          192.168.3.157:52953     SYN_RECV    -                   
tcp        0      0 10.88.85.54:80          192.168.3.213:41546     SYN_RECV    -                   
tcp        0      0 10.88.85.54:80          192.168.3.213:41545     SYN_RECV    -              

and from the container, remote hosts are reachable

:/# ping 192.168.3.157
PING 192.168.3.157 (192.168.3.157) 56(84) bytes of data.
64 bytes from 192.168.3.157: icmp_seq=1 ttl=63 time=0.723 ms
64 bytes from 192.168.3.157: icmp_seq=2 ttl=63 time=0.728 ms
64 bytes from 192.168.3.157: icmp_seq=3 ttl=63 time=0.510 ms

although I allowed all traffics in the profile, still cannot reach containers from marathon master

profile

- apiVersion: v1
  kind: profile
  metadata:
    name: calico-net
  spec:
    egress:
    - action: allow
      destination:
        net: 0.0.0.0/0
      source:
        net: 0.0.0.0/0
    ingress:
    - action: allow
      destination:
        net: 0.0.0.0/0
      source:
        net: 0.0.0.0/0
		
net.ipv4.ip_forward is enabled on the container hosts, could it be the firewall rule mess that cause the problem?
Any suggestion pls let me know.

**Comment by tykytyzy** [comment]
### The container recieved syn packet form marathon master but didn't reply to it.

**netstat from marathon master**
:/# netstat -antp | grep 10.88.85.54
tcp6       0      1 192.168.3.157:52957     10.88.85.54:80          SYN_SENT    11861/java 

**netstat in container**
:/# netstat -antp
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.11:38982        0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      1/nginx: master pro 
tcp        0      0 10.88.85.54:80          192.168.3.157:52954     SYN_RECV    -                   
tcp        0      0 10.88.85.54:80          192.168.3.213:41544     SYN_RECV    -                   
tcp        0      0 10.88.85.54:80          192.168.3.213:41547     SYN_RECV    -                   
tcp        0      0 10.88.85.54:80          192.168.3.157:52953     SYN_RECV    -                   
tcp        0      0 10.88.85.54:80          192.168.3.213:41546     SYN_RECV    -                   
tcp        0      0 10.88.85.54:80          192.168.3.213:41545     SYN_RECV    -              

### and from the container, remote hosts are reachable

:/# ping 192.168.3.157
PING 192.168.3.157 (192.168.3.157) 56(84) bytes of data.
64 bytes from 192.168.3.157: icmp_seq=1 ttl=63 time=0.723 ms
64 bytes from 192.168.3.157: icmp_seq=2 ttl=63 time=0.728 ms
64 bytes from 192.168.3.157: icmp_seq=3 ttl=63 time=0.510 ms

### although I allowed all traffics in the profile, still cannot reach containers from marathon master

**profile**

- apiVersion: v1
  kind: profile
  metadata:
    name: calico-net
  spec:
    egress:
    - action: allow
      destination:
        net: 0.0.0.0/0
      source:
        net: 0.0.0.0/0
    ingress:
    - action: allow
      destination:
        net: 0.0.0.0/0
      source:
        net: 0.0.0.0/0
		
**net.ipv4.ip_forward is enabled on the container hosts, could it be the firewall rule mess that cause the problem?
Any suggestion pls let me know.**

**Comment by tykytyzy** [comment]
The container recieved syn packet form marathon master but didn't reply to it.

netstat from marathon master

```
:/# netstat -antp | grep 10.88.85.54
tcp6       0      1 192.168.3.157:52957     10.88.85.54:80          SYN_SENT    11861/java 
```

netstat -antp 
```
:/# netstat -antp
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.11:38982        0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      1/nginx: master pro 
tcp        0      0 10.88.85.54:80          192.168.3.157:52954     SYN_RECV    -                   
tcp        0      0 10.88.85.54:80          192.168.3.213:41544     SYN_RECV    -                   
tcp        0      0 10.88.85.54:80          192.168.3.213:41547     SYN_RECV    -                   
tcp        0      0 10.88.85.54:80          192.168.3.157:52953     SYN_RECV    -                   
tcp        0      0 10.88.85.54:80          192.168.3.213:41546     SYN_RECV    -                   
tcp        0      0 10.88.85.54:80          192.168.3.213:41545     SYN_RECV    -              
```

and from the container, remote hosts are reachable

```
:/# ping 192.168.3.157
PING 192.168.3.157 (192.168.3.157) 56(84) bytes of data.
64 bytes from 192.168.3.157: icmp_seq=1 ttl=63 time=0.723 ms
64 bytes from 192.168.3.157: icmp_seq=2 ttl=63 time=0.728 ms
64 bytes from 192.168.3.157: icmp_seq=3 ttl=63 time=0.510 ms
```

although I allowed all traffics in the profile, still cannot reach containers from marathon master

profile

```
- apiVersion: v1
  kind: profile
  metadata:
    name: calico-net
  spec:
    egress:
    - action: allow
      destination:
        net: 0.0.0.0/0
      source:
        net: 0.0.0.0/0
    ingress:
    - action: allow
      destination:
        net: 0.0.0.0/0
      source:
        net: 0.0.0.0/0
```
		
net.ipv4.ip_forward is enabled on the container hosts, could it be the firewall rule mess that cause the problem?
Any suggestion pls let me know.
