### ISSUE TITLE
Typha is missing tolerations

### ISSUE THREAD

**Issue by lwr20** [projectcalico/calico#1927]
I'm installing a k8s rig using: 
https://docs.projectcalico.org/v3.1/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/1.7/calico.yaml

Using these instructions:
https://docs.projectcalico.org/v3.1/getting-started/kubernetes/installation/calico#installing-with-the-kubernetes-api-datastoremore-than-50-nodes
(so I've edited the manifest to raise the number of Typhas to be >0)

## Expected Behavior
I expect that to work.

## Current Behavior
calico-node doesn't start - logs say:
```
2018-04-20 14:13:31.455 [INFO][71] sync_client.go 129: Connecting to Typha. address="10.99.27.206:5473" connID=0x0
2018-04-20 14:13:32.425 [INFO][71] health.go 150: Overall health summary=&health.HealthReport{Live:false, Ready:false}
2018-04-20 14:13:32.454 [ERROR][71] sync_client.go 132: Failed to connect to Typha, retrying... error=dial tcp 10.99.27.206:5473: getsockopt: connection refused
```
typha doesn't start (status=Pending) - describe says:
```
Warning  FailedScheduling  2m (x33 over 12m)  default-scheduler  0/1 nodes are available: 1 node(s) had taints that the pod didn't tolerate.
```
Looking at the nodes:
```
ubuntu@ip-10-0-1-91:~$ kubectl get no -o yaml | grep taint -A 5
    taints:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
  status:
    addresses:
    - address: 10.0.1.91
```

## Possible Solution
Looking at the calico.yaml manifest, I see calico-node has more tolerations than typha.  Given that calico-node needs typha to start, shouldn't those tolerations be the same?

## Steps to Reproduce (for bugs)
Run this on a single node setup by kubeadm.  
https://docs.projectcalico.org/v3.1/getting-started/kubernetes/installation/calico#installing-with-the-kubernetes-api-datastoremore-than-50-nodes
