### ISSUE TITLE
Problem: Calico containers can't reach each other until connection has been initiated in the other direction

### ISSUE THREAD

**Issue by justinrlee** [projectcalico/calico#1996]
(Based off discussion in calicousers #general slack channel, user "Justin Lee"))

## Issue
My Mesos containers (running on Calico) are unable to reach each other until a connection has been initiated in the other direction.  Feels like a conntrack issue but I don't understand iptables well enough to troubleshoot.

### For example:
Host A: 10.10.1.65
* Container X with Calico IP: 172.16.102.1
* tunl0: 172.16.102.0/32

Host B: 10.10.2.169
* Container Y with Calico IP: 172.16.14.2
* tunl0: 172.16.14.0/32

Container X cannot ping (or curl or anything else) container Y, unless one of the following has occurred:
* Container Y has pinged (initiated a connection to) Container X
* Host B has pinged tunl0 on Host A

## Setup
I'm running Calico on DC/OS 1.11.2 Enterprise, with all certificates (etcd, calico-node, docker, etc.) signed by the internal DC/OS CA, in AWS, across multiple availability zones in a single region.

This is using etcd 3.3.5, Calico Node Docker image v2.6.9 (which has Felix 2.6.7).  Apparently there was conntrack issue previously, but that was supposed to have been fixed in Felix 2.6.1.

Using a relatively default pool (IPIP enabled and active for cross-subnet).  All dest/src checks have been disabled:

```yaml
- apiVersion: v1
  kind: ipPool
  metadata:
    cidr: 172.16.0.0/16
  spec:
    ipip:
      enabled: true
      mode: cross-subnet
    nat-outgoing: true
- apiVersion: v1
  kind: ipPool
  metadata:
    cidr: fd80:24e2:f998:72d6::/64
  spec: {}
```

No changes to the default Calico profile, which I think allows all Calico containers to talk to each other:

```yaml
- apiVersion: v1
  kind: profile
  metadata:
    name: calico
    tags:
    - calico
  spec:
    egress:
    - action: allow
      destination: {}
      source: {}
    ingress:
    - action: allow
      destination: {}
      source:
        tag: calico
```

DC/OS 1.11.2 EE in strict mode, with Calico installed as follow
Scripts to set Calico up are here: https://github.com/justinrlee/dcos-calico/tree/master/calico-secure/v03

Basically, just run the shell scripts 1a, 1b, 1c, 1d, 2, 3 on all DC/OS masters.

Then run 4 on one master (to set up Calico pools and stuff)

Then run 1a, 1b, 1c, 1d, 2, 5 on all DC/OS agents.

## Other
For now, I'm building a workaround where I set up a cron job (or systemd timer, not sure yet) that will get a list of all tunnel endpoints, and ping all of them, every X amount of time.  Something like this (although I'll probably gather them and store them in some temp file, rather than collecting them every time it's run):

```bash
#!/bin/bash
# tunl addresses are stored in etcd; get the keys (need client cert)
keys=$(sudo ETCDCTL_API=2 /opt/etcd/etcdctl \
  --endpoints https://localhost:2379 \
  --key-file /etc/etcd/certs/etcd.key \
  --cert-file /etc/etcd/certs/etcd.crt \
  --ca-file /etc/etcd/certs/dcos-ca.crt \
  ls /calico/v1/host --recursive | grep IpInIpTunnelAddr)

# get the actual tunl0 ip addresses, and ping them all
for key in ${keys};
do
  tun=$(sudo ETCDCTL_API=2 /opt/etcd/etcdctl \
  --endpoints https://localhost:2379 \
  --key-file /etc/etcd/certs/etcd.key \
  --cert-file /etc/etcd/certs/etcd.crt \
  --ca-file /etc/etcd/certs/dcos-ca.crt \
  get ${key})
  /usr/bin/ping -c1 -W1 ${tun} &> /dev/null
done
```
