### ISSUE TITLE
cannot check the BGP status from node

### ISSUE THREAD

**Issue by yunithon** [projectcalico/calico#2062]
Hi,all
I created three Masters and three Nodes with calico-openshift cluster.
I can see the bgp status from Master, but I fail to check the bgp status from Nodes.
Is there any way to know the BGP staus? I need to get some plugin for Node?
And also I think that pinging results below might be related...
Pinging
Master → web (behind Node) OK
Node → web (behind Master) NG

Thanks

## Your Environment

* CNI plugin version (e.g. `/opt/cni/bin/calico --version`):
Client Version:    v1.5.0
Build date:        2017-08-22T18:38:51+0000
Git commit:        118b8ae1
Cluster Version:   v2.5.0
Cluster Type:      origin,bgp

* Orchestrator version (e.g. kubernetes, mesos, rkt):
3.7 / k8s：v1.7.6

* CNI config:
 ```
cat /etc/calico/calicoctl.cfg
apiVersion: v1
kind: calicoApiConfig
metadata:
spec:
  datastoreType: "etcdv2"
  etcdEndpoints: "https://XXXXXX-osm02:2379,https://XXXXXX-osm03:2379,https://XXXXXX-osm01:2379"
  etcdKeyFile: "/etc/origin/calico/calico.etcd-client.key"
  etcdCertFile: "/etc/origin/calico/calico.etcd-client.crt"
  etcdCaCertFile: "/etc/origin/calico/calico.etcd-ca.crt"


* Operating System and version:RHEL7.4
```

*From Master
```
[root@XXXXXX-osm01 ~]# calicoctl node status
Calico process is running.

IPv4 BGP status
+--------------+-------------------+-------+----------+-------------+
| PEER ADDRESS |     PEER TYPE     | STATE |  SINCE   |    INFO     |
+--------------+-------------------+-------+----------+-------------+
| 192.168.1.2  | node-to-node mesh | up    | 13:00:38 | Established |
| 192.168.1.6  | node-to-node mesh | up    | 13:00:33 | Established |
| 192.168.1.3  | node-to-node mesh | up    | 13:00:33 | Established |
| 192.168.1.9  | node-to-node mesh | up    | 13:00:34 | Established |
+--------------+-------------------+-------+----------+-------------+

IPv6 BGP status
No IPv6 peers found.
```

```
[root@XXXXXX-osm01 ~]# ip r
default via 192.168.0.254 dev eth0 proto static metric 100
10.129.43.0/26 via 192.168.1.3 dev tunl0 proto bird onlink
10.129.117.192/26 via 192.168.1.6 dev tunl0 proto bird onlink
10.129.119.0/26 via 192.168.1.2 dev tunl0 proto bird onlink
blackhole 10.130.246.64/26 proto bird
10.130.246.70 dev caliaff4247e349 scope link
10.130.246.71 dev cali195a74113a6 scope link
10.131.183.128/26 via 192.168.1.9 dev tunl0 proto bird onlink
169.254.169.254 via 192.168.0.1 dev eth0 proto dhcp metric 100
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1
192.168.0.0/24 dev eth0 proto kernel scope link src 192.168.0.111 metric 100
192.168.1.0/24 dev eth1 proto kernel scope link src 192.168.1.8 metric 100
```

*From Node
```
[root@XXXXXX-osn01 ~]# ip r
default via 192.168.0.254 dev eth0 proto static metric 100
blackhole 10.129.43.0/26 proto bird
10.129.117.192/26 via 192.168.1.6 dev tunl0 proto bird onlink
10.129.119.0/26 via 192.168.1.2 dev tunl0 proto bird onlink
10.130.246.64/26 via 192.168.1.8 dev tunl0 proto bird onlink
10.131.183.128/26 via 192.168.1.9 dev tunl0 proto bird onlink
169.254.169.254 via 192.168.1.1 dev eth1 proto dhcp metric 100
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1
192.168.0.0/24 dev eth0 proto kernel scope link src 192.168.0.121 metric 100
192.168.1.0/24 dev eth1 proto kernel scope link src 192.168.1.3 metric 100
```
