### ISSUE TITLE
How to create endpoints to host in kubernetes

### ISSUE THREAD

**Issue by Paxa** [projectcalico/calico#2081]
I want to connect to connect to etcd running on a node without opening port for public
And would like to add network policies for that

is it possible?

I'm trying to create endpoints and service, but no luck `Host is unreachable`

```yaml
apiVersion: v1
kind: Endpoints
metadata:
  labels:
    app: exporter-kube-etcd
    component: kube-etcd
  name: kube-prometheus-exporter-kube-etcd
  namespace: kube-system
subsets:
- addresses:
  - ip: 123.123.123.123
    targetRef:
      kind: Node
      name: node1
  ports:
  - name: https-metrics
    port: 2379
    protocol: TCP
```

And service:

```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: exporter-kube-etcd
    component: kube-etcd
  name: kube-prometheus-exporter-kube-etcd
  namespace: kube-system
spec:
  clusterIP: None
  ports:
  - name: https-metrics
    port: 2379
    protocol: TCP
    targetPort: 2379
  selector:
    app: exporter-kube-etcd
```

Result:

```
$ kubectl get service kube-prometheus-exporter-kube-etcd
NAME                                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)    AGE
kube-prometheus-exporter-kube-etcd   ClusterIP   None         <none>        2379/TCP   3d

$ kubectl get endpoints kube-prometheus-exporter-kube-etcd
NAME                                 ENDPOINTS           AGE
kube-prometheus-exporter-kube-etcd   123.123.123.123:2379   3d
```

If try to connect:
```
$ kubectl exec -it some-pod sh

~ # telnet kube-prometheus-exporter-kube-etcd.kube-system 2379
telnet: can't connect to remote host (123.123.123.123): Host is unreachable

# but other ports work
~ # telnet kube-prometheus-exporter-kube-controller-manager.kube-system 10252
GET /
HTTP/1.1 400 Bad Request
Content-Type: text/plain; charset=utf-8
Connection: close

400 Bad RequestConnection closed by foreign host
```
