### ISSUE TITLE
NetworkPolicy Rules not working with Services

### ISSUE THREAD

**Issue by ecowden** [projectcalico/calico#2088]
NetworkPolicy Ingress rules are applied when connecting to Pods directly, but not when connecting through a Service. Services are of type ClusterIP.

For reference, the NetworkPolicy may look like,

```yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-example-app-ingress
spec:
  podSelector:
    matchLabels:
      app: example-app
  policyTypes:
  - Ingress
  ingress:
  - from:
    - ipBlock:
        # My workstation's CIDR
        cidr: ...
```

Conversely, If I create a NetworkPolicy rule that allows traffic from the host network, however, traffic is allowed through the Service regardless of the source (wrong), and clients cannot connect directly to pods (right).

Looks the same as issue #1683.

I've verified that `kube-proxy`'s `--cluster-cidr=...` argument is set to the Pod network, and that it excludes the Service network.

## Expected Behavior
NetworkPolicy Ingress rules should be enforced based on the original client when routing through Services, not the host where `kube-proxy` is running.

## Current Behavior
NetworkPolicy through services is enforced based on the location of the `kube-proxy` instance.

## Possible Solution
Unsure.

## Steps to Reproduce (for bugs)
1. Create a Pod or other workload in a Kubernetes cluster with Calico configured in a BGP configuration.
2. Create a Service directing traffic to the Pod.
3. Create NetworkPolicy Ingress rules to allow and deny traffic as desired.
4. NetworkPolicy rules are enforced correctly when communicating with Pods directly. When directing traffic through the Service, NetworkPolicy is enforced based on the Service's location, not the original client.

## Context
This prevents us from using Kubernetes NetworkPolicy to control access to workloads in the Kubernetes cluster.

## Your Environment
* Calico version: 2.6.8
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes v1.11.0
* Operating System and version: RHEL v7.4

Kubernetes is configured using Calico with BGP pairing to make the Pod network routable from outside the cluster.

Thanks in advance!

**Edit**: The original version of this issue was posted prematurely with an errant mouse click. Apologies for any confusion!
