### ISSUE TITLE
calicoctl convert does not successfully convert selector field

### ISSUE THREAD

**Issue by bhpratt** [projectcalico/calico#2131]
## Expected Behavior

```
c convert --filename allow-egress-pods.yaml --output yaml
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  creationTimestamp: null
  name: allow-egress-pods
spec:
  egress:
  - action: Allow
    destination:
      ports:
      - 53
      - 10250
    protocol: UDP
    source: {}
  - action: Allow
    destination:
      ports:
      - 53
      - 10250
    protocol: TCP
    source: {}
  - action: Allow
    destination:
      selector: has(calico/k8s_ns)
    source: {}
  - action: Allow
    destination:
      notNets:
      - 10.0.0.0/8
      - 172.16.0.0/12
      - 192.168.0.0/16
    source: {}
  order: 1500
  selector: has(projectcalico.org/namespace)
  types:
  - Egress
```

I expect selector at the end of the file to be `has(calico/k8s_ns)`. Instead, the convert operation changes it to `has(projectcalico.org/namespace)`.

## Steps to Reproduce (for bugs)

To reproduce, run convert, output YAML on this file:

```
- apiVersion: v1
  kind: policy
  metadata:
    name: allow-egress-pods
  spec:
    egress:
    - action: allow
      protocol: udp
      destination:
        ports:
        - 53
        - 10250
      source: {}
    - action: allow
      protocol: tcp
      destination:
        ports:
        - 53
        - 10250
      source: {}
    - action: allow
      destination:
        selector: has(calico/k8s_ns)
      source: {}
    - action: allow
      destination:
        notNets:
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16
      source: {}
    order: 1500
    selector: has(calico/k8s_ns)
    types:
    - egress
```

## Your Environment

* Calico version 1.6.3 to 3.1.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes
* Operating System and version: macOS 10.13.16
* cloud env: IBM Cloud

**Comment by caseydavenport** [comment]
@bhpratt I believe that is intended - as part of the upgrade to v3, that label (which Calico adds automatically) is translated to the new value.

e.g. `calico/k8s_ns: default` becomes `projectcalico.org/namespace: default`

I am surprised it hasn't converted the selector within the rule though.

**Comment by caseydavenport** [comment]
> did not target what was previously being targeted, causing the policy to fail.

Hm, in what way did it not target the correct things? Did it target more or less than it was intended to?

It's not intended for the user to have to do any manual switching of the labels. So, it sounds like there is indeed a bug in the conversion logic here.

**Comment by caseydavenport** [comment]
> Calico version 1.6.3 to 3.1.1

I noticed this in the original post. @bhpratt do you mean Calico v2.6.3?

In either case, I should note that upgrade to Calico v3.1 requires a base version of v2.6.5 - see here: https://docs.projectcalico.org/v3.1/getting-started/kubernetes/upgrade/

I'll do a bit more digging on this, in the mean time could you try from v2.6.5 and see if you have the same results?

**Comment by caseydavenport** [comment]
Also, could you see what the output of `calicoctl get weps -o yaml` shows for the labels on your workload endpoints? It would be useful to know if the labels on the weps have been converted.

I have a suspicion that the problem is because the rule selector has not been updated. If that's the case, then I think this is the fix: https://github.com/projectcalico/libcalico-go/pull/920/files

**Comment by bhpratt** [comment]
Apologies. Re: Version, I meant calicoctl version 1.6.3. Calico version is 2.6.5

When I run that command in the v3 cluster, I get:

```
calicoctl get weps -o yaml
apiVersion: projectcalico.org/v3
items: []
kind: WorkloadEndpointList
metadata:
  resourceVersion: "17399"
```

**Comment by caseydavenport** [comment]
Woops, you might need to specify a namespace - e.g. `--namespace kube-system` if there are no pods in the default ns.

**Comment by bhpratt** [comment]
```
apiVersion: projectcalico.org/v3
  kind: WorkloadEndpoint
  metadata:
    creationTimestamp: 2018-09-06T07:19:16Z
    generateName: vpn-5d775c97d8-
    labels:
      app: vpn
      kubernetes-dashboard-policy: allow
      pod-template-hash: "1833175384"
      projectcalico.org/namespace: kube-system
      projectcalico.org/orchestrator: k8s
      projectcalico.org/serviceaccount: default
```
