### ISSUE TITLE
Network policy auto-generated and preceding user-defined policies

### ISSUE THREAD

**Issue by ivanovaleksandar** [projectcalico/calico#2137]
## Expected Behavior
Auto generated network policy should not be created.

## Current Behavior
Currently I have a `NetworkPolicy` defined and implemented:
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-network-policy
  namespace: ingress-nginx
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - ipBlock:
        cidr: 1.2.3.4/32
``` 

After a while, a new `NetworkPolicy` is auto-generated and precedes the already user-defined policy and because of the wider `allow` rules, the following policies are not applied.
```
apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  name: np-ingress-nginx
  namespace: ingress-nginx
  ownerReferences:
  - apiVersion: v1
    kind: Service
    name: ingress-nginx
spec:
  ingress:
  - ports:
    - port: 80
      protocol: TCP
    - port: 443
      protocol: TCP
  podSelector:
    matchLabels:
      app: ingress-nginx
  policyTypes:
  - Ingress
```

I can see that a `ownerReferences` points to the service, but I am not sure if Calico is somehow instructing k8s to generate these policies. Before using Calico, this behaviour was not present.

## Your Environment
* Calico version: v3.1.3
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes
* Operating System and version: Ubuntu 18.04
