### ISSUE TITLE
container with hostPort can not access the local host's portIP:hostPort from the container

### ISSUE THREAD

**Issue by hchenxa** [projectcalico/calico#2153]
container with hostPort can not access the local host's portIP:hostPort from the containe
## Current Behavior

I have 2 host with calico as the container network, assume the host name like `hostA` and `hostB`.

`hostA` create a container with hostPort named tomcatA with IP `10.1.104.11`, then I login container and can access my tomcat service with containerIP:port, but can not access with hostIP:hostPort.

Then I create same container service with hostPort on `hostB`, and I can access the hostB's service from container on `hostA` with both `hostB`'s `hostIP:hostPort` and `hostB`'s `containerIP:containerPort`.

so the main problem was, why I can not access the container service with the hostIP on same host plus hostPort?

Here is the sample yaml file which I used to create my test app:
```
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: tomcat
spec:
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      hostNetwork: false
      containers:
      - name: tomcat
        image: hchenxa1986/tomcat:cni
        imagePullPolicy: IfNotPresent
        ports:
        - protocol: TCP
          hostPort: 8088
          containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* calicoctl version (e.g. `calicoctl version`):

```
root@hchenxa-2:~# calicoctl version
Client Version:    v2.0.0
Build date:        2017-12-21T21:02:56+0000
Git commit:        8006d580
Cluster Version:   v3.0.4
Cluster Type:      k8s,bgp
```

* calico/node version (e.g. `docker run --rm calico/node versions`)
* Orchestrator type and version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):
