### ISSUE TITLE
How can I allow dns for my namespace?

### ISSUE THREAD

**Issue by azalio** [projectcalico/calico#2199]
Hello!

I'm trying to allow access from all pods in namespace `policy-demo` to `kube-dns`, but can't.
What do I do wrong?

```
---
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: allow-dns
  namespace: policy-demo
spec:
  types:
  - Egress
  egress:
  - action: Allow
    protocol: TCP
    destination:
      selector: k8s-app == 'kube-dns'
      namespaceSelector: ns == 'kube-system'
      ports:
      - 53
```
