### ISSUE TITLE
Improve router ID docs / implementation for IPv6

### ISSUE THREAD

**Issue by hhoover** [projectcalico/calico#2229]
The current documentation for Calico with Kubernetes and IPv6 says that CALICO_ROUTER_ID must be set but does not provide guidance on what it should be or how to set it.

## Expected Behavior
The documentation should tell you to set CALICO_ROUTER_ID to a unique IPv4 address for each node, and how to customize the provided Calico DaemonSet to accomplish that.

## Current Behavior
No guidance is given.

## Possible Solution
Add an initcontainer to the daemonset to set a router-id through a pod annotation?

## Context
Trying to deploy Calico in a IPv6-only Kubernetes cluster

## Your Environment
* Calico version: 3.2
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes
* Operating System and version: Ubuntu 16.04

**Comment by caseydavenport** [comment]
Yeah, the story here is pretty weak. It should be possible, but our docs don't help very much.

We should at least do the bare minimum to document the requirements for the field, but ideally we'd provide a simpler way to automatically configure this.

**Comment by uablrek** [comment]
Pod annotation must be done per instance. I think an annotation on the k8s node object is better. Please see my comment on the same thing for the metallb speaker; https://github.com/google/metallb/issues/7#issuecomment-422008824

**Comment by hhoover** [comment]
node annotations aren't presented to the [downward API](https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/#capabilities-of-the-downward-api) (only pod labels and annotations), so it would have to be queried in the container itself somehow. To "solve this" in the meantime I've added an initContainer with kubectl that runs a script from a configmap to generate a random IPv4 address and annotates it's own pod with it. `CALICO_ROUTER_ID` then is set with this annotation on its own pod using the downward API.

It feels kinda dirty, but it works, which from experience is usually good enough in computering `/s`. I'd like a better way though

**Comment by uablrek** [comment]
But a pod needing a router-id is not an ordinary application pod, it should read the k8s api for other things anyway, like the node CIRD range for instance. And IMHO the router-id should be a property of the nore rather than a pod that may be moved. And also the router should be deployed as a DaemonSet right? Is there really a way to use the "downward API" in a way that pods on different nodes get different settings? I have searched but not found any way. A mix Daemon/Stateful-Set would be perfect but I can't find that either.

**Comment by hhoover** [comment]
the router pod is deployed as a daemonset, yes.

the initContainer I added creates a router-id and annotates it's own pod, so the calico-router container can pick it up. This is different per node, even though the daemonset is running a router pod on every node. The pods don't "move" to other nodes because the daemonset only runs one pod per node.

I've snipped a lot of the calico yaml out for brevity

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: calico-router-config
  namespace: kube-system
data:
  script.sh: |-
    #!/bin/bash
    if [ -z $HOSTIP|| -z $PODNAME ]
      exit 1
    else
      IP=$(echo ${HOSTIP} | awk -F: '{print $NF}')
      if [ -z $IP ]
      then
        exit 1
      else
        kubectl annotate pod $PODNAME routerid=10.0.0.${IP}
      fi
    fi
---
<SNIP>
initContainers:
        # CALICO_ROUTER_ID must be set for each node
        # This initcontainer generates a router ID from the host IP
        # and sets an annotation on the pod
        - name: create-routerid
          image: [redacted]
          env:
            - name: HOSTIP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: PODNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command: ["/bin/bash","-c"]
          args: ["/generatedip/script.sh"]
          volumeMounts:
          - name: generatedip
            mountPath: /generatedip
<SNIP>
 - name: CALICO_ROUTER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['routerid']
<SNIP>
volumes:
- name: generatedip
          configMap:
            name: calico-router-config
            defaultMode: 0744
```

Unless the functionality is added to the calico-router pod to read a node annotation for a router-id (which would be awesome and I think is my desired outcome), this is kind of the next best thing until there's a better way.

**Comment by caseydavenport** [comment]
It seems reasonable to me that we add support for a well-known node annotation here.

Or, why not just have the node pod calculate an address in a way similar to your script - grab the host's IP or some other bit of per-node metadata, use it to make a unique IPv4 address, cache that to `/var/lib/calico/router_id` or something so that it stays the same across node IP changes?

**Comment by uablrek** [comment]
Here is a proposal which I will suggest in metallb;
```
func hashRouterId(hostname string) net.IP {
        buf := new(bytes.Buffer)
        binary.Write(buf, binary.LittleEndian, crc32.ChecksumIEEE([]byte(hostname)))
        return net.IP(buf.Bytes())
}
```
Be aware that the probability for collitions is larger than n/2^32. As an example the probabliliy that 2 kids have birthday on the same day in a class with 23 children is ~50%, not 23/365~=6%. If my calculations are correct p=0.002906 for n=5000, i.e. pretty small. But **if** it happens it is irreversible until hosts are renamed.

**Comment by uablrek** [comment]
Since the router-is's are dependent on hostname only amd totally deterministic it is easy to write an offline program that with 100% accuracy can tell if there will be a collision given the hostnames as input.

**Comment by uablrek** [comment]
Did a test for hostsnames `vm-000000` - `vm-999999` and got no collisions (I must admit I enjoy analyzing this :-) )

**Comment by rachappag** [comment]
As a stop gap, I am planing to use this method.

```
export CALICO_ROUTER_ID=`hostname | cksum | cut -d " " -f 1 | xargs printf "%08x" | sed 's/.\{2\}/ 0x&/g' | xargs printf "%d.%d.%d.%d"` ; start_runit
```
With this, unique and constant `CALICO_ROUTER_ID` brought to each node.

```
/ # hostname | cksum | cut -d " " -f 1 | xargs printf "%08x" | sed 's/.\{2\}/ 0x&/g' | xargs printf "%d.%d.%d.%d"
84.92.226.61
/ #
/ # grep "CALICO_ROUTER_ID" /etc/envvars
CALICO_ROUTER_ID=84.92.226.61
```

**Comment by rachappag** [comment]
@caseydavenport 
Can you please suggest, Is it good to add the `CALICO_ROUTER_ID` generation logic in `start_runit` for IPv6 case.

Script to test the method:

```
value=""
gen_ip()
{
  name=`echo -n "$1" | cksum | cut -d " " -f 1 | xargs printf "%08x" | sed 's/.\{2\}/ 0x&/g' | xargs printf "%d.%d.%d.%d"`
  value=$name
}

> /tmp/ip_list.txt
for  i in {1..100000}
do
  rand_chars=`uuidgen | cut -d "-" -f 1`
  ahostname="myhost-$i-$rand_chars"
  gen_ip $ahostname
  grep -w -F $value  /tmp/ip_list.txt 2>&1 /dev/null
  if [ $? -eq 0 ]
  then
     echo "found collision $value for $ahostname"
     exit
  fi
  echo $value >> /tmp/ip_list.txt
done
```

Check for invalid IP address generation:
```
grep "\.[2-9][5-9][6-9]\." /tmp/ip_list.txt
```

**Comment by caseydavenport** [comment]
I believe we've just added some new functionality to support autogeneration of the router ID for IPv6 only systems. 

See here: https://github.com/projectcalico/calico/pull/2474 and https://github.com/projectcalico/confd/pull/215

This has gone into the master branch, so it's not in a release yet but you can probably try it out using images built from master!

**Comment by rachappag** [comment]
@caseydavenport  Thanks, calico 3.6.0  is released.

**Comment by mpfisterUniBE** [comment]
> @caseydavenport Thanks, calico 3.6.0 is released.

Does the 3.6.0 release actually work for you?
In my setup it causes a bird error as within the router id I now have the string "hash" instead of an actual IP.

Using the method @hhoover described here https://github.com/projectcalico/calico/issues/2229#issuecomment-435430481 the following config is being written:
```
[root@k8s-sidl5-m1 ~]# kubectl exec -n kube-system calico-node-mq4m7 -- cat /etc/calico/confd/config/bird6.cfg
[SNIP]
router id 172.18.78.11;  # Use IPv4 address since router id is 4 octets, even in MP-BGP
```
So, using my own init container for creating a router id works but the cluster still fails because of this:
https://github.com/projectcalico/calico/issues/2458

However, switching to the release 3.6.0 where the router id should accept the string "hash" causes this **bird6.conf**
```
[root@k8s-sidl5-m1 ~]# kubectl exec -n kube-system calico-node-xc59q -- cat /etc/calico/confd/config/bird6.cfg
[SNIP]
router id hash;  # Use IPv4 address since router id is 4 octets, even in MP-BGP
```

**calico.yaml**
```
      containers:
        # Runs calico/node container on each Kubernetes node.  This
        # container programs network policy and routes on each
        # host.
        - name: calico-node
          image: calico/node:v3.6.0
          env:
            # Use Kubernetes API as the backing datastore.
            - name: DATASTORE_TYPE
              value: "kubernetes"
            # Wait for the datastore.
            - name: WAIT_FOR_DATASTORE
              value: "true"
            # Set based on the k8s node name.
            - name: NODENAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            # Choose the backend to use.
            - name: CALICO_NETWORKING_BACKEND
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: calico_backend
            # Cluster type to identify the deployment type
            - name: CLUSTER_TYPE
              value: "k8s,bgp"
            # Auto-detect the BGP IP address.
            - name: IP
              value: "none"
            # Enable IPIP
            - name: CALICO_IPV4POOL_IPIP
              value: "Always"
            # Set MTU for tunnel device used if ipip is enabled
            - name: FELIX_IPINIPMTU
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: veth_mtu
            # The default IPv4 pool to create on startup if none exists. Pod IPs will be
            # chosen from this range. Changing this value after installation will have
            # no effect. This should fall within `--cluster-cidr`.
            - name: CALICO_IPV4POOL_CIDR
              value: "192.168.0.0/16"
            - name: CALICO_IPV6POOL_CIDR
              value: "2001:620:400:282::/112"
            - name: IP6
              value: "autodetect"
            - name: CALICO_ROUTER_ID
              value: "hash"
            # Disable file logging so `kubectl logs` works.
            - name: CALICO_DISABLE_FILE_LOGGING
              value: "true"
            # Set Felix endpoint to host default action to ACCEPT.
            - name: FELIX_DEFAULTENDPOINTTOHOSTACTION
              value: "ACCEPT"
            # Disable IPv6 on Kubernetes.
            - name: FELIX_IPV6SUPPORT
              value: "true"
```

**Container Logs:**
```
bird: bird: /etc/calico/confd/config/bird.cfg, line 5: Number or IPv4 address constant expected/etc/calico/confd/config/bird6.cfg, line 5: Number or IPv4 address constant expected

bird: /etc/calico/confd/config/bird6.cfg, line 5: Number or IPv4 address constant expected
bird: /etc/calico/confd/config/bird.cfg, line 5: Number or IPv4 address constant expected
bird: /etc/calico/confd/config/bird.cfg, line 5: Number or IPv4 address constant expected
bird: /etc/calico/confd/config/bird6.cfg, line 5: Number or IPv4 address constant expected
bird: /etc/calico/confd/config/bird.cfg, line 5: Number or IPv4 address constant expected
bird: /etc/calico/confd/config/bird6.cfg, line 5: Number or IPv4 address constant expected
bird: /etc/calico/confd/config/bird6.cfg, line 5: Number or IPv4 address constant expected
bird: /etc/calico/confd/config/bird.cfg, line 5: Number or IPv4 address constant expected
bird: /etc/calico/confd/config/bird6.cfg, line 5: Number or IPv4 address constant expected
bird: /etc/calico/confd/config/bird.cfg, line 5: Number or IPv4 address constant expected
```

**Calico Version:**
```
[root@k8s-sidl5-m1 ~]# kubectl get pods -n kube-system -o=custom-columns=NAME:.metadata.name,IMAGE:.spec.containers[*].image | egrep 'NAME|calico'
NAME                                                   IMAGE
calico-kube-controllers-644fcf8fbf-msjp5               calico/kube-controllers:v3.6.0
calico-node-lptnc                                      calico/node:v3.6.0
calico-node-rlz28                                      calico/node:v3.6.0
calico-node-rwkr7                                      calico/node:v3.6.0
calico-node-xc59q                                      calico/node:v3.6.0
```

**Pods Status:**
```
[root@k8s-sidl5-m1 ~]# kubectl get pods -n kube-system |grep calico
calico-kube-controllers-644fcf8fbf-msjp5               0/1     CrashLoopBackOff   6          7m25s
calico-node-lptnc                                      0/1     Running            0          7m25s
calico-node-rlz28                                      0/1     Running            0          7m25s
calico-node-rwkr7                                      0/1     Running            0          7m25s
calico-node-xc59q                                      0/1     Running            0          7m25s
```
