### ISSUE TITLE
How to do network isolation for different ipPools

### ISSUE THREAD

**Issue by halfcrazy** [projectcalico/calico#2258]
## Expected Behavior

I want to limit network access between different ipPools, pod cannot communicate across the ipPool. After reading the docs, I think I should use calico globalnetworkset to define the pools and add the label, then use globalnetworkpolicy to do the limit. But I cannot get it to work.
## Steps to Reproduce (for bugs)

1. Suppose I have two ipPools 10.1.0.0/16 and 10.2.0.0/26. Two nodes 192.168.8.28, 192.168.8.29 in the same subnet.
```yaml
apiVersion: projectcalico.org/v3
items:
- apiVersion: projectcalico.org/v3
  kind: IPPool
  metadata:
    creationTimestamp: 2018-08-13T13:54:12Z
    name: default-ipv4-ippool
    resourceVersion: "10356499"
    uid: 5beb88e0-9f00-11e8-90dd-000c29591785
  spec:
    cidr: 10.1.0.0/16
    ipipMode: CrossSubnet
- apiVersion: projectcalico.org/v3
  kind: IPPool
  metadata:
    creationTimestamp: 2018-10-21T07:43:33Z
    name: test-pool1
    resourceVersion: "10362539"
    uid: 0331b538-d505-11e8-a7cd-000c29b9f965
  spec:
    cidr: 10.2.0.0/26
    ipipMode: CrossSubnet
kind: IPPoolList
metadata:
  resourceVersion: "10371164"
```
2. Define the globalnetworkset for 10.1.0.0/16
```yaml
apiVersion: projectcalico.org/v3
items:
- apiVersion: projectcalico.org/v3
  kind: GlobalNetworkSet
  metadata:
    labels:
      pool: ippool-1
    name: ippool-1
  spec:
    nets:
    - 10.1.0.0/16
kind: GlobalNetworkSetList
```
3. Apply the globalnetworkpolicy to it.
```yaml
apiVersion: projectcalico.org/v3
items:
- apiVersion: projectcalico.org/v3
  kind: GlobalNetworkPolicy
  metadata:
    name: allow-ippool-1-internal
  spec:
    ingress:
    - action: Deny
      destination:
        selector: pool == 'ippool-1'
      source:
        selector: pool != 'ippool-1'
    types:
    - Ingress
    selector: pool == 'ippool-1'
kind: GlobalNetworkPolicyList
```

## Context

I want pods in 10.2.0.0/26 cannot access pods in 10.1.0.0/16. 
```shell
[root@192-168-8-28 policy]# kubectl get pods --all-namespaces -o wide
NAMESPACE     NAME                                      READY     STATUS    RESTARTS   AGE       IP             NODE
default       qaq8-5b767977d-77twb                      1/1       Running   0          1h        10.1.0.7       192-168-8-28
default       qaq8-5b767977d-jrwhq                      1/1       Running   0          1h        10.1.0.8       192-168-8-29
default       qaq8-5b767977d-vnsm7                      1/1       Running   0          1h        10.1.0.6       192-168-8-28
default       qaq9-79b8bd86d7-czgd7                     1/1       Running   0          1h        10.2.0.17      192-168-8-28
default       qaq9-79b8bd86d7-r57rc                     1/1       Running   0          1h        10.2.0.18      192-168-8-29

[root@192-168-8-28 policy]# kubectl exec -it qaq9-79b8bd86d7-wgrnw ping 10.1.0.7
PING 10.1.0.7 (10.1.0.7): 56 data bytes
64 bytes from 10.1.0.7: seq=0 ttl=62 time=0.833 ms
64 bytes from 10.1.0.7: seq=1 ttl=62 time=0.905 ms
64 bytes from 10.1.0.7: seq=2 ttl=62 time=0.566 ms
^C
--- 10.1.0.7 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.566/0.768/0.905 ms
```

## Your Environment

* Calico version 3.1.3
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes 1.9.6
* Operating System and version: centos 7.4
* Link to your project (optional):
