### ISSUE TITLE
On k8s worker nodes, failed to "StartContainer" for "install-cni" with CrashLoopBackOff.

### ISSUE THREAD

**Issue by pushu115** [projectcalico/calico#2266]
I created a kubernetes 1.12.2 cluster master with kubeadm ,then applied calico 3.3 following instructions from https://docs.projectcalico.org/v3.3/getting-started/kubernetes/installation/calico#installing-with-the-kubernetes-api-datastore50-nodes-or-less:
```
kubectl apply -f https://docs.projectcalico.org/v3.3/getting-started/kubernetes/installation/hosted/rbac-kdd.yaml
kubectl apply -f https://docs.projectcalico.org/v3.3/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/1.7/calico.yaml
```

The master node was working fine with calico applied. But after I added a worker node using 'kubeadm join', the worker node wouldn't come up to Ready state complaining about 'No networks found in /etc/cni/net.d '. So I copied 2 files from master node to worker nodes, which are 10-calico.conflist  and calico-kubeconfig, and the complaint disappeared. So here is my first question, is there a better way to let the pods populate these files on worker nodes instead of copying them manually?

Anyway the worker nodes are in Ready state , but the calico-node pods end up in status CrashLoopBackOff now, as you can see below:

```
[root@okd-master-1 kubernetes]# kubectl get pods --all-namespaces -o wide
NAMESPACE     NAME                                           READY   STATUS             RESTARTS   AGE   IP             NODE                   NOMINATED NODE
kube-system   calico-node-l5m9b                              1/2     CrashLoopBackOff   25         55m   10.0.1.215     okd-node-2.ypl.loc     <none>
kube-system   calico-node-p9llb                              2/2     Running            12         17h   10.0.1.211     okd-master-1.ypl.loc   <none>
kube-system   calico-node-vq8vh                              1/2     CrashLoopBackOff   255        17h   10.0.1.214     okd-node-1.ypl.loc     <none>
kube-system   coredns-6c66ffc55b-7f86z                       1/1     Running            5          17h   192.168.0.32   okd-master-1.ypl.loc   <none>
kube-system   coredns-6c66ffc55b-wwz6w                       1/1     Running            5          17h   192.168.0.33   okd-master-1.ypl.loc   <none>
kube-system   etcd-okd-master-1.ypl.loc                      1/1     Running            6          17h   10.0.1.211     okd-master-1.ypl.loc   <none>
kube-system   kube-apiserver-okd-master-1.ypl.loc            1/1     Running            7          17h   10.0.1.211     okd-master-1.ypl.loc   <none>
kube-system   kube-controller-manager-okd-master-1.ypl.loc   1/1     Running            8          17h   10.0.1.211     okd-master-1.ypl.loc   <none>
kube-system   kube-proxy-2hgtk                               1/1     Running            0          55m   10.0.1.215     okd-node-2.ypl.loc     <none>
kube-system   kube-proxy-b94cw                               1/1     Running            8          17h   10.0.1.214     okd-node-1.ypl.loc     <none>
kube-system   kube-proxy-gvns2                               1/1     Running            8          17h   10.0.1.211     okd-master-1.ypl.loc   <none>
kube-system   kube-scheduler-okd-master-1.ypl.loc            1/1     Running            5          17h   10.0.1.211     okd-master-1.ypl.loc   <none>

```

So I checked the container logs and got this:

```
[root@okd-master-1 kubernetes]# kubectl logs -p  calico-node-l5m9b -c install-cni --namespace kube-system
ls: /calico-secrets: No such file or directory
cp: can't create '/host/opt/cni/bin/calico': Permission denied
Failed to copy /opt/cni/bin/calico to /host/opt/cni/bin. This may be caused by selinux configuration on the host, or something else.
```

Though actually I already disabled selinux on the host and I don't know why install-cni container wouldn't work. I even changed the mod of /opt/cni/bin to 777, but without any luck.

So what can I do to resolve this? Thanks.

Below is the kubeadm config file I use:
```
apiVersion: kubeadm.k8s.io/v1alpha2
kind: MasterConfiguration
kubernetesVersion: v1.12.2
imageRepository: registry.cn-hangzhou.aliyuncs.com/google_containers

apiServerCertSANs:
- "okd-master-1.ypl.loc"
- "okd-master-2.ypl.loc"
- "okd-master-3.ypl.loc"
- "10.0.1.211"
- "10.0.1.212"
- "10.0.1.213"
- "10.0.1.210"
- "127.0.0.1"

api:
  advertiseAddress: 10.0.1.211
  controlPlaneEndpoint: 10.0.1.210:8443

etcd:
  local:
    extraArgs:
      listen-client-urls: "https://127.0.0.1:2379,https://10.0.1.211:2379"
      advertise-client-urls: "https://10.0.1.211:2379"
      listen-peer-urls: "https://10.0.1.211:2380"
      initial-advertise-peer-urls: "https://10.0.1.211:2380"
      initial-cluster: "okd-master-1.ypl.loc=https://10.0.1.211:2380"
    serverCertSANs:
      - okd-master-1.ypl.loc
      - 10.0.1.211
    peerCertSANs:
      - okd-master-1.ypl.loc
      - 10.0.1.211

controllerManagerExtraArgs:
  node-monitor-grace-period: 10s
  pod-eviction-timeout: 10s

networking:
  podSubnet: "192.168.0.0/16"

kubeProxy:
  config:
    mode: ipvs

```

## Expected Behavior

I expect the calico-node pods to be in Running state.

## Current Behavior

Currently they're in CrashLoopBackOff state.

## Your Environment

* Calico version
3.3
* Orchestrator version (e.g. kubernetes, mesos, rkt):
kubernetes 1.12.2
* Operating System and version:
CentOS Linux release 7.5.1804 (Core)
* Link to your project (optional):
