### ISSUE TITLE
Blocking traffic via kube-ipvs0 using GlobalNetworkPolicies

### ISSUE THREAD

**Issue by KashifSaadat** [projectcalico/calico#2279]
I'm currently looking at switching out custom iptables rules we've applied to hard-block certain traffic from `cali+` interfaces to sensitive host ports, moving to use the `GlobalNetworkPolicies` in Calico v3 (with Kubernetes backend). Ran into a few issues with this and was wondering if anyone is able to advise. Scenario below:

**Setup:**
- Kubernetes v1.12 w/ Canal (Calico v3.3, Flannel v0.9.0)
- Taking sshd as a (bad) example, with it listening on all nodes, all interfaces and port 22
- kube-proxy in IPVS mode
- Built with kops latest

Previous configuration for iptables (example blocking ssh to nodes in cluster):
```
*filter
:INPUT ACCEPT [0:0]
-I INPUT 1 -i cali+ -p tcp -m tcp --dport 22 -m state --state NEW -j REJECT -m comment --comment "SSH"
:FORWARD ACCEPT [0:0]
-I FORWARD 1 -i cali+ -p tcp -m tcp -d {{ .SERVICE_CIDR }} --dport 22 -m state --state NEW -j REJECT -m comment --comment "SSH"
COMMIT
```

Previous custom configuration for Calico:
```yml
  chainInsertMode: append
  defaultEndpointToHostAction: RETURN
```

Previous behaviour (inside a pod running on node 10.200.0.10):
```bash
telnet 10.200.0.10 22 # blocked
telnet 10.200.0.20 22 # different node, blocked
telnet 172.17.0.1 22 # docker0 interface, blocked
telnet 10.10.0.10 22 # one of the kube-ipvs0 listening addresses on 10.200.0.10 node, blocked
```

New configuration is a Calico GlobalNetworkPolicy being deployed (no custom iptables rules or calico config):
```yml
  apiVersion: crd.projectcalico.org/v1
  kind: GlobalNetworkPolicy
  metadata:
    name: deny-rules
  spec:
    order: 1001
    applyOnForward: true
    egress:
    - action: Deny
      destination:
        nets:
        - "10.200.0.0/21" # Cluster CIDR
        - "10.10.0.0/16" # Flannel Network
        - "172.17.0.0/16" # docker0
        ports:
        - 22
      protocol: TCP
```

New behaviour (inside a pod running on node 10.200.0.10):
```bash
telnet 10.200.0.10 22 # blocked
telnet 10.200.0.20 22 # different node, blocked
telnet 172.17.0.1 22 # docker0 interface, blocked
telnet 10.10.0.10 22 # one of the kube-ipvs0 listening addresses on 10.200.0.10 node, this request isn't blocked and I can successfully ssh via this address to the 10.200.0.10 node
```

Are there any clear mistakes I may have made in my global network policy definition or will I just have to keep the INPUT chain rules in place for now, as it seems the GNP rules are occurring too late in the chains. Any help is appreciated, thanks!
