### ISSUE TITLE
(3.3.x) Calico node as Route Reflector integrating with external router

### ISSUE THREAD

**Issue by mrrandrade** [projectcalico/calico#2292]
We have a working 3.2.x setup with cailco-node integrating with 2 route reflectors which are themselves integrated with an edge router using the configuration available here #1745 (which changes the rreflector container with a custom template).

Since 3.3 calico node replaces the route reflector container, I tried to upgrade following the available docs but wasn't able to succeed. 

## Expected Behavior

RR peering with Edge router.

## Current Behavior

```
Nov 12 20:28:27 calico-router docker[99658]: bird: /etc/calico/confd/config/bird.cfg, line 96: Only internal neighbor can be RR client
```

## Possible Solution

Hardcoding it on the template again.

## Steps to Reproduce (for bugs)

Calico node that will be used as route reflector:
```
apiVersion: projectcalico.org/v3
kind: Node
metadata:
  creationTimestamp: 2018-11-11T07:46:41Z
  labels:
    route-reflector: "true"
  name: node-reflector
  resourceVersion: "1292481"
  uid: edd5f222-e585-11e8-ae71-0050569a43d2
spec:
  bgp:
    ipv4Address: 192.168.0.10/32
    routeReflectorClusterID: 224.0.0.1
```

Configuration extracted from: https://docs.projectcalico.org/v3.3/usage/configuration/bgp

* Peers to rs
```
kind: BGPPeer
apiVersion: projectcalico.org/v3
metadata:
  name: peer-to-rrs
spec:
  nodeSelector: !has(route-reflector)
  peerSelector: has(route-reflector)
```
* RR Mesh:

```
kind: BGPPeer
apiVersion: projectcalico.org/v3
metadata:
  name: rr-mesh
spec:
  nodeSelector: has(route-reflector)
  peerSelector: has(route-reflector)
```
My BGPConfig: 

```
apiVersion: projectcalico.org/v3
kind: BGPConfiguration
metadata:
  creationTimestamp: 2018-07-18T23:50:08Z
  name: default
  resourceVersion: "13672"
  uid: 4d44e65f-8ae5-11e8-ba58-0050568fae1d
spec:
  asNumber: 64513
  logSeverityScreen: Info
  nodeToNodeMeshEnabled: false
```
The edge router is already configured to integrate with my environment. Since there's no new configuration, it's blocked:

```
Nov 12 18:01:15 node-reflector docker[123244]: bird: BGP: Unexpected connect from unknown address 192.168.0.1 (port 63651)
```

So I create a BGPPeer for it. My edge router has a different AS Number than my cluster:

```
apiVersion: projectcalico.org/v3
kind: BGPPeer
metadata:
  name: external-router-hom 
spec:
  peerIP: 10.79.63.1 
  asNumber: 65533 
  nodeSelector: has(route-reflector)
```

Now I get this validation error and everything stops working (since the file is not renewed anymore):

```
Nov 12 20:28:27 calico-router docker[99658]: bird: /etc/calico/confd/config/bird.cfg, line 96: Only internal neighbor can be RR client
```

## Your Environment

* Calico 3.3.0
* Kubernetes 1.12, but I think it's not relevant to the situation.
* Operating System and version: CoreOS 1855.5
