### ISSUE TITLE
System Pods not on Calico Network

### ISSUE THREAD

**Issue by Joerg-L** [projectcalico/calico#2299]
We are trying to setup a Kubernetes Cluster with Calico on-premise.

As we want to automize the whole setup we have create some Ansible playbooks for that.
The Cluster should have 3 Master and 5 Worker/Minions.

After the first master is configured, we run 

```
$ KUBECONFIG=secrets/admin.conf kubectl apply -f https://docs.projectcalico.org/v3.2/getting-started/kubernetes/installation/hosted/etcd.yaml
$ KUBECONFIG=secrets/admin.conf kubectl apply -f https://docs.projectcalico.org/v3.2/getting-started/kubernetes/installation/rbac.yaml
$ KUBECONFIG=secrets/admin.conf kubectl apply -f https://docs.projectcalico.org/v3.2/getting-started/kubernetes/installation/hosted/calico.yaml
```
after that, master 2 and 3 is getting setup.
For setting up first master we use following config
```
ApiVersion: kubeadm.k8s.io/v1alpha3
kind: ClusterConfiguration
kubernetesVersion: stable
imageRepository: google-containers
apiServerCertSANs:
- "vmamradd04.gfklctx.local"
controlPlaneEndpoint: "vmamradd04.gfklctx.local:6443"
etcd:
  local:
    extraArgs:
      listen-client-urls: "https://127.0.0.1:2379,https://172.28.16.81:2379"
      advertise-client-urls: "https://172.28.16.81:2379"
      listen-peer-urls: "https://172.28.16.81:2380"
      initial-advertise-peer-urls: "https://172.28.16.81:2380"
      initial-cluster: "vmkubei01.gfklctx.local=https://172.28.16.81:2380"
    serverCertSANs:
      - "vmkubei01.gfklctx.local"
      - "172.28.16.81"
    peerCertSANs:
      - "vmkubei01.gfklctx.local"
      - "172.28.16.81"
networking:
    # This CIDR is a Calico default. Substitute or remove for your CNI provider.
    podSubnet: "192.168.0.0/16"
---
apiVersion: kubeadm.k8s.io/v1alpha3
kind: InitConfiguration
nodeRegistration:
  kubeletExtraArgs:
    pod-infra-container-image: "google-containers/pause:3.1"
```
After the playbook is finished, all Master and Worker seams to be up correctly.
```
[root@vmkubei01 ~]# kubectl get nodes -o wide
NAME                      STATUS     ROLES    AGE     VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION               CONTAINER-RUNTIME
vmkubei01.gfklctx.local   Ready      master   4m25s   v1.12.2   172.28.16.81   <none>        CentOS Linux 7 (Core)   3.10.0-862.14.4.el7.x86_64   docker://18.6.1
vmkubei02.gfklctx.local   Ready      master   2m50s   v1.12.2   172.28.16.82   <none>        CentOS Linux 7 (Core)   3.10.0-862.14.4.el7.x86_64   docker://18.6.1
vmkubei03.gfklctx.local   Ready      master   74s     v1.12.2   172.28.16.83   <none>        CentOS Linux 7 (Core)   3.10.0-862.14.4.el7.x86_64   docker://18.6.1
vmkubep01.gfklctx.local   NotReady   <none>   12s     v1.12.2   172.28.16.87   <none>        CentOS Linux 7 (Core)   3.10.0-862.14.4.el7.x86_64   docker://18.6.1
vmkubep02.gfklctx.local   NotReady   <none>   13s     v1.12.2   172.28.16.88   <none>        CentOS Linux 7 (Core)   3.10.0-862.14.4.el7.x86_64   docker://18.6.1
vmkubep03.gfklctx.local   NotReady   <none>   13s     v1.12.2   172.28.16.89   <none>        CentOS Linux 7 (Core)   3.10.0-862.14.4.el7.x86_64   docker://18.6.1
vmkubep04.gfklctx.local   NotReady   <none>   12s     v1.12.2   172.28.16.90   <none>        CentOS Linux 7 (Core)   3.10.0-862.14.4.el7.x86_64   docker://18.6.1
vmkubep05.gfklctx.local   NotReady   <none>   12s     v1.12.2   172.28.16.91   <none>        CentOS Linux 7 (Core)   3.10.0-862.14.4.el7.x86_64   docker://18.6.1
```
On the pods, we see that the system pods are running on host ip's and not on calico network
```
[root@vmkubei01 ~]# kubectl get pods -o wide -n kube-system
NAME                                              READY   STATUS    RESTARTS   AGE     IP               NODE                      NOMINATED NODE
calico-etcd-6hvqk                                 1/1     Running   0          2m24s   172.28.16.83     vmkubei03.gfklctx.local   <none>
calico-etcd-d8ldn                                 1/1     Running   0          6m      172.28.16.81     vmkubei01.gfklctx.local   <none>
calico-etcd-jgwdz                                 1/1     Running   0          3m53s   172.28.16.82     vmkubei02.gfklctx.local   <none>
calico-kube-controllers-757fbf57c9-l4mqq          1/1     Running   0          6m12s   172.28.16.81     vmkubei01.gfklctx.local   <none>
calico-node-5rwf4                                 2/2     Running   2          4m54s   172.28.16.82     vmkubei02.gfklctx.local   <none>
calico-node-62mkm                                 1/2     Running   3          2m18s   172.28.16.88     vmkubep02.gfklctx.local   <none>
calico-node-6mhft                                 2/2     Running   3          2m17s   172.28.16.91     vmkubep05.gfklctx.local   <none>
calico-node-bzjn2                                 2/2     Running   1          6m12s   172.28.16.81     vmkubei01.gfklctx.local   <none>
calico-node-lfsch                                 2/2     Running   2          3m18s   172.28.16.83     vmkubei03.gfklctx.local   <none>
calico-node-pbr2z                                 1/2     Running   0          2m18s   172.28.16.89     vmkubep03.gfklctx.local   <none>
calico-node-rsnkr                                 1/2     Running   1          2m17s   172.28.16.90     vmkubep04.gfklctx.local   <none>
calico-node-wld7m                                 1/2     Running   0          2m17s   172.28.16.87     vmkubep01.gfklctx.local   <none>
coredns-598b4954b9-g8jrv                          1/1     Running   0          6m12s   192.168.203.65   vmkubei01.gfklctx.local   <none>
coredns-598b4954b9-xzp99                          1/1     Running   0          6m12s   192.168.203.66   vmkubei01.gfklctx.local   <none>
etcd-vmkubei01.gfklctx.local                      1/1     Running   0          5m10s   172.28.16.81     vmkubei01.gfklctx.local   <none>
etcd-vmkubei02.gfklctx.local                      1/1     Running   0          4m53s   172.28.16.82     vmkubei02.gfklctx.local   <none>
etcd-vmkubei03.gfklctx.local                      1/1     Running   0          3m8s    172.28.16.83     vmkubei03.gfklctx.local   <none>
kube-apiserver-vmkubei01.gfklctx.local            1/1     Running   0          5m36s   172.28.16.81     vmkubei01.gfklctx.local   <none>
kube-apiserver-vmkubei02.gfklctx.local            1/1     Running   0          4m13s   172.28.16.82     vmkubei02.gfklctx.local   <none>
kube-apiserver-vmkubei03.gfklctx.local            1/1     Running   0          2m46s   172.28.16.83     vmkubei03.gfklctx.local   <none>
kube-controller-manager-vmkubei01.gfklctx.local   1/1     Running   1          5m14s   172.28.16.81     vmkubei01.gfklctx.local   <none>
kube-controller-manager-vmkubei02.gfklctx.local   1/1     Running   0          4m20s   172.28.16.82     vmkubei02.gfklctx.local   <none>
kube-controller-manager-vmkubei03.gfklctx.local   1/1     Running   0          2m46s   172.28.16.83     vmkubei03.gfklctx.local   <none>
kube-proxy-55ntz                                  1/1     Running   0          2m17s   172.28.16.90     vmkubep04.gfklctx.local   <none>
kube-proxy-6dspq                                  1/1     Running   0          2m18s   172.28.16.88     vmkubep02.gfklctx.local   <none>
kube-proxy-86flc                                  1/1     Running   0          6m12s   172.28.16.81     vmkubei01.gfklctx.local   <none>
kube-proxy-dkvzd                                  1/1     Running   0          2m17s   172.28.16.87     vmkubep01.gfklctx.local   <none>
kube-proxy-dl5qs                                  1/1     Running   0          4m54s   172.28.16.82     vmkubei02.gfklctx.local   <none>
kube-proxy-fswqt                                  1/1     Running   0          2m17s   172.28.16.91     vmkubep05.gfklctx.local   <none>
kube-proxy-h9ptm                                  1/1     Running   0          3m18s   172.28.16.83     vmkubei03.gfklctx.local   <none>
kube-proxy-lzqxx                                  1/1     Running   0          2m18s   172.28.16.89     vmkubep03.gfklctx.local   <none>
kube-scheduler-vmkubei01.gfklctx.local            1/1     Running   1          5m35s   172.28.16.81     vmkubei01.gfklctx.local   <none>
kube-scheduler-vmkubei02.gfklctx.local            1/1     Running   0          4m11s   172.28.16.82     vmkubei02.gfklctx.local   <none>
kube-scheduler-vmkubei03.gfklctx.local            1/1     Running   0          2m46s   172.28.16.83     vmkubei03.gfklctx.local   <none>
[root@vmkubei01 ~]# 
```

When deploying for example kubernetes dashboard we see that the new pod is getting calico ip, but it's not able to access himself and so on.

what are we doing wrong?
