### ISSUE TITLE
error occurs after recreate node

### ISSUE THREAD

**Issue by kaybinwong** [projectcalico/calico#2302]
1. show the node info
```
[root@a-docker-cluster01 ~]# calicoctl get node a-docker-cluster01 -o yaml
- apiVersion: v1
  kind: node
  metadata:
    name: a-docker-cluster01
  spec:
    bgp:
      ipv4Address: 172.18.88.200/32
    orchRefs:
    - nodeName: a-docker-cluster01
      orchestrator: k8s
```
2. delete the node
```
[root@a-docker-cluster01 ~]# calicoctl delete node a-docker-cluster01
Successfully deleted 1 'node' resource(s)
```
3. recreate the node
```
[root@a-docker-cluster01 ~] echo '
- apiVersion: v1
  kind: node
  metadata:
    name: a-docker-cluster01
  spec:
    bgp:
      ipv4Address: 172.18.88.200/32
    orchRefs:
    - nodeName: a-docker-cluster01
      orchestrator: k8s' | calicoctl apply -f -
Successfully applied 1 'node' resource(s)
```
4. show the node status
```
[root@a-docker-cluster01 ~]# calicoctl node status
Calico process is not running.
```
error is below.
```
Nov 19 18:28:32 a-docker-cluster01 kubelet[11143]: E1119 18:28:32.123497   11143 kuberuntime_manager.go:733] container start failed: CreateContainerConfigError: host IP unknown; known addresses: []
```
what had i missed, help

## Expected Behavior
show the node status normally.

## Current Behavior
Calico process is not running.

## Possible Solution
```
calicoctl node run --node-image=calico/node:v2.6.8 --ip=172.18.88.200
```
it works, but not what i wanted. i just want to know how to fix the error above.

## Your Environment
* Calico version
v2.6.8 
* Orchestrator version (e.g. kubernetes, mesos, rkt):
kubernetes
* Operating System and version:
3.10.0-862.11.6.el7.x86_64
* Link to your project (optional):
nothing
