### ISSUE TITLE
3.4 Calico node inconsistent behaviour when generating bird.cfg when acting as route reflector

### ISSUE THREAD

**Issue by mrrandrade** [projectcalico/calico#2373]
We're trying to replace a 3.2 route reflector setup with a 3.4 cluster with calico-node as route reflectors.

We have followed [the guide](https://docs.projectcalico.org/v3.4/usage/configuration/bgp) but the result, without a single a change in configuration, that sometimes it generates the /etc/calico/confd/config/bird.cfg correctly, sometimes it generates with the default AS number instead. 

## Expected Behavior
 Every execution to generate the correct /etc/calico/confd/config/bird.cfg

## Current Behavior
 Inconsistence of generating /etc/calico/confd/config/bird.cfg.

## Possible Solution
Would like some help on pointing where to look for this one.

## Steps to Reproduce (for bugs)

We have followed the BGP configuration guide linked above.

1. We have set up the nodes with labels and routereflector cluster id:

```
calicoctl get nodes 10.79.63.19 -o yaml --export  
apiVersion: projectcalico.org/v3
kind: Node
metadata:
  creationTimestamp: null
  labels:
    route-reflector: "true"
  name: 10.79.63.19
spec:
  bgp:
    ipv4Address: 10.79.63.19/32
    routeReflectorClusterID: 224.0.0.1
apiVersion: projectcalico.org/v3
kind: Node
metadata:
  creationTimestamp: null
  labels:
    route-reflector: "true"
  name: 10.79.63.20
spec:
  bgp:
    ipv4Address: 10.79.63.20/32
    routeReflectorClusterID: 224.0.0.1
```

This is our bgpconfiguration object. Notice we do not use the default value (64512).

```
apiVersion: projectcalico.org/v3
kind: BGPConfiguration
metadata:
  creationTimestamp: null
  name: default
spec:
  asNumber: 64513
  logSeverityScreen: Info
  nodeToNodeMeshEnabled: false
```

We have fully followed the guide and created all kinds of different types of configuration of bgppers in order to figure out what is wrong. This is our current configuration:

```
apiVersion: projectcalico.org/v3
kind: BGPPeer
metadata:
  creationTimestamp: null
  name: peer-to-rrs
spec:
  asNumber: 0
  nodeSelector: '!has(route-reflector)'
  peerIP: ""
  peerSelector: has(route-reflector)
```

(I noted that the documentation has  nodeSelector: !has(route-reflector) without quotes, and as is, it does not get recorded into the ETCD backend. But anyways, We've tried with it, without it, and we still get inconsistent behaviour).

As a result of this configuration, we expect all of our nodes to pair with both route reflectors.

MOST of the times, when we start calico-node on route reflector, the bird.cfg shows up with the peers set with the WRONG as number (64512, which is the default). 

There is no occurence of 64512 on the ETCD database, so I'm assuming confd is either setting default for some reason:

```
# cat /etc/calico/confd/config/bird.cfg
...
# Template for all BGP clients
template bgp bgp_template {
  debug { states };
  description "Connection to BGP peer";
  # this is the correct number, as configured in the bgpconfiguration object.
  local as 64513;
  multihop;

...

# For peer /host/10.79.63.20/peer_v4/10.79.63.11
protocol bgp Node_10_79_63_11 from bgp_template {
  # When it DOESN'T work, the as get set to 64512 somehow and I do not know where it comes from.
  neighbor 10.79.63.11 as 64512;
}
 
# For peer /host/10.79.63.20/peer_v4/10.79.63.12
protocol bgp Node_10_79_63_12 from bgp_template {
  # When it DOESN'T work, the as get set to 64512 somehow and I do not know where it comes from.
  neighbor 10.79.63.12 as 64512;
}

```

Sometimes, we start it and without **any manual intervention** it just plain works.

```
# cat /etc/calico/confd/config/bird.cfg
...
# Template for all BGP clients
template bgp bgp_template {
  debug { states };
  description "Connection to BGP peer";
  # this is the correct number, as configured in the bgpconfiguration object.
  local as 64513;
  multihop;

...

# For peer /host/10.79.63.20/peer_v4/10.79.63.11
protocol bgp Node_10_79_63_11 from bgp_template {
  neighbor 10.79.63.11 as 64513;
  rr client;
  rr cluster id 224.0.0.1;
}
 
# For peer /host/10.79.63.20/peer_v4/10.79.63.12
protocol bgp Node_10_79_63_12 from bgp_template {
  # When this works, this line shows the correct AS and the rr client and cluster id shows up.
  neighbor 10.79.63.12 as 64513;
  rr client;
  rr cluster id 224.0.0.1;
}

```

One thing we noticed is that if they started in the "not working" setup, and we recreate a bgppeer object (without any changes, just a basic --export | replace), it **always** works.

I'd guess there's some problem sometimes with initial calico-node configuration; when reading data to process confd templates, maybe the order or processing might mess some values. After the recreation of a bgppeer object, it resyncs and corrects itself.

Could really use a hand on figuring out where to look, because this inconsistent behaviour is killing me!

## Context
 Basic setup with 2 route reflectors integrating with a regular router to broadcast Calico networks.

## Your Environment

* Calico version: 3.4 running on ETCD backend (not kubernetes internal)
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes 1.12, but I think its not relevant.
* Operating System and version: CoreOS 1911.3.0
* Link to your project (optional):
