### ISSUE TITLE
kubespray not compatible with cross-subnet IPIP

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico#2380]
User reported that kubespray's manifest uses this approach to configuring the Calico node IP:
```
       - name: IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
```
However, that results in the node IP being a `/32` in our datamodel, which breaks cross-subnet IPIP.
## Expected Behavior

If we're handed a bare IP, we could look up the subnet from those configured on the system.
## Current Behavior

Interpret bare IP as a `/32`.
## Steps to Reproduce (for bugs)

1. Install a Calico system with kubespray
2. Turn on cross-subnet
3.
4.

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):
