### ISSUE TITLE
calico network policy unauthorized

### ISSUE THREAD

**Issue by nik786** [projectcalico/calico#2407]
```
Failed to list *v1.NetworkPolicy: Unauthorized
```
Internet communication should happen in side of pod and intercommunication b/w pods should happen

calico version 3.1.3

1.
```
cat calico-rbac.yaml
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: calico-kube-controllers
rules:
  - apiGroups:
    - ""
    - extensions
    resources:
      - pods
      - namespaces
      - serviceaccounts
      - nodes
    verbs:
      - watch
      - list
  - apiGroups:
    - networking.k8s.io
    resources:
      - networkpolicies
    verbs:
      - watch
      - list
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: calico-kube-controllers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  #name: calico-kube-controllers
  name: admin
subjects:
- kind: ServiceAccount
  name: calico-kube-controllers
  namespace: kube-system

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: calico-node
rules:
  - apiGroups: [""]
    resources:
      - pods
      - nodes
    verbs:
      - get

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: calico-node
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: calico-node
subjects:
- kind: ServiceAccount
  name: calico-node
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:calico-node
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: calico-node
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:nodes

2. cat calico-kube-controllers.yaml
# Calico Version v3.1.1
# https://docs.projectcalico.org/v3.1/releases#v3.1.1
# This manifest includes the following component versions:
#   calico/kube-controllers:v3.1.1
# Create this manifest using kubectl to deploy
# the Calico Kubernetes controllers.
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: calico-kube-controllers
  namespace: kube-system
  labels:
    k8s-app: calico-kube-controllers
spec:
  # Only a single instance of the this pod should be
  # active at a time.  Since this pod is run as a Deployment,
  # Kubernetes will ensure the pod is recreated in case of failure,
  # removing the need for passive backups.
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      name: calico-kube-controllers
      namespace: kube-system
      labels:
        k8s-app: calico-kube-controllers
    spec:
      serviceAccount: calico-kube-controllers
      hostNetwork: true
      volumes:
        - name: kubeconfig
          hostPath: 
            path: /opt/apps/bin
      containers:
        - name: calico-kube-controllers
          # Make sure to pin this to your desired version.
          image: quay.io/calico/kube-controllers:v3.1.1
          env:
            # Configure the location of your etcd cluster.
            - name: ETCD_ENDPOINTS
              value: "http://192.168.10.150:2379"
            - name: KUBECONFIG
              value: /etc/kubernetes/calico-controller-kubeconfig
            - name: FELIX_DEFAULTENDPOINTTOHOSTACTION
              value: RETURN
          volumeMounts:
            - mountPath: /etc/kubernetes
              name: kubeconfig

cat calico-node-ds.yaml 
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: calico-node
  namespace: kube-system
  labels:
    k8s-app: calico-node
spec:
  selector:
    matchLabels:
      k8s-app: calico-node
  template:
    metadata:
      labels:
        k8s-app: calico-node
      annotations:
        # Mark this pod as a critical add-on; when enabled, the critical add-on scheduler
        # reserves resources for critical add-on pods so that they can be rescheduled after
        # a failure.  This annotation works in tandem with the toleration below.
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      hostNetwork: true
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      # Allow this pod to be rescheduled while the node is in "critical add-ons only" mode.
      # This, along with the annotation above marks this pod as a critical add-on.
      - key: CriticalAddonsOnly
        operator: Exists
      #serviceAccountName: calico-cni-plugin
      containers:
        # Runs calico/node container on each Kubernetes node.  This
        # container programs network policy and routes on each
        # host.
        - name: calico-node
          image: quay.io/calico/node:v3.1.1
          env:
            # The location of the Calico etcd cluster.
            - name: ETCD_ENDPOINTS
              value: "http://192.168.10.150:2379"
            # Enable BGP.  Disable to enforce policy only.
            - name: CALICO_NETWORKING_BACKEND
              value: "bird"
            # Set Felix endpoint to host default action to ACCEPT.
            - name: FELIX_DEFAULTENDPOINTTOHOSTACTION
              value: "ACCEPT"
            # Configure the IP Pool from which Pod IPs will be chosen.
            - name: CALICO_IPV4POOL_CIDR
              value: "10.1.0.0/16"
            # Node IP address.
            - name: IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            # Node Name.
            - name: NODENAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /lib/modules
              name: lib-modules
              readOnly: true
            - mountPath: /run/docker/plugins
              name: run-docker-plugin
              readOnly: false
            - mountPath: /var/run/docker.sock
              name: var-run-docker-sock
              readOnly: false
            - mountPath: /var/run/calico
              name: var-run-calico
              readOnly: false
            - mountPath: /var/lib/calico
              name: var-lib-calico
              readOnly: false
            - mountPath: /var/log/calico
              name: var-log-calico
              readOnly: false
      volumes:
        - name: lib-modules
          hostPath:
            path: /lib/modules
        - name: run-docker-plugin
          hostPath:
            path: /run/docker/plugins
        - name: var-run-docker-sock
          hostPath:
            path: /var/run/docker.sock
        - name: var-run-calico
          hostPath:
            path: /var/run/calico
        - name: var-lib-calico
          hostPath:
            path: /var/lib/calico
        - name: var-log-calico
          hostPath:
            path: /var/log/calico
```

**Comment by caseydavenport** [comment]
Looks like an RBAC issue to me - can you confirm that the RBAC is configured to allow kube-controllers to access that resource in the k8s API?

```
kubectl get clusterroles -o yaml calico-kube-controllers
```

**Comment by nik786** [comment]
kubectl get clusterroles -o yaml calico-kube-controllers
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: "2019-02-06T19:29:02Z"
  name: calico-kube-controllers
  resourceVersion: "12219"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/calico-kube-controllers
  uid: 756aa276-2a45-11e9-8876-080027b74296
rules:
- apiGroups:
  - ""
  - extensions
  resources:
  - pods
  - namespaces
  - serviceaccounts
  - nodes
  verbs:
  - watch
  - list
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - watch
  - list

**Comment by nik786** [comment]
any help or idea??

**Comment by caseydavenport** [comment]
@nik786 I've noticed that the role binding is modified to use "admin' instead of "calico-kube-controllers". I'd sorta expect that to work, but wondering if that's related. Could you try an unmodified set of RBAC?

```
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  #name: calico-kube-controllers
  name: admin
```
