### ISSUE TITLE
Network policies are not interpreted correctly when using namespaceSelector

### ISSUE THREAD

**Issue by menardorama** [projectcalico/calico#2443]
Migrating from kube-router a cluster with namespace isolation.
Installed calico with Kubernetes API Storage and ippools with IPinIP to false (same behaviour when it's set to true)

All namespaces are labeled in order to define network policies.

Systems namespaces are labeled with a specific label in order to grant access to all "application" namespaces (mostly for ingress controller traefik).

Here a netpol for the namespace app01 which is tagged with project: app01
```
apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  name: allow-only-from-admin
  namespace: app01
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          scope: admin
    - namespaceSelector:
        matchLabels:
          project: app01
  podSelector: {}
  policyTypes:
  - Ingress
```

Traffic is working correctly in the namespace but pod coming from namespaces with label ` scope: admin` are being blocked.

I didn't define any Global Network Policy, tried to add preNAT but it's the same problem.

The only thing I see is that I get profile defined when seeing using calicoctl; but i didn't do anything.

## Expected Behavior

Should work as is.

## Current Behavior

Not working at all

## Possible Solution

Remove network policies... but t's just a temporary workarround

## Steps to Reproduce (for bugs)

1. Deploy a kubernetes cluster
2. Install traefik in the kube-system
3. Label kube-system namespace with somthing
4. Create an application namespace and label it
5. Apply a networkpolicy that will allow the 2 labels.

## Context

Migration from kube-router to calico

## Your Environment

* Calico version : 3.5.1
* Orchestrator version: kubernetes 1.13.2
* Operating System and version: Ubuntu 18.04
* Docker CE 18.06
* Traefik 1.7.7
