### ISSUE TITLE
IPV6 BGP peer is not Established in calico node and stays Passive 

### ISSUE THREAD

**Issue by roshnihp** [projectcalico/calico#2458]
After installing Calico CNI for IPV6 kubernetes cluster, all pods are assigned IPV6 address but calico node does not establish BGP peering with IPV6 peer address. But can see IPV4 address as Established.

Below shows the output from the Kubernetes worker node. The peer address shows the Master node IP address.

```
/ # ./calicoctl node status
Calico process is running.

IPv4 BGP status
+--------------+-------------------+-------+----------+-------------+
| PEER ADDRESS |     PEER TYPE     | STATE |  SINCE   |    INFO     |
+--------------+-------------------+-------+----------+-------------+
| 172.16.0.6   | node-to-node mesh | up    | 15:24:40 | Established |
+--------------+-------------------+-------+----------+-------------+


IPv6 BGP status
+--------------+-------------------+-------+----------+---------+
| PEER ADDRESS |     PEER TYPE     | STATE |  SINCE   |  INFO   |
+--------------+-------------------+-------+----------+---------+
| 2019::100    | node-to-node mesh | start | 15:24:38 | **Passive** |
+--------------+-------------------+-------+----------+---------+
```

## Expected Behavior
I expects to get the IPV6 peering as established. 

```
IPv6 BGP status
+-----------------------------------+-------------------+-------+----------+-------------+
|           PEER ADDRESS            |     PEER TYPE     | STATE |  SINCE   |    INFO     |
+-----------------------------------+-------------------+-------+----------+-------------+
| 2019::100         | node-to-node mesh | up    | 07:07:04 | Established |
```

## Possible Solution
Dont have much idea if this is an issue of installation.

## Steps to Reproduce (for bugs)

1. Installed Kubernetes  on one master (IPV6 address : 2019::100) and one worker node (IPV6 address : 2019::100)
kubeadm init --pod-network-cidr=2019::1:192.168.0.0/112 --apiserver-advertise-address=2019::100 --service-cidr=2019::10.0.0.0/112
2. kubectl apply -f https://docs.projectcalico.org/v3.3/getting-started/kubernetes/installation/hosted/rbac-kdd.yaml
3. wget https://docs.projectcalico.org/v3.5/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/1.7/calico.yaml
4. Updated  calico node part of the file to add IPV6 support as below 

```
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: calico-node
  namespace: kube-system
  labels:
    k8s-app: calico-node
spec:
  selector:
    matchLabels:
      k8s-app: calico-node
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        k8s-app: calico-node
      annotations:
              scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
      hostNetwork: true
      tolerations:
        # Make sure calico-node gets scheduled on all nodes.
        - effect: NoSchedule
          operator: Exists
        # Mark the pod as a critical add-on for rescheduling.
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoExecute
          operator: Exists
      serviceAccountName: calico-node
      # Minimize downtime during a rolling upgrade or deletion; tell Kubernetes to do a "force
      # deletion": https://kubernetes.io/docs/concepts/workloads/pods/pod/#termination-of-pods.
      terminationGracePeriodSeconds: 0
      initContainers:
        # This container installs the Calico CNI binaries
        # and CNI network config file on each node.
        - name: install-cni
          image: calico/cni:v3.5.2
          command: ["/install-cni.sh"]
          env:
            # Name of the CNI config file to create.
            - name: CNI_CONF_NAME
              value: "10-calico.conflist"
            # The CNI network config to install on each node.
            - name: CNI_NETWORK_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: cni_network_config
            # Set the hostname based on the k8s node name.
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            # CNI MTU Config variable
            - name: CNI_MTU
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: veth_mtu
            # Prevents the container from sleeping forever.
            - name: SLEEP
              value: "false"
          volumeMounts:
            - mountPath: /host/opt/cni/bin
              name: cni-bin-dir
            - mountPath: /host/etc/cni/net.d
              name: cni-net-dir
      containers:
        # Runs calico/node container on each Kubernetes node.  This
        # container programs network policy and routes on each
        # host.
        - name: calico-node
          image: calico/node:v3.5.2
          env:
            # Use Kubernetes API as the backing datastore.
            - name: DATASTORE_TYPE
              value: "kubernetes"
            # Wait for the datastore.
            - name: WAIT_FOR_DATASTORE
              value: "true"
            # Set based on the k8s node name.
            - name: NODENAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            # Choose the backend to use.
            - name: CALICO_NETWORKING_BACKEND
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: calico_backend
            # Cluster type to identify the deployment type
            - name: CLUSTER_TYPE
              value: "k8s,bgp"
            # Auto-detect the BGP IP address.
            - name: IP6
              value: "autodetect"
            # Enable IPIP
            - name: CALICO_IPV4POOL_IPIP
              value: "off"
            # Set MTU for tunnel device used if ipip is enabled
            - name: FELIX_IPINIPMTU
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: veth_mtu
            # The default IPv4 pool to create on startup if none exists. Pod IPs will be
            # chosen from this range. Changing this value after installation will have
            # no effect. This should fall within `--cluster-cidr`.
            - name: CALICO_IPV6POOL_CIDR
              value: "2019::1:192.168.0.0/112"
            # Disable file logging so `kubectl logs` works.
            - name: CALICO_DISABLE_FILE_LOGGING
              value: "true"
            # Set Felix endpoint to host default action to ACCEPT.
            - name: FELIX_DEFAULTENDPOINTTOHOSTACTION
              value: "ACCEPT"
            # Disable IPv6 on Kubernetes.
            - name: FELIX_IPV6SUPPORT
              value: "true"
            # Set Felix logging to "info"
            - name: FELIX_LOGSEVERITYSCREEN
              value: "info"
            - name: FELIX_HEALTHENABLED
              value: "true"
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: 250m
          livenessProbe:
            httpGet:
              path: /liveness
              port: 9099
              host: localhost
            periodSeconds: 10
            initialDelaySeconds: 10
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
              - /bin/calico-node
              - -bird-ready
              - -felix-ready
            periodSeconds: 10
          volumeMounts:
            - mountPath: /lib/modules
              name: lib-modules
              readOnly: true
            - mountPath: /run/xtables.lock
              name: xtables-lock
              readOnly: false
            - mountPath: /var/run/calico
              name: var-run-calico
              readOnly: false
            - mountPath: /var/lib/calico
              name: var-lib-calico
              readOnly: false
      volumes:
        # Used by calico/node.
        - name: lib-modules
          hostPath:
            path: /lib/modules
        - name: var-run-calico
          hostPath:
            path: /var/run/calico
        - name: var-lib-calico
          hostPath:
            path: /var/lib/calico
        - name: xtables-lock
          hostPath:
            path: /run/xtables.lock
            type: FileOrCreate
        # Used to install CNI.
        - name: cni-bin-dir
          hostPath:
            path: /opt/cni/bin
        - name: cni-net-dir
          hostPath:
            path: /etc/cni/net.d
---
```

5.  Can see all pods running with IPV6 address

```
root@master1:/etc/systemd/network# kubectl get pods --all-namespaces -o wide
NAMESPACE     NAME                              READY   STATUS             RESTARTS   AGE    IP                 NODE      NOMINATED NODE   READINESS GATES

kube-system   calico-node-ltf92                 1/1     Running            0          84m    2019::101          worker1   <none>           <none>
kube-system   calico-node-pw8qj                 1/1     Running            0          84m    2019::100          master1   <none>           <none>
kube-system   coredns-86c58d9df4-56gw4          1/1     Running            38         154m   2019::1:c0a8:126   worker1   <none>           <none>
kube-system   coredns-86c58d9df4-gc7vf          1/1     Running   39         154m   2019::1:c0a8:125   worker1   <none>           <none>
kube-system   etcd-master1                      1/1     Running            0          153m   2019::100          master1   <none>           <none>
kube-system   kube-apiserver-master1            1/1     Running            0          153m   2019::100          master1   <none>           <none>
kube-system   kube-controller-manager-master1   1/1     Running            0          153m   2019::100          master1   <none>           <none>
kube-system   kube-proxy-t4bwb                  1/1     Running            0          154m   2019::101          worker1   <none>           <none>
kube-system   kube-proxy-tddjr                  1/1     Running            0          154m   2019::100          master1   <none>           <none>
kube-system   kube-scheduler-master1            1/1     Running            0          153m   2019::100          master1   <none>           <none>

```

6. Now get into one of the calico node and see the node status 

```
/ # ./calicoctl node status
Calico process is running.
IPv4 BGP status
+--------------+-------------------+-------+----------+-------------+
| PEER ADDRESS |     PEER TYPE     | STATE |  SINCE   |    INFO     |
+--------------+-------------------+-------+----------+-------------+
| 172.16.0.6   | node-to-node mesh | up    | 15:24:40 | Established |
+--------------+-------------------+-------+----------+-------------+

IPv6 BGP status
+--------------+-------------------+-------+----------+---------+
| PEER ADDRESS |     PEER TYPE     | STATE |  SINCE   |  INFO   |
+--------------+-------------------+-------+----------+---------+
| 2019::100    | node-to-node mesh | start | 15:24:38 | **Passive** |
+--------------+-------------------+-------+----------+---------+
```

## Context
I am trying to get connect to the kubernetes service and I get no route as the pods are running on worker nodes and there is no route between each other.

```
root@master1:/etc/systemd/network# kubectl get svc
NAME            TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
kubernetes      ClusterIP   2019::a00:1      <none>        443/TCP          158m
nginx-service   NodePort    2019::a00:ae83   <none>        8080:30302/TCP   154m
root@master1:/etc/systemd/network# curl http://[2019::a00:ae83]:8080
curl: (7) Failed to connect to 2019::a00:ae83 port 8080: No route to host
```

## Your Environment

* Calico version: 3.5.2
* Orchestrator version : kubernetes version : 1.13.3
* Operating System and version: I have VMs running with Ubuntu 18.04 LTS
* Link to your project (optional):
