### ISSUE TITLE
Understand why -- kubernetes calico network policy does not filter ping traffic

### ISSUE THREAD

**Issue by sarashakeri** [projectcalico/calico#2543]
Hi all,

I am using Kubernetes network policy and also calico for network plugin. I have deployed a simple policy on pod A which just accept ingress TCP traffic from pod B. I expect to not have any ping from pod A to pod B and also from pod B to pod A. pod B can not ping pod A. However, pinging pod B form pod A is possible! Below is the applied policy:

```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: access-nginx
spec:
  podSelector:
    matchLabels:
      name: A
  ingress:
  - from:
     - podSelector:
        matchLabels:
          name: B
    ports:
      - protocol: TCP
```

## Expected Behavior

None of the pods can ping each other.
## Current Behavior

 
pod B cannot ping pod A, but pod A can ping B.
## Your Environment

* Calico version : v3.5.4
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes, 1.14
* Operating System and version: Ubuntu 16.04.6 LTS- Xenial
