### ISSUE TITLE
canal ClusterRole requires namespace resource added to RBAC rules

### ISSUE THREAD

**Issue by erhudy** [projectcalico/calico#2556]
## Current Behavior
When deploying things into Kubernetes with Canal v3.6.1, I found that they were failing to progress beyond ContainerCreating state, with this error:
```
  Warning  FailedCreatePodSandBox  2m46s (x4 over 2m49s)   kubelet, node-3    (combined from similar events): Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "949119d5fc9d946a740faa03b0d2d297ce962d28c302bc89ffa43a832cd82dce" network for pod "smoke-test-deployment-5bc58fcf5d-c54j5": NetworkPlugin cni failed to set up pod "smoke-test-deployment-5bc58fcf5d-c54j5_smoke-test-namespace" network: namespaces "smoke-test-namespace" is forbidden: User "system:serviceaccount:kube-system:canal-node" cannot get resource "namespaces" in API group "" in the namespace "smoke-test-namespace"
```

## Possible Solution
Adding `namespaces` to the list of allowed resources for the **canal** ClusterRole resolved the issue:
```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: canal
rules:
  - apiGroups: [""]
    resources:
      - pods
      - nodes
      - namespaces
    verbs:
      - get
```

## Steps to Reproduce (for bugs)
1. Set up Canal using the Getting Started manifests for v3.6.1.
2. Launch a deployment and see if it succeeds.

## Context
Couldn't get Canal working for pod-networked containers until I made that change.

## Your Environment

* Calico version: v3.6.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes
* Operating System and version: Ubuntu Xenial 16.0.4.5
