### ISSUE TITLE
Network policy with multiple selectors does not work with IPv6 cluster

### ISSUE THREAD

**Issue by kahou82** [projectcalico/calico#2557]
I am trying to test out the network policy with multiple selector on a calico IPv6 cluster but it seems not working. Below are the steps to reproduce it:

```
# Deploy a db deployment and expose it as a service
kubectl run db-tnioue -n default --image=redis:4 --image-pull-policy=IfNotPresent --port 6379 --expose --labels app=bookstore,role=db

# Create some app pods and test out the connectivity to the db deployment
kubectl run catalog-eowqio -n default --image=alpine:3.8 --image-pull-policy=IfNotPresent --labels=app=inventory,role=web --command -- tail -f /dev/null

kubectl run api-jhod8q -n default --image=alpine:3.8 --image-pull-policy=IfNotPresent --labels=app=bookstore,role=api --command -- tail -f /dev/null

kubectl run search-mibjy1 -n default --image=alpine:3.8 --image-pull-policy=IfNotPresent --labels=app=bookstore,role=search --command -- tail -f /dev/null

kubectl run other-api-v1yivt -n default --image=alpine:3.8 --image-pull-policy=IfNotPresent --labels=app=other,role=api --command -- tail -f /dev/null

kubectl run other-inventory-v0pu66 -n default --image=alpine:3.8 --image-pull-policy=IfNotPresent --labels=app=inventory,role=other --command -- tail -f /dev/null

# Run nc to test out connection. At this point, all pod should access the db svc
kubectl exec -n default <APP POD NAME> -- nc -v -w 2 db-tnioue.default 6379

# Now apply the following network policy to the cluster
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: redis-allow-services
spec:
  podSelector:
    matchLabels:
      app: bookstore
      role: db
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: bookstore
          role: search
    - podSelector:
            matchLabels:
              app: bookstore
              role: api
    - podSelector:
            matchLabels:
              app: inventory
              role: web

# Test out the nc connection again, the pod with prefix "other" should not work and other app should work
kubectl exec -n default <APP POD NAME> -- nc -v -w 2 db-tnioue.default 6379
```

Note: This test works perfectly in Calico IPv4 cluster.

## Expected Behavior
pod add with app:other label will not work but the rest of app will work

## Current Behavior
app which is allowed in the network policy cannot talk to the db svc

## Steps to Reproduce (for bugs)
See description

## Your Environment

* Calico version: 3.6.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): k8s 1.12.6
* Operating System and version: ubuntu 18.04
* Link to your project (optional):
