### ISSUE TITLE
Calico IP-forward rule causing SCTP connection to drop

### ISSUE THREAD

**Issue by nikhil-96** [projectcalico/calico#2570]
While sending SCTP connection from host to pod or pod to pod in same worker node, calico ip-forward rule causing INIT-ACK to drop. 

## Expected Behavior
SCTP connection from host to pod or pod to pod in the kubernetes environment should go through.

## Current Behavior
While sending SCTP connection from host to pod or pod to pod in same worker node, calico ip-forward rule causing INIT-ACK to drop (It is also true for pod to pod in different worker nodes, however it works fine if I start sctp client & server in the same pod). In my case following two rules in iptables (of filter table) which are causing sctp packet to drop are :
=> cali-fw-calif498e885c39 -m comment --comment "cali:nrRYKNz5iJPxLbvb" -m conntrack --ctstate INVALID -j DROP
=> cali-tw-calif498e885c39 -m comment --comment "cali:VAKfjUiWZY3FdsCf" -m conntrack --ctstate INVALID -j DROP

## Temporary work-around
In order to verify that my SCTP packet drops due to iptables rule created by calico, I deleted these two rules manually from iptables :
=> iptables -D cali-fw-calif498e885c39 -m comment --comment "cali:nrRYKNz5iJPxLbvb" -m conntrack --ctstate INVALID -j DROP
=> iptables -D cali-tw-calif498e885c39 -m comment --comment "cali:VAKfjUiWZY3FdsCf" -m conntrack --ctstate INVALID -j DROP
After deleting above specified rules, I was able to run SCTP connection from worker node to target pod. 
Also I tested another scenario to update above specified rules to work with only tcp protocol like this : 
=> cali-fw-calif498e885c39 -p tcp -m comment --comment "cali:nrRYKNz5iJPxLbvb" -m conntrack --ctstate INVALID -j DROP
=> cali-tw-calif498e885c39 -p tcp -m comment --comment "cali:VAKfjUiWZY3FdsCf" -m conntrack --ctstate INVALID -j DROP
In this scenario, sctp connection go through successfully.

## Steps to Reproduce (for bugs)
1.  Created a pod on a worker node with a svc having SCTP enabled using following yaml : 
```
apiVersion: apps/v1
kind: Deployment
metadata:
# name should be of maximum 3 characters
  name: sctp
  labels:
    k8-xyz-app: sctp
spec:
  replicas: 1
  selector:
    matchLabels:
      k8-xyz-app: sctp
  template:
    metadata:
      labels:
        k8-xyz-app: sctp
      annotations:
       sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: sctp
        image: oraclelinux:7.6
        command: ["/bin/bash", "-c", "--"]
        args: ["while true; do sleep 30; done;" ]

---
kind: Service
apiVersion: v1
metadata:
  name: sctp-svc
spec:
  type: LoadBalancer
  ports:
  - name: sctp-svc
    protocol: SCTP
    port: 3868
  externalTrafficPolicy: Local
  selector:
    k8-xyz-app: sctp
```
This yaml creates a pod which listens on 3868 & a service of type LoadBalancer :
```
Name:                     sctp-svc
Namespace:                default
Labels:                   <none>
Annotations:              <none>
Selector:                 k8-xyz-app=sctp
Type:                     LoadBalancer
IP:                       10.108.133.96
Port:                     sctp-svc  3868/SCTP
TargetPort:               3868/SCTP
NodePort:                 sctp-svc  31535/SCTP
Endpoints:                192.168.140.67:3868
Session Affinity:         None
External Traffic Policy:  Local
HealthCheck NodePort:     30329
Events:                   <none>
```
2. Run SCTP server on pod to listen SCTP connection using netcat : 
ncat -k -l --sctp 192.168.140.67 3868 -v -v
3. Run SCTP client on worker node to send SCTP connection using netcat : 
ncat --sctp 192.168.140.67 3868 -v -v
4. Now you can see that INIT is reaching SCTP server successfully but INIT-ACK is failing to reach SCTP client.

## Your Environment
* Calico version 3.6.1
* Orchestrator version : **kubernetes 1.13.2**
* Operating System and version: **Oracle Linux Server release 7.5**
