### ISSUE TITLE
Installing Calico 3.6 in Kubernetes results in error in calico-kube-controllers

### ISSUE THREAD

**Issue by proskehy** [projectcalico/calico#2597]
I am trying to upgrade Calico in my k8s cluster from 3.3 to 3.6. To upgrade, I delete the previously created resources and create new ones. The pod `calico-kube-controllers` is stuck in `ContainerCreating`, so none of the `calico-node` pods start.

## Expected Behavior
Calico pods described in the used manifest are created and start running.

## Current Behavior
Calico-kube-controllers does not exit the `ContainerCreating` state.
`kubectl describe pod` shows this error:
```Failed create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "4a3c5993de2bb25bb59c33f55a1ea65f2584980c83c4704ebde6af5bec3e09b5" network for pod "calico-kube-controllers-5cbcccc885-nddnj": NetworkPlugin cni failed to set up pod "calico-kube-controllers-5cbcccc885-nddnj_kube-system" network: error getting ClusterInformation: connection is unauthorized: Unauthorized, failed to clean up sandbox container "4a3c5993de2bb25bb59c33f55a1ea65f2584980c83c4704ebde6af5bec3e09b5" network for pod "calico-kube-controllers-5cbcccc885-nddnj": NetworkPlugin cni failed to teardown pod "calico-kube-controllers-5cbcccc885-nddnj_kube-system" network: error getting ClusterInformation: connection is unauthorized: Unauthorized]```

## Possible Solution
I am able to upgrade all the way to 3.5, which is the last version without calico-kube-controllers, so I assume there is something going on with this new addition?

## Steps to Reproduce (for bugs)
I do not have a fresh cluster to test this on, but how I got where I am is this:
1. Create a cluster with kubeadm (I have been through about 3 major Kubernetes verison upgrades with the cluster)
2. Install Calico 3.3 following https://docs.projectcalico.org/v3.3/getting-started/kubernetes/installation/calico#installing-with-the-kubernetes-api-datastore50-nodes-or-less
3. Delete the resources created in step 2. with `kubectl delete -f` 
4. Install Calico 3.6 following https://docs.projectcalico.org/v3.6/getting-started/kubernetes/installation/calico#installing-with-the-kubernetes-api-datastore50-nodes-or-less

## Context
I'm trying to upgrade the Calico version in my cluster.

## Your Environment
* Calico version 3.3, trying to get to 3.6
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes, created via kubeadm
* Operating System and version: Centos 7

**Comment by niekvn1** [comment]
It looks like the same problem I currently have with upgrading from 3.1 to 3.7.

**Comment by dklesev** [comment]
Had the same problem. I run my lab cluster with [this](https://github.com/galexrt/k8s-vagrant-multi-node/issues).
As default OS is fedora I did following changes to calico:

- replaced *cni-bin-dir* to **/usr/libexec/cni**
- `echo 1 > /proc/sys/net/ipv4/conf/all/rp_filter` ([mor info here](https://www.slashroot.in/linux-kernel-rpfilter-settings-reverse-path-filtering))
- tried 3.3 before with addition to rbac:
```
...
- apiGroups: [""]
    resources:
      - nodes/status
    verbs:
      - patch
...
```
- set *IP_AUTODETECTION_METHOD* to **"interface=eth1"**
- used **"10.244.0.0/16"** as *CALICO_IPV4POOL_CIDR*

Resolved all issues by inspecting logs.

**Comment by caseydavenport** [comment]
>  NetworkPlugin cni failed to teardown pod "calico-kube-controllers-5cbcccc885-nddnj_kube-system" network: error getting ClusterInformation: connection is unauthorized: Unauthorized]

This seems to indicate that calico/node (the CNI plugin, specifically) isn't authorized to get ClusterInformation resources. 

Looking at https://docs.projectcalico.org/v3.6/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/1.7/calico.yaml, I see the following inside the ClusterRole for calico-node, which seems to indicate it _does_ have access.

```
  # Calico monitors various CRDs for config.
  - apiGroups: ["crd.projectcalico.org"]
    resources:
      - globalfelixconfigs
      - felixconfigurations
      - bgppeers
      - globalbgpconfigs
      - bgpconfigurations
      - ippools
      - ipamblocks
      - globalnetworkpolicies
      - globalnetworksets
      - networkpolicies
      - clusterinformations
      - hostendpoints
    verbs:
      - get
      - list
      - watch
```

@proskehy @niekvn1 can you guys do a `kubectl get clusterrole calico-node` and see if it contains this section?

**Comment by caseydavenport** [comment]
> The pod calico-kube-controllers is stuck in ContainerCreating, so none of the calico-node pods start.

Actually, this isn't quite right - calico-node doesn't require kube-controllers to start. In fact, its the other way around. In this case, it's likely calico-node that is causing the above errors.

Can you check the calico-node logs to see why they are failing?

**Comment by niekvn1** [comment]
Hi @caseydavenport,

This is the output I get,
`$  kubectl -n kube-system get clusterrole calico-node-c8zxp
Error from server (NotFound): clusterroles.rbac.authorization.k8s.io "calico-node-c8zxp" not found`

`kubectl -n kube-system logs calico-node-c8zxp
Error from server (BadRequest): container "calico-node" in pod "calico-node-c8zxp" is waiting to start: PodInitializing`

**Comment by proskehy** [comment]
Hi @caseydavenport, sorry for the delayed reply.

I checked the created ClusterRole and got the same result as @niekvn1:

```
- apiGroups:
  - crd.projectcalico.org
  resources:
  - globalfelixconfigs
  - felixconfigurations
  - bgppeers
  - globalbgpconfigs
  - bgpconfigurations
  - ippools
  - ipamblocks
  - globalnetworkpolicies
  - globalnetworksets
  - networkpolicies
  - clusterinformations
  - hostendpoints
  verbs:
  - get
  - list
  - watch
```

Could this be something that can only be solved by accessing the node as @dklesev mentions?
