### ISSUE TITLE
Default ingress deny policy allows traffic between pods on the same node via a service

### ISSUE THREAD

**Issue by leonsodhi-lf** [projectcalico/calico#2632]
## Expected Behavior
All ingress traffic should be blocked unless it's explicitly allowed via a separate policy.

## Current Behavior
The connection is allowed from a pod on the same node:
```
/ # wget -T 5 kube-state-metrics:8080
Connecting to kube-state-metrics:8080 (172.20.121.13:8080)
index.html           100% |*************************************************************|   289   0:00:00 E
```
Running the same test on a pod created via the same daemonset that's executing on a different node results in the expected behaviour:
```
/ # wget -T 5 kube-state-metrics:8080
Connecting to kube-state-metrics:8080 (172.20.121.13:8080)
wget: download timed out
```

## Possible Solution
Unknown

## Steps to Reproduce (for bugs)
1. Start a pod that contains an Nginx (or other webserver) container that runs inside the `a-namespace` namespace
2. Create a service that targets this Nginx pod, e.g:
```
apiVersion: v1
kind: Service
metadata:
  name: an-app
  namespace: a-namespace
  labels:
    k8s-app: an-app
spec:
  ports:
  - name: http-metrics
    port: 8080
    targetPort: http-metrics
    protocol: TCP 
  selector:
    k8s-app: an-app

```
3. Start another pod in the same namespace that can be used as an HTTP client
4. Ensure both pods are running on the same node
5. Apply a network policy that denies all traffic, e.g:
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: a-namespace
spec:
  podSelector: {}
  ingress: []
```
6. Attempt to connect to the listener from the client using `wget`, `telnet`, etc.

## Context
The goal is to block all ingress traffic by default, regardless of the source, with the exception of traffic that is explicitly allowed.

## Your Environment
* Calico version: 3.3.6 (https://github.com/aws/amazon-vpc-cni-k8s/blob/master/config/v1.4/calico.yaml was used as a base to configure all Calico components)
* Orchestrator version (e.g. kubernetes, mesos, rkt): AWS EKS running Kubernetes v1.11.8-eks-7c34c0
* Operating System and version: Alpine
