### ISSUE TITLE
Unexpected behavior with networkpolicies and service type loadbalancer

### ISSUE THREAD

**Issue by TheKangaroo** [projectcalico/calico#2635]
Unexpected behavior with networkpolicies and service type loadbalancer.

## Expected Behavior
I deployed a app to kubernetes and published it as service type loadbalancer. The service listens on 443 and the pods behind on 6443. Ingress on this service is allowed for anyone.
I expected to 
* deploy a network policy to another namespace which allows egress 443 and can access the external IP on port 443.
* deploy a network policy to a namespace in another cluster which allows egress 443 and can access the external IP between clusters on port 443.

## Current Behavior
To access the app between clusters I can deploy a networkpolicy with egress 443 and everything works as expected.
To access the app from the same cluster I need to deploy a networkpolicy with egress 6443 (the pod port) which is unexpected.

## Possible Solution
I dug a bit into kubernetes iptables rules, and I think the root cause is the KUBE-SERVICES chain in the OUTPUT chain which directly maps the external ip to the internal service ip and then to the pod service ip and the port 443 to the pod port 6443.

## Steps to Reproduce (for bugs)
1.
Deploy a service to a namespace, e.g. an ingress:
```
apiVersion: v1
kind: Service
metadata:
  name: ingress
  namespace: ingress
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: https
    port: 443
    targetPort: 6443
    protocol: TCP    
  selector:
    app: ingress-nginx
  type: LoadBalancer
  externalTrafficPolicy: Local
```
and add the according deployment/pods
2.
Add a NetPol to a diffrent Namespace:
```
apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  labels:
    app: myapp
  name: allow-ingress access
  namespace: nottheingressnamespace
spec:
  egress:
  - ports:
    - port: 443 (<- works only if you are in a diffrent cluster,
                 needs to be 6443 for the same cluster)
      protocol: TCP
  podSelector:
    matchLabels:
      app: myapp
  policyTypes:
  - Egress
```
3.
run pod with label `app: myapp` and try to access the ingress from within the pod.

## Context
Maybe this is the expected behavior, but it was quite surprising since we accessed the service via an external IP and the behavior is different from different clusters.

## Your Environment

* Calico version v3.4.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes 1.13.4
* Operating System and version: CoreOS 1855.5.0
