### ISSUE TITLE
Add shortName gnp to GlobalNetworkPolicy CRD

### ISSUE THREAD

**Issue by vgramer** [projectcalico/calico#2651]
Currently the crd `GlobalNetworkPolicy` have only singular and plural name (`GlobalNetworkPolicy` and `GlobalNetworkPolicies`). Theses names are a bit long, it would be nice to have a shortName. 

i propose to add the shortName `gnp`

## Possible Solution
```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: globalnetworkpolicies.crd.projectcalico.org
spec:
  scope: Cluster
  group: crd.projectcalico.org
  version: v1
  names:
    kind: GlobalNetworkPolicy
    plural: globalnetworkpolicies
    singular: globalnetworkpolicy
    shortNames:
      - gnp
```
