### ISSUE TITLE
Network policy ingress rule can't match remote non-k8s-node IP

### ISSUE THREAD

**Issue by tungdam** [projectcalico/calico#2660]
Hi
I have a problem with applying network policy for my pod against the node which is outside the k8s cluster. 

The situation is like this:

We have kubernetes 1.12, calico 3.5 setup, which advertise clusterIP range over BGP following [this](https://docs.projectcalico.org/v3.5/usage/service-advertisement) instruction. 

As security concern, we just want to expose my pod to fixed list of remote hosts ( non-k8s ones ). 
Here's my network policy config: 

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-policy
  namespace: default
spec:
  podSelector:
      matchLabels:
          svc-group: test
  policyTypes:
  - Ingress
  ingress:
  - from:
    - ipBlock:
        cidr: 10.101.1.1/32
    ports:
    - protocol: TCP
      port: 80
```

My svc/deployment yaml: 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.k8s.itim.vn/name: "td-nginx"
  name: "td-nginx"
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      application: "td-nginx"
  template:
    metadata:
      annotations:
        cni.projectcalico.org/ipv4pools: '["10.199.0.0/21"]'
      labels:
        application: "td-nginx"
        svc-group: "test"
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.k8s.itim.vn/name: "td-nginx"
    app.k8s.itim.vn/instance: "td-nginx"
  name: "td-nginx"
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    application: "td-nginx"
```

My test service's clusterIP:
```
kubectl get svc td-nginx
NAME       TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)   AGE
td-nginx   ClusterIP   10.196.54.69   <none>        80/TCP    27h
```

My clusterIP range: 10.196.48.0/20 
My calico pod ip range: 10.198.0.0/15 ( which i set to kube proxy's clusterCIDR param ) 
IPs for test pod 
```
kubectl get pod -o wide | fgrep td-nginx
td-nginx-6658b757c-5lxsw                             1/1     Running   0          27h   10.199.7.64    nodeA          <none>
td-nginx-6658b757c-c5snz                             1/1     Running   0          27h   10.199.5.129   nodeB               <none>
```
## Expected Behavior

With network policy above applied: 

Can access to port 80 of my service by clusterIP ( 10.196.54.69 ) from an IP ( non-k8s node which is white-listed in network policy config - 10.101.1.1. 

## Current Behavior
With network policy applied: 
- Can't access from external node ( 10.101.1.1 ) to clusterIP ( 10.196.54.69 ) 
- Still can access to pod IP directly 
- if we reconfigure service to LoadBalancer type as below
```
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
```
And edit deployment to deploy 1 replica only, it works. 
If replica = 2, sometimes it works, sometimes it's blocked 

With network policy removed:
- Can access to both clusterIP and pod IPs

## Possible reason 
The source IP before hitting network policy was changed by kube-proxy
`-A KUBE-SERVICES ! -s 10.198.0.0/15 -d 10.196.54.69/32 -p tcp -m comment --comment "default/td-nginx: cluster IP" -m tcp --dport 80 -j KUBE-MARK-MASQ`

## Question
Is it possible to apply network policy with external IP address ( outside kubernetes cluster)  as I did above ? 

Thanks in advance 

## My Environment
* Calico 3.5
* Kubernetes 1.12
* Debian 9
