### ISSUE TITLE
Global network policy no effective after upgrading the components from 3.1.3 to 3.7.2

### ISSUE THREAD

**Issue by prabhakar-pal** [projectcalico/calico#2665]
- Running Calico 3.1.3 with Kubernetes 1.14.3 
- Tried upgrading to 3.7.2 by updating the calico k8s services and calicoctl binary
- The calico global network policies which were effective in 3.1.3 stopped working
- Followed instructions in https://docs.projectcalico.org/v3.7/getting-started/kubernetes/installation/calico 
- Basically  applied https://docs.projectcalico.org/v3.7/manifests/calico.yaml manifest and copied the calicoctl manifest [ Is that enough? ]
- This is the policy to block ingress traffic which stopped working - now all ports are open from outside

```
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: drop-other-ingress
spec:
  applyOnForward: true
  ingress:
  - action: Deny
    destination: {}
    source: {}
  order: 20
  preDNAT: true
  selector: has(host-endpoint)
  types:
  - Ingress

```
