### ISSUE TITLE
specific ip with annotations not repect

### ISSUE THREAD

**Issue by wu0407** [projectcalico/calico#2702]
this [link](https://docs.projectcalico.org/v3.7/reference/cni-plugin/configuration#requesting-a-specific-ip-address) assign the specific ip not respected.
test float ip and ipaddrs same result

## Expected Behavior

assign the specific ip for deployment pod

## Current Behavior

assign ip not same what annotations

## Steps to Reproduce (for bugs)

1. the cni config
```
root@k8s-test02:~# cat /etc/cni/net.d/10-calico.conf                        
{
    "name": "calico-k8s-network",
    "cniVersion": "0.3.1",
    "type": "calico",
    "etcd_endpoints": "http://192.168.0.13:2379",
    "log_level": "info",
    "ipam": {
        "type": "calico-ipam"
    },
    "kubernetes": {
        "kubeconfig": "/etc/kubernetes/kubelet.kubeconfig"
    },
    "feature_control": {
         "floating_ips": true
     }
}
``` 
calico split sbunet for k8s-test02 is 10.1.105.192/26
```
root@k8s-test02:~# ip route
default via 192.168.0.1 dev bond0.2 onlink 
blackhole 10.1.105.192/26  proto bird 
10.1.105.195 dev calieb986ccc2e3  scope link 
10.1.105.211 dev cali2741528c153  scope link 
10.1.105.222 dev calic37973f231f  scope link 
10.1.105.231 dev cali046b21d4944  scope link 
10.1.105.241 dev caliab7ec5c8f94  scope link 
10.1.105.243 dev calidc5f8e53dda  scope link 
10.1.105.246 dev cali360b1569bac  scope link 
10.1.105.248 dev calica457f57f7c  scope link 
10.1.231.128/26 via 192.168.0.12 dev bond0.2  proto bird 
192.168.0.0/24 dev bond0.2  proto kernel  scope link  src 192.168.0.11
```

2. create deployment
```
cat test-network-nginx.yml 
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  labels:
    run: test-network-nginx
  name: test-network-nginx
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: test-network-nginx
      version: v2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cni.projectcalico.org/ipAddrs: '["10.1.105.223"]'
      creationTimestamp: null
      labels:
        run: test-network-nginx
        version: v2
    spec:
      nodeName: k8s-test02
      containers:
      - env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: nginx-test-daemon:v1.2
        imagePullPolicy: IfNotPresent
        name: test-network-nginx
        resources:
          limits:
            cpu: "1"
            memory: 1G
          requests:
            cpu: "1"
            memory: 1G
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: Default
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
```

3. apply deployment

4.get pod
```
kubectl get pod -o wide
test-network-nginx-6c5f4d8d6b-2q8xt          1/1     Running   0          37m     10.1.105.211   k8s-test02  <none>           <none>
```

## Your Environment

* Calico version
3.7.2
* Orchestrator version (e.g. kubernetes, mesos, rkt):
1.14.1
* Operating System and version:
ubuntu 16.04
* Link to your project (optional):
