### ISSUE TITLE
new pod ip cannot ping successfully suddenly 

### ISSUE THREAD

**Issue by tingweiwu** [projectcalico/calico#2723]
I use calico as my  k8s cluster  network componet  and it run normally last few months.

and suddenly when new pod created, the pod ip o can't ping successfully 

## Expected Behavior

pod ip cannot ping successfully from host

## Current Behavior

here is my pods on one node 
![image](https://user-images.githubusercontent.com/29671725/61193053-93e08100-a6eb-11e9-92c4-936542b177c5.png)
the new pod ip `192.168.211.75` can't ping successfully but the old pod ip `192.168.211.84` still ping successfully 
![image](https://user-images.githubusercontent.com/29671725/61193089-e15cee00-a6eb-11e9-92bd-a0d09a1a5d50.png)

here is the calico-node logs when I create the new pod `ifae97645333407eb3f312af988e529d-single-0 `

```
{"log":"2019-07-15 02:19:05.950 [INFO][207] int_dataplane.go 690: Applying dataplane updates\n","stream":"stdout","time":"2019-07-15T02:19:05.95034452Z"}
{"log":"2019-07-15 02:19:05.950 [INFO][207] table.go 717: Invalidating dataplane cache ipVersion=0x4 reason=\"refresh timer\" table=\"filter\"\n","stream":"stdout","time":"2019-07-15T02:19:05.950452105Z"}
{"log":"2019-07-15 02:19:05.950 [INFO][207] table.go 438: Loading current iptables state and checking it is correct. ipVersion=0x4 table=\"filter\"\n","stream":"stdout","time":"2019-07-15T02:19:05.9504673Z"}
{"log":"2019-07-15 02:19:05.952 [INFO][207] int_dataplane.go 704: Finished applying updates to dataplane. msecToApply=2.018841\n","stream":"stdout","time":"2019-07-15T02:19:05.95236442Z"}
{"log":"2019-07-15 02:19:07.744 [INFO][207] health.go 150: Overall health summary=\u0026health.HealthReport{Live:true, Ready:true}\n","stream":"stdout","time":"2019-07-15T02:19:07.744669821Z"}
{"log":"2019-07-15 02:19:11.672 [INFO][207] int_dataplane.go 690: Applying dataplane updates\n","stream":"stdout","time":"2019-07-15T02:19:11.672773727Z"}
{"log":"2019-07-15 02:19:11.672 [INFO][207] ipsets.go 222: Asked to resync with the dataplane on next update. family=\"inet\"\n","stream":"stdout","time":"2019-07-15T02:19:11.672796618Z"}
{"log":"2019-07-15 02:19:11.672 [INFO][207] ipsets.go 253: Resyncing ipsets with dataplane. family=\"inet\"\n","stream":"stdout","time":"2019-07-15T02:19:11.672831329Z"}
{"log":"2019-07-15 02:19:11.676 [INFO][207] ipsets.go 295: Finished resync family=\"inet\" numInconsistenciesFound=0 resyncDuration=3.37344ms\n","stream":"stdout","time":"2019-07-15T02:19:11.676205746Z"}
{"log":"2019-07-15 02:19:11.676 [INFO][207] int_dataplane.go 704: Finished applying updates to dataplane. msecToApply=3.544368\n","stream":"stdout","time":"2019-07-15T02:19:11.676248688Z"}
{"log":"2019-07-15 02:19:13.183 [INFO][207] health.go 150: Overall health summary=\u0026health.HealthReport{Live:true, Ready:true}\n","stream":"stdout","time":"2019-07-15T02:19:13.1838769Z"}
{"log":"2019-07-15 02:19:15.303 [INFO][207] int_dataplane.go 447: Linux interface addrs changed. addrs=set.mapSet{\"fe80::ecee:eeff:feee:eeee\":set.empty{}} ifaceName=\"caliec83ef92d7e\"\n","stream":"stdout","time":"2019-07-15T02:19:15.303427458Z"}
{"log":"2019-07-15 02:19:15.303 [INFO][207] int_dataplane.go 598: Received interface addresses update msg=\u0026intdataplane.ifaceAddrsUpdate{Name:\"caliec83ef92d7e\", Addrs:set.mapSet{\"fe80::ecee:eeff:feee:eeee\":set.empty{}}}\n","stream":"stdout","time":"2019-07-15T02:19:15.303562173Z"}
{"log":"2019-07-15 02:19:15.303 [INFO][207] int_dataplane.go 690: Applying dataplane updates\n","stream":"stdout","time":"2019-07-15T02:19:15.303578347Z"}
{"log":"2019-07-15 02:19:15.303 [INFO][207] int_dataplane.go 704: Finished applying updates to dataplane. msecToApply=0.079182\n","stream":"stdout","time":"2019-07-15T02:19:15.303665534Z"}
{"log":"2019-07-15 02:19:15.306 [INFO][207] int_dataplane.go 429: Linux interface state changed. ifaceName=\"caliec83ef92d7e\" state=\"up\"\n","stream":"stdout","time":"2019-07-15T02:19:15.306248984Z"}
{"log":"2019-07-15 02:19:15.306 [INFO][207] int_dataplane.go 588: Received interface update msg=\u0026intdataplane.ifaceUpdate{Name:\"caliec83ef92d7e\", State:\"up\"}\n","stream":"stdout","time":"2019-07-15T02:19:15.306336666Z"}
{"log":"2019-07-15 02:19:15.306 [INFO][207] int_dataplane.go 690: Applying dataplane updates\n","stream":"stdout","time":"2019-07-15T02:19:15.30667024Z"}
{"log":"2019-07-15 02:19:15.306 [INFO][207] endpoint_mgr.go 239: Workload interface came up, marking for reconfiguration. ifaceName=\"caliec83ef92d7e\"\n","stream":"stdout","time":"2019-07-15T02:19:15.307071174Z"}
{"log":"2019-07-15 02:19:15.306 [INFO][207] endpoint_mgr.go 777: Applying /proc/sys configuration to interface. ifaceName=\"caliec83ef92d7e\"\n","stream":"stdout","time":"2019-07-15T02:19:15.307077778Z"}
{"log":"2019-07-15 02:19:15.307 [INFO][207] route_table.go 442: Syncing routes: found unexpected route; ignoring due to grace period. dest=192.168.211.75/32 ifaceName=\"caliec83ef92d7e\" ipVersion=0x4\n","stream":"stdout","time":"2019-07-15T02:19:15.307626002Z"}
{"log":"2019-07-15 02:19:15.307 [INFO][207] route_table.go 298: Interface in cleanup grace period, will retry after. ifaceName=\"caliec83ef92d7e\" ipVersion=0x4\n","stream":"stdout","time":"2019-07-15T02:19:15.307642619Z"}
{"log":"2019-07-15 02:19:15.307 [INFO][207] int_dataplane.go 704: Finished applying updates to dataplane. msecToApply=0.801575\n","stream":"stdout","time":"2019-07-15T02:19:15.307647377Z"}
{"log":"2019-07-15 02:19:16.342 [INFO][207] iface_monitor.go 168: Netlink address update. addr=\"fe80::ecee:eeff:feee:eeee\" exists=true ifIndex=111\n","stream":"stdout","time":"2019-07-15T02:19:16.342398841Z"}
{"log":"2019-07-15 02:19:17.744 [INFO][207] health.go 150: Overall health summary=\u0026health.HealthReport{Live:true, Ready:true}\n","stream":"stdout","time":"2019-07-15T02:19:17.744711458Z"}
{"log":"2019-07-15 02:19:22.513 [INFO][207] int_dataplane.go 690: Applying dataplane updates\n","stream":"stdout","time":"2019-07-15T02:19:22.513753512Z"}
{"log":"2019-07-15 02:19:22.513 [INFO][207] ipsets.go 222: Asked to resync with the dataplane on next update. family=\"inet\"\n","stream":"stdout","time":"2019-07-15T02:19:22.513779073Z"}
{"log":"2019-07-15 02:19:22.513 [INFO][207] ipsets.go 253: Resyncing ipsets with dataplane. family=\"inet\"\n","stream":"stdout","time":"2019-07-15T02:19:22.513783399Z"}
{"log":"2019-07-15 02:19:22.513 [INFO][207] route_table.go 442: Syncing routes: found unexpected route; ignoring due to grace period. dest=192.168.211.75/32 ifaceName=\"caliec83ef92d7e\" ipVersion=0x4\n","stream":"stdout","time":"2019-07-15T02:19:22.514130542Z"}
{"log":"2019-07-15 02:19:22.514 [INFO][207] route_table.go 298: Interface in cleanup grace period, will retry after. ifaceName=\"caliec83ef92d7e\" ipVersion=0x4\n","stream":"stdout","time":"2019-07-15T02:19:22.514152744Z"}
{"log":"2019-07-15 02:19:22.517 [INFO][207] ipsets.go 295: Finished resync family=\"inet\" numInconsistenciesFound=0 resyncDuration=3.418333ms\n","stream":"stdout","time":"2019-07-15T02:19:22.517208267Z"}
{"log":"2019-07-15 02:19:22.517 [INFO][207] int_dataplane.go 704: Finished applying updates to dataplane. msecToApply=3.641408\n","stream":"stdout","time":"2019-07-15T02:19:22.517258039Z"}
{"log":"2019-07-15 02:19:23.183 [INFO][207] health.go 150: Overall health summary=\u0026health.HealthReport{Live:true, Ready:true}\n","stream":"stdout","time":"2019-07-15T02:19:23.183915499Z"}
{"log":"2019-07-15 02:19:27.744 [INFO][207] health.go 150: Overall health summary=\u0026health.HealthReport{Live:true, Ready:true}\n","stream":"stdout","time":"2019-07-15T02:19:27.744749768Z"}
{"log":"2019-07-15 02:19:29.428 [INFO][207] int_dataplane.go 690: Applying dataplane updates\n","stream":"stdout","time":"2019-07-15T02:19:29.428711902Z"}
{"log":"2019-07-15 02:19:29.428 [INFO][207] table.go 717: Invalidating dataplane cache ipVersion=0x4 reason=\"refresh timer\" table=\"raw\"\n","stream":"stdout","time":"2019-07-15T02:19:29.428734129Z"}
{"log":"2019-07-15 02:19:29.428 [INFO][207] table.go 438: Loading current iptables state and checking it is correct. ipVersion=0x4 table=\"raw\"\n","stream":"stdout","time":"2019-07-15T02:19:29.428808237Z"}
{"log":"2019-07-15 02:19:29.430 [INFO][207] route_table.go 446: Syncing routes: removing old route. dest=192.168.211.75/32 ifaceName=\"caliec83ef92d7e\" ipVersion=0x4\n","stream":"stdout","time":"2019-07-15T02:19:29.430418851Z"}
{"log":"2019-07-15 02:19:29.430 [INFO][207] int_dataplane.go 704: Finished applying updates to dataplane. msecToApply=1.745496\n","stream":"stdout","time":"2019-07-15T02:19:29.430434507Z"}
{"log":"2019-07-15 02:19:29.430 [INFO][207] conntrack.go 78: Removing conntrack flows ip=192.168.211.75\n","stream":"stdout","time":"2019-07-15T02:19:29.430507295Z"}
{"log":"2019-07-15 02:19:32.966 [INFO][207] int_dataplane.go 690: Applying dataplane updates\n","stream":"stdout","time":"2019-07-15T02:19:32.966982201Z"}
{"log":"2019-07-15 02:19:32.966 [INFO][207] ipsets.go 222: Asked to resync with the dataplane on next update. family=\"inet\"\n","stream":"stdout","time":"2019-07-15T02:19:32.967003077Z"}
{"log":"2019-07-15 02:19:32.966 [INFO][207] ipsets.go 253: Resyncing ipsets with dataplane. family=\"inet\"\n","stream":"stdout","time":"2019-07-15T02:19:32.967051298Z"}
{"log":"2019-07-15 02:19:32.970 [INFO][207] ipsets.go 295: Finished resync family=\"inet\" numInconsistenciesFound=0 resyncDuration=3.410025ms\n","stream":"stdout","time":"2019-07-15T02:19:32.970462802Z"}
{"log":"2019-07-15 02:19:32.970 [INFO][207] int_dataplane.go 704: Finished applying updates to dataplane. msecToApply=3.5811800000000003\n","stream":"stdout","time":"2019-07-15T02:19:32.970495108Z"}
{"log":"2019-07-15 02:19:33.183 [INFO][207] health.go 150: Overall health summary=\u0026health.HealthReport{Live:true, Ready:true}\n","stream":"stdout","time":"2019-07-15T02:19:33.183884038Z"}
{"log":"2019-07-15 02:19:35.335 [INFO][207] int_dataplane.go 690: Applying dataplane updates\n","stream":"stdout","time":"2019-07-15T02:19:35.336058773Z"}
{"log":"2019-07-15 02:19:35.336 [INFO][207] table.go 717: Invalidating dataplane cache ipVersion=0x4 reason=\"refresh timer\" table=\"nat\"\n","stream":"stdout","time":"2019-07-15T02:19:35.336182711Z"}
{"log":"2019-07-15 02:19:35.336 [INFO][207] table.go 438: Loading current iptables state and checking it is correct. ipVersion=0x4 table=\"nat\"\n","stream":"stdout","time":"2019-07-15T02:19:35.336195203Z"}
{"log":"2019-07-15 02:19:35.337 [INFO][207] int_dataplane.go 704: Finished applying updates to dataplane. msecToApply=1.550275\n","stream":"stdout","time":"2019-07-15T02:19:35.337604217Z"}
{"log":"2019-07-15 02:19:37.744 [INFO][207] health.go 150: Overall health summary=\u0026health.HealthReport{Live:true, Ready:true}\n","stream":"stdout","time":"2019-07-15T02:19:37.744784291Z"}
{"log":"2019-07-15 02:19:38.452 [INFO][207] int_dataplane.go 690: Applying dataplane updates\n","stream":"stdout","time":"2019-07-15T02:19:38.452759554Z"}
{"log":"2019-07-15 02:19:38.452 [INFO][207] table.go 717: Invalidating dataplane cache ipVersion=0x4 reason=\"refresh timer\" table=\"mangle\"\n","stream":"stdout","time":"2019-07-15T02:19:38.452781281Z"}
{"log":"2019-07-15 02:19:38.452 [INFO][207] table.go 438: Loading current iptables state and checking it is correct. ipVersion=0x4 table=\"mangle\"\n","stream":"stdout","time":"2019-07-15T02:19:38.452860532Z"}
{"log":"2019-07-15 02:19:38.453 [INFO][207] int_dataplane.go 704: Finished applying updates to dataplane. msecToApply=1.247249\n","stream":"stdout","time":"2019-07-15T02:19:38.453997902Z"}
{"log":"2019-07-15 02:19:43.184 [INFO][207] health.go 150: Overall health summary=\u0026health.HealthReport{Live:true, Ready:true}\n","stream":"stdout","time":"2019-07-15T02:19:43.184618817Z"}
{"log":"2019-07-15 02:19:43.240 [INFO][207] int_dataplane.go 690: Applying dataplane updates\n","stream":"stdout","time":"2019-07-15T02:19:43.240480303Z"}
{"log":"2019-07-15 02:19:43.240 [INFO][207] ipsets.go 222: Asked to resync with the dataplane on next update. family=\"inet\"\n","stream":"stdout","time":"2019-07-15T02:19:43.240499681Z"}
{"log":"2019-07-15 02:19:43.240 [INFO][207] ipsets.go 253: Resyncing ipsets with dataplane. family=\"inet\"\n","stream":"stdout","time":"2019-07-15T02:19:43.24058579Z"}
{"log":"2019-07-15 02:19:43.243 [INFO][207] ipsets.go 295: Finished resync family=\"inet\" numInconsistenciesFound=0 resyncDuration=3.390214ms\n","stream":"stdout","time":"2019-07-15T02:19:43.243932685Z"}
{"log":"2019-07-15 02:19:43.243 [INFO][207] int_dataplane.go 704: Finished applying updates to dataplane. msecToApply=3.552481\n","stream":"stdout","time":"2019-07-15T02:19:43.243987845Z"}
{"log":"2019-07-15 02:19:47.744 [INFO][207] health.go 150: Overall health summary=\u0026health.HealthReport{Live:true, Ready:true}\n","stream":"stdout","time":"2019-07-15T02:19:47.744745107Z"}
{"log":"2019-07-15 02:19:53.183 [INFO][207] health.go 150: Overall health summary=\u0026health.HealthReport{Live:true, Ready:true}\n","stream":"stdout","time":"2019-07-15T02:19:53.183989353Z"}
{"log":"2019-07-15 02:19:54.235 [INFO][207] int_dataplane.go 690: Applying dataplane updates\n","stream":"stdout","time":"2019-07-15T02:19:54.236099101Z"}
{"log":"2019-07-15 02:19:54.236 [INFO][207] ipsets.go 222: Asked to resync with the dataplane on next update. family=\"inet\"\n","stream":"stdout","time":"2019-07-15T02:19:54.236121166Z"}
{"log":"2019-07-15 02:19:54.236 [INFO][207] ipsets.go 253: Resyncing ipsets with dataplane. family=\"inet\"\n","stream":"stdout","time":"2019-07-15T02:19:54.23620437Z"}
{"log":"2019-07-15 02:19:54.239 [INFO][207] ipsets.go 295: Finished resync family=\"inet\" numInconsistenciesFound=0 resyncDuration=3.420777ms\n","stream":"stdout","time":"2019-07-15T02:19:54.239606969Z"}
{"log":"2019-07-15 02:19:54.239 [INFO][207] int_dataplane.go 704: Finished applying updates to dataplane. msecToApply=3.578866\n","stream":"stdout","time":"2019-07-15T02:19:54.239640501Z"}
{"log":"2019-07-15 02:19:57.744 [INFO][207] health.go 150: Overall health summary=\u0026health.HealthReport{Live:true, Ready:true}\n","stream":"stdout","time":"2019-07-15T02:19:57.744789682Z"}

```

I check the route on this node.

![image](https://user-images.githubusercontent.com/29671725/61193201-75c75080-a6ec-11e9-8734-ef7443fae0f3.png)

and this happen on all host nodes almost at the same time.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

network unreachable with new pod

## Your Environment

* Calico version
  image: quay.io/coreos/etcd:v3.1.10
 image: quay.io/calico/node:v3.0.4
 image: quay.io/calico/cni:v2.0.3
 image: quay.io/calico/kube-controllers:v2.0.2
* Orchestrator version (e.g. kubernetes, mesos, rkt):
kubernetes
* Operating System and version:

* Link to your project (optional):

**Comment by tingweiwu** [comment]
seems I have found out the reason.
the calico-etcd pod have been recreated 3 days ago. And I have check the nodes.
find the node that older calico-etcd pod  running reboot 3 days ago.
so the calico-etcd recreated.
![image](https://user-images.githubusercontent.com/29671725/61200934-8fc95900-a715-11e9-9808-98a37ced54e7.png)



I have 3 Kubernetes masters and I modify the calico-etcd manifest from DaemonSet to Deployment. 
becaunse this issue #1902 

so is there have calico HA solution?? not just only calico-etcd but also calico-kube-controllers?


here is my yaml
```
# Calico Version v3.0.4
# https://docs.projectcalico.org/v3.0/releases#v3.0.4
# This manifest includes the following component versions:
#   calico/node:v3.0.4
#   calico/cni:v2.0.3
#   calico/kube-controllers:v2.0.2

# This ConfigMap is used to configure a self-hosted Calico installation.
kind: ConfigMap
apiVersion: v1
metadata:
  name: calico-config
  namespace: kube-system
data:
  # The location of your etcd cluster.  This uses the Service clusterIP
  # defined below.
  etcd_endpoints: "http://10.96.232.136:6666"

  # Configure the Calico backend to use.
  calico_backend: "bird"

  # The CNI network configuration to install on each node.
  cni_network_config: |-
    {
      "name": "k8s-pod-network",
      "cniVersion": "0.3.0",
      "plugins": [
        {
          "type": "calico",
          "etcd_endpoints": "__ETCD_ENDPOINTS__",
          "log_level": "info",
          "mtu": 1500,
          "ipam": {
              "type": "calico-ipam"
          },
          "policy": {
              "type": "k8s",
               "k8s_api_root": "https://__KUBERNETES_SERVICE_HOST__:__KUBERNETES_SERVICE_PORT__",
               "k8s_auth_token": "__SERVICEACCOUNT_TOKEN__"
          },
          "kubernetes": {
              "kubeconfig": "/etc/cni/net.d/__KUBECONFIG_FILENAME__"
          }
        },
        {
          "type": "portmap",
          "snat": true,
          "capabilities": {"portMappings": true}
        }
      ]
    }


---

# This manifest installs the Calico etcd on the kubeadm master.  This uses a DaemonSet
# to force it to run on the master even when the master isn't schedulable, and uses
# nodeSelector to ensure it only runs on the master.
apiVersion: extensions/v1beta1
#kind: DaemonSet
kind: Deployment
metadata:
  name: calico-etcd
  namespace: kube-system
  labels:
    k8s-app: calico-etcd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: calico-etcd
      annotations:
        # Mark this pod as a critical add-on; when enabled, the critical add-on scheduler
        # reserves resources for critical add-on pods so that they can be rescheduled after
        # a failure.  This annotation works in tandem with the toleration below.
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      tolerations:
      # This taint is set by all kubelets running `--cloud-provider=external`
      # so we should tolerate it to schedule the calico pods
      - key: node.cloudprovider.kubernetes.io/uninitialized
        value: "true"
        effect: NoSchedule
      # Allow this pod to run on the master.
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      # Allow this pod to be rescheduled while the node is in "critical add-ons only" mode.
      # This, along with the annotation above marks this pod as a critical add-on.
      - key: CriticalAddonsOnly
        operator: Exists
      # Only run this pod on the master.
      nodeSelector:
        node-role.kubernetes.io/master: ""
      hostNetwork: true
      containers:
        - name: calico-etcd
          image: quay.io/coreos/etcd:v3.1.10
          env:
            - name: CALICO_ETCD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          command:
          - /usr/local/bin/etcd
          args:
          - --name=calico
          - --data-dir=/var/etcd/calico-data
          - --advertise-client-urls=http://$CALICO_ETCD_IP:6666
          - --listen-client-urls=http://0.0.0.0:6666
          - --listen-peer-urls=http://0.0.0.0:6667
          - --auto-compaction-retention=1
          volumeMounts:
            - name: var-etcd
              mountPath: /var/etcd
      volumes:
        - name: var-etcd
          hostPath:
            path: /var/etcd

---

# This manifest installs the Service which gets traffic to the Calico
# etcd.
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: calico-etcd
  name: calico-etcd
  namespace: kube-system
spec:
  # Select the calico-etcd pod running on the master.
  selector:
    k8s-app: calico-etcd
  # This ClusterIP needs to be known in advance, since we cannot rely
  # on DNS to get access to etcd.
  clusterIP: 10.96.232.136
  ports:
    - port: 6666

---

# This manifest installs the calico/node container, as well
# as the Calico CNI plugins and network config on
# each master and worker node in a Kubernetes cluster.
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: calico-node
  namespace: kube-system
  labels:
    k8s-app: calico-node
spec:
  selector:
    matchLabels:
      k8s-app: calico-node
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        k8s-app: calico-node
      annotations:
        # Mark this pod as a critical add-on; when enabled, the critical add-on scheduler
        # reserves resources for critical add-on pods so that they can be rescheduled after
        # a failure.  This annotation works in tandem with the toleration below.
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      hostNetwork: true
      tolerations:
      # This taint is set by all kubelets running `--cloud-provider=external`
      # so we should tolerate it to schedule the calico pods
      - key: node.cloudprovider.kubernetes.io/uninitialized
        value: "true"
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      # Allow this pod to be rescheduled while the node is in "critical add-ons only" mode.
      # This, along with the annotation above marks this pod as a critical add-on.
      - key: CriticalAddonsOnly
        operator: Exists
      serviceAccountName: calico-cni-plugin
      # Minimize downtime during a rolling upgrade or deletion; tell Kubernetes to do a "force
      # deletion": https://kubernetes.io/docs/concepts/workloads/pods/pod/#termination-of-pods.
      terminationGracePeriodSeconds: 0
      containers:
        # Runs calico/node container on each Kubernetes node.  This
        # container programs network policy and routes on each
        # host.
        - name: calico-node
          image: quay.io/calico/node:v3.0.4
          env:
            # The location of the Calico etcd cluster.
            - name: ETCD_ENDPOINTS
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_endpoints
            # Enable BGP.  Disable to enforce policy only.
            - name: CALICO_NETWORKING_BACKEND
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: calico_backend
            # Cluster type to identify the deployment type
            - name: CLUSTER_TYPE
              value: "kubeadm,bgp"
            # Disable file logging so `kubectl logs` works.
            - name: CALICO_DISABLE_FILE_LOGGING
              value: "true"
            # Set noderef for node controller.
            - name: CALICO_K8S_NODE_REF
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            # Set Felix endpoint to host default action to ACCEPT.
            - name: FELIX_DEFAULTENDPOINTTOHOSTACTION
              value: "ACCEPT"
            # The default IPv4 pool to create on startup if none exists. Pod IPs will be
            # chosen from this range. Changing this value after installation will have
            # no effect. This should fall within `--cluster-cidr`.
            - name: CALICO_IPV4POOL_CIDR
              value: "K8S_HA_CIDR"
            - name: CALICO_IPV4POOL_IPIP
              value: "Always"
            # Disable IPv6 on Kubernetes.
            - name: FELIX_IPV6SUPPORT
              value: "false"
            # Set MTU for tunnel device used if ipip is enabled
            - name: FELIX_IPINIPMTU
              value: "1440"
            # Set Felix logging to "info"
            - name: FELIX_LOGSEVERITYSCREEN
              value: "info"
            # Auto-detect the BGP IP address.
            - name: IP
              value: "autodetect"
            - name: IP_AUTODETECTION_METHOD
              value: "can-reach=K8SHA_CALICO_REACHABLE_IP"
            - name: FELIX_HEALTHENABLED
              value: "true"
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: 250m
          livenessProbe:
            httpGet:
              path: /liveness
              port: 9099
            periodSeconds: 10
            initialDelaySeconds: 10
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /readiness
              port: 9099
            periodSeconds: 10
          volumeMounts:
            - mountPath: /lib/modules
              name: lib-modules
              readOnly: true
            - mountPath: /var/run/calico
              name: var-run-calico
              readOnly: false
        # This container installs the Calico CNI binaries
        # and CNI network config file on each node.
        - name: install-cni
          image: quay.io/calico/cni:v2.0.3
          command: ["/install-cni.sh"]
          env:
            # Name of the CNI config file to create.
            - name: CNI_CONF_NAME
              value: "10-calico.conflist"
            # The location of the Calico etcd cluster.
            - name: ETCD_ENDPOINTS
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_endpoints
            # The CNI network config to install on each node.
            - name: CNI_NETWORK_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: cni_network_config
          volumeMounts:
            - mountPath: /host/opt/cni/bin
              name: cni-bin-dir
            - mountPath: /host/etc/cni/net.d
              name: cni-net-dir
      volumes:
        # Used by calico/node.
        - name: lib-modules
          hostPath:
            path: /lib/modules
        - name: var-run-calico
          hostPath:
            path: /var/run/calico
        # Used to install CNI.
        - name: cni-bin-dir
          hostPath:
            path: /opt/cni/bin
        - name: cni-net-dir
          hostPath:
            path: /etc/cni/net.d

---

# This manifest deploys the Calico Kubernetes controllers.
# See https://github.com/projectcalico/kube-controllers
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: calico-kube-controllers
  namespace: kube-system
  labels:
    k8s-app: calico-kube-controllers
spec:
  # The controllers can only have a single active instance.
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      name: calico-kube-controllers
      namespace: kube-system
      labels:
        k8s-app: calico-kube-controllers
      annotations:
        # Mark this pod as a critical add-on; when enabled, the critical add-on scheduler
        # reserves resources for critical add-on pods so that they can be rescheduled after
        # a failure.  This annotation works in tandem with the toleration below.
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      # The controllers must run in the host network namespace so that
      # it isn't governed by policy that would prevent it from working.
      hostNetwork: true
      tolerations:
      # This taint is set by all kubelets running `--cloud-provider=external`
      # so we should tolerate it to schedule the calico pods
      - key: node.cloudprovider.kubernetes.io/uninitialized
        value: "true"
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      # Allow this pod to be rescheduled while the node is in "critical add-ons only" mode.
      # This, along with the annotation above marks this pod as a critical add-on.
      - key: CriticalAddonsOnly
        operator: Exists
      # Only run this pod on the master.
      nodeSelector:
         node-role.kubernetes.io/master: ""
      serviceAccountName: calico-kube-controllers
      containers:
        - name: calico-kube-controllers
          image: quay.io/calico/kube-controllers:v2.0.2
          env:
            # The location of the Calico etcd cluster.
            - name: ETCD_ENDPOINTS
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_endpoints
            # Choose which controllers to run.
            - name: ENABLED_CONTROLLERS
              value: policy,profile,workloadendpoint,node

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: calico-cni-plugin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: calico-cni-plugin
subjects:
- kind: ServiceAccount
  name: calico-cni-plugin
  namespace: kube-system

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: calico-cni-plugin
rules:
  - apiGroups: [""]
    resources:
      - pods
      - nodes
    verbs:
      - get

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: calico-cni-plugin
  namespace: kube-system

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: calico-kube-controllers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: calico-kube-controllers
subjects:
- kind: ServiceAccount
  name: calico-kube-controllers
  namespace: kube-system

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: calico-kube-controllers
rules:
  - apiGroups:
    - ""
    - extensions
    resources:
      - pods
      - namespaces
      - networkpolicies
      - nodes
    verbs:
      - watch
      - list

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: calico-kube-controllers
  namespace: kube-system

```


```
