### ISSUE TITLE
Calico does not enforce deny policy when NetworkPolicy is updated from 'allow' to 'deny'.

### ISSUE THREAD

**Issue by eyeezzi** [projectcalico/calico#2759]
I have a classic 3-tier app with 3 sets of pods: **frontend-app**, **backend-app**, and **database-app**. By default, each app can access all the other apps as per K8s network model.

The issue only shows up when you perform these actions in this specific order. 

1. "Create" a NetworkPolicy that allows _backend-app_ to access _database-app_. 
    - Observed: _frontend-app_ DOES NOT HAVE access to database-app (expected behaviour).
2. "Update" the NetworkPolicy to allow _frontend-app_ to access _database-app_. 
    - Observed: _frontend-app_ HAS access to _database-app_ (expected behaviour).
3. "Update" the NetworkPolicy to remove access for _frontend-app_. 
    - Observed: _frontend-app_ STILL HAS access to _database-app_. (**unexpected behaviour**).

## Steps to Reproduce

1. Create a new policy to allow _backend-app_ access _database-app_.
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: db-policy
  namespace: default
spec:
  podSelector: 
    matchLabels:
      app: database-app
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: backend-app
```
2. Update policy to allow _frontend-app_ access _database-app_.
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: db-policy
  namespace: default
spec:
  podSelector: 
    matchLabels:
      app: database-app
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: backend-app
     - podSelector:              # addition
         matchLabels:
           app: frontend-app
```
3. Update policy to remove access for _frontend-app_.
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: db-policy
  namespace: default
spec:
  podSelector: 
    matchLabels:
      app: database-app
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: backend-app
     # deletion
```
frontend-app can still access database-app, even after waiting for 5 mins, 1 hr, 24 hrs.

## Context

The ability to add and remove subjects to/from a NetworkPolicy is a fundamental requirement of any NetworkPolicy plugin. So it would be really nice to understand why this is failing.

## Your Environment

* Calico version 3.2.7
* Orchestrator version - kubernetes 1.13.7-gke.8
* Operating System and version: Container-Optimized OS (cos)
* Running Calico on a brown new Google Kubernetes Engine cluster. Nothing else but my demo apps and Calico components. I am using the default Calico installation that GKE creates when you enable `Network Policy` on the cluster.

> If you cannot reproduce this issue. I don't mind giving 'read' access to my test cluster. Thanks.
