### ISSUE TITLE
Similar Egress rules should work the same

### ISSUE THREAD

**Issue by cscetbon** [projectcalico/calico#2789]
I can add an Egress rule using `ipBlock` but a rule using `podSelector` + an empty `namespaceSelector` should do exactly the same and does not.

Here is the rule that works :
```
# rule1
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: apiserver-access
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: apiserver-client
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 172.17.0.4/32
    ports:
    - port: 6443
      protocol: TCP
```

And here is the one that does not work :
```
# rule2
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: apiserver-access
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: apiserver-client
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          component: kube-apiserver
    - namespaceSelector: {}
    ports:
    - port: 6443
      protocol: TCP
```

Other rule similar to previous rule but that works :
```
# rule3
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-apiserver-access
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: apiserver-client
  policyTypes:
  - Egress
  egress:
  - ports:
    - port: 6443
      protocol: TCP
  - to:
    - podSelector:
        matchLabels:
          component: kube-apiserver
    - namespaceSelector: {}
``` 

both second and third rules are supposed to be identical but don't.

## Expected Behavior

All rules should allow pods in namespace `default` with label `apiserver-client` to access 172.17.0.4 on port 6443

## Current Behavior

when `to` and `ports` are provided in the same list, it should work the same as if they were provided as 2 different items

## Steps to Reproduce (for bugs)

1. In namespace default, create pod with 
```
kubectl run --rm --restart=Never --image=alpine -n default -i -t -l app=apiserver-client test -- ash
```
2. Apply rule2
3. try `nc -w 1 172.17.0.4 6443 && echo ok || echo nok` in interactive shell
4. see that it echoes `nok`

## Environment

* Calico version 3.8
* Orchestrator version (e.g. kubernetes, mesos, rkt): k8s
* Operating System and version: MacOs 10.14.6
* Link to your project (optional): https://github.com/Orange-OpenSource/cassandra-k8s-operator

**Comment by caseydavenport** [comment]
> but a rule using podSelector + an empty namespaceSelector should do exactly the same and does not.

Why do you say that this should be the same as an IP block rule? 

It is curious that it seems that switching the order of the two rules in your second and third examples seems to change the behavior - that definitely shouldn't be the case. What do you mean by "works"?

```
 - podSelector:
        matchLabels:
          component: kube-apiserver
```

FYI usually the kube-apiserver runs with host networking which means it won't be selected by this rule. Can you confirm whether or not your kube-apiserver is running with host networking?

**Comment by cscetbon** [comment]
Take a better look @caseydavenport. The order is not the issue. It's where `ports` is located. In the working case it's an item like `to`. In the second case, it's an item of the list `to`.

**Comment by caseydavenport** [comment]
Right, thanks for point that out explicitly to me. 

In this case, I think it is most likely working as expected. In the case where it is _not_ working, the two clauses are part of the same list element and thus are AND'ed together.

In the case where they are not part of the same list element, they are OR'd together. This is the expected behavior.

Since the API server is run as host networking it isn't selectable via a pod selector. Thus, the AND'ed scenario isn't matching on the API server pod, whereas the OR'ed policy is because the label selector is essentially ignored and all traffic sent to port 6443 is allowed independent of what the destination is.

**Comment by cscetbon** [comment]
> In the case where they are not part of the same list element, they are OR'd together. This is the expected behavior.

I don't agree, the [documentation](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#networkpolicyegressrule-v1-networking-k8s-io) is clear about that. `ports` list and `to` list are AND'ed, but items in those lists are OR'ed. 

_NetworkPolicyEgressRule describes a particular set of traffic that is allowed out of pods matched by a NetworkPolicySpec's podSelector. The traffic must match both ports and to. This type is beta-level in 1.8_

That's why I'm saying that whether they are in the same list or not, the behavior should be the same. Maybe `ports` shouldn't even be accepted under `to`, cause I can't see it in the [defined structure](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#networkpolicypeer-v1-networking-k8s-io).

**Comment by caseydavenport** [comment]
```yaml
  egress:
  - ports:
    - port: 6443
      protocol: TCP

  - to:
    - podSelector:
        matchLabels:
          component: kube-apiserver
    - namespaceSelector: {}
```

This egress section has two distinct rules. Those two rules are OR'd together (I added an empty line between the two rules).

> NetworkPolicyEgressRule describes a particular set of traffic that is allowed out of pods matched by a NetworkPolicySpec's podSelector. The traffic must match both ports and to. This type is beta-level in 1.8

This is true within the context of a single egress rule, but they are not AND'ed across multiple rules. Egress rules are combined using a logical OR - i.e., the traffic is allowed if it matches any one of the specified NetworkPolicyEgressRules. In the example you've provided, the `ports` and `to` are in separate NetworkPolicyEgressRule structures. 

Another way to look at the example above is like this - with the omitted bits filled in.

```yaml
  egress:
  - ports:
    - port: 6443
      protocol: TCP
    to: nil

  - to:
    - podSelector:
        matchLabels:
          component: kube-apiserver
    - namespaceSelector: {}
    ports: nil
```
