### ISSUE TITLE
Using Calico GlobalNetworkpolicy to deny all the ingress traffic but the node can access to it's pods

### ISSUE THREAD

**Issue by zanghao2** [projectcalico/calico#2797]
## Expected Behavior
When apply a GlobalNetwrokpolicy to deny all ingress, traffic that from anywhere can not arrive pods. 

## Current Behavior

I create k8s cluster (v1.13) and then use calico(v3.8) as the CNI. My cluster is 1 master and 2 node (node1, node2).
First, I deploy webserver deployment on node1 and node2
Second, I use GlobalNetworkpolicy to deny all the ingress traffic to webserver
```
apiVersion: projectcalico.org/v3
kind: GlobalNetworkpolicy
metadata:
  name: drop
spec:
  selector: run == 'webserver'
  ingress:
  - action: deny
```
Third,Validation networkpolicy. One node can not access the webserver on other node, but it can access it own webserver. 

I think all the websever can not be accessed by any node.
## Steps to Reproduce (for bugs)

Is there a mistake in my approach, or is Calico designed like this?

## Your Environment

* Calico version 3.8
* Orchestrator version (e.g. kubernetes, mesos, rkt):1.13
* Operating System and version: centos
* Link to your project (optional):
