### ISSUE TITLE
allow the node out of cluster to visit pod by pod's IP

### ISSUE THREAD

**Issue by llhhbc** [projectcalico/calico#2798]
I have node A that out of cluster,  node B,C in cluster. 
node A ip: 10.10.40.25
node B ip: 10.10.40.95
node C ip: 10.10.40.99

ipvs vip: 10.10.40.182   this vip is on node B.
set the ipvs config:  10.10.40.182 ----> 10.244.199.191 (this pod is on node C)

## Expected Behavior
I can visit 10.10.40.182 9111  on node A

## Current Behavior
I can't  visit 10.10.40.182 9111  on node A, but I can't .
If the pod(10.244.199.191) is on node B, I can visit ok.

## Possible Solution
I have add GlobalNetworkPolicy, but is not work.

this is my add for policy

```yaml
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: allow-app-net
spec:
  ingress:
  - action: Allow
    destination:
      selector: all()
    protocol: TCP
    source:
      selector: all()
      nets:
      - 10.10.0.0/16
  - action: Allow
    destination:
      selector: all()
    protocol: ICMP
    source:
      selector: all()
      nets:
      - 10.10.0.0/16
  selector: all()
  order: 10
  types:
  - Ingress
---
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: def-allow-app-net
  namespace: default
spec:
  ingress:
  - action: Allow
    destination:
      selector: all()
    protocol: TCP
    source:
      selector: all()
      nets:
      - 10.10.0.0/16
  - action: Allow
    destination:
      selector: all()
    protocol: ICMP
    source:
      selector: all()
      nets:
      - 10.10.0.0/16
  selector: all()
  order: 20
  types:
  - Ingress
---
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: ks-allow-app-net
  namespace: kube-system
spec:
  ingress:
  - action: Allow
    destination:
      selector: all()
    protocol: TCP
    source:
      selector: all()
      nets:
      - 10.10.0.0/16
  - action: Allow
    destination:
      selector: all()
    protocol: ICMP
    source:
      selector: all()
      nets:
      - 10.10.0.0/16
  selector: all()
  order: 20
  types:
  - Ingress
```

## Your Environment
* Calico version: 3.8.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): k8s 1.13.4
* Operating System and version: centos 7
* Link to your project (optional):
