### ISSUE TITLE
hostendpoint use GlobalNetworkPolicy

### ISSUE THREAD

**Issue by zanghao2** [projectcalico/calico#2819]
## Expected Behavior
Two hostendpoint can use globalnetworkpolicy to controll the traffic from one hostendpoint to another.
## Current Behavior
I create k8s cluster (v1.13) and then use calico(v3.8) as the CNI. My cluster is 1 master and 1 node (node).
First, I create two hostendpoint on master and node.
```
apiVersion: projectcalico.org/v3
kind: HostEndpoint
metadata:
  name: master-hep
  labels:
    type: master-ss
spec:
  interfaceName: eth0
  node: master
  expectedIPs:
  - 192.168.0.1
```
```
apiVersion: projectcalico.org/v3
kind: HostEndpoint
metadata:
  name: node-hep
  labels:
    type: node-ss
spec:
  interfaceName: eth0
  node: node
  expectedIPs:
  - 192.168.0.1
```
Second, I create GlobalNetworkPolicy to controll the traffic form node to master.
```
apiVersion: projectcalico.org/v3
kind: GlobalNetworkpolicy
metadata:
  name: allow-traffic
spec:
  selector: type == 'master-ss'
  ingress:
  - action: Allow
     protocol: TCP
     source:
        selector: type == 'node-ss'
     destination:
        ports:
        - 6443
    egress:
    - action: Allow
```
Third, I curl the master ip:6443 on node, but the traffic refused.
## Possible Solution
1.There may be something wrong on my globalnetworkpolicy.
2.Globalnetworkpolicy do not support two hostendpoint.
## Your Environment

* Calico version 3.8
* Orchestrator version (e.g. kubernetes, mesos, rkt):1.13
* Operating System and version: centos
* Link to your project (optional):
