### ISSUE TITLE
Pod cannot communicate with network policy

### ISSUE THREAD

**Issue by Woap** [projectcalico/calico#2896]
I have trouble with network policies using Calico which is installed with Kubespray. When I set a network policy to allow only traffic from specific namespace, some of my pod inside this namespace cannot communicate with others pod in the same namespace.

I found that they can communicate only if they're scheduled on the same node. Two pod in the same namespace but in two separate node cannot communicate.

Without network policy, everything work as expected

## Expected Behavior

A pod inside "advanced-policy-demo" namespace should communicate with all others pod in the same namespace.

## Current Behavior

```
NAME                     READY   STATUS    RESTARTS   AGE   IP              NODE                    NOMINATED NODE   READINESS GATES
access                   1/1     Running   0          7s    10.233.72.84    *-node3.*   <none>           <none>
nginx-7bb7cd8db5-5574p   1/1     Running   0          22m   10.233.86.88    *-node2.*   <none>           <none>
nginx-7bb7cd8db5-b2hh2   1/1     Running   0          22m   10.233.113.55   *-node1.*   <none>           <none>
nginx-7bb7cd8db5-thnhs   1/1     Running   0          22m   10.233.72.71    *-node3.*   <none>           <none>
```

The pod "access" can only wget the pod "nginx-7bb7cd8db5-thnhs" which is on node3.
When I try the two others, I got a timeout.

## Steps to Reproduce (for bugs)

Here's a calico example : 
https://docs.projectcalico.org/v3.9/security/tutorials/kubernetes-policy-advanced

```
kubectl create ns advanced-policy-demo
kubectl run --namespace=advanced-policy-demo nginx --replicas=3 --image=nginx
kubectl expose --namespace=advanced-policy-demo deployment nginx --port=80
```

```
kubectl create -f - <<EOF
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: advanced-policy-demo
spec:
  podSelector:
    matchLabels: {}
  policyTypes:
  - Ingress
EOF
```

```
kubectl create -f - <<EOF
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: access-nginx
  namespace: advanced-policy-demo
spec:
  podSelector:
    matchLabels:
      run: nginx
  ingress:
    - from:
      - podSelector:
          matchLabels: {}
EOF
```

`kubectl run --namespace=advanced-policy-demo access --rm -ti --image busybox /bin/sh`

## Your Environment
* Calico version v3.7.3
* Orchestrator version (e.g. kubernetes, mesos, rkt): K8S v.1.15.0
* Operating System and version: Ubuntu server 18.04
* Topoglogy : 1 master and 3 nodes
