### ISSUE TITLE
Calico Network Policy only works when both application are on same K8s node

### ISSUE THREAD

**Issue by venomwaqar** [projectcalico/calico#2898]
I am having a very strange issue and I couldn't find out the issue that is causing this weird scenario. I am using Calico Network Policy to allow the DB to accept the connection from one specific namespace only.

## Calico Network Policy

```
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: network-policy-171-946
  namespace: ns-restriction-demo-2
spec:
  selector: app == 'db-demo-2'
  ingress:  
  - action: Allow
    protocol: TCP
    source:
      selector: app == 'node-demo-1'
      namespaceSelector: name == 'ns-restriction-demo-1'

  - action: Allow
    protocol: TCP
    source:
      namespaceSelector: name == 'ns-restriction-demo-2'
```

## Expected Behavior
When I apply the network policy, regardless of the kubernetes worker node, the policy should work.

## Current Behavior
When I apply the network policy, it work only if the DB and the application that is connecting to it, both are on same kubernetes worker node.

## Steps to Reproduce (for bugs)
1. Deploy a DB app in one k8s node
2. Deploy another app that is going to connect to DB in another k8s node

## Your Environment
Client Version:    v3.5.8
Git commit:        107e128
Cluster Version:   v3.9.1
Cluster Type:      k8s,bgp,kdd,typha
Kubernetes: 1.13.6
Istio: 1.1.10

Please help me understand or debug the issue.
Thanks
