### ISSUE TITLE
Kubectl apply global network policy fails

### ISSUE THREAD

**Issue by dontreboot** [projectcalico/calico#2918]
https://docs.projectcalico.org/v3.3/reference/calicoctl/resources/globalnetworkpolicy#ports provides examples for setting up global network policy; however, the instruction is not clearly out that the example yaml should only be applied via calicoctl and it won't work with kubectl.

## Expected Behavior
The official calico documentation should have the right instruction for applying global network policy in addition to examples for calicoctl if the instructions are supposed to be different.

## Current Behavior
I have this yaml file:
```
kind: GlobalNetworkPolicy
apiVersion: projectcalico.org/v3
metadata:
  name: egress-policy
spec:
  types:
  - Egress
  egress:
  - action: Allow
    protocol: TCP
    destination:
      ports: [80, 443]
  - action: Allow
    protocol: UDP
    destination:
      ports: [53, 123]
  - action: Allow
    protocol: ICMP
```

When I ran `kubectl apply`, I got this error:
```
error: unable to recognize "global-egress-policy.yaml": no matches for kind "GlobalNetworkPolicy" in version "projectcalico.org/v3"
```
## Possible Solution

When I updated apiverison to ```apiVersion: crd.projectcalico.org/v1```, `kubectl apply` works fine.

## Steps to Reproduce (for bugs)
- Deploy https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/release-1.5/config/v1.5/calico.yaml to an EKS cluster
- kubectl apply the following file
```
kind: GlobalNetworkPolicy
apiVersion: projectcalico.org/v3
metadata:
  name: egress-policy
spec:
  types:
  - Egress
  egress:
  - action: Allow
    protocol: TCP
    destination:
      ports: [80, 443]
  - action: Allow
    protocol: UDP
    destination:
      ports: [53, 123]
  - action: Allow
    protocol: ICMP
```

## Your Environment

* calico 3.3
* k8s 1.14.3

**Comment by caseydavenport** [comment]
@dontreboot GlobalNetworkPolicy objects need to be created using `calicoctl`

**Comment by dontreboot** [comment]
> @dontreboot GlobalNetworkPolicy objects need to be created using `calicoctl`

hmm... I am able to apply the following manifest with kubectl without issues.
```
kind: GlobalNetworkPolicy
apiVersion: crd.projectcalico.org/v1
metadata:
  name: egress-policy
spec:
  types:
  - Egress
  egress:
  - action: Allow
    protocol: TCP
    destination:
      # allow intra-vpc communication
      nets:
        - "10.50.0.0/16"
```
