### ISSUE TITLE
pod get IP assigned from wrong ippool

### ISSUE THREAD

**Issue by huegelc** [projectcalico/calico#2950]
We use calico with metallb on a 3 node cluster. metallb is configured to peer with eBGP to calico:

```
apiVersion: projectcalico.org/v3
kind: BGPConfiguration
metadata:
  creationTimestamp: null
  name: default
spec:
  asNumber: 63400
  logSeverityScreen: Info
  nodeToNodeMeshEnabled: true
```
```
apiVersion: projectcalico.org/v3
kind: BGPPeer
metadata:
  name: metallb
spec:
  peerIP: 127.0.0.1
  asNumber: 63401
```
```
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    peers:
    - peer-address: 127.0.0.1
      peer-asn: 63400
      my-asn: 63401
    address-pools:
    - name: prod-pool
      protocol: bgp
      avoid-buggy-ips: true
      addresses:
      - 10.2.136.128/26
```
```
calicoctl  node status
Calico process is running.

IPv4 BGP status
+--------------+-------------------+-------+----------+-------------+
| PEER ADDRESS |     PEER TYPE     | STATE |  SINCE   |    INFO     |
+--------------+-------------------+-------+----------+-------------+
| 10.2.136.4   | node-to-node mesh | up    | 07:24:45 | Established |
| 10.2.136.5   | node-to-node mesh | up    | 19:33:12 | Established |
| 127.0.0.1    | global            | up    | 19:34:59 | Established |
+--------------+-------------------+-------+----------+-------------+

IPv6 BGP status
No IPv6 peers found.
```

```
apiVersion: projectcalico.org/v3
kind: IPPoolList
items:
- apiVersion: projectcalico.org/v3
  kind: IPPool
  metadata:
    name: metallb-prod-pool
  spec:
    cidr: 10.2.136.128/26
    ipipMode: Always
    natOutgoing: false
```
and a separate ippool for cert-manager

```
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
   name: cert-manager
spec:
   cidr: 10.2.136.16/28
   blockSize: 28
   ipipMode: Always
   natOutgoing: false
   nodeSelector: all()  
```
```
calicoctl get ippool
NAME                  CIDR              SELECTOR   
cert-manager         10.2.136.16/28    all()      
default-ipv4-ippool   10.2.137.0/24     all()      
metallb-prod-pool     10.2.136.128/26   all()      
```

The cert-manager deployment has the correct IPs assigned to the pods:

```
 kubectl get po -n cert-manager -o wide
NAME                                       READY   STATUS    RESTARTS   AGE   IP            NODE             NOMINATED NODE   READINESS GATES
cert-manager-55fff7f85f-2xmqw              1/1     Running   0          11h   **10.2.136.17**   xxxxxxnr02   <none>           <none>
cert-manager-cainjector-54c4796c5d-rphmj   1/1     Running   0          11h   **10.2.136.16**   xxxxxxnr02   <none>           <none>
cert-manager-webhook-77ccf5c8b4-wg7w6      1/1     Running   0          11h   **10.2.136.18**   xxxxxxnr03   <none>           <none>

```
Now when I do a test deployment in the default namespace some pods get the IP from the cert-amanger ippool and only when the pods are scheduled on a specific host **xxxxxxnr02**

 `kubectl run pingtest --image=busybox --replicas=6 -- sleep infinity`

```
kubectl get pod -l run=pingtest -o wide
NAME                      READY   STATUS    RESTARTS   AGE   IP             NODE             NOMINATED NODE   READINESS GATES
pingtest-b4b6f8cf-5749x   1/1     Running   0          18m   10.2.137.76    xxxxxxnr03   <none>           <none>
pingtest-b4b6f8cf-7tvn9   1/1     Running   0          18m   10.2.137.75    xxxxxxnr03   <none>           <none>
pingtest-b4b6f8cf-bmmz7   1/1     Running   0          18m   10.2.136.28    xxxxxxnr02   <none>           <none>
pingtest-b4b6f8cf-gqt2g   1/1     Running   0          18m   10.2.137.207   xxxxxxnr01   <none>           <none>
pingtest-b4b6f8cf-rq42f   1/1     Running   0          18m   10.2.137.208   xxxxxxnr01   <none>           <none>
pingtest-b4b6f8cf-x5d2c   1/1     Running   0          18m   10.2.136.29    xxxxxxnr02   <none>           <none>
```

## Expected Behavior

correct IP address assignment as per ippool configuration
## Current Behavior

As described above.
## Steps to Reproduce (for bugs)

as described above

## Your Environment

* Calico version 3.10
* Orchestrator version (e.g. kubernetes, mesos, rkt):rkt
* Operating System and version: RHEL 7.7
* Link to your project (optional):
