### ISSUE TITLE
In k8s for ipv6 natOutgoing is false by default

### ISSUE THREAD

**Issue by uablrek** [projectcalico/calico#2954]
When dploying Calico on k8s in ipv6 or dual-stack mode the `default-ipv6-ippool` does not get "natOutgoing: true".

## Expected Behavior

The `default-ipv6-ippool` should be setup in the same way as the `default-ipv4-ippool`.

## Current Behavior

"natOutgoing: true" is not set in `default-ipv6-ippool`

## Possible Solution

Since ipv6 should not need NAT the behaivor should be configurable with some "FELIX_*" parameter. But most users will probably expect the same behavior as for ipv4 by default (I did).

## Steps to Reproduce (for bugs)

1. Install Calico on a ipv6-only or dual-stack K8s cluster
2. Check with `calicoctl get ippool default-ipv6-ippool -o yaml`

## Context

A work-around is to set "natOutgoing: true" after Calico has started. It works but is clumsy and may be hard for many users. Example;

```
# cat /etc/calico/default-ipv6-ippool.yaml
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: default-ipv6-ippool
spec:
  blockSize: 122
  cidr: 1100::b00:0/112
  ipipMode: Never
  nodeSelector: all()
  natOutgoing: true
  vxlanMode: Never
# calicoctl apply -f /etc/calico/default-ipv6-ippool.yaml
```

## Your Environment

* Calico version v3.10.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): K8s v1.16.2
* Operating System and version: Linux (own installation)
* Link to your project (optional):
