### ISSUE TITLE
Selector for HostEndpoints in a GlobalNetworkPolicy

### ISSUE THREAD

**Issue by harmjanblok** [projectcalico/calico#2956]
The field `spec.ingress[].source.selector` in the GlobalNetworkPolicy doesn't seem to work for labels on HostEndpoints.

## Expected Behavior
HostEndpoints can be selected using the [EntityRule](https://docs.projectcalico.org/v3.10/reference/resources/globalnetworkpolicy#entityrule) selector.

## Current Behavior
Only WorkloadEndpoints are included.

## Steps to Reproduce (for bugs)

I have configured two `HostEndpoints`:
```yaml
---
apiVersion: projectcalico.org/v3
kind: HostEndpoint
metadata:
  name: silver-ingress-north-a-1
  labels:
    role: ingress
spec:
  interfaceName: ens192
  node: silver-ingress-north-a-1
---
apiVersion: projectcalico.org/v3
kind: HostEndpoint
metadata:
  name: silver-master-south-b-1
  labels:
    role: master
spec:
  interfaceName: ens192
  node: silver-master-south-b-1
```

And following `GlobalNetworkPolicy`
```yaml
---
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: ingress-test
spec:
  selector: role=='ingress'
  order: 100
  ingress:
  - action: Allow
    protocol: ICMP
  - action: Allow
    protocol: TCP
    source:
      selector: role=='master'
    destination:
      ports: [10250]
  egress:
  - action: Allow
  types:
  - Ingress
  - Egress
---
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: master-test
spec:
  selector: role=='master'
  order: 100
  ingress:
  - action: Allow
  egress:
  - action: Allow
  types:
  - Ingress
  - Egress
```

On `silver-ingress-north-a-1` I verified the created iptable rules:

```
sudo iptables-save | grep 10250
-A cali-pi-default.ingress-test -p tcp -m comment --comment "cali:3_u7ItmuBbTMJiR4" -m set --match-set cali40s:OMq638XWj6VHdDuecG5Xf_2 src -m multiport --dports 10250 -j MARK --set-xmark 0x10000/0x10000
-A cali-pi-default.ingress-test -p tcp -m comment --comment "cali:3_u7ItmuBbTMJiR4" -m set --match-set cali40s:OMq638XWj6VHdDuecG5Xf_2 src -m multiport --dports 10250 -j MARK --set-xmark 0x10000/0x10000
-A cali-pi-default.ingress-test -p tcp -m comment --comment "cali:3_u7ItmuBbTMJiR4" -m set --match-set cali40s:OMq638XWj6VHdDuecG5Xf_2 src -m multiport --dports 10250 -j MARK --set-xmark 0x10000/0x10000
```

and the corresponding `match-set`:

```
sudo ipset -L cali40s:OMq638XWj6VHdDuecG5Xf_2
Name: cali40s:OMq638XWj6VHdDuecG5Xf_2
Type: hash:net
Revision: 6
Header: family inet hashsize 1024 maxelem 1048576
Size in memory: 376
References: 3
Number of entries: 0
Members:
```

When using the selector `all()`, only workload IPs are included in the resulting `match-set`.

## Your Environment
* Calico version 3.8.2
* Kubernetes 1.13.11
* CentOS Linux release 7.7.1908
