### ISSUE TITLE
Received: Bad peer AS: 64512 and calicoctl panics

### ISSUE THREAD

**Issue by iamaquaman** [projectcalico/calico#2961]
## Current Behavior
I  am running into issues where I am receiving a bad peer AS. 

The peer that I am receiving is the default AS of 64512. That is where I believe my errors are coming from. 

From the calico pod logs:

bird: Global_XXX_XXX_XX_50: Received: Bad peer AS: 64512
bird: Global_XXX_XXX_XX_50: State changed to stop
bird: Global_XXX_XXX_XX_50: State changed to down

Node status:

calicoctl node status
Calico process is running.

IPv4 BGP status
+---------------+-----------+-------+----------+----------------------------+
| PEER ADDRESS  | PEER TYPE | STATE |  SINCE   |            INFO            |
+---------------+-----------+-------+----------+----------------------------+
| xxx.xxx.xx.48 | global    | start | 23:54:24 | Idle Received: Bad peer AS |
| xxx.xxx.xx.50 | global    | start | 23:54:14 | Idle Received: Bad peer AS |
+---------------+-----------+-------+----------+----------------------------+

calicoctl get bgpPeers
NAME         PEERIP          NODE       ASN          
bgppeer001   xxx.xxx.xx.48   (global)   4200002024  
bgppeer002   xxx.xxx.xx.50   (global)   4200002024   

calicoctl get nodes -o wide
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12e984a]

goroutine 1 [running]:
text/template.errRecover(0xc4207e18b8)
/usr/local/go/src/text/template/exec.go:137 +0x1d4

I disabled node to node mesh and enabled global bgp peering using this documentation: https://docs.projectcalico.org/v3.4/usage/configuration/bgp#example

## Environment
* Calico version v3.4.0, build a7e09d5
* Orchestrator version Kubernetes 1.13.5
* Operating System and version: CentOs 7

**Comment by kprabhak** [comment]
@iamaquaman Could you share the bgp peer resource yaml that you are using as well (with sensitive info like IP's masked if appropriate)?
I'm curious about how you have the AS # configured within the yaml.

**Comment by tmjd** [comment]
If this is a new cluster I'd suggest updating to the latest release since v3.4 is several releases old and try this sequence again.
If that is not possible could you try the calicoctl command with the `-l debug` to see if there is any useful info returned.

**Comment by iamaquaman** [comment]
Hi @kprabhak 

I used this to disable node to node mesh.

```
cat << EOF | calicoctl create -f -
 apiVersion: projectcalico.org/v3
 kind: BGPConfiguration
 metadata:
   name: default
 spec:
   logSeverityScreen: Info
   nodeToNodeMeshEnabled: false
   asNumber: 
EOF
```

I used the following configuration to add bgp peer sources.

```
cat << EOF | calicoctl create -f -
apiVersion: projectcalico.org/v3
kind: BGPPeer
metadata:
  name: bgppeer001
spec:
  peerIP: xxx.xx.xx.48
  asNumber: 4200002024
EOF
```
```
cat << EOF | calicoctl create -f -
apiVersion: projectcalico.org/v3
kind: BGPPeer
metadata:
  name: bgppeer001
spec:
  peerIP: xxx.xx.xx.50
  asNumber: 4200002024
EOF
```

**Comment by iamaquaman** [comment]
@tmjd 

It is a brand new dev cluster. I don't mind updating this as long as the upgrade doesn't break anything or causes me to reconfigure anything too significant that might affect how calico works on the cluster.

**Comment by tmjd** [comment]
Off the top of my head I don't think there are any major changes that should break things though you'd probably want to go through the release notes to see if there are any changes specific to your setup.

Since this is a new cluster I'm curious how did you ended up using 3.4? I'm wondering if there is some documentation or something that needs to be updated to direct people to the latest release.

**Comment by iamaquaman** [comment]
Here is the output of a tcp dump from our Netops team

```
xx:cc:xx:xx:xx:38 > xx:xx:xx:xx:xx:10, ethertype IPv4 (0x0800), length 127: (tos 0xc0, ttl 64, id 38760, offset 0, flags [DF], proto TCP (6), length 113)
    xxx.xxx.xx.175.57187 > xxx.xxx.xx.48.bgp: Flags [P.], cksum 0x40b7 (correct), seq 1:62, ack 1, win 229, options [nop,nop,TS val 1466780510 ecr 3487464229], length 61: BGP
	Open Message (1), length: 61
	  Version 4, my AS 64512, Holdtime 240s, ID xxx.xxx.xx.175
	  Optional parameters, length: 32
	    Option Capabilities Advertisement (2), length: 30
	      Multiprotocol Extensions (1), length: 4
		AFI IPv4 (1), SAFI Unicast (1)
		0x0000:  0001 0001
	      Route Refresh (2), length: 0
	      Graceful Restart (64), length: 6
		Restart Flags: [none], Restart Time 120s
		  AFI IPv4 (1), SAFI Unicast (1), Forwarding state preserved: no
		0x0000:  0078 0001 0100
	      32-Bit AS Number (65), length: 4
		 4 Byte AS 64512
		0x0000:  0000 fc00
	      Multiple Paths (69), length: 4
		AFI IPv4 (1), SAFI Unicast (1), Send/Receive: Both
		0x0000:  0001 0103
	      Enhanced Route Refresh (70), length: 0
		no decoder for Capability 70
```

**Comment by iamaquaman** [comment]
@tmjd what command would you like to see in debug mode?

**Comment by iamaquaman** [comment]
Hi @neiljerram 

Here is the output:

```
apiVersion: projectcalico.org/v3
items:
- apiVersion: projectcalico.org/v3
  kind: Node
  metadata:
    creationTimestamp: 2019-10-05T00:52:17Z
    name: xxxxxxxxxxxxxxxxxxx
    resourceVersion: "4671112"
    uid: 614b8c4a-e70a-11e9-aa4c-2c59e53d8ba8
  spec:
    bgp:
      ipv4Address: xx.xxx.xx.172/32
      ipv4IPIPTunnelAddr: xx.xxx.xxx.0
    orchRefs:
    - nodeName: xxxxxxxxxxxxxxxxx
      orchestrator: k8s
- apiVersion: projectcalico.org/v3
  kind: Node
  metadata:
    creationTimestamp: 2019-10-05T00:52:18Z
    name: xxxxxxxxxxxxxxxxx
    resourceVersion: "4671109"
    uid: 61c79fd5-e70a-11e9-813f-2c59e53db6d8
  spec:
    bgp:
      ipv4Address: xxx.xxx.xx.173/32
      ipv4IPIPTunnelAddr: xx.xxx.xxx.2
    orchRefs:
    - nodeName: xxxxxxxxxxxxxxxx
      orchestrator: k8s
- apiVersion: projectcalico.org/v3
  kind: Node
  metadata:
    creationTimestamp: 2019-10-05T00:52:18Z
    name: xxxxxxxxxxxxxxxxxxxxxxxxx
    resourceVersion: "4671119"
    uid: 61a186e8-e70a-11e9-a60e-2c59e53dab58
  spec:
    bgp:
      ipv4Address: xxx.xxx.xx.174/32
      ipv4IPIPTunnelAddr: xx.xxx.xxx.0
    orchRefs:
    - nodeName: xxxxxxxxxxxxxxxxxxx
      orchestrator: k8s
- apiVersion: projectcalico.org/v3
  kind: Node
  metadata:
    creationTimestamp: 2019-10-05T00:52:18Z
    name: xxxxxxxxxxxxxxxx
    resourceVersion: "4671116"
    uid: 61c8822e-e70a-11e9-a33a-2c59e53c8a38
  spec:
    bgp:
      ipv4Address: xxx.xxx.xx.xxx/32
      ipv4IPIPTunnelAddr: xx.xxx.xxx.1
    orchRefs:
    - nodeName: xxxxxxxxxxxxxxxxxxx
      orchestrator: k8s
- apiVersion: projectcalico.org/v3
  kind: Node
  metadata:
    creationTimestamp: 2019-10-05T00:52:18Z
    name: xxxxxxxxxxxxxxxxxxxxxxxxxx
    resourceVersion: "4671091"
    uid: 617cc520-e70a-11e9-bb93-2c59e53deaf0
  spec:
    bgp:
      ipv4Address: xxx.xxx.xx.176/32
      ipv4IPIPTunnelAddr: xx.xxx.xxx.0
    orchRefs:
    - nodeName: xxxxxxxxxxxxxxxxxxxx
      orchestrator: k8s
- apiVersion: projectcalico.org/v3
  kind: Node
  metadata:
    creationTimestamp: 2019-10-05T00:52:18Z
    name: b-k8s-dev-06.gld.dreamworks.net
    resourceVersion: "4671107"
    uid: 615deec4-e70a-11e9-86ad-2c59e53da820
  spec:
    bgp:
      ipv4Address: xxx.xxx.xx.177/32
      ipv4IPIPTunnelAddr: xx.xxx.xxx.2
    orchRefs:
    - nodeName: xxxxxxxxxxxxxxxxxxx
      orchestrator: k8s
kind: NodeList
metadata:
  resourceVersion: "4673694"
```

**Comment by iamaquaman** [comment]
Hi @neiljerram 

I decided to rebuild the cluster and started from scratch. I no longer get those calicoctl panics, but I still have issues with the bad peer AS. For some reason, it is receiving the default AS of  64512.

According to the documentation, that is the default AS. I don't understand why I cannot peer with the specified AS peers.

**Comment by neiljerram** [comment]
Thanks for the update @iamaquaman 

I'm unclear where you want the AS to be 64512 and where you want it to be a 32 bit number like 4200002024.  Is it 32 bit on the Calico nodes, and 64512 on the routers that they are peering with?

A configuration like this -
```
cat << EOF | calicoctl create -f -
apiVersion: projectcalico.org/v3
kind: BGPPeer
metadata:
  name: bgppeer001
spec:
  peerIP: xxx.xx.xx.48
  asNumber: 4200002024
EOF
```
means that Calico expects the .48 peer to have AS number 4200002024.  In other words, "neighbor xxx.xx.xx.48 as 4200002024" in the BIRD config on each Calico node.  So if the peer actually says it is 64512, that would explain the "Received: Bad peer AS" message.

**Comment by iamaquaman** [comment]
@neiljerram 

The issue is that I DON'T want the 64512 AS. I'm receiving it, but I don't want it. I disabled node to node mesh and established the 32 bit peers, but for some reason the logs say that  I am receiving the 64512 AS when I do NOT want it. That is the default AS number and for some reason it is picking it up when it is not supposed to.

**Comment by neiljerram** [comment]
@iamaquaman OK, thanks.  So I think you need:

1. AS number 4200002024 in the default BGPConfiguration, like this:
```
 apiVersion: projectcalico.org/v3
 kind: BGPConfiguration
 metadata:
   name: default
 spec:
   logSeverityScreen: Info
   nodeToNodeMeshEnabled: false
   asNumber: 4200002024
```

2. Check that you have configured AS number 4200002024 on the peers that the Calico nodes are connecting to.

**Comment by iamaquaman** [comment]
@neiljerram 

I still get the same issue. 

```
calicoctl get bgpconfig default --export -o yaml
apiVersion: projectcalico.org/v3
kind: BGPConfiguration
metadata:
  creationTimestamp: null
  name: default
spec:
  asNumber: 4200002024
  logSeverityScreen: Info
  nodeToNodeMeshEnabled: false
```
```
calicoctl get bgppeers
NAME        PEERIP          NODE       ASN          
bgppeer01   xxx.xxx.xx.48   (global)   4200002024   
bgppeer02   xxx.xxx.xx.50   (global)   4200002024   
```
```
calicoctl node status
Calico process is running.

IPv4 BGP status
+---------------+-----------+-------+----------+----------------------------+
| PEER ADDRESS  | PEER TYPE | STATE |  SINCE   |            INFO            |
+---------------+-----------+-------+----------+----------------------------+
| xxx.xxx.xx.48 | global    | start | 22:11:25 | Idle Received: Bad peer AS |
| xxx.xxx.xx.50 | global    | start | 22:11:09 | Idle Received: Bad peer AS |
+---------------+-----------+-------+----------+----------------------------+
```
The calico-node pods are down.

I notice that whenever I configure the global bgp peers, the calico node pods go down, as soon as I remove the peers, the calico-node pods go back up.

**Comment by neiljerram** [comment]
@iamaquaman What are your BGP peer devices, and how are they configured?

**Comment by iamaquaman** [comment]
Hi,

Upon inspecting the calico pod configurations for each node, I realized that the local AS number was never configured for each node. I have now properly configured the calico node pods with each individual node's local AS. I can now see that one of them works, but the others are still not working.

Here is a sample of the configuration for the one pod that is actually receiving traffic after configuring the local pod AS.

```
kind: Node
metadata:
  creationTimestamp: null
  name: MYNODE3
spec:
  bgp:
    asNumber: 4282231640
    ipv4Address: xxx.xx.xx.174/32
    ipv4IPIPTunnelAddr: xx.xxx.xxx.6
  orchRefs:
  - nodeName: MYNODE3
    orchestrator: k8s
```

Upon viewing the pods, I can see that only the one pod mentioned is receiving traffic.

```
kube-system   calico-node-6c7qs                                         0/1     Running   0          10d
kube-system   calico-node-dgc8x                                         1/1     Running   0          10d
kube-system   calico-node-jxv6v                                         0/1     Running   0          10d
kube-system   calico-node-l8hlj                                         0/1     Running   0          10d
kube-system   calico-node-xtd2f                                         0/1     Running   0          10d
kube-system   calico-node-zxkn4                                         0/1     Running   0          10d
```

**Comment by iamaquaman** [comment]
Hi Everyone,

We were able to get this fixed on our end.

We were originally getting the errors because we had not configured our calico node pods to have the local AS set.

We did this by directly applying the desired configuration to the calico node pods.

Example:

```
cat << EOF | calicoctl apply -f -
apiVersion: projectcalico.org/v3
kind: Node
metadata:
  creationTimestamp: null
  name: #############
spec:
  bgp:
    asNumber: 4282223528
    ipv4Address: xxx.xxx.xx.173/32
  orchRefs:
  - nodeName: ############
    orchestrator: k8s
EOF
```

We then saw the issue with only one calico pod running. The reason for that was because we re-kicked machines and they came back with different IPs meaning the ASN mappings changed. We neglected to update the upstream configs.

This is now working as expected.


Thank you all for your willingness to help.
