### ISSUE TITLE
NetworkPolicy based on PodSelector and NamespaceSelector doesn't work.

### ISSUE THREAD

**Issue by TomatoAres** [projectcalico/calico#2993]
NetworkPolicy based on PodSelector and NamespaceSelector doesn't work.
## Expected Behavior

* policy:
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: network-policy
  creationTimestamp: null
  name: allow-client-b-in-ns-b-via-ns-selector-and-pod-selector
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          ns-name: network-policy-c
      podSelector:
        matchLabels:
          pod-name: client-b
  podSelector:
    matchLabels:
      pod-name: network-policy-server
```
* namespace:
```yaml
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2019-11-15T05:52:09Z"
  labels:
    ns-name: network-policy-b
  name: network-policy-b
```
* pod
```
apiVersion: v1
kind: Pod
metadata:
  namespace: network-policy-b
  generateName: client-a-

  labels:
    pod-name: client-b
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - for i in $(seq 1 5); do nc -vz -w 8 svc-network-policy-server.network-policy
      80 && exit 0 || sleep 1; done; exit 1
    image: beyond.io:5000/busybox:1.29
    name: client-a-container
    resources: {}
  restartPolicy: Never
status: {}

```
this pod was expected to connect to server，but can not.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version : v3.1.0
* Orchestrator version (e.g. kubernetes, mesos, rkt):kubernetes-v1.15.1
* Operating System and version: Centos 7 1804
* Link to your project (optional):
