### ISSUE TITLE
can floatingIPs feature working with IPv6?

### ISSUE THREAD

**Issue by nokia-t1zhou** [projectcalico/calico#3013]
I want to use the floating IP feature in Calico 3.9, after follow the step by https://docs.projectcalico.org/v3.9/networking/add-floating-ip#enable-floating-ips, 
first, i am test the IPv4 floating IP, it is working in our pod, i can ping it from outside of Kubernetes cluster.
but when i try the IPv6 floating IP, the pod is running, but i can't find any entry in IPv6 iptables.

so dose any other configuration steps that i am missed?
```
[root@master floatingip]# ip6tables -nL
Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
```
and i can't use ping6 to ping the floating IP outside cluster, seams icmp package is arrived in node, but not forwarding to container, maybe the root cause is there is no IPv6 iptable rule.
## Steps to Reproduce (for bugs)

1. ippool for ipv6
```
[root@master zhoutong]# kubectl get ippools.crd.projectcalico.org ipv6-ippool -o yaml
apiVersion: crd.projectcalico.org/v1
kind: IPPool
metadata:
  creationTimestamp: "2019-11-26T08:05:00Z"
  generation: 1
  name: ipv6-ippool
  resourceVersion: "8278059"
  selfLink: /apis/crd.projectcalico.org/v1/ippools/ipv6-ippool
  uid: 7172d43d-1023-11ea-8505-a81e847ddd7d
spec:
  cidr: 2000:1900::0/120
  ipipMode: Always
  natOutgoing: true
  nodeSelector: all()
```

2. CNI configuration
```
{
  "name": "k8s-cm-network",
  "cniVersion": "0.3.1",
  "plugins": [
    {
      "type": "calico",
      "log_level": "info",
      "datastore_type": "kubernetes",
      "nodename": "10.70.42.68",
      "mtu": 1440,
      "ipam": {
          "type": "calico-ipam"
      },
      "policy": {
          "type": "k8s"
      },
      "kubernetes": {
          "kubeconfig": "/etc/cni/net.d/calico-kubeconfig"
      },
      "feature_control": {
          "floating_ips": true
      }
    },
    {
      "type": "portmap",
      "snat": true,
      "capabilities": {"portMappings": true}
    }
  ]
}
```
3. pod deployment yaml
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zhou-test
  namespace: default
spec:
  selector:
    matchLabels:
      app: zhou-test
  template:
    metadata:
      labels:
        app: zhou-test
      annotations:
        "cni.projectcalico.org/floatingIPs": "[\"3000:2000::10\"]"
        "cni.projectcalico.org/ipAddrs": "[\"2000:1900::10\"]"
    spec:
      containers:
      - name: zhoutest
        image: test:v1.6
        command: ["/bin/bash"]
        stdin: true
        tty: true
```
4.

## Your Environment

* Calico version 3.9.3
* Orchestrator version (e.g. kubernetes, mesos, rkt): K8s 1.13.0
* Operating System and version:  Linux master 3.10.0-1062.1.2.el7.x86_64 #1 SMP Mon Sep 30 14:19:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Link to your project (optional):
