### ISSUE TITLE
GlobalNetworkPolicy for IPv4 and IPv6

### ISSUE THREAD

**Issue by revengel** [projectcalico/calico#3133]
How can I configure a firewall using GlobalNetworkPolicy manifests on interface eth0 for IPv4 and IPv6 in Kubernetes?

I has been configured HostEndpoint

```yaml
---
apiVersion: crd.projectcalico.org/v1
kind: HostEndpoint
metadata:
  name: node1-eth0-ipv4
  labels:
    kubernetes-host: ingress
spec:
  interfaceName: eth0
  node: node1
  expectedIPs:
    - "136.136.136.136"
    - "2001:db8:85a3:8d3:1319:8a2e:370:7348"
```

Applying it with kubectl
```bash
kubectl apply -f manifest.yaml
```

Now creating GlobalNetworkPolicy for IPv4 and IPv6:
```yaml
---
apiVersion: crd.projectcalico.org/v1
kind: GlobalNetworkPolicy
metadata:
  name: drop-node-ingress-ipv6-web
spec:
  order: 0
  selector: has(kubernetes-host)
  ingress:
    - action: Deny
      protocol: TCP
      ipVersion: 6
      destination:
        ports: [8181]
    - action: Deny
      protocol: TCP
      ipVersion: 4
      destination:
        ports: [8181]
```

But there are not any ip6tables rules
```bash
ip6tables-save
```

```# Generated by ip6tables-save v1.6.1 on Wed Jan 15 10:38:30 2020
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
COMMIT
# Completed on Wed Jan 15 10:38:30 2020
```
