### ISSUE TITLE
[GlobalNetworkPolicy] Ingress rules partially working

### ISSUE THREAD

**Issue by sc250024** [projectcalico/calico#3233]
When I apply a `GlobalNetworkPolicy` to accept traffic by default from namespaces which run Ingress controllers, I can establish TCP connections properly, but the webpage I'm trying to reach _still_ times out.

Here's the `GlobalNetworkPolicy`:

<details>
  <summary>global-default-policy.yaml</summary>
  
  ```yaml
---
apiVersion: crd.projectcalico.org/v1
kind: GlobalNetworkPolicy
metadata:
  name: global-default-policy
spec:
  order: 5000
  types:
  - Egress
  - Ingress

  # Egress network rules
  egress:
  ## Allow all egress traffic
  - action: Allow
    destination:
      nets:
      - 0.0.0.0/0

  # Ingress network rules
  ingress:
  ## Allow incoming DNS traffic into the 'kube-system' namespace.
  - action: Allow
    destination:
      selector: k8s-app == 'kube-dns'
    protocol: UDP
    ports:
    - 53
  ## Allow all ingress traffic from the 'monitoring' namespace.
  - action: Allow
    source:
      namespaceSelector: name == 'monitoring'
  ## Allow all ingress traffic from the 'ingress-nginx-external' namespace.
  - action: Allow
    source:
      namespaceSelector: name == 'ingress-nginx-external'
  ## Allow all ingress traffic from the 'ingress-nginx-internal' namespace.
  - action: Allow
    source:
      namespaceSelector: name == 'ingress-nginx-internal'
  ```
</details>

And for reproducing, I'm using the following test application in the `test-app` namespace on my cluster:

<details>
  <summary>test-app.yaml</summary>
  
  ```yaml
---
kind: Pod
apiVersion: v1
metadata:
  name: apple-app
  labels:
    app: apple
spec:
  containers:
  - name: apple-app
    image: hashicorp/http-echo
    args:
    - "-text=apple"
---
kind: Service
apiVersion: v1
metadata:
  name: apple-service
spec:
  selector:
    app: apple
  ports:
  - port: 5678
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    kubernetes.io/ingress.class: ingress-nginx-external
    nginx.ingress.kubernetes.io/ingress.class: ingress-nginx-external
spec:
  rules:
  - host: myapp.mycompany.com
    http:
      paths:
      - path: /
        backend:
          serviceName: apple-service
          servicePort: 5678
  ```
</details>

## Expected Behavior

The above basic global policy should:

- Allow all egress traffic
- Allow ingress traffic on pods with the label `k8s-app == 'kube-dns'` on port `UDP/53`.
- Allow all ingress traffic from the `monitoring` namespace.
- Allow all ingress traffic from the `ingress-nginx-external` namespace.
- Allow all ingress traffic from the `ingress-nginx-internal` namespace.

## Current Behavior

From a network perspective it is in fact working, but when I try to access the site externally, it continually times out.

Currently all of the rules are _technically_ obeyed:
- From the **monitoring** namespace, I can access the `test-app` on port `5678`.

```console
$ kubectl run \
--generator=run-pod/v1 \
--image=nicolaka/netshoot \
--namespace monitoring \
--rm \
--stdin \
--tty \
test-pod -- curl --head http://apple-service.test-app:5678

HTTP/1.1 200 OK
X-App-Name: http-echo
X-App-Version: 0.2.3
Date: Sun, 09 Feb 2020 22:10:18 GMT
Content-Length: 6
Content-Type: text/plain; charset=utf-8

pod "test-pod" deleted
```

- From the **ingress-nginx-external** namespace, I can access the `test-app` on port `5678`.

```console
$ kubectl run \
--generator=run-pod/v1 \
--image=nicolaka/netshoot \
--namespace ingress-nginx-external \
--rm \
--stdin \
--tty \
test-pod -- curl --head http://apple-service.test-app:5678

HTTP/1.1 200 OK
X-App-Name: http-echo
X-App-Version: 0.2.3
Date: Sun, 09 Feb 2020 22:12:20 GMT
Content-Length: 6
Content-Type: text/plain; charset=utf-8

pod "test-pod" deleted
```

- From the **ingress-nginx-internal** namespace, I can access the `test-app` on port `5678`.

```console
$ kubectl run \
--generator=run-pod/v1 \
--image=nicolaka/netshoot \
--namespace ingress-nginx-internal \
--rm \
--stdin \
--tty \
test-pod -- curl --head http://apple-service.test-app:5678

HTTP/1.1 200 OK
X-App-Name: http-echo
X-App-Version: 0.2.3
Date: Sun, 09 Feb 2020 22:13:37 GMT
Content-Length: 6
Content-Type: text/plain; charset=utf-8

pod "test-pod" deleted
```

When I try to access the application externally now, I can do an initial `telnet`, which responds, but any attempt to do a basic `curl` fails.

```console
$ telnet myapp.mycompany.com 80

Trying 54.77.3.XYZ...
Connected to myapp.mycompany.com.
Escape character is '^]'.

$ timeout 10s curl --verbose --head http://myapp.mycompany.com

*   Trying 54.77.3.XYZ...
* TCP_NODELAY set
* Connected to myapp.mycompany.com (54.77.3.XYZ) port 80 (#0)
> HEAD / HTTP/1.1
> Host: myapp.mycompany.com
> User-Agent: curl/7.64.1
> Accept: */*
>
```

## Possible Solution

I'm not sure actually. Do I need separate `GlobalNetworkPolicy` documents?

Also, EKS only supports `crd.projectcalico.org/v1`. Could this be the problem?

## Steps to Reproduce (for bugs)

1. Apply the `GlobalNetworkPolicy` above.
2. Apply the `test-app.yaml` in a namespace called `test-app` on a cluster with a working Ingress controller.

## Context

I'm trying to create a basic `GlobalNetworkPolicy` whereby pods in the `monitoring` namespace can scrape the cluster by default, and that applications created in their own namespaces can be access from the ingress controllers.

## Your Environment
* Calico version: **quay.io/calico/node:v3.12.0**
* Helm chart: **https://hub.kubeapps.com/charts/aws/aws-calico**
* Helm chart version: **aws-calico-0.1.0**
* Orchestrator version (e.g. kubernetes, mesos, rkt): **Kubernetes / Amazon EKS 1.14**
* Operating System and version: **Amazon Linux 2**
