### ISSUE TITLE
DNS resolution from pods does not work: `Can't find xxxxx.xxx: No answer`

### ISSUE THREAD

**Issue by papanito** [projectcalico/calico#3274]
Dns resolution does not properly work. If I do a `nslookup` from within a pod I get an `Can't find xxxxx.xxx: No answer`

```

/ # nslookup github.com
Server:		10.43.0.10
Address:	10.43.0.10:53

Non-authoritative answer:
Name:	github.com
Address: 140.82.118.3

*** 
```
nslookup from the k8s node itself is fine

```
user@node001:~$ dig github.com

; <<>> DiG 9.11.5-P4-5.1-Debian <<>> github.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 57607
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 8, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;github.com.			IN	A

;; ANSWER SECTION:
github.com.		7	IN	A	140.82.118.3

;; AUTHORITY SECTION:
github.com.		536	IN	NS	ns4.p16.dynect.net.
github.com.		536	IN	NS	ns-1283.awsdns-32.org.
github.com.		536	IN	NS	ns-1707.awsdns-21.co.uk.
github.com.		536	IN	NS	ns-421.awsdns-52.com.
github.com.		536	IN	NS	ns-520.awsdns-01.net.
github.com.		536	IN	NS	ns1.p16.dynect.net.
github.com.		536	IN	NS	ns2.p16.dynect.net.
github.com.		536	IN	NS	ns3.p16.dynect.net.

;; Query time: 0 msec
;; SERVER: 213.133.100.100#53(213.133.100.100)
;; WHEN: Fri Feb 21 19:30:35 CET 2020
;; MSG SIZE  rcvd: 275
```

## Expected Behavior

I would expect that the dns resolution just works and I get a proper response

## Current Behavior

As mentioned above I get a error `Can't find xxxxx: No answer`

```
kubectl run -i -t busybox --image=busybox --restart=Never

/ # nslookup github.com
Server:		10.43.0.10
Address:	10.43.0.10:53

Non-authoritative answer:

*** Can't find github.com: No answer

/ # nslookup letsencrypt.org
Server:		10.43.0.10
Address:	10.43.0.10:53

Non-authoritative answer:
Name:	letsencrypt.org
Address: 2a03:b0c0:3:e0::298:6001

*** Can't find letsencrypt.org: No answer
```

## Possible Solution

N/A

## Steps to Reproduce (for bugs)

1. Start `busybox`: `kubectl run -i -t busybox --image=busybox --restart=Never`
2. Run `nslookup` in pod

## Context

I've setup my cluster with `rke` using `calico` and `coredns`. After that I've installed `cert-manager` `0.13.0` and I noticed the following error for the `ClusterIssuer`

```bash
  Type     Reason                Age   From          Message
  ----     ------                ----  ----          -------
  Warning  ErrVerifyACMEAccount  112s  cert-manager  Failed to verify ACME account: Get https://acme-v02.api.letsencrypt.org/directory: dial tcp: i/o timeout
  Warning  ErrInitIssuer         112s  cert-manager  Error initializing issuer: Get https://acme-v02.api.letsencrypt.org/directory: dial tcp: i/o timeout
```
So having a look at `DNS` resoultion I figured this might be the problem...

I know the topic with `nft` so currently I followed the suggestion in [this comment](https://github.com/coredns/coredns/issues/2693#issuecomment-543208513) and run `iptables-legacy`

```bash
sudo update-alternatives --set iptables /usr/sbin/iptables-legacy
sudo update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
sudo update-alternatives --set arptables /usr/sbin/arptables-legacy
sudo update-alternatives --set ebtables /usr/sbin/ebtables-legacy
```
[calico-kube-controller.log](https://github.com/projectcalico/calico/files/4241185/calico-kube-controller.log)
[calico-node-cvbsq.log](https://github.com/projectcalico/calico/files/4241186/calico-node-cvbsq.log)
[calico-node-h74pg.log](https://github.com/projectcalico/calico/files/4241187/calico-node-h74pg.log)
[coredns-7c5566588d-4cqm4.log](https://github.com/projectcalico/calico/files/4241188/coredns-7c5566588d-4cqm4.log)
[coredns-7c5566588d-ftkc8.log](https://github.com/projectcalico/calico/files/4241189/coredns-7c5566588d-ftkc8.log)
[coredns-autoscaler.log](https://github.com/projectcalico/calico/files/4241190/coredns-autoscaler.log)

## Your Environment

* Calico version: ``
* Orchestrator version (e.g. kubernetes, mesos, rkt): `kubernetes 1.17.2`
* Operating System and version: `Debian 10`
* Link to your project (optional):

kind /support

**Comment by fasaxc** [comment]
What's you Calico version?  v3.12 has autodetect for iptables mode, which could be useful if you're on a system that uses nft mode.

Do you have any network policy applied?  Once you have some policy, you get default drop so DNS can get dropped by accident just by creating a policy that allows some other traffic.  (That's the behaviour defined by the k8s network policy API so it's what we follow.)

**Comment by papanito** [comment]
I am using 
```
rancher/calico-node:v3.10.2
```
for now, I use `iptables` so autodetection is not necessary. However, good to know!

**Comment by tmjd** [comment]
Can you verify on your hosts that iptables-legacy is being used? Just setting the alternatives to use iptables-legacy does not immediately switch the iptables backend used on the system. You'd probably at least need to reboot your nodes to pickup that change fully.
You should also check (after reboot) that there are not rules being added to the iptables nft backend by any components.

**Comment by papanito** [comment]
After switching I've restarted the servers and I can confirm that legacy is running

```bash
sudo iptables -v
iptables v1.8.2 (legacy): no command specified
```

> You should also check (after reboot) that there are not rules being added to the iptables nft backend by any components.

Any hints how I do this best :-/

**Comment by tmjd** [comment]
Hopefully you have `iptables-nft-save` and then you can do `sudo iptables-nft-save` to see the rules, if any.

Does pod-to-pod traffic work? You can bring up two test pods, preferably on different nodes and then check that one can reach the other. My thought being that if DNS isn't working perhaps the dns pod is not reachable for some reason.

You can run `nc -v -l 5555` in pod A (this will block until a connection) and then `nc -v <ip of pod A> 5555`. You should see a message with both if the connection is successful.

**Comment by papanito** [comment]
Yeah pod to pod connection works

**pod B**
```
/ # nc -v 10.42.112.166 5555
10.42.112.166 (10.42.112.166:5555) open
```
**pod A**
```
nc -v -l -p 5555
listening on [::]:5555 ...
connect to [::ffff:10.42.112.166]:5555 from [::ffff:10.42.112.167]:45517 ([::ffff:10.42.112.167]:45517)
```

Here a dump of the `iptables` rules
[iptable-rules.txt](https://github.com/projectcalico/calico/files/4325524/iptable-rules.txt)

**Comment by tmjd** [comment]
That's good. Have you checked that no rules exist in the `iptables-nft-save`? Just because there are rules in the legacy(that's what non-nft is considered) backend does not mean there are none in iptables nft.

Can you do a `dig @10.43.0.10 github` from a node, does that work? That is a kube service so it should work from a node also.

In your original post it looks like the dns pod is reachable but it is not returning an answer.
Could you verify that perhaps using from a pod `nc -v -u 10.43.0.10 53` can connect. Assuming that does, it seems like the issue may be the DNS pod reaching an upstream DNS server. Could you try connecting to an 'upstream' DNS server from the DNS pod, if it doesn't have utilities for that can you reach from a test pod?

Have you customized your install any? I'm wondering what your IPPool configuration is, do you have NAT Outgoing disabled (enabled is the default).

**Comment by papanito** [comment]
`iptables-nft-save` does not work

```bash
user@node002:~$ sudo iptables-nft-save
# Warning: iptables-legacy tables present, use iptables-legacy-save to see them
```

Yes `dig` from a node works

```bash
user@node002:~$ dig @10.43.0.10 github

; <<>> DiG 9.11.5-P4-5.1-Debian <<>> @10.43.0.10 github
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 8488
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;github.				IN	A

;; AUTHORITY SECTION:
.			30	IN	SOA	a.root-servers.net. nstld.verisign-grs.com. 2020031300 1800 900 604800 86400

;; Query time: 25 msec
;; SERVER: 10.43.0.10#53(10.43.0.10)
;; WHEN: Fri Mar 13 19:03:57 CET 2020
;; MSG SIZE  rcvd: 110
```

I can connect to DNS pod

```bash
/ # nc -v -u 10.43.0.10 53
10.43.0.10 (10.43.0.10:53) open
```

> Have you customized your install any? 

I can share my `rke`-conifg. As you can see I use an internal address which is a `vlan` which connects the nodes together.

```yaml
# 
# Cluster Config
# 
enable_cluster_alerting: true
enable_cluster_monitoring: true
enable_network_policy: false
local_cluster_auth_endpoint:
  enabled: true

nodes:
  - address: x.x.x.x
    hostname_override: node001
    internal_address: 192.168.100.1
    user: ansible
    role: [controlplane,worker,etcd]
  - address: y.y.y.y
    hostname_override: node002
    internal_address: 192.168.100.2
    user: ansible
    role: [worker,etcd]
  - address: z.z.z.z
    hostname_override: node003
    internal_address: 192.168.100.3
    user: ansible
    role: [worker,etcd]

cluster_name: dev-cluster
kubernetes_version: "v1.17.2-rancher1-2" # rke config --list-version --all

dns:
  provider: coredns
  upstreamnameservers:
  - 1.1.1.1
  - 8.8.8.8
  - 8.8.4.4
  - 213.133.100.100
  - 213.133.99.99
  - 213.133.98.98

network:
  plugin: calico

ingress:
    provider: nginx

services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 48h
  kube-api:
    service_cluster_ip_range: 10.43.0.0/16
  kube-controller:
    cluster_cidr: 10.42.0.0/16
    service_cluster_ip_range: 10.43.0.0/16
  kubelet:
    cluster_domain: cluster.local
    cluster_dns_server: 10.43.0.10
  scheduler:
    # no paramaters available
  kube-proxy:
    # no paramaters available
  # calico:
  #   extra_env:
  #     - "FELIX_IPTABLESBACKEND=NFT"
```
