### ISSUE TITLE
FELIX_NATOUTGOINGADDRESS and IPv6

### ISSUE THREAD

**Issue by duylong** [projectcalico/calico#3275]
Hi,

I have a problem when I'm trying to configure Calico in order to use FELIX_NATOUTGOINGADDRESS. 

I'm in a dualstack IPv4/IPv6 with Kubernetes.  When I use this configuration in my calico.yaml deployment:
```
            - name: FELIX_NATOUTGOINGADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
```
... I get this error:

```
2020-02-24 14:12:52.093 [WARNING][1558] table.go 1191: Failed to execute ip(6)tables-restore command error=exit status 2 errorOutput="ip6tables-restore v1.8.2 (legacy): Bad IP address \"192.168.10.100\"\n\nError occurred at line: 2\nTry `ip6tables-restore -h' or 'ip6tables-restore --help' for more information.\n" input="*nat\n-R cali-nat-outgoing 1 -m comment --comment \"cali:ltvx3bX8efbq2000\" -m set --match-set cali60masq-ipam-pools src -m set ! --match-set cali60all-ipam-pools dst --out-interface bond+ --jump SNAT --to-source 192.168.10.100\nCOMMIT\n" ipVersion=0x6 output="" table="nat"
```
How to configure for FELIX_NATOUTGOINGADDRESS in IPv6 mode ?
