### ISSUE TITLE
[Question] GlobalNetworkPolicy  vs NetworkPolicy

### ISSUE THREAD

**Issue by emirot** [projectcalico/calico#3308]
Calico version: 3.9 on gke15.9

I have 3 applications, app-go, nginx-1, and nginx-2 all in default namespace.
My goal is to add an ingress rule to allow incoming traffic from app-go to nginx-2.

If I have this global rule:
```
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: default-deny
spec:
  order: 20
  selector: all()
  types:
  - Ingress
```
Combined with:

```
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: allow-nginx
  namespace: default
spec:
  order: 40
  selector: app == 'nginx-2'
  ingress:
#   - action: Allow
#     source:
#       nets:
#         - 0.0.0.0/0
  - action: Allow
    protocol: TCP
    source:
      selector: app == 'app-go'
    destination:
      ports:
        - 80
```
I can't access anything from anywhere.

However with this "NamespaceNetworkPolicy" I have the desired behavior.

```
 apiVersion: projectcalico.org/v3
 kind: NetworkPolicy
 metadata:
   name: default-deny
   namespace: default
 spec:
   selector: all()
   types:
   - Ingress
```
Why is the case ?

**Comment by tmjd** [comment]
Since you have specified a lower order for your GlobalNetworkPolicy default-deny it will happen before your higher order allow-nginx policy. That means the traffic never makes it to the allow policy since it has already been denied by the GlobalNetworkPolicy default-deny.
I believe the default order when not specified is 1000, or maybe it is highest if not specified, I don't remember. Either way, the deny comes after the allow so your traffic is allowed when using the NetworkPolicy default-deny.

**Comment by emirot** [comment]
I don't understand why I can't access my pod from that ip:

```
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: nolan
  namespace: app
spec:
  selector: app == 'nolan'
  ingress:
  - action: Allow
    protocol: TCP
    source:
      nets:
      - 1.2.3.4/32 # my ip office
```
What am I missing there ?
