### ISSUE TITLE
Cannot reach coredns server after adding default bgpConfiguration in K8S

### ISSUE THREAD

**Issue by shaozi** [projectcalico/calico#3311]
After I added a default bgpConfiguration as in https://docs.projectcalico.org/reference/resources/bgpconfig

```yaml
apiVersion: projectcalico.org/v3
kind: BGPConfiguration
metadata:
  name: default
spec:
  logSeverityScreen: Info
  nodeToNodeMeshEnabled: true
  asNumber: 64512
  serviceClusterIPs:
  - cidr: 10.96.0.0/12
  serviceExternalIPs:
  - cidr: 192.168.1.1/32
  - cidr: 192.168.1.2/32
  - cidr: 192.168.1.3/32
```

all pod in k8s cannot reach coredns anymore.

```sh
/ # nslookup google.com
;; connection timed out; no servers could be reached
```

## Your Environment

* Calico version

Client Version:    v3.12.0
Git commit:        84a21b3b
Cluster Version:   v3.11.2
Cluster Type:      k8s,bgp,kdd

* Orchestrator version (e.g. kubernetes, mesos, rkt):

Kubernetes 1.17 with 3 nodes

* Operating System and version:

Ubuntu 18.04
