### ISSUE TITLE
Misconfiguration BGPConfiguration

### ISSUE THREAD

**Issue by tung-huynh** [projectcalico/calico#3337]
I am trying to follow the instruction at https://docs.projectcalico.org/networking/advertise-service-ips
But it is failed to create the BGPConfiguration 
```yaml
calicoctl create -f - <<EOF
apiVersion: projectcalico.org/v3
kind: BGPConfiguration
metadata:
  name: default
spec:
  serviceExternalIPs:
  - cidr: x.x.x.x/16
  - cidr: y.y.y.y/32
EOF
```

## Expected Behavior
BGPConfiguration is created just fine

## Current Behavior
A error message:
`Failed to execute command: error parsing document: field in document is not recognized or is in the wrong location: serviceExternalIPs`

## Your Environment
* Calico version: v3.13.0
* Orchestrator version: kubernetes
* Operating System and version: Ubuntu 18.04.4 LTS
