### ISSUE TITLE
GKE 1.14 - NetworkPolicies only working within the same node

### ISSUE THREAD

**Issue by lechuk47** [projectcalico/calico#3347]
Hi all, 

I'm testing the network policies in GKE 1.14 with a very basic configuration. I want to allow the comunicacions from namespace ns1 to namespace ns2. The rule seems to work only if I test it with pods in the same node.  

## Expected Behavior
All pods from ns2 namespace can communicate with pods in ns1 namespace

## Current Behavior
Pods from ns2 namespace can comunicate with pods in ns1 namespace if both pods are in the same node

## Steps to Reproduce (for bugs)
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: ns1
  labels:
    name: ns1
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns2
  labels:
    name: ns2
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: app-ns1
  name: dep-app-ns1
  namespace: ns1
spec:
  replicas: 3
  template:
    metadata:
      labels:
        run: app-ns1
    spec:
      containers:
      - image: brndnmtthws/nginx-echo-headers
        imagePullPolicy: Always
        name: app-ns1
        ports:
        - containerPort: 8080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: app-ns2
  name: dep-app-ns2
  namespace: ns2
spec:
  replicas: 3
  template:
    metadata:
      labels:
        run: app-ns2
    spec:
      containers:
      - image: brndnmtthws/nginx-echo-headers
        imagePullPolicy: Always
        name: app-ns2
        ports:
        - containerPort: 8080
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-from-ns2
  namespace: ns1
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ns2
```

```bash
$ kubectl get pods -n ns1 -o wide
NAME                           READY   STATUS    RESTARTS   AGE     IP             NODE                                                  NOMINATED NODE   READINESS GATES
dep-app-ns1-78648b76fb-mthq2   1/1     Running   0          4m20s   172.22.16.23   gke-gkepro-mp1-gke-c-e2-standard-8-pr-71d73afa-s08f   <none>           <none>
dep-app-ns1-78648b76fb-x5d2g   1/1     Running   0          4m20s   172.22.17.17   gke-gkepro-mp1-gke-c-e2-standard-8-pr-82d4caf3-scph   <none>           <none>
dep-app-ns1-78648b76fb-z2r4m   1/1     Running   0          4m20s   172.22.18.14   gke-gkepro-mp1-gke-c-e2-standard-8-pr-d9c9ec9e-z8cm   <none>           <none>
$ kubectl get pods -n ns2 -o wide
NAME                          READY   STATUS    RESTARTS   AGE     IP             NODE                                                  NOMINATED NODE   READINESS GATES
dep-app-ns2-58987d744-c5jtf   1/1     Running   0          4m24s   172.22.16.24   gke-gkepro-mp1-gke-c-e2-standard-8-pr-71d73afa-s08f   <none>           <none>
dep-app-ns2-58987d744-kx9gh   1/1     Running   0          4m24s   172.22.17.18   gke-gkepro-mp1-gke-c-e2-standard-8-pr-82d4caf3-scph   <none>           <none>
dep-app-ns2-58987d744-rngw4   1/1     Running   0          4m24s   172.22.18.15   gke-gkepro-mp1-gke-c-e2-standard-8-pr-d9c9ec9e-z8cm   <none>           <none>
$ kubectl exec -ti dep-app-ns2-58987d744-c5jtf -n ns2 /bin/sh
/ # nc -vz -w 2 172.22.16.23 8080
172.22.16.23 (172.22.16.23:8080) open
/ # nc -vz -w 2 172.22.17.17 8080
nc: 172.22.17.17 (172.22.17.17:8080): Operation timed out
/ # nc -vz -w 2 172.22.18.14 8080
nc: 172.22.18.14 (172.22.18.14:8080): Operation timed out
```

## Your Environment

* Calico version: 3.2.7
* GKE 1.14.10-22
* COS

Any advice? 

Many thanks in advance.
