### ISSUE TITLE
GlobalNetworkPolicy/NetworkPolicy to deny traffic across k8s clusters does not work as expected.

### ISSUE THREAD

**Issue by lut777** [projectcalico/calico#3387]
## Your Environment
Calico version:
Client Version:    v3.13.0
Git commit:        eb796e31
Cluster Version:   v3.13.1
Cluster Type:      k8s,bgp,kubeadm,kdd

k8s version:
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

Operating System and version:
Ubuntu 18.04

Project env:
2 k8s clusters, The pod CIDR of cluster A is 192.17.0.0/16, and CIDR of cluster B is 192.18.0.0/16. I managed to peer RRs of 2 clusters thus they are reachable mutually.

expected behavior:
first of all, I have a default "globalnetworkpolicy" deny for all traffic as suggested in https://docs.projectcalico.org/security/kubernetes-default-deny.
Based on namespaces isolation network policy from here: https://docs.projectcalico.org/security/namespace-policy, I specified the label of the source/destination of the ingress/egress under the same ns, which is like the following:
```yaml
  ...
  selector: all()
  egress:
  - action: Allow
    source:
      namespaceSelector: svc == 'default'
  ingress:
  - action: Allow
    source:
      namespaceSelector: svc == 'default'
```
In this way, it works as I expect.

unexpected behavior:
HOWEVER, based on such settings, I find out that I can ping the pod in cluster A from a pod in cluster B, which is not I expect.
I assumed this unexpected reachable problem may be caused by the network policy I set, thus I add settings for limited external IP (which is 192.17.0.0/16) based on https://docs.projectcalico.org/security/external-ips-policy.
I changed the nets of spec in GlobalNetworkSet, and add a "GlobalNetworkPolicy" to deny matched traffic with the highest order, which are as shown as following:

```yaml
apiVersion: projectcalico.org/v3
kind: GlobalNetworkSet
metadata:
  name: ip-protect
  labels:
    IP-blacklist: true
spec:
  nets:
  - 192.17.0.0/16
---
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: ip-protect
spec:
  selector: all()
  order: 99
  doNotTrack: true
  applyOnForward: true
  types:
  - Ingress
  ingress:
  - action: Deny
    source:
      selector: IP-blacklist == 'true' && !has(projectcalico.org/namespace)
```
THEN the strange things come out: traffic of pods in the same namespace is dropped, which can be expected, however, pods between clusters are still reachable! Which is totally beyond my understanding.

So, does anyone understand why this scenario shows up? and how can I satisfy my needs?
Or some clues on how Calico network policy works are also welcomed. maybe I can still have a try by myself.
Thank you!
