### ISSUE TITLE
[Question] Except Namespace rules on deny all ?

### ISSUE THREAD

**Issue by emirot** [projectcalico/calico#3419]
Hi There,

I was wondering if I could apply a deny all policy with an except rule on namespaces.

I would like to apply this policy to my cluster: 
```
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: default-deny
spec:
  selector: all()
  types:
  - Ingress
```
Leaving `kube-addons` and `kube-system` free of networking rules. So I don't have to create rules for each service in those namespaces.
Is this possible ?
