### ISSUE TITLE
Poor error message when IP pools annotation is not properly formed. 

### ISSUE THREAD

**Issue by sadeghrz** [projectcalico/calico#3427]
Hi.
After creating new IPPool using calicoctl i faced this error on creating pod with new IPPool.

IPPool file:
```
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: new-pool
spec:
  cidr: 10.0.0.0/16
  ipipMode: Always
  natOutgoing: true
```

IPPool list:
```
NAME                  CIDR             NAT    IPIPMODE   DISABLED
default-ipv4-ippool   192.168.0.0/16   true   Always     true
new-pool              10.0.0.0/16      true   Always     false
```

describe pod error:
```
networkPlugin cni failed to set up pod [POD_NAME] network: invalid character 'e' in literal null (expecting 'u')
```

Kubernetes: v1.17.4,
Calico: v3.13.0,
RKE: 1.0.5,
OS: ubuntu 16.4
