### ISSUE TITLE
Add a knob to disable profile addition in HostEndpoint automatically

### ISSUE THREAD

**Issue by surajssd** [projectcalico/calico#3566]
## Problem && Current Behavior

I have deployed kube controllers and it created following HostEndpoint automatically:

```
apiVersion: crd.projectcalico.org/v1
kind: HostEndpoint
metadata:     
  name: suraj-lk-cluster-pool-1-worker-0-auto-hep
...
spec:
  profiles: 
  - projectcalico-default-allow
...
```

Now the problem is it has added this field called `profiles` with automatic value of `projectcalico-default-allow`. Now using Calico on Kubernetes, which is deployed in [standard way](https://docs.projectcalico.org/manifests/calico.yaml) does not have `Profiles` CRD. 

## Possible Solution

Profile docs here https://docs.projectcalico.org/reference/resources/profile say following:

> For historic reasons, Profiles can also include policy rules, but that feature is deprecated in favor of the much more flexible `NetworkPolicy` and `GlobalNetworkPolicy` resources.

Like the docs say we make heavy use of GlobalNetworkPolicy. Add a knob to disable adding any profiles information. An env var or something in `KubeControllersConfiguration`. 

Let me know what am I doing wrong?

## Context

I cannot make use of calico version v3.14.0 with kube controller.

## Your Environment

* Calico version: v3.14.0
* Orchestrator version: Kubernetes
* Operating System and version: Flatcar Container Linux 2247.7.0
* Link to your project (optional): https://github.com/kinvolk/lokomotive/pull/415
