### ISSUE TITLE
Source ip is not preserved even though externalTrafficPolicy is Local.

### ISSUE THREAD

**Issue by jc-lab** [projectcalico/calico#3585]
## Expected Behavior
When accessing the externalIP assigned to the k8s service, the source ip of the packet in the Pod must be the original client's IP.

## Current Behavior
http://10.100.0.10/abcdefg
```
CLIENT VALUES:
client_address=10.0.0.11
command=GET
real path=/abcdefg
request_uri=http://10.100.0.10/abcdefg
```

The source ip has been changed with the IP of node-1 (the pod is running) instead of the actual IP of the client.

| Node Name | Physical Interface IP | tunl0 IP |
| ------------- | ---------------------- | --------- |
| node-1 | 10.0.0.11 | 172.30.1.35 | 
| node-2 | 10.0.0.12 | 172.30.2.9   | 

Physical network cidr : 10.0.0.0/24
Pod network cidr : 172.30.0.0/16
Service cidr : 10.244.0.0/16

In calicoctl container
```
# calicoctl get ippool -o wide
NAME                  CIDR            NAT     IPIPMODE   VXLANMODE   DISABLED   SELECTOR
default-ipv4-ippool   172.30.0.0/16   false   Always     Never       false      all()
```

In calicoctl container
```
# calicoctl get bgpconfiguration -o yaml
apiVersion: projectcalico.org/v3
kind: BGPConfigurationList
items:
- apiVersion: projectcalico.org/v3
  kind: BGPConfiguration
  metadata:
    name: default
  spec:
    asNumber: 65001
    nodeToNodeMeshEnabled: true
    serviceExternalIPs:
    - cidr: 10.100.0.0/22
```

In calicoctl container
```
# calicoctl get bgppeer -o yaml
apiVersion: projectcalico.org/v3
kind: BGPPeerList
items:
- apiVersion: projectcalico.org/v3
  kind: BGPPeer
  metadata:
    name: router-1
  spec:
    asNumber: 65000
    peerIP: 10.0.0.1
```

In kubernetes cluster
```
$ kubectl -n test get svc source-ip-app -o yaml
apiVersion: v1
kind: Service
spec:
  clusterIP: 10.244.13.190
  externalIPs:
  - 10.100.0.10
  externalTrafficPolicy: Local
  healthCheckNodePort: 32209
  ports:
  - name: http
    nodePort: 32077
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: source-ip-app
  sessionAffinity: None
  type: LoadBalancer

# while [ 1 ]; do clear; date ;echo ; iptables -t nat -L KUBE-SERVICES -v -n | grep 10.100.0.10; sleep 1; done

    1     0 KUBE-MARK-MASQ  tcp  --  *      *       0.0.0.0/0            10.100.0.10          /* test/source-ip-app:b external IP */ tcp dpt:80
    1     0 KUBE-SVC-ZFVB77MKF5SHNAE3  tcp  --  *      *       0.0.0.0/0            10.100.0.10          /* test/source-ip-app:b external IP */ tcp dpt:80 PHYSDEV match ! --physdev-is-in ADDRTYPE match src-type !LOCAL
    0     0 KUBE-SVC-ZFVB77MKF5SHNAE3  tcp  --  *      *       0.0.0.0/0            10.100.0.10          /* test/source-ip-app:b external IP */ tcp dpt:80 ADDRTYPE match dst-type LOCAL
```

KUBE-MARK-MASQ triggered

In Router
```
# show ip bgp
BGP table version is 0, local router ID is 10.0.0.1
Status codes: s suppressed, d damped, h history, * valid, > best, = multipath,
              i internal, r RIB-failure, S Stale, R Removed
Origin codes: i - IGP, e - EGP, ? - incomplete

   Network          Next Hop            Metric LocPrf Weight Path
* 10.100.0.10/32 10.0.0.11              0 65001 i
```

## Your Environment
* Calico version : v3.14.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes v1.16.8
* Operating System and version: ubuntu 18.04
