### ISSUE TITLE
After pod start network temporarily is unavailable

### ISSUE THREAD

**Issue by iLeonidze** [projectcalico/calico#3628]
At the start of the pod, it sometimes has non-working network for the first few seconds.

## Expected Behavior
When the pod starts, the network is immediately completely ready for use.

## Current Behavior
At the moment, some applications immediately crash, so they do not have a network. If you add a delay, everything works.

## Possible Solution
As far as I see, the network interface first has `tentative`, and then it disappears and the network works. Possibly problems with DAD, may be here the rootcause https://unix.stackexchange.com/questions/293629/let-ifconfig-wait-for-ipv6-address-to-not-be-tentative

## Steps to Reproduce (for bugs)
1. Create and apply Daemonset
    ```
    apiVersion: apps/v1
    kind: DaemonSet
    metadata:
      name: pingtest
      namespace: kube-system
      labels:
        k8s-app: busybox
    spec:
      selector:
        matchLabels:
          name: pingtest
      template:
        metadata:
          labels:
            name: pingtest
        spec:
          tolerations:
          - key: node-role.kubernetes.io/master
            effect: NoSchedule
          containers:
          - name: pingtest
            image: busybox-curl
            command: [ "sh", "-c", "ip a; curl -vk https://kubernetes.default; sleep 10s; ip a; curl -vk https://kubernetes.default" ]
          terminationGracePeriodSeconds: 3
    ```
2. Read logs. I get the following result:
    ```
    1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1000
        link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
        inet 127.0.0.1/8 scope host lo
           valid_lft forever preferred_lft forever
        inet6 ::1/128 scope host 
           valid_lft forever preferred_lft forever
    3: eth0@if212: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1440 qdisc noqueue 
        link/ether be:99:51:06:f1:f6 brd ff:ff:ff:ff:ff:ff
        inet6 fd02::1626:ef84:3d30/128 scope global tentative 
           valid_lft forever preferred_lft forever
        inet6 fe80::bc99:51ff:fe06:f1f6/64 scope link tentative 
           valid_lft forever preferred_lft forever

    * Expire in 200 ms for 1 (transfer 0x5599dcc23880)
      0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0* Expire in 200 ms for 1 (transfer 0x5599dcc23880)
    * Could not resolve host: kubernetes.default
    * Expire in 200 ms for 1 (transfer 0x55b2bbd58880)
    * Closing connection 0
    curl: (6) Could not resolve host: kubernetes.default

    1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1000
        link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
        inet 127.0.0.1/8 scope host lo
           valid_lft forever preferred_lft forever
        inet6 ::1/128 scope host 
           valid_lft forever preferred_lft forever
    3: eth0@if212: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1440 qdisc noqueue 
        link/ether be:99:51:06:f1:f6 brd ff:ff:ff:ff:ff:ff
        inet6 fd02::1626:ef84:3d30/128 scope global 
           valid_lft forever preferred_lft forever
        inet6 fe80::bc99:51ff:fe06:f1f6/64 scope link 
           valid_lft forever preferred_lft forever

    * TCP_NODELAY set
    * Expire in 200 ms for 4 (transfer 0x5564f127d880)
    * Connected to kubernetes.default (fd03::7d4) port 80 (#0)
    > GET / HTTP/1.1
    > Host: kubernetes.default
    > User-Agent: curl/7.64.0
    > Accept: /
    >
    < HTTP/1.1 403 Forbidden
    ```

## Context
I am running a thirdparty software that requires immediate access to the network. Adding a sleep does not seem to me the correct solution.

## Your Environment
* Calico version v3.10.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes v1.16.3
* Operating System and version: Red Hat Enterprise Linux Server release 7.6 (Maipo)
* Calico config: [calico.yaml](https://github.com/projectcalico/calico/files/4722443/calico.yaml.txt)
