### ISSUE TITLE
add additionalPrinterColumns to calico crds

### ISSUE THREAD

**Issue by juliantaylor** [projectcalico/calico#3633]
It would be nice when the crds installed by calico in https://github.com/projectcalico/calico/tree/master/_includes/charts/calico/crds/kdd would include some additionalPrinterColumns to simplify debugging issues.
See https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#additional-printer-columns for the documentation

For example the ipamblock crd could have the affinity as a printer column like this:

```
    additionalPrinterColumns:
    - name: Affinity
      type: string
      description: The affinity of the block
      jsonPath: .spec.affinty
```

I could provide a PR with some added if you would consider it.
