### ISSUE TITLE
CalicoNode as RouteReflector do not keep the originary "Next Hop" when it forward BGP routes to an Edge Router

### ISSUE THREAD

**Issue by gunboe** [projectcalico/calico#3666]
Calico Node working as a Router Reflector announce the Cluster routes as his own, that is, it does not use the parameter "next hop keep" from Bird that maintains the "Next Hop" of the routes received from the Nodes.

In my scenario I have 3 Nodes and the Master Node has Calico as RouteReflector and it share the Pods' routes with an edge BGP Router. So the Pods can be accessed from outside.

However, the Router Reflector sends all routes from the Pod Subnets to the Edge Router with the RouteReflector's IP address in the "Next Hop" field. In this way, all traffic coming from outside is transferred only to the Calico RouterReflector, when in fact it could forward directly to the Nodes.

### Sugestion to implement
**(WARNING: this not work!! Its a sugestion for a new feature)**
Inserting "next hop keep" in Bird Template file by a configurable field in BGPpeer, like this:
```
# calicoctl get bgppeer my-global-peer -o yaml
apiVersion: projectcalico.org/v3
kind: BGPPeer
metadata:
  name: my-global-peer
spec:
  asNumber: 65000
  nodeSelector: route-reflector == "true"
  peerIP: 10.79.63.42
  nextHopKeep: true
```

Resulting:
```
# cat /etc/calico/confd/config/bird.cfg
...
# For peer /host/NodeMaster/peer_v4/10.79.63.42
protocol bgp Node_10_79_63_42 from bgp_template {
  neighbor 10.79.63.42 as 65000;
  next hop keep;
}
```
