### ISSUE TITLE
felix/table.go 612: Detected out-of-sync inserts, marking for resync

### ISSUE THREAD

**Issue by tomdoherty** [projectcalico/calico#3756]
Logs flooded with `felix/table.go 612: Detected out-of-sync inserts, marking for resync`

## Expected Behavior
Inserts should be in sync

## Current Behavior
My production, staging, and development cluster logs all see logs like:

```
[calico-node-qvnwt calico-node] 2020-07-06 17:09:05.651 [WARNING][58] felix/table.go 612: Detected out-of-sync inserts, marking for resync actualRuleIDs=[]string{"", "", "tVnHkvAo15HuiPy0", "", ""} chainName="OUTPUT" expectedRuleIDs=[]string{"tVnHkvAo15HuiPy0", "", "", "", ""} ipVersion=0x4 table="filter"
[calico-node-qvnwt calico-node] 2020-07-06 17:09:05.651 [WARNING][58] felix/table.go 612: Detected out-of-sync inserts, marking for resync actualRuleIDs=[]string{"", "", "", "", "wUHhoiAYhphO9Mso", "", "", "", "", "", "", "", ""} chainName="FORWARD" expectedRuleIDs=[]string{"wUHhoiAYhphO9Mso", "", "", "", "", "", "", "", "", "", "", "", ""} ipVersion=0x4 table="filter"
[calico-node-vk7tr calico-node] 2020-07-06 17:09:23.282 [WARNING][54] felix/table.go 612: Detected out-of-sync inserts, marking for resync actualRuleIDs=[]string{"", "", "tVnHkvAo15HuiPy0", "", ""} chainName="OUTPUT" expectedRuleIDs=[]string{"tVnHkvAo15HuiPy0", "", "", "", ""} ipVersion=0x4 table="filter"
[calico-node-vk7tr calico-node] 2020-07-06 17:09:23.282 [WARNING][54] felix/table.go 612: Detected out-of-sync inserts, marking for resync actualRuleIDs=[]string{"", "", "", "", "wUHhoiAYhphO9Mso", "", "", "", "", "", "", "", ""} chainName="FORWARD" expectedRuleIDs=[]string{"wUHhoiAYhphO9Mso", "", "", "", "", "", "", "", "", "", "", "", ""} ipVersion=0x4 table="filter"
[calico-node-vmh6s calico-node] 2020-07-06 17:09:25.016 [WARNING][61] felix/table.go 612: Detected out-of-sync inserts, marking for resync actualRuleIDs=[]string{"", "", "tVnHkvAo15HuiPy0", "", ""} chainName="OUTPUT" expectedRuleIDs=[]string{"tVnHkvAo15HuiPy0", "", "", "", ""} ipVersion=0x4 table="filter"
[calico-node-vmh6s calico-node] 2020-07-06 17:09:25.016 [WARNING][61] felix/table.go 612: Detected out-of-sync inserts, marking for resync actualRuleIDs=[]string{"", "", "", "", "wUHhoiAYhphO9Mso", "", "", "", "", "", "", "", ""} chainName="FORWARD" expectedRuleIDs=[]string{"wUHhoiAYhphO9Mso", "", "", "", "", "", "", "", "", "", "", "", ""} ipVersion=0x4 table="filter"
[calico-node-qvnwt calico-node] 2020-07-06 17:10:09.675 [WARNING][58] felix/table.go 612: Detected out-of-sync inserts, marking for resync actualRuleIDs=[]string{"", "", "", "", "wUHhoiAYhphO9Mso", "", "", "", "", "", "", "", ""} chainName="FORWARD" expectedRuleIDs=[]string{"wUHhoiAYhphO9Mso", "", "", "", "", "", "", "", "", "", "", "", ""} ipVersion=0x4 table="filter"
[calico-node-qvnwt calico-node] 2020-07-06 17:10:09.675 [WARNING][58] felix/table.go 612: Detected out-of-sync inserts, marking for resync actualRuleIDs=[]string{"", "", "tVnHkvAo15HuiPy0", "", ""} chainName="OUTPUT" expectedRuleIDs=[]string{"tVnHkvAo15HuiPy0", "", "", "", ""} ipVersion=0x4 table="filter"
```
## Steps to Reproduce (for bugs)
1. follow instructions at https://docs.projectcalico.org/getting-started/kubernetes/k3s/quickstart to install Calico v3.15.0
2. Only modifications I make are below kustomize patch

```yaml
metadata:
  name: calico-config
  namespace: kube-system
data:  
  cni_network_config: |-
    {  
      "name": "k8s-pod-network",
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "calico",
          "log_level": "info",
          "datastore_type": "kubernetes",
          "nodename": "__KUBERNETES_NODE_NAME__",
          "mtu": __CNI_MTU__,
          "ipam": {
              "type": "calico-ipam"
          },
          "container_settings": {
              "allow_ip_forwarding": true
          },
          "policy": {
              "type": "k8s"
          },
          "kubernetes": {
              "kubeconfig": "__KUBECONFIG_FILEPATH__"
          }
        },
        {
          "type": "portmap",
          "snat": true,
          "capabilities": {"portMappings": true}
        },
        {
          "type": "bandwidth",
          "capabilities": {"bandwidth": true}
        }
      ]                                                                                                                                                                                                                                                                                                                                       
    }  
       
---    
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: calico-node
  namespace: kube-system
spec:  
  template:
    spec:
      containers:
        - name: calico-node
          env:
            - name: FELIX_LOGSEVERITYSCREEN
              value: "Warning"

---         
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: calico-node                                                                                                                                                                                                                                                                                                                           
  namespace: kube-system
spec:       
  template:
    spec:
      containers:
      - name: calico-node
        env:
        - name: CALICO_IPV4POOL_CIDR
          value: "10.42.0.0/16"
        - name: IP_AUTODETECTION_METHOD
          value: "interface=eth1"
        - name: IP6_AUTODETECTION_METHOD
          value: "interface=eth1"
```

3. watch out-of-sync messages appear in logs

## Context
This is my first time using calico so unsure whether this is a regression. Applications running on the clusters seem fine

## Your Environment
<!--- Include as many relevant details about the environment you experienced the bug in -->
* v3.15.0
* k3s 1.17.7
* RHEL 7.8 (Linux p-nj2d-k8sw02 3.10.0-1127.el7.x86_64 #1 SMP Tue Feb 18 16:39:12 EST 2020 x86_64 x86_64 x86_64 GNU/Linux)
