### ISSUE TITLE
Feature: Mandatory wireguard

### ISSUE THREAD

**Issue by dragon2611** [projectcalico/calico#3760]
According to the docs https://docs.projectcalico.org/security/encrypt-cluster-pod-traffic if a node doesn't support wireguard traffic to/from it won't be encrypted.

I'd like the option to configure calico in such a way that if a node doesn't support wireguard then it's not able to send traffic to other nodes, I'd rather have the network break than send the traffic un-encrypted.

Also it looks like in IPIP mode BGP is made outside of the wireguard tunnel, although I don't actually know if BGP is needed with wireguard as traffic appeared to be routing even though I had a broken peer (it had an RFC1918 IP), Wireguard was working because when it reached out to the public IP of one of the other nodes wireguard updated the endpoint ip address (which it will do if a peer connects with a valid keypair)

Use case is I have a K3s cluster for personal use/learning that spans low end VPS hosts, therefore I want to encrypt all my cluster internal traffic as it's going over the internet rather than a private network.

**Comment by caseydavenport** [comment]
Yes, I agree this would be nice. We should have a way to say "If you can't send traffic over wireguard, then don't send it at all". 

@robbrockbank maybe you could comment on what would be required to make this happen?

**Comment by ffilippopoulos** [comment]
We are trying to have the same setup, use wireguard for all in cluster configuration and if wireguard is not running in a node we want the node to break and not send traffic (all our nodes are capable of wg, so for us it would be a matter of debugging why).
The only configuration that allowed us to "hack" such behaviour is to use `bird` as networking backend, but disable bgp `nodeToNodeMeshEnabled` config like:
```
apiVersion: crd.projectcalico.org/v1
kind: BGPConfiguration
metadata:
  name: default
spec:
  logSeverityScreen: Error
  nodeToNodeMeshEnabled: false
  asNumber: 64512
```
Then we make sure that we do not have any BGPPeer and thus calico cannot discover any peer and any route via bgp.
Ofc, we tune felix to use wireguard with a very simple configuration, like:
```
apiVersion: crd.projectcalico.org/v1
kind: FelixConfiguration
metadata:
  name: default
spec:
  ipipEnabled: true
  logSeverityScreen: Info
  reportingInterval: 0s
  wireguardEnabled: true
```

The result is that on each node we have the calico interfaces created for pods and the wg route table seems up to date to provide our routing. For example:
```
ip route show table 1 
10.4.0.0/24 dev wireguard.cali scope link 
10.4.0.1 dev wireguard.cali scope link 
10.4.1.0/24 dev wireguard.cali scope link 
10.4.1.1 dev wireguard.cali scope link 
10.4.4.0/24 dev wireguard.cali scope link 
10.4.4.1 dev wireguard.cali scope link 
10.4.6.0/24 dev wireguard.cali scope link 
10.4.6.1 dev wireguard.cali scope link 
10.4.7.0/24 dev wireguard.cali scope link 
10.4.7.1 dev wireguard.cali scope link 
throw 10.4.8.0/24 
```

That seems to cover the functionality described in this issue. Are we missing anything or trying to use calico in an unintended setup? @caseydavenport 
Finally, it would be nice to be able to just select wireguard as networking backend and not have to do any of the above ^
