### ISSUE TITLE
kubectl can get/describe pods, but kubectl logs and exec don't work

### ISSUE THREAD

**Issue by pengfeiwang-cn** [projectcalico/calico#3765]
for details:
https://github.com/kubernetes/kubernetes/issues/92929

**Comment by pengfeiwang-cn** [comment]
is there any one could help on this?

**Comment by pengfeiwang-cn** [comment]
I deploy the kubernetes cluster with these steps:
1. with virtualbox, create a network named "vboxnet0", 192.168.56.1/24 with dhcp enabled, address bound: 192.168.56.101 ~ 192.168.56.254.
2. create a new centos vm named "master", and configure two adapters, one NAT, the other Host-only Adapter with "vboxnet0".
3. clone "master" to "worker1"/"worker2"/"worker3", generate new MAC address for all networker adapters.
4. on master, install kubernetes with kubeadm
  - kubeadm init --pod-network-cidr=192.168.0.0/16 --apiserver-advertise-address=192.168.56.101 --control-plane-endpoint=192.168.56.101
  - configure kubectl with information returned by kubeadm init
  - kubectl create -f https://docs.projectcalico.org/manifests/tigera-operator.yaml
  - kubectl create -f https://docs.projectcalico.org/manifests/custom-resources.yaml
  - watch kubectl get pods -n calico-system, wait until every pods is running.
5. on worker1/worker2/worker3, kubeadm join the cluster: kubeadm join 192.168.56.101:6443 --token twc791.v9hwsw27s5w1wt43 --discovery-token-ca-cert-hash <ignored>
6. install calicoctl on master.
7. calicoctl delete ippools default-ipv4-ippool
8. create a new ip pool with calicoctl, yaml:
```yaml
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: test-ippool
spec:
  cidr: 192.168.56.128/25
  ipipMode: Never
  natOutgoing: false
```
9. create a Deployment with kubectl, yaml:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
spec:
  replicas: 3
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
        - name: test-container
          image: registry.cn-hangzhou.aliyuncs.com/google_containers/busybox
          imagePullPolicy: Never
          command: [ "sh", "-c"]
          args:
          - while true; do
              echo -en '\n';
              printenv MY_NODE_NAME MY_POD_NAME MY_POD_NAMESPACE;
              printenv MY_POD_IP MY_POD_SERVICE_ACCOUNT;
              sleep 10;
            done;
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app: busybox
```
10. kubectl get pods, pick one, try kubectl logs/exec <pod name> , they don't work.

> [root@master ~]# kubectl get pods
> NAME READY STATUS RESTARTS AGE
> busybox-7df9447df4-9mphh 1/1 Running 0 4s
> busybox-7df9447df4-bhxkt 1/1 Running 0 4s
> busybox-7df9447df4-hvxs4 1/1 Running 0 4s
> [root@master ~]# kubectl logs busybox-7df9447df4-bhxkt -v=9
> I0710 11:35:07.740944 4739 loader.go:375] Config loaded from file: /root/.kube/config
> I0710 11:35:07.757924 4739 round_trippers.go:423] curl -k -v -XGET -H "Accept: application/json, /" -H "User-Agent: kubectl/v1.18.5 (linux/amd64) kubernetes/e6503f8" 'https://192.168.56.101:6443/api/v1/namespaces/default/pods/busybox-7df9447df4-bhxkt'
> I0710 11:35:07.779576 4739 round_trippers.go:443] GET https://192.168.56.101:6443/api/v1/namespaces/default/pods/busybox-7df9447df4-bhxkt 200 OK in 21 milliseconds
> I0710 11:35:07.779619 4739 round_trippers.go:449] Response Headers:
> I0710 11:35:07.779642 4739 round_trippers.go:452] Cache-Control: no-cache, private
> I0710 11:35:07.779646 4739 round_trippers.go:452] Content-Type: application/json
> I0710 11:35:07.779649 4739 round_trippers.go:452] Date: Fri, 10 Jul 2020 03:35:07 GMT
> I0710 11:35:07.779766 4739 request.go:1068] Response Body: {"kind":"Pod","apiVersion":"v1","metadata":{"name":"busybox-7df9447df4-bhxkt","generateName":"busybox-7df9447df4-","namespace":"default","selfLink":"/api/v1/namespaces/default/pods/busybox-7df9447df4-bhxkt","uid":"6f650200-ca7b-491d-ac66-eefd8013cf3a","resourceVersion":"147093","creationTimestamp":"2020-07-10T03:34:45Z","labels":{"app":"busybox","pod-template-hash":"7df9447df4"},"annotations":{"cni.projectcalico.org/podIP":"192.168.56.192/32","cni.projectcalico.org/podIPs":"192.168.56.192/32"},"ownerReferences":[{"apiVersion":"apps/v1","kind":"ReplicaSet","name":"busybox-7df9447df4","uid":"219d4294-5d38-4640-80a1-4fa6b1f20d39","controller":true,"blockOwnerDeletion":true}],"managedFields":[{"manager":"kube-controller-manager","operation":"Update","apiVersion":"v1","time":"2020-07-10T03:34:45Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:generateName":{},"f:labels":{".":{},"f:app":{},"f:pod-template-hash":{}},"f:ownerReferences":{".":{},"k:{"uid":"219d4294-5d38-4640-80a1-4fa6b1f20d39"}":{".":{},"f:apiVersion":{},"f:blockOwnerDeletion":{},"f:controller":{},"f:kind":{},"f:name":{},"f:uid":{}}}},"f:spec":{"f:affinity":{".":{},"f:podAntiAffinity":{".":{},"f:requiredDuringSchedulingIgnoredDuringExecution":{}}},"f:containers":{"k:{"name":"test-container"}":{".":{},"f:args":{},"f:command":{},"f:env":{".":{},"k:{"name":"MY_NODE_NAME"}":{".":{},"f:name":{},"f:valueFrom":{".":{},"f:fieldRef":{".":{},"f:apiVersion":{},"f:fieldPath":{}}}},"k:{"name":"MY_POD_IP"}":{".":{},"f:name":{},"f:valueFrom":{".":{},"f:fieldRef":{".":{},"f:apiVersion":{},"f:fieldPath":{}}}},"k:{"name":"MY_POD_NAME"}":{".":{},"f:name":{},"f:valueFrom":{".":{},"f:fieldRef":{".":{},"f:apiVersion":{},"f:fieldPath":{}}}},"k:{"name":"MY_POD_NAMESPACE"}":{".":{},"f:name":{},"f:valueFrom":{".":{},"f:fieldRef":{".":{},"f:apiVersion":{},"f:fieldPath":{}}}},"k:{"name":"MY_POD_SERVICE_ACCOUNT"}":{".":{},"f:name":{},"f:valueFrom":{".":{},"f:fieldRef":{".":{},"f:apiVersion":{},"f:fieldPath":{}}}}},"f:image":{},"f:imagePullPolicy":{},"f:name":{},"f:resources":{},"f:terminationMessagePath":{},"f:terminationMessagePolicy":{}}},"f:dnsPolicy":{},"f:enableServiceLinks":{},"f:restartPolicy":{},"f:schedulerName":{},"f:securityContext":{},"f:terminationGracePeriodSeconds":{}}}},{"manager":"calico","operation":"Update","apiVersion":"v1","time":"2020-07-10T03:34:47Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:cni.projectcalico.org/podIP":{},"f:cni.projectcalico.org/podIPs":{}}}}},{"manager":"kubelet","operation":"Update","apiVersion":"v1","time":"2020-07-10T03:34:47Z","fieldsType":"FieldsV1","fieldsV1":{"f:status":{"f:conditions":{"k:{"type":"ContainersReady"}":{".":{},"f:lastProbeTime":{},"f:lastTransitionTime":{},"f:status":{},"f:type":{}},"k:{"type":"Initialized"}":{".":{},"f:lastProbeTime":{},"f:lastTransitionTime":{},"f:status":{},"f:type":{}},"k:{"type":"Ready"}":{".":{},"f:lastProbeTime":{},"f:lastTransitionTime":{},"f:status":{},"f:type":{}}},"f:containerStatuses":{},"f:hostIP":{},"f:phase":{},"f:podIP":{},"f:podIPs":{".":{},"k:{"ip":"192.168.56.192"}":{".":{},"f:ip":{}}},"f:startTime":{}}}}]},"spec":{"volumes":[{"name":"default-token-42hcm","secret":{"secretName":"default-token-42hcm","defaultMode":420}}],"containers":[{"name":"test-container","image":"registry.cn-hangzhou.aliyuncs.com/google_containers/busybox","command":["sh","-c"],"args":["while true; do echo -en '\n'; printenv MY_NODE_NAME MY_POD_NAME MY_POD_NAMESPACE; printenv MY_POD_IP MY_POD_SERVICE_ACCOUNT; sleep 100; done;"],"env":[{"name":"MY_NODE_NAME","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"spec.nodeName"}}},{"name":"MY_POD_NAME","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"metadata.name"}}},{"name":"MY_POD_NAMESPACE","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"metadata.namespace"}}},{"name":"MY_POD_IP","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"status.podIP"}}},{"name":"MY_POD_SERVICE_ACCOUNT","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"spec.serviceAccountName"}}}],"resources":{},"volumeMounts":[{"name":"default-token-42hcm","readOnly":true,"mountPath":"/var/run/secrets/kubernetes.io/serviceaccount"}],"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"Never"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","serviceAccountName":"default","serviceAccount":"default","nodeName":"worker2","securityContext":{},"affinity":{"podAntiAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":[{"labelSelector":{"matchLabels":{"app":"busybox"}},"topologyKey":"kubernetes.io/hostname"}]}},"schedulerName":"default-scheduler","tolerations":[{"key":"node.kubernetes.io/not-ready","operator":"Exists","effect":"NoExecute","tolerationSeconds":300},{"key":"node.kubernetes.io/unreachable","operator":"Exists","effect":"NoExecute","tolerationSeconds":300}],"priority":0,"enableServiceLinks":true},"status":{"phase":"Running","conditions":[{"type":"Initialized","status":"True","lastProbeTime":null,"lastTransitionTime":"2020-07-10T03:34:45Z"},{"type":"Ready","status":"True","lastProbeTime":null,"lastTransitionTime":"2020-07-10T03:34:47Z"},{"type":"ContainersReady","status":"True","lastProbeTime":null,"lastTransitionTime":"2020-07-10T03:34:47Z"},{"type":"PodScheduled","status":"True","lastProbeTime":null,"lastTransitionTime":"2020-07-10T03:34:45Z"}],"hostIP":"10.0.2.15","podIP":"192.168.56.192","podIPs":[{"ip":"192.168.56.192"}],"startTime":"2020-07-10T03:34:45Z","containerStatuses":[{"name":"test-container","state":{"running":{"startedAt":"2020-07-10T03:34:47Z"}},"lastState":{},"ready":true,"restartCount":0,"image":"registry.cn-hangzhou.aliyuncs.com/google_containers/busybox:latest","imageID":"docker://sha256:e7d168d7db455c45f4d0315d89dbd18806df4784f803c3cc99f8a2e250585b5b","containerID":"docker://44156823052feea07d2806f3cf7351e6a148c0efe6498e8e184951440390aac8","started":true}],"qosClass":"BestEffort"}}
> I0710 11:35:07.788337 4739 round_trippers.go:423] curl -k -v -XGET -H "Accept: application/json, /" -H "User-Agent: kubectl/v1.18.5 (linux/amd64) kubernetes/e6503f8" 'https://192.168.56.101:6443/api/v1/namespaces/default/pods/busybox-7df9447df4-bhxkt/log'
> I0710 11:35:07.974163 4739 round_trippers.go:443] GET https://192.168.56.101:6443/api/v1/namespaces/default/pods/busybox-7df9447df4-bhxkt/log 404 Not Found in 185 milliseconds
> I0710 11:35:07.974176 4739 round_trippers.go:449] Response Headers:
> I0710 11:35:07.974180 4739 round_trippers.go:452] Date: Fri, 10 Jul 2020 03:35:07 GMT
> I0710 11:35:07.974183 4739 round_trippers.go:452] Cache-Control: no-cache, private
> I0710 11:35:07.974186 4739 round_trippers.go:452] Content-Type: application/json
> I0710 11:35:07.974189 4739 round_trippers.go:452] Content-Length: 262
> I0710 11:35:07.974203 4739 request.go:1068] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the server could not find the requested resource ( pods/log busybox-7df9447df4-bhxkt)","reason":"NotFound","details":{"name":"busybox-7df9447df4-bhxkt","kind":"pods/log"},"code":404}
> I0710 11:35:07.976356 4739 helpers.go:216] server response object: [{
> "metadata": {},
> "status": "Failure",
> "message": "the server could not find the requested resource ( pods/log busybox-7df9447df4-bhxkt)",
> "reason": "NotFound",
> "details": {
> "name": "busybox-7df9447df4-bhxkt",
> "kind": "pods/log"
> },
> "code": 404
> }]
> F0710 11:35:07.976390 4739 helpers.go:115] Error from server (NotFound): the server could not find the requested resource ( pods/log busybox-7df9447df4-bhxkt)

Thanks.
