### ISSUE TITLE
NetworkPolicy: Allow all ports except specific one

### ISSUE THREAD

**Issue by vrathore18** [projectcalico/calico#3786]
Here is the sample NetworkPolicy which allows connection to pods that have a label hello and allow port connection on 53 TCP and UDP and block all ports.

How I can Make this to allow all ports and block 53 TCP and UDP (egress).

```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: foo-allow-to-hello
spec:
  policyTypes:
  - Egress
  podSelector:
    matchLabels:
      app: foo
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: hello
  - ports:
    - port: 53
      protocol: TCP
    - port: 53
      protocol: UDP
```
