### ISSUE TITLE
Log action in network policy blocks the traffic

### ISSUE THREAD

**Issue by smartproductlabs** [projectcalico/calico#3801]
A Calico network policy with action "Log" (only Log) drops the traffic. There are no other actions / policies present.

## Expected Behavior

When policy with action "Log" is created, the packets should be logged that matches the filter. The Log policies are created to debug other Deny/Allow policies created on the Calico network. 

## Current Behavior

The Node has only one policy defined with action "Log" (copied below). This is blocking all the traffic to the Pod with label **app.kubernetes.io/name == 'telcoservice-5gudm'**

```
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: telco-logger
  namespace: default
spec:
  ingress:
  - action: Log
    destination: {}
    source: {}
  order: 3000
  selector: projectcalico.org/orchestrator == 'k8s' && app.kubernetes.io/name == 'telcoservice-5gudm'
  types:
  - Ingress
```

## Possible Solution

Log policy should not block the traffic and allow the traffic
Or
Documentation on the page should be corrected

## Steps to Reproduce (for bugs)

1. Apply "Log" only network policy on a Pod
2. Send traffic to the Pod
3. Traffic packet drop is logged

## Context

We were testing Calico network policies and it all worked well. A debug policy added to Log some specific traffic was left on the cluster by mistake and we see that it is blocking the traffic. 

## Your Environment

* Calico version
Client Version:    v3.8.5
Cluster Version:   v3.8.5
Cluster Type:      k8s

* Orchestrator version (e.g. kubernetes, mesos, rkt):
Kubernetes "v1.16.4"

* Operating System and version:
CentOS Linux release 7.7.1908 (Core)

* Link to your project (optional):
