### ISSUE TITLE
Whitelisted port 80 but still not able to curl  

### ISSUE THREAD

**Issue by vrathore18** [projectcalico/calico#3802]
I raised this bug but Kubernetes but they said calico will handle this:
https://github.com/kubernetes/kubernetes/issues/93111#issuecomment-659105277

This is my network policy. I am applying in EKS using calico plugin
```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: net-document
  namespace: default
spec:
  policyTypes:
  - Egress
  - Ingress
  podSelector:
    matchLabels:
      app: test-document
  ingress:
  - {}
  egress:
  - to:
    ports:
    - port: 53
      protocol: TCP
    - port: 53
      protocol: UDP
    - port: 5000
      protocol: TCP
    - port: 5000
      protocol: UDP
    - port: 27017
      protocol: TCP
    - port: 443
      protocol: TCP
    - port: 443
      protocol: UDP
    - port: 6379
      protocol: TCP
    - port: 8080
      protocol: TCP
    - port: 80
      protocol: TCP
    - port: 80
      protocol: UDP
    - port: 5672
      protocol: TCP
    - port: 943
      protocol: TCP
    - port: 1194
      protocol: TCP
```
But when I go inside the pod and do
`curl http://169.254.169.254/latest/meta-data/`
I am getting timeout error. It should run as I have allowed port 80.
