### ISSUE TITLE
External Traffic Policy:  Cluster and Local is not working

### ISSUE THREAD

**Issue by eselvam** [projectcalico/calico#3815]
I have calico policy installed on kubernetes cluster. 

created nginx deployment in default namespace
created service my-dep in same namespace exposed as node port
however it is using External Traffic Policy: Cluster which I changed to Local
But I could not access it using nodeip:nodeport outside of the cluster

```
Service: Nodeport.
Name:                     my-dep
Namespace:                default
Labels:                   app=my-dep
Annotations:              <none>
Selector:                 app=my-dep
Type:                     NodePort
IP:                       10.110.22.112
Port:                     <unset>  80/TCP
TargetPort:               80/TCP
NodePort:                 <unset>  32620/TCP
Endpoints:                10.244.215.65:80
Session Affinity:         None
External Traffic Policy:  Local
Events:                   <none>
```

created one more pod to check the connectivity using busybox.
created networkpolicy with below yaml file however I still could not connect it.
```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: access-nginx
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: my-dep
  ingress:
    - from:
      - podSelector:
          matchLabels:
            run: access
```

It may be basic question but kindly help me here.
