### ISSUE TITLE
Cluster I/O timeout when using Calico CNI.

### ISSUE THREAD

**Issue by johnray21216** [projectcalico/calico#3835]
## Expected Behavior
Sonobuoy Pod should be able to run multiple instances of the E2E test in an IPV6 Kubernetes Cluster Environment. 

## Current Behavior
When sonobuoy is ran for the first time, sonobuoy is able to start the e2e test. When run the second time (or if the sonobuoy pod is scheduled on THE SAME node as the previous successful instance), it would produce an i/o timeout
when connecting to the service IP from the sonobuoy pod. 

## Possible Solution
None

## Steps to Reproduce (for bugs)
1. Configure Cluster and Calico for IPV6.
2. Copy $HOME/.kube/config file from the master node to a client machine (a machine that is outside of the cluster but is able to communicate with the cluster)
3. Download sonobuoy (v0.17.2) on client machine.
4. Push sonobuoy images to private repository.
4. Execute sonobuoy run with the `--kubeconfig` flag and using the config file that was copied from the master node to the client machine.
 

## Context
We are currently trying to build an air-gapped ipv6 kubernetes cluster environment. We are using sonobuoy to do end-to-end testing on our clusters. 

## Your Environment
* Calico version - 0.3.14
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes 1.16.3
* Operating System and version: Centos 7

We have setup an air-gapped IPV6 cluster environment composed of 3 nodes (1 master , 2 worker) and also a private repository and a client machine. The private repository holds the images used for the cluster and the client machine executes the sonobuoy test remotely outside the cluster. All of the machines are connected in the same network and is not connected to the internet. We have downloaded the images on an online machine and transferred it to the cluster and the private repository.

We already escalated this issue with sonobuoy and we have already dismissed the idea that the issue is with the executable or the deployment. We have tried a CNI called KindNet and it was able to run sonobuoy multiple instances with no issues. We have also tried an IPv4 setup and we have confirmed that it is working as expected.

I hope the community would be able to help us with this issue.

**Comment by caseydavenport** [comment]
Hm, this is interesting. I'm not aware of any reason that this would be Sonobuoy specific. Are you seeing issues with any other pods in the cluster connecting to services?

could you share the manifest you're using to run sonobuoy?

**Comment by aaasolo** [comment]
Hello, @caseydavenport. I will be replying in behalf of @johnray21216 .

The i/o timeout issue when connecting to the Kubernetes service IP is not encountered by other pods in the cluster.
As stated by @johnray21216 , there is no timeout issue in the sonobuoy pod when the test is executed for the first time. It only appears in the succeeding executions of the test.

Shown below is the sonobuoy manifest used,
```
---
apiVersion: v1
kind: Namespace
metadata:
  name: sonobuoy
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    component: sonobuoy
  name: sonobuoy-serviceaccount
  namespace: sonobuoy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    component: sonobuoy
    namespace: sonobuoy
  name: sonobuoy-serviceaccount-sonobuoy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sonobuoy-serviceaccount-sonobuoy
subjects:
- kind: ServiceAccount
  name: sonobuoy-serviceaccount
  namespace: sonobuoy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    component: sonobuoy
    namespace: sonobuoy
  name: sonobuoy-serviceaccount-sonobuoy
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '/metrics'
  - '/logs'
  - '/logs/*'
  verbs:
  - 'get'
---
apiVersion: v1
data:
  config.json: |
    {"Description":"DEFAULT","UUID":"5235698a-3c3f-46bd-934c-7a57a7a9547c","Version":"v0.17.2","ResultsDir":"/tmp/sonobuoy","Resources":["apiservices","certificatesigningrequests","clusterrolebindings","clusterroles","componentstatuses","configmaps","controllerrevisions","cronjobs","customresourcedefinitions","daemonsets","deployments","endpoints","ingresses","jobs","leases","limitranges","mutatingwebhookconfigurations","namespaces","networkpolicies","nodes","persistentvolumeclaims","persistentvolumes","poddisruptionbudgets","pods","podlogs","podsecuritypolicies","podtemplates","priorityclasses","replicasets","replicationcontrollers","resourcequotas","rolebindings","roles","servergroups","serverversion","serviceaccounts","services","statefulsets","storageclasses","validatingwebhookconfigurations","volumeattachments"],"Filters":{"Namespaces":".*","LabelSelector":""},"Limits":{"PodLogs":{"Namespaces":"","SonobuoyNamespace":true,"FieldSelectors":[],"LabelSelector":"","Previous":false,"SinceSeconds":null,"SinceTime":null,"Timestamps":false,"TailLines":null,"LimitBytes":null,"LimitSize":"","LimitTime":""}},"QPS":30,"Burst":50,"Server":{"bindaddress":"0.0.0.0","bindport":8080,"advertiseaddress":"","timeoutseconds":10800},"Plugins":[{"name":"e2e"},{"name":"systemd-logs"}],"PluginSearchPath":["./plugins.d","/etc/sonobuoy/plugins.d","~/sonobuoy/plugins.d"],"Namespace":"sonobuoy","WorkerImage":"abk-opm:5000/sonobuoy:v0.17.2","Always":"IfNotPresent","ImagePullSecrets":"","ProgressUpdatesPort":"8099"}
kind: ConfigMap
metadata:
  labels:
    component: sonobuoy
  name: sonobuoy-config-cm
  namespace: sonobuoy
---
apiVersion: v1
data:
  plugin-0.yaml: |
    sonobuoy-config:
      driver: Job
      plugin-name: e2e
      result-format: junit
    spec:
      command:
      - /run_e2e.sh
      env:
      - name: E2E_FOCUS
        value: \[Conformance\]
      - name: E2E_SKIP
        value: \[Disruptive\]|NoExecuteTaintManager
      - name: E2E_PARALLEL
        value: "1"
      - name: E2E_USE_GO_RUNNER
        value: "true"
      - name: E2E_EXTRA_ARGS
        value: --progress-report-url=http://localhost:8099/progress
      image: abk-opm:5000/conformance:v1.16.3
      imagePullPolicy: Always
      name: e2e
      resources: {}
      volumeMounts:
      - mountPath: /tmp/results
        name: results
  plugin-1.yaml: |
    sonobuoy-config:
      driver: DaemonSet
      plugin-name: systemd-logs
      result-format: raw
    spec:
      command:
      - /bin/sh
      - -c
      - /get_systemd_logs.sh && while true; do echo "Sleeping for 1h to avoid daemonset
        restart"; sleep 3600; done
      env:
      - name: CHROOT_DIR
        value: /node
      - name: RESULTS_DIR
        value: /tmp/results
      - name: NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      image: abk-opm:5000/systemd-logs:v0.3
      imagePullPolicy: Always
      name: systemd-logs
      resources: {}
      securityContext:
        privileged: true
      volumeMounts:
      - mountPath: /tmp/results
        name: results
      - mountPath: /node
        name: root
kind: ConfigMap
metadata:
  labels:
    component: sonobuoy
  name: sonobuoy-plugins-cm
  namespace: sonobuoy
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    component: sonobuoy
    run: sonobuoy-master
    tier: analysis
  name: sonobuoy
  namespace: sonobuoy
spec:
  containers:
  - env:
    - name: SONOBUOY_ADVERTISE_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    image: abk-opm:5000/sonobuoy:v0.17.2
    imagePullPolicy: Always
    name: kube-sonobuoy
    command: ["/sonobuoy"]
    args: ["aggregator", "--no-exit", "--logtostderr", "-v", "8"]
    volumeMounts:
    - mountPath: /etc/sonobuoy
      name: sonobuoy-config-volume
    - mountPath: /plugins.d
      name: sonobuoy-plugins-volume
    - mountPath: /tmp/sonobuoy
      name: output-volume
  restartPolicy: Never
  serviceAccountName: sonobuoy-serviceaccount
  tolerations:
  - key: "kubernetes.io/e2e-evict-taint-key"
    operator: "Exists"
  volumes:
  - configMap:
      name: sonobuoy-config-cm
    name: sonobuoy-config-volume
  - configMap:
      name: sonobuoy-plugins-cm
    name: sonobuoy-plugins-volume
  - emptyDir: {}
    name: output-volume
---
apiVersion: v1
kind: Service
metadata:
  labels:
    component: sonobuoy
    run: sonobuoy-master
  name: sonobuoy-master
  namespace: sonobuoy
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: sonobuoy-master
  type: ClusterIP
```
