### ISSUE TITLE
calico namespaceselector question

### ISSUE THREAD

**Issue by iamruhua** [projectcalico/calico#3849]
I setup calico with kubesphere on aws eks.
Used calicoctl to create  networkpolicy:
```
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: deny-user-namespace
  namespace: 2048-game
spec:
  ingress:
  - action: Allow
    protocol: TCP
    source:
      namespaceSelector: 'systemCreated=="true"'
```

namespace:
```
Name:         default
Labels:       kubesphere.io/namespace=default
              kubesphere.io/workspace=system-workspace
              systemCreated=true
Annotations:  <none>
Status:       Active

No resource quota.

No LimitRange resource.
```

and then, i created a nginx deployment in 2048-game namespace.
Then curl busybox in default namespace.

When I execute curl from busybox container in defualt namespace, the traffic is blocked.

Can anyone help? I am expecting the curl traffic to be able to reach nginx, since i have allowed tcp traffic from systemCreated=true namespaces
