### ISSUE TITLE
Cannot manage to Deny connection based on namespaceSelector

### ISSUE THREAD

**Issue by thibaudio** [projectcalico/calico#3860]
Hi!

I'm trying to deny access to `kube-system` to all namespace with a specific label, on AWS EKS.  
There's also a NetworkPolicy inside the namespace to restrict access to AWS metadata.

The network policy inside `kube-system`: 
```
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  annotations:
  name: kube-system-network-policy
  namespace: kube-system
spec:
  egress:
  - action: Allow
  ingress:
  - action: Deny
    destination:
      selector: all()
    source:
      namespaceSelector: "sample-label-key == 'sample-label-value'"
      selector: all()
  - action: Allow
  order: 499
```

namespace from which we want to restrict network:
```
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sample-label-key: sample-label-value
  name: sample-namespace
```

Existing network policy inside namespace:
```
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: sample-namespace-network-policy
  namespace: sample-namespace
spec:
  egress:
  - action: Deny
    destination:
      nets:
      - 169.254.169.254/32
  - action: Allow
  order: 500
```

When I spawn a pod inside `sample-network` I can curl an endpoint in `kube-system`.
Any idea what I did wrong?

Thanks for your help.

**Comment by thibaudio** [comment]
Side note, I also tried to achieve this by Denying egress in the `sample-namespace`:
```
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: sample-namespace-network-policy
  namespace: sample-namespace
spec:
  egress:
  - action: Deny
    destination:
      nets:
      - 169.254.169.254/32
  - action: Deny
    destination:
      namespaceSelector: "projectcalico.org/name == 'kube-system'"
  - action: Allow
  order: 500
```
