### ISSUE TITLE
Calico pods in calico pools outside of podCIDR in Kubernetes cannot access clusterIP services when networkpolicy is applied

### ISSUE THREAD

**Issue by rsparulek** [projectcalico/calico#4004]
Calico pods in calico pools outside of podCIDR in Kubernetes cannot services when Kubernetes network policy is applied. It is observed that when calico pods which are outside of podCIDR subnet cannot access pods back ending a cluster IP service which are present on the other host. We are using Calico version v3.11.1. When pods are present within the podCIDR subnet; they can access pods behind services on another host.

## Expected Behavior
It is expected that pods created in any Calico IP pools must be able to access service pods across hosts when K8S ingress/egress network policies are configured which allow traffic.

## Current Behavior
Current behaviour is that Calico pods in ip-pool subnet same as the podCIDR can communicate with services across hosts. When we create additional IP pools which do not overlap with the podCIDR configured in K8S cluster; packets start getting dropped when trying to access the service when network policies are present. This is an example of the K8S network policy present on the cluster

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-network-policy
  namespace: my-ns
spec:
  podSelector:
    matchLabels:
      app: test-app
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          allow: yes
```

## Possible Solution
Calico network policy enforcement must not drop packets which are not originating from the ip pool subnet same as podCIDR. Calico pods in subnets other than podCIDR must also be allowed to access the service when appropriate network policies are present.

## Steps to Reproduce (for bugs)
1) Create a calico IP pool which is outside of podCIDR subnet
2) Now create a pod in this new Calico ip pool say on host A
3) Create a nginx cluster IP service and the pod back-ending this service must be present only on host B (non local host)
4) Also, configure a Kubernetes network policy on the K8S cluster as listed above which only has ingress namespace selector
5) Now perform a `curl -v <cluster ip>:80` to the nginx clusterIP and see that the curl fails.
6) Also, if possible use the following IP pool configuration spec for the IP pool

```
spec:
  blockSize: 26
  cidr: <non pod CIDR overlapping subnet>/16
  ipipMode: Always
  natOutgoing: true
  nodeSelector: all()
  vxlanMode: Never
```

## Context
With this issue; calico pods in subnets or ip pools outside of podCIDR cannot access services across hosts when K8S network policies are configured on the host.

## Your Environment
* Calico version: v3.11.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes
* Operating System and version: Centos 7 3.10.0-1062.18.1.el7.x86_64
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

```
calicoctl version
Client Version:    v3.11.1
Git commit:        6c04a83
Cluster Version:   v3.11.1
Cluster Type:      k8s,bgp,kubeadm,kdd
```
