### ISSUE TITLE
Document recommended RBAC permissions 

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico#402]
We should document what RBAC controls Calico needs when running under k8s using etcd.

We also need to supply an RBAC policy for Calico when using the Calico self-hosted manifests for the etcd and kubernetes datastore drivers.

**Comment by caseydavenport** [comment]
@djosborne you recently created these for openshift-ansible, right?  Can I assign this to you?

**Comment by caseydavenport** [comment]
There are really two sets of RBAC required here - one for full etcd mode, and one for the Kubernetes datastore driver (which is policy-only at the moment).

For etcd, we don't need much:

- NetworkPolicy (read)

For the k8s datastore driver, we need a bit more:

- NetworkPolicy (read)
- Namespace (read)
- Pod (read / write)
- ThirdPartyResource (read / write)

There's a WIP ClusterRole defined here: https://github.com/djosborne/openshift-ansible/blob/fdd4f6492d577b4e9e1287a0fc9d6cbb6220dff6/roles/calico_master/templates/calico-policy-controller.yml.j2

**Comment by caseydavenport** [comment]
Bumped to P0 since RBAC is being enabled by default: https://github.com/kubernetes/kubeadm/issues/143

**Comment by djosborne** [comment]
As a starting point, here are [the RBAC roles I created for apiserver access in openshift](https://github.com/djosborne/openshift-ansible/blob/fdd4f6492d577b4e9e1287a0fc9d6cbb6220dff6/roles/calico_master/templates/calico-policy-controller.yml.j2):

```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: calico
  namespace: kube-system
---
kind: ClusterRole
apiVersion: v1
metadata:
  name: calico
  namespace: kube-system
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
  - apiGroups:
      - extensions
    resources:
      - networkpolicies
    verbs:
      - list
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - list
---
apiVersion: v1
kind: ClusterRoleBinding
metadata:
  name: calico
roleRef:
  name: calico
subjects:
- kind: SystemUser
  name: kube-system:calico
- kind: ServiceAccount
  name: calico
  namespace: kube-system
userNames:
  - system:serviceaccount:kube-system:calico
```
