### ISSUE TITLE
Breaking one node (stoping kubelet) brings calico pods on other nodes down

### ISSUE THREAD

**Issue by michalzxc** [projectcalico/calico#4118]
I am having 5 nodes running calico, when shut down one of them (systemctl stop kubelet), networking collapses across the cluster
```
2020-10-21 16:13:38.306 [INFO][9] watchercache.go 297: Sending synced update ListRoot="/calico/ipam/v2/assignment/"
2020-10-21 16:13:38.306 [INFO][9] watchersyncer.go 209: Received InSync event from one of the watcher caches
2020-10-21 16:13:38.338 [INFO][9] watchercache.go 297: Sending synced update ListRoot="/calico/resources/v3/projectcalico.org/profiles"
2020-10-21 16:13:38.345 [INFO][9] watchersyncer.go 209: Received InSync event from one of the watcher caches
2020-10-21 16:13:39.040 [INFO][9] watchercache.go 297: Sending synced update ListRoot="/calico/resources/v3/projectcalico.org/workloadendpoints"
2020-10-21 16:13:39.040 [INFO][9] watchersyncer.go 209: Received InSync event from one of the watcher caches
2020-10-21 16:13:39.040 [INFO][9] watchersyncer.go 221: All watchers have sync'd data - sending data and final sync
2020-10-21 16:13:39.040 [INFO][9] watchersyncer.go 127: Sending status update Status=in-sync
2020-10-21 16:13:39.051 [INFO][9] cache.go 239: Received status update message from datastore. status=in-sync
2020-10-21 16:14:05.503 [INFO][9] health.go 196: Overall health status changed newStatus=&health.HealthReport{Live:true, Ready:true}
2020-10-21 16:14:09.776 [INFO][9] rebalance.go 77: Calculated new connection limit. newLimit=300 numNodes=5 numTyphas=3 reason="configured lower limit" thread="k8s-poll"
2020-10-21 16:14:09.777 [INFO][9] sync_server.go 449: New target number of connections currentNum=0 newMax=300 oldMax=10000 thread="numConnsGov"
2020-10-21 16:15:06.559 [FATAL][9] daemon.go 439: Received SIGTERM, shutting down
```
Calico pods are being killed by liveness check, on other nodes:
```
~❯ kubectl --namespace calico-system get pods -o wide
NAME                                       READY   STATUS             RESTARTS   AGE   IP               NODE                           NOMINATED NODE   READINESS GATES
calico-kube-controllers-5687f44fd5-796qw   1/1     Running            0          62d   172.22.173.126   master1cluster0dc.ad.dice.fm   <none>           <none>
calico-node-2dnr4                          1/1     Running            0          11d   192.168.66.50    master0cluster0dc.ad.dice.fm   <none>           <none>
calico-node-6fh92                          1/1     Running            8          11d   192.168.66.101   worker1cluster0dc.ad.dice.fm   <none>           <none>
calico-node-jd8h4                          1/1     Running            0          11d   192.168.66.51    master1cluster0dc.ad.dice.fm   <none>           <none>
calico-node-m5gvt                          0/1     CrashLoopBackOff   41         11d   192.168.66.100   worker0cluster0dc.ad.dice.fm   <none>           <none>
calico-node-x75wq                          0/1     CrashLoopBackOff   33         11d   192.168.66.102   worker2cluster0dc.ad.dice.fm   <none>           <none>
calico-typha-576d7cd989-5fgk4              0/1     Running            31         11d   192.168.66.102   worker2cluster0dc.ad.dice.fm   <none>           <none>
calico-typha-576d7cd989-72s2d              1/1     Running            4          11d   192.168.66.101   worker1cluster0dc.ad.dice.fm   <none>           <none>
calico-typha-576d7cd989-fhnfs              1/1     Running            0          11d   192.168.66.51    master1cluster0dc.ad.dice.fm   <none>           <none>
calico-typha-576d7cd989-grrv6              0/1     CrashLoopBackOff   40         11d   192.168.66.100   worker0cluster0dc.ad.dice.fm   <none>           <none>
````

The node I shut down was worker1cluster0dc.ad.dice.fm, and it didn't refresh its status
But calico pods on other nodes started collapsing

```Events:
  Type     Reason     Age                  From     Message
  ----     ------     ----                 ----     -------
  Normal   Created    37m                  kubelet  Created container calico-node
  Normal   Started    37m                  kubelet  Started container calico-node
  Warning  Unhealthy  37m (x4 over 39m)    kubelet  Readiness probe failed: command timed out
  Normal   Killing    36m (x2 over 38m)    kubelet  Container calico-node failed liveness probe, will be restarted
  Warning  Unhealthy  35m (x9 over 38m)    kubelet  Readiness probe errored: rpc error: code = Unknown desc = container is not created or running
  Warning  Unhealthy  14m (x26 over 62m)   kubelet  Liveness probe failed: Get http://localhost:9099/liveness: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  Normal   Pulled     8m53s (x7 over 38m)  kubelet  Container image "docker.io/calico/node:v3.15.1" already present on machine
  Warning  BackOff    4m3s (x91 over 31m)  kubelet  Back-off restarting failed container
```

## Steps to Reproduce (for bugs)
SSH to one of nodes, and do ```systemctl stop kubelet```

## Your Environment
* Calico version
3.15
* Orchestrator version (e.g. kubernetes, mesos, rkt):
Kubernetes v1.18.8
* Operating System and version:
Fedora Server 32

**Comment by michalzxc** [comment]
After rebooting worker1cluster0dc.ad.dice.fm it will all recover, but until then both worker0cluster0dc.ad.dice.fm and worker2cluster0dc.ad.dice.fm are without network, with calico crashing

**Comment by michalzxc** [comment]
https://pastebin.com/UGdexnFY - logs tail from all calico namespace

**Comment by michalzxc** [comment]
After restarting stopped node, I had to delete calico pod from it, because it went into "complete" status

```
~❯ kubectl --namespace calico-system get pods -o wide
NAME                                       READY   STATUS             RESTARTS   AGE   IP               NODE                           NOMINATED NODE   READINESS GATES
calico-kube-controllers-5687f44fd5-796qw   1/1     Running            0          62d   172.22.173.126   master1cluster0dc.ad.dice.fm   <none>           <none>
calico-node-2dnr4                          1/1     Running            0          12d   192.168.66.50    master0cluster0dc.ad.dice.fm   <none>           <none>
calico-node-6fh92                          0/1     Completed          8          12d   192.168.66.101   worker1cluster0dc.ad.dice.fm   <none>           <none>
calico-node-jd8h4                          1/1     Running            0          12d   192.168.66.51    master1cluster0dc.ad.dice.fm   <none>           <none>
calico-node-m5gvt                          0/1     CrashLoopBackOff   49         12d   192.168.66.100   worker0cluster0dc.ad.dice.fm   <none>           <none>
calico-node-x75wq                          1/1     Running            38         12d   192.168.66.102   worker2cluster0dc.ad.dice.fm   <none>           <none>
calico-typha-576d7cd989-5fgk4              1/1     Running            35         12d   192.168.66.102   worker2cluster0dc.ad.dice.fm   <none>           <none>
calico-typha-576d7cd989-72s2d              1/1     Running            4          12d   192.168.66.101   worker1cluster0dc.ad.dice.fm   <none>           <none>
calico-typha-576d7cd989-fhnfs              1/1     Running            0          12d   192.168.66.51    master1cluster0dc.ad.dice.fm   <none>           <none>
calico-typha-576d7cd989-grrv6              0/1     CrashLoopBackOff   46         12d   192.168.66.100   worker0cluster0dc.ad.dice.fm   <none>           <none>
~❯ kubectl --namespace calico-system delete pod calico-node-6fh92
pod "calico-node-6fh92" deleted
```

Wait 5-10 minutes
```
~❯ kubectl --namespace calico-system get pods -o wide
NAME                                       READY   STATUS    RESTARTS   AGE     IP               NODE                           NOMINATED NODE   READINESS GATES
calico-kube-controllers-5687f44fd5-796qw   1/1     Running   0          62d     172.22.173.126   master1cluster0dc.ad.dice.fm   <none>           <none>
calico-node-2dnr4                          1/1     Running   0          12d     192.168.66.50    master0cluster0dc.ad.dice.fm   <none>           <none>
calico-node-jd8h4                          1/1     Running   0          12d     192.168.66.51    master1cluster0dc.ad.dice.fm   <none>           <none>
calico-node-pk5gw                          1/1     Running   0          6m13s   192.168.66.101   worker1cluster0dc.ad.dice.fm   <none>           <none>
calico-node-r5tx9                          1/1     Running   3          5m10s   192.168.66.100   worker0cluster0dc.ad.dice.fm   <none>           <none>
calico-node-x75wq                          1/1     Running   38         12d     192.168.66.102   worker2cluster0dc.ad.dice.fm   <none>           <none>
calico-typha-576d7cd989-5fgk4              1/1     Running   35         12d     192.168.66.102   worker2cluster0dc.ad.dice.fm   <none>           <none>
calico-typha-576d7cd989-72s2d              1/1     Running   6          12d     192.168.66.101   worker1cluster0dc.ad.dice.fm   <none>           <none>
calico-typha-576d7cd989-fhnfs              1/1     Running   0          12d     192.168.66.51    master1cluster0dc.ad.dice.fm   <none>           <none>
calico-typha-576d7cd989-wv9hf              1/1     Running   0          84s     192.168.66.50    master0cluster0dc.ad.dice.fm   <none>           <none>
```
And all is happy again

**Comment by michalzxc** [comment]
Just to confirm, before starting again worker1cluster0dc.ad.dice.fm  I left it for almost a hour, and calico pods were crashing all the time without any improvement with time

**Comment by michalzxc** [comment]
This is my calicoconf.yaml
```
# This section includes base Calico installation configuration.
# For more information, see: https://docs.projectcalico.org/v3.15/reference/installation/api#operator.tigera.io/v1.Installation
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  # Configures Calico networking.
  calicoNetwork:
    # Note: The ipPools section cannot be modified post-install.
    ipPools:
    - blockSize: 26
      cidr: 172.20.0.0/14
      encapsulation: VXLANCrossSubnet
      natOutgoing: Enabled
      nodeSelector: all()
    nodeAddressAutodetectionV4:
      canReach: 192.168.66.1
```

**Comment by michalzxc** [comment]
192.168.66.1 is GW, on local LAN, nothing to do with worker1

**Comment by michalzxc** [comment]
This is how I installed operator:
```
kubectl create -f https://docs.projectcalico.org/manifests/tigera-operator.yaml
```

**Comment by michalzxc** [comment]
Guessing there, but maybe it just needs more time to build new topology or something before liveness will kill it?

**Comment by michalzxc** [comment]
Trying edit deamonset by hand:
```
        livenessProbe:
          failureThreshold: 30
          httpGet:
            host: localhost
            path: /liveness
            port: 9099
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
```

Shutting down one node, and... it seems to be doing a trick

How to make Operator create deamonset with:

failureThreshold: 30 and timeoutSeconds: 3 ?

**Comment by michalzxc** [comment]
Said it to early :/
One got restarted so far, but it is still much better:
```
~❯ kubectl --namespace calico-system get pods --watch -o wide
NAME                                       READY   STATUS    RESTARTS   AGE   IP               NODE                           NOMINATED NODE   READINESS GATES
calico-kube-controllers-5687f44fd5-796qw   1/1     Running   0          62d   172.22.173.126   master1cluster0dc.ad.dice.fm   <none>           <none>
calico-node-jjg28                          1/1     Running   0          62m   192.168.66.101   worker1cluster0dc.ad.dice.fm   <none>           <none>
calico-node-ld7fr                          1/1     Running   0          62m   192.168.66.100   worker0cluster0dc.ad.dice.fm   <none>           <none>
calico-node-vw87b                          1/1     Running   0          60m   192.168.66.50    master0cluster0dc.ad.dice.fm   <none>           <none>
calico-node-x7jjc                          1/1     Running   0          63m   192.168.66.102   worker2cluster0dc.ad.dice.fm   <none>           <none>
calico-node-zts74                          1/1     Running   0          64m   192.168.66.51    master1cluster0dc.ad.dice.fm   <none>           <none>
calico-typha-576d7cd989-5fgk4              1/1     Running   65         12d   192.168.66.102   worker2cluster0dc.ad.dice.fm   <none>           <none>
calico-typha-576d7cd989-72s2d              1/1     Running   6          12d   192.168.66.101   worker1cluster0dc.ad.dice.fm   <none>           <none>
calico-typha-576d7cd989-fhnfs              1/1     Running   0          12d   192.168.66.51    master1cluster0dc.ad.dice.fm   <none>           <none>
calico-typha-576d7cd989-wv9hf              1/1     Running   0          17h   192.168.66.50    master0cluster0dc.ad.dice.fm   <none>           <none>




calico-node-ld7fr                          0/1     Running   0          67m   192.168.66.100   worker0cluster0dc.ad.dice.fm   <none>           <none>
calico-node-ld7fr                          0/1     Running   1          67m   192.168.66.100   worker0cluster0dc.ad.dice.fm   <none>           <none>
calico-node-ld7fr                          1/1     Running   1          67m   192.168.66.100   worker0cluster0dc.ad.dice.fm   <none>           <none>
```
Logs:
https://paste.ubuntu.com/p/NtKyS6RhV5/

**Comment by michalzxc** [comment]
More restarts now, maybe I need treshold like 60 and 6s timeout?
```
~❯ kubectl --namespace calico-system get pods --watch -o wide
NAME                                       READY   STATUS    RESTARTS   AGE   IP               NODE                           NOMINATED NODE   READINESS GATES
calico-kube-controllers-5687f44fd5-796qw   1/1     Running   0          62d   172.22.173.126   master1cluster0dc.ad.dice.fm   <none>           <none>
calico-node-jjg28                          1/1     Running   0          62m   192.168.66.101   worker1cluster0dc.ad.dice.fm   <none>           <none>
calico-node-ld7fr                          1/1     Running   0          62m   192.168.66.100   worker0cluster0dc.ad.dice.fm   <none>           <none>
calico-node-vw87b                          1/1     Running   0          60m   192.168.66.50    master0cluster0dc.ad.dice.fm   <none>           <none>
calico-node-x7jjc                          1/1     Running   0          63m   192.168.66.102   worker2cluster0dc.ad.dice.fm   <none>           <none>
calico-node-zts74                          1/1     Running   0          64m   192.168.66.51    master1cluster0dc.ad.dice.fm   <none>           <none>
calico-typha-576d7cd989-5fgk4              1/1     Running   65         12d   192.168.66.102   worker2cluster0dc.ad.dice.fm   <none>           <none>
calico-typha-576d7cd989-72s2d              1/1     Running   6          12d   192.168.66.101   worker1cluster0dc.ad.dice.fm   <none>           <none>
calico-typha-576d7cd989-fhnfs              1/1     Running   0          12d   192.168.66.51    master1cluster0dc.ad.dice.fm   <none>           <none>
calico-typha-576d7cd989-wv9hf              1/1     Running   0          17h   192.168.66.50    master0cluster0dc.ad.dice.fm   <none>           <none>




calico-node-ld7fr                          0/1     Running   0          67m   192.168.66.100   worker0cluster0dc.ad.dice.fm   <none>           <none>
calico-node-ld7fr                          0/1     Running   1          67m   192.168.66.100   worker0cluster0dc.ad.dice.fm   <none>           <none>
calico-node-ld7fr                          1/1     Running   1          67m   192.168.66.100   worker0cluster0dc.ad.dice.fm   <none>           <none>
calico-node-ld7fr                          0/1     Running   1          72m   192.168.66.100   worker0cluster0dc.ad.dice.fm   <none>           <none>
calico-node-ld7fr                          0/1     Running   2          73m   192.168.66.100   worker0cluster0dc.ad.dice.fm   <none>           <none>
calico-node-ld7fr                          1/1     Running   2          73m   192.168.66.100   worker0cluster0dc.ad.dice.fm   <none>           <none>
calico-node-ld7fr                          0/1     Running   2          74m   192.168.66.100   worker0cluster0dc.ad.dice.fm   <none>           <none>
````
Still much better than what happened before, most of the cluster do have network

**Comment by michalzxc** [comment]
Actually it did work, operator overwritten my deamonset and this pot reverted to default liveness

**Comment by michalzxc** [comment]
So, how to make operator to change deamonset liveness to:
```
        livenessProbe:
          failureThreshold: 30
          httpGet:
            host: localhost
            path: /liveness
            port: 9099
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
```
?

**Comment by caseydavenport** [comment]
I'm surprised that the failureThreshold and timeoutSeconds actually _solve_ the issue. More than likely it's just delaying it (it will now need to fail 30 times in order for Kubernetes to restart the container). 

In your calico/node logs, I don't see anything indicating why the liveness probe is failing (I'd expect a log from `health.go` with the latest status). In fact, I don't think Felix generally will ever report liveness as "false" in order to avoid this sort of thing.

**Comment by michalzxc** [comment]
Any node, I was restarting one of the workers (not masters), in above example I shared logs from it was "worker1cluster0dc.ad.dice.fm", but it happens with every one of them

This is 5 nodes bare metal clusters. 3 workers nodes, 2 master nodes
```
~❯ kubectl get nodes
NAME                           STATUS   ROLES    AGE   VERSION
master0cluster0dc.ad.dice.fm   Ready    master   90d   v1.18.6
master1cluster0dc.ad.dice.fm   Ready    master   90d   v1.18.6
worker0cluster0dc.ad.dice.fm   Ready    worker   84d   v1.18.6
worker1cluster0dc.ad.dice.fm   Ready    worker   84d   v1.18.6
worker2cluster0dc.ad.dice.fm   Ready    worker   63d   v1.18.6
```

**Comment by michalzxc** [comment]
All webhooks deployments, ingress server, coredns, and vault and operators are running on masters

**Comment by fasaxc** [comment]
How did you deploy k8s? kubeadm/kops/rancher/....?

**Comment by michalzxc** [comment]
kubeadm, it is bare metal cluster running on dedicated hosts from ovh
```
TEMPLATE=/etc/kubernetes/kubeadm-config.yaml
if [ ! -f $TEMPLATE ]; then
    echo "[RUN] Create: $TEMPLATE"
    mkdir -p $(dirname $TEMPLATE)
    cat << EOF > $TEMPLATE
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: stable
controlPlaneEndpoint: "${LOAD_BALANCER_DNS}:6443"
etcd:
    external:
        endpoints:
        - https://192.168.66.10:${ETCD_PORT}
        - https://192.168.66.11:${ETCD_PORT}
        - https://192.168.66.12:${ETCD_PORT}
        caFile: /etc/kubernetes/pki/etcd/ca.crt
        certFile: /etc/kubernetes/pki/apiserver-etcd-client.crt
        keyFile: /etc/kubernetes/pki/apiserver-etcd-client.key
apiServer:
  extraArgs:
    advertise-address: ${IP}
scheduler:
  extraVolumes:
  - name: "k8s-certs"
    hostPath: "/etc/kubernetes/pki"
    mountPath: "/etc/kubernetes/pki"
    readOnly: true
networking:
  serviceSubnet: "172.24.0.0/16"
  podSubnet: "172.20.0.0/14"
  dnsDomain: "cluster.local"
EOF
fi
chmod 744 ${TEMPLATE}
```

**Comment by michalzxc** [comment]
ETCDs are running on separate hosts from masters

**Comment by fasaxc** [comment]
Are you using host endpoint policy at all?

**Comment by michalzxc** [comment]
I am not, all my calico config is:
```
# This section includes base Calico installation configuration.
# For more information, see: https://docs.projectcalico.org/v3.15/reference/installation/api#operator.tigera.io/v1.Installation
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  # Configures Calico networking.
  calicoNetwork:
    # Note: The ipPools section cannot be modified post-install.
    ipPools:
    - blockSize: 26
      cidr: 172.20.0.0/14
      encapsulation: VXLANCrossSubnet
      natOutgoing: Enabled
      nodeSelector: all()
    nodeAddressAutodetectionV4:
      canReach: 192.168.66.1
```

**Comment by michalzxc** [comment]
I also have kube-vip as LB before masters, this is what LOAD_BALANCER_DNS targets (this is also what is used by users kubectl)
```
localPeer:
  id: ${ID}
  address: ${IPADDR}
  port: 10000
remotePeers:
- id: ${PEER1_ID}
  address: ${PEER1_IPADDR}
  port: 10000
- id: ${PEER2_ID}
  address: ${PEER2_IPADDR}
  port: 10000
vip: 192.168.66.2${cluster}
gratuitousARP: true
singleNode: false
startAsLeader: ${IS_LEADER}
interface: ${INTERFACE}
loadBalancers:
- name: API Server Load Balancer
  type: tcp
  port: ${APISERVER_DEST_PORT}
  bindToVip: false
  backends:
  - port: ${APISERVER_SRC_PORT}
    address: ${HOST1_ADDRESS}
  - port: ${APISERVER_SRC_PORT}
    address: ${HOST2_ADDRESS}
```
```
TEMPLATE=/etc/kubernetes/manifests/kube-vip${cluster}.yaml
    echo "[RUN] Create: $TEMPLATE"
    mkdir -p $(dirname $TEMPLATE)
    cat << EOF > $TEMPLATE
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: kube-vip
  namespace: kube-system
spec:
  containers:
  - command:
    - /kube-vip
    - start
    - -c
    - /vip.yaml
    image: 'plndr/kube-vip:0.1.6'
    name: kube-vip
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - SYS_TIME
        - NET_RAW
    volumeMounts:
    - mountPath: /vip.yaml
      name: config
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kube-vip/config${cluster}.yaml
    name: config
status: {}
EOF
chmod 644 ${TEMPLATE}
```
