### ISSUE TITLE
Cannot access external ip addresses/network

### ISSUE THREAD

**Issue by jenwirth** [projectcalico/calico#4134]
I am unable to access IP addresses outside the cluster. There's no problem accessing internal pods/service/ingresses.

```shell
$ kubectl run -i -t busybox --rm --image=busybox:latest --restart=Never 
/ # wget http://172.217.22.132
Connecting to 172.217.22.132 (172.217.22.132:80)
wget: can't connect to remote host (172.217.22.132): No route to host

```

## Expected Behaviour
Should be able to access external hosts

## Your Environment
* Calico version 3.16.4
* k8s 1.19.3 (new installation)
* Operating System and version: Centos 8 (8.2)

The calico-node pods are showing the following warning. I am not sure if it is related

```
[WARNING][44] felix/vxlan_mgr.go 467: Failed to set vxlan tunnel device MTU error=invalid argument 
```

**Comment by fasaxc** [comment]
Might be an issue, I can't tell without seeing more of the log.  There should be an Info log above that that tells you what MTU it is trying to set.

**Comment by fasaxc** [comment]
Some things to check: does your IP pool have nat outgoing enabled?
```
calicoctl get ippool -o yaml
```
should show you.

Do you have other firewall solutions enabled such as firewalld?  Possible that they're blocking the traffic.

**Comment by jenwirth** [comment]
Hi,

Some things that i've tried:
- disabled firewall (did not help)
- accessing IPs on the private network (does not work either)
- using the non-operator and the operator install (same results on both. This also allowed be to test tunnel and vxlan, both have the same problem)

All internal traffic works, nodeports work as well. 

The operator yaml is 

```yaml
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  calicoNetwork:
    ipPools: # immutable
      - blockSize: 26
        cidr: "{{podSubnet}}"
        encapsulation: VXLANCrossSubnet
        natOutgoing: Enabled
        nodeSelector: all()
    nodeAddressAutodetectionV4:
      interface: "(ens10|enp7s0)"
```

The ip routing table on one of the nodes is:

```shell
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         _gateway        0.0.0.0         UG    100    0        0 eth0
10.0.0.0        10.0.0.1        255.255.255.0   UG    0      0        0 enp7s0
10.0.0.1        0.0.0.0         255.255.255.255 UH    0      0        0 enp7s0
_gateway        0.0.0.0         255.255.255.255 UH    100    0        0 eth0
192.168.25.64   192.168.25.64   255.255.255.192 UG    0      0        0 vxlan.calico
192.168.77.64   192.168.77.64   255.255.255.192 UG    0      0        0 vxlan.calico
192.168.148.128 192.168.148.128 255.255.255.192 UG    0      0        0 vxlan.calico
192.168.169.192 192.168.169.192 255.255.255.192 UG    0      0        0 vxlan.calico
192.168.205.0   192.168.205.0   255.255.255.192 UG    0      0        0 vxlan.calico
192.168.234.0   192.168.234.0   255.255.255.192 UG    0      0        0 vxlan.calico

```

It is trying to set the MTU to :

```
felix/vxlan_mgr.go 465: VXLAN device MTU needs to be updated device="vxlan.calico" new=1410 old=1400   
```
