### ISSUE TITLE
[BUG] serviceExternalIPs should also work with ClusterIP.

### ISSUE THREAD

**Issue by Cellebyte** [projectcalico/calico#4151]
## Expected Behavior
* When I run a service with `protocol: UDP` on an `serviceExternalIP` as a `LoadBalancer` it gets advertised.

## Current Behavior
* When I run it it gets only advertised when it is a Service with `protocol: TCP`.

## Possible Solution
* Allow to run a ClusterIP Service on an externalIP.
* This allow also mixed exposure of e.G. SCTP, UDP and TCP over one service definition.
* Allow binding two LBs together via Annotation, one LB for UDP and one for TCP.
* MetalLB is doing something similar. By defining a unique annotation.

## Steps to Reproduce (for bugs)
1. create a service type `LoadBalancer` which references a port with `protocol: UDP`
2. try to see if its being advertised on your router.
3. It will not appear

## Context
I want to run my DNS service over `protocol: TCP` and `protocol: UDP` on an `externalServiceIP`.
Currently that is only possible via defining a TCP endpoint and UDP is not exposed when I do that.
## Your Environment

* Calico version: calico/kube-controllers:v3.16.4
* Orchestrator version: k8s v1.19.2
* Operating System and version: CentOS 8.2

**Comment by mgleung** [comment]
Hi @Cellebyte, thanks for bringing this to our attention. Just wanted to ask a few clarifying questions. What does the yaml for the service you're using look like? Based on the context section it seems that you are trying to set up a TCP and UDP service for the same workload. Does UDP work if it is the only service?

**Comment by Cellebyte** [comment]
@mgleung when having a Service Type Loadbalancer with only Protocol UDP it does not work at all so the exposure on the nodes as an externalIP works as expected but bird is not announcing my IPs to the world. Also defining a clusterIP Service with an externalIP creates the right local listening but it is also not announced to the world. It gets only announced when its LoadBalancer with TCP and externalIPs set.

**Comment by caseydavenport** [comment]
@Cellebyte it would also be useful if you could share what your BGPConfiguration resources look like

**Comment by Cellebyte** [comment]
@caseydavenport this is my BGP Configuration.

```yaml
---
apiVersion: crd.projectcalico.org/v1
kind: BGPConfiguration
metadata:
  name: default
spec:
  logSeverityScreen: Info
  nodeToNodeMeshEnabled: false
  asNumber: {{ k8s.bgp.as }}
  serviceExternalIPs:
  - cidr: "{{ k8s.v4.service.external.cidr }}"
  - cidr: "{{ k8s.v6.service.external.cidr }}"
  serviceClusterIPs:
  - cidr: "{{ k8s.v4.service.cidr }}"
  - cidr: "{{ k8s.v6.service.cidr }}"
  communities:
  - name: bgp-cluster-community
    value: "{{ k8s.bgp.as }}:{{ k8s.bgp.community }}"
  prefixAdvertisements:
  - cidr: "{{ k8s.v4.service.external.cidr }}"
    communities:
    - bgp-cluster-community
  - cidr: "{{ k8s.v6.service.external.cidr }}"
    communities:
    - bgp-cluster-community
  - cidr: "{{ k8s.v4.service.cidr }}"
    communities:
    - bgp-cluster-community
  - cidr: "{{ k8s.v6.service.cidr }}"
    communities:
    - bgp-cluster-community
  - cidr: "{{ k8s.v4.pod.cidr }}"
    communities:
    - bgp-cluster-community
  - cidr: "{{ k8s.v6.pod.cidr }}"
    communities:
    - bgp-cluster-community
```
