### ISSUE TITLE
NodePort Not Working in Conjunction with Network Policies

### ISSUE THREAD

**Issue by reddog335** [projectcalico/calico#4171]
I need to isolate the network traffic for each individual namespace in a v1.18 K8 cluster.  I have created a deny all ingress traffic network policy and an allow all ingress traffic from the Ingress Controller namespace network policy for each application namespace.  This allows all application ingress traffic external to the cluster to reach applications internal to the cluster via Layer 7 but restricts and internal namespace to namespace traffic and it works like a champ.  The issue is with external cluster traffic attempting to reach internal cluster applications via TCP Layer 4 - NodePort.  Adding the network policies breaks NodePort.  I created a GlobalNetworkPolicy to allow the ingress host NodePort traffic (https://docs.projectcalico.org/security/kubernetes-node-ports) but it still does not work.  Any ideas?

## Expected Behavior
**curl http://myapp1.example.com:30000**  - will reach the application behind the NodePort service (30000-->80).  This works prior to applying the network policies but not after.

## Current Behavior
**curl http://myapp1.example.com:30000**  - cannot reach the application behind the NodePort service (30000-->80)

## Steps to Reproduce (for bugs)

1. Create namespace app1
2. Deploy a simple webapp with a NodePort service NodePort 
```
apiVersion: v1
kind: Service
  name: app1
  namespace: app1
spec:
  ports:
  - nodePort: 30000
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: app1
  type: NodePort
```
3. Verify you can reach the application
**curl http://myapp1.example.com:30000**
4. Apply the deny-from-other-namespaces network policy to the app1 namespace
```
    kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      namespace: app1
      name: deny-from-other-namespaces
    spec:
      podSelector:
        matchLabels:
      ingress:
      - from:
        - podSelector: {}
```
5. Apply the allow-from-ingress-namespace
```
    kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      namespace: app1
      name: allow-from-ingress-namespace
    spec:
      podSelector:
        matchLabels:
      ingress:
      - from:
        - namespaceSelector:
            matchLabels:
              app: ingress-controller
```
6. Apply the allow-cluster-np-internal-ingress-only GlobalNetworkPolicy
```
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: allow-cluster-np-internal-ingress-only
spec:
  order: 20
  preDNAT: true
  applyOnForward: true
  ingress:
    - action: Allow
      source:
        nets: [1.2.3.0/23, 100.100.0.0/16]
    - action: Deny
  selector: has(kubernetes-host)
```
7. Verify you can reach the application - you will not be able to.
**curl http://myapp1.example.com:30000**
## Context
Isolating internal namespace to namespace network traffic with network policies breaks ingress using NodePort.  We need external ingress into the cluster for non-Layer 7 traffic.

## Your Environment

* Calico version: Calico v3.11.2
* Kubernetes version: v1.18 (baremetal cluster)
* Operating System and version: VMware Photon OS 3.0
CRI and version: containerd  v1.3.4

**Comment by caseydavenport** [comment]
```
  ingress:
    - action: Allow
      source:
        nets: [1.2.3.0/23, 100.100.0.0/16]
    - action: Deny
  selector: has(kubernetes-host)
```

In policy rule example, what are those nets? Are they your node IP ranges or something else?

**Comment by reddog335** [comment]
Hey @caseydavenport,  The 1.2.3.0/23 is the IP range for our nodes and the 100.100.0.0/16 is for our pods.  I initially tried it with just the IP range for our nodes (1.2.3.0/23) but once that didn't worked I added the pod IP range to see if that helped.

**Comment by caseydavenport** [comment]
Hm, so the traffic that will be hitting your NodePort services pre-DNAT will have a source IP address of whatever originated the traffic - in your case is that a pod and/or node? Or is it something outside the cluster?

**Comment by reddog335** [comment]
@caseydavenport - the traffic hitting the NodePort is ingress traffic coming from applications with source IP addresses outside of our cluster.   The goal is to prevent any east/west traffic between namespaces within the cluster but allow all external ingress via Layer 7 through the Ingress Controller and Layer 4 via Nodeport.

**Comment by caseydavenport** [comment]
So I think for that you'd want something like this:

- Policy in namespace X which allows only from namespace X ("allow from same namespace")
- Policy in namespace X which allows from ingress namespace (assumes that your ingress pods are NOT host networked)

^ This is what you already have, and will get you the prevent east/west between namespaces except for the ingress namespace behavior. But of course, as you discovered, doesn't allow traffic that enters via a NodePort, since that traffic is SNAT'd before it reaches the pod.

I think you might be looking for a policy like this one in order to allow traffic to your NodePort:

```
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: allow-cluster-np-internal-ingress-only
spec:
  order: 20
  preDNAT: true
  applyOnForward: true
  ingress
    - action: Allow
      protocol: TCP
      destination:
        selector: has(kubernetes-host)
        ports: [30000]
  selector: has(kubernetes-host)
```

This of course assumes you have host endpoints for each of your kubernetes nodes. It should allow all traffic to your service that uses the node port `30000`. If you want to restrict who is able to access the nodeport, you can add a `source` section to limit to certain selectors or IP addresses. 

Give that a shot and let me know if it works - I might have missed something in your set up :)

**Comment by reddog335** [comment]
@caseydavenport - Thank you for the suggestion.  I removed my entire previous setup and started from scratch.  

1. Deployed two test applications:  App1 using L7 Ingress and App2 using NodePort on 30000
2. Verified both applications were reachable - success
2. Applied your suggested deny all Network Policy
```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: vcs
  name: deny-from-other-namespaces
spec:
  podSelector:
    matchLabels:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          asi: vcs
```
3.  Tested both applications - both unreachable as expected.
4. Applied the Allow Ingress from the Ingress Controller namespace Network Policy 
```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: vcs
  name: allow-from-ingress-namespace
spec:
  podSelector:
    matchLabels:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          app: tanzu-system-ingress
```
5. Tested both applications - App1 using L7 Ingress worked as expected and App2 using NodePort on 30000 unreachable as expected.
6.  Created a host endpoint for each of my worker nodes
```
apiVersion: projectcalico.org/v3
kind: HostEndpoint
metadata:
  name: k8-tkg-prod-md-0-948f59b86-pbb4s-eth0
  labels:
    kubernetes-host: ingress
spec:
  interfaceName: eth0
  node: k8-tkg-prod-md-0-948f59b86-pbb4s
```
7. Created the GlobalNetworkPolicy
```
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: allow-cluster-np-internal-ingress-only
spec:
  order: 20
  preDNAT: true
  applyOnForward: true
  ingress:
    - action: Allow
      protocol: TCP
      destination:
        selector: has(kubernetes-host)
        ports: [30000]
  selector: has(kubernetes-host)
```
8. Tested App2 - App2 using NodePort on 30000 is still unreachable :-(

I really had high hopes this was going to work.

**Comment by caseydavenport** [comment]
@reddog335 I think I know what is going on, and, I believe it is a bug in the example in our docs.

Specifically, the issue is that the `destination.selector` field needs to resolve to a set of IP addresses in order to be enforced. However, the HostEndpoints you've created (and the one in the docs) do not have the `expectedIPs` field set.

You can test this by modifying your host endpoints to have the `expectedIPs` field set with the addresses of `eth0` that you intend for nodeport traffic to hit. If that gets traffic flowing, which I expect it will, then I think we've found the culprit. 

Once that is working, you can either ensure your HEPs have the right addresses, or you might want to look at enabling automatic host endpoints so that you don't need to create them by hand: https://docs.projectcalico.org/archive/v3.16/security/kubernetes-nodes#automatic-host-endpoints

**Comment by reddog335** [comment]
@caseydavenport - Thank you for the update.  I added the expectedIps to my HEPs and it still did not work.

```
apiVersion: projectcalico.org/v3
kind: HostEndpoint
metadata:
  name: k8-tkg-cya-lab2-md-0-8d88f59d6-rzxvg-eth0
  labels:
    kubernetes-host: ingress
spec:
  interfaceName: eth0
  node: k8-tkg-cya-lab2-md-0-8d88f59d6-rzxvg
  expectedIPs:
  - 10.<redacted>
---
apiVersion: projectcalico.org/v3
kind: HostEndpoint
metadata:
  name: k8-tkg-cya-lab2-md-0-8d88f59d6-t5drm-eth0
  labels:
    kubernetes-host: ingress
spec:
  interfaceName: eth0
  node: k8-tkg-cya-lab2-md-0-8d88f59d6-t5drm
  expectedIPs:
  - 10.<redacted>
---
apiVersion: projectcalico.org/v3
kind: HostEndpoint
metadata:
  name: k8-tkg-cya-lab2-md-0-8d88f59d6-xzvf6-eth0
  labels:
    kubernetes-host: ingress
spec:
  interfaceName: eth0
  node: k8-tkg-cya-lab2-md-0-8d88f59d6-xzvf6
  expectedIPs:
  - 10.<redacted>
```
After investigating further, the source IP address of the ingress traffic shows up as a Pod network address (100.111.191.###), not the worker node address.  I was able to get around this by changing ipipMode from Always to Never in the default-ipv4-ippool ippool.  After making this change, I was able to get nodePort working with a native K8 Network Policy so I no longer required the GlobalNetworkPolicy and HEPs.

```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: vcs
  name: allow-from-node-port
spec:
  podSelector: {}
  ingress:
  - from:
    - ipBlock:
        cidr: 10.0.0.0/8
    ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 8080
```
