### ISSUE TITLE
bird: Netlink: Network is down, The new node cannot work

### ISSUE THREAD

**Issue by dotbalo** [projectcalico/calico#4273]
I have a k8s cluster, which worked normally before. Then several nodes have been added recently, the bird connection is normal, and the Calico Pod is also normal. But Calico's Pod log keeps printing: **bird: Netlink: Network is down**. At this time, the new node cannot ping the Pod's IP on other nodes.
I mentioned an [issue](https://github.com/projectcalico/calico/issues/3134) before, but this issue has not been resolved. I have also tried some ideas to solve this problem, but it has never been solved. Now I have no idea to solve this problem, because there is no abnormal log, only: **bird: Netlink: Network is down.**

## Expected Behavior
I want to solve the problem of bird: Netlink: Network is down. Then the new node can ping Pods on other nodes.

## Current Behavior
I have a cluster as follows:
````
[root@k8s-master01 ~]# kubectl get node
NAME                   STATUS   ROLES    AGE     VERSION
k8s-master01      Ready    master   584d    v1.18.9
k8s-master02      Ready    master   340d    v1.18.9
k8s-master03      Ready    master   584d    v1.18.9
k8s-node01        Ready    node     584d    v1.18.9
k8s-node02        Ready    node     584d    v1.18.9
k8s-node236-230   Ready    <none>   2d21h   v1.18.9
k8s-node236-231   Ready    <none>   2d20h   v1.18.9
````
k8s-node236-230 and k8s-node236-231 are new nodes.
Bird Status:
````
[root@k8s-node236-230 ~]# netstat -lantup |grep bird
tcp        0      0 0.0.0.0:179             0.0.0.0:*               LISTEN      4839/bird           
tcp        0      0 192.168.0.230:50649    192.168.0.178:179      ESTABLISHED 4839/bird           
tcp        0      0 192.168.0.230:51321    192.168.0.179:179      ESTABLISHED 4839/bird           
tcp        0      0 192.168.0.230:60227    192.168.0.175:179      ESTABLISHED 4839/bird           
tcp        0      0 192.168.0.230:39239    192.168.0.177:179      ESTABLISHED 4839/bird           
tcp        0      0 192.168.0.230:179      192.168.0.231:50469    ESTABLISHED 4839/bird           
tcp        0      0 192.168.0.230:33471    192.168.0.176:179      ESTABLISHED 4839/bird
````
k8s-master01:
````
[root@k8s-master01 ~]# netstat -lantup |grep bird
tcp        0      0 0.0.0.0:179             0.0.0.0:*               LISTEN      22731/bird          
tcp        0      0 192.168.0.177:179      192.168.0.179:49993    ESTABLISHED 22731/bird          
tcp        0      0 192.168.0.177:179      192.168.0.230:39239    ESTABLISHED 22731/bird          
tcp        0      0 192.168.0.177:56867    192.168.0.175:179      ESTABLISHED 22731/bird          
tcp        0      0 192.168.0.177:35795    192.168.0.176:179      ESTABLISHED 22731/bird          
tcp        0      0 192.168.0.177:179      192.168.0.178:47913    ESTABLISHED 22731/bird          
tcp        0      0 192.168.0.177:179      192.168.0.231:52831    ESTABLISHED 22731/bird
````
It all looks normal.
But the new node does not have any routing information._The previous node is normal_.
````
[root@k8s-node236-230 ~]# ip route
default via 192.168.0.254 dev ens192 
192.168.0.0/24 dev ens192 proto kernel scope link src 192.168.0.230 
169.254.0.0/16 dev ens192 scope link metric 1002 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown 
blackhole 192.242.27.128/26 proto bird
````
Calico Status:
````
[root@k8s-master01 ~]# calicoctl node status
Calico process is running.

IPv4 BGP status
+----------------+-------------------+-------+------------+-------------+
|  PEER ADDRESS  |     PEER TYPE     | STATE |   SINCE    |    INFO     |
+----------------+-------------------+-------+------------+-------------+
| 192.168.0.178 | node-to-node mesh | up    | 2020-12-18 | Established |
| 192.168.0.179 | node-to-node mesh | up    | 2020-11-03 | Established |
| 192.168.0.175 | node-to-node mesh | up    | 2020-11-03 | Established |
| 192.168.0.176 | node-to-node mesh | up    | 2020-11-03 | Established |
| 192.168.0.230 | node-to-node mesh | up    | 2020-12-18 | Established |
| 192.168.0.231 | node-to-node mesh | up    | 2020-12-18 | Established |
+----------------+-------------------+-------+------------+-------------+

IPv6 BGP status
No IPv6 peers found.
````
NetworkManager:
````
[root@k8s-master01 ~]# systemctl status NetworkManager
● NetworkManager.service - Network Manager
   Loaded: loaded (/usr/lib/systemd/system/NetworkManager.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:NetworkManager(8)
````

## Possible Solution
1. Change IPIP to BGP:   Not solved.
2. Add IP_AUTODETECTION_METHOD configuration： Not solved.
3. Update Calico: Not solved.

## Context
My newly added node cannot communicate with the pods of other nodes, hoping to solve this problem.

## Your Environment
* Calico version:  v3.16.3
* Orchestrator version: Kubernetes
* Operating System and version:  Old Node: CentOS Linux release 7.6.1810 (Core)     
* Operating System and version:  New Node: CentOS Linux release 7.9.2009 (Core)  **Just executed yum update**

**Comment by caseydavenport** [comment]
@dotbalo could you share the log file from the calico/node pod that is emitting these logs? That would be useful to see. 

It would also be useful to see what might be occuring to the interface on that node.

i.e., run the following command on the problematic node to see what is happening to that interface:

```
ip monitor dev <CALICO_INTERFACE>
```

Where <CALICO_INTERFACE> is eth0, ens0, etc. Whatever Calico is using for BGP.

**Comment by dotbalo** [comment]
@caseydavenport Thank you very much for your answer.
This is the result of the new node **ip monitor**:
````
[root@k8s-node236-230 ~]# ip monitor dev ens192
192.168.0.254 lladdr xxxx:00:01:ec REACHABLE
192.168.0.178 lladdr xxxx:f2:7d:a1 PROBE
192.168.0.178 lladdr xxxx:f2:7d:a1 REACHABLE
192.168.0.175 lladdr xxxx:f3:1c:f0 REACHABLE
192.168.0.177 lladdr xxxx:f3:65:d0 STALE
192.168.0.231 lladdr xxxx:6d:0b:df PROBE
192.168.0.231 lladdr xxxx:6d:0b:df REACHABLE
192.168.0.175 lladdr xxxx:f3:1c:f0 STALE
192.168.0.178 lladdr xxxx:f2:7d:a1 STALE
192.168.0.129 lladdr xxxx:b3:2f:0c PROBE
192.168.0.129 lladdr xxxx:b3:2f:0c REACHABLE
192.168.0.176 lladdr xxxx:f3:1b:ac STALE
192.168.0.231 lladdr xxxx:6d:0b:df STALE
192.168.0.177 lladdr xxxx:f3:65:d0 PROBE
192.168.0.177 lladdr xxxx:f3:65:d0 REACHABLE
192.168.0.176 lladdr xxxx:f3:1b:ac PROBE
192.168.0.176 lladdr xxxx:f3:1b:ac REACHABLE
192.168.0.178 lladdr xxxx:f2:7d:a1 PROBE
192.168.0.178 lladdr xxxx:f2:7d:a1 REACHABLE
192.168.0.129 lladdr xxxx:b3:2f:0c STALE
192.168.0.175 lladdr xxxx:f3:1c:f0 REACHABLE
192.168.0.231 lladdr xxxx:6d:0b:df PROBE
192.168.0.231 lladdr xxxx:6d:0b:df REACHABLE
192.168.0.177 lladdr xxxx:f3:65:d0 STALE
192.168.0.178 lladdr xxxx:f2:7d:a1 STALE
192.168.0.175 lladdr xxxx:f3:1c:f0 STALE
192.168.0.231 lladdr xxxx:6d:0b:df STALE
192.168.0.177 lladdr xxxx:f3:65:d0 PROBE
192.168.0.177 lladdr xxxx:f3:65:d0 REACHABLE
192.168.0.176 lladdr xxxx:f3:1b:ac STALE
192.168.0.178 lladdr xxxx:f2:7d:a1 PROBE
192.168.0.178 lladdr xxxx:f2:7d:a1 REACHABLE
192.168.0.176 lladdr xxxx:f3:1b:ac PROBE
192.168.0.176 lladdr xxxx:f3:1b:ac REACHABLE
192.168.0.175 lladdr xxxx:f3:1c:f0 PROBE
192.168.0.175 lladdr xxxx:f3:1c:f0 REACHABLE
192.168.0.177 lladdr xxxx:f3:65:d0 STALE
192.168.0.231 lladdr xxxx:6d:0b:df PROBE
192.168.0.231 lladdr xxxx:6d:0b:df REACHABLE
192.168.0.178 lladdr xxxx:f2:7d:a1 STALE
192.168.0.175 lladdr xxxx:f3:1c:f0 STALE
192.168.0.177 lladdr xxxx:f3:65:d0 PROBE
192.168.0.177 lladdr xxxx:f3:65:d0 REACHABLE
192.168.0.231 lladdr xxxx:6d:0b:df STALE
192.168.0.176 lladdr xxxx:f3:1b:ac STALE
192.168.0.176 lladdr xxxx:f3:1b:ac REACHABLE
192.168.0.178 lladdr xxxx:f2:7d:a1 REACHABLE
192.168.0.175 lladdr xxxx:f3:1c:f0 PROBE
192.168.0.175 lladdr xxxx:f3:1c:f0 REACHABLE
192.168.0.176 lladdr xxxx:f3:1b:ac STALE
192.168.0.176 lladdr xxxx:f3:1b:ac REACHABLE
192.168.0.177 lladdr xxxx:f3:65:d0 STALE
192.168.0.231 lladdr xxxx:6d:0b:df PROBE
192.168.0.231 lladdr xxxx:6d:0b:df REACHABLE
192.168.0.178 lladdr xxxx:f2:7d:a1 STALE
192.168.0.175 lladdr xxxx:f3:1c:f0 STALE
192.168.0.176 lladdr xxxx:f3:1b:ac STALE
192.168.0.231 lladdr xxxx:6d:0b:df STALE
192.168.0.176 lladdr xxxx:f3:1b:ac PROBE
192.168.0.176 lladdr xxxx:f3:1b:ac REACHABLE
192.168.0.177 lladdr xxxx:f3:65:d0 PROBE
192.168.0.177 lladdr xxxx:f3:65:d0 REACHABLE
192.168.0.231 lladdr xxxx:6d:0b:df PROBE
192.168.0.231 lladdr xxxx:6d:0b:df REACHABLE
192.168.0.178 lladdr xxxx:f2:7d:a1 PROBE
192.168.0.178 lladdr xxxx:f2:7d:a1 REACHABLE
192.168.0.176 lladdr xxxx:f3:1b:ac STALE
192.168.0.231 lladdr xxxx:6d:0b:df STALE
192.168.0.176 lladdr xxxx:f3:1b:ac REACHABLE
192.168.0.175 lladdr xxxx:f3:1c:f0 PROBE
192.168.0.175 lladdr xxxx:f3:1c:f0 REACHABLE
192.168.0.177 lladdr xxxx:f3:65:d0 STALE
192.168.0.231 lladdr xxxx:6d:0b:df PROBE
192.168.0.231 lladdr xxxx:6d:0b:df REACHABLE
192.168.0.178 lladdr xxxx:f2:7d:a1 STALE
192.168.0.176 lladdr xxxx:f3:1b:ac STALE
192.168.0.175 lladdr xxxx:f3:1c:f0 STALE
192.168.0.176 lladdr xxxx:f3:1b:ac PROBE
192.168.0.176 lladdr xxxx:f3:1b:ac REACHABLE
192.168.0.231 lladdr xxxx:6d:0b:df STALE
192.168.0.177 lladdr xxxx:f3:65:d0 PROBE
192.168.0.177 lladdr xxxx:f3:65:d0 REACHABLE
192.168.0.176 lladdr xxxx:f3:1b:ac STALE
192.168.0.176 lladdr xxxx:f3:1b:ac PROBE
192.168.0.176 lladdr xxxx:f3:1b:ac REACHABLE
192.168.0.175 lladdr xxxx:f3:1c:f0 PROBE
192.168.0.175 lladdr xxxx:f3:1c:f0 REACHABLE
192.168.0.178 lladdr xxxx:f2:7d:a1 PROBE
192.168.0.178 lladdr xxxx:f2:7d:a1 REACHABLE
192.168.0.177 lladdr xxxx:f3:65:d0 STALE
192.168.0.231 lladdr xxxx:6d:0b:df PROBE
192.168.0.231 lladdr xxxx:6d:0b:df REACHABLE
192.168.0.175 lladdr xxxx:f3:1c:f0 STALE
192.168.0.178 lladdr xxxx:f2:7d:a1 STALE
192.168.0.231 lladdr xxxx:6d:0b:df STALE
192.168.0.177 lladdr xxxx:f3:65:d0 PROBE
192.168.0.177 lladdr xxxx:f3:65:d0 REACHABLE
192.168.0.176 lladdr xxxx:f3:1b:ac STALE
192.168.0.176 lladdr xxxx:f3:1b:ac REACHABLE
192.168.0.178 lladdr xxxx:f2:7d:a1 PROBE
192.168.0.178 lladdr xxxx:f2:7d:a1 REACHABLE
192.168.0.176 lladdr xxxx:f3:1b:ac STALE
192.168.0.175 lladdr xxxx:f3:1c:f0 PROBE
192.168.0.175 lladdr xxxx:f3:1c:f0 REACHABLE
192.168.0.177 lladdr xxxx:f3:65:d0 STALE
192.168.0.176 lladdr xxxx:f3:1b:ac REACHABLE
192.168.0.231 lladdr xxxx:6d:0b:df PROBE
192.168.0.231 lladdr xxxx:6d:0b:df REACHABLE
192.168.0.178 lladdr xxxx:f2:7d:a1 STALE
192.168.0.175 lladdr xxxx:f3:1c:f0 STALE
192.168.0.176 lladdr xxxx:f3:1b:ac STALE
192.168.0.231 lladdr xxxx:6d:0b:df STALE
192.168.0.176 lladdr xxxx:f3:1b:ac PROBE
192.168.0.176 lladdr xxxx:f3:1b:ac REACHABLE
192.168.0.177 lladdr xxxx:f3:65:d0 PROBE
192.168.0.177 lladdr xxxx:f3:65:d0 REACHABLE
192.168.0.178 lladdr xxxx:f2:7d:a1 PROBE
192.168.0.178 lladdr xxxx:f2:7d:a1 REACHABLE
192.168.0.175 lladdr xxxx:f3:1c:f0 PROBE
192.168.0.175 lladdr xxxx:f3:1c:f0 REACHABLE
````
Previous node, 192.168.0.231 and 192.168.0.230 are new node:
````
[root@k8s-master01 ~]# ip monitor dev enp7s0f0
192.168.0.231 lladdr xxxx:6d:0b:df PROBE
192.168.0.231 lladdr xxxx:6d:0b:df REACHABLE
192.168.0.230 lladdr xxxx:92:ff:20 PROBE
192.168.0.230 lladdr xxxx:92:ff:20 REACHABLE
192.168.0.231 lladdr xxxx:6d:0b:df STALE
192.168.0.230 lladdr xxxx:92:ff:20 STALE
192.168.0.231 lladdr xxxx:6d:0b:df REACHABLE
192.168.0.230 lladdr xxxx:92:ff:20 PROBE
192.168.0.230 lladdr xxxx:92:ff:20 REACHABLE
192.168.0.231 lladdr xxxx:6d:0b:df STALE
192.168.0.230 lladdr xxxx:92:ff:20 STALE
192.168.0.231 lladdr xxxx:6d:0b:df PROBE
192.168.0.231 lladdr xxxx:6d:0b:df REACHABLE
192.168.0.230 lladdr xxxx:92:ff:20 PROBE
192.168.0.230 lladdr xxxx:92:ff:20 REACHABLE
192.168.0.231 lladdr xxxx:6d:0b:df STALE
192.168.0.230 lladdr xxxx:92:ff:20 STALE
192.168.0.231 lladdr xxxx:6d:0b:df REACHABLE
192.168.0.230 lladdr xxxx:92:ff:20 REACHABLE
192.168.0.231 lladdr xxxx:6d:0b:df STALE
192.168.0.230 lladdr xxxx:92:ff:20 STALE
192.168.0.231 lladdr xxxx:6d:0b:df REACHABLE
192.168.0.230 lladdr xxxx:92:ff:20 PROBE
192.168.0.230 lladdr xxxx:92:ff:20 REACHABLE
192.168.0.231 lladdr xxxx:6d:0b:df STALE
192.168.0.230 lladdr xxxx:92:ff:20 STALE
192.168.0.231 lladdr xxxx:6d:0b:df PROBE
192.168.0.231 lladdr xxxx:6d:0b:df REACHABLE
192.168.0.230 lladdr xxxx:92:ff:20 PROBE
192.168.0.230 lladdr xxxx:92:ff:20 REACHABLE
````

Log of the new node Calico:
````
2020-12-23 03:54:40.263 [INFO][71] felix/int_dataplane.go 1300: Applying dataplane updates
2020-12-23 03:54:40.263 [INFO][71] felix/route_table.go 398: Queueing a resync of routing table. ifaceRegex="^cali.*" ipVersion=0x4
2020-12-23 03:54:40.263 [INFO][71] felix/wireguard.go 534: Queueing a resync of wireguard configuration
2020-12-23 03:54:40.263 [INFO][71] felix/route_table.go 398: Queueing a resync of routing table. ifaceRegex="^wireguard.cali$" ipVersion=0x4
2020-12-23 03:54:40.263 [INFO][71] felix/route_rule.go 172: Queueing a resync of routing rules. ipVersion=4
2020-12-23 03:54:40.268 [INFO][71] felix/int_dataplane.go 1314: Finished applying updates to dataplane. msecToApply=4.81853
bird: Netlink: Network is down
bird: Netlink: Network is down
bird: ...
2020-12-23 03:54:42.980 [INFO][71] felix/int_dataplane.go 1300: Applying dataplane updates
2020-12-23 03:54:42.981 [INFO][71] felix/ipsets.go 223: Asked to resync with the dataplane on next update. family="inet"
2020-12-23 03:54:42.981 [INFO][71] felix/ipsets.go 306: Resyncing ipsets with dataplane. family="inet"
2020-12-23 03:54:42.991 [INFO][71] felix/ipsets.go 356: Finished resync family="inet" numInconsistenciesFound=0 resyncDuration=10.212526ms
2020-12-23 03:54:42.992 [INFO][71] felix/int_dataplane.go 1314: Finished applying updates to dataplane. msecToApply=11.009635
bird: Netlink: Network is down
bird: Netlink: Network is down
bird: ...
bird: Netlink: Network is down
bird: Netlink: Network is down
bird: ...
bird: Netlink: Network is down
bird: Netlink: Network is down
bird: ...
bird: Netlink: Network is down
bird: Netlink: Network is down
bird: ...
bird: Netlink: Network is down
bird: Netlink: Network is down
bird: ...
2020-12-23 03:54:53.044 [INFO][71] felix/int_dataplane.go 1300: Applying dataplane updates
2020-12-23 03:54:53.044 [INFO][71] felix/ipsets.go 223: Asked to resync with the dataplane on next update. family="inet"
2020-12-23 03:54:53.045 [INFO][71] felix/ipsets.go 306: Resyncing ipsets with dataplane. family="inet"
2020-12-23 03:54:53.056 [INFO][71] felix/ipsets.go 356: Finished resync family="inet" numInconsistenciesFound=0 resyncDuration=11.189209ms
2020-12-23 03:54:53.056 [INFO][71] felix/int_dataplane.go 1314: Finished applying updates to dataplane. msecToApply=11.894278
bird: Netlink: Network is down
bird: Netlink: Network is down
bird: ...
bird: Netlink: Network is down
bird: Netlink: Network is down
bird: ...
bird: Netlink: Network is down
bird: Netlink: Network is down
bird: ...
bird: Netlink: Network is down
bird: Netlink: Network is down
````

This is the yaml file of calico:
````
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: calico-node
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: calico-node
    spec:
      containers:
      - env:
        - name: DATASTORE_TYPE
          value: kubernetes
        - name: FELIX_TYPHAK8SSERVICENAME
          valueFrom:
            configMapKeyRef:
              key: typha_service_name
              name: calico-config
        - name: WAIT_FOR_DATASTORE
          value: "true"
        - name: NODENAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: CALICO_NETWORKING_BACKEND
          valueFrom:
            configMapKeyRef:
              key: calico_backend
              name: calico-config
        - name: CLUSTER_TYPE
          value: k8s,bgp
        - name: IP
          value: autodetect
        - name: CALICO_IPV4POOL_IPIP
          value: Always
        - name: CALICO_IPV4POOL_VXLAN
          value: Never
        - name: FELIX_IPINIPENABLED
          value: "false"
        - name: FELIX_IPINIPMTU
          valueFrom:
            configMapKeyRef:
              key: veth_mtu
              name: calico-config
        - name: FELIX_VXLANMTU
          valueFrom:
            configMapKeyRef:
              key: veth_mtu
              name: calico-config
        - name: FELIX_WIREGUARDMTU
          valueFrom:
            configMapKeyRef:
              key: veth_mtu
              name: calico-config
        - name: CALICO_IPV4POOL_CIDR
          value: 10.244.0.0/12
        - name: CALICO_DISABLE_FILE_LOGGING
          value: "true"
        - name: FELIX_DEFAULTENDPOINTTOHOSTACTION
          value: ACCEPT
        - name: FELIX_IPV6SUPPORT
          value: "false"
        - name: FELIX_LOGSEVERITYSCREEN
          value: info
        - name: FELIX_HEALTHENABLED
          value: "true"
        - name: IP_AUTODETECTION_METHOD
          value: cidr=10.103.236.0/24
        envFrom:
        - configMapRef:
            name: kubernetes-services-endpoint
            optional: true
        image: harborsy.lenovo.com.cn/system-images/calico/node:v3.16.3
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /bin/calico-node
            - -felix-live
            - -bird-live
          failureThreshold: 6
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: calico-node
        readinessProbe:
          exec:
            command:
            - /bin/calico-node
            - -felix-ready
            - -bird-ready
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 250m
        securityContext:
          privileged: true
          procMount: Default
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /lib/modules
          name: lib-modules
          readOnly: true
        - mountPath: /run/xtables.lock
          name: xtables-lock
        - mountPath: /var/run/calico
          name: var-run-calico
        - mountPath: /var/lib/calico
          name: var-lib-calico
        - mountPath: /var/run/nodeagent
          name: policysync
        - mountPath: /sys/fs/
          mountPropagation: Bidirectional
          name: sysfs
      dnsPolicy: ClusterFirst
      hostNetwork: true
      initContainers:
      - command:
        - /opt/cni/bin/calico-ipam
        - -upgrade
        env:
        - name: KUBERNETES_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: CALICO_NETWORKING_BACKEND
          valueFrom:
            configMapKeyRef:
              key: calico_backend
              name: calico-config
        - name: IP_AUTODETECTION_METHOD
          value: cidr=192.168.0.0/24
        envFrom:
        - configMapRef:
            name: kubernetes-services-endpoint
            optional: true
        image: harborsy.lenovo.com.cn/system-images/calico/cni:v3.16.3
        imagePullPolicy: IfNotPresent
        name: upgrade-ipam
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/cni/networks
          name: host-local-net-dir
        - mountPath: /host/opt/cni/bin
          name: cni-bin-dir
      - command:
        - /opt/cni/bin/install
        env:
        - name: CNI_CONF_NAME
          value: 10-calico.conflist
        - name: CNI_NETWORK_CONFIG
          valueFrom:
            configMapKeyRef:
              key: cni_network_config
              name: calico-config
        - name: IP_AUTODETECTION_METHOD
          value: cidr=10.103.236.0/24
        - name: KUBERNETES_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: CNI_MTU
          valueFrom:
            configMapKeyRef:
              key: veth_mtu
              name: calico-config
        - name: SLEEP
          value: "false"
        envFrom:
        - configMapRef:
            name: kubernetes-services-endpoint
            optional: true
        image: harborsy.lenovo.com.cn/system-images/calico/cni:v3.16.3
        imagePullPolicy: IfNotPresent
        name: install-cni
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /host/opt/cni/bin
          name: cni-bin-dir
        - mountPath: /host/etc/cni/net.d
          name: cni-net-dir
      - image: harborsy.lenovo.com.cn/system-images/calico/pod2daemon-flexvol:v3.16.3
        imagePullPolicy: IfNotPresent
        name: flexvol-driver
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /host/driver
          name: flexvol-driver-host
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: calico-node
      serviceAccountName: calico-node
      terminationGracePeriodSeconds: 0
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoExecute
        operator: Exists
      volumes:
      - hostPath:
          path: /lib/modules
          type: ""
        name: lib-modules
      - hostPath:
          path: /var/run/calico
          type: ""
        name: var-run-calico
      - hostPath:
          path: /var/lib/calico
          type: ""
        name: var-lib-calico
      - hostPath:
          path: /run/xtables.lock
          type: FileOrCreate
        name: xtables-lock
      - hostPath:
          path: /sys/fs/
          type: DirectoryOrCreate
        name: sysfs
      - hostPath:
          path: /opt/cni/bin
          type: ""
        name: cni-bin-dir
      - hostPath:
          path: /etc/cni/net.d
          type: ""
        name: cni-net-dir
      - hostPath:
          path: /var/lib/cni/networks
          type: ""
        name: host-local-net-dir
      - hostPath:
          path: /var/run/nodeagent
          type: DirectoryOrCreate
        name: policysync
      - hostPath:
          path: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds
          type: DirectoryOrCreate
        name: flexvol-driver-host
  updateStrategy:
    type: OnDelete
````

I have no other ideas to solve this problem. It looks like a problem with the server's network. Do you have any good solutions?
