### ISSUE TITLE
RKE: NetworkPolicy based on NamespaceSelector doesn't work

### ISSUE THREAD

**Issue by ducminhle** [projectcalico/calico#4291]
## Expected Behavior
Pods in another namespace allow traffic in from nginx-ingress namespace with namepsaceSelector.

## Current Behavior
- Calico has been deploy when launching rke. (https://rancher.com/docs/rke/latest/en/config-options/add-ons/network-plugins/)
- In RKE, nginx-ingress deployed with DaemonSet by RKE.
```
# ingress controller
ingress:
  provider: nginx
  options:
     use-forwarded-headers: "true"
# CNI
network:
  plugin: calico
```

We have a service running with `containerPort: 80`. We create a network policy to nginx-ingress that can connect to our service., but it not working with namespaceSelector but it work if I use node worker IPs.

## Possible Solution

## Steps to Reproduce (for bugs)
1. When we use namespaceSeletor to create network policy, I can not access our website.
```
apiVersion: networking.k8s.io/v1                                                                                                                                                                             
 kind: NetworkPolicy                                                                                                                                                                                          
 metadata:                                                                                                                                                           
   generation: 12                                                                                                                                                           
   name: marketing-landing-page-policy                                                                                                                                             
   namespace: marketing-portal                                                                                                                                                           
 spec:                                                                                                                                                                                                        
   ingress:                                                                                                                                                                                                   
   - from:                                                                                                                                                                                                    
     - namespaceSelector:                                                                                                                                                                                     
         matchLabels:                                                                                                                                                                                         
           service: ingress-nginx                                                                                                                                                                             
     ports:                                                                                                                                                                                                   
     - port: 80                                                                                                                                                                                               
       protocol: TCP                                                                                                                                                                                          
   podSelector:                                                                                                                                                                                               
     matchLabels:                                                                                                                                                                                             
       app.kubernetes.io/name: marketing-landing-page                                                                                                                                                         
   policyTypes:                                                                                                                                                                                               
   - Ingress                                                                                                                                                                                                  
   - Egress
```

2. I try to create a pod in nginx-ingress namespace and run nc, it's connected.

```
kubectl run curl-test --labels="app=test-curl" --image=infoblox/dnstools:latest --namespace ingress-nginx -i --tty --rm
If you don't see a command prompt, try pressing enter.
dnstools# nc -v 172.22.1.153 80
172.22.1.153 (172.22.1.153:80) open
```
3. However, nc from nginx-ingress-controller pod => time out
```
bash-5.0$ ./nc -v 172.22.1.153 80
Ncat: Version 6.49BETA1 ( http://nmap.org/ncat )
Ncat: Operation timed out.
```
4. When we use IP worker node (projectcalico.org/IPv4IPIPTunnelAddr) nginx-ingress can connect to our service => but it's not a good solution.

```
apiVersion: networking.k8s.io/v1                                                                                                                                                                             
 kind: NetworkPolicy                                                                                                                                                                                          
 metadata:                                                                                                                                                           
   generation: 12                                                                                                                                                           
   name: marketing-landing-page-policy                                                                                                                                             
   namespace: marketing-portal                                                                                                                                                           
 spec:                                                                                                                                                                                                        
   ingress:                                                                                                                                                                                                   
   - ipBlock:                                                                                                                                                                                               
         cidr: 172.22.1.120/32                                                                                                                                                                                 
     - ipBlock:                                                                                                                                                                                               
         cidr: 172.22.1.121/32                                                                                                                                                                                
     - ipBlock:                                                                                                                                                                                               
         cidr: 172.22.1.122/32                                                                                                                                                                              
     - ipBlock:                                                                                                                                                                                               
         cidr: 172.22.1.123/32                                                                                                                                                                           
     ports:                                                                                                                                                                                                   
     - port: 80                                                                                                                                                                                               
       protocol: TCP                                                                                                                                                                                          
   podSelector:                                                                                                                                                                                               
     matchLabels:                                                                                                                                                                                             
       app.kubernetes.io/name: marketing-landing-page                                                                                                                                                         
   policyTypes:                                                                                                                                                                                               
   - Ingress                                                                                                                                                                                                  
   - Egress
```

## Context
Could you please help me with a solution to use NetworkPolicy base on NamespaceSelector with nginx-ingress?

## Your Environment
<!--- Include as many relevant details about the environment you experienced the bug in -->
* Calico version: v3.13.4
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes v1.16.13 (RKE)
* Operating System and version:  Ubuntu 20.04 LTS
* Link to your project (optional):

**Comment by mgleung** [comment]
Hi @ducminhle , thanks for bringing this to our attention. I wanted to ask a few clarifying questions to make sure I'm understanding the use case you've written here. What does the namespace with the `service: ingress-nginx` label look like? Is that another namespace or is it `marketing-portal`? I'm also interested in what the IP `172.22.1.153` refers to since it appears to be different than the IP addresses you use in the final working (though not ideal) network policy. Is that the `curl-test` pod's IP? Also is the overall intention to create a policy where all nodes in the same namespace can interact with each other?

**Comment by ducminhle** [comment]
Thank you @mgleung for your reply.
- What does the namespace with the service: ingress-nginx label look like?
```
kubectl get ns ingress-nginx -o yaml
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"name":"ingress-nginx"}}
  creationTimestamp: "2020-10-08T05:48:11Z"
  labels:
    service: ingress-nginx
  name: ingress-nginx
  resourceVersion: "104890552"
  selfLink: /api/v1/namespaces/ingress-nginx
  uid: 32c2e217-24c1-4418-a8b9-a9faa1a70853
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
```
```
kubectl get all -n ingress-nginx
NAME                                        READY   STATUS    RESTARTS   AGE
pod/default-http-backend-57545b6b6c-jcqh2   1/1     Running   1          96d
pod/nginx-ingress-controller-2w9jl          1/1     Running   1          6d18h
pod/nginx-ingress-controller-kkltw          1/1     Running   1          6d18h
pod/nginx-ingress-controller-kljbb          1/1     Running   2          6d18h
pod/nginx-ingress-controller-sxgcg          1/1     Running   2          6d18h

NAME                           TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)   AGE
service/default-http-backend   ClusterIP   172.20.3.28   <none>        80/TCP    96d

NAME                                      DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/nginx-ingress-controller   4         4         4       4            4           <none>          96d

NAME                                   READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/default-http-backend   1/1     1            1           96d

NAME                                              DESIRED   CURRENT   READY   AGE
replicaset.apps/default-http-backend-57545b6b6c   1         1         1       96d
replicaset.apps/default-http-backend-6789ff6fc    0         0         0       96d
replicaset.apps/default-http-backend-67cf578fc4   0         0         0       96d
replicaset.apps/default-http-backend-68fd5d6465   0         0         0       96d
```

- Is that another namespace or is it marketing-portal?
Yes, in my example is marketing-portal

- I'm also interested in what the IP 172.22.1.153 refers to since it appears to be different than the IP addresses you use in the final working (though not ideal) network policy. Is that the curl-test pod's IP?
It's pod IP of marketing-landing-page
```
kubectl get pods -n marketing-portal -o wide
NAME                                           READY   STATUS    RESTARTS   AGE   IP             NODE           NOMINATED NODE   READINESS GATES
marketing-landing-page-web-6d99bd9f79-8ffwv    1/1     Running   1          48d   172.22.1.153   rke-worker-3   <none>           <none>
marketing-portal-be-service-646c59bdb6-qjk42   1/1     Running   0          21h   172.22.90.8    rke-worker-4   <none>           <none>
marketing-portal-fe-web-6fd79c8c47-nmpqn       1/1     Running   0          29d   172.22.1.175   rke-worker-3   <none>           <none>
```

To debug, I create pod `curl-test` in namespace ingress-nginx to check connect with netcat from pod curl-test to marketing-landing-page-web => connected. However, I check netcat from pod nginx-ingress-controller in namespace ingress-nginx to marketing-landing-page-web => Operation timed out.

- Also is the overall intention to create a policy where all nodes in the same namespace can interact with each other?
We want to create a network policy: nginx-ingress-controler can access pods on another namespace (example: marketing-landing-page-web in namespace marketing-portal with port 80) but don't need to use IP worker node, we can use namespaceSelector or podSelector in policy config.

**Comment by mgleung** [comment]
@ducminhle Thanks for the extra info. I think this sounds like we have an issue with our namespace selectors. From your setup this sounds kind of similar to https://github.com/projectcalico/calico/issues/4092 so I would keep an eye on that.

**Comment by mgleung** [comment]
Hi @ducminhle, was taking a crack at trying to replicate your issue and am having a little bit of difficulty (though my testing is on a different version of Calico). I have 2 policies only, 1 to deny traffic from any other namespace and 1 to allow traffic from another namespace (based off of your policy above).
```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: deny-from-other-namespaces
  #namespace: my-app
  namespace: ingress-internal
spec:
  policyTypes:
    - Ingress
    - Egress
  podSelector:
    matchLabels:
  ingress:
  - from:
    - podSelector: {}
  egress:
  - to:
    - podSelector: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress
  namespace: ingress-internal
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: my-app
    ports:
    - port: 80
      protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/name: ingress
  policyTypes:
  - Ingress
  - Egress
```
Thought that I should ask as a follow-up what your network policy looked like that was denying traffic? I'm thinking that the issue might be in the specific combination of deny/allow policies that are used and whether we interpret the rules correctly from them. Also as a sanity check, I was wondering if you could show the labels for the pods in `marketing-portal` as well? Just want to make sure that the pod selector matches as I would expect it to.

**Comment by tomerleib** [comment]
I can confirm the same behavior is at my setup as well.
Current environment:

- RKE v1.2.4
- K8s 1.19
- Canal

Same networkpolicies are working in EKS but not in RKE:  
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app: app-test
  name: deny-all-ns
  namespace: test
spec:
  ingress:
  - from:
    - podSelector: {}
  podSelector: {}
  policyTypes:
  - Ingress 
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app: app-test
  name: allow-monitoring
  namespace: test
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: monitoring
  podSelector: {}
  policyTypes:
  - Ingress
```

Here as well, I'm not targeting pod labels but using the `namespaceSelector` which does not work for some reason.

**Comment by mgleung** [comment]
@tomerleib that's very interesting. This might possibly be an RKE issue then. Can I get you to quickly verify that targeting pod labels will work in your policies? I want to narrow this down to namespace selectors in your environment first.

**Comment by tomerleib** [comment]
@mgleung 
It seems that it is a version related, here's my configuration that had this issue:

- RKE v1.2.4
- K8s 1.19.6
- Calico 3.16.1

After I've upgrade my RKE to version 1.2.7, K8s to 1.20.4, Calico images to 3.17.2, the network policies worked as they should.

**Comment by mgleung** [comment]
@tomerleib thanks for testing and narrowing that down for us. Sounds like that at least for now, the workaround is to upgrade the cluster components. If you have your RKE cluster still up, would you mind checking if Calico 3.17 works on RKE 1.2.4? I don't recall any changes between Calico 3.16 and 3.17 that should affect policy to this extent but I want to narrow down that the issue is Calico and not dependent on the version of RKE.

**Comment by dev-maniac** [comment]
Hello. I want to confirm the behaviour initially described by @ducminhle. 
Namespace selectors per se are working, but whitelisting ingress-nginx namespace does not work. 
Or rather, it works, but the ingress-nginx controllers do not seem to be catched by the rule (also deployed a simple pod in ingress-nginx namespace to confirm that this pod CAN reach my "target" namespace).
Some search indicated, that hostNetwork may be the problem: 
* https://superuser.com/questions/1481901/networkpolicy-has-no-effect-on-nginx-ingress-namespace
* https://github.com/projectcalico/felix/issues/1361
Tried it with three different RKE/K8s/Calco versions (upgraded to newest stable RKE 1.2.7 yesterday from a few versions back - old RKE had k8s 1.17.7 - I don't know RKE or Calio version, though. I think Calico was < 3.16 before)

Current versons:
* RKE v1.2.7
* K8s v1.20.5
* Calico 3.17.2

Is this a known limitation? How can I isolate my namespace to only allow ingress from a few other pods/namespaces AND ingress-nginx? Using the internal IPs of the ingress-nginx-controllers would be very static...

What I did:
1. Add label to ingress-nginx namespace to be able to select it (e.g. type: ingress)
2. Deny all ingress in my own namespace
3. Allow ingress from namespace with label "type: ingress"

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-all-deny
  namespace: my-own-namespace
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress: []
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-allow-ingress
  namespace: my-own-namespace
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          type: ingress
```

**Comment by mgleung** [comment]
Sorry for the super long delay. I am still having a little bit of trouble replicating this issue. I think from my past attempts, I hadn't quite replicated the scenario reported here perfectly since I wasn't using RKE so in case there's anything else I'm missing here, I've tried to detail my replication steps as much as possible below.

My replication versions:
- RKE v1.2.7
- K8s v1.20.5
- Calico v3.17.6

Replication steps:
- Set up an nginx pod that will function as my test app to test connectivity
```
apiVersion: v1
kind: Namespace
metadata:
  labels:
    service: nginx
  name: nginx
spec:
  finalizers:
  - kubernetes

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx-server
  namespace: nginx
  labels:
    app: connect-test
spec:
  containers:
  - name: nginx-server
    image: nginx

---

apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx
spec:
  selector:
    app: connect-test
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
```
- Install the nginx ingress controller (following the instructions for installing the nginx ingress controller from a manifest from the [website](https://kubernetes.github.io/ingress-nginx/deploy/). `kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.0/deploy/static/provider/cloud/deploy.yaml`
- Creating an Ingress resource to route to my nginx backend pods at the `/nginx` path
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-backend-ingress
  namespace: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /nginx
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 80
```
- Creating a nodeport service to expose my ingress controllers to external traffic
```
apiVersion: v1
kind: Service
metadata:
  name: ingress-nodeport
  namespace: ingress-nginx
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: ingress-nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
```
- Creating the K8s network policies in my nginx backend's namespace to only allow traffic from the ingress controller's namespace
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-all-deny
  namespace: nginx
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress: []

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-ingress-nginx
  namespace: nginx
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx
```
- SSH into a node that my nginx backing pod is not on in order to curl my nodeport service and test that non-locally originating traffic can make it through the ingress and network policies properly.
```
$ curl 10.128.1.181:30007/nginx
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```

Anyone who is still seeing this issue notice any corners I am cutting in my replication?
