### ISSUE TITLE
NetworkPolicy works on LoadBalancer but not on ClusterIP Service

### ISSUE THREAD

**Issue by shibumi** [projectcalico/calico#4309]
I want to achieve the following. I have a namespace called "foo". The following Rules should apply on this namespace

* Deny all outgoing traffic on default
* Deny all incoming traffic on default
* Allow Traffic for port 80/443 (a web application)
* Allow outgoing traffic to the mariadb instance

## Expected Behavior
I expect that `namespaceSelector` matches all resources in the specified namespace.

## Current Behavior
It is possible to match a Loadbalancer Service, but it is not possible to match a ClusterIP Service.

## Possible Solution
None

## Steps to Reproduce (for bugs)
I have the following two Netpols. The first one denies all incoming/outgoing traffic:
```yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: deny-from-other-namespaces
  namespace: my-app
spec:
  policyTypes:
    - Ingress
    - Egress
  podSelector:
    matchLabels:
  ingress:
  - from:
    - podSelector: {}
  egress:
  - to:
    - podSelector: {}
```

The second one allows incoming traffic on Port 80/443 and allows Egress traffic to the mariadb namespace and the ingress namespace for exposing the website (I am not sure if allowing egress to the ingress is needed):
```yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-exceptions
  namespace: my-app
spec:
  podSelector:
    matchLabels:
      io.kompose.service: my-app
  policyTypes:
    - Ingress
    - Egress
  ingress:
  - ports:
    - port: 80
    - port: 443
  egress:
    - to:
      - namespaceSelector:
          matchLabels:
            name: mariadb-10-5
      - namespaceSelector:
          matchLabels:
            name: ingress-internal
```

I have checked that the namespace `mariadb-10-5` has a label called `name=mariadb-10-5`.
The deployment in that namespace looks like this:

```
❯ k get all -n mariadb-10-5
NAME                                READY   STATUS    RESTARTS   AGE
pod/mariadb-10-5-mariadb-galera-0   2/2     Running   0          8d
pod/mariadb-10-5-mariadb-galera-1   2/2     Running   0          8d
pod/mariadb-10-5-mariadb-galera-2   2/2     Running   0          8d

NAME                                           TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
service/mariadb-10-5-mariadb-galera            ClusterIP   10.43.244.49    <none>        3306/TCP                     15d
service/mariadb-10-5-mariadb-galera-headless   ClusterIP   None            <none>        4567/TCP,4568/TCP,4444/TCP   15d
service/mariadb-10-5-mariadb-galera-metrics    ClusterIP   10.43.145.158   <none>        9104/TCP                     15d

NAME                                           READY   AGE
statefulset.apps/mariadb-10-5-mariadb-galera   3/3     15d
```

If I `k exec` into the my-app container I can't reach the IP 10.43.244.49 on Port 3306 (I think I should be able to, right?!).
If create a loadBalancer out of this clusterIP service on the IP 10.101.0.205 it works.

## Context
See my explanation upfront.

## Your Environment

* Calico version: rancher/calico-cni:v3.13.4
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes
* Operating System and version: CentOS 7
* Link to your project (optional):

**Comment by caseydavenport** [comment]
This might be the same issues as these:
- https://github.com/projectcalico/calico/issues/4291
- https://github.com/projectcalico/calico/issues/4092

There have been some reports that namespace selectors are not working properly, but our tests for namespace selectors seems to be passing, so I'm not sure yet what's going on there. Needs some more investigation.

**Comment by shibumi** [comment]
@caseydavenport  I played around with this and it's finally working. Looks like I forgot about DNS that's why I had the feeling it's not working. Although I can confirm that there are strange namespaceSelector issues sometimes.

I just restarted the deployment and then it worked as expected.

```yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: mynetpol
spec:
  podSelector:
    matchLabels:
      io.kompose.service: myapp
  policyTypes:
    - Ingress
    - Egress
  ingress:
  - ports:
    - port: 80
    - port: 443
  egress:
    - ports:
      - port: 53
        protocol: UDP
      to:
        - namespaceSelector:
            matchLabels:
              name: kube-system
    - to:
      - namespaceSelector:
          matchLabels:
            name: mariadb-10-5
```
