### ISSUE TITLE
calico global networkpolicy does not work for egress policy ?

### ISSUE THREAD

**Issue by ShawnBian** [projectcalico/calico#4352]
we use calicoctl to apply below yaml file :

![image](https://user-images.githubusercontent.com/19188604/105942525-57d8fb00-609a-11eb-83be-c77d52e3bf20.png)

post the yaml file here as well (I dont know why the format is just disappeared once we copy them to here)

=========================================

```
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: deny-blue
spec:
  selector: color == 'red'
  types:
  - Ingress
  - Egress
  Ingress:
  - action: Allow
    metadata:
      annotations:
        from: blue
        to: red
    protocol: TCP
    source:
      selector: color == 'blue'
    destination:
      ports:
        - 80
  Egress:
  - action: Deny
    metadata:
      annotations:
        from: red
        to: blue
    protocol: TCP
    destination:
      selector: color == 'blue'
      ports:
        - 80
```
=======================================

## Current Behavior
pod has label "color=blue" can not access the POD with label "color=red"
pod has label "color=red" can not access anywhere .

## Expected Behavior
pod has label "color=blue" can not access the POD with label "color=red"
pod has label "color=red" can not access the POD with label "color=blue",but it is suppose that it can access internet and other pod dont have label "color=blue"

**Comment by ShawnBian** [comment]
meanwhile I also find other question , if we apply below yaml file :
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: deny-blue
spec:
  selector: color == 'red'
  types:
  - Ingress
  #- Egress
  Ingress:
  - action: Deny
    metadata:
      annotations:
        from: blue
        to: red
    protocol: TCP
    source:
      selector: color == 'blue'
    destination:
      ports:
        - 80


Actually the pod has label "color=red" can not be accessed from anywhere. we expect that it only can not be accessed from the pod with label "color=blue"

**Comment by lwr20** [comment]
Are you following: 
https://docs.projectcalico.org/security/calico-network-policy#control-traffic-tofrom-endpoints-independent-of-namespace  ?

**Comment by lwr20** [comment]
You should be able to post yaml with indentation if you enclose it in triple backtick quotes (```).

**Comment by caseydavenport** [comment]
```
  Egress:
  - action: Deny
    metadata:
      annotations:
        from: red
        to: blue
    protocol: TCP
    destination:
      selector: color == 'blue'
      ports:
        - 80
```

Your egress rules only deny traffic - there is nothing allowing traffic, and so everything else is going to get hit by the "default deny" behavior of the policy. You need to explicitly allow the traffic that you want to allow using a rule with `action: Allow`
