### ISSUE TITLE
same IP on two different MAC (two different machines)

### ISSUE THREAD

**Issue by punkprzemo** [projectcalico/calico#4362]
## Current Behavior

We are using Calico VXLAN mode.
```
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: default-ipv4-ippool
spec:
  blockSize: 23
  cidr: 172.26.0.0/16
  ipipMode: Never
  natOutgoing: true
  nodeSelector: all()
  vxlanMode: Always
  
```

Example  issue from title:
```
Node_A (00:26:b5:02:a1:02) - eth0: 10.1.1.3 - baremetal machine / not in k8s cluster / no Calico VXLAN
Node_B (00:26:b5:02:a1:12) - eth0: 10.1.1.12 - baremetal machine / k8s worker node with Calico VXLAN
Pod - 172.26.58.228 
```
I have a `Pod` which has IP from cluster VXLAN default pool 172.26.x.x/16 running on k8s worker `Node_B`  
This `Pod` is doing a lot of frequent connection healthchecks to application which is running on **non-k8s** `Node_A`. 
**If i kill the** `Pod` some packets captured  on eth0 of the `Node_B` appears to have source IP of the `Node_A` but with MAC of the `node_B`. 
Below example captured packets.

![image](https://user-images.githubusercontent.com/36777025/106618460-c40e9f80-656f-11eb-861b-326f33c2603f.png)

In the picture for packet 92773 I can see TCP retransmission from **non-k8s** `Node_A` (00:26:b5:02:a1:02) (10.1.1.3) to `Node_B` (00:26:b5:02:a1:12)(10.1.1.12) which seems to be OK.
But in the next packet 92774 i can see TCP retransmission from 'Node_B`(00:26:b5:02:a1:12) with src IP of Node_A`  (10.1.1.3) to IP of killed POD (172.26.58.228) but with dst MAC of Cisco ACI (00:22:bd:f8:19:ff).

## Context

The above described behavior causes the `rogue endpoint detection` mechanism to be called on Cisco ACI which is banning `rogue` IP traffic for 30 minutes  as it detects too many  packets with the  same IP but different MAC addresses.  
Can this be some misconfiguration of Calico VXLAN mode on k8s worker nodes? Do you have any insights what can be the issue? 
Any help is appreciated. `

## Your Environment

* Calico version : 3.14.0, 
* Orchestrator version: kubernetes v1.19.4, 
* Operating System and version: RHEL 7
