### ISSUE TITLE
IPAM inconsistencies and unreachable pods after Etcd restore

### ISSUE THREAD

**Issue by grandich** [projectcalico/calico#4374]
We are testing restore of Etcd data from backup for disaster recovery scenarios in our kubernetes on-premise cluster.

Kubernetes re-applied state correctly after restore, but Calico IPAM resulted in multiple inconsistencies and pods unreachable. In order to stabilize the cluster, we rebooted all workers to trigger reallocation of IPs and recover pod reachability.

Besides the correctness of this procedure and bug report, we need to know if there is some documentation for recommended backup/restore of Calico/Kubernetes Etcd shared datastore -- in this case restoring from several hours/days old backup.

Inconsistencies found after Etcd restore:

- IP addresses allocated without corresponding pod
- Pod with missing IP allocation
- IP address allocated to multiple pods
- Every time we reboot a worker node, higher IP addresses are re-allocated for the pods (maybe thats OK)

## Steps to Reproduce
- Create simple kubernetes app deployment
- Make etcd backup (kubernetes+calico data store)
- Delete deployment
- Stop kube-apiserver
- Restore etcd from backup
- Start kube-apiserver
- Pods are unreachable

## Your Environment
* Calico version 3.13.2
* Orchestrator version kubernetes installed with kubespray
* Operating System and version: Ubuntu 18
/etc/cni/net.d# cat 10-calico.conflist
{
  "name": "cni0",
  "cniVersion":"0.3.1",
  "plugins":[
    {
      "nodename": "dev-102-node-t05-1",
          "type": "calico",
      "log_level": "info",
      "etcd_endpoints": "...",
      "etcd_cert_file": "/etc/calico/certs/cert.crt",
      "etcd_key_file": "/etc/calico/certs/key.pem",
      "etcd_ca_cert_file": "/etc/calico/certs/ca_cert.crt",
      "ipam": {
        "type": "calico-ipam",
        "assign_ipv4": "true",
        "ipv4_pools": ["10.231.112.0/20"]
      },
      "policy": {
        "type": "k8s"
      },      "kubernetes": {
        "kubeconfig": "/etc/cni/net.d/calico-kubeconfig"
      }
    },
    {
      "type":"portmap",
      "capabilities":{
        "portMappings":true
      }
    }
  ]
}

## Current Behavior

UNREACHABLE IPs from within random node
```
# ping 10.231.121.129
connect: Invalid argument
# mtr 10.231.121.129
mtr: udp socket connect failed: Invalid argument


```
DUPLICATE IP ALLOCATIONS
```
default       httpenv-7b669df8b6-fmq7k                         1/1     Running   1          20d   10.231.126.3     dev-102-node-t01-2   <none>           <none>
default       httpenv-7b669df8b6-rxsnt                         1/1     Running   0          20d   10.231.126.5     dev-102-node-t01-2   <none>           <none>
default       httpenv-7b669df8b6-w87hn                         1/1     Running   0          20d   10.231.126.3     dev-102-node-t01-2   <none>           <none>

```
```
# calicoctl.sh ipam show --ip=10.231.126.1
IP 10.231.126.1 is in use
Attributes:
  namespace: default
  node: dev-102-node-t01-2
  pod: httpenv-7b669df8b6-w87hn

# calicoctl.sh ipam show --ip=10.231.126.2
IP 10.231.126.2 is in use
Attributes:
  pod: httpenv-7b669df8b6-rxsnt
  namespace: default
  node: dev-102-node-t01-2

# calicoctl.sh ipam show --ip=10.231.126.3
IP 10.231.126.3 is in use
Attributes:
  namespace: default
  node: dev-102-node-t01-2
  pod: httpenv-7b669df8b6-fmq7k
```

MISSING ALLOCATIONs

```
# kubectl get pod --all-namespaces -o wide |grep 10.231|grep t05-1
default       httpenv-7b669df8b6-zkq8p                         1/1     Running            1          20d   10.231.121.129   dev-102-node-t05-1   <none>           <none>

# calicoctl.sh ipam show --ip=10.231.121.129
10.231.121.129 is not assigned

```

UNMATCHED IP ALLOCATIONS
Various allocated IPs do not match any pod address

```
default       httpenv-7b669df8b6-fz49b                         1/1     Running            1          20d   10.231.118.198   dev-102-node-t01-1   <none>           <none>
default       httpenv-7b669df8b6-p8c7q                         1/1     Running            1          20d   10.231.118.197   dev-102-node-t01-1   <none>           <none>
default       httpenv-7b669df8b6-vgfm2                         1/1     Running            1          20d   10.231.118.196   dev-102-node-t01-1   <none>           <none>
kube-system   kubernetes-dashboard-556b9ff8f8-6v2jp            1/1     Running            1          20d   10.231.118.199   dev-102-node-t01-1   <none>           <none>

```

```
# calicoctl.sh ipam show --ip=10.231.118.193
IP 10.231.118.193 is in use
Attributes:
  namespace: default
  node: dev-102-node-t01-1
  pod: httpenv-7b669df8b6-vgfm2

# calicoctl.sh ipam show --ip=10.231.118.194
IP 10.231.118.194 is in use
Attributes:
  namespace: default
  node: dev-102-node-t01-1
  pod: httpenv-7b669df8b6-fz49b

# calicoctl.sh ipam show --ip=10.231.118.195
IP 10.231.118.195 is in use
Attributes:
  namespace: default
  node: dev-102-node-t01-1
  pod: httpenv-7b669df8b6-p8c7q

# calicoctl.sh ipam show --ip=10.231.118.196
IP 10.231.118.196 is in use
Attributes:
  namespace: default
  node: dev-102-node-t01-1
  pod: httpenv-7b669df8b6-vgfm2

# calicoctl.sh ipam show --ip=10.231.118.197
IP 10.231.118.197 is in use
Attributes:
  namespace: default
  node: dev-102-node-t01-1
  pod: httpenv-7b669df8b6-p8c7q

# calicoctl.sh ipam show --ip=10.231.118.198
IP 10.231.118.198 is in use
Attributes:
  namespace: default
  node: dev-102-node-t01-1
  pod: httpenv-7b669df8b6-fz49b

# calicoctl.sh ipam show --ip=10.231.118.199
IP 10.231.118.199 is in use
Attributes:
  namespace: kube-system
  node: dev-102-node-t01-1
  pod: kubernetes-dashboard-556b9ff8f8-6v2jp

```
