### ISSUE TITLE
Selector docs wrong

### ISSUE THREAD

**Issue by lwr20** [projectcalico/calico#438]
http://docs.projectcalico.org/v2.0/reference/calicoctl/resources/policy#selector says: 

k not in { ‘v1’, ‘v2’ }	Matches any endpoint with label ‘k’ and value not in the given set

This is not the case: if I have a policy like:
```
- apiVersion: v1
  kind: policy
  metadata:
    name: deny-test-true7
    tier: default
  spec:
    egress:
    - action: deny
      destination:
        selector: test not in {'true', 'false'}
      source: {}
    - action: allow
      destination: {}
      source: {}
    ingress:
    - action: deny
      destination: {}
      source:
        selector: test not in {'true', 'false'}
    - action: allow
      destination: {}
      source: {}
    selector: ""
```
and I have workload endpoints which do not have the 'test' label at all, their traffic matches the selector and is denied.

@fasaxc says the code is correct, but the docs are wrong.
