### ISSUE TITLE
Calico ebpf + wireguard packet drops

### ISSUE THREAD

**Issue by mlushpenko** [projectcalico/calico#4411]
## Current Behavior
Wireguard interface seems to be dropping packets:
```
 tc -s qdisc show dev wireguard.cali
qdisc noqueue 0: root refcnt 2
 Sent 0 bytes 0 pkt (dropped 0, overlimits 0 requeues 0)
 backlog 0b 0p requeues 0
qdisc clsact ffff: parent ffff:fff1
 Sent 10184841243 bytes 3670344 pkt (dropped 1103, overlimits 0 requeues 0)
 backlog 0b 0p requeues 0
```

And I couldn't find much in bpf debug logs, but after putting them back to `Info` level noticed these kind of messages:
```
         kubelet-5448    [000] .... 43491.309127: 0: CALI-C: NAT miss.
 elasticsearch[e-16767   [000] .... 43513.076161: 0: CALI-C: NAT miss.
```

And [calico-node.log](https://github.com/projectcalico/calico/files/6008524/calico-node.log) logs just in case.

## Possible Solution
Maybe disabling wireguard or disabling ebpf but that would require cluster redeployment which I hope to avoid.

## Steps to Reproduce (for bugs)
Setup kops cluster with the following calico settings:
```
networking:
  calico:
    mtu: 8941
    encapsulationMode: vxlan
    crossSubnet: true
    awsSrcDstCheck: Disable
    bpfEnabled: true
    wireguardEnabled: true
    bpfLogLevel: Info
```

Or these:

```
networking:
  calico:
    mtu: 8941
    encapsulationMode: ipip
    crossSubnet: true
    awsSrcDstCheck: Disable
    bpfEnabled: true
    wireguardEnabled: true
    bpfLogLevel: Info
```

## Context
We are running a platform where many components are talking to ElasticSearch and seeing intermittent disconnects all the time:

![image](https://user-images.githubusercontent.com/2006610/108473031-c9692b00-728d-11eb-8fbb-25d395e13100.png)

Two production clusters are affected right now as we haven't noticed the issue on time. Initial settings for calico ipPool:
```
spec:
    blockSize: 26
    cidr: 100.96.0.0/11
    ipipMode: CrossSubnet
    natOutgoing: true
    nodeSelector: all()
    vxlanMode: Never
```

Yesterday tried changing to vxlan as this [page](https://docs.projectcalico.org/maintenance/troubleshoot/troubleshoot-ebpf) suggests not to use IPIP mode, so one of the cluster has this Ippool setup but errors persist:
```
spec:
    blockSize: 26
    cidr: 100.96.0.0/11
    ipipMode: Never
    natOutgoing: true
    nodeSelector: all()
    vxlanMode: CrossSubnet
```

## Your Environment

* Calico version:
```
calicoctl version
Client Version:    v3.17.1
Git commit:        8871aca3
Cluster Version:   v3.17.1
Cluster Type:      kops,bgp,kdd,k8s
```
* Orchestrator version (e.g. kubernetes, mesos, rkt):
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-14T05:15:04Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
* Operating System and version:
```
Linux ip-10-151-38-111 5.4.0-1035-aws #37-Ubuntu SMP Wed Jan 6 21:01:57 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by mlushpenko** [comment]
Disabling wireguard improved situation a lot (errors are basically non-visible for our customer), but I still see the same errors in ElasticSearch every 2-3 hours about master node disconnected after failing 3 consecutive checks, so probably issue is partially related to ebpf data plane. (pods aren't getting restarted, just connection issues)

**Comment by mlushpenko** [comment]
Changing daemonset to this [image](https://github.com/projectcalico/calico/issues/4290#issuecomment-779701612) finally resolved the problem, current setup without errors:

```
calicoctl version
Client Version:    v3.17.1
Git commit:        8871aca3
Cluster Version:   v3.19.0-0.dev-13-ga9bbeb301daa-dirty
Cluster Type:      kops,bgp,kdd,k8s
```

IPPool:
```
spec:
    blockSize: 26
    cidr: 100.96.0.0/11
    ipipMode: Never
    natOutgoing: true
    nodeSelector: all()
    vxlanMode: CrossSubnet
```

FelixConfiguration:
```
spec:
    bpfLogLevel: ""
    ipipEnabled: true
    logSeverityScreen: Info
    reportingInterval: 0s
    vxlanEnabled: true
```

At one point during migration from IPIP encapsulation, VXLAN interface wasn't being created on nodes before until this option was addded to felixconfiguration: `vxlanEnabled: true` even though we expected `kops` to do that for us.

**Comment by song-jiang** [comment]
@fasaxc could you follow up and label this issue?

**Comment by fasaxc** [comment]
Can you tell me more about how elastic search is deployed?  Host or pod networked?  Where are the connections with problems going from and to?  How do the connections reach the cluster; service VIP?

**Comment by mlushpenko** [comment]
@fasaxc we've used the image that you've built `fasaxc/calico-node:ct-syns-2`. Elasticsearch is deployed as pod networking, infrastructure is on AWS. Yeah, service VIP is used to reach elasticsearch, no ingresses/loadbalancers, just internal kubernetes traffic. `v3.18` maybe would solve the issue but as we rely on kops fro deployments and it doesn't seem to allow specifying the version, I am not eager to experiment right now on production as it seems to be stable since the latest changes that I've posted above.

Was hoping that together with the info from https://github.com/projectcalico/calico/issues/4290 and a bit of debugging info I've provided here would be enough to confirm or discard certain bug, sorry if that's too little.

**Comment by fasaxc** [comment]
Does `fasaxc/calico-node:ct-syns-2` fix the issue for you?  That change has merged now.

**Comment by mlushpenko** [comment]
@fasaxc yes, it did, together with disabling wireguard.  So, now waiting for next kops releases that would include that version

**Comment by fasaxc** [comment]
Does it work if you re-enable wireguard?

**Comment by mlushpenko** [comment]
I don't think so. That was my first step to try that image - didn't work. Then I disabled wire guard - less errors but didn't work still. Then I tried image again with disabled wire guard and errors went away

**Comment by fasaxc** [comment]
Are the disconnects after the connection has been open for a long time?  BPF mode has connection timeouts to clean up the BPF conntrack table, for example.

**Comment by fasaxc** [comment]
> see the same errors in ElasticSearch every 2-3 hours about master node disconnected after failing 3 consecutive checks

Are the checks once per hour?  I think our connection timeout is an hour with no packets so you could hit that.

**Comment by mlushpenko** [comment]
> Are the checks once per hour? I think our connection timeout is an hour with no packets so you could hit that.

If I am not mistaken, checks are done as discovery mechanism all the time, not sure about exact frequency but probably something like once per minute. All the settings [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-discovery-settings.html) are in terms of seconds and we didn't configure anything special.

**Comment by fasaxc** [comment]
```
qdisc clsact ffff: parent ffff:fff1
 Sent 10184841243 bytes 3670344 pkt (dropped 1103, overlimits 0 requeues 0)
```
Does suggest that our BPF program is dropping packets.

```
CALI-C: NAT miss.
```
Is normal; that just means that a particular connection was not NATted.

I'd expect this log if the BPF program drops a packet:
```
Final result=DENY ...
```
do you see that in the BPF trace?  We'd need some context around the log too to figure out what went wrong.

**Comment by fasaxc** [comment]
@mlushpenko I've set up a BPF/wg cluster and provisioned an Elastic cluster with ECK.  What should I expect to see now; how can i see the errors?  What do I need to do to trigger an error?

**Comment by mlushpenko** [comment]
@fasaxc we have setup where ES nodes are on different nodes (sometimes also in different zones, but not the case for the  clusters where we've noticed issues). I don't believe platform load has any affect on this, so likely you will start seeing errors pretty soon as it is discovery for ES that is failing. MTU values are the same 8941? Apart from that, not sure what other conditions are needed. I could provide kops template optionally.

Maybe a week ago we've updated cluster via kops and calico image was reverted to the original one and errors came back. So, at least behaviour is consistent.

Values for `elastic/elasticsearch` chart version `7.5.1`:

```
podAnnotations:
  iam.amazonaws.com/role: k8s-elasticsearch
esJavaOpts: -Xms4g -Xmx4g
resources:
  requests:
    memory: 4Gi
    cpu: 512m
  limits:
    cpu: 2000m
    memory: 5Gi
persistence:
  enabled: true
volumeClaimTemplate:
  storageClassName: gp3
  resources:
    requests:
      storage: 50Gi
rbac:
  create: true
podSecurityPolicy:
  enabled: true
securityContext:
  runAsUser: 1000
esConfig: # log level can be TRACE to get even more data
  elasticsearch.yml: |
    xpack.monitoring.collection.enabled: true
    script.allowed_types: inline, stored
    logger.org.elasticsearch.cluster: INFO
esMajorVersion: 7
imagePullPolicy: "IfNotPresent"
clusterName: elasticsearch
roles: # that's the default
  master: "true"
  data: "true"
  ingest: "true"
updateStrategy: RollingUpdate # that's the default
replicas: 3
nodeSelector:
  type: es-instance
tolerations:
  - key: type
    operator: Equal
    value: es-instance
    effect: NoSchedule
maxUnavailable: 1
antiAffinity: "hard"
```

**Comment by fasaxc** [comment]
@mlushpenko thanks for the follow-up.  Where would I see the errors?  Would they be in the ES logs?

**Comment by mlushpenko** [comment]
Yes, you should see in ES logs that nodes are failing and being added/removed to the cluster, I can't find proper stacktrace in kibana right now, but see at least this message from the period when they were failing

![image](https://user-images.githubusercontent.com/2006610/114882009-ca3cba00-9e03-11eb-8254-b75456d269b3.png)

**Comment by fasaxc** [comment]
I don't see this on a kubeadm cluster on GCP, using wireguard.  It's a small cluster with only Elastic running on it.  @mlushpenko can you tell us more about your cluster?  Where is it running, how did you set it up?  What's the underlying network?

**Comment by mlushpenko** [comment]
@fasaxc you used wireguard and ebpf together, right? Apparently, it also happens just with ebpf, as current settings on one of the clusters that was failing recently (until image is changed back manully) are these:
```
networking:
    calico:
      awsSrcDstCheck: Disable
      bpfEnabled: true
      bpfLogLevel: Info
      crossSubnet: true
      encapsulationMode: vxlan
      ipipMode: Never
      mtu: 8941
```

just realised that in this case MTU should probably be 8951 according to this [table](https://docs.projectcalico.org/networking/mtu#determine-mtu-size). Would you expect packet drops due to that? But if MTU would be the cause, then new image wouldn't help, right?

Do you want full kops state file? (you'll need to change some values)

We use calico CNI as defined [here](https://github.com/kubernetes/kops/blob/master/docs/networking/calico.md) and I've provided our settings.
