### ISSUE TITLE
Problem with the Manifest for Calico Kubernetes Hosted Install with Kubeadm

### ISSUE THREAD

**Issue by lslatr** [projectcalico/calico#442]
When installing Kubernetes with kubeadm on real hardware (running ubuntu) there is a problem with the [manifest file](http://docs.projectcalico.org/v2.0/getting-started/kubernetes/installation/hosted/kubeadm/calico.yaml).  It turns on IPIP for containers but kubeadm sets up the api server to run with host networking as a result containers can't talk to the api server.  Turning off IPIP fixes the problem for me.

```
  ippool.yaml: |
      apiVersion: v1
      kind: ipPool
      metadata:
        cidr: 172.16.0.0/16
      spec:
        nat-outgoing: true
```

Is there a reason that IPIP is enabled by default?
