### ISSUE TITLE
Netplan config for MetalLB overridden by dataplane updates 

### ISSUE THREAD

**Issue by FerdinandvHagen** [projectcalico/calico#4455]
## Context
We are setting up a kubernetes cluster on bare metal servers. The servers are connected on a VLAN and a public subnet is available for the VLAN for servers to dynamically retrieve public IPs. MetalLB manages and announces the assignment of those public IPs.

## Expected Behavior
IP addresses assigned and announced by MetalLB should be routed to the correct Service with type Loadbalancer and the node/loadbalancer/pod should react to service and ICMP requests on the publicly announced IP.

## Current Behavior
MetalLB correctly announces and assigns the IP to the node in layer2 mode. The netplan config used for the VLAN and to route the subnets is attached at the end. 
Without Calico or Calico with a version lower than v3.14.0 service and ICMP requests are correctly answered.
Starting with Calico v3.14.0 running `netplan apply` temporarily allows service and ICMP requests through, but connections are broken after a couple of seconds. This happens at the moment where felix applies dataplane updates after having checked CIDRs and interfaces.

## Possible Solution
It seems like felix is overwriting the netplan configuration when updating the dataplane. However I couldn't yet figure out how to prevent this from happening or configure calico to apply the netplan configuration. Setting `chainInsertMode: Append` or `xdpEnabled: false` did not solve the issue (if the config via calicoctl did work).
Is this an issue that can be solved by a special configuration or is there something that must be changed in felix?

## Steps to Reproduce (for bugs)
1. Node(s) connected to VLAN with public subnet routed into the VLAN
2. Set netplan config to route the ips from the public subnet
2. Create Loadbalancer and assign public IP with Metallb
3. Check that MetalLB correctly announces IP with arping
3. Ping the assigned public IP --> no response
4. Run `netplan apply` on the node where the IP is announced
5. Ping the assigned public IP --> Responses run for up to 90 seconds and then stop

## Your Environment

* Calico version: v3.16.6 but issue exists since v3.14.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes v1.19.8
* Operating System and version: Ubuntu 20.04

Thank you very much,

Ferdinand

## Netplan config
```
network:
  version: 2
  vlans:
    # Configure vSwitch vswitch
    enp4s0.4000:
      id: 4000
      link: enp4s0
      mtu: 1400
      addresses: ["10.233.255.1/24"]
      routes:
        - to: 0.0.0.0/0
          via: 168.119.132.73
          table: 1
          on-link: true
      routing-policy:
        - from: 168.119.132.72/29
          to: 10.233.0.0/18
          table: 254
          priority: 0
        - from: 168.119.132.72/29
          to: 10.233.64.0/18
          table: 254
          priority: 0
        - from: 168.119.132.72/29
          table: 1
          priority: 10
        - to: 168.119.132.72/29
          table: 1
          priority: 10
```
