### ISSUE TITLE
The generated route is not using tunl0 if there are multiple next hops when ipipMode is Always

### ISSUE THREAD

**Issue by JimmyMa** [projectcalico/calico#4462]
In my cluster, the ipipMode is Always for IP Pool 198.19.0.0/16, as below: 

```
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: controlplane-services-cidr
spec:
  blockSize: 26
  cidr: 198.19.0.0/16
  disabled: true
  ipipMode: Always
  nodeSelector: all()
  vxlanMode: Never
```

When there are multiple next hops, below routes are generated, and they are not using tunl0

```
198.19.0.0/16 proto bird
	nexthop via 10.240.1.57 dev ens3 weight 1
	nexthop via 10.240.1.58 dev ens3 weight 1
```

When there is only one next hop, below route is generated, and it's using tunl0:

```
198.19.0.0/16 via 10.240.3.49 dev tunl0 proto bird onlink
```

## Expected Behavior
I hope it generates the routes with `tunl0` as below when there are multiple next hops 

```
198.19.0.0/16 proto bird
	nexthop via 10.240.1.57 dev tunl0 weight 1
	nexthop via 10.240.1.58 dev tunl0 weight 1
```

## Context

I have two k8s clusters, and each cluster has a node as route reflector, and the two route reflectors are peered. Each cluster broadcasts its service cidr to other cluster, and I need all traffic are IPIP.

## Your Environment

* Calico version: 3.17
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes
* Operating System and version: 4.15.0-109-generic #110-Ubuntu SMP Tue Jun 23 02:39:32 UTC 2020 x86_64 Linux
