### ISSUE TITLE
Mixed (calico and k8s) policies not applied correctly?

### ISSUE THREAD

**Issue by zetaab** [projectcalico/calico#4474]
We are trying to follow principles which are defined here https://docs.projectcalico.org/about/about-network-policy#mix-kubernetes-and-calico-network-policy which means that cluster operators could define globalnetworkpolicy using calicos resources. Then teams itself could use kubernetes networkpolicies.

I am testing test-case which is following:

```
apiVersion: crd.projectcalico.org/v1
kind: GlobalNetworkPolicy
metadata:
  name: default-deny-cloud-metadata
spec:
  order: 10
  types:
  - Egress
  egress:
  - action: Deny
    destination:
      nets:
      - 169.254.169.254/32
---
apiVersion: crd.projectcalico.org/v1
kind: GlobalNetworkPolicy
metadata:
  name: allow-all
spec:
  order: 5000
  types:
  - Egress
  egress:
  - action: Allow
    destination:
      nets:
      - 0.0.0.0/0
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: testing-policy
  namespace: default
spec:
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 104.21.192.7/32
  podSelector: {}
  policyTypes:
  - Egress
```

## Expected Behavior

I expect that ips `169.254.169.254/32` and `104.21.192.7/32` are blocked in `default` namespace and others allowed

## Current Behavior

In default namespace `169.254.169.254/32` is blocked but `104.21.192.7/32` works fine.

## Possible Solution

I can get this `104.21.192.7` blocked by adding another rule:

```
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: deny-test
  namespace: default
spec:
  order: 20
  types:
  - Egress
  egress:
  - action: Deny
    destination:
      nets:
      - 104.21.192.7/32
```
However, like I said we want to allow normal users only use kubernetes networkpolicies, and now it looks like that it does not work as we expect.

## Steps to Reproduce (for bugs)

1. install manifest mentioned in this issue
2. try to curl addresses

## Your Environment

* Calico version 3.18.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes / kops
* Operating System and version: debian buster
* Link to your project (optional):

**Comment by lwr20** [comment]
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: testing-policy
  namespace: default
spec:
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 104.21.192.7/32
  podSelector: {}
  policyTypes:
  - Egress
```
