### ISSUE TITLE
Kubernetes probes fail with auto created host endpoints

### ISSUE THREAD

**Issue by qvicksilver** [projectcalico/calico#4478]
## Expected Behavior
Tried following this blog post: https://www.projectcalico.org/securing-kubernetes-nodes-with-calico-automatic-host-endpoints/ to test using auto created host endpoints.

Expected external traffic that was not explicitly allowed to be blocked and internal kubernetes traffic to be unaffected.

## Current Behavior
When applying the global network policies external traffic that is not explicitly allowed is blocked as expected. However so is lots of internal traffic as well. For example liveness and readiness probes from the kubelet start failing as well as requests from api-server to kubelets.

## Possible Solution
Manually created host endpoints targeting specific interfaces seem to work as expected.

## Steps to Reproduce (for bugs)

1. Install cluster using Kubespray 2.15.0 on bare metal using Calico for CNI/policy
2. Follow instructions in the blog
3. Watch probes fail

## Context

Currently it is mostly annoying since we can work around the issue using manually created host endpoints.

## Your Environment

* Calico version: 3.16.5
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes 1.19.7
* Operating System and version: Ubuntu 20.04
Hosts are bare metal and multihomed

**Comment by bjetal** [comment]
The main issue here seems to be that automatically created host endpoints apply to all of the hosts interfaces, including the loopback interface.  The fact that they also apply to Calico's own interfaces might cause some weird behaviors in some edge cases.

I've been working around this by adding specific GlobalNetworkPolicies for the probe ports (e.g. 10257 and 10259 for kube-controller-manager and kube-scheduler).

**Comment by bjetal** [comment]
I should add this is only a problem for pods running in the host network (`hostNetwork: true`) like the kubernetes control plane pods and nodelocaldns (see https://github.com/projectcalico/calico/issues/3795)

**Comment by mskel003** [comment]
hi bjetal, I seem to have encountered the same issue after working with nodelocaldns on my migrated flannel split-wan cluster.
I have removed nodelocaldns while looking for a solution, but the reason I have been using nodelocaldns is to work around the known rhel7 udp race condition on our dns (nodelocaldns fixes that issue as it upgrades dns from udp to tcp).

Can you share your GlobalNetworkPolicy files you have used to get around this issue?

**Comment by mskel003** [comment]
Ahh i have found the thread mentioning that it may be fixed with this:
https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/nodelocaldns/README.md#network-policy-and-dns-connectivity
I'll try that

**Comment by bjetal** [comment]
My approach was a little different and works if you want to access the nodelocaldns from the host network and not just from pods.  Here is the GNP I created for this:
```
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: nodelocaldns
spec:
  selector: has(kubernetes.io/hostname)
  order: 5
  types:
  - Ingress
  ingress:
  - action: Allow
    metadata:
      annotations:
        traffic: nodelocaldns request
    protocol: UDP
    destination:
      ports: [53]
      nets: [169.254.25.10/32]
  - action: Allow
    metadata:
      annotations:
        traffic: nodelocaldns response
    protocol: UDP
    source:
      ports: [53]
      nets: [169.254.25.10/32]
  - action: Allow
    metadata:
      annotations:
        traffic: nodelocaldns TCP request
    protocol: TCP
    destination:
      ports: [53]
      nets: [169.254.25.10/32]
  - action: Allow
    metadata:
      annotations:
        traffic: nodelocaldns TCP response
    protocol: TCP
    source:
      ports: [53]
      nets: [169.254.25.10/32]
  - action: Allow
    metadata:
      annotations:
        traffic: nodelocaldns internal/health check
    protocol: TCP
    destination:
      ports: [9254]
      nets: [169.254.25.10/32]
    source:
      nets: [169.254.25.10/32]
```

**Comment by bjetal** [comment]
I finally figured out one way to solve this problem is to create a host end point for each host's loopback (lo) interface and allow all traffic in and out on that interface.  The problem with this solution is that these HostEndpoint objects are node specific, which means as nodes get added and removed, they need to be kept up to date.  I'd really love for something like this to be added to the automatic host endpoint creation functionality already in Calico.

**Comment by mskel003** [comment]
Thanks bjetal. I have configured our environment to not use nodelocaldns for now. Instead its now managed through ansible when we tear-down and recreate the cluster –
..making sure the clear the “iptables -t nat” “iptables -t mangle” “iptables -t raw” so calico can start fresh – as it doesn’t fully clean these tables when there is an init/join.

**Comment by yelhouti** [comment]
@bjetal could you please share with me how you created the interafce and how you allowed traffic ? also how is what you are suggesting different from using the existing endpoints which have interface * and the public IP. ie:
```
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: allow-cluster-internal-ingress
spec:
  order: 10
  preDNAT: true
  applyOnForward: true
  ingress:
    - action: Allow
      source:
        nets: [10.233.64.0/18]
    - action: Allow
      source:
        selector: has(host-endpoint)
  selector: has(host-endpoint)
```

**Comment by bjetal** [comment]
@yelhouti 
For each host we create a calico HostEndpoint with the following settings:
```
metadata:
  name: <hostname>-lo
  labels:
    interface: loopback
spec:
  node: <hostname>
  interfaceName: lo
```

Then we create a GlobalNetworkPolicy like the following:

```
metadata:
  name: loopback
spec:
  selector: interface == 'loopback'
  order: 0
  types:
  - Ingress
  - Egress
  ingress:
  - action: Allow
  egress:
  - action: Allow
```
