### ISSUE TITLE
NetworkPolicy with podSelector not working when hostNetwork: true?

### ISSUE THREAD

**Issue by jbnjohnathan** [projectcalico/calico#4493]
## Expected Behavior
Using the following code

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: monitoring-network-policy-prometheus
  namespace: monitoring
spec:
  podSelector:
    matchLabels:
      app: prometheus
  policyTypes:
    - Egress
  egress:
    - to:
      - namespaceSelector:
          matchLabels:
            name: kube-system
      - podSelector:
          matchLabels:
            k8s-app: aws-node
      ports:
        - protocol: TCP
          port: 61678
```
I expect that traffic is allowed outbound from the prometheus pod towards the aws-node pod on prot 61678

## Current Behavior
The above code is not allowing the outbound traffic.
If I use the below instead it works. But this creates a rule that is too wide.
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: monitoring-network-policy-prometheus
  namespace: monitoring
spec:
  podSelector:
    matchLabels:
      app: prometheus
  policyTypes:
    - Egress
  egress:
    - to:
      ports:
        - protocol: TCP
          port: 61678
```

## Possible Solution
This issue is not for all pods, but seems to be for pods that have `hostNetwork: true`.
For example the `aws-node` and `prometheus-node-exporter` pods.

## Steps to Reproduce (for bugs)

1. Deploy an AWS EKS cluster
2. Deploy calico
2.1 (optional) Deploy Prometheus
3. Apply the first manifest mentioned above
4. Confirm that traffic which should have matched the rule is not allowed
5. Open for only the port and confirm that it works.

## Context
Allow traffic from the Prometheus pod to specific pods on specific ports in order to have Prometheus scrape them.

## Your Environment

* Calico version: v3.17.1, 
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes 1.18 (AWS EKS)
* Operating System and version: AWS linux 2
* Link to your project (optional):
