### ISSUE TITLE
Failure in name resolutions after applying ingress policy

### ISSUE THREAD

**Issue by cazorla19** [projectcalico/calico#4523]
When applying Calico network policy, the DNS resolver connection gets lost. The application that runs on the selected pod can't resolve DNS records any longer.

Here's the ingress policy I'm trying to apply in order to allow access from (only) ingress and a couple of other pods.

```yaml
---
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: my-service
  namespace: my-service
spec:
  selector: app == 'my-service'
  ingress:
  # Allow Nginx Ingress Controller
  - action: Allow
    protocol: TCP
    source:
      selector: app.kubernetes.io/name == 'ingress-nginx'
      namespaceSelector: domain == 'system'
    destination:
      ports:
      - 8080                                                                             
  - action: Allow
    protocol: TCP
    source:
      selector: app == 'dependent-service'
      namespaceSelector: app == 'dependent-service'
    destination:
      ports:
      - 8080
  - action: Allow
    nets:                                                                               
    - 10.30.0.0/24
    # nameserver IP address                                                                            
    - 10.100.0.10/32
```

## Expected Behavior

The policy will restrict ingress access to the pod, but DNS resolution would still work.

## Current Behavior

Getting errors from different applications and different libraries

```
{"time": "2021-04-12T14:25:05.150+00:00", "service": "my-service", "proc": 19, "lvl": "WARNING", "line": 479, "name": "newrelic.core.data_collector", "req_id": "", "seq_id": "", "msg": "Data collector is not contactable. This can be because of a network issue or because of the data collector being restarted. In the event that contact cannot be made after a period of time then please report this problem to New Relic support for further investigation. The exception raised was ConnectionError(ProtocolError('Connection aborted.', gaierror(-3, 'Temporary failure in name resolution'))).", "tags": {}}

{"asctime": 2021-04-12 07:15:53,822, "service_name": "my-service", "process": "MainProcess", "levelname": "ERROR", "lineno": "421", "name": "celery.worker.consumer.consumer", "message": "consumer: Cannot connect to rediss://:**@my_redis_host:6379//: Error -3 connecting to my_redis_host:6379. Temporary failure in name resolution..
Trying again in 2.00 seconds... (1/100)
```

Temporary failure in name resolution = No known DNS was able to answer with the IP address of target domain.

The issue disappears once the network policy gets deleted.

## Steps to Reproduce (for bugs)

1. Deploy the network policy from this issue adjusted to your application
2. Restart the application (i.e. delete pod)
3. Observe application logs in the initialization stage when it tries to connect to any data storage or anything else that needs to be resolved by DNS.

## Context

I'm trying to apply network restrictions only to ingress side, leaving egress access the way it is. I'm trying to achieve the state when the application is functioning as it would do so without network policy, but only declared dependent services could access the app.

## Your Environment

* **Calico version**: `v3.15.1`
* **Kubernetes version**:  `Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.6-eks-49a6c0", GitCommit:"49a6c0bf091506e7bafcdb1b142351b69363355a", GitTreeState:"clean", BuildDate:"2020-12-23T22:10:21Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}`
* **Network Policy API being used**: crd.projectcalico.org/v1
