### ISSUE TITLE
Feature: Implement full policy model in kubernetes

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico#458]
This needs some design, but likely this means implementing as a ThirdPartyResource alongside the NetworkPolicy object and supported both sources of policy implementation.

This would support features like the following, which only exist in the Calico API (not in k8s):

- Ordering
- CIDR based policy
- Egress policy

There are two main scenarios that would need to support the TPR:

**etcd datastore + policy controller**

In this mode, we'd augment the [Calico policy controller](https://github.com/projectcalico/k8s-policy) to read in the TPRs and populate etcd with the correct data to implement it in the Calico API.

**kubernetes datastore driver**

In this mode, libcalico-go is [backed directly by the k8s API](https://github.com/projectcalico/libcalico-go/blob/master/lib/backend/k8s/conversion.go#L263).  The TPR would appear as a Policy in the Calico API.

The main question here I think is what does the TPR look like?

I see two main options:
1. Make it look like the `extensions.NetworkPolicy` resource from the k8s API.
2. Make it look like the [v1.Policy](http://docs.projectcalico.org/v2.0/reference/calicoctl/resources/policy) resource from the Calico API.

I'm leaning towards option 2, since it will get us the full flexibility of the Calico API easier than converting to/from NetworkPolicy syntax, and probably needs less work to implement.

**Comment by caseydavenport** [comment]
Example schema proposal below.  This is just a 1:1 copy of the Calico v1.Policy schema discussed here: http://docs.projectcalico.org/v2.0/reference/calicoctl/resources/policy

```
apiVersion: projectcalico.org/v1
kind: Policy
metadata:
  name: allow-tcp-6379
spec:
  selector: role == 'database'
  ingress:
  - action: allow 
    protocol: tcp
    source:
      selector: role == 'frontend'
    destination:
      ports:
      - 6379
  egress:
  - action: allow
```
