### ISSUE TITLE
Calico for windows network issue with BGP networking on RKE cluster

### ISSUE THREAD

**Issue by vgaurihar** [projectcalico/calico#4595]
**Calico for windows network issue with BGP networking on RKE cluster**

## Expected Behavior

While configuring calico for windows on RKE cluster(provisioned by Rancher Dashboard), I followed official documentation
https://docs.projectcalico.org/getting-started/windows-calico/kubernetes/rancher
In this case we have used BGP networking
https://docs.projectcalico.org/getting-started/windows-calico/quickstart#install-calico-for-windows
The Expected behavior would be ConnectivityStatus should be `Connected` for all windows and linux nodes. This causing the  issue that the windows pod can not communicate with service/pod which is running on linux node

## Current Behavior

```
Get-BgpPeer

PeerName         LocalIPAddress PeerIPAddress PeerASN OperationMode ConnectivityStatus
--------         -------------- ------------- ------- ------------- ------------------
Mesh_****                 ****    WindowsNode2   64512   Mixed         Connected
Mesh_****                 ****    LinuxNode1   64512   Mixed         Connecting
Mesh_****                 ****    LinuxNode2   64512   Mixed         Connecting
Mesh_****                 ****    LinuxNode3   64512   Mixed         Connecting
Mesh_****                 ****    LinuxNode4   64512   Mixed         Connecting
Mesh_****                 ****    LinuxNode5   64512   Mixed         Connecting
Mesh_****                 ****    LinuxNode6   64512   Mixed         Connecting
Mesh_****                 ****    LinuxNode7   64512   Mixed         Connecting
Mesh_****                 ****    LinuxNode8   64512   Mixed         Connecting
```
![Screenshot from 2021-05-06 15-20-22](https://user-images.githubusercontent.com/8803900/117278783-af97b700-ae7e-11eb-956a-0d2ff286d201.png)

## Steps to Reproduce (for bugs)
1. Provision RKE cluster(all linux nodes) with Calico as plugin from Rancher Manager Dashboard (BGP peering and IPIP overlay)
2. Try to register windows nodes into the RKE cluster by configuring `Calico For Windows` with BGP networking model
Ref: - https://docs.projectcalico.org/getting-started/windows-calico/kubernetes/rancher
3. After registering the windows nodes into the  RKE cluster, try to communicate from windows pod to one of service/pod running on linux nodes internally (as shown in the diagram)

## Context

We are trying to setup windows logging with loki-promtail. For that windows-promtail configured  as a daemonset  and then trying to send logs from windows promtail pods to loki for segregation (here loki service internal fqdn - `loki-loki.loki-loki.svc.cluster.local`)

## Your Environment
* Calico version =  v3.18.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): v1.19.6
* Operating System and version: RHEL8.2 / Windows Server 2019
* Link to your project (optional): - https://rancher.com/docs/rke/latest/en/

Please find attached files 
i) calico-confd-err.log
ii) calico-config_linux_rke
iii) calico-config-windows
iv) calico-node.log

[calico-confd-err.log](https://github.com/projectcalico/calico/files/6433497/calico-confd-err.log)
[calico-config_linux_rke.txt](https://github.com/projectcalico/calico/files/6433499/calico-config_linux_rke.txt)
[calico-config_windows.txt](https://github.com/projectcalico/calico/files/6433500/calico-config_windows.txt)
[calico-node.log](https://github.com/projectcalico/calico/files/6433501/calico-node.log)

**Comment by vgaurihar** [comment]
@lwr20 could you please assist in this?

**Comment by lwr20** [comment]
@song-jiang is the windows expert.

A couple of questions from me though - is there anything blocking BGP (TCP port 179) between nodes in your network?  What does the BGP status look like from the Linux nodes?  i.e. run `calicoctl node status` on one of your linux nodes.

You say you're using BGP and IPIP overlay in your cluster, but the windows quickstart says this mode is explicitly NOT supported.  https://docs.projectcalico.org/getting-started/windows-calico/quickstart#before-you-begin
> Networking must be VXLAN or BGP without encapsulation. (Note: for EKS, networking is set to none since AWS VPC networking is used.)

**Comment by song-jiang** [comment]
Can you try to access pod ip between linux pod and windows pod? Maybe this is an kube-proxy issue.

As @lwr20 said, IPIP is not supported on Windows.

**Comment by vgaurihar** [comment]
Hi @song-jiang and @lwr20 
Sorry for late reply. Thanks for your suggestions. 
I patch up the bgp Ipv4 address for each windows nodes. Now the BGP peer status showing connections are Established, 
but connectivity from linux pod/service to windows pod/service and vice versa still not working
```
./calicoctl node status
Calico process is running.

IPv4 BGP status
+--------------+-------------------+-------+----------+-------------+
| PEER ADDRESS |     PEER TYPE     | STATE |  SINCE   |    INFO     |
+--------------+-------------------+-------+----------+-------------+
| xx.xxx.x.21  | node-to-node mesh | up    | 09:36:48 | Established |
| xx.xxx.x.22  | node-to-node mesh | up    | 09:36:48 | Established |
| xx.xxx.x.12  | node-to-node mesh | up    | 09:36:48 | Established |
| xx.xxx.x.13  | node-to-node mesh | up    | 09:36:49 | Established |
| xx.xxx.x.31  | node-to-node mesh | up    | 09:36:48 | Established |
| xx.xxx.x.32  | node-to-node mesh | up    | 09:36:48 | Established |
| xx.xxx.x.33  | node-to-node mesh | up    | 09:36:50 | Established |
| xx.xxx.x.41  | node-to-node mesh | up    | 09:57:32 | Established |   Windows node1
| xx.xxx.x.42  | node-to-node mesh | up    | 10:07:49 | Established |   Windows node2
+--------------+-------------------+-------+----------+-------------+

IPv6 BGP status
No IPv6 peers found.
```

- from windows pod to linux pod connectivity test
```
PS C:\Users\Administrator> kubectl -n logging exec -it loki-promtail-win-7zfkd -- powershell
PS C:\Loki> ping xx.xx.xxx.17

Pinging xx.xx.xxx.17 with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
```

**Comment by vgaurihar** [comment]
Following are my findings 
ICMP may be blocked some reason

1. Windows Pod <-> Windows Pod: Is it available?(Ping/Curl)
```
PS C:\Users\Administrator> kubectl.exe get pods -n logging -o wide
NAME                      READY   STATUS    RESTARTS   AGE   IP             NODE       NOMINATED NODE   READINESS GATES
loki-promtail-win-7zfkd   1/1     Running   1          25d   xx.xx.xxx.89   cpocww01   <none>           <none>
loki-promtail-win-j6rzq   1/1     Running   0          25d   xx.xx.xxx.80   cpocww02   <none>           <none>
PS C:\Users\Administrator>

PS C:\Loki> ping  xx.xx.xxx.89

Pinging xx.xx.xxx.89 with 32 bytes of data:
Reply from xx.xx.xxx.89: bytes=32 time<1ms TTL=128
Reply from xx.xx.xxx.89: bytes=32 time<1ms TTL=128
Reply from xx.xx.xxx.89: bytes=32 time<1ms TTL=128

Ping statistics for xx.xx.xxx.89:
    Packets: Sent = 3, Received = 3, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms
Control-C
PS C:\Loki>
```

2. Windows Pod --> Service -> Linux Pod and Windows Pod: Is it available from Linux Pod and Windows Pod?(Ping/Curl)
    Ans: The linux service (loki-stak) connecting from windows pod (loki-promtail-win)

```
PS C:\Users\Administrator> kubectl.exe get svc -n loki-stack -o wide
NAME                  TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)          AGE    SELECTOR
loki-grafana          ClusterIP   xx.xx.xxx.18   <none>        80/TCP           37d    app.kubernetes.io/instance=loki-grafana,app.kubernetes.io/name=grafana
loki-stack            NodePort    xx.xx.xxx.58   <none>        3100:xxxxx/TCP   121d   app=loki,release=loki-stack
loki-stack-headless   ClusterIP   None           <none>        3100/TCP         121d   app=loki,release=loki-stack
PS C:\Users\Administrator>

PS C:\Loki> Test-NetConnection "xx.xx.xxx.58" -DiagnoseRouting -InformationLevel Detailed
ComputerName                      : xx.xx.xxx.58
RemoteAddress                     : xx.xx.xxx.58
SelectedSourceAddress             : xx.xx.xxx.89
OutgoingInterfaceIndex            : 37
SelectedNetRoute                  : DestinationPrefix: 0.0.0.0/0
                                    NextHop: xx.xx.xxx.66
DestinationAddressSelectionEvents :
RouteSelectionEvents              :
SourceAddressSelectionEvents      :
RouteDiagnosticsSucceeded         : True
```

3. Windows BGB connection(Get-BGPPeer)?
```
PS C:\Users\Administrator> Get-BGPPeer

PeerName         LocalIPAddress PeerIPAddress PeerASN OperationMode ConnectivityStatus
--------         -------------- ------------- ------- ------------- ------------------
Mesh_xx_xxx_xx_11 xx.xxx.x.41    xx.xxx.x.11   64512   Mixed         Connected
Mesh_xx_xxx_xx_12 xx.xxx.x.41    xx.xxx.x.12   64512   Mixed         Connected
Mesh_xx_xxx_xx_13 xx.xxx.x.41    xx.xxx.x.13   64512   Mixed         Connected
Mesh_xx_xxx_xx_21 xx.xxx.x.41    xx.xxx.x.21   64512   Mixed         Connected
Mesh_xx_xxx_xx_22 xx.xxx.x.41    xx.xxx.x.22   64512   Mixed         Connected
Mesh_xx_xxx_xx_31 xx.xxx.x.41    xx.xxx.x.31   64512   Mixed         Connected
Mesh_xx_xxx_xx_32 xx.xxx.x.41    xx.xxx.x.32   64512   Mixed         Connected
Mesh_xx_xxx_xx_33 xx.xxx.x.41    xx.xxx.x.33   64512   Mixed         Connected
Mesh_xx_xxx_xx_42 xx.xxx.x.41    xx.xxx.x.42   64512   Mixed         Connected
```

**Comment by lwr20** [comment]
You can't ping to service IPs in kubernetes.  You'll need to use curl or the windows equivalent.

**Comment by song-jiang** [comment]
Can you access Linux pod by a Windows pod via Pod IP? I don't see the output from your log above.

**Comment by vgaurihar** [comment]
> Can you access Linux pod by a Windows pod via Pod IP? I don't see the output from your log above.

No, I can't 
- from windows loki-promtail-win pod to linux loki-stack pod
```
PS C:\Loki> New-Object System.Net.Sockets.TcpClient("xx.xx.xxx.58", 3100)
New-Object : Exception calling ".ctor" with "2" argument(s): "A connection attempt failed because the connected party did not properly respond after a period of time, or
established connection failed because connected host has failed to respond xx.xx.xxx.58:3100"
At line:1 char:1
+ New-Object System.Net.Sockets.TcpClient("xx.xx.xxx.58", 3100)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodInvocationException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand
```
- linux pod to windows pod 
```
kubectl -n loki-stack run -i --tty busybox --image=busybox --restart=Never -- sh
If you don't see a command prompt, try pressing enter.
/ # ping xx.xx.xx.98
PING xx.xx.xxx.98 (xx.xx.xxx.98): 56 data bytes
```

**Comment by song-jiang** [comment]
It could be a routing issue. I saw errors in calico-confd-err.log . Could you verify if you see routes from your Linux node  to windows pod cidr by executing `ip r` ?

**Comment by vgaurihar** [comment]
@song-jiang Sorry for late reply
I tried to change from bgp to vxlan on both windows and linux nodes(RKE)

**- Windows**
Calico Networking Backend from windows-bgp to vxlan 
![image](https://user-images.githubusercontent.com/8803900/123030306-389f8900-d400-11eb-9a84-cd0410bf2082.png)



**- Linux**
- name: CALICO_IPV4POOL_VXLAN
  value: Always
```
- env:
        - name: DATASTORE_TYPE
          value: kubernetes
        - name: WAIT_FOR_DATASTORE
          value: "true"
        - name: NODENAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: CALICO_NETWORKING_BACKEND
          valueFrom:
            configMapKeyRef:
              key: calico_backend
              name: calico-config
        - name: CLUSTER_TYPE
          value: k8s,bgp
        - name: IP
          value: autodetect
        - name: CALICO_IPV4POOL_IPIP
          value: Never
        - name: CALICO_IPV4POOL_VXLAN
          value: Always
        - name: FELIX_IPINIPMTU
          valueFrom:
            configMapKeyRef:
              key: veth_mtu
              name: calico-config
        - name: FELIX_VXLANMTU
          valueFrom:
            configMapKeyRef:
              key: veth_mtu
              name: calico-config
        - name: FELIX_WIREGUARDMTU
          valueFrom:
            configMapKeyRef:
              key: veth_mtu
              name: calico-config
        - name: CALICO_IPV4POOL_CIDR
          value: 10.42.0.0/16
        - name: CALICO_DISABLE_FILE_LOGGING
          value: "true"
        - name: FELIX_DEFAULTENDPOINTTOHOSTACTION
          value: ACCEPT
        - name: FELIX_IPV6SUPPORT
          value: "false"
        - name: FELIX_LOGFILEPATH
          value: none
        - name: FELIX_LOGSEVERITYSYS
        - name: FELIX_LOGSEVERITYSCREEN
          value: Warning
        - name: FELIX_HEALTHENABLED
          value: "true"
        - name: FELIX_IPTABLESBACKEND
          value: auto
```
but still connection from  linux to windows pod is not working.

**Comment by vgaurihar** [comment]
@song-jiang 
Even I tried with Never on RKE cluster and on windows  with windows-bgp.

```
spec:
        containers:
        - env:
          - name: DATASTORE_TYPE
            value: kubernetes
          - name: WAIT_FOR_DATASTORE
            value: "true"
          - name: NODENAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
          - name: CALICO_NETWORKING_BACKEND
            valueFrom:
              configMapKeyRef:
                key: calico_backend
                name: calico-config
          - name: CLUSTER_TYPE
            value: k8s,bgp
          - name: IP
            value: autodetect
          - name: CALICO_IPV4POOL_IPIP
            value: Never
          - name: CALICO_IPV4POOL_VXLAN
            value: Never
          - name: FELIX_IPINIPMTU
            valueFrom:
              configMapKeyRef:
                key: veth_mtu
                name: calico-config
          - name: FELIX_VXLANMTU
            valueFrom:
              configMapKeyRef:
                key: veth_mtu
                name: calico-config
          - name: FELIX_WIREGUARDMTU

```
![Screenshot from 2021-06-23 09-20-05](https://user-images.githubusercontent.com/8803900/123032810-435c1d00-d404-11eb-9cfd-f24b7be48949.png)
