### ISSUE TITLE
Wireguard interface MTU not adjusted

### ISSUE THREAD

**Issue by lixmal** [projectcalico/calico#4606]
## Expected Behavior
MTU on physical interfaces should be reflected on the wireguard interface, i.e. `link mtu - 60`.
So for example wireguard MTU of `8940` for a link MTU of `9000`.

## Current Behavior

The physical interfaces have set MTU to `9000`
```
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc mq state UP group default qlen 1000
```
calico interfaces end up with `9000`
```
4: cali56e6e319386@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc noqueue state UP group default qlen 1000
```

MTU of the `wireguard.cali` interface is at `1440` instead of `8940`.
```
14: wireguard.cali: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1440 qdisc noqueue state UNKNOWN group default qlen 1000
```

The generated wireguard config doesn't list any MTU setting either
```
$ sudo wg showconf wireguard.cali
[Interface]
ListenPort = 51820
FwMark = 0x40000
PrivateKey = xxx

[Peer]
PublicKey = xxx
AllowedIPs = 10.25.0.0/24, 10.25.0.1/32
Endpoint = xxx:51820
```

I'm not sure this is an actual bug or just not yet implemented. I've seen some mtu references in the wireguard calico code, but didn't read it thoroughly.

## Possible Solution

-

## Steps to Reproduce (for bugs)

1. Set up k8s cluster with kubeadm (+ default requirements)
`kubeadm init --control-plane-endpoint  xxx:6443 --upload-certs --pod-network-cidr=10.25.0.0/16`
2. Install calico from manifest, changed calico config excerpt (+ disabled typha):
```yaml
---
# Source: calico/templates/calico-config.yaml
# This ConfigMap is used to configure a self-hosted Calico installation.
kind: ConfigMap
apiVersion: v1
metadata:
  name: calico-config
  namespace: kube-system
data:
  # You must set a non-zero value for Typha replicas below.
  typha_service_name: ""

  # Configure the MTU to use for workload interfaces and tunnels.
  # By default, MTU is auto-detected, and explicitly setting this field should not be required.
  # You can override auto-detection by providing a non-zero value.
  veth_mtu: "0"

  # The CNI network configuration to install on each node. The special
  # values in this config will be automatically populated.
  cni_network_config: |-
    {
      "name": "k8s-pod-network",
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "calico",
          "log_level": "info",
          "log_file_path": "/var/log/calico/cni/cni.log",
          "datastore_type": "kubernetes",
          "nodename": "__KUBERNETES_NODE_NAME__",
          "mtu": 9000,
          "ipam": {
              "type": "host-local",
              "subnet": "usePodCidr"
          },
          "policy": {
              "type": "k8s"
          },
          "kubernetes": {
              "kubeconfig": "__KUBECONFIG_FILEPATH__"
          }
        },
        {
          "type": "portmap",
          "snat": true,
          "capabilities": {"portMappings": true}
        },
        {
          "type": "bandwidth",
          "capabilities": {"bandwidth": true}
        }
      ]
    }

[...]
            - name: IP                                                           
              value: "autodetect"                                                
            - name: IP_AUTODETECTION_METHOD                                      
              value: "interface=eth1"                                            
            - name: FELIX_WIREGUARDENABLED                                       
              value: "true"                                                      
            - name: FELIX_BPFENABLED                                             
              value: "true"                                                      
            - name: FELIX_BPFEXTERNALSERVICEMODE                                 
              value: "DSR" 
```
3. observe interface MTU

## Context

We're running ceph on k8s (among other stuff), so a higher MTU is desirable.

## Your Environment

- Debian 10, kernel 5.10.13-1~bpo10+1
- Kubernetes 1.21, 3 untainted master nodes
- containerd 1.4.4 with default config
- Calico 3.19 with eBPF, DSR, wireguard enabled
