### ISSUE TITLE
k8s Windows pods don't have access to internet

### ISSUE THREAD

**Issue by danilnich** [projectcalico/calico#4633]
## Expected Behavior
Pods deployed on the windows node can reach each other by name and have internet access.

## Current Behavior
Pods deployed on the windows node do not ping each other by name (only ip) and do not have internet access.
![image](https://user-images.githubusercontent.com/32566593/119512392-eecd6f80-bd7b-11eb-8da5-7ace5b238319.png)

## Possible Solution
Incorrect calico for windows settings?

## Steps to Reproduce
1. Deploy windows node according to the instructions https://docs.projectcalico.org/getting-started/windows-calico/quickstart.
All default settings.
2. Start the pod

```
apiVersion: v1
kind: Pod
metadata:
  name: run-as-username-pod-demo
spec:
  containers:
  - name: run-as-username-demo
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    command: ["ping", "-t", "localhost"]
  nodeSelector:
    kubernetes.io/os: windows
```

3. Inside the container run
`ping 8.8.8.8`

## Context
I want to have internet access with windows containers similar to Linux containers. After installing calico on a Linux kubernetes cluster, all containers in the cluster get Internet access automatically.

## Environment
* Calico (windows) v3.19.0
* Calico (linux) v3.19.0
* Kubernetes (windows) v1.20.0 (on v1.21.1 too)
* Kubernetes (linux) v1.21.1
* Containerd v1.5.2
* OS CentOS 7 and Windows Server 2019
* 10-calico.conf from windows node
```
{
  "name": "Calico",
  "windows_use_single_network": true,

  "cniVersion": "0.3.1",
  "type": "calico",
  "mode": "vxlan",

  "vxlan_mac_prefix":  "0E-2A",
  "vxlan_vni": 4096,

  "policy": {
    "type": "k8s"
  },

  "log_level": "info",

  "capabilities": {"dns": true},

  "DNS":  {
    "Nameservers":  ["10.96.0.10"],
    "Search":  [
      "svc.cluster.local"
    ]
  },

  "nodename_file": "C:\\CalicoWindows\\libs\\calico\\..\\..\\nodename",

  "datastore_type": "kubernetes",

  "etcd_endpoints": "",
  "etcd_key_file": "",
  "etcd_cert_file": "",
  "etcd_ca_cert_file": "",

  "kubernetes": {
    "kubeconfig": "C:\\CalicoWindows\\calico-kube-config"
  },

  "ipam": {
    "type": "calico-ipam",
    "subnet": "usePodCidr"
  },

  "policies":  [
    {
      "Name":  "EndpointPolicy",
      "Value":  {
        "Type":  "OutBoundNAT",
        "ExceptionList":  [
		  "10.96.0.0/12"
        ]
      }
    },
    {
      "Name":  "EndpointPolicy",
      "Value":  {
        "Type":  "SDNROUTE",
        "DestinationPrefix":  "10.96.0.0/12",
        "NeedEncap":  true
      }
    }
  ]
}
```

P.S.
Firewall is disabled. Windows defender too.
