### ISSUE TITLE
Apply networkpolicy namespaceselector cause can't access service via ClusterIP

### ISSUE THREAD

**Issue by xuchenCN** [projectcalico/calico#4679]
It's getting timeout when access the service via ClusterIP 

try to deploy the example

 [https://github.com/ahmetb/kubernetes-network-policy-recipes/blob/master/06-allow-traffic-from-a-namespace.md](https://github.com/ahmetb/kubernetes-network-policy-recipes/blob/master/06-allow-traffic-from-a-namespace.md)

There are two conclusions was found after test:
* It CAN NOT access service via ClusterIP across the node but inter node is well.
* It CAN access PodIP acording the networkpolicy.

## Expected Behavior

Can access the service via ClusterIP from arbitary node in cluster acording the networkpolicy

## Steps to Reproduce (for bugs)
1. Acording the example above, try to access url from different node

## Your Environment

* k8s: v1.17.16
* calico: v3.18.0
* kube-proxy : 
                       mode: ipvs 
                       hostnetwork: true
* core-dns: enabled

**Comment by lwr20** [comment]
> Can access the service via ClusterIP from arbitary node in cluster acording the networkpolicy

This should absolutely work.  The way this is supposed to work is that:
- source pod sends to cluster IP
- kube-proxy on the source pod's node DNATs the packet to one of the pods backing the service
- packet is sent exactly as if it were a pod-pod packet
- packet arrives at destination pod - network policy is applied (exactly as if the packet was pod-pod originally).

Does connectivity work if you send to the pod IP direct?  If not, need to fix that first.
If pod-pod works, then look at service endpoints - check that the destination pod is in the list of endpoints for the service.  If it is, check kube-proxy logs - did it create the iptables rule to NAT the packet to the service?

If none of those work, perhaps join us in the calico slack http://slack.projectcalico.org/ and we can try to help you there?

**Comment by xuchenCN** [comment]
Thanks @lwr20 .
Here is the context :

Namespace NS1:
(label app=net)

* Service A (10.254.222.217:8080) -> Endpoint(172.18.148.134:8766) -> Pod A1
* Pod T1 (a test pod)

Namespace NS2
* Pod T2 (a test pod)

Networkpolicy 
```yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: web-allow-prod
  namespace: ns1
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          app: net
    - namespaceSelector:
        matchLabels:
          name: kube-system
  egress:
  - {}
```

Test:

* Pod T1 -> Endpoint(172.18.148.134:8766)     ✔️
* Pod T1 -> Service A (10.254.222.217:8080)  ❌
* Pod T2 -> Endpoint(172.18.148.134:8766) ❌   (acording to the policy)

ipvs:
```
ipvsadm -Ln  | grep 172.18.148.134 -B1

TCP  10.254.222.217:8080 rr
  -> 172.18.148.134:8766          Masq    1      0          0

```
test in pod:
```
# curl -m 2 172.18.148.134:8766
OK
# curl -m 2 10.254.222.217:8080
curl: (28) Connection timed out after 2001 milliseconds
```
endpoint:
``` 
kubectl -n ns1 get ep
service-a         172.18.148.134:8766                       3d
```

service:
```
kubectl -n ns1 get svc
service-a         ClusterIP   10.254.222.217   <none>        8080/TCP   3d
```

**Comment by xuchenCN** [comment]
Hi @lwr20 

After modify the cidr to `172.18.0.0/16` still can't access via clusterIP.

* modify the config and flag `--cluster-cidr` and restart kube-proxy's daemonset.

```
apiVersion: kubeproxy.config.k8s.io/v1alpha1
    kind: KubeProxyConfiguration
    bindAddress: 0.0.0.0
    clientConnection:
      acceptContentTypes: ""
      burst: 10
      contentType: application/vnd.kubernetes.protobuf
      kubeconfig: /var/lib/kube-proxy/kubeconfig.conf
      qps: 5
    # Use the ippool of calico
    clusterCIDR: 172.18.0.0/16
    configSyncPeriod: 15m0s
    conntrack:
      maxPerCore: 32768
      min: 131072
      tcpCloseWaitTimeout: 1h0m0s
      tcpEstablishedTimeout: 24h0m0s
    enableProfiling: false
    healthzBindAddress: 0.0.0.0:10256
    iptables:
      masqueradeAll: true
      masqueradeBit: 14
      minSyncPeriod: 0s
      syncPeriod: 30s
    ipvs:
      minSyncPeriod: 0s
      # rr: round-robin
      # lc: least connection
      # dh: destination hashing
      # sh: source hashing
      # sed: shortest expected delay
      # nq: never queue
      scheduler: rr
      syncPeriod: 30s
    metricsBindAddress: 0.0.0.0:10249
    mode: ipvs
    oomScoreAdj: -999
```

Acording to the IPIP rules access the service IP is corssing the subnet, it pass through the `tunl0`.
