### ISSUE TITLE
A Global policy preventing pods communication across namespaces, but allow in same namespace.

### ISSUE THREAD

**Issue by gh4dp** [projectcalico/calico#4751]
I want to be able to deploy 1 common global policy, which allows pod to pod communication within the same network but prevents pods communicating across namespaces. 

## Current Behavior
Once we deploy global default deny policy, unless explicitly opened all communication stops.

## Possible Solution
No suggestions as of yet. But can there be any function that could match "ingress" and "egress" namespaceSelector? 
The namesapceSelector should allow variable reflecting the namespace name from where traffic is originating instead of a literal value as it currently expects.

_For example: webpod1 and dbPod1 both are in namespace "dev1"._

_Sample yml:_

```
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: deny-app-policy
spec:
  namespaceSelector: has(projectcalico.org/name) && projectcalico.org/name not in {"kube-system", "calico-system"}
  types:
  - Ingress
  - Egress
  ingess:
  - action: Allow
    destination:
      namespaceSelector: thisNS()
  egress:
  - action: Allow
    protocol: UDP
    destination:
      selector: 'k8s-app == "kube-dns"'
      ports:
      - 53
  - action: Allow
    destination:
      namespaceSelector: thisNS()
```

My imaginary function: thisNS(), return "dev1" and matches! and will allow traffic from webpod1 and dbPod1 and traffic should flow within the same namespace. But if webpod1 tries to connect appServer2 in "dev2" namespace, it should be blocked.

From what I understand, this eventually means iptables manipulation and there could be much more. But that's where you guys rock!

## Context
Let's just say we have too many namespaces and we want to allow traffic without monitoring within the namespace. If InfoSec is allowing the images and/or we have local quarantined repo for images, it allows small team to focus immediate issues than creating local policies. We eventually lock down everything but this at the moment is helpful.

## Your Environment
Bare metal Kube version 1.20
