### ISSUE TITLE
Error querying controller installation

### ISSUE THREAD

**Issue by Forbzy** [projectcalico/calico#4802]
## Expected Behavior
Calico works. Network Policies work

## Current Behavior
```
 {"level":"error","ts":1627926445.6165264,"logger":"controller_installation","msg":"Error querying installation","Request.Namespace":"tigera-operator","Request.Name":"default-token-vbl4j","error":"Could not resolve CalicoNetwork IPPool and kubeadm configuration: kubeadm configuration is missing required podSubnet field","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.2.  0/zapr.go:132\ngithub.com/tigera/operator/pkg/controller/installation.(*ReconcileInstallation).SetDegraded\n\t/go/src/github.com/tigera/operator/pkg/controller/installation/core_controller.go:1240\ngithub.com/ti  gera/operator/pkg/controller/installation.(*ReconcileInstallation).Reconcile\n\t/go/src/github.com/tigera/operator/pkg/controller/installation/core_controller.go:699\nsigs.k8s.io/controller-runtime/pkg/internal/  controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).proc  essNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:235\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1\n\t/go/pkg/mod/s  igs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:198\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185  \nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.1  9.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.UntilWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:99"}
{"level":"error","ts":1627926445.6166239,"logger":"controller-runtime.manager.controller.tigera-installation-controller","msg":"Reconciler error","name":"default-token-vbl4j","namespace":"tigera-operator","error  ":"Could not resolve CalicoNetwork IPPool and kubeadm configuration: kubeadm configuration is missing required podSubnet field","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:2  67\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:235\nsigs.k8s.io/controller  -runtime/pkg/internal/controller.(*Controller).Start.func1.1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:198\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithConte  xt.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:155\nk8s.io/ap  imachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/  wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.UntilWithContext\n\t/go/pkg/mod/k8s.i  o/apimachinery@v0.19.2/pkg/util/wait/wait.go:99"} 
{"level":"error","ts":1627926445.6167448,"logger":"controller_installation","msg":"Error querying installation","Request.Namespace":"tigera-operator","Request.Name":"tigera-operator-token-cjc5d","error":"Could not resolve CalicoNetwork IPPool and kubeadm configuration: kubeadm configuration is missing required podSubnet field","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/za  pr@v0.2.0/zapr.go:132\ngithub.com/tigera/operator/pkg/controller/installation.(*ReconcileInstallation).SetDegraded\n\t/go/src/github.com/tigera/operator/pkg/controller/installation/core_controller.go:1240\ngithu  b.com/tigera/operator/pkg/controller/installation.(*ReconcileInstallation).Reconcile\n\t/go/src/github.com/tigera/operator/pkg/controller/installation/core_controller.go:699\nsigs.k8s.io/controller-runtime/pkg/i  nternal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controll  er).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:235\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1\n\t/go/p  kg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:198\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext  \n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.UntilWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:99"}
{"level":"error","ts":1627926445.6168146,"logger":"controller-runtime.manager.controller.tigera-installation-controller","msg":"Reconciler error","name":"tigera-operator-token-cjc5d","namespace":"tigera-operator  ","error":"Could not resolve CalicoNetwork IPPool and kubeadm configuration: kubeadm configuration is missing required podSubnet field","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/control  ler.go:267\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:235\nsigs.k8s.io/co  ntroller-runtime/pkg/internal/controller.(*Controller).Start.func1.1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:198\nk8s.io/apimachinery/pkg/util/wait.JitterUntilW  ithContext.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:155\nk  8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/ut  il/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.UntilWithContext\n\t/go/pkg/m  od/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:99"}
```

## Steps to Reproduce (for bugs)

1. Install Docker Desktop
2. Run with kubernetes
3. helm install calico projectcalico/calico --version v3.20.0

## Context
The calico pod is in a running state however the logs show there are errors. Network policies wont work. What is it I've missed?

Where do I define the Calico Network IPPool?

Docker Desktop creates a kubernetes cluster automatically so I don't normally have to set a pod subnet but I can add it as part of the kubeadm. Will calico know how to pick it up?

## Your Environment

* Calico version 3.20.0
* Kubernetes v1.21.2
* Docker-Desktop 3.5.1
* Windows 10

**Comment by lmm** [comment]
I don't know whether we test Calico with Docker Desktop. From the logs you provided, you're hitting: https://github.com/tigera/operator/blob/v1.20.0/pkg/controller/installation/pod_cidr_detection.go#L32

So I think you might need to try setting the pod subnet with kubeadm (or adding it to the configmap).

**Comment by Forbzy** [comment]
I updated the configmap called kubeadm-config and below is the result. I added `podSubnet: 10.1.0.0/16` . Those error logs are gone but my network security policies still don't work. I'll keep investigating.
 
```
apiVersion: v1
data:
  ClusterConfiguration: |
    apiServer:
      extraArgs:
        authorization-mode: Node,RBAC
        enable-admission-plugins: NodeRestriction
        watch-cache: "false"
      timeoutForControlPlane: 4m0s
    apiVersion: kubeadm.k8s.io/v1beta2
    certificatesDir: /run/config/pki
    clusterName: kubernetes
    controlPlaneEndpoint: vm.docker.internal:6443
    controllerManager:
      extraArgs:
        horizontal-pod-autoscaler-sync-period: 60s
        leader-elect: "false"
        node-monitor-grace-period: 180s
        node-monitor-period: 30s
        pvclaimbinder-sync-period: 60s
    dns:
      type: CoreDNS
    etcd:
      local:
        dataDir: /var/lib/etcd
    imageRepository: k8s.gcr.io
    kind: ClusterConfiguration
    kubernetesVersion: v1.21.2
    networking:
      dnsDomain: cluster.local
      serviceSubnet: 10.96.0.0/12
      podSubnet: 10.1.0.0/16
    scheduler: {}
  ClusterStatus: |
    apiEndpoints:
      docker-desktop:
        advertiseAddress: 192.168.65.4
        bindPort: 6443
    apiVersion: kubeadm.k8s.io/v1beta2
    kind: ClusterStatus
kind: ConfigMap
metadata:
  creationTimestamp: "2021-08-12T15:03:08Z"
  name: kubeadm-config
  namespace: kube-system
```

**Comment by Forbzy** [comment]
I just wanted to provide an update before closing this ticket. To get the network security policy to work I've updated the installation below by adding cidrs=10.1.0.0/16 under `nodeAddressAutodetectionV4`. It would default to first found.

```
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  name: default
spec:
  calicoNetwork:
    bgp: Enabled
    hostPorts: Enabled
    ipPools:
    - blockSize: 26
      cidr: 10.1.0.0/16
      encapsulation: IPIP
      natOutgoing: Enabled
      nodeSelector: all()
    linuxDataplane: Iptables
    multiInterfaceMode: None
    nodeAddressAutodetectionV4:
      cidrs:
      - 10.1.0.0/16
  cni:
    ipam:
      type: Calico
    type: Calico
  flexVolumePath: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/
  imagePullSecrets: []
  kubernetesProvider: ""
  nodeUpdateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  variant: Calico 
```

I then provided the network security policy below.

```
apiVersion: crd.projectcalico.org/v1
kind: GlobalNetworkPolicy
metadata:
  name: network-policy-test-deployment
spec:
  selector: app == 'test-deployment'
  types:
  - Ingress
  - Egress
  ingress:
  - action: Deny
  egress:
  - action: Deny
```

As a result I would receive the below errors. Maybe there is a network guru out there that can help with this. I think that the cali network interface card isn't being created because I can't found it when running `route` or `ip addr` or `ifconfig` on the pods or the host.

```
2021-08-17 13:00:16.501 [INFO][1252] felix/endpoint_mgr.go 1128: Skipping configuration of interface because it is oper down. ifaceName="calif6837bb65d1"
2021-08-17 13:00:16.501 [INFO][1252] felix/endpoint_mgr.go 476: Re-evaluated workload endpoint status adminUp=true failed=false known=true operUp=false status="down" workloadEndpointID=proto.WorkloadEndpointID{O  rchestratorId:"k8s", WorkloadId:"default/test-deployment-root-7cff96c6f7-rqb8b", EndpointId:"eth0"}
2021-08-17 13:00:16.501 [INFO][1252] felix/status_combiner.go 58: Storing endpoint status update ipVersion=0x4 status="down" workload=proto.WorkloadEndpointID{OrchestratorId:"k8s", WorkloadId:"default/test-deplo  yment-root-7cff96c6f7-rqb8b", EndpointId:"eth0"}
2021-08-17 13:00:16.518 [INFO][1252] felix/route_table.go 1096: Failed to access interface because it doesn't exist. error=Link not found ifaceName="calif6837bb65d1" ifaceRegex="^cali.*" ipVersion=0x4
2021-08-17 13:00:16.518 [INFO][1252] felix/route_table.go 1164: Failed to get interface; it's down/gone. error=Link not found ifaceName="calif6837bb65d1" ifaceRegex="^cali.*" ipVersion=0x4
2021-08-17 13:00:16.532 [INFO][1252] felix/route_table.go 538: Interface missing, will retry if it appears. ifaceName="calif6837bb65d1" ifaceRegex="^cali.*" ipVersion=0x4
2021-08-17 13:00:16.837 [INFO][1252] felix/status_combiner.go 78: Endpoint down for at least one IP version id=proto.WorkloadEndpointID{OrchestratorId:"k8s", WorkloadId:"default/test-deployment-root-7cff96c6f7-r  qb8b", EndpointId:"eth0"} ipVersion=0x4 status="down"
2021-08-17 13:00:16.837 [INFO][1252] felix/status_combiner.go 98: Reporting combined status. id=proto.WorkloadEndpointID{OrchestratorId:"k8s", WorkloadId:"default/test-deployment-root-7cff96c6f7-rqb8b", Endpoint  Id:"eth0"} status="down"
```
