### ISSUE TITLE
Calico node spikes with memory usage after upgrading to 3.20

### ISSUE THREAD

**Issue by invidian** [projectcalico/calico#4810]
## Expected Behavior
Memory usage of DaemonSet remains stable.

## Current Behavior
Memory usage is now spiky, occasionally triggering OOM on small nodes. This graph shows memory usage after updating from 3.19.1 to 3.20.0.
![Selection_444](https://user-images.githubusercontent.com/16539896/128342304-0aab1dd5-7da1-40ad-8399-418f0cbe9e87.png)

## Steps to Reproduce (for bugs)

1. `helm repo add flexkube https://flexkube.github.io/charts/`
2. `helm upgrade --install --wait -n kube-system calico flexkube/calico`
3. Wait.

## Your Environment

* Calico version
```
    Image:          docker.io/calico/kube-controllers:v3.20.0
    Image:         docker.io/calico/cni:v3.20.0
    Image:         docker.io/calico/cni:v3.20.0
    Image:          docker.io/calico/pod2daemon-flexvol:v3.20.0
    Image:          docker.io/calico/node:v3.20.0
```
* Orchestrator version (e.g. kubernetes, mesos, rkt):
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T20:59:07Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
```
* Operating System and version:
```
Flatcar Container Linux by Kinvolk 2905.2.1 (Oklo)   5.10.55-flatcar
```

My config:
```yaml
data:
  calico_backend: bird
  cni_network_config: |-
    {
      "name": "k8s-pod-network",
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "calico",
          "log_level": "info",
          "log_file_path": "/var/log/calico/cni/cni.log",
          "datastore_type": "kubernetes",
          "nodename": "__KUBERNETES_NODE_NAME__",
          "mtu": __CNI_MTU__,
          "nodename_file_optional": true,
          "ipam": {
              "type": "calico-ipam"
          },
          "policy": {
              "type": "k8s"
          },
          "kubernetes": {
              "kubeconfig": "__KUBECONFIG_FILEPATH__"
          }
        },
        {
          "type": "portmap",
          "snat": true,
          "capabilities": {"portMappings": true}
        },
        {
          "type": "bandwidth",
          "capabilities": {"bandwidth": true}
        }
      ]
    }
  typha_service_name: none
  veth_mtu: "1430"
```
