### ISSUE TITLE
API-Server fails to import GlobalNetworkSet

### ISSUE THREAD

**Issue by frozenprocess** [projectcalico/calico#4845]
I was trying to import the following `GNS` to my kubernetes cluster with the help of api-server and kuebctl but import failed.

```
apiVersion: projectcalico.org/v3
kind: GlobalNetworkSet
metadata:
  name: block-ipset-1
  labels:
    IP-deny-list: true
spec:
  nets:
  - 186.158.201.183/32
```
kubectl returned the following error
```
error: unable to decode "rules/policy01.yaml": resource.metadataOnlyObject.ObjectMeta: v1.ObjectMeta.Labels: ReadString: expects " or n, but found t, error found in #10 byte of ...|ny-list":true},"name|..., bigger context ...|NetworkSet","metadata":{"labels":{"IP-deny-list":true},"name":"block-ipset-1"},"spec":{"nets":["186.|...
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.8", GitCommit:"5575935422cc1cf5169dfc8847cb587aa47bac5a", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:07Z", GoVersion:"go1.15.13", Compiler:"gc", Platform:"linux/amd64"}
```

## Your Environment

* Calico version v3.20.0 5ef66b403f4f
* calico/apiserver v3.20.0 b5a4c6d1f3d6
* Orchestrator version (e.g. kubernetes, mesos, rkt): RKE, K8s, OKD
* Operating System and version: Redhat 8 , ubuntu 20.04
