### ISSUE TITLE
Global Network Policy to block Azure Metadata endpoint not working

### ISSUE THREAD

**Issue by webbdog28** [projectcalico/calico#4853]
## Expected Behavior

Global network policy should allow all egress traffic except to the Azure VM metadata endpoint 169.254.169.254/32
## Current Behavior

All egress traffic is allowed, including to the VM metadata endpoint

## Steps to Reproduce (for bugs)

1. Apply this network policy

```
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: default-deny
spec:
  namespaceSelector: has(projectcalico.org/name) && projectcalico.org/name not in {"kube-system", "calico-system"} # do not apply the policy to the kube-system or calico-system namespaces
  types:
  - Ingress
  - Egress  
  egress:   
  - action: Deny
    destination:
      nets:
      - 169.254.169.254/32
  - action: Allow
    destination:
      nets:
      - 0.0.0.0/0
  ingress:
  - action: Allow
    protocol: UDP
    destination:
      selector: k8s-app == 'kube-dns'
      ports:
      - 53
  - action: Allow
    source:
      namespaceSelector: has(projectcalico.org/name) && projectcalico.org/name in {"traefik", "kube-system", "calico-system"}
```

## Your Environment

* Calico version: 3.19.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): AKS 1.21.2
* Operating System and version: Ubuntu
* Link to your project (optional):
