### ISSUE TITLE
Can not create calico network policies with service match 

### ISSUE THREAD

**Issue by bigTuxer** [projectcalico/calico#4878]
Hello,

at the moment i try to implement some network policies to secure my kubernetes cluster.  
As described in the project calico tutorials i first implemented a default deny rule.  

After that i try to allow one needed service after another, based on ports i was successful. 
But when i try to use service matches as descrubed here: [Project Calico: NetworkPolicy](https://docs.projectcalico.org/reference/resources/networkpolicy#servicematch). I get error messages from calicoctl like that:
```bash
calicoctl create -f dnsAllow.yml
Failed to execute command: error parsing document: field in document is not recognized or is in the wrong location: services
```
dnsAllow.yml looks like that:
```yaml
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: allow-kube-dns
spec:
  selector: projectcalico.org/namespace == "calico-policy-ns"
  egress:
    - action: Allow
      destination:
        services:
          name: kube-dns
          namespace: kube-system
```
That file is based on: [Project Calico: Service Policy](https://docs.projectcalico.org/security/service-policy). I've only replaced the selector `all()` with my namespace selector `projectcalico.org/namespace == "calico-policy-ns"`

## Expected Behavior
Create a networkPolicy with the destination rule based on kubernetes services.  

## Current Behavior
Get an error message when i try to create the object with calicoctl:
```bash
Failed to execute command: error parsing document: field in document is not recognized or is in the wrong location: services
```

## Possible Solution
i don't know

## Steps to Reproduce (for bugs)
1. Create a yaml file with the following content:
```yaml
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: allow-kube-dns
spec:
  selector: all()
  egress:
    - action: Allow
      destination:
        services:
          name: kube-dns
          namespace: kube-system
```
2. Use calicoctl `calicoctl create -f dnsAllow.yml`
3. Get the error message: `Failed to execute command: error parsing document: field in document is not recognized or is in the wrong location: services`

## Context
I just try to secure my kubernetes cluster following the documentation on the project calico website.  
I need to be able to isolate pods in different namespaces from each other, based on service matches that would be awesome.  

## Your Environment

* Calico version:
```bash
calicoctl version  
Client Version:    v3.18.0
Git commit:        5d65da3d
Cluster Version:   v3.18.1
Cluster Type:      k8s,bgp,kdd
```
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes v1.20.5
* Operating System and version: Ubuntu 20.04
