### ISSUE TITLE
Multiple IPv6 addresses for a kubernetes pod

### ISSUE THREAD

**Issue by tavolodobela** [projectcalico/calico#4893]
We use dual stack configuration, and when a kubernetes pod starts it gets both an IPv4 and an IPv6 address. So far so good.

However, out developers require that the eth0 interface in the pod needs to have 3 more IP aliases. I tried to use the metadata annotation, eg.

```
metadata:
  annotations:
    "cni.projectcalico.org/ipAddrs": "[\"192.168.199.199\", \"2001:db8:42::8\", \"2001:db8:42::9\"]"
...
```

However I got the below error when I ran kubectl describe pod:

**"cannot have more than one IPv6 address for "cni.projectcalico.org/ipAddrs" annotation"**

## Expected Behavior

The pod should have both IPv6 addresses (and the IPv4 address specified as well)

## Current Behavior

The pod is stuck in the "Pending" state, and won't start.

## Steps to Reproduce (for bugs)

Use the following yaml:

```
apiVersion: v1
kind: Pod
metadata:
  name: test1
  namespace: default
  annotations:
    "cni.projectcalico.org/ipAddrs": "[\"192.168.199.199\", \"2001:db8:42::8\",  \"2001:db8:42::9\"]"
spec:
  containers:
  - name: test1
    image: ubuntu:20.04
    command:
      - sleep
      - "3600"

```
## Your Environment

* Calico version
v3.19.1

* Orchestrator version (e.g. kubernetes, mesos, rkt):
kubernetes 1.22.0

* Operating System and version:
Ubuntu 20.04 LTS

* Link to your project (optional):
