### ISSUE TITLE
Cannot access services of pods located in a different node after applying NetworkPolicies

### ISSUE THREAD

**Issue by aalcaraz97** [projectcalico/calico#4919]
I have a K3S cluster with two control-plane nodes which is using Calico as the cluster CNI.
I am installing K3S in my nodes using the K3S installation script. I am disabling Flannel and the default Network Policy that comes by default in K3S, and setting the 192.168.0.0/16 CIDR range (my network uses a 10.x.x.x CIDR range, so no overlapping should exist), following the [Calico docs on K3S](https://docs.projectcalico.org/getting-started/kubernetes/k3s/multi-node-install#initializing-master-instance):

```bash
# K3S installation flags
K3S_EXEC="--disable=traefik \
  --secrets-encryption \
  --cluster-init \
  --flannel-backend=none \
  --disable-network-policy \
  --cluster-cidr=192.168.0.0/16 \
  --selinux"
# Install K3S
INSTALL_K3S_SKIP_DOWNLOAD=true \
	INSTALL_K3S_EXEC="$K3S_EXEC" \
	INSTALL_K3S_SYMLINK=force \
	K3S_TOKEN="<master-token>" \
	install.sh
```

After installing K3S, I'm deploying Calico into the cluster, following the [Calico documentation](https://docs.projectcalico.org/getting-started/kubernetes/k3s/multi-node-install#install-calico). I am also enabling Wireguard in the Calico deployment to encrypt the pod traffic:

```bash
# Install Calico CRDs
kubectl create -f tigera-operator.yaml"
# Install Calico on the cluster
kubectl create -f custom-resources.yaml"
# Enable Wireguard in Calico deployment
calicoctl patch Felixconfiguration default --type='merge' -p '{"spec":{"wireguardEnabled":true}}'
```

These are the contents of the custom-resources.yaml file:
```yaml
# This section includes base Calico installation configuration.
# For more information, see: https://docs.projectcalico.org/v3.19/reference/installation/api#operator.tigera.io/v1.Installation
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  # Configures Calico networking.
  calicoNetwork:
    containerIPForwarding: Enabled
    # Note: The ipPools section cannot be modified post-install.
    ipPools:
    - blockSize: 26
      cidr: 192.168.0.0/16
      encapsulation: VXLANCrossSubnet
      natOutgoing: Enabled
      nodeSelector: all()
```
After installing Calico, I install several components into my cluster: Grafana, Prometheus, Longhorn, Istio, etc. Each component is installed in an specific namespace.

Before installing the components, I create several Calico Network Policies to restrict the access to those components. I first enable the default deny policy, and then I add several allow policies to only allow certain traffic.
This is the default deny policy applied into the cluster, following the [default deny policy documentation](https://docs.projectcalico.org/security/kubernetes-default-deny#enable-default-deny-calico-global-network-policy-non-namespaced) (I can post the rest of the NetworkPolicies if that can help debugging the issue):

```yaml
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: deny-all-policy
spec:
  order: 1
  namespaceSelector: has(projectcalico.org/name) && projectcalico.org/name not in {"kube-system", "calico-system", "tigera-operator"}
  types:
    - Ingress
    - Egress
  egress:
    # allow all namespaces to communicate to DNS pods
    - action: Allow
      protocol: UDP
      destination:
        selector: 'k8s-app == "kube-dns"'
        ports:
          - 53
```

After installing all these components into the first control-plane node, all is working as expected. All the accesses allowed/denied by Network Policies are working fine, and the components can be deployed correctly in the cluster.

The problem I have is when adding a second control-plane node to the existing cluster. For doing that, I execute the K3S install script in the new node:

```bash
# K3S installation flags
K3S_EXEC="--disable=traefik \
  --secrets-encryption \
  --cluster-init \
  --flannel-backend=none \
  --disable-network-policy \
  --cluster-cidr=192.168.0.0/16 \
  --selinux \
  --server=https://<master-node-1-ip>:6443"
# Install K3S
INSTALL_K3S_SKIP_DOWNLOAD=true \
	INSTALL_K3S_EXEC="$K3S_EXEC" \
	INSTALL_K3S_SYMLINK=force \
	K3S_TOKEN="<master-token>" \
	install.sh
```

The second node is successfully added into the cluster, and some new DaemonSet pods start to create in the new node, as expected.

Some of the new Daemonset pods fail to reach some of the Kubernetes services of pods that are running in the first control-plane node.

For example, the Grafana ClusterIP service can be accessed from the first control-plane node (where the Grafana pod is located), but it cannot be accessed from the second control-plane. 
```bash
<control-plane-node-1> $ kubectl get svc -A
NAMESPACE                NAME                                       TYPE           CLUSTER-IP      EXTERNAL-IP               PORT(S)                                      AGE
<grafana-ns>             grafana                                    ClusterIP      10.43.73.48     <none>                    80/TCP                                       5h37m
```

```bash
<control-plane-node-1> $ curl -vvv http://10.43.73.48
* About to connect() to 10.43.73.48 port 80 (#0)
*   Trying 10.43.73.48...
* Connected to 10.43.73.48 (10.43.73.48) port 80 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 10.43.73.48
> Accept: */*
>
< HTTP/1.1 302 Found
[...]
<
<a href="/grafana/login">Found</a>.

* Connection #0 to host 10.43.73.48 left intact
```

```bash
<control-plane-node-2> $ curl -vvv http://10.43.73.48
* About to connect() to 10.43.73.48 port 80 (#0)
*   Trying 10.43.73.48...

```

I have tried to debug which component can be failing on this scenario:
1. I tried with an installation without Wireguard enabled, but the same error happens
2. I then tried to not install any Network Policy in the cluster (and Wireguard enabled), and after that, the second node could actually reach the services deployed in the first node.

So I'm starting to think that maybe it has to do with the set of Network Policies that I'm creating in the cluster. 
This is the NetworkPolicy for the namespace where Grafana is deployed. In this NetworkPolicy, I am only allowing (in theory) the Grafana namespace to communicate with the Prometheus namespace (so I can visualize metrics), and the Istio namespace (to expose Grafana outside of the cluster):
```yaml
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: grafana-allow-access-policy
  namespace: <grafana-namespace>
spec:
  selector: all()
  order: 9
  types:
  - Egress
  - Ingress
  egress:
  - action: Allow
    source:
      namespaceSelector: (projectcalico.org/name == '<grafana-namespace>' || projectcalico.org/name == '<istio-namespace>' || projectcalico.org/name == '<prometheus-namespace>')
  ingress:
  - action: Allow
    source:
      namespaceSelector: (projectcalico.org/name == '<grafana-namespace>' || projectcalico.org/name == '<istio-namespace>' || projectcalico.org/name == '<prometheus-namespace>')
```
Is there something obvious that I'm missing here about Network Policies? 
Is there any extra configuration that I need to add intothe Calico installation (or to the Network Policy objects) to enable the traffic between the different nodes of the cluster? 
Do I need to include or fix any of the fields in the NetworkPolicy spec? 

I have been stuck with this problems for a couple of days, and I still don't know how to solve it....
I am not seeing any significant error on the Calico pods also. I can post the content of iptables if that is needed for further debugging...

FYI: 
* NetworkManager has been configured to not interfere with the iptables in both nodes, and firewalld has been disabled in both nodes, following the [Calico requirements](https://docs.projectcalico.org/getting-started/kubernetes/requirements#node-requirements)
* Both nodes are Virtual Machines created on a VMware vSphere infrastructure.
* I'm trying to change the previous CNI that I was using in my K3S cluster (Flannel + Wireguard), and use Calico + Wireguard instead (so I can create NetworkPolicies in my cluster). The Grafana access scenario described before was working successfully when using Flannel + Wireguard, but it is not working when using Calico + Wireguard.

## Expected Behavior
The second node should be able to access the services of pods deployed in the first node

## Current Behavior
The second node does not reach services of pods deployed in the first node

## Your Environment

* Calico version: 
** CALICO_VERSION = v3.19.1
** TIGERA_OPERATOR_VERSION = v1.17.4
* Orchestrator version (e.g. kubernetes, mesos, rkt): K3S v1.20.4+k3s1
* Operating System and version: CentOS Linux release 7.9.2009 (Core)
* Link to your project (optional):

**Comment by caseydavenport** [comment]
Thanks for the detailed report! This helps a lot to diagnose what is going on.

> <control-plane-node-2> $ curl -vvv http://10.43.73.48

Just wanted to confirm - it looks like the curl command you are trying is being run from the second node, rather than a pod on the other node. Are you sure that your policy allows traffic from the node's IP? 

From what it sounds like, your policy will not allow traffic from the nodes themselves, rather only allow from pods in the selected namespaces. This might just be a matter of your policy not matching your expectation!

The reason it works from node-1 is because Calico allows a local node to access pods running on that node, since Kubernetes needs that behavior in order to properly implement pod liveness checking.

**Comment by caseydavenport** [comment]
@aalcaraz97 ^

**Comment by aalcaraz97** [comment]
Thanks for the answer @caseydavenport!

I think it is definitely a NetworkPolicy issue that is only allowing traffic from within the specified namespace, and blocking the traffic from the other nodes.

I found the following [Calico documentation on External IP and Networks rules](https://docs.projectcalico.org/security/external-ips-policy).

I wanted to do something similar, but instead of allowing all ingress traffic and denying explicitly the CIDRs of the IPs, I want to do the opposite: only allow ingress traffic from certain CIDRs.

For simplicity in the testing, I removed the NetworkPolicies associated to the components (Grafana, Istio, etc.) from the cluster.

**Without any NetworkPolicy applied**, I tested the curl command to the Grafana ClusterIP Service from both nodes of the cluster, and both nodes are able to reach it (which is expected).

Then, I applied the "deny all" policy described above, and the Grafana Service was **not available** from the second node (which is also expected).

I wanted to test the GlobalNetworkSet approach, so I created the following resources in the cluster: a GlobalNetworkSet including the two IPs of the nodes (let's name the IP of the nodes 10.0.0.1 for node1, and 10.0.0.2 for node2), and a GlobalNetworkPolicy allowing the traffic from the CIDRs in the GlobalNetworkSet:
* global-network-set.yaml:
```yaml
apiVersion: projectcalico.org/v3
kind: GlobalNetworkSet
metadata:
  name: network-set-node-allow
  labels:
    IP-allow-list: true
spec:
  nets:
  - 10.0.0.1/32
  - 10.0.0.2/32
```
* global-network-policy-allow-nodes.yaml:
```yaml
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: global-node-allow
spec:
  selector: all()
  order: 2
  types:
  - Ingress
  ingress:
  - action: Allow
    source:
      selector: IP-allow-list == 'true' && !has(projectcalico.org/namespace)
```
I tested the curl command to the Grafana ClusterIP Service after applying the GlobalNetworkSet and the GlobalNetworkPolicy:
* From the node where Grafana pod is deployed, the service is still reachable.
* But from the second node in the cluster, the service is **still unreachable**:
```bash
<control-plane-node-2> $ curl -vvv http://10.43.73.48
* About to connect() to 10.43.73.48 port 80 (#0)
*   Trying 10.43.73.48...
```
I also have tried to add the following:
```yaml
 ingress:
  - action: Allow
    source:
      selector: IP-allow-list == 'true' && !has(projectcalico.org/namespace)
``` 
into the spec of my "deny all" policy, but the service is still unreachable from the second node.

I wanted to perform these rules to allow certain IPs in a GlobalNetworkPolicy, in order to avoid having to manually add a rule for each new node (that is, a new CIDR) to all the already created NetworkPolicies in the cluster.

I have seen some documentation on [how to protect Kubernetes hosts](https://docs.projectcalico.org/security/kubernetes-nodes), which includes defining HostEndpoints and applying a GlobalNetworkPolicy to them to allow/deny traffic. I haven't tried that yet, but first I wanted to make sure that I am going to the right way for solving my issue, or if it is much more simpler than I think it is.

**Comment by caseydavenport** [comment]
> let's name the IP of the nodes 10.0.0.1 for node1, and 10.0.0.2 for node2), and a GlobalNetworkPolicy allowing the traffic from the CIDRs in the GlobalNetworkSet:

Are you _sure_ those are the IP addresses being used for communication from Node2 -> Pods on node 1?

If you have IPIP / VXLAN encap enabled in Calico, there is likely another IP address you need to add to your NetworkSet - namely, the tunnel address on the `tunl0` (ipip) or `vxlan.calico` (vxlan) devices.

**Comment by lwr20** [comment]
The doc on protecting kubernetes hosts https://docs.projectcalico.org/security/kubernetes-nodes also talks about turning on a feature which will automatically create Host Endpoints for them, which can be thought of as a way of automating updates of the IPs of the nodes (particularly handy if you're adding/deleting nodes later).

**Comment by laptimus** [comment]
> Thanks for the answer @caseydavenport!
> 
> I think it is definitely a NetworkPolicy issue that is only allowing traffic from within the specified namespace, and blocking the traffic from the other nodes.
> 
> I found the following [Calico documentation on External IP and Networks rules](https://docs.projectcalico.org/security/external-ips-policy).
> 
> I wanted to do something similar, but instead of allowing all ingress traffic and denying explicitly the CIDRs of the IPs, I want to do the opposite: only allow ingress traffic from certain CIDRs.
> 
> For simplicity in the testing, I removed the NetworkPolicies associated to the components (Grafana, Istio, etc.) from the cluster.
> 
> **Without any NetworkPolicy applied**, I tested the curl command to the Grafana ClusterIP Service from both nodes of the cluster, and both nodes are able to reach it (which is expected).
> 
> Then, I applied the "deny all" policy described above, and the Grafana Service was **not available** from the second node (which is also expected).
> 
> I wanted to test the GlobalNetworkSet approach, so I created the following resources in the cluster: a GlobalNetworkSet including the two IPs of the nodes (let's name the IP of the nodes 10.0.0.1 for node1, and 10.0.0.2 for node2), and a GlobalNetworkPolicy allowing the traffic from the CIDRs in the GlobalNetworkSet:
> 
> * global-network-set.yaml:
> 
> ```yaml
> apiVersion: projectcalico.org/v3
> kind: GlobalNetworkSet
> metadata:
>   name: network-set-node-allow
>   labels:
>     IP-allow-list: true
> spec:
>   nets:
>   - 10.0.0.1/32
>   - 10.0.0.2/32
> ```
> 
>  * global-network-policy-allow-nodes.yaml:
> 
> ```yaml
> apiVersion: projectcalico.org/v3
> kind: GlobalNetworkPolicy
> metadata:
>   name: global-node-allow
> spec:
>   selector: all()
>   order: 2
>   types:
>   - Ingress
>   ingress:
>   - action: Allow
>     source:
>       selector: IP-allow-list == 'true' && !has(projectcalico.org/namespace)
> ```
> 
> I tested the curl command to the Grafana ClusterIP Service after applying the GlobalNetworkSet and the GlobalNetworkPolicy:
> 
> * From the node where Grafana pod is deployed, the service is still reachable.
> * But from the second node in the cluster, the service is **still unreachable**:
> 
> ```shell
> <control-plane-node-2> $ curl -vvv http://10.43.73.48
> * About to connect() to 10.43.73.48 port 80 (#0)
> *   Trying 10.43.73.48...
> ```
> 
> I also have tried to add the following:
> 
> ```yaml
>  ingress:
>   - action: Allow
>     source:
>       selector: IP-allow-list == 'true' && !has(projectcalico.org/namespace)
> ```
> 
> into the spec of my "deny all" policy, but the service is still unreachable from the second node.
> 
> I wanted to perform these rules to allow certain IPs in a GlobalNetworkPolicy, in order to avoid having to manually add a rule for each new node (that is, a new CIDR) to all the already created NetworkPolicies in the cluster.
> 
> I have seen some documentation on [how to protect Kubernetes hosts](https://docs.projectcalico.org/security/kubernetes-nodes), which includes defining HostEndpoints and applying a GlobalNetworkPolicy to them to allow/deny traffic. I haven't tried that yet, but first I wanted to make sure that I am going to the right way for solving my issue, or if it is much more simpler than I think it is.

hello aalcaraz97

we are facing similar issue where namespace based policy is working fine as long as the pods are in same nodes

did you find any solution to make calico policies to work across nodes ?

**Comment by laptimus** [comment]
> @laptimus could you share the policy in question and explain which traffic is being denied that you expect to be allowed?

thanks for reaching out casey

we solved the problem

looks like there were some SNAT rules that were modifying pod ip across nodes and hence calico policy was blocking them

once those SNAT rules were fixed - policy started working fine across nodes

**Comment by ybizeul** [comment]
I'm facing a similar situation. The following policy doesn't let pods in the same namespace talk to each other, if they are on different nodes :
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-web-policy
  namespace: ybontap-tynsoe-org
spec:
  podSelector: {}
  ingress:
    - from:
      - podSelector: {}
  egress:
    - to:
      - podSelector: {}
    - to:
      - namespaceSelector: {}
        podSelector:
          matchLabels:
            k8s-app: kube-dns
      ports:
      - port: 53
        protocol: UDP
```

On the destination host with tcpdump, I see packets being SNAT'd to the VXLAN's interface IP, not sure that's expected or part of the issue.

@laptimus do you remember what were those SNAT rules and where they came from ?
