### ISSUE TITLE
Helm -  chart cannot be installed as a dependency 

### ISSUE THREAD

**Issue by sean-mcgimpsey** [projectcalico/calico#4922]
When used as a child/dependency of a parent chart , installation fails with the below error
```
Error: UPGRADE FAILED: unable to recognize "": no matches for kind "Installation" in version "operator.tigera.io/v1"

```

I think this maybe due to some hard-coded namespaces in some resources, meaning some resources get installed in the release namespace, and some resources get installed in the tigera-operator namespace (hard cored). Im not certain though...

## Expected Behavior
The chart is able to be installed as a dependency/child of a parent chart.

## Steps to Reproduce (for bugs)

1. Add repo 
```
helm repo add projectcalico   https://docs.projectcalico.org/charts
```
2. Add the chart as a dependency of a parent chart
```
apiVersion: v2
name: parent-chart
description:  Parent chart
type: application

version: 0.1.0
appVersion: ~

dependencies:
  - name: tigera-operator
    version: 3.20.0
    alias: calico
    repository: "@projectcalico"
```
2. Update dependencies
3. Attempt to install chart

## Context
We would like to add the chart to our standard chart package, installed across EKS cluster, alongside other charts for example the kubernetes dashboard.

## Your Environment

* Calico version - 3.20.0
* k8s version
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3+k3s1", GitCommit:"1d1f220fbee9cdeb5416b76b707dde8c231121f2", GitTreeState:"clean", BuildDate:"2021-07-22T20:52:14Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}

```
