### ISSUE TITLE
NetworkPolicy based on NamespaceSelector (namespace-isolation) breaks windows pod communication

### ISSUE THREAD

**Issue by dropdeadfu** [projectcalico/calico#4936]
When I enable a policy to allow pods in one namespace to communicate with services in the same namespace windows pods can no longer communicate with any service inside that namespace. The rest of the cluster (linux nodes and pods) work as expected and can communicate.

## Expected Behavior
I would expect linux and windows nodes to behave the same way.

## Current Behavior
Currently I apply the following policies to all non-system namespace on my namespace:
```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: default-deny
spec:
  podSelector:
    matchLabels: {}

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-same-namespace
spec:
  podSelector:
    matchLabels: {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          stack: e1-dev

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress
spec:
  podSelector:
    matchLabels: {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-kube-system
spec:
  podSelector:
    matchLabels: {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: kube-system
```
In this example the namepace those policies are applied to is named "e1-dev". The purpose of them is to only allow pods and service within the namespace to communicate with each other (+ ingress and kubesystem).

As soon as I delete the policies, the networking works totally fine in windows pods. I could however test it successfully that if you enable only the "allow-same-namespace" policy, communication is blocked again.

I was watching calico-agent logs on windows for a while and looking for relevant things but the only thing that I currently see that seems to be at least somewhat related is, even tho this refers to kube-system:
```
2021-09-14 20:28:19.878 [WARNING][4824] felix/policysets.go 388: SrcIpSetIds could not be resolved, rule will be skipped rule=proto.Rule{Action:"allow", IpVersion:0, Protocol:(*proto.Protocol)(nil), SrcNet:[]string(nil), SrcPorts:[]*proto.PortRange(nil), SrcNamedPortIpSetIds:[]string(nil), DstNet:[]string(nil), DstPorts:[]*proto.PortRange(nil), DstNamedPortIpSetIds:[]string(nil), Icmp:proto.isRule_Icmp(nil), SrcIpSetIds:[]string{"s:bkglHyxR1taxu8-2G6JtfeoOIIpvp-z72I7uUw"}, DstIpSetIds:[]string(nil), DstIpPortSetIds:[]string(nil), NotProtocol:(*proto.Protocol)(nil), NotSrcNet:[]string(nil), NotSrcPorts:[]*proto.PortRange(nil), NotDstNet:[]string(nil), NotDstPorts:[]*proto.PortRange(nil), NotIcmp:proto.isRule_NotIcmp(nil), NotSrcIpSetIds:[]string(nil), NotDstIpSetIds:[]string(nil), NotSrcNamedPortIpSetIds:[]string(nil), NotDstNamedPortIpSetIds:[]string(nil), OriginalSrcSelector:"projectcalico.org/orchestrator == 'k8s'", OriginalDstSelector:"", OriginalSrcNamespaceSelector:"app.kubernetes.io/name == 'kube-system'", OriginalDstNamespaceSelector:"", OriginalNotSrcSelector:"", OriginalNotDstSelector:"", OriginalDstService:"", OriginalDstServiceNamespace:"", SrcServiceAccountMatch:(*proto.ServiceAccountMatch)(nil), DstServiceAccountMatch:(*proto.ServiceAccountMatch)(nil), HttpMatch:(*proto.HTTPMatch)(nil), Metadata:(*proto.RuleMetadata)(nil), RuleId:"1VrL3jl870yR-VRt"}
2021-09-14 20:28:19.879 [INFO][4824] felix/policysets.go 275: Rule could not be converted, error: rule referenced a missing IP set rule=action:"allow" src_ip_set_ids:"s:bkglHyxR1taxu8-2G6JtfeoOIIpvp-z72I7uUw" original_src_selector:"projectcalico.org/orchestrator == 'k8s'" original_src_namespace_selector:"app.kubernetes.io/name == 'kube-system'" rule_id:"1VrL3jl870yR-VRt" 
```

## Possible Solution
Either not use network policies, find a different way to isolate namespaces or have it behave the same way on windows as it does on linux. I am sorry but I am totally unclear about the technical details on this one.

## Steps to Reproduce (for bugs)

1. EKS cluster with k8s 1.19
2. Add calico (3.20) with tigera operator (1.20) but only enable EKS scenario for basically having only policies being managed by calico
3. Add windows node and install calico 3.20
4. Apply the above mentioned network policy

## Context
My expected behavior of k8s should be that namespaces should in fact be isolated by default and to my knowledge a big portion of enterprise customers expect this to be this way as well. Tho the actual technical difficulty I am currently running into is that in the stack my guys deploy there are consul-clusters. Consul is so aggressive in finding agents and keep the cluster alive, it will eventually find other agents from other namespaces and basically start combining different stacks into one big stack which will break our setup.
On this journey I found another problem which your communicate helped to fix (which was kind of a user error)
https://github.com/projectcalico/calico/issues/4932

Any thoughts from you guys would be appreciated.

## Your Environment
* Calico version 3.20
* Orchestrator version (e.g. kubernetes, mesos, rkt): EKS k8s 1.19
* Operating System and version: linux windows
* Link to your project (optional):
