### ISSUE TITLE
Calico IPv6-only environment incompatible with latest containerd version

### ISSUE THREAD

**Issue by severindellsperger** [projectcalico/calico#4937]
The installation of Calico on Ubuntu 20.04 with an IPv6-only configuration fails if the latest containerd version (1.5.2-0ubuntu1~20.04.2) is used. 
Unfortunately, it seems that the latest changes in the containerd are incompatible with calico.
It seems only to affect IPv6 installation - IPv4 seems not to be affected.
It is likely that the problem also exists with other OS (versions).

## Expected Behavior

Calico should get installed without any issues and the nodes change and stay in the `Ready` state.

## Current Behavior

After applying the changes the nodes stay in a `NotReady` state with the following error message:
```
NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
``` 
The logs don't contain any further information, which helps to localize the problem.

## Possible Solution

We switched back to an older containerd version ( 1.3.3-0ubuntu2), which solved the problem.

## Steps to Reproduce (for bugs)

1. Init Cluster with appropriate IPv6 pod-network-cidr, service-cidr, etc.
2. Install Calico with IPv6-only settings:
```
* cni_network_config (assign_ipv4 : "false" and assign_ipv6: "true")
* vpp_dataplane_interface set to the appropriate interface
* service_prefix (set to the cluster service-cidr)
* change the env in calico-node:
          env:
            - name: CALICO_IPV4POOL_CIDR
              value: ""
            - name: CALICO_IPV6_POOL_CIDR
              value: "2001:db8:a::/64"
            - name: FELIX_IPV6SUPPORT
              value: "true"
            - name: IP
              value: "none"
            - name: CALICO_ROUTER_ID
              value: "hash"
            - name: IP6
              value: "autodetect"
```

## Context

For a research project, a new Kubernetes Cluster should be installed with Calico as CNI Plugin. First, we tried to get calico-vpp up and running. After we failed to deploy calico-vpp we switched to regular calico and faced similar issues. Because the project focus on an IPv6 environment, Calico has to be configured in IPv6 only mode. 

## Your Environment

* Calico version: latest (v3.20.0)
* Orchestrator version: kubernetes v 1.22.1
* containerd version: 1.5.2-0ubuntu1~20.04.2
* Operating System and version: Ubuntu 20.04
