### ISSUE TITLE
TCP listen on port 179 on all interface addresses creates security vulnerability

### ISSUE THREAD

**Issue by hanamantagoudvk** [projectcalico/calico#4974]
K8s cluster is installed on VMs/worker nodes having multiple interfaces. Couple of interfaces have external connectivity towards DC-GW.  Calico uses only one of the interface based on auto detection method . But TCP listens on all the non-calico interfaces.
This makes cluster vulnerable to DoS attack and BGP spoofing/hijacking.  

```
worker-pool1:~ # lsof -i -P  | grep bird | grep LISTEN
bird       9374     root    7u  IPv4     41912      0t0  TCP *:179 (LISTEN)
bird6      9375     root    7u  IPv6     39839      0t0  TCP *:179 (LISTEN)
```

Isn't there a way to configure specific address to bind ? Why can't just listen on interface address based on auto detection ?

**Comment by hanamantagoudvk** [comment]
@neiljerram : Any comments here ?

**Comment by neiljerram** [comment]
I suppose the important thing is for a Calico BIRD to listen on the address that any valid BGP peer will use to connect to it. I think the cases are as follows.

1. Node to node mesh peerings: the remote Calico node will try to connect to this node's bgp.IPv4Address.

2. BGPPeer with a peerSelector that includes this node: same as (1).

3. BGPPeer with an explicit peerIP: remote BGP will connect to the specified peerIP.

4. Non-Calico config for a BGP speaker outside the cluster, connecting in to us: speaker will connect on to whatever IP that config says.

I think bgp.IPv4Address is the same as the node's autodetected IP - @caseydavenport ? - so cases (1) and (2) should be fine if the listen was restricted to that IP.  Cases (3) and (4) would also be fine if the person responsible for the config took care to only use the IPs that they know Calico nodes will autodetect.

**Comment by hanamantagoudvk** [comment]
We should have configuration like this i below. Am i right ? 
confd should detect the `eth1 `interface ip and set it in` /etc/calico/confd/config/bird.cfg`

```
apiVersion: projectcalico.org/v3
kind: BGPConfiguration
metadata:
  name: default
spec:
  logSeverityScreen: Info
  nodeToNodeMeshEnabled: true
  asNumber: 
  serviceClusterIPs:
  ...
  serviceExternalIPs:
  ...
  listenPort: 178
  bindInterface : eth1          <--------- 
  communities:
  ...
  prefixAdvertisements:
  ....
```
