### ISSUE TITLE
calico IPIP virtual interface has 10Gbps bandwidth limit

### ISSUE THREAD

**Issue by lowang-bh** [projectcalico/calico#5092]
The host interface has 25Gbps speed，but IPIP mode， calico virtual interface only have 10Gbps。 Is there something wrong about configuration? Or it is just the limitation for vtep virtutal interface 
## Current Behavior

![image](https://user-images.githubusercontent.com/21003791/142169741-f0fc4c9f-2e5d-44c4-ae7c-af5decd5aeb4.png)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version: 0.1.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): k8s 1.12.5
* Operating System and version: CentOS Linux release 7.6.1810 (Core) 
* Link to your project (optional):

calico config
```yaml
  calico_backend: bird
  cni_network_config: |-
    {
        "name": "k8s-pod-network",
        "cniVersion": "0.1.0",
        "type": "calico",
        "etcd_endpoints": "__ETCD_ENDPOINTS__",
        "etcd_key_file": "__ETCD_KEY_FILE__",
        "etcd_cert_file": "__ETCD_CERT_FILE__",
        "etcd_ca_cert_file": "__ETCD_CA_CERT_FILE__",
        "log_level": "info",
        "mtu": 1500,
        "ipam": {
            "type": "calico-ipam"
        },
        "policy": {
            "type": "k8s",
            "k8s_api_root": "https://__KUBERNETES_SERVICE_HOST__:__KUBERNETES_SERVICE_PORT__",
            "k8s_auth_token": "__SERVICEACCOUNT_TOKEN__"
        },
        "kubernetes": {
            "kubeconfig": "__KUBECONFIG_FILEPATH__"
        }
    }
```
```
