### ISSUE TITLE
namespaceSelector allows unexpected traffic

### ISSUE THREAD

**Issue by lookbrook** [projectcalico/calico#5102]
If namespaceA allows access to ipA, then other namespaces that allow access to namespaceA will also be allowed to access ipA
## Expected Behavior

other namespaces that allow access to namespaceA cannot access ipA

## Current Behavior
other namespaces that allow access to namespaceA will also be allowed to access ipA

## Steps to Reproduce (for bugs)

1. create calico networkpolicy on namespace A
```
apiVersion: projectcalico.org/v3
kind: NetworkSet
metadata:
  name: ip-protect
  namespace: x01
  labels:
    IP-allow-list: true
spec:
  nets:
  - 8.8.8.8/32
---
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: ip-protect
  namespace: x01
spec:
  selector: all()
  order: 10
  types:
  - Egress
  egress:
  - action: Allow
    destination:
      selector: IP-allow-list == 'true'
```

2. create calico networkpolicy on namespace B
```
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: ip-protect
  namespace: x02
spec:
  selector: run == 'busybox'
  order: 10
  types:
  - Egress
  egress:
  - action: Allow
    destination:
      namespaceSelector: has(projectcalico.org/name) && projectcalico.org/name == 'x01'
      selector: all()
```
3. exec pod on namespace B and ping 8.8.8.8 successed

## Your Environment

* Calico version

calico 3.17.4

* Orchestrator version (e.g. kubernetes, mesos, rkt):

kubernetes 1.17.8

* Operating System and version:
centos7.6

* Link to your project (optional):

**Comment by frozenprocess** [comment]
If I understood the issue correctly you have two pods in two different namespaces and you would like only allow pods with the `IP-allow-list: true` label to talk to `ipA (8.8.8.8)`. 

Each `Networkset` is limited to the namespace that it is assigned to. [More about networksets] (https://docs.projectcalico.org/archive/v3.17/reference/resources/networkset)

I would suggest using `GlobalNetworkSet` if you like to apply a behivour to multiple namespaces. [More about GlobalNetworkSet](https://docs.projectcalico.org/archive/v3.17/reference/resources/globalnetworkset)
```
apiVersion: projectcalico.org/v3
kind: GlobalNetworkSet
metadata:
  name: ip-protect
  labels:
    IP-allow-list: true
spec:
  nets:
  - 8.8.8.8/32
---
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: forward-default-allow
spec:
  selector: IP-allow-list == 'true'
  order: 1000
  types:
  - Egress
  egress:
  - action: Allow
 ```
**Disclaimer**: This is just a demo policy, please don't use it in a production environment.
