### ISSUE TITLE
Calico network policy for ClusterIP

### ISSUE THREAD

**Issue by L4rS6** [projectcalico/calico#5129]
I'm unable to write a calico network policy which allows traffic from a specific POD to the ClusterIP (DNAT iptables rule).

I'm having a global default deny policy:

```
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: deny-any-to-any
spec:
  types:
  - Ingress
  - Egress

```

I want to be able to communicate to Kubernetes Services aka ClusterIPs. But to achieve that I have to allow Kubernetes Node to Node communication by the following policy:

```
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: permit-k8s-svc-out
spec:
  order: 500
  types:
  egress:
  - action: Allow
    protocol: TCP
    source:
    destination:
      nets:
      - 10.6.0.0/20 # k8s pod cidr
```

With that policy I'm able to communicate with the Kubernetes ClusterIP (10.96.0.1) from a POD, which is for example required by our CNI PODs. Am I right that there is no other way to allow that traffic? It would be nice to allow traffic based on it's destination (in my case 10.96.0.1), but that doesn't work as the ClusterIP are DNAT iptables rules.

I also got the same problem if I create a new service which has two POD endpoints:

```
# kubectl describe svc my-service
Name:              my-service
...
Type:              ClusterIP
...
IP:                10.96.139.205
IPs:               10.96.139.205
Port:              <unset>  80/TCP
TargetPort:        9376/TCP
Endpoints:         10.50.20.160:9376,10.50.200.11:9376
...
```

As you can see the endpoints are listening on port 9376. For that reason I have to write network policies with the destination port 9376 instead of port 80:

```
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: permit-ubuntu-to-ubuntu-svc
spec:
  types:
  - Ingress
  - Egress
  egress:
  - action: Allow
    protocol: TCP
    source:
      selector: app == 'ubuntu'
    destination:
      selector: app == 'ubuntu'
      ports:
      - 9376
  ingress:
  - action: Allow
    protocol: TCP
    source:
      selector: app == 'ubuntu'
    destination:
      selector: app == 'ubuntu'
      ports:
      - 9376
```

How is it possible to write policies which target on destination port 80 instead of 9376?

## Your Environment
* Calico version
```
Client Version:    v3.21.0
Git commit:        e9535482
Cluster Version:   v3.20.2
Cluster Type:      typha,kdd,k8s,operator,bgp,kubeadm
```
* Orchestrator version (kubernetes):
```
serverVersion:
  gitVersion: v1.22.2
  goVersion: go1.16.8
  major: "1"
  minor: "22"
  platform: linux/amd64
```
* Operating System and version:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
```

**Comment by Jc2k** [comment]
In the latest calico version you can write egress rules that target a service. I believe it would look like this:

```
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: allow-api-access
  namespace: my-app
spec:
  selector: all()
  egress:
    - action: Allow
      destination:
        services:
          name: my-service
          namespace: default
```

See https://docs.projectcalico.org/security/service-policy.

It looks like you can use the service selector for egress as a destination and for ingress as a source. But i don't think you can select by service in `spec.selector`, which may limit some of your rules.
