### ISSUE TITLE
Helm chart repo is broken

### ISSUE THREAD

**Issue by sl4dy** [projectcalico/calico#5143]
```
apiVersion: v1
entries:
  tigera-operator:
  - apiVersion: v2
    appVersion: v3.21.1
    created: "2021-12-02T17:13:12.449037905-08:00"
    description: Installs the Tigera operator for Calico
    digest: 6b55d4377b0d842c0a7685b3982bb9c144e019f024ad49e68f8f650a39a892af
    name: tigera-operator
    urls:
    - https://github.com/projectcalico/calico/releases/download/v3.21.1/tigera-operator-v3.21.1-0.tgz
    version: v3.21.1-0
  - apiVersion: v2
    appVersion: v3.21.0
    created: "2021-12-02T17:13:12.447301449-08:00"
    description: Installs the Tigera operator for Calico
    digest: 23c37c695c2a41a603bc7fd6196326fa9b5e93a8f9472ce577992aff402739d8
    name: tigera-operator
    urls:
    - https://github.com/projectcalico/calico/releases/download/others/tigera-operator-v3.21.0-0.tgz
    version: v3.21.0
```

- the versions are inconsistent **v3.21.1-0** vs **v3.21.0**, Helm treats v3.21.0 as latest one
- excepts **v3.21.1-0** version, the urls are invalid and lead to 404

**Comment by slushysnowman** [comment]
Yep, our pipelines are broken as we can't pull any charts

**Comment by lwr20** [comment]
I just re-ran `make helm-index` and I _think_ that's fixed it up.  Can you confirm please?

I'll investigate what happened here and get back to you, but I think someone manually pushed a broken helm index in error.

**Comment by sl4dy** [comment]
It is ok now @lwr20 .

**Comment by slushysnowman** [comment]
Seems to be working now, thanks!

**Comment by viceice** [comment]
Looks like it's broken again
![image](https://user-images.githubusercontent.com/1798109/144987358-4aa9edaa-9e34-404c-8506-7cd4f2183f7f.png)

**Comment by lwr20** [comment]
Worked for me?  But I did find an error in the docs - the version should be `v3.21.2`, not `v3.21.2-0` (the `-0` upsets our release tooling, I think semver defines the `-n` suffix as a pre-release)

```
lance@lwr20:~/scratch$ kind create cluster --config kind-config.yaml 
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.21.1) 🖼
 ✓ Preparing nodes 📦 📦  
 ✓ Writing configuration 📜 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing StorageClass 💾 
 ✓ Joining worker nodes 🚜 
Set kubectl context to "kind-kind"
You can now use your cluster with:

kubectl cluster-info --context kind-kind

Not sure what to do next? 😅  Check out https://kind.sigs.k8s.io/docs/user/quick-start/

lance@lwr20:~/scratch$ kubectl get no
NAME                 STATUS     ROLES                  AGE   VERSION
kind-control-plane   NotReady   control-plane,master   38s   v1.21.1
kind-worker          NotReady   <none>                 9s    v1.21.1

lance@lwr20:~/scratch$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "projectcalico" chart repository
Update Complete. ⎈Happy Helming!⎈

lance@lwr20:~/scratch$ helm install calico projectcalico/tigera-operator --version v3.21.2
W1207 09:47:20.273337  129294 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W1207 09:47:20.353424  129294 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
NAME: calico
LAST DEPLOYED: Tue Dec  7 09:47:20 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
```

**Comment by viceice** [comment]
@lwr20 I'm using the terraform `helm_release` to deploy the operator:

```hcl
resource "helm_release" "tigera-operator" {
  name = "tigera-operator"

  repository = "https://docs.projectcalico.org/charts"
  chart      = "tigera-operator"
  version    = "v3.21.1"

  max_history = 10

  values = [
    file("${path.module}/tigera-operator/values.yaml")
  ]
}
```
*values.yaml*
```yml
installation:
  # Configures Calico networking.
  calicoNetwork:
    mtu: 1400
    nodeAddressAutodetectionV4:
      firstFound: false
      cidrs:
        - 172.xx.yy.0/24
        - 172.xx.zz.0/24
    # Note: The ipPools section cannot be modified post-install.
    ipPools:
    - blockSize: 26
      cidr: 10.xx.0.0/16
      encapsulation: IPIPCrossSubnet
      natOutgoing: Enabled
      nodeSelector: all()
```

if update the version to v3.21.2, it will break with the error i posted 😕
