### ISSUE TITLE
GlobalNetworkPolicy does not apply rules to workload host

### ISSUE THREAD

**Issue by wayfrro** [projectcalico/calico#5161]
I'm trying to protect host as [in this howto](https://docs.projectcalico.org/security/kubernetes-nodes). Trying to apply GNP on automatic HostEndpoints, it works fine with all K8s nodes except for workload host. Changing defaultEndpointToHostAction to DROP helps, but then all wl->Host traffic is blocked unconditionally, which is not what we need.

## Expected Behavior
Rules are applied properly to all nodes, not only non-host nodes. 

## Current Behavior
Rules are applied correctly on all nodes, except for WL Host. 

## Steps to Reproduce (for bugs)
1. Enable automatic HostEndpoints
2. Apply some GNPs and try connecting like below:

It looks like this (that's the host for tested workload):

```
---
apiVersion: projectcalico.org/v3
kind: HostEndpoint
metadata:
  creationTimestamp: "2021-12-03T06:33:16Z"
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    my.test.label.io/node-role: worker
  ...
  name: worker-0-0-auto-hep
...
spec:
  expectedIPs:
  - 10.36.0.5
  - 10.233.111.0
  interfaceName: '*'
  node: worker-0-0
  profiles:
  - projectcalico-default-allow
```
Some other node:
```
---
apiVersion: projectcalico.org/v3
kind: HostEndpoint
metadata:
  creationTimestamp: "2021-12-03T06:33:16Z"
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    my.test.label.io/node-role: worker
    ...
  name: worker-0-1-auto-hep
...
spec:
  expectedIPs:
  - 10.36.0.6
  - 10.233.117.0
  interfaceName: '*'
  node: worker-0-1
  profiles:
  - projectcalico-default-allow
```

My GNPs:
```
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: ingress-k8s-masters
spec:
  selector: has(node-role.kubernetes.io/master)
  ingress:
  - action: Allow
    protocol: TCP
    destination:
      ports:
      - 6443
  - action: Allow
    destination:
      nets:
      - 127.0.0.1/32
  - action: Allow
    protocol: UDP
    destination:
      ports:
      - 53
  - action: Allow
    protocol: TCP
    source:
      selector: has(node-role.kubernetes.io/master)
    destination:
      ports:
      - 2380
      - 10250
```

```
---
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: ingress-k8s-workers
spec:
  selector: "my.test.label.io/node-role==\"worker\""
  ingress:
  - action: Allow
    destination:
      nets:
      - 127.0.0.1/32
  - action: Allow
    protocol: TCP
    source:
      selector: has(node-role.kubernetes.io/master)
    destination:
      ports:
      - 10250
  - action: Allow
    protocol: UDP
    destination:
      ports:
      - 53

```

Access from workload to random non-host node works perfect:
```
root@debug:~# nc -vzw1 10.233.117.0 22
Connection to 10.233.117.0 22 port [tcp/ssh] succeeded! # that's fine, failsafe port
root@debug:~# nc -vzw1 10.233.117.0 23
nc: connect to 10.233.117.0 port 23 (tcp) timed out: Operation now in progress # Fine!  
root@debug:~# nc -vzw1 10.233.117.0 10250
nc: connect to 10.233.117.0 port 10250 (tcp) timed out: Operation now in progress # Fine

```

Access from workload to host node:
```
root@debug:~# nc -vzw1 10.233.111.0 22
Connection to 10.233.111.0 22 port [tcp/ssh] succeeded! # that's fine, failsafe port
root@debug:~# nc -vzw1 10.233.111.0 23
nc: connect to 10.233.111.0 port 23 (tcp) failed: Connection refused # Open, but should be blocked!
root@debug:~# nc -vzw1 10.233.111.0 10250 
Connection to 10.233.111.0 10250 port [tcp/*] succeeded! # Open, but should be blocked!
```

## Context
I want to protect hosts with consistent policy describing on what ports workload can connect to K8s nodes. All I really wan't accomplish is that when I say "only wl->node port 123 and 124 are allowed" this is applied to all HostEndpoints, including workload Host.

## Your Environment
```
# calicoctl version
Client Version:    v3.19.2
Git commit:        6f3d4900
Cluster Version:   v3.19.2
Cluster Type:      kubespray,kubeadm,kdd,k8s
```
Kubespray is release-2.17
Ubuntu 20.04.3 LTS
Kubernetes v1.21.6

```
# kubectl get ds -n kube-system calico-node -oyaml
apiVersion: apps/v1
kind: DaemonSet
...
spec:
  selector:
    matchLabels:
      k8s-app: calico-node
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: calico-node
    spec:
      containers:
      - env:
        - name: DATASTORE_TYPE
          value: kubernetes
        - name: WAIT_FOR_DATASTORE
          value: "true"
        - name: FELIX_VXLANVNI
          value: "4096"
        - name: FELIX_VXLANPORT
          value: "4789"
        - name: CALICO_NETWORKING_BACKEND
          valueFrom:
            configMapKeyRef:
              key: calico_backend
              name: calico-config
        - name: CLUSTER_TYPE
          valueFrom:
            configMapKeyRef:
              key: cluster_type
              name: calico-config
        - name: CALICO_K8S_NODE_REF
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: CALICO_DISABLE_FILE_LOGGING
          value: "true"
        - name: FELIX_DEFAULTENDPOINTTOHOSTACTION
          value: RETURN
        - name: FELIX_HEALTHHOST
          value: localhost
        - name: FELIX_IPTABLESBACKEND
          value: Legacy
        - name: FELIX_IPTABLESLOCKTIMEOUTSECS
          value: "10"
        - name: CALICO_IPV4POOL_IPIP
          value: "Off"
        - name: FELIX_IPV6SUPPORT
          value: "False"
        - name: FELIX_LOGSEVERITYSCREEN
          value: info
        - name: CALICO_STARTUP_LOGLEVEL
          value: error
        - name: FELIX_USAGEREPORTINGENABLED
          value: "False"
        - name: FELIX_CHAININSERTMODE
          value: Insert
        - name: FELIX_PROMETHEUSMETRICSENABLED
          value: "False"
        - name: FELIX_PROMETHEUSMETRICSPORT
          value: "9091"
        - name: FELIX_PROMETHEUSGOMETRICSENABLED
          value: "True"
        - name: FELIX_PROMETHEUSPROCESSMETRICSENABLED
          value: "True"
        - name: NODEIP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: IP_AUTODETECTION_METHOD
          value: can-reach=$(NODEIP)
        - name: IP
          value: autodetect
        - name: NODENAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: FELIX_HEALTHENABLED
          value: "true"
        - name: FELIX_IGNORELOOSERPF
          value: "False"
        - name: CALICO_MANAGE_CNI
          value: "true"
        envFrom:
        - configMapRef:
            name: kubernetes-services-endpoint
            optional: true
        image: quay.io/calico/node:v3.19.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /bin/calico-node
            - -felix-live
          failureThreshold: 6
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: calico-node
        readinessProbe:
          exec:
            command:
            - /bin/calico-node
            - -felix-ready
          failureThreshold: 6
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 300m
            memory: 500M
          requests:
            cpu: 150m
            memory: 64M
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /lib/modules
          name: lib-modules
          readOnly: true
        - mountPath: /var/run/calico
          name: var-run-calico
        - mountPath: /var/lib/calico
          name: var-lib-calico
        - mountPath: /run/xtables.lock
          name: xtables-lock
        - mountPath: /host/etc/cni/net.d
          name: cni-net-dir
        - mountPath: /var/run/nodeagent
          name: policysync
        - mountPath: /var/log/calico/cni
          name: cni-log-dir
          readOnly: true
      dnsPolicy: ClusterFirst
      hostNetwork: true
      initContainers:
      - command:
        - /opt/cni/bin/calico-ipam
        - -upgrade
        env:
        - name: KUBERNETES_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: CALICO_NETWORKING_BACKEND
          valueFrom:
            configMapKeyRef:
              key: calico_backend
              name: calico-config
        envFrom:
        - configMapRef:
            name: kubernetes-services-endpoint
            optional: true
        image: quay.io/calico/cni:v3.19.2
        imagePullPolicy: IfNotPresent
        name: upgrade-ipam
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/cni/networks
          name: host-local-net-dir
        - mountPath: /host/opt/cni/bin
          name: cni-bin-dir
      - command:
        - /opt/cni/bin/install
        env:
        - name: CNI_CONF_NAME
          value: 10-calico.conflist
        - name: UPDATE_CNI_BINARIES
          value: "true"
        - name: CNI_NETWORK_CONFIG_FILE
          value: /host/etc/cni/net.d/calico.conflist.template
        - name: SLEEP
          value: "false"
        - name: KUBERNETES_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: quay.io/calico/cni:v3.19.2
        imagePullPolicy: IfNotPresent
        name: install-cni
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /host/etc/cni/net.d
          name: cni-net-dir
        - mountPath: /host/opt/cni/bin
          name: cni-bin-dir
      - image: quay.io/calico/pod2daemon-flexvol:v3.19.2
        imagePullPolicy: IfNotPresent
        name: flexvol-driver
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /host/driver
          name: flexvol-driver-host
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: calico-node
      serviceAccountName: calico-node
      terminationGracePeriodSeconds: 0
      tolerations:
      - operator: Exists
      volumes:
      - hostPath:
          path: /lib/modules
          type: ""
        name: lib-modules
      - hostPath:
          path: /var/run/calico
          type: ""
        name: var-run-calico
      - hostPath:
          path: /var/lib/calico
          type: ""
        name: var-lib-calico
      - hostPath:
          path: /etc/cni/net.d
          type: ""
        name: cni-net-dir
      - hostPath:
          path: /opt/cni/bin
          type: ""
        name: cni-bin-dir
      - hostPath:
          path: /run/xtables.lock
          type: FileOrCreate
        name: xtables-lock
      - hostPath:
          path: /var/lib/cni/networks
          type: ""
        name: host-local-net-dir
      - hostPath:
          path: /var/log/calico/cni
          type: ""
        name: cni-log-dir
      - hostPath:
          path: /var/run/nodeagent
          type: DirectoryOrCreate
        name: policysync
      - hostPath:
          path: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds
          type: DirectoryOrCreate
        name: flexvol-driver-host
...
```
```
# calicoctl get felixconfiguration default -oyaml
apiVersion: projectcalico.org/v3
kind: FelixConfiguration
metadata:
...
spec:
  bpfEnabled: false
  bpfExternalServiceMode: Tunnel
  bpfLogLevel: ""
  ipipEnabled: false
  logSeverityScreen: Info
  reportingInterval: 0s
  vxlanEnabled: true
  wireguardEnabled: false
```
```
# calicoctl get ippool default-pool -oyaml
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
...
spec:
  blockSize: 24
  cidr: 10.233.64.0/18
  ipipMode: Never
  natOutgoing: true
  nodeSelector: all()
  vxlanMode: Always
  ```
