### ISSUE TITLE
Helm chart v3.21.2 is broken for terraform

### ISSUE THREAD

**Issue by viceice** [projectcalico/calico#5162]
I'm using the terraform `helm_release` to deploy the operator:

```hcl
resource "helm_release" "tigera-operator" {
  name = "tigera-operator"

  repository = "https://docs.projectcalico.org/charts"
  chart      = "tigera-operator"
  version    = "v3.21.1"

  max_history = 10

  values = [
    file("${path.module}/tigera-operator/values.yaml")
  ]
}
```
*values.yaml*
```yml
installation:
  # Configures Calico networking.
  calicoNetwork:
    mtu: 1400
    nodeAddressAutodetectionV4:
      firstFound: false
      cidrs:
        - 172.xx.yy.0/24
        - 172.xx.zz.0/24
    # Note: The ipPools section cannot be modified post-install.
    ipPools:
    - blockSize: 26
      cidr: 10.xx.0.0/16
      encapsulation: IPIPCrossSubnet
      natOutgoing: Enabled
      nodeSelector: all()
```

if update the version to v3.21.2, it will break with the error i posted below 😕

_Originally posted by @viceice in https://github.com/projectcalico/calico/issues/5143#issuecomment-988107197_

![image](https://user-images.githubusercontent.com/1798109/144987358-4aa9edaa-9e34-404c-8506-7cd4f2183f7f.png)

**Comment by lwr20** [comment]
So the entry in the helm index at https://docs.projectcalico.org/charts/index.yaml for v3.21.1 is:
```
  - apiVersion: v2
    appVersion: v3.21.1
    created: '2021-12-06T19:36:19.79745053Z'
    description: Installs the Tigera operator for Calico
    digest: f963c1ae6dab7f0a63f51528296c82e294c977cd2cab1915fc0a8d771b3b4ab9
    name: tigera-operator
    urls:
    - https://github.com/projectcalico/calico/releases/download/v3.21.1/tigera-operator-v3.21.1-0.tgz
    version: v3.21.1
```

And for v3.21.2 is:
```
  - apiVersion: v2
    appVersion: v3.21.2
    created: '2021-12-06T19:36:19.798858941Z'
    description: Installs the Tigera operator for Calico
    digest: 7c2a106419dd84ca225790d34d0feab7dfaa5761cd2773fb61a432110eb24e61
    name: tigera-operator
    urls:
    - https://github.com/projectcalico/calico/releases/download/v3.21.2/tigera-operator-v3.21.2-0.tgz
    version: v3.21.2
```
I don't see any material difference between the two.  

The only slightly odd thing I see is that v3.21.2 is at the bottom of the list, whereas v3.21.1 is at the top.

Is there any way you can confirm that that's the issue?  If so, I can probably update the helm index updating tool to order the list before writing.
