### ISSUE TITLE
kubernetes networkpolicy ingress from same pod not working as expected

### ISSUE THREAD

**Issue by levimm** [projectcalico/calico#5165]
I'm using kubernetes networkpolicy spec and set ingress from podSelector selects the same pod as networkPolicy pod. But this pod can be access by any other pod. 

## Expected Behavior

Expect this pod could only be accessed by itself using Pod IP.

## Current Behavior

This pod can be access by any other pods.

## Steps to Reproduce (for bugs)

1. deploy nginx deployment.
1. with such networkpolicy spec
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nginx
  namespace: test
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: nginx
    ports:
    - port: 8089
      protocol: TCP
  podSelector:
    matchLabels:
      app: nginx
  policyTypes:
  - Ingress
```
2. curl succeeded from one of the nodes or pods
3. iptables looks fine from the node, the ipset `cali40s:cHwtnAWWXu-dz0534SIJhoz` has members as the nginx pod ip.
`-A cali-pi-_9IYQj5sqkYzgSUigeMl -p tcp -m comment --comment "cali:WhaxFmUNf3MCeuGx" -m set --match-set cali40s:cHwtnAWWXu-dz0534SIJhoz src -m multiport --dports 8089 -j MARK --set-xmark 0x10000/0x10000
`

## Your Environment

* Calico version: v3.10.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes v1.17.16
* Operating System and version: Ubuntu 18.04.6 LTS
* Link to your project (optional):
