### ISSUE TITLE
NetworkPolicy egress selectors not working

### ISSUE THREAD

**Issue by kub3let** [projectcalico/calico#5170]
I installed calico for dual stack which works fine and I'm trying to setup networkpolicies to lock down the environment.

For some reason I can't get selectors working.

It also kinder wonders me since setting a ipblock to the dns pod ip makes it work, but the container dns resolver is set to the service ip not the dns pod ip, using the service ip does not work.

Any help appreciated.

## Expected Behavior
DNS should be working with defined NetworkPolicy

## Current Behavior
DNS does not work, it only works with ipblock set to pod ip cidr

## Steps to Reproduce (for bugs)
```
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all
  namespace: example
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-cluster-dns
  namespace: example
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    # both podSelector and namespaceSelector
    # do not work ?
    - podSelector:
        matchLabels:
          k8s-app: kube-dns
    - namespaceSelector:
        matchLabels:
          name: kube-system
    # this works:
    # - ipBlock:
    #     cidr: 10.42.9.138/32
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
```

![image](https://user-images.githubusercontent.com/95883234/145470618-be7932a3-93e3-4f65-93a1-70f825b110db.png)

```
root@kube1:~# kubectl get all -A -o wide | grep dns
kube-system      pod/coredns-85cb69466-2hr9t                    1/1     Running   1 (103m ago)   22h   10.42.9.138     kube3   <none>           <none>
kube-system      service/kube-dns                             ClusterIP   10.43.0.10      <none>        53/UDP,53/TCP,9153/TCP       22h   k8s-app=kube-dns
kube-system      deployment.apps/coredns                   1/1     1            1           22h   coredns                              rancher/mirrored-coredns-coredns:1.8.4                                                                                               k8s-app=kube-dns
kube-system      replicaset.apps/coredns-85cb69466                    1         1         1       22h   coredns                              rancher/mirrored-coredns-coredns:1.8.4                                                                                               k8s-app=kube-dns,pod-template-hash=85cb69466
```

## Your Environment
* Calico version v3.21.2
* Orchestrator version (e.g. kubernetes, mesos, rkt): v1.22.4+k3s1
* Operating System and version: debian 11
