### ISSUE TITLE
Support for multiple bgp peers with automatic or peer-specific source address

### ISSUE THREAD

**Issue by krisiasty** [projectcalico/calico#5226]
Current bird [template](https://github.com/projectcalico/confd/blob/master/etc/calico/confd/templates/bird.cfg.template) contains global "source address" configuration option in the template bgp bgp_template [section](https://github.com/projectcalico/confd/blob/38a7ddf0c45da457cf8bb279b86bf144eb5f3cd9/etc/calico/confd/templates/bird.cfg.template#L85), which is not overrided later in the peer-specific section. With multiple L3 interfaces peering with different bgp peers this renders incorrect configuration where calico tries to use source ip address from other subnet than the peer it is trying to connect for all but one interfaces. 

Simple solution to this issue would be to provide option to remove the source address from the bgp_template section since it should be automatically selected by bird (unless your peer is not directly connected). In that case, the option should be part of node object, for example "useSourceIP: false" like below:

```
apiVersion: projectcalico.org/v3
kind: Node
metadata:
  name: storage-1-1
spec:
  bgp:
    asNumber: 4201061
    ipv4Address: 10.10.0.97/31
    useSourceIp: false
```
Or we could have peer-specific option defined in the calico bgppeer object, for example "localIP: 10.10.0.96" like below:
```
apiVersion: projectcalico.org/v3
kind: BGPPeer
metadata:
  name: storage-1-1
spec:
  asNumber: 65001
  node: storage-1-1
  peerIP: 10.10.0.96
  localIP: 10.10.0.97
```
If this option is present in the object, it should be used to render "source address" option for specific peer in bird configuration.
 
Having both options supported by calico should address all use cases, including those using bgp multihop. Unfortunately, implementing these features needs relevant changes in calico code.

Please also refer to the following issue and my comment:
https://github.com/projectcalico/calico/issues/1829#issuecomment-638494464
