### ISSUE TITLE
Calico-node pods fails. interface name `any-interface-at-all' must be shorter than IFNAMSIZ

### ISSUE THREAD

**Issue by andlf** [projectcalico/calico#5292]
After creating GlobalNetworkPolicy calico-node pods fails. Some iptables rules was not created.
felix/table.go 1324: Failed to execute ip(6)tables-restore command error=exit status 2 errorOutput="iptables-nft-restore v1.8.4 (nf_tables): interface name `any-interface-at-all' must be shorter than IFNAMSIZ (15)

## Expected Behavior
GlobalNetworkPolicy enabled

## Current Behavior
calico-node pods failed.

## Your Environment
Client Version:    v3.20.3
Git commit:        dcb4b76a
Cluster Version:   v3.20.3
Cluster Type:      kubespray,bgp,kubeadm,kdd,k8s
v1.22.4
* Orchestrator version (e.g. kubernetes, mesos, rkt):
v1.22.4
* Operating System and version:
Ubuntu 20.04.3
my policy:
```
---
kind: GlobalNetworkPolicy
apiVersion: projectcalico.org/v3
metadata:
  name: allow-all-worker
spec:
  selector: has(kubernetes-worker)
  order: 10
  applyOnForward: true
  preDNAT: true
#  doNotTrack: true
  ingress:
  - action: Allow
    protocol: TCP
    source:
      nets:
        - 192.168.0.0/16
        - 10.0.0.0/8
 #       - 127.0.0.1/8
        - 169.254.0.0/16
  - action: Allow
    protocol: UDP
    source:
      nets:
        - 192.168.0.0/16
        - 10.0.0.0/8
  #      - 127.0.0.1/8
        - 169.254.0.0/16
  - action: Allow
    protocol: TCP
    destination:
      ports: [443,80,31194,179]
  - action: Allow
    protocol: ICMP
#  egress:
#  - action: Allow
---
kind: GlobalNetworkPolicy
apiVersion: projectcalico.org/v3
metadata:
  name: bgp-allow
spec:
  selector: has(kubernetes-worker)
  order: 9
  applyOnForward: true
#  preDNAT: true
  doNotTrack: true
  ingress:
  - action: Allow
    protocol: TCP
 #   source:
 #     nets:
#        - 192.168.0.0/16
  #      - 0.0.0.0
    destination:
      ports: [179]
---
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
    name: drop-other-ingress-external
spec:
    order: 20
    preDNAT: true
    applyOnForward: true
    ingress:
      - action: Deny
    selector: has(kubernetes-worker)
---
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: allow-outbound-external
spec:
  order: 5
  egress:
    - action: Allow
  selector: has(host-endpoint)
```

**Comment by caseydavenport** [comment]
> interface name `any-interface-at-all' must be shorter than IFNAMSIZ (15)

The name `any-interface-at-all` seems an odd one - is that a real interface on your host? If so, what is it for? 

Have you modified Calico's interface prefix config option by chance?

**Comment by lysyy** [comment]
No, seems it is from felix code. 3 places. https://github.com/projectcalico/calico/search?q=any-interface-at-all

**Comment by caseydavenport** [comment]
Ah, interesting. It looks to me like that is not meant to end up in the renderned iptables rules and is just meant as an identifier to skip wildcarded HEPs, so perhaps there is a bug here. @neiljerram can confirm if that assessment is correct though.

**Comment by neiljerram** [comment]
> not meant to end up in the renderned iptables rules and is just meant as an identifier to skip wildcarded HEPs

That is correct.  (Except with "an identifier to identify the wildcard HEP", rather than "an identifier to skip wildcarded HEPs".)

@lysyy Do you know if this was working with a previous version of Calico?  That would help us work out if this is a recent regression, or is a bug that has always been present.

**Comment by lysyy** [comment]
No, i was not used any kind of policies early with Calico.. i think we can try to change https://github.com/projectcalico/calico/blob/79b442a53adb7d7f1fd62927d9322daf87dce9de/felix/dataplane/linux/endpoint_mgr.go 
string 1255 to a shoter value

**Comment by robinzoncruzo** [comment]
Have issued this with rule like that:
```
- apiVersion: projectcalico.org/v3
  kind: GlobalNetworkPolicy
  metadata:
    name: allow-lan
  spec:
    doNotTrack: true
    applyOnForward: true
    ingress:
      - action: Allow
        destination: {}
        source:
          nets:
            - 172.31.0.0/24
            - 192.168.100.0/24
    order: 10
    selector: kubernetes.io/os == "linux"
    types:
      - Ingress
```
After deletion of this rule everything runned fine.
