### ISSUE TITLE
Is it possible to change pod images for Helm install?

### ISSUE THREAD

**Issue by schizoid90** [projectcalico/calico#5422]
We're seeing an issue with images being rate limited by Docker when installing the tigera-operator through Helm

Is there a way to change which images the operator uses when starting up the services?

## Context

`helm install calico projectcalico/tigera-operator --version v3.21.3`

The operator installs and pods get created but several of them start to fail with ImagePullBackoff due to Docker Hub rate limiting

```
NAME                                       READY   STATUS                  RESTARTS   AGE
calico-kube-controllers-58494599f9-pqgzn   0/1     ContainerCreating       0          25h
calico-node-4jv2v                          0/1     Init:ImagePullBackOff   0          25h
calico-node-g4nkq                          0/1     ImagePullBackOff        0          25h
calico-node-lvfkh                          0/1     Init:ImagePullBackOff   0          25h
calico-node-v66w2                          0/1     Init:ImagePullBackOff   0          25h
calico-typha-5df589bb7d-cc74n              1/1     Running                 0          25h
calico-typha-5df589bb7d-q5z6m              0/1     ImagePullBackOff        0          25h
```

The error in calico-node

```
 Warning  Failed   36m (x128 over 25h)   kubelet  Failed to pull image "docker.io/calico/cni:v3.21.2": rpc error: code = Unknown desc = Error reading manifest v3.21.2 in docker.io/calico/cni: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

We have been getting round this issue by migrating images to our own registry but I don't see a way through the Helm chart to configure the images

```
helm show values projectcalico/tigera-operator
imagePullSecrets: {}

installation:
  enabled: true
  kubernetesProvider: ""

apiServer:
  enabled: true

certs:
  node:
    key:
    cert:
    commonName:
  typha:
    key:
    cert:
    commonName:
    caBundle:

# Configuration for the tigera operator
tigeraOperator:
  image: tigera/operator
  version: v1.23.3
  registry: quay.io
calicoctl:
  image: quay.io/docker.io/calico/ctl
  tag: v3.21.2
```

I can't find any ConfigMap or Secret we could change to edit this either behaviour either.

## Your Environment
* Calico version 3.21.2
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes 1.22.3
* Operating System and version: Ubuntu 20.04
