### ISSUE TITLE
Policy not allowing access from nginx-ingress as expected

### ISSUE THREAD

**Issue by vvatlin** [projectcalico/calico#5566]
Hello. 

Could you please help me to solve my problem. 

I installed calico-operator on top of the AWS VPC CNI in EKS.

for test I have 2 services ingress-nginx and frontend app (nginx).

I have 2 policies.
1) deny all inside frontend namespace 
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: frontend
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
```
2) frontend policy
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: frontend
  namespace: frontend
spec:
  podSelector:
    matchLabels:
      app: frontend
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
          podSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
```

After that, I can access frontend from ingress-nginx but only from the pod on the same node, from ingress-nginx pods on the other nodes I get timeout.

What is my mistake ?

* v3.20.0
* Orchestrator version: EKS 1.21.5
* amazon-linux
