### ISSUE TITLE
Unable to reach public ip from a pod using hostNetwork

### ISSUE THREAD

**Issue by yelhouti** [projectcalico/calico#5572]
## Expected Behavior
be able to reach public ip from a pod using hostNetwork.

## Current Behavior
it times out

## workaround
use 127.0.0.1 instead of public IP (for probes)

## Steps to Reproduce (for bugs)

1. create a new cluster
2. install calico with hostEndpoint: autocreate: true
3. block all ingress traffic
```yaml
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: drop-other-ingress
spec:
  order: 20
  preDNAT: true
  applyOnForward: true
  ingress:
    - action: Deny
  selector: has(host-endpoint)
```
4. allow incoming traffic from host-endpoint 
```yaml
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: allow-cluster-internal-ingress
spec:
  order: 10
  preDNAT: true
  applyOnForward: true
  ingress:
    - action: Allow
      source:
        nets: [10.233.64.0/18] # pod ip range retrieved from kubespray kube_pods_subnet
    - action: Allow
      source:
        selector: has(host-endpoint)
  selector: has(host-endpoint)
```

## Context
Probes stop working for pods using hostNetwork.

## Your Environment

* Calico version: 3.22.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): k8s 1.22
* Operating System and version: Alma Linux 8.5

## Similar issue:
https://github.com/projectcalico/calico/issues/4478
