### ISSUE TITLE
Provide Minimal RBAC Needed for Tigera Operator in Helm Chart

### ISSUE THREAD

**Issue by shelby-moore** [projectcalico/calico#5590]
Following principles of least access, the Tigera Operator and related components should have the minimum RBAC granted to function. Currently the RBAC included in the chart is overly permissive, violating this best practice. At minimum, consumers of the chart should have the option to opt-in to a minimal RBAC setup. Some OSS charts provide overly permissive RBAC by default to facilitate getting the tool up and running with minimum friction. In production ready environments this needs to be trimmed down.

## Expected Behavior
Provide an option to opt-in to a minimal RBAC setup for the operator in the Helm Chart.

## Current Behavior
The RBAC included in the chart is overly permissive.

## Possible Solution
I was able to get to a minimal RBAC setup by removing all permissions from the ClusterRole in the chart and iteratively adding back just what was needed to get the operator working on my installation. I've only tested this on an installation using EKS + the eBPF dataplane, so it may be incomplete:

```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tigera-operator
rules:
  - apiGroups:
      - operator.tigera.io
    resources:
      - '*'
    verbs:
      - list
      - get
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - crd.projectcalico.org
    resources:
      - '*'
    verbs:
      - list
      - watch
      - create
  - apiGroups:
      - ''
    resources:
      - namespaces
      - nodes
    verbs:
      - list
      - get
      - watch
      - update
  - apiGroups:
      - ''
    resources:
      - configmaps
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - ''
    resources:
      - pods
      - secrets
      - serviceaccounts
      - services
    verbs:
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - deployments
    verbs:
      - list
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
    verbs:
      - list
      - watch
      - create
      - update
      - escalate
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
    verbs:
      - bind
    resourceNames:
      - calico-typha
      - calico-node
      - calico-kube-controllers
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterrolebindings
    verbs:
      - list
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterrolebindings
    verbs:
      - create
      - update
  - apiGroups:
      - apiregistration.k8s.io
    resources:
      - apiservices
    verbs:
      - list
      - watch
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - list
      - watch
  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    verbs:
      - list
      - watch
  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    verbs:
      - create
      - update
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tigera-operator
subjects:
- kind: ServiceAccount
  name: tigera-operator
  namespace: tigera-operator
roleRef:
  kind: ClusterRole
  name: tigera-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tigera-operator
  namespace: calico-system
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
    verbs:
      - list
      - get
      - watch
      - create
      - update
  - apiGroups:
      - ''
    resources:
      - configmaps
      - services
      - serviceaccounts
      - secrets
    verbs:
      - create
      - update
      - delete
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - create
      - update
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tigera-operator
  namespace: calico-system
subjects:
  - kind: ServiceAccount
    name: tigera-operator
    namespace: tigera-operator
roleRef:
  kind: Role
  name: tigera-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tigera-operator
  namespace: kube-system
rules:
  - apiGroups:
      - 'apps'
    resources:
      - 'daemonsets'
      - 'deployments'
    verbs:
      - get
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tigera-operator
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: tigera-operator
    namespace: tigera-operator
roleRef:
  kind: Role
  name: tigera-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tigera-operator
  namespace: tigera-operator
rules:
  - apiGroups:
      - ''
    resources:
      - configmaps
      - secrets
    verbs:
      - list
      - get
      - watch
      - create
      - update
  - apiGroups:
      - ''
    resources:
      - events
    verbs:
      - create
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - create
      - update
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tigera-operator
  namespace: tigera-operator
subjects:
  - kind: ServiceAccount
    name: tigera-operator
    namespace: tigera-operator
roleRef:
  kind: Role
  name: tigera-operator
  apiGroup: rbac.authorization.k8s.io
```

## Your Environment
EKS using Kubernetes 1.21 with AWS VPC CNI networking and the latest tigera-operator Helm Chart (https://projectcalico.docs.tigera.io/getting-started/kubernetes/helm).
