### ISSUE TITLE
Configuring KubeControllersConfiguration in a declarative way

### ISSUE THREAD

**Issue by invidian** [projectcalico/calico#5592]
## Expected Behavior
`KubeControllersConfiguration/default` can be configured declaratively with only non-default values.

## Current Behavior
Right now, `KubeControllersConfiguration/default` resource is being created automatically once Calico is deployed, which makes user rely on either `calico-kube-controllers` deployment configuration (e.g. environment variables) or on `kubectl patch` or `calicoctl patch` after installing Calico.

## Possible Solution
Include `KubeControllersConfiguration/default` in the release manifests and Helm chart with empty spec so user can customize it.

## Others
As a workaround, is it OK to create the following `KubeControllersConfiguration/default` before `calico-kube-controllers` is running?

```yaml
apiVersion: crd.projectcalico.org/v1
kind: KubeControllersConfiguration
metadata:
  name: default
spec:
  controllers:
    node:
      hostEndpoint:
        autoCreate: Enabled
```

The status values field remains the same after reconciliation, however, the spec created by the controller looks like following:
```yaml
spec:
  controllers:
    namespace:
      reconcilerPeriod: 5m0s
    node:
      hostEndpoint:
        autoCreate: Disabled
      reconcilerPeriod: 5m0s
      syncLabels: Enabled
    policy:
      reconcilerPeriod: 5m0s
    serviceAccount:
      reconcilerPeriod: 5m0s
    workloadEndpoint:
      reconcilerPeriod: 5m0s
  etcdV3CompactionPeriod: 10m0s
  healthChecks: Enabled
  logSeverityScreen: Info
```

**Comment by caseydavenport** [comment]
Yep, agree this is a gap right now.

You can do this _after_ the API server is running (e.g., `kubectl replace -f config.yaml` but we have a gap right now where it's hard to do this prior to the Calico API server running.

**Comment by sebhoss** [comment]
@caseydavenport would the following workflow be ok for new installations?

1. apply calico-cni manifests
2. deploy calico-apiserver
3. apply (replace?) KubeControllersConfiguration
4. apply network policies

**Comment by caseydavenport** [comment]
@sebhoss yes that should work

**Comment by nullxx** [comment]
```
kubectl apply --server-side --validate=false -f - <<EOF
apiVersion: crd.projectcalico.org/v1
kind: KubeControllersConfiguration
metadata:
  name: default
spec:
  controllers:
    node:
      hostEndpoint:
        autoCreate: "Enabled"
EOF
```


Or just an ArgoCD template:
```yaml
apiVersion: crd.projectcalico.org/v1
kind: KubeControllersConfiguration
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-options: "ServerSideApply=true, Validate=false"
spec:
  controllers:
    node:
      hostEndpoint:
        autoCreate: "Enabled"
```
