### ISSUE TITLE
NetworkPolicy: EntityRule as Source Selector at Ingress is not deterministic

### ISSUE THREAD

**Issue by alex1989hu** [projectcalico/calico#5621]
## Expected Behavior

EntityRule as Source Selector at Ingress works nondeterministic but it works at Egress (based on my experience).

Note: I did not create any `egress` rule for simplicity.

## Current Behavior

- Pod with label `run == 'busybox'` was not able to connect despite the fact that the source selector was: `selector: run == 'busybox'`
- Pod with label `app == 'busybox'` was not able to connect despite the fact that the source selector was: `selector: app == 'busybox'`
- Pod with label `app == 'busybox'` was not able to connect despite the fact that the source selector was: `selector: run == 'busybox' || app == 'busybox'`
- Pod with label `run == 'busybox'` was not able to connect despite the fact that the source selector was: `selector: run == 'busybox' || app == 'busybox'`
- None of the Pods with labels `run == 'busybox'` / `app == 'busybox'` were not able to connect despite the fact that the source selector was: `selector: run == 'busybox' || app == 'busybox'`

If you remove selector (see later in Steps to Reproduce section) then it is deterministic: I was able to connect with both Pods.

### Note:
If I create only one `NetworkPolicy` to limit traffic from `busybox` Pod to `nginx` (and to `kube-dns`), then the selector at Egress works good.

## Possible Solution
N/A

## Steps to Reproduce (for bugs)

1. Create namespace
```sh
kubectl create ns fca-dev
```
2. Verify its labels
```sh
kubectl get ns fca-dev --show-labels
NAME      STATUS   AGE   LABELS
fca-dev   Active   27s   kubernetes.io/metadata.name=fca-dev
```

3. Create `nginx` Deployment and Service
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: nginx
  name: nginx
  namespace: fca-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nginx
  template:
    metadata:
      labels:
        role: nginx
    spec:
      containers:
      - image: bitnami/nginx:latest
        name: nginx
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8443
          name: https
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    role: nginx
  name: nginx
  namespace: fca-dev
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    role: nginx
  type: ClusterIP

```
4. Create `test.yaml`
```yaml
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: nginx
  namespace: fca-dev
spec:
  selector: role == 'nginx'
  types:
  - Ingress
  ingress:
  - action: Allow
    protocol: TCP
    source:
      selector: run == 'busybox' || app == 'busybox'
    destination:
      ports:
        - 8080
```
4. Publish previously created `test.yaml` with `calicoctl create -f - < test.yaml`
5. Start `busybox` Pod
```sh
kubectl run --namespace=fca-dev busybox --rm -ti --image busybox -- /bin/sh
```
6. Execute command within `busybox` Pod
```sh
/ # nc -zv nginx.fca-dev.svc.cluster.local 8080
nc: nginx.fca-dev.svc.cluster.local (172.23.30.60:8080): Connection timed out
```
7. Exit from `busybox` Pod
8. Create `busybox` Deployment
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: busybox
  name: busybox
  namespace: fca-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - image: busybox
        command:
        - /bin/sh
        - -c
        - --
        args:
          - 'trap : TERM INT; sleep infinity & wait'
        name: busybox
```
9. Open shell into `busybox` Pod created by `busybox` Deployment
```sh
kubectl -n fca-dev exec -it deployment/busybox -- sh
/ # nc -zv nginx.fca-dev.svc.cluster.local 8080
nc: nginx.fca-dev.svc.cluster.local (172.23.30.60:8080): Connection timed out
```
10. Close the shell
11. Comment selector line in `test.yaml`
```patch
diff --git a/test.yaml b/test.yaml
index eeb63a3..7aa48a9 100644
--- a/test.yaml
+++ b/test.yaml
@@ -10,8 +10,8 @@ spec:
   ingress:
   - action: Allow
     protocol: TCP
-    source:
-      selector: run == 'busybox' || app == 'busybox'
+    # source:
+    #   selector: run == 'busybox' || app == 'busybox'
     destination:
       ports:
         - 8080
```
12. Apply previously changed manifest with `calicoctl apply -f - < test.yaml`
13. Open shell into `busybox` Pod created by `busybox` Deployment
```sh
kubectl -n fca-dev exec -it deployment/busybox -- sh
/ # nc -zv nginx.fca-dev.svc.cluster.local 8080
nginx.fca-dev.svc.cluster.local (172.23.111.14:8080) open
```
14. Create `busybox` Pod and enter its shell
```sh
kubectl run --namespace=fca-dev busybox --rm -ti --image busybox -- /bin/sh
nginx.fca-dev.svc.cluster.local (172.23.30.60:8080) open
```

You can reach nondeterministic results if you remove `NetworkPolicy` by calling `calicoctl delete -f - < test.yaml`, modify the `selector` and create it again `calicoctl create -f - < test.yaml`
```yaml
    source:
      selector: run == 'busybox'
```

or

```yaml
    source:
      selector: app == 'busybox'
```

I checked `WorkloadEndpoint` by calling `calicoctl get -n fca-dev workloadendpoints`, both Pod have the labels e.g. `run: busybox` or `app: busybox`

```yaml
apiVersion: projectcalico.org/v3
items:
- apiVersion: projectcalico.org/v3
  kind: WorkloadEndpoint
  metadata:
    creationTimestamp: "2022-02-16T11:25:55Z"
    labels:
      projectcalico.org/namespace: fca-dev
      projectcalico.org/orchestrator: k8s
      projectcalico.org/serviceaccount: default
      run: busybox
    name: k8sworker02t-k8s-busybox-eth0
    namespace: fca-dev
    resourceVersion: "303401150"
    uid: a6b33276-4410-4d69-8c12-4109bc42dc22
  spec:
    containerID: 6fc08245d32e494981a3eead27b3204912c3e0b9b5b3f913550949ba6ac10ce0
    endpoint: eth0
    interfaceName: cali500da6a5c1e
    ipNetworks:
    - 172.24.8.216/32
    node: k8sworker02t
    orchestrator: k8s
    pod: busybox
    profiles:
    - kns.fca-dev
    - ksa.fca-dev.default
    serviceAccountName: default
- apiVersion: projectcalico.org/v3
  kind: WorkloadEndpoint
  metadata:
    creationTimestamp: "2022-02-16T11:21:23Z"
    generateName: busybox-7c69c8dcc5-
    labels:
      app: busybox
      pod-template-hash: 7c69c8dcc5
      projectcalico.org/namespace: fca-dev
      projectcalico.org/orchestrator: k8s
      projectcalico.org/serviceaccount: default
    name: k8sworker01t-k8s-busybox--7c69c8dcc5--sbm46-eth0
    namespace: fca-dev
    resourceVersion: "303399649"
    uid: f66b5e71-a925-4b70-899a-afe34121fc57
  spec:
    containerID: 0489fd2f2572a9d8cdd79888b6652233aef94d03d03e17e95ab6806622e294d9
    endpoint: eth0
    interfaceName: cali79b2634172b
    ipNetworks:
    - 172.24.12.243/32
    node: k8sworker01t
    orchestrator: k8s
    pod: busybox-7c69c8dcc5-sbm46
    profiles:
    - kns.fca-dev
    - ksa.fca-dev.default
    serviceAccountName: default
- apiVersion: projectcalico.org/v3
  kind: WorkloadEndpoint
  metadata:
    creationTimestamp: "2022-02-16T11:17:04Z"
    generateName: nginx-5b96bf498b-
    labels:
      pod-template-hash: 5b96bf498b
      projectcalico.org/namespace: fca-dev
      projectcalico.org/orchestrator: k8s
      projectcalico.org/serviceaccount: default
      role: nginx
    name: k8sworker01t-k8s-nginx--5b96bf498b--6xwjx-eth0
    namespace: fca-dev
    resourceVersion: "303398276"
    uid: b70e2b47-9142-471e-a347-815210f19c7d
  spec:
    containerID: 09a055bca59d6cfc9b1a61b520707b2de6ad9074a1f3f148e06e7e5b24a86341
    endpoint: eth0
    interfaceName: cali820131b8b33
    ipNetworks:
    - 172.24.12.115/32
    node: k8sworker01t
    orchestrator: k8s
    pod: nginx-5b96bf498b-6xwjx
    ports:
    - name: http
      port: 8080
      protocol: TCP
    - name: https
      port: 8443
      protocol: TCP
    profiles:
    - kns.fca-dev
    - ksa.fca-dev.default
    serviceAccountName: default
kind: WorkloadEndpointList
metadata: {}
```

## Context

I would like to limit Pod inter communication.

## Your Environment

* Calico version: 3.19.2
* Orchestrator version (e.g. kubernetes, mesos, rkt): rke; Rancher v2.6.3
* Kubernetes version: v1.21.8
* Operating System and version: CentOS Linux release 7.9.2009 (Core) 3.10.0-1160.53.1.el7.x86_64
* Link to your project (optional):

**Comment by caseydavenport** [comment]
@alex1989hu I followed your steps exactly (although I used Calico v3.19.4, but I don't think that should matter) and was not able to reproduce what you're seeing. The policiy correctly allowed the expected traffic and denied unexpected traffic.

I would check for unexpected NAT in your cluster - do you have the `--cluster-cidr` argument set on the kube-proxy, and if so does it match or include the range used for pod IPs? Is there any other NAT that might be occurring in your cluster? It might be that you are seeing inconsistent behavior because some pod traffic is being NAT'd so that the receiving end of the connection doesn't recognize the source.

**Comment by alex1989hu** [comment]
@caseydavenport thank you four the suggestion. You could be right concerning NAT.

When I schedule the `busybox` Pod onto the same worker node, then `Ingress` rule works. Once I schedule onto different node, then it does not work.

When Pods are

- on the same node I see in `nginx` log the client (`busybox`) IP is: 172.21.0.1
- not on the same node I see in `nginx` log the client (`busybox`) IP is: 10.40.101.12 - **which is the IP address of the worker node**

Yes, we set  `--cluster-cidr=172.24.0.0/21` for `kube-proxy`, and create the following Kubernetes resource:
```yaml
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: worker-ippool
spec:
  cidr: "172.24.8.0/21"
  blockSize: "24"
  ipipMode: Never
  natOutgoing: true
  nodeSelector: node-role.kubernetes.io/worker == "true"
```

**Comment by alex1989hu** [comment]
> So long as your cluster-cidr and IP pool match, I wouldn't expect it to be kube-proxy performing that NAT. But perhaps there is something else on the node programming that rule.

To be honest, I am confused now. Kindly ask you to help me out to understand what is going on.

We set

```yaml
kubeController:
  clusterCidr: "172.24.0.0/21"
```

and create two `IPPool`:

```yaml
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: default-ipv4-ippool
spec:
  cidr: "172.24.0.0/21"
  blockSize: 26
  ipipMode: Never
  natOutgoing: true
  nodeSelector: node-role.kubernetes.io/worker != "true"
---
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: worker-ippool
spec:
  cidr: "172.24.8.0/21"
  blockSize: "24"
  ipipMode: Never
  natOutgoing: true
  nodeSelector: node-role.kubernetes.io/worker == "true"
```

Pods (`busybox`/`nginx`) are running on nodes which have common label: `node-role.kubernetes.io/worker == "true"`.

In that case cluster-cidr and IP pool does match* on worker nodes because we set `kubeController.clusterCidr: "172.24.0.0/21"` and Pods are running in `cidr: "172.24.8.0/21"` - see the `WorkloadEndpoint` in one OP comment.

*: They do not have intersection:

| CIDR          | Usable Host IP Range       |
|---------------|----------------------------|
| 172.24.0.0/21 | 172.24.0.1 - 172.24.7.254  |
| 172.24.8.0/21 | 172.24.8.1 - 172.24.15.254 |



What is the purpose of `natOutgoing: true`here? The [documentation](https://projectcalico.docs.tigera.io/reference/resources/ippool) says:
> When enabled, packets sent from Calico networked containers in this pool to destinations outside of this pool will be masqueraded.

I expect that Calico shall not perform outgoing NAT when connecting to an IP address that is in a Calico IPPool. That is what I learned from another [documentation](https://projectcalico.docs.tigera.io/networking/workloads-outside-cluster).

**Comment by caseydavenport** [comment]
```
kubeApi:
  serviceClusterIpRange: "172.23.0.0/17"
kubeController:
  clusterCidr: "172.24.0.0/21"
```

Are you seeing the cluster CIDR on the kube-proxy as well? That's the more relevant setting here.

At least one problem appears to be that you're assigning pods from `172.24.8.0/21` which is NOT part of `172.24.0.0/21` - every pod IP needs to fall within the cluster CIDR passed to the kube-proxy. 

`natOutgoing` does what you expect - it should not NAT traffic to any other IP address within a Calico IP pool. The "outside of this pool" statement is just wrong, I'll fix it.
