### ISSUE TITLE
Calico-kube-controllers has Error: container has runAsNonRoot and image will run as root

### ISSUE THREAD

**Issue by Heeseok-82** [projectcalico/calico#5713]
Trying to install Calico using helm (version 3.0) to AWS EKS (nodes using graviton 2)
I followed this step : https://projectcalico.docs.tigera.io/getting-started/kubernetes/helm

## Expected Behavior
Installed without any error

## Current Behavior

```
calico-kube-controllers pod showing error below:
calico-kube-controllers-549dfc5dc7-v676j   0/1     **CreateContainerConfigError**   0          16m
```

and detailed error :

```

Warning  Failed     15m (x12 over 17m)   kubelet            Error: container has **runAsNonRoot and image will run as root** (pod: "calico-kube-controllers-549dfc5dc7-v676j_calico-system(afe2087d-caa3-439e-b310-8624f862f62f)", container: calico-kube-controllers)
```

I tried to change psp or pods security context using kubectl edit 
but psp yaml file  has automatically changed back to its original :

```
Run As User:
    Rule:  **MustRunAsNonRoot**
  Se Linux:
    Rule:  RunAsAny
  Supplemental Groups:
    Ranges:
      Max:  65535
      Min:  1
    Rule:   MustRunAs
```

and pod yaml file cannot be changed : 

```
    name: calico-kube-controllers
    readinessProbe:
      exec:
        command:
        - /usr/bin/check-status
        - -r
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      **runAsNonRoot: true**
```

## Possible Solution

tryied to change psp and pod yaml using kubectl edit, but it didnt work 

## Your Environment
Using AWS EKS(kubernetes v1.21) with nodes of graviton instances. 

It seems that same trouble has solved years ago, but it is happening again. 
Can you help me to solve this?
