### ISSUE TITLE
Network policy seems to block kubectl exec?

### ISSUE THREAD

**Issue by perezjasonr** [projectcalico/calico#5743]
Feel like i must be losing my mind, but all the trial and error, and process of elimination leaves me no choice but to conclude that a network policy isn't allowing an exec call.

## Expected Behavior

I should be able to exec into the pod and run commands

## Current Behavior

I'm using helm to install hashicorp vault. the basic setup has docs that tell you to exec in and run some commands to initialize vault.
ie: vault operator init

there is a network policy in place which allows anything in the vault namespace to ingress or egress to and from its own ns.

but whats strange here is i can't even exec in, and get a network denied error of some kind. it just hangs, Is it possible that the networkpol can block one from exec-ing in?

according to k8s docs, network pols shouldnt be able to block loopback, or from its own node (kubelet/container runtime, which i believe is what is needed for exec).

but when i delete the netpol I can exec in and run the command. why would that be?
note that im not even talking about the command being successful or not, but the ability to exec in and it not hang in the first place.

the only thing i can guess are one of two things:
something crazy is going on under the hood and i need a rule for it, like allow port, for exec maybe from kubelet or something.

## Steps to Reproduce (for bugs)

1. install vault using helm, https://github.com/hashicorp/vault-helm
2. have a network policy in the vault namespace that allows ingress/egress to/from pods in the vault ns freely
3. the init call will hang, something like this kubectl exec -it -n vault vault-0 -- vault operator init
4. if do this entire process again, but without the network policy, suddenly it works

## Context

I noticed kubelet saying this as well, the readiness probe is also exec, and being denied. Is it possible for the network pol to be the cause?

```
Mar 11 19:35:15 ip-10-42-32-149.ec2.internal kubelet[20271]: E0311 19:35:15.005034   20271 remote_runtime.go:394] "ExecSync cmd from runtime service failed" err="rpc error: code = DeadlineExceeded desc = failed to exec in container: timeout 3s exceeded: context deadline exceeded" containerID="e2c5fcce675ccd2ac80cb3a248ad2c02d8577fffd36fb81419e37d156d2e81ba" cmd=[/bin/sh -ec vault status -tls-skip-verify]
Mar 11 19:35:19 ip-10-42-32-149.ec2.internal kubelet[20271]: E0311 19:35:19.979755   20271 remote_runtime.go:394] "ExecSync cmd from runtime service failed" err="rpc error: code = DeadlineExceeded desc = failed to exec in container: timeout 3s exceeded: context deadline exceeded" containerID="e2c5fcce675ccd2ac80cb3a248ad2c02d8577fffd36fb81419e37d156d2e81ba" cmd=[/bin/sh -ec vault status -tls-skip-verify]
Mar 11 19:35:25 ip-10-42-32-149.ec2.internal kubelet[20271]: E0311 19:35:25.011105   20271 remote_runtime.go:394] "ExecSync cmd from runtime service failed" err="rpc error: code = DeadlineExceeded desc = failed to exec in container: timeout 3s exceeded: context deadline exceeded" containerID="e2c5fcce675ccd2ac80cb3a248ad2c02d8577fffd36fb81419e37d156d2e81ba" cmd=[/bin/sh -ec vault status -tls-skip-verify]
Mar 11 19:35:29 ip-10-42-32-149.ec2.internal kubelet[20271]: E0311 19:35:29.959013   20271 remote_runtime.go:394] "ExecSync cmd from runtime service failed" err="rpc error: code = DeadlineExceeded desc = failed to exec in container: timeout 3s exceeded: context deadline exceeded" containerID="e2c5fcce675ccd2ac80cb3a248ad2c02d8577fffd36fb81419e37d156d2e81ba" cmd=[/bin/sh -ec vault status -tls-skip-verify]
```

## Your Environment

* Calico version 3.17.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubeadm, on aws
* Operating System and version: CentOS Stream release 8
* Link to your project (optional):

**Comment by caseydavenport** [comment]
Do you have any host endpoints configured on your cluster? What does your network policy look like and do you have any other policies?

I agree regular network policies shouldn't impact a host from execing into its own pods. To be honest, I don't think network policy should impact exec at all.

If I had to guess, it's not the exec itself that is failing, rather it's the command that is being run within the container that is timing out (because policy isn't allowing it)  

> there is a network policy in place which allows anything in the vault namespace to ingress or egress to and from its own ns.

Perhaps the exec command `/bin/sh -ec vault status -tls-skip-verify` relies on traffic that leaves the vault namespace and so is denited?

**Comment by perezjasonr** [comment]
heres the network policy in full:

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: vault-wide
  namespace: vault
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector: {}
    # for the ui
    - podSelector:
        matchLabels:
          app: istio-ingressgateway
      namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: istio-system
    # required to receive from cert manager via issuer
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: cert-manager
  egress:
  - to:
    - podSelector: {}
  - to:
  # kubeapi calls from vault configure kubernetes auth
    - ipBlock:
        cidr: <controll node cidr>
    ports:
    - port: 6443
      protocol: TCP
    # dns for postgres
  - to:
    - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
```

so as you can see it allows to/from namespace, most of the other rules dont really come into play they assume we get past this point.

i thought the exact same thing you did, that perhaps status, or operator init, might call out to another namespace, or needs a cidr, but i cant imagine what else it would talk to. posgres is in the vault ns, there are other vault pods, but of course those are in the vault ns.

my last guess is, maybe it needs to egress to kubelet? and thats being blocked. OR...that readiness check, might require egress to kubelet, and until that passes, the exec doesn't work. but I'm just throwing things out there.

no special endpoints configured, just w/e comes with the vault helm chart.

also if it needs kube-system for any reason, we dont have a network policy touching that yet.
the vault ns also doesn't have istio inject, if thats relevant.
