### ISSUE TITLE
NetworkPolicy not working in EKS

### ISSUE THREAD

**Issue by axkng** [projectcalico/calico#5761]
I have a EKS-cluster in which I deployed calico for networkpolicy enforcement.
To test if everything works, I created a test namespace with a pod in it and created a networkpolicy, that would deny all ingress-traffic.
If I now try to reach this pod from another pod in another namespace, it just works.
## Expected Behavior

I expected the pod to not be reachable.

## Current Behavior

The pod is reachable.

## Steps to Reproduce (for bugs)

1. Create a EKS-cluster (v.1.21.9), with bottlerocket-os on t4g-instances with the cluster using ipv6 and vpc-cni.
2. Now install calico to the cluster, following the guide of [AWS](https://docs.aws.amazon.com/eks/latest/userguide/calico.html)
3. Deploy a example workload with a policy denying all ingress.
4. Try to reach the example workload from another pod, possibly in another namespace.

## Context

I want to isolate workloads in different namespace from eachother, which is not possible now.

## Your Environment

* Calico version 3.22.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes 1.21.9
* Operating System and version: Bottlerocket OS 1.6.2 (on ARM)
* Link to your project (optional):

**Comment by vladyslav-mahilevskyi** [comment]
In my opinion, it would be useful to share at least the network policy manifest.

**Comment by Furragen** [comment]
That is correct.
I used this manifest to setup a quick test environment:
```
---
apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: test
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: test
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: default-ingress-deny
  namespace: test
spec:
  podSelector:
    matchLabels:
      app: nginx
  ingress: []
```

It does not matter if I try to connect to the pod directly or via the service. I always can connect.

**Comment by vladyslav-mahilevskyi** [comment]
Your Network Policy seems to be wrong.
Please try this one.
```
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
spec:
  podSelector: {}
  policyTypes:
  - Ingress
```
More info: https://kubernetes.io/docs/concepts/services-networking/network-policies/#default-deny-all-ingress-traffic
