### ISSUE TITLE
Deploying helm chart 3.22.2 fails for a new cluster while 3.21.4 works

### ISSUE THREAD

**Issue by EugenMayer** [projectcalico/calico#5775]
I'am creating a cluster from scratch via terraform for the reproduction of https://github.com/projectcalico/calico/issues/5575 -
When using 3.21.4 the cluster comes up just fine, while 3.22.2 ails.

It fails in a strange way, which means the only real thing that i can see is that cert-manager fails to talk to the calico API. The tigera operator seems to work just fine / come up just fine.

I understand that i need to provide better logs here - what should I look for / fetch? Which pods are interesting to get the logs from? The logs i have are https://gist.github.com/EugenMayer/94866586c516591f95b4ea8184ff8c13

Env:
- ubuntu 20.04 (latest) LTS
- rke2 v1.22.3+rke2r1 / rke2 v1.23.52+rke2r1 / k3s 1.22.6-k3s1
- 1 server node, 2 agent nodes (workloads)

I deploy plainly via TF, nothing special:

```
    bgp: Disabled
    linuxDataplane: ${dataPlane}
    hostPorts: ${hostPorts}
    ipPools:
      - blockSize: 26
        # TODO: make this configurable, yet matches k3s deployments
        cidr: 10.42.0.0/16
        encapsulation: ${encapsulation}
        natOutgoing: Enabled
        nodeSelector: all()
```
