### ISSUE TITLE
Network Policies not working in windows when using podSelector

### ISSUE THREAD

**Issue by manuelbuil** [projectcalico/calico#5800]
When setting up a network policy that involves pods running in a windows node it does not always work. If an ipBlock or a port is defined, things work and I can see the VFP rules being created. For example, for port 3000:

```
    RULE : 158F4FC7-C20D-4F74-8CDC-BEB1728B77BF
        Friendly name : policy-default/knp.default.test-network-policy-9hsYrf0hoS-7JCIf-0
        Priority : 1000
        Flags : 8195 terminating stateful
        Type : allow
        Conditions:
            Protocols : 6
            Destination ports : 3000-3000
        Flow TTL: 240
        FlagsEx : 0
```

However, when using podSelector, that rule disappears and I can no longer access the service offered by the pod

## Expected Behavior

When creating a networkpolicy that includes podSelector, I'd expect all pods containing the label to be able to connect to the pod running in a windows node. Rule example:

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-network-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: pstools-app-node
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: multitool
```

## Current Behavior

The pods in windows are not accessible anymore because the rule `policy-default/knp.default.test-network-policy-9hsYrf0hoS-7JCIf-0` is deleted

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version: v3.22.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): k8s 1.22.7
* Operating System and version: Windows Server 2019
* Link to your project (optional):
