### ISSUE TITLE
Egress definitions don't work

### ISSUE THREAD

**Issue by liyaka** [projectcalico/calico#5810]
I'm trying to define the following egress rule - my pods with 'my-plugin' label are allowed to access only the outside world and are not allowed to access any internal IP, including nodes IPs and etc:
```
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: deny-from-plugins
spec:
  types:
  - Egress
  egress:
  - action: Allow
    destination:
      notNets:
      - 10.3.4.0/24
      - 10.3.5.0/24
      - 10.3.6.0/24
    source:
      selector:
        appType == 'my-plugin'
    
```
where 10.3.4.0/24, 10.3.5.0/24, 10.3.6.0/24 are the relevant subnets CIDRs

## Expected Behavior
my pods can access external IPs and not internal ones

## Current Behavior
There is no access to any IP at all...

## Your Environment

* Calico version - v3.22.1
* Orchestrator version  - EKS 1.21

What am I missing?

**Comment by liyaka** [comment]
I also tried 
```
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: deny-from-plugins
spec:
  types:
  - Egress
  egress:
  - action: Allow
    destination:
      nets:
      - 0.0.0.0/0
      notNets:
      - 10.3.4.0/24
      - 10.3.5.0/24
      - 10.3.6.0/24
    source:
      selector:
        appType == 'my-plugin'
        
```
same result
