### ISSUE TITLE
Failed to perform list of current data during resync ListRoot="/calico/resources/v3/projectcalico.org/profiles" error=connection is unauthorized:

### ISSUE THREAD

**Issue by nishit93-hub** [projectcalico/calico#5834]
Hi, 

**I was trying to deploy `Argocd` on cluster but container didn't come. After i describe the Argocd pods, there is get the below error** 

> kubelet  (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "4faa9d59e685b4d7ce11a2cec835f7d5c6918851fd8aadaa1530418a2dda8972": error getting ClusterInformation: connection is unauthorized: clusterinformations.crd.projectcalico.org "default" is forbidden: User "system:serviceaccount:kube-system:calico-node" cannot get resource "clusterinformations" in API group "crd.projectcalico.org" at the cluster scope

**After that i checked the `Calico pods` logs, there i find the below error**

> ry.k8s.io" at the cluster scope
> 2022-04-01 19:23:52.766 [INFO][95] felix/watchercache.go 186: Failed to perform list of current data during resync ListRoot="/calico/resources/v3/projectcalico.org/networksets" error=connection is unauthorized: networksets.crd.projectcalico.org is forbidden: User "system:serviceaccount:kube-system:calico-node" cannot list resource "networksets" in API group "crd.projectcalico.org" at the cluster scope
> 2022-04-01 19:23:52.766 [INFO][95] felix/watchercache.go 174: Full resync is required ListRoot="/calico/resources/v3/projectcalico.org/felixconfigurations"
> 2022-04-01 19:23:52.868 [INFO][93] confd/watchercache.go 174: Full resync is required ListRoot="/calico/ipam/v2/host/sn1-r720-g09-25.puretec.purestorage.com"
> 2022-04-01 19:23:52.869 [INFO][93] confd/watchercache.go 186: Failed to perform list of current data during resync ListRoot="/calico/ipam/v2/host/sn1-r720-g09-25.puretec.purestorage.com" error=connection is unauthorized: blockaffinities.crd.projectcalico.org is forbidden: User "system:serviceaccount:kube-system:calico-node" cannot list resource "blockaffinities" in API group "crd.projectcalico.org" at the cluster scope
> 2022-04-01 19:23:52.882 [INFO][95] felix/watchercache.go 174: Full resync is required ListRoot="/calico/resources/v3/projectcalico.org/nodes"
> 2022-04-01 19:23:52.883 [INFO][95] felix/watchercache.go 186: Failed to perform list of current data during resync ListRoot="/calico/resources/v3/projectcalico.org/nodes" error=connection is unauthorized: nodes is forbidden: User "system:serviceaccount:kube-system:calico-node" cannot list resource "nodes" in API group "" at the cluster scope
> 2022-04-01 19:23:52.966 [INFO][95] felix/watchercache.go 186: Failed to perform list of current data during resync ListRoot="/calico/resources/v3/projectcalico.org/hostendpoints" error=connection is unauthorized: hostendpoints.crd.projectcalico.org is forbidden: User "system:serviceaccount:kube-system:calico-node" cannot list resource "hostendpoints" in API group "crd.projectcalico.org" at the cluster scope
> 2022-04-01 19:23:52.966 [INFO][95] felix/watchercache.go 174: Full resync is required ListRoot="/calico/resources/v3/projectcalico.org/globalnetworkpolicies"
> 2022-04-01 19:23:53.008 [INFO][95] felix/watchercache.go 174: Full resync is required ListRoot="/calico/resources/v3/projectcalico.org/profiles"
> 2022-04-01 19:23:53.009 [INFO][95] felix/watchercache.go 186: Failed to perform list of current data during resync ListRoot="/calico/resources/v3/projectcalico.org/profiles" error=connection is unauthorized: namespaces is forbidden: User "system:serviceaccount:kube-system:calico-node" cannot list resource "namespaces" in API group "" at the cluster scope

Please guide for this issue.

**Comment by gondaz** [comment]
Hi! 
I've bumped into the same issue recently. It looks like there is some insufficient cluster role permissions for new versions of calico.
As of me I was able to fix this by adding some missed entries to the ClusterRole resource kind:
```
- apiGroups:
  - ""
  resources:
  - pods
  - **namespaces**
  - serviceaccounts
  verbs:
  - list
  - watch
```

```
- apiGroups:
  - crd.projectcalico.org
  resources:
  - globalfelixconfigs
  - felixconfigurations
  - bgppeers
  - globalbgpconfigs
  - bgpconfigurations
  - ippools
  - ipamblocks
  - globalnetworkpolicies
  - globalnetworksets
  - networkpolicies
  - **networksets**
  - clusterinformations
  - **hostendpoints**
  - **blockaffinities**
  verbs:
  - get
  - list
  - watch
```
Check out how it looks at your cluster and edit if required as follows:
`kubectl -n kube-system edit clusterrole calico-node -o yaml`
