### ISSUE TITLE
Issue when trying to set resource requests / limits on calico API

### ISSUE THREAD

**Issue by robbo10** [projectcalico/calico#5841]
When deploying the calico operator through Helm we are running into an issue when trying to set resource requests/limits on the calico API pod, when we update the values.yaml to try and set these they don't get implemented.

## Expected Behavior
The calico api pod should have requests/limits set

## Current Behavior
The pod runs without request/limits

## Possible Solution
The ability to add this through the values.yaml per the following doc it can be set for Node, Typha, KubeControllers
https://projectcalico.docs.tigera.io/reference/installation/api#operator.tigera.io/v1.ComponentName

## Steps to Reproduce (for bugs)
Deploy the calico operator through helm

## Context
We use OPA for enforcing some rules / guidelines for pods in our clusters, one of these rules is that every pod must specify  resource requests/limits 

## Your Environment
EKS

**Comment by lwr20** [comment]
According to the doc at https://projectcalico.docs.tigera.io/reference/installation/api#operator.tigera.io/v1.ComponentName, valid values of componentName are:

> One of: Node, Typha, KubeControllers

So looks like you _can't_ set requests and limits on the apiserver via the Installation resource currently.

**Comment by lwr20** [comment]
pinging @caseydavenport

**Comment by caseydavenport** [comment]
Yep, looks like we're missing that. That's an oversight, I will add this to an upcoming release.

**Comment by parsley42** [comment]
Recently we experienced an issue where the API server had a memory leak and caused some issues. I believe the leak (#8383) has been fixed, but it looks like I'm still not able to set requests/limits for this, so I thought I'd try to wake this issue up again.

**Comment by lwr20** [comment]
I _think_ that's actively being worked on, but I don't recall if its scheduled for v3.28.0.  @caseydavenport might know?

**Comment by caseydavenport** [comment]
Actually, looking at the code it appears this is already possible as of this commit from 2 years ago: https://github.com/tigera/operator/commit/331f24d8f5d69cb98d1a97738b2d75205533b5cc

For example:

```
apiVersion: operator.tigera.io/v1
kind: APIServer
metadata:
  name: default
spec:
  apiServerDeployment:
    spec:
      template:
        spec:
          containers:
          - name: calico-apiserver
            resources:
              limits:
                cpu: 100m
                mem: 100Mi
```
