### ISSUE TITLE
kubernetes network policy doesn't seem to be able to take precedence over global network policy when policy action is allowed in global policy

### ISSUE THREAD

**Issue by weinong** [projectcalico/calico#5940]
kubernetes network policy doesn't seem to be able to take precedence over global network policy when policy action is allowed in global policy

## Expected Behavior
I have a global policy that allows egress for all pods.
I have a k8s network policy to only allow UDP port 53 in a namespace `test`.
I'm not sure if this is expected or a bug. But, I would expect the namespace `test` have no egress except egress to UDP port 53.

```yaml
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ubuntu
  name: ubuntu
  namespace: test
spec:
  containers:
  - args:
    - bash
    image: mcr.microsoft.com/aks/fundamental/base-ubuntu:v0.0.11
    imagePullPolicy: Always
    name: ubuntu
    resources: {}
    stdin: true
    stdinOnce: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true
  restartPolicy: Always
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ubuntu
  namespace: test
spec:
  podSelector:
    matchLabels:
      run: ubuntu
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - port: 53
      protocol: UDP
---
apiVersion: crd.projectcalico.org/v1
kind: GlobalNetworkPolicy
metadata:
  name: default-allow
spec:
  order: 2000
  types:
  - Egress
  egress:
    - action: Allow
---
apiVersion: crd.projectcalico.org/v1
kind: GlobalNetworkPolicy
metadata:
  name: block-wireserver
spec:
  order: 0
  types:
  - Egress
  egress:
    - action: Deny
      protocol: TCP
      destination:
        nets:
        - 168.63.129.16/32
        ports: [80]
``` 

## Current Behavior
namespace `test` still have all egress.

## Context
Our infrastructure has two global policies: 1) deny all traffic to Azure wireserver endpoint, and 2) allow all egress.
In the namespace where my application runs, I want k8s networkpolicy to block all egress except DNS
