### ISSUE TITLE
bgpconfiguration leads to invalid iptables rules

### ISSUE THREAD

**Issue by RuriRyan** [projectcalico/calico#5941]
The mere existence of a bgpconfiguration resource leads to an invalid iptables rule.
```
-A cali-cidr-block -m comment --comment "cali:kvkVd9hHTAqesBz-" --destination  --jump DROP
```
And this therefor resulted in errors when trying to apply the whole iptables config block.
```
2022-04-20 10:16:49.917 [WARNING][48778] felix/table.go 1324: Failed to execute ip(6)tables-restore command error=exit status 2 errorOutput="Bad argument `DROP'\nError occurred at line: 19\nTry `iptables-restore -h' or 'iptables-restore --help' for more information.\n"
```

## Expected Behavior
iptables-restore shouldn't fail

## Current Behavior
iptables-restore fails

## Possible Solution
n/a

## Steps to Reproduce (for bugs)
apply:
```
apiVersion: crd.projectcalico.org/v1
kind: BGPConfiguration
metadata:
  name: default
spec:
  asNumber: 63400
  logSeverityScreen: Info
  serviceExternalIPs:
  - cird: 10.9.140.0/24
```
and see the chaos arise.

## Context
It was working fine in 3.18.6.

## Your Environment
* Calico version 3.22.2
* k8s 1.22.8
* Ubuntu 20.04.4 LTS   5.4.0-107-generic
