### ISSUE TITLE
iptables+vxlan with mulit-node setups have broken network-policies when accessing via services

### ISSUE THREAD

**Issue by EugenMayer** [projectcalico/calico#5952]
Having 2 pods and a service in the same network, while deploying a network policy that allows all inter-namespace traffic and blocks only the ingress from other namespaces, should allow podA to contact podB via the server `to-pod-b`

## Expected Behavior
Using `ping to-pod-b` should work.

## Current Behavior
The network traffic is blocked. This can be fixed with changing one of the following (and nothing else).
Using podB podIP the connection does work - so it seems to be related to the service in some way.

The issue can be 'fixed' by one of these:
a) either remove the network policy 
b) or deploy podA and podB on the same node

## Possible Solution
The issue does not happen with EBPF - but this is not a solution. We are bound to `Iptables` here

## Steps to Reproduce (for bugs)
The basic setup is
 - podA and podB deployed in a namespace N1
 - a service called to-podb deployed in N1
 - podA and podB are on different workloads (important!)
 - deployed network policy rule which should mean semantically: Allow all egress, and allow no ingress from non N1 namespaces, but all ow all traffic within the namespace N1
 ```yaml
 spec:
  podSelector: {}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: N1
  policyTypes:
    - Ingress
```

It is also mandatory that you use at `Iptables` (see configuration below), using `EBPF` does make the issue disappear,

## Context
We can no longer use any of our NetworkPolicies at all

## Your Environment

* Calico version: Tried 3.20/3.21.4/.3.22.2
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes 1.22 / 1.23
* Operating System and version: ubuntu 20 / kernel 5.4
* rke2 based workloads (1 server,2 agents). rke2-1.23

My calico / felix configuration. I use the helm-chart variant

```yaml
installation:
  controlPlaneTolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/etcd"
      operator: "Exists"
      effect: "NoExecute"
  enabled: true
  kubernetesProvider: ""
  calicoNetwork:
    bgp: Disabled
    linuxDataplane: Iptables
    hostPorts: true
    ipPools:
      - blockSize: 26
        # TODO: make this configurable, yet matches k3s deployments
        cidr: 10.42.0.0/16
        encapsulation: VXLAN
        natOutgoing: Enabled
        nodeSelector: all()
apiServer:
  enabled: true

certs:
  node:
    key:
    cert:
    commonName:
  typha:
    key:
    cert:
    commonName:
    caBundle:

global:
  systemDefaultRegistry: ""
  clusterCIDRv4: ""
  clusterCIDRv6: ""

felixConfiguration:
  wireguardEnabled: false
  # Config required to fix RKE2 issue #1541
  # @see https://github.com/rancher/rke2/blob/master/docs/known_issues.md#calico-with-vxlan-encapsulation
  featureDetectOverride: "ChecksumOffloadBroken=true"
```
