### ISSUE TITLE
Add overview documentation on Policy and Profiles

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/calico#600]
Need an overview documentation describing the Calico policy model, in particular how Policy and Profiles are applied and the configuration for each.

Tags would be deprecated and not discussed in these docs.

Important to cover:
-  Policy: labels, selectors, rules
-  Default action at end of policies (and when it applies)
-  Profiles

**Comment by ozdanborne** [comment]
You might be interested in this 3-group, 3-layer policy demo I put together: #793

**Comment by caseydavenport** [comment]
I think this doc should also include a recommendation to use _Policy_ for defining rules instead of Profiles, and using Profiles simply as a way of applying labels to collections of Endpoints.

**Comment by gogeof** [comment]
@robbrockbank @caseydavenport 
Today I have tried to set calico profile action to log, but can't find the log message, I'm also looking for the document for help. Is there any document about that?
**here is my profile, but can't find relatived log when I trying to access pod's service:**
```
- apiVersion: v1
  kind: profile
  metadata:
    labels:
      profile: k8s_ns.ws1
    name: k8s_ns.ws1
  spec:
    egress:
    - action: log
      destination:
        net: 10.22.144.0/21
        selector: profile == "k8s_ns.ws1"
      source: {}
    ingress:
    - action: log
      destination: {}
      source:
        net: 10.22.144.0/21
        selector: profile == "k8s_ns.ws1"
```
**here is the environment I am in:**
```
kubernetes version:  v1.8.3
calico/node:v2.5.1
calico/cni:v1.10.0
calico/kube-policy-controller:v0.7.0
calicoctl: calicoctl version v1.3.0, build d2babb6
```

**any help is appreciate!**

**Comment by YuryHrytsuk** [comment]
@caseydavenport it is still not documented anywhere. At least I cannot find it.

I can see that my workloadendpoints use `kns.<namespace>` profile that allows everything. In [whisker logs](https://docs.tigera.io/calico/latest/observability/view-flow-logs) I see that profile seems to have a higher priority then global policy 

I spent a day figuring out why my global network policy "does not work". Then I found that there are some [mysterious profiles](https://docs.tigera.io/calico/latest/reference/resources/profile) created (apparently) by default and allowing all ingress / egress. Furthermore, this profile overrides (?) my global policy (I presume NetworkPolicy as well)

**Whisker policies entry**
``` json
{
  "enforced": [
    {
      "kind": "Profile",
      "name": "kns.cert-manager",
      "namespace": "",
      "tier": "",
      "action": "Allow",
      "policy_index": 0,
      "rule_index": 0,
      "trigger": null
    }
  ],
  "pending": [
    {
      "kind": "EndOfTier",
      "name": "",
      "namespace": "",
      "tier": "default",
      "action": "Deny",
      "policy_index": 0,
      "rule_index": -1,
      "trigger": {
        "kind": "GlobalNetworkPolicy",
        "name": "default-global-deny-network-policy",
        "namespace": "",
        "tier": "default",
        "action": "ActionUnspecified",
        "policy_index": 0,
        "rule_index": 0,
        "trigger": null
      }
    }
  ]
}
```

**default (?) profile for namespace**
```yaml
apiVersion: projectcalico.org/v3
kind: Profile
metadata:
  creationTimestamp: "2025-07-28T11:50:56Z"
  name: kns.cert-manager
  resourceVersion: 1162/
  uid: 30083664-3ab3-4aa0-a0f4-a9a99f6a47a4
spec:
  egress:
  - action: Allow
    destination: {}
    source: {}
  ingress:
  - action: Allow
    destination: {}
    source: {}
  labelsToApply:
    pcns.kubernetes.io/metadata.name: cert-manager
    pcns.name: cert-manager
    pcns.projectcalico.org/name: cert-manager
```

**Global policy**
```yaml
# Source: https://docs.tigera.io/calico-enterprise/latest/network-policy/default-deny#best-practice-2-keep-the-scope-to-non-system-pods
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: default-global-deny-network-policy
spec:
  # on local deployment, calico is installed in the `calico-system` namespace
  # and the operator is in the `tigera-operator` namespace
  namespaceSelector: kubernetes.io/metadata.name not in {"calico-system", "kube-public", "kube-system", "tigera-operator", "traefik"}
  types:
  - Ingress
  - Egress
  egress:
   # allow all namespaces to communicate to DNS pods
  - action: Allow
    protocol: UDP
    destination:
      selector: 'k8s-app == "kube-dns"'
      ports:
      - 53
  - action: Allow
    protocol: TCP
    destination:
      selector: 'k8s-app == "kube-dns"'
      ports:
      - 53
```
