### ISSUE TITLE
Hard-coded tolerations allow non-daemonset resources to be scheduled on a cordoned node.

### ISSUE THREAD

**Issue by technotaff-nbs** [projectcalico/calico#6136]
The following tolerations exist on several non-daemonset (deployments, replicaset) k8s manifests:

```
spec:
  tolerations:
    - effect: NoExecute
      operator: Exists
    - effect: NoSchedule
      operator: Exists
```

This means when a NoSchedule/NoExecute taint is set on a node (e.g. during cordon) these resources can still be scheduled.

This is standard-practice for daemonsets which are usually ignored during subsequent draining processes.

By setting the above tolerations, pods can be rescheduled on cordoned nodes, preventing node draining.

The setting is hard-coded into the helm chart here:

https://github.com/projectcalico/calico/blob/6afaed515b51ad20a7e142be26acbba30c5ea671/calico/_includes/charts/tigera-operator/templates/tigera-operator/02-tigera-operator.yaml#L21

Also, operator-created non-DaemonSet resources:

calico-system/calico-typha
calico-system/calico-kube-controllers

Please allow the tolerations to be overridden in both helm chart and operator-deployed resources.

## Expected Behavior
Cordon and drain processes, e.g. EKS rolling-update, process should proceed normally with calico-operator deployed.

## Current Behavior
Cordon and drain processes, e.g. EKS rolling-update processes often hang due to non-DS calico pods being scheduled on a cordoned nodes.

## Possible Solution
Allow user-control of pod tolerations.
or
Do not set tolerations on non-DaemonSet resources.

## Steps to Reproduce (for bugs)
1. Deploy EKS
2. Deploy calico-operator.
3. Perform rolling-update of cluster nodes without "force" flag.

## Context
We are unable to upgrade node groups unless we use "forced" mode which ignores Pod Disruption Budgets etc. and has a knock-on affect on our application workloads.

## Your Environment
EKS 1.21
Calico-Operator v1.25.7

**Comment by caseydavenport** [comment]
Yep, agree we need to make this configurable. 

@lmm is already looking at some related work in the operator, so this should go on his radar :eyes:

**Comment by tmjd** [comment]
>Do not set tolerations on non-DaemonSet resources.

I think you are referring to typha here. I don't think we can do that for initial creation because without those tolerations typha would never be scheduled because calico-node wouldn't ever be able to successfully run (and the nodes would never become Ready)

@caseydavenport would we want to have the operator only add those tolerations when all nodes have NoExecute or NoSchedule (or at least until some number are Read) and when there are nodes with Execute and Schedule then remove the tolerations?
Or I guess since this is EKS it is probably using AWS CNI, could we not add the toleration when using a non-Calico CNI?

**Comment by technotaff-nbs** [comment]
Okay, I see why these tolerations exist. 

[Default tolerations](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/#taint-based-evictions) are added to pods which I *think* would allow initial execution:

```
   tolerations:
   - effect: NoExecute
     key: node.kubernetes.io/not-ready
     operator: Exists
     tolerationSeconds: 300
   - effect: NoExecute
     key: node.kubernetes.io/unreachable
     operator: Exists
     tolerationSeconds: 300
```

I'm not sure what kube-scheduler does when all nodes are NotReady, I _think_ that it will schedule on a node and then evict/reschedule after 300 seconds. It might be just as well to duplicate those tolerations but _without_ the tolerationSeconds directives (like the default DaemonSet tolerations).

The problem is these tolerations means you lose **all** control over pod scheduling via node taints:

```
spec:
  tolerations:
    - effect: NoExecute
      operator: Exists
    - effect: NoSchedule
      operator: Exists
```

**Comment by caseydavenport** [comment]
> Or I guess since this is EKS it is probably using AWS CNI, could we not add the toleration when using a non-Calico CNI?

I think this is probably a safe and useful increment, but we'd still need to solve for the Calico networking case as well. 

Was imagining we'd keep our defaults the same and simply expose an option for users to set these to something else should they need to use taints to control scheduling, but that's not really a great solution and just pushes the problem to users (we want to make this configurable anyway, but we should have default settings that "just work").

I guess the trick will be to tolerate just enough that we get scheduled, and no more, which I think just means:

```
    - effect: NoSchedule
      key: node.kubernetes.io/not-ready
```

**Comment by lmm** [comment]
Hey @technotaff-nbs 

We've put up an outline of proposed changes to operator component configuration. Among other things, this will include allowing custom tolerations. Please take a look. We'd appreciate your input on the proposed changes: https://github.com/tigera/operator/issues/1990

**Comment by caseydavenport** [comment]
xref: https://github.com/tigera/operator/issues/2020

**Comment by caseydavenport** [comment]
https://github.com/tigera/operator/pull/2063 introduced the ability to override the tolerations set on kube-controllers as well as typha.

Default tolerations for the operator can also beconfigured in helm using values.yaml: https://github.com/projectcalico/calico/blob/cbb1eaf9f7a6c55e6f82f1e954c748e8886163d2/charts/tigera-operator/values.yaml#L23-L29

I'm still considering a change to our default tolerations to be slightly less tolerant, but I think we can still call this one done for now.

**Comment by jessehu** [comment]
Thanks! Since https://github.com/tigera/operator/pull/2101 is not merged, I used the following config in values.yaml for tigera-operator helm chart to make it work.
```
installation:
  # Specify tolerations which are then globally applied to all resources created by the operator.
  # So the pods of Calico components can be scheduled to other Nodes when its Node becomes unreachable.
  controlPlaneTolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    # tolerationSeconds must be specified explicitly
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
```
