### ISSUE TITLE
Cannot upgrade calico from 3.4 to 3.23

### ISSUE THREAD

**Issue by cy-zheng** [projectcalico/calico#6144]
I'm following the guide https://projectcalico.docs.tigera.io/maintenance/kubernetes-upgrade#upgrading-an-installation-that-uses-an-etcd-datastore to upgrade calico from 3.4 to 3.23. The `calico-kube-controllers` becomes `Ready`, but the `calico-node` couldn't reach the "Ready" state.

```
calico-kube-controllers-86bc6c487d-ppgnm   1/1     Running   0          2m57s
calico-node-cbz6n                          0/1     Running   0          3m4s
```

## Expected Behavior

The upgrade process should be smoothly.

## Current Behavior

The `calico-node` stuck in restarting Felix. Here are some logs of `calico-node`:
```
2022-05-24 14:00:45.514 [WARNING][2155] felix/l3_route_resolver.go 632: Unable to create route for IP; the node it belongs to was not recorded in IPAM IP=192.168.6.243
2022-05-24 14:00:45.514 [WARNING][2155] felix/l3_route_resolver.go 632: Unable to create route for IP; the node it belongs to was not recorded in IPAM IP=192.168.6.244
2022-05-24 14:00:45.514 [WARNING][2155] felix/l3_route_resolver.go 632: Unable to create route for IP; the node it belongs to was not recorded in IPAM IP=192.168.6.246
2022-05-24 14:00:45.514 [WARNING][2155] felix/l3_route_resolver.go 632: Unable to create route for IP; the node it belongs to was not recorded in IPAM IP=192.168.6.247
2022-05-24 14:00:45.514 [WARNING][2155] felix/l3_route_resolver.go 632: Unable to create route for IP; the node it belongs to was not recorded in IPAM IP=192.168.70.128
2022-05-24 14:00:45.514 [WARNING][2155] felix/l3_route_resolver.go 632: Unable to create route for IP; the node it belongs to was not recorded in IPAM IP=192.168.70.129
2022-05-24 14:00:45.514 [WARNING][2155] felix/l3_route_resolver.go 632: Unable to create route for IP; the node it belongs to was not recorded in IPAM IP=192.168.70.147
2022-05-24 14:00:45.514 [WARNING][2155] felix/l3_route_resolver.go 632: Unable to create route for IP; the node it belongs to was not recorded in IPAM IP=192.168.70.177
2022-05-24 14:00:45.514 [WARNING][2155] felix/l3_route_resolver.go 632: Unable to create route for IP; the node it belongs to was not recorded in IPAM IP=192.168.70.186
2022-05-24 14:00:45.515 [WARNING][2155] felix/l3_route_resolver.go 632: Unable to create route for IP; the node it belongs to was not recorded in IPAM IP=192.168.70.187
2022-05-24 14:00:45.515 [WARNING][2155] felix/l3_route_resolver.go 632: Unable to create route for IP; the node it belongs to was not recorded in IPAM IP=192.168.90.192
2022-05-24 14:00:45.515 [WARNING][2155] felix/l3_route_resolver.go 935: Some nodes share IP address, route calculation may choose wrong node. cidr=::/128 nodes=[]string{"lasvai-staging-capos-k8s-master01", "lasvai-staging-capos-k8s-master02", "lasvai-staging-capos-k8s-master03", "vai-computing-con-027", "vai-computing-con-028", "vai-computing-con-029", "vai-computing-con-030", "vai-computing-con-031", "vai-computing-con-038", "vai-computing-con-039", "vai-computing-con-040"}
2022-05-24 14:00:45.515 [WARNING][2155] felix/l3_route_resolver.go 935: Some nodes share IP address, route calculation may choose wrong node. cidr=::/128 nodes=[]string{"lasvai-staging-capos-k8s-master01", "lasvai-staging-capos-k8s-master02", "lasvai-staging-capos-k8s-master03", "vai-computing-con-027", "vai-computing-con-028", "vai-computing-con-029", "vai-computing-con-030", "vai-computing-con-031", "vai-computing-con-038", "vai-computing-con-039", "vai-computing-con-040", "vai-computing-con-041"}
2022-05-24 14:00:45.515 [WARNING][2155] felix/l3_route_resolver.go 935: Some nodes share IP address, route calculation may choose wrong node. cidr=::/128 nodes=[]string{"lasvai-staging-capos-k8s-master01", "lasvai-staging-capos-k8s-master02", "lasvai-staging-capos-k8s-master03", "vai-computing-con-027", "vai-computing-con-028", "vai-computing-con-029", "vai-computing-con-030", "vai-computing-con-031", "vai-computing-con-038", "vai-computing-con-039", "vai-computing-con-040", "vai-computing-con-041", "vai-computing-con-042"}
2022-05-24 14:00:45.515 [WARNING][2155] felix/l3_route_resolver.go 935: Some nodes share IP address, route calculation may choose wrong node. cidr=::/128 nodes=[]string{"lasvai-staging-capos-k8s-master01", "lasvai-staging-capos-k8s-master02", "lasvai-staging-capos-k8s-master03", "vai-computing-con-027", "vai-computing-con-028", "vai-computing-con-029", "vai-computing-con-030", "vai-computing-con-031", "vai-computing-con-038", "vai-computing-con-039", "vai-computing-con-040", "vai-computing-con-041", "vai-computing-con-042", "vai-computing-con-043"}
2022-05-24 14:00:45.515 [WARNING][2155] felix/l3_route_resolver.go 935: Some nodes share IP address, route calculation may choose wrong node. cidr=::/128 nodes=[]string{"lasvai-staging-capos-k8s-master01", "lasvai-staging-capos-k8s-master02", "lasvai-staging-capos-k8s-master03", "vai-computing-con-027", "vai-computing-con-028", "vai-computing-con-029", "vai-computing-con-030", "vai-computing-con-031", "vai-computing-con-038", "vai-computing-con-039", "vai-computing-con-040", "vai-computing-con-041", "vai-computing-con-042", "vai-computing-con-043", "vai-computing-con-044"}
2022-05-24 14:00:45.534 [WARNING][2155] felix/daemon.go 1209: IPIP and/or VXLAN encapsulation changed, need to restart.
2022-05-24 14:00:45.534 [WARNING][2155] felix/daemon.go 715: Felix is shutting down reason="encapsulation changed"
```

## Your Environment

* Calico version: v3.4 -> v3.23
* Orchestrator version (e.g. kubernetes, mesos, rkt): k8s v1.19.9
* Operating System and version: Linux vai-computing-con-040 4.15.0-133-generic #137~16.04.1-Ubuntu SMP Fri Jan 15 02:55:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by cy-zheng** [comment]
My calico.yaml:
```
---
# Source: calico/templates/calico-config.yaml
# This ConfigMap is used to configure a self-hosted Calico installation.
kind: ConfigMap
apiVersion: v1
metadata:
  name: calico-config
  namespace: kube-system
data:
  # Configure this with the location of your etcd cluster.
  etcd_endpoints: "https://10.92.9.224:2379,https://10.92.11.58:2379,https://10.92.6.57:2379"
  # If you're using TLS enabled etcd uncomment the following.
  # You must also populate the Secret below with these files.
  etcd_ca: "/var/lib/kubernetes/ca.pem"
  etcd_cert: "/var/lib/kubernetes/kubernetes.pem"
  # chmod 644 /var/lib/kubernetes/kubernetes-key.pem
  etcd_key: "/var/lib/kubernetes/kubernetes-key.pem"
  # Typha is disabled.
  typha_service_name: "none"
  # Configure the backend to use.
  calico_backend: "bird"

  # Configure the MTU to use for workload interfaces and tunnels.
  # By default, MTU is auto-detected, and explicitly setting this field should not be required.
  # You can override auto-detection by providing a non-zero value.
  veth_mtu: "0"

  ipv4_range: "192.168.0.0/16"
  ipip_env: "always"

  # The CNI network configuration to install on each node. The special
  # values in this config will be automatically populated.
  cni_network_config: |-
    {
      "name": "k8s-pod-network",
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "calico",
          "log_level": "info",
          "log_file_path": "/var/log/calico/cni/cni.log",
          "etcd_endpoints": "__ETCD_ENDPOINTS__",
          "etcd_key_file": "__ETCD_KEY_FILE__",
          "etcd_cert_file": "__ETCD_CERT_FILE__",
          "etcd_ca_cert_file": "__ETCD_CA_CERT_FILE__",
          "mtu": __CNI_MTU__,
          "ipam": {
              "type": "calico-ipam"
          },
          "policy": {
              "type": "k8s"
          },
          "kubernetes": {
              "kubeconfig": "__KUBECONFIG_FILEPATH__"
          }
        },
        {
          "type": "portmap",
          "snat": true,
          "capabilities": {"portMappings": true}
        },
        {
          "type": "bandwidth",
          "capabilities": {"bandwidth": true}
        }
      ]
    }

---
# Source: calico/templates/calico-kube-controllers-rbac.yaml

# Include a clusterrole for the kube-controllers component,
# and bind it to the calico-kube-controllers serviceaccount.
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: calico-kube-controllers
rules:
  # Pods are monitored for changing labels.
  # The node controller monitors Kubernetes nodes.
  # Namespace and serviceaccount labels are used for policy.
  - apiGroups: [""]
    resources:
      - pods
      - nodes
      - namespaces
      - serviceaccounts
    verbs:
      - watch
      - list
      - get
  # Watch for changes to Kubernetes NetworkPolicies.
  - apiGroups: ["networking.k8s.io"]
    resources:
      - networkpolicies
    verbs:
      - watch
      - list
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: calico-kube-controllers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: calico-kube-controllers
subjects:
  - kind: ServiceAccount
    name: calico-kube-controllers
    namespace: kube-system
---

---
# Source: calico/templates/calico-node-rbac.yaml
# Include a clusterrole for the calico-node DaemonSet,
# and bind it to the calico-node serviceaccount.
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: calico-node
rules:
  # The CNI plugin needs to get pods, nodes, and namespaces.
  - apiGroups: [""]
    resources:
      - pods
      - nodes
      - namespaces
    verbs:
      - get
  # EndpointSlices are used for Service-based network policy rule
  # enforcement.
  - apiGroups: ["discovery.k8s.io"]
    resources:
      - endpointslices
    verbs:
      - watch
      - list
  - apiGroups: [""]
    resources:
      - endpoints
      - services
    verbs:
      # Used to discover service IPs for advertisement.
      - watch
      - list
  # Pod CIDR auto-detection on kubeadm needs access to config maps.
  - apiGroups: [""]
    resources:
      - configmaps
    verbs:
      - get
  - apiGroups: [""]
    resources:
      - nodes/status
    verbs:
      # Needed for clearing NodeNetworkUnavailable flag.
      - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: calico-node
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: calico-node
subjects:
  - kind: ServiceAccount
    name: calico-node
    namespace: kube-system

---
# Source: calico/templates/calico-node.yaml
# This manifest installs the calico-node container, as well
# as the CNI plugins and network config on
# each master and worker node in a Kubernetes cluster.
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: calico-node
  namespace: kube-system
  labels:
    k8s-app: calico-node
spec:
  selector:
    matchLabels:
      k8s-app: calico-node
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        k8s-app: calico-node
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      hostNetwork: true
      tolerations:
        # Make sure calico-node gets scheduled on all nodes.
        - effect: NoSchedule
          operator: Exists
        # Mark the pod as a critical add-on for rescheduling.
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoExecute
          operator: Exists
      serviceAccountName: calico-node
      # Minimize downtime during a rolling upgrade or deletion; tell Kubernetes to do a "force
      # deletion": https://kubernetes.io/docs/concepts/workloads/pods/pod/#termination-of-pods.
      terminationGracePeriodSeconds: 0
      priorityClassName: system-node-critical
      initContainers:
        # This container installs the CNI binaries
        # and CNI network config file on each node.
        - name: install-cni
          image: cubox.prod.hulu.com/proxy/calico/cni:v3.23.1
          command: ["/opt/cni/bin/install"]
          envFrom:
            - configMapRef:
                # Allow KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT to be overridden for eBPF mode.
                name: kubernetes-services-endpoint
                optional: true
          env:
            # Name of the CNI config file to create.
            - name: CNI_CONF_NAME
              value: "10-calico.conflist"
            # The CNI network config to install on each node.
            - name: CNI_NETWORK_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: cni_network_config
            # The location of the etcd cluster.
            - name: ETCD_ENDPOINTS
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_endpoints
            # CNI MTU Config variable
            - name: CNI_MTU
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: veth_mtu
            # Prevents the container from sleeping forever.
            - name: SLEEP
              value: "false"
          volumeMounts:
            - mountPath: /host/opt/cni/bin
              name: cni-bin-dir
            - mountPath: /host/etc/cni/net.d
              name: cni-net-dir
            - mountPath: /var/lib/kubernetes
              name: var-lib-k8s
              readOnly: true
            #- mountPath: /etc/calico/kube/kubeconfig
            #  name: etc-kubeconfig
            #  readOnly: true
          securityContext:
            privileged: true
      containers:
        # Runs calico-node container on each Kubernetes node. This
        # container programs network policy and routes on each
        # host.
        - name: calico-node
          image: docker.io/calico/node:v3.23.1
          envFrom:
            - configMapRef:
                # Allow KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT to be overridden for eBPF mode.
                name: kubernetes-services-endpoint
                optional: true
          env:
            # The location of the etcd cluster.
            - name: ETCD_ENDPOINTS
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_endpoints
            # Location of the CA certificate for etcd.
            - name: ETCD_CA_CERT_FILE
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_ca
            # Location of the client key for etcd.
            - name: ETCD_KEY_FILE
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_key
            # Location of the client certificate for etcd.
            - name: ETCD_CERT_FILE
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_cert
            # Set noderef for node controller.
            - name: CALICO_K8S_NODE_REF
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            # Choose the backend to use.
            - name: CALICO_NETWORKING_BACKEND
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: calico_backend
            # Cluster type to identify the deployment type
            - name: CLUSTER_TYPE
              value: "k8s,bgp"
            # Auto-detect the BGP IP address.
            - name: IP
              value: ""
            # Enable IPIP
            - name: CALICO_IPV4POOL_IPIP
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: ipip_env
            # Enable or Disable VXLAN on the default IP pool.
            - name: CALICO_IPV4POOL_VXLAN
              value: "Never"
            # Enable or Disable VXLAN on the default IPv6 IP pool.
            - name: CALICO_IPV6POOL_VXLAN
              value: "Never"
            # Set MTU for tunnel device used if ipip is enabled
            - name: FELIX_IPINIPMTU
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: veth_mtu
            # Set MTU for the VXLAN tunnel device.
            - name: FELIX_VXLANMTU
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: veth_mtu
            # Set MTU for the Wireguard tunnel device.
            - name: FELIX_WIREGUARDMTU
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: veth_mtu
            # The default IPv4 pool to create on startup if none exists. Pod IPs will be
            # chosen from this range. Changing this value after installation will have
            # no effect. This should fall within `--cluster-cidr`.
            - name: CALICO_IPV4POOL_CIDR
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: ipv4_range
            # Disable file logging so `kubectl logs` works.
            - name: CALICO_DISABLE_FILE_LOGGING
              value: "true"
            # Set Felix endpoint to host default action to ACCEPT.
            - name: FELIX_DEFAULTENDPOINTTOHOSTACTION
              value: "ACCEPT"
            # Disable IPv6 on Kubernetes.
            - name: FELIX_IPV6SUPPORT
              value: "false"
            - name: FELIX_HEALTHENABLED
              value: "true"
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: 250m
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/calico-node
                  - -shutdown
          livenessProbe:
            exec:
              command:
                - /bin/calico-node
                - -felix-live
                - -bird-live
            periodSeconds: 10
            initialDelaySeconds: 10
            failureThreshold: 6
            timeoutSeconds: 10
          readinessProbe:
            exec:
              command:
                - /bin/calico-node
                - -felix-ready
                - -bird-ready
            periodSeconds: 10
            timeoutSeconds: 10
          volumeMounts:
            # For maintaining CNI plugin API credentials.
            - mountPath: /host/etc/cni/net.d
              name: cni-net-dir
              readOnly: false
            - mountPath: /lib/modules
              name: lib-modules
              readOnly: true
            - mountPath: /run/xtables.lock
              name: xtables-lock
              readOnly: false
            - mountPath: /var/run/calico
              name: var-run-calico
              readOnly: false
            - mountPath: /var/lib/calico
              name: var-lib-calico
              readOnly: false
            - mountPath: /var/lib/kubernetes
              name: var-lib-k8s
            #- mountPath: /etc/calico/kube/kubeconfig
            #  name: etc-kubeconfig
            #  readOnly: true
            - name: policysync
              mountPath: /var/run/nodeagent
            # For eBPF mode, we need to be able to mount the BPF filesystem at /sys/fs/bpf so we mount in the
            # parent directory.
            - name: sysfs
              mountPath: /sys/fs/
              # Bidirectional means that, if we mount the BPF filesystem at /sys/fs/bpf it will propagate to the host.
              # If the host is known to mount that filesystem already then Bidirectional can be omitted.
              mountPropagation: Bidirectional
            - name: cni-log-dir
              mountPath: /var/log/calico/cni
              readOnly: true
      volumes:
        # Used by calico-node.
        - name: lib-modules
          hostPath:
            path: /lib/modules
        - name: var-run-calico
          hostPath:
            path: /var/run/calico
        - name: var-lib-calico
          hostPath:
            path: /var/lib/calico
        - name: xtables-lock
          hostPath:
            path: /run/xtables.lock
            type: FileOrCreate
        - name: sysfs
          hostPath:
            path: /sys/fs/
            type: DirectoryOrCreate
        # Used to install CNI.
        - name: cni-bin-dir
          hostPath:
            path: /opt/cni/bin
        - name: cni-net-dir
          hostPath:
            path: /etc/cni/net.d
        # Used to access CNI logs.
        - name: cni-log-dir
          hostPath:
            path: /var/log/calico/cni
        # Mount in the etcd TLS secrets with mode 400.
        - name: var-lib-k8s
          hostPath:
            path: /var/lib/kubernetes
        #- name: etc-kubeconfig
        #  hostPath:
        #    path: /etc/calico/kube/kubeconfig
        # Used to create per-pod Unix Domain Sockets
        - name: policysync
          hostPath:
            type: DirectoryOrCreate
            path: /var/run/nodeagent
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: calico-node
  namespace: kube-system

---
# Source: calico/templates/calico-kube-controllers.yaml
# See https://github.com/projectcalico/kube-controllers
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calico-kube-controllers
  namespace: kube-system
  labels:
    k8s-app: calico-kube-controllers
spec:
  # The controllers can only have a single active instance.
  replicas: 1
  selector:
    matchLabels:
      k8s-app: calico-kube-controllers
  strategy:
    type: Recreate
  template:
    metadata:
      name: calico-kube-controllers
      namespace: kube-system
      labels:
        k8s-app: calico-kube-controllers
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
        # Mark the pod as a critical add-on for rescheduling.
        - key: CriticalAddonsOnly
          operator: Exists
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      serviceAccountName: calico-kube-controllers
      priorityClassName: system-cluster-critical
      # The controllers must run in the host network namespace so that
      # it isn't governed by policy that would prevent it from working.
      hostNetwork: true
      containers:
        - name: calico-kube-controllers
          image: docker.io/calico/kube-controllers:v3.23.1
          env:
            # The location of the etcd cluster.
            - name: ETCD_ENDPOINTS
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_endpoints
            # Location of the CA certificate for etcd.
            - name: ETCD_CA_CERT_FILE
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_ca
            # Location of the client key for etcd.
            - name: ETCD_KEY_FILE
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_key
            # Location of the client certificate for etcd.
            - name: ETCD_CERT_FILE
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_cert
            # Choose which controllers to run.
            - name: ENABLED_CONTROLLERS
              value: policy,namespace,serviceaccount,workloadendpoint,node
          volumeMounts:
            # Mount in the etcd TLS secrets.
            - mountPath: /var/lib/kubernetes
              name: var-lib-k8s
          livenessProbe:
            exec:
              command:
                - /usr/bin/check-status
                - -l
            periodSeconds: 10
            initialDelaySeconds: 10
            failureThreshold: 6
            timeoutSeconds: 10
          readinessProbe:
            exec:
              command:
                - /usr/bin/check-status
                - -r
            periodSeconds: 10
      volumes:
        # Mount in the etcd TLS secrets with mode 400.
        - name: var-lib-k8s
          hostPath:
            path: /var/lib/kubernetes

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: calico-kube-controllers
  namespace: kube-system

---

# This manifest creates a Pod Disruption Budget for Controller to allow K8s Cluster Autoscaler to evict

apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: calico-kube-controllers
  namespace: kube-system
  labels:
    k8s-app: calico-kube-controllers
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      k8s-app: calico-kube-controllers
```
