### ISSUE TITLE
In BGP mode, all Typha instances being unavailable results in eventual network issues

### ISSUE THREAD

**Issue by iamejboy** [projectcalico/calico#6167]
## Expected Behavior
There should be no network outage when typha down. Control plane down, should not affect dataplane.

## Current Behavior
When all typha  pod down (could be down for many reasons), all calico-node becomes not ready (0/1). It fails both readiness probe and liveness probe. Liveness probe reach contract ~3 mins, then restart the container. Network outage starts to happen.
<img width="1167" alt="Screen Shot 2022-06-01 at 17 24 01" src="https://user-images.githubusercontent.com/25651955/171365727-3949a7cb-8f5f-4a84-9980-0d7b7fd75a81.png">
<img width="764" alt="Screen Shot 2022-06-01 at 17 18 25" src="https://user-images.githubusercontent.com/25651955/171365781-28c22adb-d113-48c0-949c-c3b2b9cd7b89.png">
<img width="1427" alt="Screen Shot 2022-06-01 at 17 13 58" src="https://user-images.githubusercontent.com/25651955/171366698-c03be6f0-3867-4002-a156-a5ad50925a27.png">

```
        livenessProbe:
          exec:
            command:
            - /bin/calico-node
            - -felix-live
            - -bird-live
          failureThreshold: 6
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: calico-node
        readinessProbe:
          exec:
            command:
            - /bin/calico-node
            - -felix-ready
            - -bird-ready
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
```

`0s          Warning   Unhealthy           pod/calico-node-n9qd9                Liveness probe failed: calico/node is not ready: bird/confd is not live: Service confd is not running. Output << down: /etc/service/enabled/confd: 1s, normally up, want up >>`

Calico-node logs before restart
`2022-06-01 08:18:51.870 [INFO][27621] client.go 145: Connecting to Typha. addr="100.102.249.91:5473"
2022-06-01 08:18:51.870 [INFO][27621] sync_client.go 71:  requiringTLS=false
2022-06-01 08:18:51.870 [INFO][27621] sync_client.go 200: Starting Typha client
2022-06-01 08:18:51.870 [INFO][27621] sync_client.go 71:  requiringTLS=false
2022-06-01 08:18:51.870 [INFO][27621] sync_client.go 251: Connecting to Typha. address="100.102.249.91:5473" connID=0x0 type="bgp"
2022-06-01 08:18:52.930 [FATAL][27621] client.go 165: Failed to connect to Typha error=dial tcp 100.102.249.91:5473: connect: connection refused
2022-06-01 08:18:52.946 [INFO][27635] config.go 103: Skipping confd config file.
2022-06-01 08:18:52.946 [INFO][27635] config.go 181: Found FELIX_TYPHAK8SSERVICENAME=calico-typha
2022-06-01 08:18:52.946 [INFO][27635] run.go 17: Starting calico-confd
2022-06-01 08:18:52.947 [INFO][27635] k8s.go 228: Using Calico IPAM
2022-06-01 08:18:52.956 [INFO][27635] client.go 246: Found Typha ClusterIP. clusterIP="100.102.249.91"
2022-06-01 08:18:52.956 [INFO][27635] client.go 253: Found Typha service port. port=v1.ServicePort{Name:"calico-typha", Protocol:"TCP", Port:5473, TargetPort:intstr.IntOrString{Type:1, IntVal:0, StrVal:"calico-typha"}, NodePort:0}
`

Calico-node started to crashloopback
`2022-06-01 08:19:53.156 [INFO][1005] client.go 145: Connecting to Typha. addr="100.102.249.91:5473"
2022-06-01 08:19:53.156 [INFO][1005] sync_client.go 71:  requiringTLS=false
2022-06-01 08:19:53.156 [INFO][1005] sync_client.go 200: Starting Typha client
2022-06-01 08:19:53.156 [INFO][1005] sync_client.go 71:  requiringTLS=false
2022-06-01 08:19:53.156 [INFO][1005] sync_client.go 251: Connecting to Typha. address="100.102.249.91:5473" connID=0x0 type="bgp"
2022-06-01 08:19:53.157 [FATAL][1005] client.go 165: Failed to connect to Typha error=dial tcp 100.102.249.91:5473: connect: connection refused
bird: Unable to open configuration file /etc/calico/confd/config/bird.cfg: No such file or directory
bird: Unable to open configuration file /etc/calico/confd/config/bird6.cfg: No such file or directory`

Slack link -> https://calicousers.slack.com/archives/C0BCA117T/p1653613920575269

## Possible Solution
Not live should not happen when typha down OR even container restart after liveliness contract, it  should not break traffic (means config should be preserve)

## Steps to Reproduce (for bugs)
1. Cluster setup 
-master/worker/route-reflector node)
-calico typha
-calico-kube-controllers
2. Deliberately down typha (many ways e.g. make kube-apiserver down, make typha down, scale typha to 0)

## Context
This issue can cause big outage in production.

## Your Environment
* Calico version - v3.12
* Orchestrator version - K8s v1.20.12
* Operating System and version: Fedora CoreOS 34.20210529.3.0 (5.16.16-200.fc35.x86_64) & CoreOS 2135.6.0 (4.19.56-coreos-r1)
