### ISSUE TITLE
Cannot reach pods from different node

### ISSUE THREAD

**Issue by debendraoli** [projectcalico/calico#6193]
I recently installed calico operator and everything looks good apart from node-to-node  connection.

## Expected Behavior

Pods should be reachable from every node.

## Current Behavior

I can reach pods within the current node but not to other pods of another node and vise-versa.

## Context

There are two nodes and outputs are same for each the nodes and environments are same on both nodes. 

Custom resources.

**custom-resources.yaml**
```
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  calicoNetwork:
    # Note: The ipPools section cannot be modified post-install.
    ipPools:
    - blockSize: 26
      cidr: 10.48.0.0/21
      encapsulation: IPIP
      natOutgoing: Enabled
      nodeSelector: all()
    - blockSize: 122
      cidr: 2001::/64
      encapsulation: None
      natOutgoing: Enabled
      nodeSelector: all()
---
apiVersion: operator.tigera.io/v1
kind: APIServer
metadata:
  name: default
spec: {}
```
**kubeadm-config.yaml**
```
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 192.168.1.3
  bindPort: 6443
nodeRegistration:
  name: dev
  criSocket: unix:///var/run/crio/crio.sock
---
apiVersion: kubeadm.k8s.io/v1beta3
clusterName: deben
kind: ClusterConfiguration
networking:
  dnsDomain: cluster.local
  podSubnet: 10.48.0.0/21,2001::/64
  serviceSubnet: 10.96.0.0/24,2001::/120
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
serverTLSBootstrap: true
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: ipvs
```

`sudo calicoctl node status`

```
Calico process is running.

IPv4 BGP status
+--------------+-------------------+-------+----------+-------------+
| PEER ADDRESS |     PEER TYPE     | STATE |  SINCE   |    INFO     |
+--------------+-------------------+-------+----------+-------------+
| 192.168.1.4  | node-to-node mesh | up    | 12:07:37 | Established |
| 192.168.1.1  | global            | up    | 14:33:50 | Established |
+--------------+-------------------+-------+----------+-------------+

IPv6 BGP status
+-----------------------------------------+-------------------+-------+----------+-------------+
|              PEER ADDRESS               |     PEER TYPE     | STATE |  SINCE   |    INFO     |
+-----------------------------------------+-------------------+-------+----------+-------------+
| REDACTED | node-to-node mesh | up    | 12:07:38 | Established |
+-----------------------------------------+-------------------+-------+----------+-------------+
```

`sudo calicoctl node checksystem`

Every options are `OK` status from both nodes.

`sudo calicoctl node diags`

```
Collecting diagnostics
Using temp dir: /tmp/calico909286275
Failed to run command: hostname
Error:
Dumping netstat
Failed to run command: netstat -a -n
Error:
Dumping routes (IPv4)
Dumping routes (IPv6)
Dumping interface info (IPv4)
Dumping interface info (IPv6)
Dumping iptables (IPv4)
Dumping iptables (IPv6)
Dumping ipsets
Failed to run command: ipset list
Error:
Dumping ipsets (container)
Failed to run command: docker run --rm --privileged --net=host calico/node ipset list
Error: ipset v7.1: Kernel and userspace incompatible: settype hash:net with revision 7 not supported by userspace.

Copying journal for calico-node.service
Dumping felix stats
Failed to run command: pkill -SIGUSR1 felix
Error:
Copying Calico logs
Error creating log directory: mkdir /tmp/calico909286275/diagnostics/logs: file exists
```

[diags-20220606_203627.tar.gz](https://drive.google.com/file/d/1F43iPOofsdW4g1OCRmlyQc9UD9L9mUM3/view?usp=sharing)

## Your Environment

* Calico version: v3.23.1
*  Calico Cluster Type:  typha,kdd,k8s,operator,bgp,kubeadm
* Kubernetes: v1.24.1
* Operating System and version:  Archlinux 5.18.1-arch1-1
* Network manager: systemd-networkd
