### ISSUE TITLE
Uninstalling tigera-operator leaves all resources in calico-system namespace

### ISSUE THREAD

**Issue by aquam8** [projectcalico/calico#6210]
Installed Tigera-operator 3.23.1 through Helm, all was fine. I wanted to uninstall it.
Ran: `helm uninstall -n tigera-operator projectcalico` 
It deleted the operator, but left all resources (running pods etc..) in the calico-system namespace.

## Expected Behavior

I was expecting to have all resources deployed by tigera-operator deleted.

Resources created by the operator should be deleted. How are we supposed to clean up all resources otherwise?

## Current Behavior

All resources in calico-system are left, including DS calico-node, Deployment calico-kube-controller etc..
I was not expected to have the calico-system resources after installing the operator through Helm.

How are we supposed to uninstall calico afterwards?

## Steps to Reproduce (for bugs)

0. kubectl create namespace tigera-operator
1. helm repo add projectcalico https://projectcalico.docs.tigera.io/charts --version v3.23.1 --namespace tigera-operator -f values.yaml
This is my values.yaml:
```
installation:
  enabled: true
  kubernetesProvider: "EKS"
  componentResources:
    - componentName: KubeControllers
      resourceRequirements:
        requests:
          memory: "64Mi"
          cpu: "40m"
        limits:
          memory: "96Mi"
          # no cpu limits
    - componentName: Node
      resourceRequirements:
        requests:
          memory: "64Mi"
          cpu: "40m"
        limits:
          memory: "128Mi"
          # no cpu limits
    - componentName: Typha
      resourceRequirements:
        requests:
          memory: "64Mi"
          cpu: "40m"
        limits:
          memory: "96Mi"
          # no cpu limits
  controlPlaneTolerations:
    - effect: NoSchedule
      operator: Exists
      key: "dedicated"

apiServer:
  enabled: false
```
2. helm uninstall -n tigera-operator projectcalico
3. You should see the remaining resources in the calico-system4. 

## Your Environment

* Calico version: v3.23.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes/EKS 1.21
