### ISSUE TITLE
v3.23.1 Felixconfiguration: workloadSourceSpoofing validator expects "Any)" instead of "Any"

### ISSUE THREAD

**Issue by anaperic** [projectcalico/calico#6275]
workloadSourceSpoofing validator expects "Any)" instead of "Any"

## Expected Behavior
We are trying to pass the FelixConfiguration w/ new `workloadSourceSpoofing: Any` spec.
This should work properly and felixconfig should be applied w/o issues.

## Current Behavior
Currently this will throw an error:

```
Hit error(s): [error with field WorkloadSourceSpoofing = 'Any' (Reason: failed to validate Field: WorkloadSourceSpoofing because of Tag: oneof )] 
```

## Possible Solution
There seems to be a typo in felixconf.go where instead of oneoff beeing `Any` it is `Any)`.
https://github.com/projectcalico/calico/blob/b15773370b72c67d68075037f5012f5337228ab3/api/pkg/apis/projectcalico/v3/felixconfig.go#L455

Temp workaround (which will probably not work if someone really want's to use the service is to try to apply):

`workloadSourceSpoofing: Any)`...

This applies w/o errors.

## Steps to Reproduce (for bugs)

Have v3.23.1 calico (k8s 1.21.3)

1. Try to apply the felixconfig  where workloadSourceSpoofing is set to Any.
```
 ---
    apiVersion: projectcalico.org/v3
    kind: FelixConfiguration
    metadata:
      name: default
    spec:
      workloadSourceSpoofing: Any
      bpfLogLevel: ""
      logSeverityScreen: Info
      reportingInterval: 0s
```
2. Apply this using `calicoctl apply -f myfelixconf.yml`
Error message appears:
```
Failed to apply 'FelixConfiguration' resource: [error with field WorkloadSourceSpoofing = 'Any' (Reason: failed to validate Field: WorkloadSourceSpoofing because of Tag: oneof )]
``` 

## Your Environment

```
Client Version:    v3.23.1
Git commit:        967e24543
Cluster Version:   v3.23.1
Cluster Type:      k8s,bgp,kubeadm,kdd

k8s version: v1.21.3
```
