### ISSUE TITLE
Cannot find syslog on calico nodes in cluster.

### ISSUE THREAD

**Issue by ausername86** [projectcalico/calico#6299]
Hello,
I have a calico running in a k8 cluster running in EKS, currently looking in calico-system namespace
I am trying to log denied network traffic to syslog as discussed in this calico article: https://projectcalico.docs.tigera.io/security/calico-network-policy Generate logs for specific traffic.

I current have a default-deny-all policy in place.
```
kind: NetworkPolicy
apiVersion: projectcalico.org/v3
metadata:
  name: default-deny-all
spec:
  selector: all()
  types:
    - Ingress
    - Egress
  ingress:
    - action: Log
      protocol: TCP
      destination: {}
      source: {}
    - action: Deny
      protocol: TCP
      destination: {}
      source: {}
```
I am expecting to be able to see denied traffic in syslog on the calico nodes, however var/log/syslog doesn't exist on any of the calico nodes, I am unable to find any documentation that could indicate why this is?
## Expected Behavior
See denied traffic in syslog on the calico node

## Current Behavior
syslog does not exist on the calico node in var/log/syslog

## Steps to Reproduce (for bugs)

1. Run calico in kubernetes
2. create calico default-deny-all network policy
3. Add log action to ingress

## Context
Want to see denied network traffic logged when failing against a rule

## Your Environment

* Calico version 3.20.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): 1.22.5
* Operating System and version:
* Link to your project (optional):
