### ISSUE TITLE
ippool created with kubectl doesn't get vxlanMode: Never & ipipMode: Never as defaults

### ISSUE THREAD

**Issue by DennisGlindhart** [projectcalico/calico#6301]
Create an IP Pool via kubectl results in different defaults than calicoctl

## Current Behavior

kubectl create -f with:

```
apiVersion: crd.projectcalico.org/v1
kind: IPPool
metadata:
  name: test1-pool
spec:
  cidr: 2001:db8:1111::/64
```

calicoctl create -f with:

```
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: test2-pool
spec:
  cidr: 2001:db8:2222::/64
```

Result (calicoctl get ippool -o yaml)

```
kind: IPPoolList
items:
- apiVersion: projectcalico.org/v3
  kind: IPPool
  metadata:
    name: test1-pool
  spec:
    allowedUses:
    - Workload
    - Tunnel
    blockSize: 122
    cidr: 2001:db8:1111::/64
    nodeSelector: all()
- apiVersion: projectcalico.org/v3
  kind: IPPool
  metadata:
    name: test2-pool
  spec:
    allowedUses:
    - Workload
    - Tunnel
    blockSize: 122
    cidr: 2001:db8:2222::/64
    ipipMode: Never
    nodeSelector: all()
    vxlanMode: Never
```

Note the missing ipipMode and vxlanMode fields.

This results in vxlanMode being enabled on the IPPool (Only beginning with calico-node >=3.23 AFAIK) and leading to problems like #6144 

## Possible Solution
@fasaxc talked about aligning defaults between caliclctl and kubectl created objects.

## Your Environment
Calico version 3.23.2 (became a problem i 3.23, but the actual difference probably existed before)
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes 1.23
