### ISSUE TITLE
K8s service for linux pod is not accessible from windows pod in the same subnet

### ISSUE THREAD

**Issue by zhaidarbek** [projectcalico/calico#6322]
I have 3 master nodes and 2 workers on ubuntu and 2 workers on windows server 2022 with calico v3.23.2 installed as operator and deployed sample webapp onto both linux and windows workers.

```
apiVersion: operator.tigera.io/v1
kind: Installation
  name: default
spec:
  calicoNetwork:
    bgp: Disabled
    hostPorts: Enabled
    ipPools:
      - blockSize: 26
        cidr: 192.168.0.0/16
        encapsulation: VXLANCrossSubnet
        natOutgoing: Enabled
        nodeSelector: all()
    linuxDataplane: Iptables
    multiInterfaceMode: None
    nodeAddressAutodetectionV4:
      kubernetes: NodeInternalIP
```

![image](https://user-images.githubusercontent.com/107963/177492011-ee4a48d6-2d2e-4a29-a345-60363dc31291.png)

Nodes were launched in 3 different aws availability zones and thus have different subnets:
node-01 in subnet A
node-02 in subnet B
node-03 in subnet B
node-04 in subnet C
Src/Dest checks have been disabled for all ec2 instances including master nodes.

## Expected Behavior
With VXLANCrossSubnet i should be able to use calico on nodes in separate subnets. K8s services must be accessible across subnets.

## Current Behavior
When i curl linux-service:8000 from a windows pod running on node-04 (in subnet C) i always get response. The same is when i curl windows-service:8000 from a linux pod running on node-01 (in subnet A).

However when i do the same from pods running on nodes 02 and 03 (in subnet B) the request sometimes pass and sometimes fail with timeout. I suspect it passes when it hits the pod in different subnet and fails with pod in the same subnet (B). 

## Possible Solution
Perhaps the issue can be resolved by disabling the cross-subnet mode. However I'd love to get the performance of a non-overlay network when traffic flows between pods in the same subnet.

## Steps to Reproduce (for bugs)
1. Prepare 4 worker nodes in 3 different subnets as described above
2. Deploy 2 different apps so that one of the replicas gets deployed on the node in common subnet (eg. subnet B above)
3. Try to access the service from a pod in the common subnet
4. It sometimes responds and sometimes fail with timeout

## Context
I'd love to get the performance of a non-overlay network when traffic flows between pods in the same subnet.

## Your Environment

* Calico version v3.23.2
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes v1.24.2 deployed manually with kubeadm
* Operating System and version: EC2 instances with Ubuntu 20.04.4 LTS and Windows Server 2022 Datacenter
* Link to your project (optional):
