### ISSUE TITLE
cannot create resource "serviceaccounts/token" in API group "" in the namespace "kube-system"

### ISSUE THREAD

**Issue by pavansh** [projectcalico/calico#6378]
unable to install calico using https://projectcalico.docs.tigera.io/manifests/calico-etcd.yaml
error: cannot create resource "serviceaccounts/token" in API group "" in the namespace "kube-system"

## Possible Solution
solution:
after adding
```
  - apiGroups: [""]
    resources:
      - serviceaccounts/token
    resourceNames:
      - calico-node
    verbs:
      - create

``` 
in clusterrole fix the issue

## Steps to Reproduce (for bugs)

1. kubectl create -f https://projectcalico.docs.tigera.io/manifests/calico-etcd.yaml

## Your Environment

* Calico version: 3.23.2
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes
* Operating System and version: 
* Link to your project (optional):
