### ISSUE TITLE
Provide mechanism to modify established connections

### ISSUE THREAD

**Issue by 0m1xa** [projectcalico/calico#6399]
I faced the situation when deletion (and maybe creation) of the policy doesn't affect the pod(s).
I guess the main problem is that calico doesn't modify established connections. And if the pod has a persistent connection then changes will not affect it.

## Expected Behavior

Modify the established connections as well.

## Current Behavior

The state of the established connections doesn't change.

## Context

It is a great example to use [reloader](https://github.com/stakater/Reloader). 
- Create a default deny ingress/egress policy
- Deploy reloader in your cluster according to the docs
- Deploy a simple application and attach a secret/configMap, annotate the deployment with reloader annotations
- Try to make changes in the secret/configMap attached to the deployment.
- See error logs with unavailable kube-api from the reloader pod(s)
- Add allow policy for the reloader
```
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: allow-api-access
  namespace: test
spec:
  selector: all()
  egress:
    - action: Allow
      destination:
        services:
          name: kubernetes
          namespace: default
```
- Make changes in the secret/configMap again
- See no errors in the reloader pod(s)
- Delete the allow policy
- Make changes in the secret/configMap one more time
- It's expected to see the error messages in the reloader pod(s) with the unavailability of the kube-api.
But in the real world nothing changes to the reloader pod(s). They continue to communicate with the kube-api. 

## Your Environment

* Calico version
3.23.2
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes 1.21 (EKS), kubernetes 1.24.1 (minikube)
* Operating System and version: Amazon Linux2 (EKS), Ubuntu 20.04.4 (minikube)
