### ISSUE TITLE
After application GlobalNetworkPolicy , doesn't work [kubectl logs .. | kubectl exec ...]

### ISSUE THREAD

**Issue by KKulishov** [projectcalico/calico#6485]
## After application GlobalNetworkPolicy , doesn't work [kubectl logs .. | kubectl exec ...]
After application GlobalNetworkPolicy
```
kubectl logs -n kube-system calico-node-wd7nl 
Error from server: Get "https://xx.xx.xx.xx:10250/containerLogs/kube-system/calico-node-wd7nl/calico-node": dial tcp xx.xx.xx.xx:10250: i/o timeout
```

## My rules GlobalNetworkPolicy
```
apiVersion: crd.projectcalico.org/v1
kind: GlobalNetworkPolicy
metadata:
  name: webserver
spec:
  applyOnForward: true
  preDNAT: true
  selector: "role == 'k8s-node'"
  order: 2000
  ingress:
    - action: Allow
      protocol: TCP
      destination:
        ports: [25, 53, 179, 2376, 2379, 2380, 6443, 10250, 10255, 10111]
    - action: Allow
      protocol: UDP
      destination:
        ports: [25, 53, 179, 2376, 2379, 2380, 6443, 10250, 10255, 10111]
    - action: Allow
      protocol: UDP
      destination:
        ports: [53, 67]
    - action: Allow
      protocol: TCP
      source:
        nets:
        - "xx.xx.xx.xxx/32"
      destination:
        ports: [80, 443]      
  egress:
    - action: Allow
---
apiVersion: crd.projectcalico.org/v1
kind: GlobalNetworkPolicy
metadata:
  name: deny-all
spec:
  applyOnForward: true
  preDNAT: true
  selector: "role == 'k8s-node'"
  types:
    - Ingress
  order: 3000
  ingress:
    - action: Deny
```

My goal is to close extra ports from strangers at the level GlobalNetworkPolicy. It's all here ок , but why does it stop working after applying the policy [kubectl logs .. | kubectl exec ...] 

### Port 10250 allowed  in GlobalNetworkPolicy,  but upon request 
```
kubectl logs -n kube-system calico-node-wd7nl 
```
get 
```
Error from server: Get "https://xx.xx.xx.xx:10250/containerLogs/kube-system/calico-node-wd7nl/calico-node": dial tcp xx.xx.xx.xx:10250: i/o timeout
```

what's my mistake ?

**Comment by caseydavenport** [comment]
It looks like you have created an invalid policy by using the crd.projectcalico.org/v1 API group. You shouldn't use that API group, and can read more about why here: https://github.com/projectcalico/calico/issues/6412

projectcalico.org/v3 is the correct API to use.

**Comment by KKulishov** [comment]
@caseydavenport Thanks

changed apiVersion to projectcalico.org/v3 and remove preDNAT

```
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: webserver
spec:
  applyOnForward: true
  selector: "role == 'k8s-node'"
  order: 2000
  ingress:
    - action: Allow
      protocol: TCP
      destination:
        ports: [25, 53, 179, 2376, 2379, 2380, 6443, 10250, 10255, 10111]
    - action: Allow
      protocol: UDP
      destination:
        ports: [25, 53, 179, 2376, 2379, 2380, 6443, 10250, 10255, 10111]
    - action: Allow
      protocol: UDP
      destination:
        ports: [53, 67]
    - action: Allow
      protocol: TCP
      source:
        nets:
        - "xx.xx.xx.xxx/32"
      destination:
        ports: [80, 443]      
  egress:
    - action: Allow
```

applied via  calicoctl.

Works.
