### ISSUE TITLE
 default deny Calico global network policy not working

### ISSUE THREAD

**Issue by der-ali** [projectcalico/calico#6488]
I wanted to evaluate the calico network policies, so i followed the documentation [here](https://projectcalico.docs.tigera.io/security/kubernetes-default-deny) and create a global deny policy.  Then i created a  busybox pod in the default namespace to test if the network traffic is blocked. I was suprised that both network resolution and traffic to other pods and services is still allowed. 
## Expected Behavior
Pod is not able to access k8s services or do DNS resolution

## Steps to Reproduce (for bugs)
1. Create a minikube cluster
```
minikube start -p demo  --kubernetes-version=1.22.0 --container-runtime=containerd --nodes 2 --memory 2048 --cpus 2 --enable-default-cni=false
```
2. Deploy Calico operator
```
kubectl create -f https://projectcalico.docs.tigera.io/manifests/tigera-operator.yaml
cat <<EOF | kubectl apply -f -
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  calicoNetwork:
    ipPools:
    - blockSize: 26
      cidr: 10.244.0.0
      encapsulation: VXLANCrossSubnet
      natOutgoing: Enabled
      nodeSelector: all()
EOF
```
3. Create a default deny network policy
```
cat <<EOF | calicoctl apply -f -
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: deny-all
spec:
  selector: all()
  types:
    - Ingress
    - Egress
EOF
```
4. Test dns resolution or use `nc` to check if a port is open on a k8s svc

## Your Environment

* Calico version v3.23.3
* K8s 1.22.0
