### ISSUE TITLE
natOutgoingAddress on multi node installation

### ISSUE THREAD

**Issue by leagueofsoups** [projectcalico/calico#6503]
Hello, how can I get this behavior on operator management?

```
- name: FELIX_NATOUTGOINGADDRESS
  valueFrom:
    fieldRef:
      fieldPath: status.hostIP
```

## Expected Behavior
It is possible to specify a personal source address for each node

## Current Behavior
https://projectcalico.docs.tigera.io/reference/resources/felixconfig#spec
natOutgoingAddress parameter have type string, I don't understand how can I use it on multi node installation
