### ISSUE TITLE
Terminating the Dangling Network Call Which Is Blocked By Calico Network Policy

### ISSUE THREAD

**Issue by sumanth-sure** [projectcalico/calico#6509]
Certain IP's were Blocked Using Network Policy and applied inside k8 cluster for specific pods the blocked ip's  when called the connection where dangling utilising the pod resources

Network Policy
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-network-policy
  namespace: test
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/edge_traffic: egress
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except: 
              - 169.254.169.254/32

# Immediate Reject the calls setting inside calico 
```
Above we are expecting to block **169.254.169.254/32**
## Expected Behavior

When made a call to **169.254.169.254/32** the network call is not blocked immediately but gets timed out eventually after 130s 
Expected Behaviour: It should get terminated immediately not keeping the connection open for a definite amount of time. 
## Current Behavior
The connection not closed until 130s. 
<img width="772" alt="Screenshot 2022-08-08 at 6 07 35 PM" src="https://user-images.githubusercontent.com/59997321/183422549-8c81dbed-7484-4d65-a57e-db32d78e11f8.png">

## Possible Solution

Is there an **ENV** Vairalbe which can be configured for immediate termination of the blocked request.
## Steps to Reproduce (for bugs)

1. Deployemnt 
```
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: test
  labels:
    app.kubernetes.io/edge_traffic: egress
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
  ```
2.
Network Policy
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-network-policy
  namespace: test
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/edge_traffic: egress
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except: 
              - 169.254.169.254/32

# Immediate Reject the calls setting inside calico 
```

## Your Environment

* Calico version 3:20
`docker.io/calico/pod2daemon-flexvol:v3.20.0`
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes
* Operating System and version:
* Link to your project (optional):

**Comment by sumanth-sure** [comment]
Tried with Calico Resource(CRD) the same behavior was observed. The network Call didn't exit till 130s. Utilising the Network resource till 130s
```
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: deny-egress-external
  namespace: test
spec:
  selector:
    app.kubernetes.io/edge_traffic ==  'egress'
  types:
    - Egress
  egress:    
    - action: Deny
      destination:
        nets:
        - 169.254.169.254/32
```
