### ISSUE TITLE
calico-mesos , marathon health check failed.

### ISSUE THREAD

**Issue by tangjiaxing669** [projectcalico/calico#651]
The follow is my Marathon, Mesos, docker, etcd, and calico informations:

```
Mesos Version: 1.1.0
Marathon Version: 1.3.6
```

```
[root@slave1 ~]# docker version
Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:23:59 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:23:59 2016
 OS/Arch:      linux/amd64
[root@slave1 ~]#
[root@slave1 ~]# docker info
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 8
Server Version: 1.12.5
Storage Driver: devicemapper
 Pool Name: docker-253:0-403269431-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.102 GB
 Data Space Total: 107.4 GB
 Data Space Available: 97.74 GB
 Metadata Space Used: 4.358 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.143 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135-RHEL7 (2016-09-28)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host overlay calico null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.51 GiB
Name: slave1
ID: 4VRS:RPSC:ASAX:MTRJ:TOGC:6RFL:6RJS:J4MK:3VSN:JZO2:Q2FB:LJEW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Cluster Store: etcd://172.30.30.5:2379
Cluster Advertise: 172.30.30.5:2375
Insecure Registries:
 172.30.30.8:80
 127.0.0.0/8
[root@slave1 ~]# 
```

```
[root@slave1 ~]# etcdctl --version
etcdctl version: 3.0.15
API version: 2
[root@slave1 ~]# etcdctl member list
c0f3a64509371e0b: name=jasontom0 peerURLs=http://172.30.30.5:2380 clientURLs=http://172.30.30.5:2379 isLeader=false
f28f6ed37e2b06ad: name=jasontom2 peerURLs=http://172.30.30.11:2380 clientURLs=http://172.30.30.11:2379 isLeader=true
f33c7e938a2546a8: name=jasontom1 peerURLs=http://172.30.30.6:2380 clientURLs=http://172.30.30.6:2379 isLeader=false
```

```
[root@slave1 ~]# calicoctl version
Version:      v1.1.0
Build date:   
Git commit:   882dd008
[root@slave1 ~]# calicoctl node status
Calico process is running.

IPv4 BGP status
+--------------+-------------------+-------+----------+-------------+
| PEER ADDRESS |     PEER TYPE     | STATE |  SINCE   |    INFO     |
+--------------+-------------------+-------+----------+-------------+
| 172.30.30.11 | node-to-node mesh | up    | 19:44:06 | Established |
| 172.30.30.6  | node-to-node mesh | up    | 19:44:17 | Established |
+--------------+-------------------+-------+----------+-------------+

IPv6 BGP status
No IPv6 peers found.

[root@slave1 ~]#
```

Here are the marathon and mesos startup information(2 master and 3 slave):

```
[root@master1 ~]# ps aux | grep marathon
root     15376  0.6 11.4 4178684 443236 ?      Ssl  Mar16 131:52 java -Djava.library.path=/usr/local/lib:/usr/lib:/usr/lib64 -Djava.util.logging.SimpleFormatter.format=%2$s%5$s%6$s%n -Xmx512m -cp /usr/bin/marathon mesosphere.marathon.Main --hostname 172.30.30.4 --zk zk://172.30.30.4:2181,172.30.30.12:2181/marathon --master zk://172.30.30.4:2181,172.30.30.12:2181/mesos --artifact_store file:///mnt/store
```

```
[root@master1 ~]# ps aux | grep mesos-master
root     15448  0.0  0.7 1485476 27556 ?       Ssl  Mar16  15:48 /usr/sbin/mesos-master --zk=zk://172.30.30.4:2181,172.30.30.12:2181/mesos --port=5050 --log_dir=/var/log/mesos --cluster=cp_cluster --hostname=172.30.30.4 --quorum=1 --work_dir=/var/lib/mesos
```

```
[root@slave1 ~]# ps aux | grep mesos-slave
root      6511  0.2  0.0 960388  5636 ?        Ssl  03:13   2:42 /usr/sbin/mesos-slave --master=zk://172.30.30.4:2181,172.30.30.12:2181/mesos --log_dir=/var/log/mesos --containerizers=docker,mesos --executor_registration_timeout=5mins --hostname=172.30.30.5 --ip=172.30.30.5 --isolation=filesystem/linux,docker/runtime,network/cni --network_cni_config_dir=/var/lib/mesos/cni/config --network_cni_plugins_dir=/var/lib/mesos/cni/plugins --work_dir=/var/lib/mesos
```

I create a `my-calico-net` network.

```
[root@slave1 mesos-slave]# docker network create --driver=calico --ipam-driver=calico-ipam  my-calico-net
62df605940821546d1bf5ae796fce1c05c5c5aa684c6960f4233650f39ee44e3
[root@slave1 mesos-slave]# docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
91b6a9337154        bridge              bridge              local               
d297c7e5148e        docker_gwbridge     bridge              local               
c0d017d2f47b        host                host                local               
62df60594082        my-calico-net       calico              global              
32d1073ac56b        none                null                local    
[root@slave1 mesos-slave]# calicoctl node run 
Running command to load modules: modprobe -a xt_set ip6_tables
Enabling IPv4 forwarding
Enabling IPv6 forwarding
Increasing conntrack limit
Removing old calico-node container (if running).
Running the following command to start calico-node:

docker run --net=host --privileged --name=calico-node -d --restart=always -e NODENAME=slave1 -e CALICO_NETWORKING_BACKEND=bird -e CALICO_LIBNETWORK_ENABLED=true -e CALICO_LIBNETWORK_LABEL_ENDPOINTS=false -e CALICO_LIBNETWORK_IFPREFIX=cali -e ETCD_AUTHORITY= -e NO_DEFAULT_POOLS= -e IP_AUTODETECTION_METHOD=first-found -e IP6_AUTODETECTION_METHOD=first-found -e CALICO_LIBNETWORK_CREATE_PROFILES=true -e ETCD_ENDPOINTS=http://172.30.30.5:2379 -e ETCD_SCHEME= -v /var/log/calico:/var/log/calico -v /var/run/calico:/var/run/calico -v /lib/modules:/lib/modules -v /run/docker/plugins:/run/docker/plugins -v /var/run/docker.sock:/var/run/docker.sock quay.io/calico/node:v1.1.0

Image may take a short time to download if it is not available locally.
Container started, checking progress logs.

Skipping datastore connection test
Using autodetected IPv4 address on interface ens160: 172.30.30.5/24
No AS number configured on node resource, using global value
Using node name: slave1
Starting libnetwork service
Calico node started successfully
[root@slave1 mesos-slave]# docker ps -a
CONTAINER ID        IMAGE                                        COMMAND                  CREATED             STATUS                      PORTS                    NAMES
f59e8809a569        quay.io/calico/node:v1.1.0                   "start_runit"            25 minutes ago      Up 25 minutes                                        calico-node
20d1bc789f55        172.30.30.8:80/cp_project/syslog:v17.01.03   "/start"                 4 days ago          Up 4 days                   0.0.0.0:31514->514/tcp   mesos-1e68ea0f-0f0b-4f14-8e2e-ab10169ee5f3-S0.60b68a1e-ab9a-4f83-ad36-b43b88110bba
```

The follow is my CNI information:

```
[root@slave1 ~]# ll /var/lib/mesos/cni/plugins/
total 53496
-rwxr-xr-x. 1 root root 27660832 Mar 31 00:41 calico
-rwxr-xr-x. 1 root root 27113088 Mar 31 01:07 calico-ipam
[root@slave1 ~]# cat /var/lib/mesos/cni/config/calico-net-1.conf 
{
    "name": "my-calico-net",
    "type": "calico",
    "ipam": {
        "type": "calico-ipam"
    },
    "etcd_endpoints": "http://172.30.30.5:2379"
}
[root@slave1 ~]# 
```

The above operation I think has been very perfect, but when I submit the following JSON to Marathon, the health check in marathon is a failure(Unhealthy).

```
[root@master1 ~]# cat nginx.json 
{
	    "id": "nginx",
            "cmd": null,
            "cpus": 1,
            "mem": 128,
            "disk": 0,
            "instances": 3,
	    "constraints": [["hostname", "UNIQUE"]],
            "ipAddress": {
                "networkName": "my-calico-net"
            },
            "labels": {
                "HAPROXY_GROUP": "external",
                "HAPROXY_0_VHOST": "nginx.cp.com"
            },
	    "container": {
                "docker": {
                     "image": "172.30.30.8:80/cp_project/nginx:v17.01.08",
                     "network": "USER",
                     "parameters": [
                          { "key": "log-driver", "value": "syslog" },
                          { "key": "log-opt", "value": "syslog-address=tcp://127.0.0.1:31514" },
                          { "key": "log-opt", "value": "tag=nginx" }
                     ],
                     "portMappings": [
                          { "containerPort": 80, "hostPort": 0, "servicePort": 8888, "name": "http" },
                          { "containerPort": 443, "hostPort": 0, "servicePort": 8889, "name": "https" }
                     ]
                },
            "type": "DOCKER",
            "volumes": []
            },
	    "healthChecks": [
                {
                      "path": "/",
                      "portIndex": 0,
                      "protocol": "HTTP",
                      "gracePeriodSeconds": 300,
                      "intervalSeconds": 60,
                      "timeoutSeconds": 20,
                      "maxConsecutiveFailures": 3,
                      "ignoreHttp1xx": false
                 },
		 {
                      "protocol": "TCP",
                      "portIndex": 0,
                      "maxConsecutiveFailures": 3
                 }
              ]
}
```

In the marathon health check option will show:

```
Warning: Health check 'HTTP /' failed. Warning: Health check 'TCP ' failed.
```

after a while will not become:

```
Warning: Health check 'HTTP /' returned with status: 'AskTimeoutException: Ask timed out on [Actor[akka://marathon/user/IO-HTTP#295467085]] after [20000 ms]. Sender[null] sent message of type "spray.http.HttpRequest".'. Warning: Health check 'TCP ' returned with status: 'SocketTimeoutException: connect timed out'.
```

and finally destroy the container, and then start the container, has been circulating.

![](https://raw.githubusercontent.com/tangjiaxing669/docker/master/picture/marathon-failed1.png)
![](https://raw.githubusercontent.com/tangjiaxing669/docker/master/picture/marathon-failed2.png)

I did not see any exceptions in the log, and when I used the BRIDGE network, everything became very normal.

Please help.

**Comment by tmjd** [comment]
@djosborne is out of the office today so I'll try to help.

I noticed is that you have portMappings defined in your nginx.json.  I do not believe portMappings have any affect when using calico, could you remove those and specify the port in the healthChecks section instead of the portIndex.

djosborne pointed out in your last issue that he thought Deploying meant that mesos is having trouble launching the app/container.  Can you verify the container is being launched?  Maybe check if a `docker ps` shows the container or check if Mesos reports it being up.

Another thing djosborne mentioned was possibly the profile being too restrictive.  Could you capture the output of `calicoctl profile -o yaml` and attach it?

**Comment by tangjiaxing669** [comment]
@tmjd Thanks.

I tried your suggestion, but the problem still exists. I modify `nginx.json`:

```
[root@master1 ~]# cat nginx_test.json
{
	    "id": "nginx",
            "cmd": null,
            "cpus": 1,
            "mem": 128,
            "disk": 0,
            "instances": 3,
	    "constraints": [["hostname", "UNIQUE"]],
            "ipAddress": {
                "networkName": "my-calico-net"
            },
	    "container": {
                "docker": {
                     "image": "172.30.30.8:80/cp_project/nginx:v17.01.08",
                     "network": "USER"
                },
            "type": "DOCKER",
            "volumes": []
            },
	    "healthChecks": [
                {
                      "path": "/",
                      "port": 80,
                      "protocol": "HTTP",
                      "gracePeriodSeconds": 300,
                      "intervalSeconds": 60,
                      "timeoutSeconds": 20,
                      "maxConsecutiveFailures": 3,
                      "ignoreHttp1xx": false
                }
            ]
	}
```

If I remove the `portMapping`, then specify the `port` in the health check would it do? Is the health check in the marathon checked by the `port` (`hostPort`) mapped to the host?

In addition, in calico I did not configure any strategy.

```
[root@slave1 ~]# calicoctl get -o yaml profile
- apiVersion: v1
  kind: profile
  metadata:
    name: my-calico-net
    tags:
    - my-calico-net
  spec:
    egress:
    - action: allow
      destination: {}
      source: {}
    ingress:
    - action: allow
      destination: {}
      source:
        tag: my-calico-net
[root@slave1 ~]# 
```

Also, `docker ps` can see the container is running, but marathon's health check fails, so the container will run for some time and then destroyed and then destroyed, the wireless loop goes.

**Comment by tmjd** [comment]
Could you try running the following?
```
calicoctl apply -f - <<EOF
- apiVersion: v1
  kind: profile
  metadata:
    name: my-calico-net
    tags:
    - my-calico-net
  spec:
    egress:
    - action: allow
      destination: {}
      source: {}
    ingress:
    - action: allow
      destination: {}
EOF
```
Your current profile only allows ingress to a container if it is coming from a source with the tag: my-calico-net, which the marathon traffic would not have.  What I'm suggesting is opening the profile wide open to any traffic, it is not what you would really want to use in production but simplifies testing.

**Comment by tangjiaxing669** [comment]
Yes, I just want to test it. I applied your strategy (`calico`), but the problem still exists.

```
[root@slave3 ~]# calicoctl apply -f - <<EOF
> - apiVersion: v1
>   kind: profile
>   metadata:
>     name: my-calico-net
>     tags:
>     - my-calico-net
>   spec:
>     egress:
>     - action: allow
>       destination: {}
>       source: {}
>     ingress:
>     - action: allow
>       destination: {}
> EOF
Successfully applied 1 'profile' resource(s)
[root@slave3 ~]# calicoctl get -o yaml profile
- apiVersion: v1
  kind: profile
  metadata:
    name: my-calico-net
    tags:
    - my-calico-net
  spec:
    egress:
    - action: allow
      destination: {}
      source: {}
    ingress:
    - action: allow
      destination: {}
      source: {}
[root@slave3 ~]#
```

There are a lot of this information in the log:

```
Apr  1 00:10:04 master2 marathon[23041]: [2017-04-01 00:10:04,335] WARN Configured connecting timeout of 10 seconds expired, stopping (spray.can.client.HttpClientConnection:marathon-akka.actor.default-dispatcher-2180)
Apr  1 00:10:04 master2 marathon[23041]: [2017-04-01 00:10:04,335] WARN Configured connecting timeout of 10 seconds expired, stopping (spray.can.client.HttpClientConnection:marathon-akka.actor.default-dispatcher-2180)
Apr  1 00:10:04 master2 marathon[23041]: [2017-04-01 00:10:04,335] WARN Connection attempt to 192.168.77.28:80 failed in response to GET request to / with 1 retries left, retrying... (spray.can.client.HttpHostConnectionSlot:marathon-akka.actor.default-dispatcher-2180)
Apr  1 00:10:04 master2 marathon[23041]: [2017-04-01 00:10:04,335] WARN Connection attempt to 192.168.140.103:80 failed in response to GET request to / with 1 retries left, retrying... (spray.can.client.HttpHostConnectionSlot:marathon-akka.actor.default-dispatcher-2180)
```

> After using `calico`, does the container's `portMapping` information show up (`docker ps`)?

**Comment by tmjd** [comment]
> After using `calico`, does the container's portMapping information show up (`docker ps`)?
There is no portMapping necessary when using calico because each container has it's own IP address and ports can be accessed directly.

On the host running marathon can you try doing a ping or curl to one of your nginx instances, maybe that output will be more informative.

Could you capture the output of `calicoctl get weps -o yaml` and attach it here too?  That let us check that the label/tag is being applied correctly to the workload.

**Comment by tangjiaxing669** [comment]
@tmjd Thanks.

The follow is `calicoctl get weps -o yaml` information:

```
[root@slave3 ~]# calicoctl get -o yaml weps
- apiVersion: v1
  kind: workloadEndpoint
  metadata:
    name: a4205b6099c9884bc04079d63d1dffba6b1ea73804e0fdca84cf532800372880
    node: slave1
    orchestrator: libnetwork
    workload: libnetwork
  spec:
    interfaceName: calia4205b6099c
    ipNetworks:
    - 192.168.140.227/32
    mac: ee:ee:ee:ee:ee:ee
    profiles:
    - my-calico-net
- apiVersion: v1
  kind: workloadEndpoint
  metadata:
    name: b5474da1a140bf1ed8773bfd5c1c7abf791a207789a1a12c3a9a6a4bccaf3efa
    node: slave1
    orchestrator: libnetwork
    workload: libnetwork
  spec:
    interfaceName: calib5474da1a14
    ipNetworks:
    - 192.168.140.228/32
    mac: ee:ee:ee:ee:ee:ee
    profiles:
    - my-calico-net
- apiVersion: v1
  kind: workloadEndpoint
  metadata:
    name: 04d004d3d66b57a473dd80ecb512847eb0366257d98add215148bcea9d9f2f8c
    node: slave2
    orchestrator: libnetwork
    workload: libnetwork
  spec:
    interfaceName: cali04d004d3d66
    ipNetworks:
    - 192.168.140.102/32
    mac: ee:ee:ee:ee:ee:ee
    profiles:
    - my-calico-net
- apiVersion: v1
  kind: workloadEndpoint
  metadata:
    name: 433ff567f4d55adc67a8a2850596c7a420ae5b2c8be3edd72e369efd0f015b9e
    node: slave3
    orchestrator: libnetwork
    workload: libnetwork
  spec:
    interfaceName: cali433ff567f4d
    ipNetworks:
    - 192.168.77.30/32
    mac: ee:ee:ee:ee:ee:ee
    profiles:
    - my-calico-net
[root@slave3 ~]# 
```

It is unreachable to ping the container on the marathon node (`192.168.0.0/16`).

Marathon node IP range is `172.30.30.0/24`, the default calico IP range is `192.168.0.0/16`.
