### ISSUE TITLE
[bug] network policy is not compatible with kube-proxy's config of `clusterCIDR` under new ippool

### ISSUE THREAD

**Issue by luckymrwang** [projectcalico/calico#6545]
## Expected Behavior

under the networkpolicy : allow pod connection each other in one namespace, deny cross namespace traffic.
under one namespace bond new ippool, in one pod requesting clusterIP:port should be allowed to annother pod

## Current Behavior

under the networkpolicy : allow pod connection each other in one namespace, deny cross namespace traffic.
under one namespace bond new ippool, in one pod requesting clusterIP:port is denied to annother pod

## Possible Solution

1. kube-proxy config: 
- Add kube-proxy config `clusterCIDR` containing new ippool, but the config only support one ipv4 cidr.
- Maybe change kube-proxy config `clusterCIDR` to `0.0.0.0/0`, but it may affect request service whose endpoints is `hostnetwork` mode.
2. Add `tunl0` IP to networkpolicy. But every node is different and the tunl0 is created dynamically.

## Steps to Reproduce (for bugs)

1. create a new ippool as a subnet, such as `192.168.1.0/24` as follows
```yaml
apiVersion: crd.projectcalico.org/v1
kind: IPPool
metadata:
  name: subnet
spec:
  blockSize: 24
  cidr: 192.168.1.0/24
  ipipMode: Always
  natOutgoing: true
  nodeSelector: all()
  vxlanMode: Never
```
4. create a `namespace` named `ns1`, add ns annotation `"cni.projectcalico.org/ipv4pools": "192.168.1.0/24"`
5. under namespace `ns1`: 
- create a `deployment` named `dp1` whose `pod` is on `node1`, and the `pod` name is like `dp1-xxx`, podIP is `192.168.1.1`
- create annother `deployment` named `dp2` whose `pod` is on `node2`,  the `pod` name is like `dp2-xxx` and podIP is `192.168.1.2`. In addition, create a `service` named `svc2` whose selector matches pod `dp2-xxx`, such as `svc2`'s clusterIP is `10.233.56.189` and port is `8080`
- create a `networkpolicy` as follows

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: netpol1
  namespace: ns1
spec:
  egress:
  - to:
    - podSelector: {}
  ingress:
  - from:
    - podSelector: {}
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
```
to allow pod connection each other in one namespace, deny cross namespace traffic.

6. when `kubectl -n ns1 exec -it dp1-xxx curl 10.233.56.189:8080`, the traffic is denied. 

## Context

**Reason:**
1. the k8s cluster defalut ippool is `10.238.64.0/18` and the kube-proxy config of `clusterCIDR` is `10.238.64.0/18`
4. kube-proxy create a iptable rule `-A KUBE-SERVICES ! -s 10.238.64.0/18 -m comment --comment "Kubernetes service cluster ip + port for masquerade purpose" -m set --match-set KUBE-CLUSTER-IP dst,dst -j KUBE-MARK-MASQ` in nat table
5. when `kubectl -n ns1 exec -it dp1-xxx curl 10.233.56.189:8080`, package will leave node1, this moment package's src IP is 192.168.1.1 not in `10.238.64.0/18` matching above iptable rule, so do `SNAT` chaning package's src to `tunl0`'s IP `10.233.90.0`, leaving node1.
6. to node2, calico creates iptable rule according to networkpolicy `netpol1`. 
- such as `cali-tw-calid0xxxx -m comment "cali:xxx" -m mark 0x0/0x20000 -j cali-pi-_xxxxx`
- `cali-pi-_xxxxx -m comment "xxxxx" -m set --match-set cali40s:xx src -j MARK --set-xmark 0x10000/0x10000`
- ipset `cali40s:xx` contains pod `dp1-xxx`'s IP `192.168.1.1` allowed, not contains `tunl0`'s IP `10.233.90.0`

  **So the package is droped.**

## Your Environment

* Calico version
v3.21.4

* Orchestrator version (e.g. kubernetes, mesos, rkt):
kubernetes v1.20.10

* Operating System and version:
CentOS7

* Link to your project (optional):
