### ISSUE TITLE
Calico-node pods flapping up and down on worker nodes, control plane node is ok.

### ISSUE THREAD

**Issue by Daxcor69** [projectcalico/calico#6614]
I am doing a fresh install of kubeadm on bare metal.  The cluster comes up and initializes just fine.  When I apply the Calico operator and corresponding custom-resources, the CP node becomes ready after I remove the taints.  All the pods of calico are up and stable.  After I join a worker node to the cluster calico launches the appropriate pods for the new node.  The pods go ready, and then they start to flap between ready and not. The cp node stays stable, it is any worker nodes added that flap.  I am happy to provide the output of calicoctl diags.. just have to find a file sharing site... Just let me know what you need.  I have gone through the troubleshooting site and none of the outputs seems to show a smoking gun.

## Event output
(combined from similar events): Readiness probe failed: 2022-08-24 16:20:39.378 [INFO][366] confd/health.go 180: Number of node(s) with BGP peering established = 2 calico/node is not ready: BIRD is not ready: BGP not established with 10.0.1.6,10.0.1.7,10.0.1.9,10.0.1.11
Now the readiness endpoint does work, as I have done   watch 'http://localhost:9099/liveness'  and I can see when it flaps as I get valid out put and then "connection refused"

## Expected Behavior
Calico pods should remain up and not flap

## Your Environment
* Calico version
docker.io/calico/pod2daemon-flexvol:v3.24.0
docker.io/calico/cni:v3.24.0

* Orchestrator version (e.g. kubernetes, mesos, rkt):
k8s via kubeadm  v 1.24.4

* Operating System and version:
ubuntu 22.04 minimal install 
`Linux worker1 5.15.0-46-generic #49-Ubuntu SMP Thu Aug 4 18:03:25 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
* container run time
 containerd:  1.6.8

Network Configuration:
```
# This is the network config written by 'subiquity'
network:
  bonds:
    bond0:
      addresses:
      - 173.x.x.250/30
      - 10.0.1.9/24
      gateway4: 173.x.x.249
      interfaces:
      - enp1s0f0
      - enp1s0f1
      nameservers:
        addresses:
        - 8.8.8.8
        - 1.1.1.1
      parameters:
        lacp-rate: fast
        mode: 802.3ad
        transmit-hash-policy: layer3+4
  ethernets:
    enp1s0f0: {}
    enp1s0f1: {}
  version: 2
```
Calico custom-resources.yaml
```
# This section includes base Calico installation configuration.
# For more information, see: https://projectcalico.docs.tigera.io/master/reference/installation/api#operator.tigera.io/v1.Installation
kind: Installation
apiVersion: operator.tigera.io/v1
metadata:
  name: default
spec:
  calicoNetwork:
    nodeAddressAutodetectionV4:
      cidrs:
        - "10.0.1.0/24"
    ipPools:
    - blockSize: 26
      cidr: 10.244.0.0/16
      encapsulation: VXLANCrossSubnet
      natOutgoing: Enabled
      nodeSelector: all()
---
# This section configures the Calico API server.
# For more information, see: https://projectcalico.docs.tigera.io/master/reference/installation/api#operator.tigera.io/v1.APIServer
apiVersion: operator.tigera.io/v1
kind: APIServer
metadata:
  name: default
spec: {}

```

Kubeadm configuration file:
```
kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta3
kubernetesVersion: "v1.24.4"
clusterName: "foundry-cluster"
controlPlaneEndpoint: "cluster-endpoint:6443"
networking:
  serviceSubnet: "10.96.0.0/16"
  podSubnet: "10.244.0.0/16"
apiServer:
  certSANs:
  - "10.0.1.1"
  - "cluster-endpoint"
---
kind: InitConfiguration
apiVersion: kubeadm.k8s.io/v1beta3
localAPIEndpoint:
  advertiseAddress: 10.0.1.3
---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: systemd
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: iptables
```
