### ISSUE TITLE
Kubernetes policies that select for services instead of pods? (e.g. serviceSelector)

### ISSUE THREAD

**Issue by mconigliaro** [projectcalico/calico#6615]
I have a question about [Step 5](https://docs.projectcalico.org/security/tutorials/kubernetes-policy-advanced#5-allow-dns-egress-traffic) in the [Kubernetes policy, advanced tutorial](https://docs.projectcalico.org/security/tutorials/kubernetes-policy-advanced).

It looks like the idea here is to use `namespaceSelector` to allow traffic to pods in the `kube-system` namespace, presumably because that's where the DNS pods live:

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns-access
  namespace: advanced-policy-demo
spec:
  podSelector:
    matchLabels: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    ports:
    - protocol: UDP
      port: 53
```

However, when I `cat /etc/resolv.conf` on my pods, nameserver is set to the IP address of a **service**. So when I try this example, DNS still doesn't work, which makes complete sense to me; the allowed list of IPs would be for the pods, and DNS queries to the service IP would be getting blocked by the default deny. It seems like rather than selecting individual pods via `namespaceSelector` and/or `podSelector`, I need a `serviceSelector`, [which I guess was talked about but never actually implemented](https://groups.google.com/g/kubernetes-sig-network/search?q=serviceselector). So now I'm wondering what I'm missing, because I can't understand how this could ever work. 

Note: If I remove the selector and just allow port 53 to anywhere, it works as expected, which also makes complete sense to me.
