### ISSUE TITLE
ipBlock matches cluster internal IPs

### ISSUE THREAD

**Issue by der-ali** [projectcalico/calico#6634]
I created a K8s networkpolicy and wanted to allow egress on some pods to outside of the cluster **only**.
Kubernetes documentation states that ipBlock should only match on cluster IPs and recommends against using them to match on cluster IPs.

> ipBlock: This selects particular IP CIDR ranges to allow as ingress sources or egress destinations. These should be cluster-external IPs, since Pod IPs are ephemeral and unpredictable.

```
      egress:
        - to:
            - ipBlock:
                cidr: 0.0.0.0/0
```
In my case though, i was able to reach intern K8s service , using the upper rule (I have a default deny rule). It was only able to prevent internal ip access by adding except section.
```
      egress:
        - to:
            - ipBlock:
                cidr: 0.0.0.0/0
                except:
                  - 10.244.0.0/16
                  - 10.96.0.0/12
```

## Expected Behavior
 Internal Cluster network not reachable on the pods using the network policy with ipBlock.

## Current Behavior
Internal Cluster network is reachable

## Your Environment
* Calico version 3.22.2
* Orchestrator version (e.g. kubernetes, mesos, rkt): K8s 1.22
