### ISSUE TITLE
Calico uses the link-local ip address for traffic going from host to the pod

### ISSUE THREAD

**Issue by farcaller** [projectcalico/calico#6640]
## Expected Behavior
Calico uses link-local ip address for traffic going from host to the pod, i.e. something within 169.254/16 range. If the pod has subnetworks of its own (e.g. by running a kubevirt vm), chances are it will have its own routes to 169.154/16 and thus won't return any traffic.

## Current Behavior
Calico doesn't have any host-side interface with the pod subnet so it originates host traffic from the link-local IP. It does usually work because the pods return all the traffic to the default gw 169.254.1.1. It will break if pods have their own interfaces with link-local routes.

## Possible Solution
Flannel exposes the pod-network IP on the host via its `cni0` bridge. Cilium does the same via `cilium_host` (although that's not a bridge; I assume it's just a placeholder and proper sources are written by the ebpf).

## Steps to Reproduce (for bugs)

- deploy a [trivial nginx pod](https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/service/networking/run-my-nginx.yaml)
- curl the pod IP address from the host (in the examples below the pod ip that was assigned is `10.100.50.136`).
- observe the pod logs: `169.254.224.148 - - [30/Aug/2022:12:13:00 +0000] "GET / HTTP/1.1" 200 615 "-" "curl/7.83.1" "-"`

The IP address comes from the calico interface host-side:
```
calic542c51c80d: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
        inet 169.254.224.148  netmask 255.255.0.0  broadcast 169.254.255.255
        inet6 fe80::ecee:eeff:feee:eeee  prefixlen 64  scopeid 0x20<link>
        ether ee:ee:ee:ee:ee:ee  txqueuelen 0  (Ethernet)
        RX packets 18  bytes 2141 (2.0 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 32  bytes 4344 (4.2 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

Which is picked for the pod IP:
```
# ip r get 10.100.50.136
10.100.50.136 dev calic542c51c80d src 169.254.224.148 uid 0
    cache
```

> A fun fact - there are *several* interfaces with that IP on the host:
> 
> ```
> # ip a |grep 148
>     inet 169.254.224.148/16 brd 169.254.255.255 scope global noprefixroute calic542c51c80d
>     inet 169.254.224.148/16 brd 169.254.255.255 scope global noprefixroute calife0990f2fdb
> ```
> But of course the correct one is picked because of the routing entry:
> ```
> # ip r|grep 136
> 10.100.50.136 dev calic542c51c80d scope link
> ```

## Context
My kubevirt VMs run k3s (with the default flannel). Flannel's routing breaks down the return vm->host traffic:
![image](https://user-images.githubusercontent.com/693/187435738-100be39f-fd62-47db-b84e-3fa8b9f9c1b9.png)
because the host originates it from 169.254/16 and the vm has a route for that that takes precedence over the default gw.

## Your Environment
Calico installed with an operator:
```yaml
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  calicoNetwork:
    bgp: Disabled
    ipPools:
    - blockSize: 26
      cidr: 10.100.0.0/16
      encapsulation: VXLANCrossSubnet
      natOutgoing: Enabled
      nodeSelector: all()
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: kubernetes-services-endpoint
  namespace: tigera-operator
data:
  KUBERNETES_SERVICE_HOST: "$HOST_IP"
  KUBERNETES_SERVICE_PORT: "6443"
---
apiVersion: operator.tigera.io/v1
kind: APIServer 
metadata: 
  name: default 
spec: {}
```

* Calico version: v3.24.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): k3s v1.23.6+k3s1
* Operating System and version: nixos unstable
