### ISSUE TITLE
Allowing ingress from Kubernetes API via service selector doesn't work

### ISSUE THREAD

**Issue by Tolsto** [projectcalico/calico#6653]
## Expected Behavior

I'd expect the following policy to allow ingress from the Kubernetes API to a mutating webhook service:

```
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: allow-webhook-ingress
  namespace: webhook
spec:
  selector: app = 'webhook'
  types:
    - Ingress
  ingress:
    - action: Allow
      protocol: TCP
      source:
        services:
          name: kubernetes
          namespace: default
      destination:
        ports:
          - 9443

```

## Current Behavior
Requests from the Kubernetes API keep getting blocked.

## Steps to Reproduce (for bugs)
1. Apply the above policy to a mutating webhook service
2. Trigger a request to the webhook service

## Your Environment
* Calico version: 3.21.6
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes 1.23.5
* Operating System and version: AKS
