### ISSUE TITLE
deny traffic to K8s service failed

### ISSUE THREAD

**Issue by KangYingjie0** [projectcalico/calico#6762]
In a K8s cluster, I have created a rule that denies all traffic. But when I execute 'kubectl exec -n user1 user1-deployment1-66cf7699b4-j5hb8 -- curl 172.19.0.1:443', it returns successfully. 
```
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: 100-default
spec:
  order: 100
  selector: all()
  types:
  - Ingress
  - Egress
  ingress:
  - action: Deny
  egress:
  - action: Deny
```
After testing, just when curl the following service, it's abnormal.
1
  namespace: calico-system
  name: calico-typha
  type: ClusterIP
  cluster-ip: 172.19.177.111
  port: 5473
2
  namespace: default
  name: kubernetes
  type: ClusterIP
  cluster-ip: 172.19.0.1
  port: 443

What I found they have in common is: Both of their endpoints are of the “xx.xx.xx.xx:port” form. xx.xx.xx.xx is host ip.

So I wonder why access to these two services cannot be disabled. Is it because they are special services or am I missing something？

## Your Environment

* Calico version: v3.20.6
* Orchestrator version: kubernetes v1.20.5, Just one node.
* Operating System and version: Ubuntu 20.04.4 LTS
