### ISSUE TITLE
Cannot access UDP service via ClsuterIP from the host

### ISSUE THREAD

**Issue by jclab-joseph** [projectcalico/calico#6767]
## Expected Behavior

udp should work.

## Current Behavior

Cannot access UDP service via ClsuterIP from the host.

Failing to query kube-dns from Pods with `hostNetwork: true`.

See https://github.com/kubernetes/kubernetes/issues/112614

## Steps to Reproduce (for bugs)

**pod.yaml**

```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: dns-test
  name: dns-test
  namespace: default
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - sleep 1000
    image: debian:bullseye
    imagePullPolicy: IfNotPresent
    name: dns-test
  dnsPolicy: ClusterFirstWithHostNet
  hostNetwork: true
```

In pod:
```
# nslookup kubernetes.default.svc.cluster.local
;; connection timed out; no servers could be reached
```

If not `hostNetwork: true` it works fine.
Also, if I change server to pod ip in nslookup it works fine.

## Your Environment
* Calico version : v3.18.1
* Orchestrator version (e.g. kubernetes, mesos, rkt):
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.12", GitCommit:"4bf2e32bb2b9fdeea19ff7cdc1fb51fb295ec407", GitTreeState:"clean", BuildDate:"2021-10-27T17:07:18Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```
* Operating System and version: `Ubuntu 20.04 LTS`
* Link to your project (optional):
