### ISSUE TITLE
windows hostprocess: k8s services in CNI only reachable after a pod is scheduled

### ISSUE THREAD

**Issue by mweibel** [projectcalico/calico#6830]
## Expected Behavior
After calico-node-startup, felix and kube-proxy have set up everything, the CNI is fully ready without needing a pod to be running. A service within the CNI can be reached also from the host. 

We don't actually need to reach services from the host, but we noticed the CNI is not fully setup without a non-hostprocess pod to be scheduled.
This issue is closely related to #6829. 

## Current Behavior
When booting up a new windows node, calico startup, felix and kube-proxy do the startup sequence and setup the networking. If no pod is scheduled afterwards, the networking is only half-way set-up though. 

[See Slack for discussion](https://calicousers.slack.com/archives/CF9M1U9RV/p1665060866201719).

Possible explanation by @fasaxc:
Calico creates HNS resources only on demand. Calico supports multiple IP pools but Windows only supports one CIDR per HNS Network. 

## Possible Solution
Adjust startup sequence if possible to set up the necessary bits earlier. 

## Steps to Reproduce (for bugs)
See #6829 for steps to reproduce. The fix from our fork needs to be applied to calico-node-startup to ensure it can actually get to the point where we can observe this behavior. 

## Context
Same as in #6829. 

## Your Environment
* Calico version v3.23.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): k8s 1.24.6 with kubeadm
* Operating System and version: windows

A possible workaround is using a noop pod with a DaemonSet. Example is below. Ensure your windows node are booting up with the following set:
label: `node.example.com/ready-taint=true`
taint: 
```yaml
key: "node.helio.exchange/ready"
value: "false"
effect: "NoSchedule"
````

```

```yaml
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: calico-tainter-script
  namespace: kube-system
  labels:
    app: calico-tainter
data:
  script.ps1: |
    echo "Sleeping for 30s before untainting $env:NODE_NAME"
    Start-Sleep 30
    echo "Done sleeping, untainting node"
    C:\kubectl.exe taint nodes $env:NODE_NAME node.example.com/ready-
    echo "Taint removed"
    echo "Sleeping for 10min until evicting pod"
    Start-Sleep 600
    echo "Removing label so DS pod gets evicted"
    C:\kubectl.exe label nodes $env:NODE_NAME node.example.com/ready-taint-
    echo "Label removed"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: calico-tainter
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: calico-tainter
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: calico-tainter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: calico-tainter
subjects:
  - kind: ServiceAccount
    name: calico-tainter
    namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: calico-tainter
  labels:
    app: calico-tainter
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: calico-tainter
  template:
    metadata:
      labels:
        app: calico-tainter
    spec:
      serviceAccountName: calico-tainter
      tolerations:
        - operator: Exists
          effect: NoSchedule
        - effect: NoExecute
          operator: Exists
      nodeSelector:
        kubernetes.io/os: "windows"
        node.example.org/ready-taint: "true"
      containers:
        - name: main
          image: windows-image-with-kubectl:v0.0.1
          imagePullPolicy: IfNotPresent
          args:
            - /tainter/script.ps1
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: calico-tainter-script
              mountPath: /tainter
      volumes:
        - name: calico-tainter-script
          configMap:
            name: calico-tainter-script
```

Dockerfile for the kubectl image:

```
FROM mcr.microsoft.com/windows/servercore:ltsc2019

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

WORKDIR C:/

RUN curl -o kubectl.exe "https://dl.k8s.io/release/v1.24.0/bin/windows/amd64/kubectl.exe"

ENTRYPOINT ["powershell"]
```
