### ISSUE TITLE
Upgrading from <= 3.22 to >=3.23 using manifests and kubectl apply leaves unwanted flexvol config in place

### ISSUE THREAD

**Issue by nickperry** [projectcalico/calico#6848]
## Expected Behavior
Following the documented procedure to upgrade using manifests with kubectl should not leave behind redundant resources / fields from old versions.

## Current Behavior
After an upgrade to >=3.23, the flexvol-driver init container and flexvol-driver-host volume still exist in the cluster, although we don't want them any more and are not in the 3.23 manifest we applied.

This is only affecting clusters that have not had their Calico install upgraded at least once already. It is due to how kubectl apply works, as described here - https://kubernetes.io/docs/concepts/cluster-administration/manage-deployment/ . Specifically, `the first invocation of kubectl apply will fall back to a two-way diff between the provided input and the current configuration of the resource. During this first invocation, it cannot detect the deletion of properties set when the resource was created. For this reason, it will not remove them.`

## Possible Solution
Use kubectl replace instead of kubectl apply. This worked well for us. The documentation could be changed to use replace instead of apply.

## Steps to Reproduce (for bugs)
1. Start with a fresh cluster with no Calico resources.
2. curl https://projectcalico.docs.tigera.io/archive/v3.21/manifests/calico.yaml -o calico-3.21.yaml
3. curl https://projectcalico.docs.tigera.io/archive/v3.23/manifests/calico.yaml -o calico-3.23.yaml
4. kubectl apply -f calico-3.21.yaml
5. kubectl apply -f calico-3.23.yaml
6. kubectl get ds -n kube-system calico-node -o yaml | less
7. Observe that the flexvol-driver init container and flexvol-driver-host volume still exist although we don't want them any more and are not in the 3.23 manifest we applied -

```
      initContainers:
        # Adds a Flex Volume Driver that creates a per-pod Unix Domain Socket to allow Dikastes
        # to communicate with Felix over the Policy Sync API.
        - name: flexvol-driver
          image: docker.io/calico/pod2daemon-flexvol:v3.21.6
          volumeMounts:
          - name: flexvol-driver-host
            mountPath: /host/driver
          securityContext:
            privileged: true

      volumes:
        # Used to install Flex Volume Driver
        - name: flexvol-driver-host
          hostPath:
            type: DirectoryOrCreate
            path: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds
```

## Context
We were upgrading from Calico 3.21.2 to 3.23.3.

## Your Environment

3.23.3
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes 1.22.
* Operating System and version: RHEL 7
* Link to your project (optional):
