### ISSUE TITLE
calico pod cross-node access failed with ipv6

### ISSUE THREAD

**Issue by cyclinder** [projectcalico/calico#6877]
## Expected Behavior

calico pod cross-node access works with ipv6, Regardless of the tunnel mode（ vxlan always or crosseSubnet or never）

## Current Behavior

calico pod cross-node access failed with ipv6, Regardless of the tunnel mode（ vxlan always or crosseSubnet or never）

## Steps to Reproduce (for bugs)

1. deploy calico by kubespray(v3.23.3)
2. setting dual-stack IP family
3. create two cross-node podA and podB
4. podA failed to ping podB

## Your Environment

* Calico version: v3.23.3
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by song-jiang** [comment]
@coutinhop Could you help?

**Comment by coutinhop** [comment]
@cyclinder I'll try to reproduce this later to investigate, but could you share some more details on your setup? Is this in a cloud, or on-prem, how do your ippool and felixconfig yamls look? I assume the failing ping is to the ipv6 addresses, right? Does IPv4 ping work? (If you could share the yamls from your pods that would be great too)

**Comment by cyclinder** [comment]
Finally, here are the environment variables for calico-node, which I don't see any problem:

```
 containers:
  - env:
    - name: DATASTORE_TYPE
      value: kubernetes
    - name: WAIT_FOR_DATASTORE
      value: "true"
    - name: FELIX_VXLANVNI
      value: "4096"
    - name: FELIX_VXLANPORT
      value: "4789"
    - name: CALICO_NETWORKING_BACKEND
      valueFrom:
        configMapKeyRef:
          key: calico_backend
          name: calico-config
    - name: CLUSTER_TYPE
      valueFrom:
        configMapKeyRef:
          key: cluster_type
          name: calico-config
    - name: CALICO_K8S_NODE_REF
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: CALICO_DISABLE_FILE_LOGGING
      value: "true"
    - name: FELIX_DEFAULTENDPOINTTOHOSTACTION
      value: RETURN
    - name: FELIX_HEALTHHOST
      value: localhost
    - name: FELIX_IPTABLESBACKEND
      value: Legacy
    - name: FELIX_IPTABLESLOCKTIMEOUTSECS
      value: "10"
    - name: CALICO_IPV4POOL_IPIP
      value: "Off"
    - name: FELIX_IPV6SUPPORT
      value: "True"
    - name: FELIX_LOGSEVERITYSCREEN
      value: debug
    - name: CALICO_STARTUP_LOGLEVEL
      value: error
    - name: FELIX_USAGEREPORTINGENABLED
      value: "False"
    - name: FELIX_CHAININSERTMODE
      value: Insert
    - name: FELIX_PROMETHEUSMETRICSENABLED
      value: "False"
    - name: FELIX_PROMETHEUSMETRICSPORT
      value: "9091"
    - name: FELIX_PROMETHEUSGOMETRICSENABLED
      value: "True"
    - name: FELIX_PROMETHEUSPROCESSMETRICSENABLED
      value: "True"
    - name: IP_AUTODETECTION_METHOD
      value: interface=ens192
    - name: IP
      value: autodetect
    - name: IP6_AUTODETECTION_METHOD
      value: interface=ens192
    - name: IP6
      value: autodetect
    - name: NODENAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: FELIX_HEALTHENABLED
      value: "true"
    - name: FELIX_IGNORELOOSERPF
      value: "False"
    - name: CALICO_MANAGE_CNI
      value: "true"
    envFrom:
    - configMapRef:
        name: kubernetes-services-endpoint
        optional: true
    image: quay.m.daocloud.io/calico/node:v3.23.3
```
