### ISSUE TITLE
calico apply bgpPeer Error

### ISSUE THREAD

**Issue by tangjiaxing669** [projectcalico/calico#689]
This is my config file:

```
[root@slave1 ~]# cat bgpPeer.yml 
apiVersion: v1
kind: bgpPeer
metadata:
  scope: node
  node: slave2
  peerIP: 172.30.30.6
  scope: node
  node: slave3
  peerIP: 172.30.30.11
spec:
  asNumber: 64512

[root@slave2 ~]# cat bgpPeer.yml 
apiVersion: v1
kind: bgpPeer
metadata:
  scope: node
  node: slave1
  peerIP: 172.30.30.5
  scope: node
  node: slave3
  peerIP: 172.30.30.11
spec:
  asNumber: 64512

[root@slave3 ~]# cat bgpPool.yml 
apiVersion: v1
kind: bgpPeer
metadata:
  scope: node
  node: slave2
  peerIP: 172.30.30.6
  scope: node
  node: slave1
  peerIP: 172.30.30.5
spec:
  asNumber: 64512
```

```
[root@slave3 ~]# calicoctl node status
Calico process is running.

IPv4 BGP status
+--------------+---------------+-------+----------+--------------------------------+
| PEER ADDRESS |   PEER TYPE   | STATE |  SINCE   |              INFO              |
+--------------+---------------+-------+----------+--------------------------------+
| 172.30.30.11 | node specific | start | 14:50:02 | Idle BGP Error: Bad BGP        |
|              |               |       |          | identifier                     |
+--------------+---------------+-------+----------+--------------------------------+

IPv6 BGP status
No IPv6 peers found.

[root@slave3 ~]# 

[root@slave3 ~]# calicoctl get bgpPeers
SCOPE   PEERIP         NODE     ASN     
node    172.30.30.5    slave1   64512   
node    172.30.30.11   slave3   64512   

[root@slave3 ~]# 
```

`Idle BGP Error: Bad BGP identifier`...

what mean? Please help.
