### ISSUE TITLE
calico-node v3.23 persistently non-ready

### ISSUE THREAD

**Issue by neiljerram** [projectcalico/calico#6901]
calico-node pods are persistently showing as non-ready:
```
neil@glaurung:~$ kubectl get po -n calico-system
NAME                                       READY   STATUS    RESTARTS   AGE
calico-kube-controllers-55dfcffc85-cwqx8   1/1     Running   0          3h58m
calico-node-chnmn                          0/1     Running   0          3h58m
calico-node-cw57s                          0/1     Running   0          3h58m
calico-node-k2jbt                          0/1     Running   0          3h58m
calico-node-n25n9                          0/1     Running   0          3h58m
calico-node-zm22l                          0/1     Running   0          3h58m
calico-typha-6d9db9df67-d78sg              1/1     Running   0          3h58m
calico-typha-6d9db9df67-fcjk9              1/1     Running   0          3h58m
calico-typha-6d9db9df67-jtktm              1/1     Running   0          3h58m
```

describe indicates it's a BIRD problem:
```
neil@glaurung:~$ kubectl describe po calico-node-chnmn -n calico-system
...
  Warning  Unhealthy  4m10s (x1583 over 3h56m)  kubelet  (combined from similar events): Readiness probe failed: 2022-10-25 16:54:22.562 [INFO][25539] confd/health.go 180: Number of node(s) with BGP peering established = 0
calico/node is not ready: BIRD is not ready: BGP not established with 192.168.59.192,192.168.23.192,192.168.103.64,192.168.35.192
```

The BIRD IP addresses look surprising because the node IPs in this cluster are 10.128.1/24, and the pod CIDR is 192.168/16.

Looking at YAML for ...-node-2, which corresponds to calico-node-chnmn:
```
metadata:
  annotations:
    kubeadm.alpha.kubernetes.io/cri-socket: /var/run/dockershim.sock
    node.alpha.kubernetes.io/ttl: "0"
    projectcalico.org/IPv4Address: 192.168.165.0/32
    projectcalico.org/IPv4VXLANTunnelAddr: 192.168.165.0
```

So 192.168.165.0 was assigned as the VXLAN tunnel address for the node, and then that address was auto-detected as the node's canonical IP - which is what gets passed through to BIRD.

Then, shortly after, logs indicate that the vxlan.calico device was deleted, and the 192.168.165.0 address disappeared, and that causes everything to stop working.
