### ISSUE TITLE
Calico vxlan interface missing on custom k8s cluster in Azure

### ISSUE THREAD

**Issue by octavteodorescu** [projectcalico/calico#6920]
The current deployment is a vanilla kubernetes, using crio runtime and calico, deployed on Azure virtual machines.

Calico deployment is via helm, using these values:
```
      installation:
        cni:
          type: Calico
        calicoNetwork:
          ipPools:
          - blockSize: 26
            cidr: 10.244.0.0/16
            encapsulation: VXLANCrossSubnet
            natOutgoing: Enabled
            nodeSelector: all()
```
The problem was identified as a consequence of some mysql pods having intermittent issues resolving DNS. Following some digging around, I've seen that the calico-nodes (all) have pretty much one error (or set of errors):
```
2022-10-29 15:26:40.791 [INFO][57] felix/route_table.go 1200: Failed to access interface because it doesn't exist. error=Link not found ifaceName="vxlan.calico" ifaceRegex="^vxlan.calico$" ipVersion=0x4 tableIndex=0
2022-10-29 15:26:40.791 [INFO][57] felix/route_table.go 1268: Failed to get interface; it's down/gone. error=Link not found ifaceName="vxlan.calico" ifaceRegex="^vxlan.calico$" ipVersion=0x4 tableIndex=0
2022-10-29 15:26:40.791 [ERROR][57] felix/route_table.go 1035: Failed to get link attributes error=interface not present ifaceRegex="^vxlan.calico$" ipVersion=0x4 tableIndex=0
2022-10-29 15:26:40.792 [INFO][57] felix/route_table.go 618: Interface missing, will retry if it appears. ifaceName="vxlan.calico" ifaceRegex="^vxlan.calico$" ipVersion=0x4 tableIndex=0
```

Several tests and redeployments later I've figured out the vxlan interface on the k8s nodes gets created for a few seconds when calico is deployed, but then disappears.. 

I'm hoping there's something I'm missing rather than a bug, so it's easier to resolve... but please mind the fact that this is my first exposure to calico, hence there may be some misses. 

## Expected Behavior
The vxlan interface should not simply disappear without any trace of such operation in the logs

## Current Behavior
Due to whatever root cause, all pods (calico-node, typha, api, tiger operator) are up and running, but something is off with respect to the overall deployment... 

## Possible Solution
None that I know. I've tried multiple options/ settings without success (see below).

## Steps to Reproduce (for bugs)
I'm happy to provide the steps to preproduce, but it's just going to take a bit of time to do that, thus putting here the high-level ones and on request I can provide more:
- deploy Azure objects:
  - 1 vnet with 2 subnets
  - 1 nat gateway
  - 3 RedHat linux VMs in one subnet (as the k8s master nodes)
  - 2 RedHat linux VMs in the other subnet (as k8s master nodes)
  - 1 internal load balancer (for k8s api)
  - on the 3 RedHat VMs haproxy + keepalived are deployed for load balancing/ redundancy of k8s api
  - then configure OSes, deploy CRI-O, kubeadm, kubelet & kubectl
  - deploy calico via helm
- Should be mentioned that there's no network security group deployed (securing the az networking will be done through different means at a later point). 
- Unless there's something fundamental that I've missed the documented prerequisites have been implemented (such as setting network manager to ignore calico interfaces, which have been double checked by nmcli dev status)

## Context
The end goal of this set up is to have an application deployed on a vanilla Kubernetes cluster that's agnostic enough to be ported to any other cloud or infrastructure (hence the reason AKS is not used).
Calico seems to be seen as one of the defacto platforms when it comes to kubernetes networking, providing a solid experience without the need to continuously tweak and fix it (or so this was the story I've heard as well as read that lead me to select calico).
There's also going to be a requirement of network policies to which Calico maps to.

## Your Environment
Versions:
- OSes: Red Hat Enterprise Linux release 8.6 (Ootpa)
- Cri-O: 1.22.5 (I have tried the same deployment with Cri-O 1.25, as well as with containerd, with the same result)
- K8S (vanilla): 1.22.15
- Helm: 3.10.1
- Calico: 3.24.3

A few additional aspects for your information:
- following the read with this article: https://mihail-milev.medium.com/no-pod-to-pod-communication-on-centos-8-kubernetes-with-calico-56d694d2a6f4 I have blacklisted the iptables module, though I haven't changed any variables in the calico node, as looking a bit at the go code and a release note it seems it is not needed anymore
- selinux is set to permissive at this moment, but the plan is to comeback to enforcing
- k8s cluster initialisation config file (for kubeadm) is:
```
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
nodeRegistration:
  criSocket: "unix:///var/run/crio/crio.sock"
localAPIEndpoint:
  advertiseAddress: "0.0.0.0"
  bindPort: 6443
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
controlPlaneEndpoint: "some_name:8443"
kubernetesVersion: v1.22.15
clusterName: kx-k8s-cluster
networking:
  serviceSubnet: "10.96.0.0/16"
  podSubnet: "10.244.0.0/16"
apiServer:
  certSANs:
    - some_name
    - ....
    - some_nameX
  extraArgs:
    apiserver-count: "3"
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: systemd
```
- have tried deploying with BGP enabled and disabled. This current build has it enabled and the node status shows as follows:
```
sudo /usr/local/bin/calicoctl node status
Calico process is running.

IPv4 BGP status
+----------------+-------------------+-------+----------+--------------------------------+
|  PEER ADDRESS  |     PEER TYPE     | STATE |  SINCE   |              INFO              |
+----------------+-------------------+-------+----------+--------------------------------+
| 10.244.104.192 | node-to-node mesh | start | 15:25:46 | Active Socket: Connection      |
|                |                   |       |          | closed                         |
| 10.244.24.192  | node-to-node mesh | start | 15:25:46 | Active Socket: Connection      |
|                |                   |       |          | closed                         |
| 10.244.100.64  | node-to-node mesh | start | 15:25:46 | Active Socket: Connection      |
|                |                   |       |          | closed                         |
| 10.244.140.128 | node-to-node mesh | start | 15:25:52 | Active Socket: Connection      |
|                |                   |       |          | closed                         |
+----------------+-------------------+-------+----------+--------------------------------+

IPv6 BGP status
No IPv6 peers found.

```

See attached the diagnostics collected using calicoctl.

[calico-diagnostics.tar.gz](https://github.com/projectcalico/calico/files/9894079/calico-diagnostics.tar.gz)

This is driving me crazy for a few days, so thanks in advance for any help on the matter!
