### ISSUE TITLE
Location of imagePullSecrets deviates from documentation

### ISSUE THREAD

**Issue by gregwhorley** [projectcalico/calico#6969]
## Expected Behavior

The calico InstallationSpec doc lists an `imagePullSecrets` property that accepts a list of objects: https://projectcalico.docs.tigera.io/reference/installation/api#operator.tigera.io/v1.InstallationSpec

So I add it to my values override yaml along with the other properties:

```
installation:
  kubernetesProvider: EKS
  cni:
    ipam:
      type: AmazonVPC
    type: AmazonVPC
  flexVolumePath: None
  nodeMetricsPort: 9091
  nodeUpdateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  variant: Calico
  imagePullSecrets:
    - name: docker-regcred
```

## Current Behavior

When I run a test render via `helm template -g calico/tigera-operator -f values.yaml --debug` the `Installation` resource lists an `imagePullSecrets` property with an empty list value:

```
# Source: tigera-operator/templates/crs/custom-resources.yaml
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  cni:
    ipam:
      type: AmazonVPC
    type: AmazonVPC
  flexVolumePath: None
  imagePullSecrets: []
  kubernetesProvider: EKS
  nodeMetricsPort: 9091
  nodeUpdateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  variant: Calico
```

[There is another `imagePullSecrets` property listed in the helm chart README](https://github.com/projectcalico/calico/tree/master/charts/tigera-operator#values-reference) that will populate the `imagePullSecrets` value inside of `Installation` when defined in my values.yaml file.

```
installation:
  kubernetesProvider: EKS
  cni:
    ipam:
      type: AmazonVPC
    type: AmazonVPC
  flexVolumePath: None
  nodeMetricsPort: 9091
  nodeUpdateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  variant: Calico
imagePullSecrets:
  docker-regcred: ""
```

This will render the `Installation` resource with the `imagePullSecrets`

```
# Source: tigera-operator/templates/crs/custom-resources.yaml
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  cni:
    ipam:
      type: AmazonVPC
    type: AmazonVPC
  flexVolumePath: None
  imagePullSecrets:
  - name: docker-regcred
  kubernetesProvider: EKS
  nodeMetricsPort: 9091
  nodeUpdateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  variant: Calico
```

## Possible Solution

The helm chart template `custom-resources.yaml` actively overwrites anything within the scope of `installation.imagePullSecrets` with keys from the `.Values.imagePullSecrets` map: https://github.com/projectcalico/calico/blob/c68b107cb0e19ed029d74c14cd7893bcb00e8eb3/charts/tigera-operator/templates/crs/custom-resources.yaml#L1-L8

It seems like, per the InstallationSpec, the template should pull in secret names from within the appropriate scope under `installation`.

## Steps to Reproduce (for bugs)

1. `helm repo add calico https://projectcalico.docs.tigera.io/charts && helm repo update`
2. create `values.yaml` file with contents from Expected Behavior
3. `helm template -g calico/tigera-operator -f values.yaml --debug`
4. edit `values.yaml` file with `imagePullSecrets` from Current Behavior
5. `helm template -g calico/tigera-operator -f values.yaml --debug`

## Context

I'm trying to inject an `imagePullSecret` into each pod spec that's created by the operator.

## Your Environment

* Calico version: 3.22.4
* Orchestrator version (e.g. kubernetes, mesos, rkt): EKS v1.21
* Operating System and version: Amazon Linux
* Link to your project (optional):

**Comment by caseydavenport** [comment]
I'm not 100% sure I understand - it sounds like when you use the values.yaml `imagePullSecrets` configuration setting, everything works as expected - is that right?

If so, maybe the fix is just better documentation in our values.yaml and chart README to explain how this is meant to work?

**Comment by gregwhorley** [comment]
I was just confused about the chart's logic around gathering `imagePullSecrets`. The `tigera-operator` [API reference shows an `imagePullSecret` property underneath the `Installation` resource ](https://projectcalico.docs.tigera.io/reference/installation/api#operator.tigera.io/v1.InstallationSpec) so I thought the chart would adhere to that contract. Instead, the chart relies on an `imagePullPolicy` property in the root scope to fill `imagePullSecrets` underneath `Installation`.

I think it's a combination of a vague description for `imagePullSecrets` and the [values reference in the readme](https://github.com/projectcalico/calico/tree/master/charts/tigera-operator#values-reference) has a silghtly misleading comment about how it conforms to the API spec.

```
# Image pull secrets to provision for pulling images from private registries.
# This field is a map of desired Secret name to .dockerconfigjson formatted data to use for the secret.
imagePullSecrets: {}

# Configures general installation parameters for Calico. Schema is based
# on the operator.tigera.io/Installation API documented
# here: https://projectcalico.docs.tigera.io/reference/installation/api#operator.tigera.io/v1.InstallationSpec
installation:
  enabled: true
  kubernetesProvider: ""
```

I can try editing the readme with revised language around the `imagePullSecrets` value.
