### ISSUE TITLE
Configure log levels for calico-node

### ISSUE THREAD

**Issue by cheeryfella** [projectcalico/calico#7018]
Would like to be able to configure the log level of calico nodes deployed via the tigera operator

The relevant environment variables appear to be:

- CALICO_STARTUP_LOGLEVEL
- BGP_LOGSEVERITYSCREEN
- FELIX_LOGSEVERITYSCREEN

## Expected Behavior
Be able to set these values on the calico-node daemonset for the container environment variables via the tigera-operator helm chart.

## Current Behavior
based on the code in `https://github.com/tigera/operator/blob/master/pkg/render/node.go` it would appear non of these are available to be set.

## Context
Unable to change the log level of the calico-node

**Comment by lwr20** [comment]
In an operator install, you set these config parameters using the `felixconfiguration` object.

https://projectcalico.docs.tigera.io/reference/resources/felixconfig

**Comment by caseydavenport** [comment]
> CALICO_STARTUP_LOGLEVEL

This one is not configurable by the operator to my knowledge, so requires some code work.

The others are available through the FelixConfiguration and BGPConfiguration APIs.

**Comment by Chili-Man** [comment]
@caseydavenport I tried @lwr20's suggestion by creating a FelixConfiguration like below:

```yaml
---
apiVersion: projectcalico.org/v3
kind: FelixConfiguration
metadata:
  name: log-level

spec:
  logSeverityFile: Error
  logSeverityScreen: Error
  logSeveritySys: Error
```

However, I don't observe the log level being reduced on the `calico-node` daemonset. It works when I directly modify the existing default resource, but I don't want to particularly do that since I want to manage the configuration through Helm as well.  How does it work alongside the default configuration?
