### ISSUE TITLE
Unexpected default behavior of workload to host traffic

### ISSUE THREAD

**Issue by log1cb0mb** [projectcalico/calico#7056]
According to documentation [Default behavior of workload to host traffic](https://projectcalico.docs.tigera.io/security/protect-hosts#default-behavior-of-workload-to-host-traffic), traffic should be by default blocked however in Calico installations, the corresponding config is set to `Accept` which I believe comes from some kubernetes requirement.

**NOTE:** The documentation page [Protect Hosts](https://projectcalico.docs.tigera.io/security/protect-hosts) also seems to just wrong as it goes completely against the default installation/behavior as mentioned default installation sets FELIX_DEFAULTENDPOINTTOHOSTACTION` to `ACCEPT`

## Expected Behavior
With `FELIX_DEFAULTENDPOINTTOHOSTACTION` set to `ACCEPT` by default it should however be possible to still use Calico policy for e.g GlobalNetworkPolicy for protecting host Endpoints to control such traffic i.e from workload to its local host/node. 

## Current Behavior
The current behavior seems to be that traffic from workload to local host/node or its endpoint does not match against any policy at all hence even if blocking such traffic is required, it gets through regardless of the policy configured.

## Steps to Reproduce (for bugs)
1. Default calico manifest or tigera based installation
2. manual or automatic hostendpoints enable in order to apply GlobalNetworkPolicy against node endpoints
3. Create policy for example:
```
apiVersion: crd.projectcalico.org/v1
kind: GlobalNetworkPolicy
metadata:
  name: default-worker-policy
spec:
  selector: has(node-role.kubernetes.io/worker)
  order: 1
  ingress:
    - action: Allow
      protocol: TCP
      source:
        nets:
          - "<only external kubernetes networks OR anything other than workload/pod network>"
      destination:
        ports: [22]
```
5. Try reaching SSH/22 port from a normal workload using Pod CIDR (not `hostNetwork`) to node hostendpoint/IP address

## Context
The idea is to lock down traffic to ports on kubernetes nodes including any kubernetes workload not allowed to reach kubernetes node ports until explicitly allowed

Related discussion on Slack channel:
https://calicousers.slack.com/archives/CPT3EH2LC/p1669464638253439

## Your Environment
* Calico version: 3.23.5 (tigera-operator based installation) with eBPF dataplane
* Orchestrator version: Kubernetes
* Operating System and version: RHEL 8.5/8.6
* Link to your project (optional):
