### ISSUE TITLE
arm64 calico ebpf dataplane enabled but not supported by kernel

### ISSUE THREAD

**Issue by wahahawasabi** [projectcalico/calico#7058]
I am trying to enable calico ebpf dataplane on an arm64 device. I managed to modify the kernel and include all the required configs to get calico working in the normal mode, it was able to install via the manifest, or via the operator. No issues there. 

However, when I followed the [tutorial](https://projectcalico.docs.tigera.io/maintenance/ebpf/enabling-ebpf) to install it in ebpf mode, and disable kubeproxy, even though `calico node shows 1/1 Running`, kubectl logs shows:
```
[ERROR][65] felix/daemon.go 354: BPF dataplane mode enabled but not supported by the kernel.  Disabling BPF mode.
```

The below is the set of configs I have enabled in the kernel:
```
jakew@desktop:~$ cat config | grep BPF
CONFIG_CGROUP_BPF=y
CONFIG_BPF=y
CONFIG_BPF_SYSCALL=y
CONFIG_BPF_JIT_ALWAYS_ON=y
# CONFIG_BPF_UNPRIV_DEFAULT_OFF is not set
CONFIG_IPV6_SEG6_BPF=y
CONFIG_NETFILTER_XT_MATCH_BPF=y
CONFIG_BPFILTER=y
CONFIG_BPFILTER_UMH=m
CONFIG_NET_CLS_BPF=y
CONFIG_NET_ACT_BPF=y
CONFIG_BPF_JIT=y
CONFIG_BPF_STREAM_PARSER=y
CONFIG_LWTUNNEL_BPF=y
CONFIG_HAVE_EBPF_JIT=y
CONFIG_BPF_EVENTS=y
# CONFIG_TEST_BPF is not set
```

There were no other errors to note. 

## Expected Behavior
calico node in ebpf mode should have no errors or warnings. 

## Current Behavior
```
[ERROR][65] felix/daemon.go 354: BPF dataplane mode enabled but not supported by the kernel.  Disabling BPF mode.
```

## Steps to Reproduce (for bugs)
1. Install the operator: `kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.24.5/manifests/tigera-operator.yaml`
2. Add this to the `custom-resource.yaml` file:
    ```
       kind: ConfigMap
       apiVersion: v1
       metadata:
         name: kubernetes-services-endpoint
         namespace: tigera-operator
       data:
         KUBERNETES_SERVICE_HOST: "<API server host>"  # obtained from kubectl cluster-info
         KUBERNETES_SERVICE_PORT: "<API server port>"  # obtained from kubectl cluster-info
   ```
4. kubectl apply -f custom-resource.yaml
5. refresh calico-node by deleting the pod. 
6.  kubectl logs calico-node-xx -n calico-system | grep ERROR

## Your Environment

* Calico version 3.25.4
* Orchestrator version kubeadm 1.25.4
* Operating System and version: ubuntu jammy, kernel version 4.19.232
