### ISSUE TITLE
help: is there any way to customize the toleration config of csi-node-driver please

### ISSUE THREAD

**Issue by zoezhangmattr** [projectcalico/calico#7070]
using tigera-operator to install calico, version 3.24.1
we have different taints for each node groups in eks cluster
after installation. calic-node-driver cant be tolerated into those node groups, because the tolerations of it.
i dont find a way to config it. 
```yaml
tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
```
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version : 3.24.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): eks kubernetes 1.21
* Operating System and version:
* Link to your project (optional):
