### ISSUE TITLE
kubernetes endpoints cannot reached after upgrade

### ISSUE THREAD

**Issue by nancykyo** [projectcalico/calico#713]
I have a k8s cluster of  3 nodes, call them node[1-3], node1 is master
k8s version: kuberadm 1.5.1
previous:
```
image: quay.io/calico/node:v1.0.0
image: calico/cni:v1.5.5
image: calico/kube-policy-controller:v0.5.1
image: calico/ctl:v1.0.0
```
after upgrading
```
image: quay.io/calico/node:v1.1.0
image: quay.io/calico/cni:v1.6.1
image: quay.io/calico/kube-policy-controller:v0.5.4
```
ip pool
```
# calicoctl get pool -o yaml
- apiVersion: v1
  kind: ipPool
  metadata:
    cidr: 10.86.244.0/22
  spec:
    nat-outgoing: true
```
endpoints
```
kubectl get ep jenkins
NAME      ENDPOINTS           AGE
jenkins   10.86.246.68:8080   17h
```
iptables on node 2
```
iptables -t nat -L | grep  10.86.246.68
KUBE-MARK-MASQ  all  --  10.86.246.68         anywhere             /* default/jenkins:http */
DNAT       tcp  --  anywhere             anywhere             /* default/jenkins:http */ tcp to:10.86.246.68:8080
```
and it's not a policy or profile problem,  for 
endpoints on node3 is accessible.
`telnet 10.86.246.68 8080`  and `ping 10.86.246.68` is ok

can you help indicating how to debug this?
