### ISSUE TITLE
Log spew storm when vxlanMode=Never

### ISSUE THREAD

**Issue by jtackaberry** [projectcalico/calico#7162]
My installation is using BIRD and I had intended to disable VXLAN.  However given the following IPPool:

```
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: default-ipv4-ippool
spec:
  allowedUses:
  - Workload
  - Tunnel
  blockSize: 26
  cidr: 10.2.0.0/16
  ipipMode: Never
  natOutgoing: true
  nodeSelector: all()
  vxlanMode: Never
```

calico-node pods spew this log line several dozen times per second:

```
2023-01-07 01:20:43.357 [INFO][82] felix/route_table.go 1159: Failed to access interface because it doesn't exist. error=Link not found ifaceName="vxlan.calico" ifaceRegex="^vxlan.calico$" ipVersion=0x4 tableIndex=0
``` 

Everything works fine otherwise.  BIRD is doing its thing, and the appropriate routes are in place.

If I patch the IPPool to set `vxlanMode` to `Always`, this causes the vxlan.calico interface to be created.  After that point, I am able to set it back to `Never` and calico-node is quiet until the next node reboot.

## Expected Behavior

My expectation was that vxlan.calico interface wouldn't be created -- and it isn't, so this expectation was met -- and that calico-node would be perfectly fine with that.

## Current Behavior

Rampant complaining about the absence of vxlan.calico for no discernible reason.

## Possible Solution

Because all my nodes are currently on the same subnet, I can set vxlanMode to CrossSubnet.  This causes the vxlan.calico interface to be created, but doesn't otherwise pass traffic over this interface.

## Steps to Reproduce (for bugs)

1. Set calico_backend to `bird`
2. Set `vxlanMode: Never` on all IPPools
3. Reboot node if vxlan.calico interface already exists (as the problem only manifests when the interface doesn't exist)

## Your Environment

* Calico version: v3.23.5 (default with microk8s v1.25) although I did also briefly try v3.24.5 and saw the same behavior from calico-node
* Orchestrator version: Microk8s v1.25
* Operating System and version: Ubuntu 22.04.1
