### ISSUE TITLE
Create kubernetes-service-endpoint config map with helm

### ISSUE THREAD

**Issue by willzhang** [projectcalico/calico#7164]
## Expected Behavior
now it not possible to auto enable ebpf for calico, hope support Create kubernetes-service-endpoint config map with helm.

## Current Behavior
must create configmap manual with https://projectcalico.docs.tigera.io/maintenance/ebpf/install#create-a-suitable-cluster

## Possible Solution
add configmap to helm charts 
```
kubectl apply -f - <<EOF
kind: ConfigMap
apiVersion: v1
metadata:
  name: kubernetes-services-endpoint
  namespace: tigera-operator
data:
  KUBERNETES_SERVICE_HOST: "<API server host>"
  KUBERNETES_SERVICE_PORT: "<API server port>"
EOF
```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version v3.24.5
* Orchestrator version (e.g. kubernetes, mesos, rkt):  kubernetes v1.25.3
* Operating System and version:  ubuntu 22.04
* Link to your project (optional):
