### ISSUE TITLE
calico-kube-controllers with K8S_INSECURE_SKIP_TLS_VERIFY

### ISSUE THREAD

**Issue by christiancadieux** [projectcalico/calico#7191]
on 3.24.5

I added a configmap to configure eBPF without kube-proxy :
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: kubernetes-services-endpoint
  namespace: tigera-operator
data:
  KUBERNETES_SERVICE_HOST: "..."
  KUBERNETES_SERVICE_PORT: "6443"
```
then I get this error:
```
2023-01-14 21:08:57.452 [INFO][6] main.go 134: Failed to initialize datastore error=Get "https://anvil2-vpis-sit-01....net:6443/apis/crd.projectcalico.org/v1/clusterinformations/default": x509: certificate is valid for localhost, kubernetes, kubernetes.default, kubernetes.default.svc, kubernetes.default.svc.cluster.local, *, not anvil2-vpis-sit-01.....net
```

then, if I add ENV K8S_INSECURE_SKIP_TLS_VERIFY = true to calico-kube-controllers deployment to avoid this error:

the pod refuse to start:
```
2023-01-14 21:09:17.362 [FATAL][6] main.go 116: Failed to start error=failed to build Calico client: invalid configuration: default cluster has no server defined
```

## Expected Behavior
should work

## Current Behavior
pod fails

## Context
need to configure eBPF without kube-proxy

## Your Environment
3.24.5
