### ISSUE TITLE
Stop tigera-operator writing back to `spec` of CRDs

### ISSUE THREAD

**Issue by mkjpryor** [projectcalico/calico#7228]
The tigera-operator re-writes the spec of some of the CRDs that it watches, in particular the `Installation` CRD.

## Expected Behavior

The `spec` of CRDs remain as given.

## Current Behavior

The `spec` of some CRDs (in particular `Installation`) is updated by tigera-operator.

## Possible Solution

Apply defaults to the in-memory representation only.

## Steps to Reproduce (for bugs)

Use this Argo manifest to deploy `tigera-operator`:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cni-calico
spec:
  destination:
    name: my-cluster
    namespace: tigera-operator
  project: default
  source:
    repoURL: https://projectcalico.docs.tigera.io/charts
    chart: tigera-operator
    targetRevision: v3.24.5
    helm:
      releaseName: cni-calico
      values: |
        installation:
          calicoNetwork:
            bgp: Disabled
            ipPools:
              - cidr: 172.16.0.0/13
                encapsulation: VXLAN
            nodeAddressAutodetectionV4:
              kubernetes: NodeInternalIP
          registry: docker.io
        tigeraOperator:
          registry: quay.io
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - CreateNamespace=true
    - ServerSideApply=true
```

## Context

This causes tools like Argo CD, that rely on diffing to detect changes that need to be applied, to enter an infinite apply loop where they are fighting with the tigera-operator.

## Your Environment

* Calico version: 3.24.5
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes 1.25
* Operating System and version: ubuntu 20.04
* Link to your project (optional):
