### ISSUE TITLE
K8S-API blocked to reach Webhooks

### ISSUE THREAD

**Issue by hans-fischer** [projectcalico/calico#7242]
I'm struggle to find a good way to enable the K8S-API-Server to reach whatever pod it need to reach.
In latest research I found out that the Traffic from the K8S-API ist coming from the CNI-Bridge Interface the API-Server belongs to.
API-Server (by kubeadm) is kinda special Pod, deployed by Node-Minifest, running with host-network but need to reach pods in order to fulfill webhook-request.

## Expected Behavior
I looking for an example Calico-GlobalNetworkPolicy to allow K8S-API to connect to all pods.

## Current Behavior

I tried:
```
apiVersion: crd.projectcalico.org/v1
kind: GlobalNetworkPolicy
metadata:
  name: "kube-api-reach-all"
spec:
  order: 1
  namespaceSelector: "all()"
  selector: "all()"
  ingress:
    - action: "Allow"
      source:
        nets:
          - "10.12.3.2/32"  # Node-IP
```
This is already kinda tricky because I have to lookup the exact NodeIPs. (not hard but kinda wired in such a dynamic environment)

This solution works for traffic flowing to the K8S-API, but traffic from the K8S-API is sth else. The traffic only come trough when I allow Traffic from the IPAMBlock host-address.

To lookup this information is also not that hard, but I feels not good to lookup all IPAMBlocks from a controlplane-node and also allow all traffic coming from that IP.

## Working solution (Don't feel right)

```
apiVersion: crd.projectcalico.org/v1
kind: GlobalNetworkPolicy
metadata:
  name: "kube-api-reach-all"
spec:
  order: 1
  namespaceSelector: "all()"
  selector: "all()"
  ingress:
    - action: "Allow"
      source:
        nets:
          - "10.252.80.0/32" # First address in IPAM-Block 

```

## Context
**It would be very nice to have a solution from calico to separate API-Server-traffic from everything else.**

## Your Environment
* Calico version : v3.25.0 (deployed by helm chart)
* Orchestrator version : K8S 1.24.8
* Operating System and version: Ubuntu 22.04.1 LTS

```
FelixConfiguration:
  bpfLogLevel: 'Off'
  floatingIPs: Disabled
  healthPort: 9099
  ipipEnabled: true
  logSeverityScreen: Info
  reportingInterval: 0s
  wireguardEnabled: false
```
