### ISSUE TITLE
Basic egress destination selectors not working as expected?

### ISSUE THREAD

**Issue by zarenner** [projectcalico/calico#7266]
Using Calico for the first time, and egress destination-selecting allow rules aren't working as I'd expect. I'm guessing it's my understanding of how Calico selectors work or a silly misconfiguration rather than a bug, since this seems like such basic functionality.

## Expected Behavior
Given a policy like:
```
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: allow-egress-to-all-namespaces-nginx-pods
  namespace: default
spec:
  types:
  - Egress
  egress:
  - action: Allow
    destination:
      namespaceSelector: all()
      selector: app == 'nginx'
```

should be able to connect from a pod in `default` namespace to a pod labeled `app: nginx` in namespace `foo`.

## Current Behavior
* `selector: all()` allows traffic
* `selector: app == 'nginx'` blocks traffic
* `selector: app != 'nginx'` also blocks traffic
* `selector: app != 'other'` allows traffic - that is, traffic is allowed if the selector is a negative match of other pods

## Steps to Reproduce (for bugs)
Test repo at https://github.com/zarenner/calico-test
Test run at https://github.com/zarenner/calico-test/actions/runs/4067684927/jobs/7005328105

Example:
```
*** Allow egress to namespaceSelector: all(), selector: app == 'nginx' ***
Successfully deleted 15 resource(s)
Successfully applied 1 'NetworkPolicy' resource(s)
❌ Blocked (but should have connected)

*** Allow egress to namespaceSelector: all(), selector: app != 'nginx' ***
Successfully deleted 15 resource(s)
Successfully applied 1 'NetworkPolicy' resource(s)
✅ Blocked

*** Allow egress to namespaceSelector: all(), selector: app == 'other' ***
Successfully deleted 15 resource(s)
Successfully applied 1 'NetworkPolicy' resource(s)
✅ Blocked

*** Allow egress to namespaceSelector: all(), selector: app != 'other' ***
Successfully deleted 15 resource(s)
Successfully applied 1 'NetworkPolicy' resource(s)
✅ Connected
```

The tests with specific namespaceSelector, or absent namespaceSelector are similarly odd. It acts like doesn't know that the destination pod is labeled `app: nginx`, but somehow knows it doesn't match `app: other`

## Context
* Trying to write a simple policy to allow all pods in a specific namespace to egress to selected pods in any namespace.
* Started with k8s `NetworkPolicy` and when that also didn't work as I expected switched to Calico `NetworkPolicy`

## Your Environment
*  minikube v1.29.0 on Ubuntu 20.04 (docker/amd64)
    * started with `minikube start --cni=calico` 
    * single-node cluster
    * Kubernetes v1.26.1 on Docker 20.10.23
* Calico: v3.24.5
