### ISSUE TITLE
Kubernetes Service NodePort not working correct on Windows Node 

### ISSUE THREAD

**Issue by dnsdhcp** [projectcalico/calico#7305]
I was creating pod and service using the following YAML.

``` YAML
apiVersion: v1
kind: Pod
metadata:
  name: "myiis"
  namespace: default
  labels:
    app: "myiis"
spec:
  containers:
  - name: myiis
    image: "mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2019"
    ports:
    - containerPort: 80
      name: http
  nodeSelector:
    kubernetes.io/os: windows
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: myiis
spec:
  ports:
    - port: 80
      nodePort: 31080
      targetPort: 80
  selector:
    app: myiis
  type: NodePort
```

Th Pod is on winnode1.

```
[root@control ~]# kubectl get pods -o wide
NAME      READY   STATUS    RESTARTS   AGE   IP               NODE       NOMINATED NODE   READINESS GATES
myiis     1/1     Running   0          12s   192.168.15.71    winnode1   <none>           <none>
```

```
[root@control ~]# kubectl get svc
NAME         TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
kubernetes   ClusterIP   10.96.0.1       <none>        443/TCP        47h
myiis        NodePort    10.108.79.160   <none>        80:31080/TCP   71s
```

I can't access myiis service on the other windows nodes that not running the pod.

``` BASH
curl -I http://winnode1:31080 # HTTP/1.1 200 OK
curl -I http://winnode2:31080 # Connection timed out
curl -I http://winnode3:31080 # Connection timed out
curl -I http://control:31080 # HTTP/1.1 200 OK
curl -I http://node1:31080 # HTTP/1.1 200 OK
```

After I creating pod on every windows node using the following YAML.

``` YAML
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myiis
  namespace: default
  labels:
    app: myiis
spec:
  selector:
    matchLabels:
      app: myiis
  replicas: 3
  template:
    metadata:
      labels:
        app: myiis
    spec:
      containers:
      - name: myiis
        image: "mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2019"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: myiis
      nodeSelector:
        kubernetes.io/os: windows
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: myiis
spec:
  ports:
    - port: 80
      nodePort: 31080
      targetPort: 80
  selector:
    app: myiis
  type: NodePort
```

```
[root@control ~]# kubectl get pods -o wide
NAME                     READY   STATUS    RESTARTS   AGE   IP               NODE       NOMINATED NODE   READINESS GATES
myiis-656b4bdc44-4bdqj   1/1     Running   0          9s    192.168.74.135   winnode2   <none>           <none>
myiis-656b4bdc44-4d8mk   1/1     Running   0          9s    192.168.15.72    winnode1   <none>           <none>
myiis-656b4bdc44-vp2bg   1/1     Running   0          9s    192.168.87.200   winnode3   <none>           <none>
```

```
[root@control ~]# kubectl get svc
NAME         TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
kubernetes   ClusterIP   10.96.0.1       <none>        443/TCP        47h
myiis        NodePort    10.108.79.160   <none>        80:31080/TCP   71s
```

I can access myiis server on every node.

``` BASH
curl -I http://winnode1:31080 # HTTP/1.1 200 OK
curl -I http://winnode2:31080 # HTTP/1.1 200 OK
curl -I http://winnode3:31080 # HTTP/1.1 200 OK
curl -I http://control:31080 # HTTP/1.1 200 OK
curl -I http://node1:31080 # HTTP/1.1 200 OK
```

## Expected Behavior

Access myiis service on the other windows nodes even node not running the pod.

## Your Environment

* Calico version: v3.24.5

```
[root@control ~]# calicoctl get ippool -o wide
NAME                  CIDR             NAT    IPIPMODE   VXLANMODE   DISABLED   DISABLEBGPEXPORT   SELECTOR
default-ipv4-ippool   192.168.0.0/16   true   Never      Always      false      false              all()
```

| Hostname  | Operation System | Kubernetes Version | Container Runtime |
| ------------- | ------------- | ------------- | ------------- |
| control  | Red Hat Enterprise Linux 8.7 (Ootpa) | v1.26.1 | containerd v1.6.14 | 
| node1  | Red Hat Enterprise Linux 8.7 (Ootpa)  | v1.26.1 | containerd v1.6.14 | 
| winnode1 | Windows Server 2019 - Version 1809 (OS Build 17763.3887) | v1.26.0 | containerd v1.6.14 | 
| winnode2  | Windows Server 2019 - Version 1809 (OS Build 17763.3887)  | v1.26.0 | containerd v1.6.14 | 
| winnode3  | Windows Server 2019 - Version 1809 (OS Build 17763.3887)  | v1.26.0 | containerd v1.6.14 |
