### ISSUE TITLE
remove failsafe inbound rule for port 22

### ISSUE THREAD

**Issue by alirezaDavid** [projectcalico/calico#734]
Hi
I removed failsafe inbound rule for port 22 with calicoctl, it's seems ALLOW 22 rules removed from iptables 

```
Chain cali-failsafe-in (0 references)
 pkts bytes target     prot opt in     out     source               destination         

```

but it's seems ssh port still open because I can ssh to machine.
this is our policy file
```
cat << EOF | calicoctl apply -f -
- apiVersion: v1
  kind: policy
  metadata:
    name: webserver
  spec:
    selector: "all()"
    order: 0
    ingress:
    - action: allow
      protocol: tcp
      destination:
        ports: [80,3306, 6379]
    - action: allow
      protocol: tcp
      source:
        net: "138.68.*.*"
      destination:
        ports: [22]
    - action: allow
      protocol: udp
      destination:
        ports: [53]
    egress:
    - action: allow
EOF
```
but without  this ip `net: "138.68.*.*"` still i can ssh to machine.

Thanks
