### ISSUE TITLE
Calico network latency in IPIP mode on kubernetes cluster

### ISSUE THREAD

**Issue by xuchenCN** [projectcalico/calico#7415]
## Current Behavior
There is a node running a pod A with centos image, insdie pod A running a iperf3 -s -p xxxxx to test performance.

From the other node run iperf3 to connect the pod A, test result bandwidth only 1~10Mb/s

BUT use iperf3 -c <podA.ip> -p xxxxx -R (server send, client receive), test result bandwidth ~15Gb/s

Calico-node correctly detected the interface.

I wonder why receive has lower perfermance than send over same IP against other node.

All pods are no networkpolicy no network limitation configuration on that. 

![image](https://user-images.githubusercontent.com/2757089/222398645-2085c3c9-566f-4618-ac60-64542782f9bd.png)

![image](https://user-images.githubusercontent.com/2757089/222398687-5d8149f6-0be4-4275-8985-b49528f5dae6.png)

![image](https://user-images.githubusercontent.com/2757089/222398749-e8bc4954-e1dd-47a3-99cd-2904914f7902.png)

![image](https://user-images.githubusercontent.com/2757089/222398806-018db7d4-b5ae-48a2-9fdd-6ec530adeb0b.png)

![image](https://user-images.githubusercontent.com/2757089/222398859-af7e3e1e-649e-49fb-9e27-8384a57a4d5f.png)

![image](https://user-images.githubusercontent.com/2757089/222402279-bfadc378-d754-47c9-ba94-e9bf0e86ef5a.png)

Here are some tests to poorf the situation.

NodeA -> NodeB  good
NodeB -> NodeA good
Pod on nodeA -> NodeB good
Node -> Pod on NodeB  NOT GOOD
Pod ->  Pod on NodeB  NOT GOOD
Pod on NodeB -> NodeA good
Pod on NodeB -> Pod on NodeA good

## Your Environment

infiniband on ip
kubernetes 1.18.3
kube-proxy ipvs mode
pod image : centos
calico 3.18.0 in IPIP mode
OS: centos 7.9, kernel 3.10

**Comment by coutinhop** [comment]
Hi @xuchenCN, Calico v3.18.0 is a rather old version, this could be an issue that might have been resolved already. Would you mind trying to reproduce it with a more recent version?

How does your IPIP config look like? Is it "Always" or "CrossSubnet"? (not that it should matter from the info you gave, but just wondering...)

**Comment by xuchenCN** [comment]
Hi @coutinhop thanks for reply.
It's a old cluster in our production environment, therefore, upgrading calico may cause the user's application to crash.

Configuration :

```
- name: CLUSTER_TYPE
          value: k8s,bgp
        - name: IP
          value: autodetect
        - name: IP_AUTODETECTION_METHOD
          value: cidr=172.16.3.0/24
        - name: CALICO_IPV4POOL_IPIP
          value: CrossSubnet
        - name: CALICO_IPV4POOL_VXLAN
          value: Never
        - name: FELIX_IPINIPMTU
          valueFrom:
            configMapKeyRef:
              key: veth_mtu
              name: calico-config
        - name: FELIX_VXLANMTU
          valueFrom:
            configMapKeyRef:
              key: veth_mtu
              name: calico-config
        - name: FELIX_WIREGUARDMTU
          valueFrom:
            configMapKeyRef:
              key: veth_mtu
              name: calico-config
        - name: CALICO_IPV4POOL_CIDR
          value: 172.18.0.0/16
        - name: CALICO_DISABLE_FILE_LOGGING
          value: "true"
        - name: FELIX_DEFAULTENDPOINTTOHOSTACTION
          value: ACCEPT
        - name: FELIX_IPV6SUPPORT
          value: "false"
        - name: FELIX_LOGSEVERITYSCREEN
          value: info
        - name: FELIX_HEALTHENABLED
          value: "true"
```
