### ISSUE TITLE
Cannot find syslogs generated from Calico Network Policy log action

### ISSUE THREAD

**Issue by eguer004** [projectcalico/calico#7426]
Hi,

I have Calico network policies in place for an Azure k8s environment. There are some connections that getting dropped, (I am aware that I am missing allow rules in the policy rules), but I am not able to find the syslogs that are generated from the Calico log action to determine which connections are getting dropped. I've looked in the host node, calico-node pod, and service pods, but don't see logs related to Calico.

This is the document I found for Calico logs:
https://docs.tigera.io/calico/3.24/network-policy/get-started/calico-policy/calico-network-policy#generate-logs-for-specific-traffic

Thanks!

## Expected Behavior
See logs for dropped connections.

## Current Behavior
No logs are created

## Steps to Reproduce (for bugs)
https://docs.tigera.io/calico/3.25/network-policy/get-started/calico-policy/calico-network-policy#generate-logs-for-specific-traffic
1. Define Log action in Calico network policy
2. See logs

## Your Environment
Cluster Version:   v3.24.0
Cluster Type:      typha,kdd,k8s,operator,aks
Kubernetes version: v1.24.3

**Comment by Tim-herbie** [comment]
Same for me...  I don't see any network policy logs in either minikube or azure aks

I can see the the cni.log file (path: /var/log/calico/cni), but I can´t find any network policy logs in there

Environment: AKS and minikube
Kubernetes version: v1.24.9

I tested also different network policies and global network policies:

e.g.

```yaml
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: log
spec:
  selector: app == 'web'
  types:
  - Ingress
  - Egress
  ingress:
  - action: Log
  egress:
  - action: Log
  - action: Deny

```

Is there a known bug or anything else?
