### ISSUE TITLE
why hit the rule: iptables ctstate INVALID in KUBE-FORWARD chain drops forward packets to other node

### ISSUE THREAD

**Issue by xxoxx** [projectcalico/calico#7434]
## Expected Behavior

The external network can directly connect to the tcp port of the pod
## Current Behavior

The external network can directly ping to the pod id 
But the external network cannot directly connect to the tcp port of the pod
## Steps to Reproduce (for bugs)

I use 4 nodes for this test
k8s_node: 
    debian-241 (192.168.3.241  master)
    debian-242 (192.168.3.242  worker)
    debian-243(192.168.3.243   worker)
external_node:
   192.168.3.244

1.install k8s: kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address=192.168.3.241 --kubernetes-version v1.26.2
2. install calico: kubectl apply -f https://projectcalico.docs.tigera.io/archive/v3.25.0/manifests/calico.yaml
3. create a nginx: kubectl create deployment nginx --image=nginx
4. external_node add static route:
route add -net 10.244.0.0 netmask 255.255.0.0 gw 192.168.3.241
5. test the access:
```
ping podip    ping result is good
curl podip    curl result is bad
```
then delete the iptables rules
`iptables -t filter -D KUBE-FORWARD 1    <no1.  rules is: DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate INVALID>`
and test again
```
ping podip    ping result is good
curl podip    curl result is good
```

6. try in bgp rr  and test
```
 cat << EOF | calicoctl create -f -
 apiVersion: projectcalico.org/v3
 kind: BGPConfiguration
 metadata:
   name: default
 spec:
   logSeverityScreen: Info
   nodeToNodeMeshEnabled: false
   asNumber: 63400
EOF

 cat << EOF | calicoctl create -f -
kind: BGPPeer
apiVersion: projectcalico.org/v3
metadata:
  name: peer-to-rrs
spec:
  nodeSelector: "!has(route-reflector)"
  peerSelector: has(route-reflector)
---
kind: BGPPeer
apiVersion: projectcalico.org/v3
metadata:
  name: rr-mesh
spec:
  nodeSelector: has(route-reflector)
  peerSelector: has(route-reflector)
EOF
```
calicoctl patch node debian-241 -p '{"metadata":{"labels":{"route-reflector":"true"}}}'
calicoctl patch node debian-241 -p '{"spec":{"bgp":{"routeReflectorClusterID":"224.0.0.1"}}}'
calicoctl patch ippool default-ipv4-ippool -p '{"spec":{"ipipMode": "CrossSubnet"}}'

test the access:
```
ping podip    ping result is good
curl podip    curl result is bad
```
then delete the iptables rules
`iptables -t filter -D KUBE-FORWARD 1    <no1.  rules is: DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate INVALID>`
and test again
```
ping podip    ping result is good
curl podip    curl result is good
```

 Please confirm that this is a bug or my configuration is not configured correctly
I think the solution to this problem is not to delete this rule
Because this rule is automatically created every few minutes

## Your Environment

* Calico version:3.25
* kubernetes:1.26.2
* Operating System and version: debian11  5.10.0-21-amd64
