### ISSUE TITLE
Trailing space found in calico.yaml

### ISSUE THREAD

**Issue by hickersonj** [projectcalico/calico#7448]
While linting the [calico.yaml](https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/calico.yaml) chart, an error occurred.

## Expected Behavior

Output of yamllint is free of errors.

## Current Behavior

The following error occurs while running yamllint:
```bash
yamllint --no-warnings -d relaxed calico.yaml
  4232:14   error    trailing spaces  (trailing-spaces)
```
The specific line is:
```yaml
  - apiGroups: ["discovery.k8s.io"]
    resources:
      - endpointslices
    verbs:
      - watch <- extra space here
      - list
```
## Possible Solution

Remove the trialing space; after doing so the linter is error free.

## Steps to Reproduce (for bugs)

1. `yamllint --no-warnings -d relaxed calico.yaml`

## Context

Will need to skip auto-linting of this chart until the problem is fixed.

## Your Environment

* Calico version: **v3.25.0**
* Orchestrator version (e.g. kubernetes, mesos, rkt): **k3s**
* Operating System and version: **Linux**
* Link to your project (optional):
