### ISSUE TITLE
How to prove the topology  for BGPPeer

### ISSUE THREAD

**Issue by 631068264** [projectcalico/calico#7463]
Installation config
```
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  ....
spec:
  calicoNetwork:
    bgp: Enabled
    hostPorts: Enabled
    ipPools:
    - blockSize: 26
      cidr: 10.42.0.0/16
      disableBGPExport: false
      encapsulation: IPIP
      natOutgoing: Enabled
      nodeSelector: all()
    linuxDataplane: Iptables
    multiInterfaceMode: None
    nodeAddressAutodetectionV4:
      firstFound: true
  cni:
    ipam:
      type: Calico
    type: Calico

```

I have 3 nodes

By default  node-to-node mesh , the topology may like this  connect by tunl0

<img width="485" alt="image" src="https://user-images.githubusercontent.com/8144089/224741048-498e9e1e-fe03-4aee-a8c0-10bf4859a6a9.png">

And I can prove it from ip route

On A
```
blackhole 10.42.139.128/26 proto bird 
10.42.221.128/26 via B dev tunl0 proto bird onlink 
10.42.225.192/26 via C dev tunl0 proto bird onlink 
```
On C
```
10.42.139.128/26 via A dev tunl0 proto bird onlink 
10.42.221.128/26 via B dev tunl0 proto bird onlink 
blackhole 10.42.225.192/26 proto bird 
```

On B
```
10.42.139.128/26 via A dev tunl0 proto bird onlink 
blackhole 10.42.221.128/26 proto bird 
10.42.225.192/26 via C dev tunl0 proto bird onlink 
```

Then after I config C as **route reflector**

```
calicoctl patch node C -p '{"spec": {"bgp": {"routeReflectorClusterID": "244.0.0.1"}}}'

kubectl label node C route-reflector=true


cat <<EOF | calicoctl apply -f -
kind: BGPPeer
apiVersion: projectcalico.org/v3
metadata:
  name: peer-with-route-reflectors
spec:
  nodeSelector: all()
  peerSelector: route-reflector == 'true'
EOF


cat <<EOF | calicoctl apply -f -
apiVersion: projectcalico.org/v3
kind: BGPConfiguration
metadata:
 name: default
spec:
  logSeverityScreen: Info
  nodeToNodeMeshEnabled: false
  asNumber: 63400
EOF

```

On A
```
Calico process is running.

IPv4 BGP status
+--------------+---------------+-------+----------+-------------+
| PEER ADDRESS |   PEER TYPE   | STATE |  SINCE   |    INFO     |
+--------------+---------------+-------+----------+-------------+
| C  | node specific | up    | 06:32:50 | Established |
+--------------+---------------+-------+----------+-------------+

IPv6 BGP status
No IPv6 peers found.

```

On C
```

Calico process is running.

IPv4 BGP status
+--------------+---------------+-------+----------+-------------+
| PEER ADDRESS |   PEER TYPE   | STATE |  SINCE   |    INFO     |
+--------------+---------------+-------+----------+-------------+
| A  | node specific | up    | 06:32:40 | Established |
| B | node specific | up    | 06:32:40 | Established |
+--------------+---------------+-------+----------+-------------+

IPv6 BGP status
No IPv6 peers found.
```

BGPPeer config success

## Except Behavior

<img width="453" alt="image" src="https://user-images.githubusercontent.com/8144089/224746237-f2553dff-67c0-4749-946a-e286d1df5669.png">

**But  the ip route hasn't any change**  Why?

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):
