### ISSUE TITLE
Critical: Sluggishness and Admission WebHook failings since 3.24.x, cluster not working

### ISSUE THREAD

**Issue by linecolumn** [projectcalico/calico#7469]
According to the communication on Slack with @tomastigera, we created a GitHub Issue. [Slack conversation](https://calicousers.slack.com/archives/C0BCA117T/p1671639682860989)

After creating the cluster and applying the manifest using  v3.24.3+, including 3.25.0 (eBPF), the Kubernetes cluster appeared to be ready and working. However, there were some issues with sluggish communication via kubectl, and the Admission WebHooks were failing after applying some workload. 

When we recreated the cluster using versions <= v3.23.5 with the same Calico and Kubernetes settings, we got a perfectly working cluster.

## Expected Behavior

Working cluster without any slowness or failing WebHooks.

## Current Behavior

Communication with the cluster is extremely slow, and the WebHooks are failing. It appears that the communication with the Kubernetes API is slow or saturated.

## Possible Solution

Downgrading to Calico lower than v3.24 fixes all problems.

## Your Environment

* Calico version >= v3.24
* RKE v1.3.x, v1.4.x
* RHEL v8
* Kernel v5.15.x
* enabled eBPF
* enabled DSR
* disabled IPIP
* Dedicated servers with two NICs (em1 WAN interface, em2 LAN interface)

The only change to manifest file is following:

```            
            - name: CALICO_IPV4POOL_CIDR
              value: "10.251.0.0/16"
            - name: IP_AUTODETECTION_METHOD                                                                                                                                                   
              value: "interface=em2"              
            - name: FELIX_MTUIFACEPATTERN
              value: "em2"
```

Applied following changes to Felix configuration:

```
apiVersion: projectcalico.org/v3
kind: FelixConfiguration
metadata:
  name: default
spec:
  bpfEnabled: true
  bpfExternalServiceMode: DSR
  bpfKubeProxyIptablesCleanupEnabled: false
  bpfLogLevel: ""
  # bpfEnforceRPF: disabled (or Strict) same thing
  logSeverityScreen: Info
```

I've already tried suggested `bpfEnforceRPF: disabled` -- no effects; haven't tried _Loose_ for option.

It appears that certain modifications were implemented in version 3.24 that have impacted mine server and Calico setup, rendering newer versions of Calico entirely inoperable.
