### ISSUE TITLE
calico-node liveness health check should check bird really working .....

### ISSUE THREAD

**Issue by gaopeiliang** [projectcalico/calico#7472]
when bird process hang with some reason .....   routes can not be distribute , all network to this node will failed .....  

like this case ....

calico-node has an event about readiness , and all pod network to this node lost .....  
`
Readiness probe failed: calico/node is not ready: BIRD is not ready: Error querying BIRD: unable to connect to BIRDv4 socket: dial unix /var/run/bird/bird.ctl: connect: no such file or directory
`

we check it ,  every process confd, felix,  bird is alive ;   but bgp session connect failed to this node,  I think bird process hang and not really work ......  

`
birdcl -s /var/run/calico/bird.ctl
`

never return response , hang forever ........   restart  pod  can  recover it !   

liveness health check should  catch this exception , and restart it !  we can do nothing with zombie  process .....

## Expected Behavior
liveness health check cover  bird process hang  case ....

## Current Behavior

`/bin/calico-node -felix-live -bird-live`  command  only check bird-live with `sv status bird` && running 

but ignore process hang ,  not really work ....   

## Possible Solution
Just like liveness said ,, we should really check process alive .....   

maybe add some check can avoid this case ...

```
        livenessProbe:
          exec:
            command:
            - bash
            - -c
            - /bin/calico-node -felix-live -bird-live && /usr/bin/birdcl -s /var/run/calico/bird.ctl show status
```

## Your Environment

* Calico 3.11  
* kubernetes
* Ubuntu kernel 4.9   4.19
* Link to your project (optional):
