### ISSUE TITLE
feature: CRD Installation support cni.binDir

### ISSUE THREAD

**Issue by zhangguanzhang** [projectcalico/calico#7511]
```
kubelet --help |& grep cni-bin
      --cni-bin-dir string          
                           
  A comma-separated list of full paths of directories in which to search for CNI plugin binaries. 
This docker-specific flag only works when container-runtime is set to docker. (default "/opt/cni/bin")
```
Expected Behavior
```yaml
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  computed:
    cni:
      binDir: "/opt/cni/bin"
```

**Comment by zhangguanzhang** [comment]
@caseydavenport

**Comment by bhavyastar** [comment]
Hey @zhangguanzhang , I would like to work on this issue.

**Comment by caseydavenport** [comment]
@bhavyastar nice! Let me know if you need any guidance or code reviews - just give me a ping.

**Comment by caseydavenport** [comment]
@a-yohe1 thanks for the ping! 

Dockershim no longer exists in Kubernetes, but CNI bin / config directories are still needed - they are just configured on the container runtime instead of on kubelet.

For example, containerd has CNI directories in its config: https://github.com/containerd/containerd/blob/main/docs/cri/config.md#full-configuration

So I think this issue still makes sense.

**Comment by a-yohe1** [comment]
@caseydavenport 
Thank you for your reply. I wasn't aware that similar options were supported in container runtimes other than Dockershim. This is very informative.
It also seems that [CRI-O](https://github.com/cri-o/cri-o/blob/main/docs/crio.conf.5.md#crionetwork-table) might have similar settings.

Since several container runtimes allow for configuration changes, I agree that supporting the installation method mentioned here would be useful.
I'm interested in this issue, so I'll look into the Installation CRD and consider how to resolve it.

**Comment by caseydavenport** [comment]
@a-yohe1 nice!

I'd probably start here: https://github.com/tigera/operator/blob/master/api/v1/installation_types.go

Let me know if you have any questions

**Comment by a-yohe1** [comment]
@caseydavenport 
Sorry for the quick follow-up. I'd like to check on two points:

#### 1.
This issue discusses the directory for CNI plugin binaries. However, it occurred to me that there might also be a desire to customize the directory for CNI configuration files (/etc/cni/net.d). Do you feel it would be worthwhile to support this customization as well?

I noticed this while looking at the [containerd config](https://github.com/containerd/containerd/blob/main/docs/cri/config.md#full-configuration) and wondered what you think about this? 

#### 2.
Regarding the Installation CRD definition proposed at the beginning of this issue, is it okay as presented?
This involves adding a computed key directly under Installation.

```
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  computed:
    cni:
      binDir: "/opt/cni/bin"
```

Alternatively, since a CNISpec already exists for CNI-related settings, I thought another approach could be to consolidate CNI configurations there. I felt this might be clearer, as it would gather all CNI-related settings in one place.

```
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  cni:
    binDir: "/opt/cni/bin"

# If we also include the directory for CNI configuration files, it is as follows:
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  cni:
    binDir: "/opt/cni/bin"
    confDir: "/etc/cni/net.d"
```
If you have any thoughts, I'd like to hear them.

**Comment by caseydavenport** [comment]
@a-yohe1 always good to ask questions :) 


I think the `computed` key is unnecessary (that looks like it was just a copy/paste error from the `status` instead of the `spec` 

I would do this:

```
spec:
  cni:
    binDir: "/opt/cni/bin"
    confDir: "/etc/cni/net.d"
```

I agree we should have both `binDir` and `confDir`
