### ISSUE TITLE
Service LoadBalancer endpoint is announced from multiple peers

### ISSUE THREAD

**Issue by xhejtman** [projectcalico/calico#7512]
It seems that even if service LoadBalancer has `externalTrafficPolicy: Local`, calico announces the external IP from multiple nodes. From the bgp peer side, I can see, e.g.:
```
xhejtman@c-rect> show route receive-protocol bgp 10.16.58.130 | match 64512
  10.16.58.240/28         10.16.58.130                            64512 I
  147.251.14.0/28         10.16.58.130                            64512 I
* 147.251.14.2/32         10.16.58.130                            64512 I

xhejtman@c-rect> show route receive-protocol bgp 10.16.58.131 | match 64512
  10.16.58.240/28         10.16.58.131                            64512 I
  147.251.14.0/28         10.16.58.131                            64512 I

xhejtman@c-rect> show route receive-protocol bgp 10.16.58.132 | match 64512
* 10.16.58.240/28         10.16.58.132                            64512 I
* 147.251.14.0/28         10.16.58.132                            64512 I
  147.251.14.2/32         10.16.58.132                            64512 I

xhejtman@c-rect> show route receive-protocol bgp 10.16.58.133 | match 64512
  10.16.58.240/28         10.16.58.133                            64512 I
  147.251.14.0/28         10.16.58.133                            64512 I
  147.251.14.2/32         10.16.58.133                            64512 I
```

service is on the node `10.16.58.130`, so current traffic is OK, however, if I reboot the node or external peer is restart, traffic is sent to e.g., 10.16.58.132 and service is not there.

Calico version is 3.25.0, installed via rancher rke2 tool together with kubernetes 1.26.2, however, I can see the same bahavior with calico 3.24.5 and kubernetes 1.24.10.

The installer is tigera operator:
```
calicoNetwork:
    bgp: Enabled
    hostPorts: Enabled
    ipPools:
    - blockSize: 24
      cidr: 10.42.0.0/16
      disableBGPExport: true
      encapsulation: VXLANCrossSubnet
      natOutgoing: Enabled
      nodeSelector: all()
    - blockSize: 116
      cidr: xxx:42d3:8:2::/96
      disableBGPExport: true
      encapsulation: VXLANCrossSubnet
      natOutgoing: Enabled
      nodeSelector: all()
    linuxDataplane: Iptables
    multiInterfaceMode: None
    nodeAddressAutodetectionV4:
      firstFound: true
    nodeAddressAutodetectionV6:
      firstFound: true
```

Felix configuration:
```
spec:
  bpfLogLevel: ""
  defaultEndpointToHostAction: Drop
  failsafeInboundHostPorts:
  - port: 22
    protocol: tcp
  failsafeOutboundHostPorts:
  - port: 53
    protocol: udp
  - port: 80
    protocol: tcp
  - port: 443
    protocol: tcp
  - port: 3128
    protocol: tcp
  floatingIPs: Disabled
  healthPort: 9099
  logSeverityScreen: Info
  logSeveritySys: Info
  reportingInterval: 0s
  wireguardEnabled: false
  xdpEnabled: true
```
Calico pools:
```
apiVersion: crd.projectcalico.org/v1
kind: BGPConfiguration
metadata:
  name: default
spec:
  asNumber: 64512
  serviceLoadBalancerIPs:
  - cidr: xxx
```
