### ISSUE TITLE
`csiNodeDriverDaemonSet` is not in Installation spec

### ISSUE THREAD

**Issue by adziura-ledger** [projectcalico/calico#7569]
## Expected Behaviour

This should work
```
installation:
  enabled: true
  kubernetesProvider: "EKS"
  # There is no other way to disable csi-node-driver DaemonSet
  CSINodeDriverDaemonSet:
    spec:
      template:
        spec:
          nodeSelector:
            disable: "true"
```

## Current Behavior
```
Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(Installation.spec): unknown field "CSINodeDriverDaemonSet" in io.tigera.operator.v1.Installation.spec
```

## Possible Solution
New release includes [this](https://github.com/projectcalico/calico/commit/3c1ee204f15d880e334748499a8bdd4610492729) commit.

## Context
`csi-node-driver` is useless for `policy-only` mode without Istio.

## Your Environment
* Calico version - 3.25.1
* Orchestrator version - EKS 1.22
* Operating System and version: Amazon Linux 2

**Comment by kalpanathanneeru21** [comment]
How to disable csi-node-driver in latest versions like 3.24.X and 3.25.X

**Comment by tmjd** [comment]
If you set the field `kubeletVolumePluginPath` in the Installation resource to `None` then CSI will be disabled.

**Comment by kalpanathanneeru21** [comment]
Facing issue like `error validating data: ValidationError(Installation.spec): unknown field "kubeletVolumePluginPath" in io.tigera.operator.v1.Installation.spec`
Installation spec looks like 
```
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  cni:
    type: AmazonVPC
  componentResources:
  - componentName: Node
    resourceRequirements:
      limits:
        memory: {{ .Values.node.resources.limits.memory }}
      requests:
        cpu: {{ .Values.node.resources.requests.cpu }}
        memory: {{ .Values.node.resources.requests.memory }}
  - componentName: Typha
    resourceRequirements:
      limits:
        memory: {{ .Values.typha.resources.limits.memory }}
      requests:
        cpu: {{ .Values.typha.resources.requests.cpu }}
        memory: {{ .Values.typha.resources.requests.memory }}
  - componentName: KubeControllers
    resourceRequirements:
      limits:
        memory: {{ .Values.kubeControllers.resources.limits.memory }}
      requests:
        cpu: {{ .Values.kubeControllers.resources.requests.cpu }}
        memory: {{ .Values.kubeControllers.resources.requests.memory }}
  imagePath: {{ .Values.imagePath }}
  imagePrefix: kaas-core/
  kubernetesProvider: EKS
  kubeletVolumePluginPath: None
  nodeMetricsPort: ****
  nodeUpdateStrategy:
    rollingUpdate:
      maxUnavailable: *%
    type: RollingUpdate
  registry: ***/
  variant: Calico
```

anything wrong in my installationSpec
