### ISSUE TITLE
Calico node liveness healthcheck uses IPv6 instead of IPv4 and fails with CrashLoopBackOff

### ISSUE THREAD

**Issue by Constantin07** [projectcalico/calico#7596]
## Expected Behavior
When I upgrade Calico from v3.25.0 to v.3.25.1 or run `kubectl -n calico-system rollout restart ds calico-node` the pods should go to `Running` state.

## Current Behavior
The `calico-node` pods continuously restart with status: `CrashLoopBackOff`.
For some reason it binds to IPv6 loopback instead of IPv4 and fails.
```
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  5m6s                   default-scheduler  Successfully assigned calico-system/calico-node-kr9dm to ip-10-159-6-229.eu-west-1.compute.internal
  Normal   Pulled     5m5s                   kubelet            Container image "docker.io/calico/pod2daemon-flexvol:v3.25.1" already present on machine
  Normal   Created    5m5s                   kubelet            Created container flexvol-driver
  Normal   Started    5m5s                   kubelet            Started container flexvol-driver
  Normal   Pulled     5m5s                   kubelet            Container image "docker.io/calico/node:v3.25.1" already present on machine
  Normal   Created    5m5s                   kubelet            Created container mount-bpffs
  Normal   Started    5m4s                   kubelet            Started container mount-bpffs
  Normal   Killing    4m35s                  kubelet            Container calico-node failed liveness probe, will be restarted
  Normal   Pulled     4m30s (x2 over 5m4s)   kubelet            Container image "docker.io/calico/node:v3.25.1" already present on machine
  Normal   Created    4m30s (x2 over 5m4s)   kubelet            Created container calico-node
  Normal   Started    4m29s (x2 over 5m3s)   kubelet            Started container calico-node
  Warning  Unhealthy  4m27s (x8 over 5m2s)   kubelet            Readiness probe failed: calico/node is not ready: felix is not ready: Get "http://localhost:9099/readiness": dial tcp [::1]:9099: connect: connection refused
  Warning  Unhealthy  4m25s (x4 over 4m55s)  kubelet            Liveness probe failed: Get "http://localhost:9099/liveness": dial tcp [::1]:9099: connect: connection refused
```

```shell
 kubectl get pods -A                                                                                                                                      MAC6578: Wed Apr 26 14:44:00 2023

NAMESPACE          NAME                                               READY   STATUS             RESTARTS      AGE
calico-apiserver   calico-apiserver-6c59c9fbd6-8thm8                  1/1     Running            0             4m26s
calico-apiserver   calico-apiserver-6c59c9fbd6-v47fc                  1/1     Running            0             4m26s
calico-system      calico-kube-controllers-7fc6bcc98-mhksm            1/1     Running            0             4m26s
calico-system      calico-node-k9cvq                                  0/1     CrashLoopBackOff   2             3m54s
calico-system      calico-node-lx42c                                  0/1     CrashLoopBackOff   5             4m27s
calico-system      calico-node-szfqw                                  0/1     CrashLoopBackOff   4 (46s ago)   3m32s
calico-system      calico-typha-7bd686bfd6-fkkpc                      1/1     Running            0             4m28s
calico-system      calico-typha-7bd686bfd6-lhqv6                      1/1     Running            0             4m28s
calico-system      csi-node-driver-92r6n                              2/2     Running            0             3m25s
calico-system      csi-node-driver-pwxwf                              2/2     Running            0             4m26s
calico-system      csi-node-driver-t2f8j                              2/2     Running            0             3m16s

```
Other pods are also affected - they cannot reach K8s cluster API endpoint.

Also, not sure if calico-node DaemonSet should have the `hostname` in Liveness healthcheck ? I guess it could be omitted?
```
        livenessProbe:
          failureThreshold: 3
          httpGet:
            host: localhost
            path: /liveness
            port: 9099
```

## Possible Solution
The current workaround - terminating worker nodes returns to normal behaviour.

## Steps to Reproduce (for bugs)

1. Deploying using Helm the official chart (v3.25.0) with the below values config:
```yaml
---
installation:
  variant: Calico
  # We don't need Calico CNI networking as we already use VPC CNI plugin for this, only Calico network security policy enforcement.
  cni:
    type: AmazonVPC
  calicoNetwork:
    linuxDataplane: BPF
    bgp: Disabled
  kubernetesProvider: EKS
  # Sensible defaults. Limits can be added when baseline is known.
  calicoNodeDaemonSet:
    spec:
      template:
        spec:
          containers:
            - name: calico-node
              resources:
                requests:
                  memory: 64Mi
                  cpu: 40m
  calicoKubeControllersDeployment:
    spec:
      template:
        spec:
          containers:
            - name: calico-kube-controllers
              resources:
                requests:
                  memory: 64Mi
                  cpu: 40m
  typhaDeployment:
    spec:
      template:
        spec:
          containers:
            - name: calico-typha
              resources:
                requests:
                  memory: 64Mi
                  cpu: 40m
  controlPlaneNodeSelector:
    kubernetes.io/os: linux

apiServer:
  enabled: true
  apiServerDeployment:
    spec:
      template:
        spec:
          containers:
            - name: calico-apiserver
              # We don't have a baseline at the moment but setting minimum required for scheduling.
              resources:
                requests:
                  memory: 64Mi
                  cpu: 40m

# We don't have a baseline at the moment but setting minimum required for scheduling.
resources:
  requests:
    memory: 64Mi
    cpu: 50m
```
2. Try to upgrade Helm chart version to v3.25.1.

## Context
The networking is provided by AWS VPC CNI plugin. Calico is used only for network policy.
The VPC CNI plugin is configured with custom networking - pods get IPs allocated from secondary CIDR range, see https://docs.aws.amazon.com/eks/latest/userguide/cni-custom-network.html

## Your Environment
* Calico version v3.25.1 
* Orchestrator version: AWS EKS v1.24
* Operating System and version: Bottlerocket 1.13.3
