### ISSUE TITLE
Validation Error unknown field "serviceMatch" in Calico 3.20.0

### ISSUE THREAD

**Issue by StromBreaker10** [projectcalico/calico#7680]
I am trying to create a network policy in kubernetes 1.24 and calico 3.20 environment so that my component connect to the database through service by making use of serviceMatch feild. This solution worked for us in 1.21 and 3.15 and 1.24 and 3.15 without any errors. But when we upgraded the calico to 3.20 we getting unknown feild error.

Network rule in  NetworkPolicy yaml:

  - action: allow
    protocol: TCP
    source:
      selector: com.siemens.sdis.container.app == 'myApp' && com.siemens.sdis.container.component == 'my-component'
    destination:
      serviceMatch:
        name: db
        namespace: testnp
      ports:
      - 8080 

Error:

Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(NetworkPolicy.spec.egress[2].destination): unknown field "serviceMatch" in org.projectcalico.crd.v1.NetworkPolicy.spec.egress.destination

Environment Details:
kubernetes version: 1.24
calico version: 3.20 (docker.io/calico/node:v3.20.0)
networkpolicy api version: crd.projectcalico.org/v1

**Comment by caseydavenport** [comment]
The field should be called "services".

Per the example from the docs:

```
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: allow-api-access
  namespace: my-app
spec:
  selector: all()
  egress:
    - action: Allow
      destination:
        services:
          name: kubernetes
          namespace: default
```

https://docs.tigera.io/archive/v3.20/security/service-policy
