### ISSUE TITLE
Csi-node-driver not installed on all of our nodes/node groups -following recent upgrade to Kubernetes 1.23 (toleration link - not working)

### ISSUE THREAD

**Issue by pwyborn** [projectcalico/calico#7685]
During the k8s upgrade 1.23, we found that some of the csi-node-driver daemonset of calico-system were not installed in monitoring node group.
We suspect it is something connected to Tolerations/spec.
<img width="971" alt="Screenshot 2023-05-23 at 14 36 45" src="https://github.com/projectcalico/calico/assets/6805936/7b3e4cfd-0db9-437e-82cb-ea864223b5a2">
<img width="1419" alt="Screenshot 2023-05-23 at 14 37 50" src="https://github.com/projectcalico/calico/assets/6805936/b63a55a0-2503-4400-815e-0ffdf1a32caf">

There is some guidance - however the link in the documentation is not working 
https://v1-21.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#toleration-v1-core

## Expected Behaviour

Csi-node-driver to be installed on all of our nodes/node groups (instead of most).

We have looked at the following issues:

- https:https://github.com/projectcalico/calico/issues/7070//github.com/projectcalico/calico/issues/7070
- https://github.com/projectcalico/calico/issues/7569 - like mentioned here `unknown field "CSINodeDriverDaemonSet"`

## Current Behaviour

It is installed on 76 out of 79 nodes

## Steps to Reproduce (for bugs)

Current attempt:
values.yaml.tpl
```
imagePullSecrets: {}

installation:
  enabled: true
  kubernetesProvider: "${kubernetes_provider}"

spec:
  template:
    tolerations:
    - key: "monitoring-node"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"

apiServer:
  enabled: true

certs:
  node:
    key:
    cert:
    commonName:
  typha:
    key:
    cert:
    commonName:
    caBundle:

# Resource requests and limits for the tigera/operator pod.
resources: {}

# Tolerations for the tigera/operator pod.
tolerations:
- effect: NoExecute
  operator: Exists
- effect: NoSchedule
  operator: Exists

# NodeSelector for the tigera/operator pod.
nodeSelector:
  kubernetes.io/os: linux

# Custom annotations for the tigera/operator pod.
podAnnotations: {}

# Custom labels for the tigera/operator pod.
podLabels: {}

# Image and registry configuration for the tigera/operator pod.
tigeraOperator:
  image: tigera/operator
  version: "${tigera_operator_version}"
  registry: quay.io
calicoctl:
  image: docker.io/calico/ctl
  tag: master
```
I also tried:
```
installation:
     enabled: true
     CSINodeDriverDaemonSet:
       spec:
         template:
           spec:
             tolerations:
             - key: "monitoring-node"
               operator: "Equal"
               value: "true"
               effect: "NoSchedule"
```
However received error message:
`unknown field "CSINodeDriverDaemonSet"`

## Your Environment

* Calico version. I have tried helm chart versions [v3.25.1](https://github.com/projectcalico/calico/releases/tag/v3.25.1) and the latest [v3.24.6](https://github.com/projectcalico/calico/releases/tag/v3.24.6)
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes 1.23, AWS EKS

**Comment by pwyborn** [comment]
Just an update.
I tried the following config:
I am not now getting the error message re `CSINodeDriverDaemonSet` - however the csi node driver is still not being installed on the nodes in the monitoring nodegroup:
```
ImagePullSecrets: {}

installation:
  enabled: true
  kubernetesProvider: "${kubernetes_provider}"

CSINodeDriverDaemonSet:
  spec:
    template:
      tolerations:
      - key: "monitoring-node"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"

apiServer:
  enabled: true

certs:
  node:
    key:
    cert:
    commonName:
  typha:
    key:
    cert:
    commonName:
    caBundle:

# Resource requests and limits for the tigera/operator pod.
resources: {}

# Tolerations for the tigera/operator pod.
tolerations:
- effect: NoExecute
  operator: Exists
- effect: NoSchedule
  operator: Exists

# NodeSelector for the tigera/operator pod.
nodeSelector:
  kubernetes.io/os: linux

# Custom annotations for the tigera/operator pod.
podAnnotations: {}

# Custom labels for the tigera/operator pod.
podLabels: {}

# Image and registry configuration for the tigera/operator pod.
tigeraOperator:
  image: tigera/operator
  version: "${tigera_operator_version}"
  registry: quay.io
calicoctl:
  image: docker.io/calico/ctl
  tag: master
```
