### ISSUE TITLE
PodSecurityPolicies can't be deleted while upgrading to v3.25.0

### ISSUE THREAD

**Issue by barsilver** [projectcalico/calico#7686]
## Expected Behavior
Upgrading the tigera-operator helm chart to v3.25.0 should remove the PodSecurityPolicies or at least not recreate them once they are deleted.

## Current Behavior
After upgrading our current tigera-operator helm chart from v3.23.0 to v3.25.0, the psp of calico-apiserver, calico-node, and calico-typha remains in the cluster. Uninstalling the chart doesn’t remove them, and if we try to delete them manually, they go back once we re-install the chart. 
Removing them after the upgrade didn't help either. They were recreated.

## Steps to Reproduce (for bugs)
1. We installed the chart using Terraform:
```
resource "helm_release" "tigera-operator" {
  name = "calico"
  repository = "https://projectcalico.docs.tigera.io/charts"
  chart = "tigera-operator"
  namespace = "tigera-operator"
  create_namespace = true
  version = "v3.25.0"
  reset_values = true
  recreate_pods = true
  values = [
    file("${path.module}/values.yaml")
  ]
}
```

values.yaml :
```
installation:
  kubernetesProvider: EKS
  cni:
    type: Calico
  calicoNetwork:
    bgp: Disabled
```
2. The created psp yaml files:
```
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
  name: calico-apiserver
  ownerReferences:
  - apiVersion: operator.tigera.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: APIServer
    name: default
spec:
  allowPrivilegeEscalation: false
  fsGroup:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
  hostPorts:
  - max: 65535
    min: 0
  requiredDropCapabilities:
  - ALL
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
  volumes:
  - configMap
  - emptyDir
  - projected
  - secret
  - downwardAPI
  - persistentVolumeClaim
  - hostPath
```

```
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
  name: calico-node
  ownerReferences:
  - apiVersion: operator.tigera.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Installation
    name: default
spec:
  allowPrivilegeEscalation: true
  fsGroup:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
  hostNetwork: true
  hostPorts:
  - max: 65535
    min: 0
  privileged: true
  requiredDropCapabilities:
  - ALL
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
  volumes:
  - configMap
  - emptyDir
  - projected
  - secret
  - downwardAPI
  - persistentVolumeClaim
  - hostPath
```

```
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
  name: calico-typha
  ownerReferences:
  - apiVersion: operator.tigera.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Installation
    name: default
spec:
  allowPrivilegeEscalation: false
  fsGroup:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
  hostNetwork: true
  hostPorts:
  - max: 65535
    min: 0
  requiredDropCapabilities:
  - ALL
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
  volumes:
  - configMap
  - emptyDir
  - projected
  - secret
  - downwardAPI
  - persistentVolumeClaim
```

```
kubectl get clusterinfo -o yaml >>
apiVersion: v1
items:
- apiVersion: projectcalico.org/v3
  kind: ClusterInformation
  spec:
    calicoVersion: v3.25.0
    clusterType: k8s,bgp,kdd,typha,operator,ecs
    datastoreReady: true
kind: List
metadata:
  resourceVersion: ""
```

## Context
Before we upgrade our EKS cluster to 1.25, we check that no psp is still needed.

## Environment
* Calico version: from v2.23.0 to v3.25.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): k8s 1.23
