### ISSUE TITLE
Documentation for Installing EKS with Calico networking is incomplete

### ISSUE THREAD

**Issue by nickamon** [projectcalico/calico#7734]
I have an EKS cluster that I wanted to replace the default AWS VPC CNI with Calico.  I followed the AWS documentation (https://docs.aws.amazon.com/eks/latest/userguide/alternate-cni-plugins.html) and it referred me to the tigera site for [Installing EKS with Calico networking](https://docs.tigera.io/calico/latest/getting-started/kubernetes/managed-public-cloud/eks#install-eks-with-calico-networking).  I followed the instructions on that page to delete the _aws-node_ daemon set and install the helm chart for installing the tigera-operator operator.  After following all the steps, the nodes of my cluster were all in the NotReady state.  I poured over various documentation numerous times and various online posts until I found this ticket #5636 which indicated that I needed to modify the installation config to use the Calico CNI rather than AWS VPC CNI:

```
kind: Installation
apiVersion: operator.tigera.io/v1
metadata:
  name: default
spec:
  kubernetesProvider: EKS
  cni:
    type: Calico
  calicoNetwork:
    bgp: Disabled
```
This is completely missing from the documentation.  It would save newbies like me a lot of time if this was included as part of the steps for installing EKS with Calico networking using Helm.

## Expected Behavior

Update the documentation to mention that the helm chart must be customized to use Calico as the CNI.

## Steps to Reproduce (for bugs)

I followed the steps found here:  [Install EKS with Calico networking](https://docs.tigera.io/calico/latest/getting-started/kubernetes/managed-public-cloud/eks#install-eks-with-calico-networking) for installing Calico CNI via a Helm chart.

## Your Environment

* Calico version v3.26.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): EKS w/ Kubernetes 1.27
* Operating System and version: Amazon Linux 2
* Link to your project (optional):

**Comment by caseydavenport** [comment]
Reading the linked doc: https://docs.tigera.io/calico/latest/getting-started/kubernetes/managed-public-cloud/eks#install-eks-with-calico-networking

Step 2 under the operator installation tab seems to already configure Calico CNI correctly.

This is what the documentation instructs you to do:

```
kubectl create -f - <<EOF
kind: Installation
apiVersion: operator.tigera.io/v1
metadata:
  name: default
spec:
  kubernetesProvider: EKS
  cni:
    type: Calico
  calicoNetwork:
    bgp: Disabled
EOF
```

What am I missing?
