### ISSUE TITLE
value imagePullSecrets is not being passed to Installation custom resource

### ISSUE THREAD

**Issue by RohanArya4894** [projectcalico/calico#7738]
## Expected Behavior

I have below in my values.yaml file.

```
installation:
  imagePullSecrets:
    - name: secretname
  registry: private-registry-url/
```

- imagePullSecrets for Installation custom resource should be populated with the passed value
e.g.
```
imagePullSecrets:
  - name: secretname
```

## Current Behavior
- imagePullSecrets for Installation custom resource is not updated with the passed value and remains empty list
e.g. 
```
imagePullSecrets: []
```

## Steps to Reproduce
1. pass helm values for installation as below:
```
installation:
  imagePullSecrets:
    - name: secretname
  registry: private-registry-url/
```

## Context
Trying to use private registry with already existing secret. It would be super helpful if the documentation have examples of using these helm values. values.yaml on the repo does not have registry spec under installation. but passing it with values.yaml allows installation to use that registry. 

## Environment
* tigera-operator helm chart version 3.26.0 being deployed as terraform resource "helm_release"
* Orchestrator version kubernetes EKS : v1.23
