### ISSUE TITLE
GlobalNetworkPolicy : notNets + notpots

### ISSUE THREAD

**Issue by xuoja-acc** [projectcalico/calico#7739]
## Expected Behavior

Any pods **but** the "test" pods should be able to egress to any **but** the 192.168.105.192/27 & 192.168.105.224/27 on port 4444 .

For exemple we'd like to be able to access to 
- 192.168.105.192/27 & 192.168.105.224/27 on port 443 but **not** to 4444.
- 0.0.0.0/0 on any ports , any protocols
```
apiVersion: crd.projectcalico.org/v1
kind: GlobalNetworkPolicy
metadata:
  name: allow-all-but-some-nets
spec:
  selector: all()
  types:
  - Egress
  egress:
  - action: Allow
    metadata:
      annotations:
        from: all-but-test
        to: all-but-some-nets
    protocol: TCP
    source:
      selector: pod-role != 'test'
    destination:
      notNets:
      - 192.168.105.192/27
      - 192.168.105.224/27
      notPorts:
        - 4444
---
apiVersion: crd.projectcalico.org/v1
kind: GlobalNetworkPolicy
metadata:
  name: default-deny
spec:
  selector: all()
  types:
  - Egress
```

## Current Behavior
When we only configure the notNets , the _pod-role != 'test'_ can access to DNS, curl etc... 
When we add the notPorts everythings stop working: no more access to core-dns , curl to internet etc.. 

## Steps to Reproduce (for bugs)
Apply the same configuration : 
- deny all egress
- allow to notNets **and** notPorts

## Your Environment
* Calico version
* EKS - v1.23.17
