### ISSUE TITLE
v3.25.0 tigera-operator: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by piotrhryszko-img** [projectcalico/calico#7748]
## Expected Behavior
no panic, application should run uninterrupted

## Current Behavior
Tigera operator restarted without an apparent reason after running for about 24 hours

```
{"level":"info","ts":1686061135.6398787,"logger":"controller_apiserver","msg":"Reconciling APIServer","Request.Namespace":"","Request.Name":"default"}
W0606 14:22:00.412727       1 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
{"level":"info","ts":1686061435.9019034,"logger":"controller_apiserver","msg":"Reconciling APIServer","Request.Namespace":"","Request.Name":"default"}
W0606 14:28:46.415171       1 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
{"level":"info","ts":1686061736.2424924,"logger":"controller_apiserver","msg":"Reconciling APIServer","Request.Namespace":"","Request.Name":"default"}
{"level":"info","ts":1686061974.318336,"logger":"controller_apiserver","msg":"Reconciling APIServer","Request.Namespace":"","Request.Name":"default"}
{"level":"info","ts":1686061974.5093322,"msg":"Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference","controller":"apiserver-contro
ller","object":{"name":"default"},"namespace":"","name":"default","reconcileID":"fbb89a96-3fa5-4842-87c0-755cd01aef91"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1839296]

goroutine 735 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:118 +0x1f4
panic({0x1ede680, 0x39e8280})
        /usr/local/go-cgo/src/runtime/panic.go:838 +0x207
github.com/tigera/operator/pkg/render.(*apiServerComponent).hostNetwork(...)
        /go/src/github.com/tigera/operator/pkg/render/apiserver.go:889
github.com/tigera/operator/pkg/render.(*apiServerComponent).apiServerDeployment(0xc0018faea0)
        /go/src/github.com/tigera/operator/pkg/render/apiserver.go:806 +0x156
github.com/tigera/operator/pkg/render.(*apiServerComponent).Objects(0xc0018faea0)
        /go/src/github.com/tigera/operator/pkg/render/apiserver.go:201 +0x130b
github.com/tigera/operator/pkg/controller/utils.componentHandler.CreateOrUpdateOrDelete({{0x28ff940, 0xc0009e5d10}, 0xc00031d9d0, {0x2906520, 0xc001ba2000}, {{0x28fb718, 0xc00
0533880}, 0x0}}, {0x28f8830, 0xc000056038}, ...)
        /go/src/github.com/tigera/operator/pkg/controller/utils/component.go:218 +0x216
github.com/tigera/operator/pkg/controller/apiserver.(*ReconcileAPIServer).Reconcile(0xc0003da480, {0x28f88a0, 0xc001655b60}, {{{0x0?, 0x10?}, {0xc001cbccd6?, 0x57e547?}}})
        /go/src/github.com/tigera/operator/pkg/controller/apiserver/apiserver_controller.go:473 +0x376d
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x28f87f8?, {0x28f88a0?, 0xc001655b60?}, {{{0x0?, 0x20a1440?}, {0xc001cbccd6?, 0x573cd4?}}})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:121 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000b1f9a0, {0x28f87f8, 0xc000a70240}, {0x1f71f00?, 0xc0003fb7c0?})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:320 +0x33c
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000b1f9a0, {0x28f87f8, 0xc000a70240})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:273 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:234 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:230 +0x325
```

## Steps to Reproduce (for bugs)
1. deploy tigera-operator using helm chart v3.25.1 using the following values
```
tigera-operator:
  imagePullSecrets: {}

  installation:
    enabled: true
    kubernetesProvider: "EKS"
    registry: quay.io/

  apiServer:
    enabled: true

  certs:
    node:
      key:
      cert:
      commonName:
    typha:
      key:
      cert:
      commonName:
      caBundle:

  # Resource requests and limits for the tigera/operator pod.
  resources:
    requests:
      cpu: 50m
      memory: 150Mi
    limits:
      memory: 150Mi

  # Tolerations for the tigera/operator pod.
  tolerations:
  - effect: NoExecute
    operator: Exists
  - effect: NoSchedule
    operator: Exists
  - effect: "NoSchedule"
    operator: Equal
    key: "SPOT_INSTANCE"
    value: "true"

  # NodeSelector for the tigera/operator pod.
  nodeSelector:
    kubernetes.io/os: linux

  # Custom annotations for the tigera/operator pod.
  podAnnotations: {}

  # Custom labels for the tigera/operator pod.
  podLabels:
    team: platform
    department: technology
    service: tigera-operator

  # Image and registry configuration for the tigera/operator pod.
  tigeraOperator:
    image: tigera/operator
    version: v1.29.0
    registry: quay.io
  calicoctl:
    image: quay.io/calico/ctl
    tag: v3.25.0

```

## Your Environment
* Calico version v3.25.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes EKS 1.23
* Operating System and version: Amazon Linux
