### ISSUE TITLE
calico BGP peer next hop IP address

### ISSUE THREAD

**Issue by asskss** [projectcalico/calico#7762]
Hello, I currently have 4 network cards on a node, namely the internal network and 3 external network cards. This node acts as a peer with the corresponding 3 external network line nodes. The opposite end has been filtered, and only the network card address sent by network card 1 is received by opposite end 1. When opposite end 1 receives the network card 1 address, the next hop IP address is indeed network card 3. Why is it not network card 1?

$calicoctl get bgppeer

```
interface-1       192.168.80.2    calico/peer == "external"   6xxxx   
interface-2       192.168.81.2    calico/peer == "external"   6xxxx  
interface-3       192.168.82.2    calico/peer == "external"   6xxxx 
```

```
$calicoctl get bgpconfiguration default -o yaml
apiVersion: projectcalico.org/v3
kind: BGPConfiguration
metadata:
  name: default
spec:
  asNumber: 6xxxx
  logSeverityScreen: Info
  nodeToNodeMeshEnabled: false
  serviceLoadBalancerIPs:
  - cidr: 199.199.199.199/30
```

```
$k get svc  
NAME         TYPE           CLUSTER-IP      EXTERNAL-IP      PORT(S)        AGE
nginx   LoadBalancer   10.190.99.99   199.199.199.199   80:39999/TCP   3d4h
```

Node sends 199.199.199.199 routing to the opposite end, only receiving the routing sent by interface1. Why is the next hop address interface3？
