### ISSUE TITLE
When I started a K8s cluster using IPv6 only mode, the calico node will fall into wrong status. 

### ISSUE THREAD

**Issue by xfyan0408** [projectcalico/calico#7799]
When I started a K8s cluster using IPv6 only mode, the calico node will fall into wrong status. 
It is mainly like:
```
 Warning  Unhealthy  40s   kubelet            Readiness probe failed: calico/node is not ready: BIRD is not ready: Error querying BIRD: unable to connect to BIRDv4 socket: dial unix /var/run/calico/bird.ctl: connect: connection refused
W0617 12:35:45.538842      83 feature_gate.go:241] Setting GA feature gate ServiceInternalTrafficPolicy=true. It will be removed in a future release.
  Warning  Unhealthy  39s  kubelet  Readiness probe failed: calico/node is not ready: BIRD is not ready: Error querying BIRD: unable to connect to BIRDv4 socket: dial unix /var/run/calico/bird.ctl: connect: connection refused
W0617 12:35:46.508603     160 feature_gate.go:241] Setting GA feature gate ServiceInternalTrafficPolicy=true. It will be removed in a future release.

```
## Expected Behavior

Get a k8s cluster  with calico with IPv6-only mode.

## Current Behavior

```Shell
a@sdn233:~/IPv6$ kubectl get pod -A
NAMESPACE     NAME                                      READY   STATUS    RESTARTS      AGE
kube-system   calico-kube-controllers-57b57c56f-dc74k   0/1     Pending   0             6m51s
kube-system   calico-node-tgjwx                         0/1     Running   5 (31s ago)   6m51s
kube-system   coredns-567c556887-h4m85                  0/1     Pending   0             14m
kube-system   coredns-567c556887-stfnp                  0/1     Pending   0             14m
kube-system   etcd-sdn233                               1/1     Running   4             14m
kube-system   kube-apiserver-sdn233                     1/1     Running   3             14m
kube-system   kube-controller-manager-sdn233            1/1     Running   3             14m
kube-system   kube-proxy-8slxg                          1/1     Running   0             14m
kube-system   kube-scheduler-sdn233                     1/1     Running   4             14m

a@sdn233:~/IPv6$ kubectl describe pod -n kube-system calico-node-tgjwx
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  7m35s                  default-scheduler  Successfully assigned kube-system/calico-node-tgjwx to sdn233
  Normal   Pulled     7m35s                  kubelet            Container image "docker.io/calico/cni:v3.25.0" already present on machine
  Normal   Created    7m35s                  kubelet            Created container upgrade-ipam
  Normal   Started    7m34s                  kubelet            Started container upgrade-ipam
  Normal   Pulled     7m33s                  kubelet            Container image "docker.io/calico/cni:v3.25.0" already present on machine
  Normal   Created    7m33s                  kubelet            Created container install-cni
  Normal   Started    7m33s                  kubelet            Started container install-cni
  Normal   Pulling    7m30s                  kubelet            Pulling image "docker.io/calico/node:v3.25.0"
  Normal   Pulled     7m10s                  kubelet            Successfully pulled image "docker.io/calico/node:v3.25.0" in 20.206903044s (20.206926398s including waiting)
  Normal   Created    7m10s                  kubelet            Created container mount-bpffs
  Normal   Started    7m10s                  kubelet            Started container mount-bpffs
  Normal   Pulled     7m4s                   kubelet            Container image "docker.io/calico/node:v3.25.0" already present on machine
  Normal   Created    7m4s                   kubelet            Created container calico-node
  Normal   Started    7m4s                   kubelet            Started container calico-node
  Warning  Unhealthy  6m15s (x7 over 7m3s)   kubelet            Readiness probe failed: calico/node is not ready: BIRD is not ready: Error querying BIRD: unable to connect to BIRDv4 socket: dial unix /var/run/calico/bird.ctl: connect: connection refused
  Warning  Unhealthy  6m5s (x4 over 6m45s)   kubelet            Liveness probe failed: calico/node is not ready: bird/confd is not live: Service bird is not running. Output << down: /etc/service/enabled/bird: 0s, normally up, want up >>
  Warning  Unhealthy  2m35s (x4 over 6m25s)  kubelet            Liveness probe failed: calico/node is not ready: bird/confd is not live: Service bird is not running. Output << down: /etc/service/enabled/bird: 1s, normally up, want up >>

```

kubectl logs -n kube-system calico-node-xxxx, it is too long, I show the end of the output.
```
2023-06-17 12:35:48.907 [INFO][128] felix/health.go 336: Overall health status changed: live=true ready=true
+---------------------------+---------+----------------+-----------------+--------+
|         COMPONENT         | TIMEOUT |    LIVENESS    |    READINESS    | DETAIL |
+---------------------------+---------+----------------+-----------------+--------+
| CalculationGraph          | 30s     | reporting live | reporting ready |        |
| FelixStartup              | -       | reporting live | reporting ready |        |
| InternalDataplaneMainLoop | 1m30s   | reporting live | reporting ready |        |
+---------------------------+---------+----------------+-----------------+--------+
2023-06-17 12:36:46.520 [INFO][127] monitor-addresses/autodetection_methods.go 117: Using autodetected IPv6 address 3001:1::233/64 on matching interface ens41f0
2023-06-17 12:36:50.480 [INFO][128] felix/summary.go 100: Summarising 23 dataplane reconciliation loops over 1m3.9s: avg=28ms longest=316ms (resync-filter-v4,resync-filter-v6,resync-ipsets-v4,resync-ipsets-v6,resync-mangle-v4,resync-mangle-v6,resync-nat-v4,resync-nat-v6,resync-raw-v4,resync-raw-v6,resync-routes-v4,resync-routes-v4,resync-routes-v6,resync-routes-v6,resync-rules-v4,resync-rules-v6,update-ipsets-4,update-ipsets-6)

```

## Possible Solution

configure some parameters I do not know the let the cluster and cni work fine.

## Steps to Reproduce (for bugs)

1. `sudo kubeadm init --config kube-config.yaml`
2. `kubectl apply -f calico-3.26.yaml`

## Context

kubeadm-config.yaml

```
apiVersion: kubeadm.k8s.io/v1beta3
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: abcdef.0123456789abcdef
  ttl: 24h0m0s
  usages:
  - signing
  - authentication
kind: InitConfiguration
localAPIEndpoint: #api server 发布的IP地址和端口，apiserver-advertise-address 不支持双栈
  advertiseAddress: "3002:1::233" # master 节点IP
  bindPort: 6443
nodeRegistration:
  criSocket: unix:///var/run/containerd/containerd.sock
  imagePullPolicy: IfNotPresent
  name: sdn233
  taints: null
---
apiServer:
  timeoutForControlPlane: 4m0s
apiVersion: kubeadm.k8s.io/v1beta3
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controllerManager: {}
dns: {}
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: registry.cn-hangzhou.aliyuncs.com/google_containers
kind: ClusterConfiguration
kubernetesVersion: 1.26.0
networking:
  dnsDomain: cluster.local
  serviceSubnet: "3001:1::1/120"
  podSubnet: "3001:1::1/63"
scheduler: {}
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
bindAddress: "::"
bindAddressHardFail: false
clientConnection:
  acceptContentTypes: ""
  burst: 0
  contentType: ""
  kubeconfig: /var/lib/kube-proxy/kubeconfig.conf
  qps: 0
clusterCIDR: "" # 这个怎么填
configSyncPeriod: 0s
conntrack:
  maxPerCore: null
  min: null
  tcpCloseWaitTimeout: null
  tcpEstablishedTimeout: null
detectLocal:
  bridgeInterface: ""
  interfaceNamePrefix: ""
detectLocalMode: ""
enableProfiling: false
healthzBindAddress: "::"
hostnameOverride: ""
iptables:
  localhostNodePorts: null
  masqueradeAll: false
  masqueradeBit: null
  minSyncPeriod: 0s
  syncPeriod: 0s
ipvs:
  excludeCIDRs: null
  minSyncPeriod: 0s
  scheduler: ""
  strictARP: false
  syncPeriod: 0s
  tcpFinTimeout: 0s
  tcpTimeout: 0s
  udpTimeout: 0s
kind: KubeProxyConfiguration
metricsBindAddress: ""
mode: ""
nodePortAddresses: null
oomScoreAdj: null
portRange: ""
showHiddenMetricsForVersion: ""
winkernel:
  enableDSR: false
  forwardHealthCheckVip: false
  networkName: ""
  rootHnsEndpointName: ""
  sourceVip: ""
---
apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
  anonymous:
    enabled: false
  webhook:
    cacheTTL: 0s
    enabled: true
  x509:
    clientCAFile: /etc/kubernetes/pki/ca.crt
authorization:
  mode: Webhook
  webhook:
    cacheAuthorizedTTL: 0s
    cacheUnauthorizedTTL: 0s
cgroupDriver: systemd
clusterDNS:
- "3001:1::a"
#  - 10.96.0.10 # checkme
clusterDomain: cluster.local
cpuManagerReconcilePeriod: 0s
evictionPressureTransitionPeriod: 0s
fileCheckFrequency: 0s
healthzBindAddress: 127.0.0.1
healthzPort: 10248
httpCheckFrequency: 0s
imageMinimumGCAge: 0s
kind: KubeletConfiguration
logging:
  flushFrequency: 0
  options:
    json:
      infoBufferSize: "0"
  verbosity: 0
memorySwap: {}
nodeStatusReportFrequency: 0s
nodeStatusUpdateFrequency: 0s
rotateCertificates: true
runtimeRequestTimeout: 0s
shutdownGracePeriod: 0s
shutdownGracePeriodCriticalPods: 0s
staticPodPath: /etc/kubernetes/manifests
streamingConnectionIdleTimeout: 0s
syncFrequency: 0s
volumeStatsAggPeriod: 0s
```

calico-3.26.yaml
it's too long, I show the content I modified
```
          "ipam": {
              "type": "calico-ipam",
              "assign_ipv4": "false", 
              "assign_ipv6": "true"
          },
.
.
.
      containers:
        # Runs calico-node container on each Kubernetes node. This
        # container programs network policy and routes on each
        # host.
        - name: calico-node
          image: docker.io/calico/node:v3.26.0
          imagePullPolicy: IfNotPresent
          envFrom:
          - configMapRef:
              # Allow KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT to be overridden for eBPF mode.
              name: kubernetes-services-endpoint
              optional: true
          env:
            # Use Kubernetes API as the backing datastore.
            - name: DATASTORE_TYPE
              value: "kubernetes"
            # Wait for the datastore.
            - name: WAIT_FOR_DATASTORE
              value: "true"
            # Set based on the k8s node name.
            - name: NODENAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            # Choose the backend to use.
            - name: CALICO_NETWORKING_BACKEND
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: calico_backend
            # Cluster type to identify the deployment type
            - name: CLUSTER_TYPE
              value: "k8s,bgp"
            # Auto-detect the BGP IP address.
            - name: IP
              value: "none"
            - name: IP6
              value: "autodetect"
            # Enable IPIP
            - name: CALICO_IPV4POOL_IPIP
              value: "Never"
            # Enable or Disable VXLAN on the default IP pool.
            - name: CALICO_IPV4POOL_VXLAN
              value: "Never"
            # Enable or Disable VXLAN on the default IPv6 IP pool.
            - name: CALICO_IPV6POOL_VXLAN
              value: "Never"
            # Set MTU for tunnel device used if ipip is enabled
            - name: FELIX_IPINIPMTU
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: veth_mtu
            # Set MTU for the VXLAN tunnel device.
            - name: FELIX_VXLANMTU
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: veth_mtu
            # Set MTU for the Wireguard tunnel device.
            - name: FELIX_WIREGUARDMTU
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: veth_mtu
            # The default IPv4 pool to create on startup if none exists. Pod IPs will be
            # chosen from this range. Changing this value after installation will have
            # no effect. This should fall within `--cluster-cidr`.
#            - name: CALICO_IPV4POOL_CIDR
#              value: "192.168.0.0/16"
            - name: CALICO_IPV6POOL_CIDR
              value: "3001:1::1/63"
            # Disable file logging so `kubectl logs` works.
            - name: CALICO_ROUTER_ID
              value: "hash"
            - name: IP6_AUTODETECTION_METHOD
              value: "interface=ens41f0"
              # INTERFACE_NAME=ens33
            - name: CALICO_DISABLE_FILE_LOGGING
              value: "true"
            # Set Felix endpoint to host default action to ACCEPT.
            - name: FELIX_DEFAULTENDPOINTTOHOSTACTION
              value: "ACCEPT"
            # Disable IPv6 on Kubernetes.
            - name: FELIX_IPV6SUPPORT
              value: "true"
            - name: FELIX_HEALTHENABLED
              value: "true"
.
.
.
```

/etc/hosts files

```
yxf@sdn233:~/SRv6-INT$ cat /etc/hosts
127.0.0.1       localhost
::1 localhost
127.0.0.1 sdn233

::1 sdn233
3002:1::233 sdn233

#::1 sdn233
# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

ip a

```
server interface which I can ssh to 
4: eno3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether b4:05:5d:88:d7:74 brd ff:ff:ff:ff:ff:ff
    altname enp26s0f2
    altname ens31f2
    inet 192.168.109.233/24 brd 192.168.109.255 scope global noprefixroute eno3
       valid_lft forever preferred_lft forever
    inet6 fe80::b605:5dff:fe88:d774/64 scope link noprefixroute
       valid_lft forever preferred_lft forever

used for k8s node interface
5: eno4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether b4:05:5d:88:d7:75 brd ff:ff:ff:ff:ff:ff
    altname enp26s0f3
    altname ens31f3
    inet 192.168.75.233/24 brd 192.168.75.255 scope global noprefixroute eno4
       valid_lft forever preferred_lft forever
    inet6 3002:1::233/64 scope global noprefixroute
       valid_lft forever preferred_lft forever
    inet6 fe80::b605:5dff:fe88:d775/64 scope link noprefixroute
       valid_lft forever preferred_lft forever

used for bind calico interface
8: ens41f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 40:a6:b7:36:d0:58 brd ff:ff:ff:ff:ff:ff
    altname enp94s0f0
    inet 192.168.129.233/24 brd 192.168.129.255 scope global noprefixroute ens41f0
       valid_lft forever preferred_lft forever
    inet6 3001:1::233/64 scope global noprefixroute
       valid_lft forever preferred_lft forever
    inet6 fe80::42a6:b7ff:fe36:d058/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
```

## Your Environment

* Calico version 3.26 and 3.25, I tried them all
* Orchestrator version (e.g. kubernetes, mesos, rkt): K8s 1.26.5
* Operating System and version: Ubuntu 20
* Link to your project (optional):
