### ISSUE TITLE
Despite Using Latest version 3.26.1 - Still Csi-node-driver not installed on all of our nodes/node groups -following recent upgrade to Kubernetes 1.23 (toleration link - not working)

### ISSUE THREAD

**Issue by pwyborn** [projectcalico/calico#7802]
With Reference to closed issue [Csi-node-driver not installed on all of our nodes/node groups -following recent upgrade to Kubernetes 1.23 (toleration link - not working) #7685](https://github.com/projectcalico/calico/issues/7685).

- Despite using latest helm release 3.26.1, we are still having issues installing the csi-node-driver on our monitoring node group (it is installed in other node groups):
- The link to the tolerations settings is still not working in the documentation - https://v1-21.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#toleration-v1-core. So it may of course be that I not getting how the toleration config should be

**Comment by pwyborn** [comment]
@coutinhop @mazdakn - can I ask you a question please that might help understanding of the problem.

- I have tried v3.26:

- If I describe nodes in the nodegroups where the csi node driver has successfully been installed. I get:

 ```
Non-terminated Pods:          (32 in total)
  Namespace                   Name                                                         CPU Requests  CPU Limits   Memory Requests  Memory Limits   Age
  ---------                   ----                                                         ------------  ----------   ---------------  -------------   ---
  calico-apiserver            calico-apiserver-74bc4d8d67-xgthb                            0 (0%)        0 (0%)       0 (0%)           0 (0%)          12m
  calico-system               calico-node-xhk5d                                            0 (0%)        0 (0%)       0 (0%)           0 (0%)          73m
  calico-system               calico-typha-d687c9d85-9gnfd                                 0 (0%)        0 (0%)       0 (0%)           0 (0%)          73m
  calico-system               csi-node-driver-n95l4                                        0 (0%)        0 (0%)       0 (0%)           0 (0%)          73m
```

- Whereas nodes on the nodegroup where csi node driver not installed:

```
Non-terminated Pods:          (8 in total)
  Namespace                   Name                                                  CPU Requests  CPU Limits    Memory Requests  Memory Limits  Age
  ---------                   ----                                                  ------------  ----------    ---------------  -------------  ---
  calico-system               calico-node-5ckzm                                     0 (0%)        0 (0%)        0 (0%)           0 (0%)         76m
```
both "calico-apiserver...." and "calico-node-driver...." do not appear.

- Although the nodes in question are there when I do:

` kubctl get node -n calico-apiserver`

strange!
The question maybe is:

- can the driver be linked to/installed on nodes that were not created in the first place using the driver?

**Comment by pwyborn** [comment]
- I have tried the following 2 values.yaml configurations:

1. 

```
imagePullSecrets: {}

installation:
  enabled: true
  kubernetesProvider: "${kubernetes_provider}"


  CSINodeDriverDaemonSet:
    spec:
      template:
        tolerations:
        - key: "monitoring-node"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"


apiServer:
  enabled: true
```
I get the following error message when I terraform apply:
```
│ Error: error validating "": error validating data: ValidationError(Installation.spec): unknown field "CSINodeDriverDaemonSet" in io.tigera.operator.v1.Installation.spec
│
│   with module.tigera_calico.helm_release.tigera_calico,
│   on .terraform/modules/tigera_calico/calico.tf line 137, in resource "helm_release" "tigera_calico":
│  137: resource "helm_release" "tigera_calico" {
```

2. and this:
```
imagePullSecrets: {}

installation:
  enabled: true
  kubernetesProvider: "${kubernetes_provider}"


CSINodeDriverDaemonSet:
   spec:
      template:
        tolerations:
         - key: "monitoring-node"
           operator: "Equal"
           value: "true"
           effect: "NoSchedule"


apiServer:
  enabled: true
```
This has no error messages and terraform applies ok - but seems to have affect
