### ISSUE TITLE
FQDN not solved when global network policy is applied

### ISSUE THREAD

**Issue by beltran-rubo** [projectcalico/calico#7828]
Im trying to block egress connections following the [Calico recommendation](https://docs.tigera.io/calico/latest/network-policy/get-started/kubernetes-default-deny#enable-default-deny-calico-global-network-policy-non-namespaced) for all namespaces. Applying that policy works properly and DNS are resolved but not the FQDN.

This works from a pod: `nslookup mongodb.myrelease`
This does not work: `nslookup mongodb.myrelease.svc.cluster.local`

Removing the global network policy works properly so it is not a K8s issue.

## Expected Behavior
The FQDN works properly after applying the global network policies.

## Current Behavior
The FQDN does not work after applying the global network policies recommended by the docs.

## Steps to Reproduce (for bugs)
1. Install calico on top of GKE
2. Apply the [Calico recommendation from docs](https://docs.tigera.io/calico/latest/network-policy/get-started/kubernetes-default-deny#enable-default-deny-calico-global-network-policy-non-namespaced) for blocking egress connection
3. Deploy a pod and check if it has connectivity through FQDN

## Your Environment
* Calico version: 3.26.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): GKE 1.26

**Comment by balajisa09** [comment]
Can you mention the global network policy manifest here?

**Comment by beltran-rubo** [comment]
```
apiVersion: crd.projectcalico.org/v1
kind: GlobalNetworkPolicy
metadata:
  name: deny-all-except-system-and-dns-policy
spec:
  namespaceSelector: has(projectcalico.org/name) && projectcalico.org/name not in {"kube-system", "calico-system", "tigera-system"}
  types:
    - Egress
  egress:
    # allow all namespaces to communicate to DNS pods
    - action: Allow
      protocol: UDP
      destination:
        selector: 'k8s-app == "kube-dns"'
        ports:
          - 53
---
apiVersion: crd.projectcalico.org/v1
kind: GlobalNetworkPolicy
metadata:
  name: allow-inter-app-policy
spec:
  namespaceSelector: all()
  types:
    - Egress
  egress:
    - action: Allow
      destination:
        nets:
          - 10.0.0.0/8 
 ```

**Comment by balajisa09** [comment]
Also can you mention the nslookup/dig verbose output for both FQDN and partial DN. Would help more in troubleshooting this.

**Comment by ruospalo** [comment]
`nslookup mongodb.myrelease`

```
kubectl exec -i -t dnsutils -n deployment-omcsq -- nslookup mongodb.deployment-omcsq -debug
Server:		10.132.0.10
Address:	10.132.0.10#53

------------
    QUESTIONS:
	mongodb.deployment-omcsq.deployment-omcsq.svc.cluster.local, type = A, class = IN
    ANSWERS:
    AUTHORITY RECORDS:
    ->  cluster.local
	origin = ns.dns.cluster.local
	mail addr = hostmaster.cluster.local
	serial = 1688364000
	refresh = 28800
	retry = 7200
	expire = 604800
	minimum = 60
	ttl = 60
    ADDITIONAL RECORDS:
------------
** server can't find mongodb.deployment-omcsq.deployment-omcsq.svc.cluster.local: NXDOMAIN
Server:		10.132.0.10
Address:	10.132.0.10#53

------------
    QUESTIONS:
	mongodb.deployment-omcsq.svc.cluster.local, type = A, class = IN
    ANSWERS:
    ->  mongodb.deployment-omcsq.svc.cluster.local
	internet address = 10.132.4.182
	ttl = 30
    AUTHORITY RECORDS:
    ADDITIONAL RECORDS:
------------
Name:	mongodb.deployment-omcsq.svc.cluster.local
Address: 10.132.4.182

command terminated with exit code 1
```

`nslookup mongodb.myrelease.svc.cluster.local`

```
kubectl exec -i -t dnsutils -n deployment-omcsq -- nslookup mongodb.deployment-omcsq -debug
Server:		10.132.0.10
Address:	10.132.0.10#53

------------
    QUESTIONS:
	mongodb.deployment-omcsq.deployment-omcsq.svc.cluster.local, type = A, class = IN
    ANSWERS:
    AUTHORITY RECORDS:
    ->  cluster.local
	origin = ns.dns.cluster.local
	mail addr = hostmaster.cluster.local
	serial = 1688364000
	refresh = 28800
	retry = 7200
	expire = 604800
	minimum = 60
	ttl = 60
    ADDITIONAL RECORDS:
------------
** server can't find mongodb.deployment-omcsq.deployment-omcsq.svc.cluster.local: NXDOMAIN
Server:		10.132.0.10
Address:	10.132.0.10#53

------------
    QUESTIONS:
	mongodb.deployment-omcsq.svc.cluster.local, type = A, class = IN
    ANSWERS:
    ->  mongodb.deployment-omcsq.svc.cluster.local
	internet address = 10.132.4.182
	ttl = 30
    AUTHORITY RECORDS:
    ADDITIONAL RECORDS:
------------
Name:	mongodb.deployment-omcsq.svc.cluster.local
Address: 10.132.4.182

command terminated with exit code 1
➜  parent kubectl exec -i -t dnsutils -n deployment-omcsq -- nslookup mongodb.deployment-omcsq.svc.cluster.local -debug
Server:		10.132.0.10
Address:	10.132.0.10#53

------------
    QUESTIONS:
	mongodb.deployment-omcsq.svc.cluster.local.deployment-omcsq.svc.cluster.local, type = A, class = IN
    ANSWERS:
    AUTHORITY RECORDS:
    ->  cluster.local
	origin = ns.dns.cluster.local
	mail addr = hostmaster.cluster.local
	serial = 1688364000
	refresh = 28800
	retry = 7200
	expire = 604800
	minimum = 60
	ttl = 60
    ADDITIONAL RECORDS:
------------
** server can't find mongodb.deployment-omcsq.svc.cluster.local.deployment-omcsq.svc.cluster.local: NXDOMAIN
Server:		10.132.0.10
Address:	10.132.0.10#53

------------
    QUESTIONS:
	mongodb.deployment-omcsq.svc.cluster.local.svc.cluster.local, type = A, class = IN
    ANSWERS:
    AUTHORITY RECORDS:
    ->  cluster.local
	origin = ns.dns.cluster.local
	mail addr = hostmaster.cluster.local
	serial = 1688364000
	refresh = 28800
	retry = 7200
	expire = 604800
	minimum = 60
	ttl = 60
    ADDITIONAL RECORDS:
------------
** server can't find mongodb.deployment-omcsq.svc.cluster.local.svc.cluster.local: NXDOMAIN
Server:		10.132.0.10
Address:	10.132.0.10#53

------------
    QUESTIONS:
	mongodb.deployment-omcsq.svc.cluster.local.cluster.local, type = A, class = IN
    ANSWERS:
    AUTHORITY RECORDS:
    ->  cluster.local
	origin = ns.dns.cluster.local
	mail addr = hostmaster.cluster.local
	serial = 1688364000
	refresh = 28800
	retry = 7200
	expire = 604800
	minimum = 60
	ttl = 60
    ADDITIONAL RECORDS:
------------
** server can't find mongodb.deployment-omcsq.svc.cluster.local.cluster.local: NXDOMAIN
;; connection timed out; no servers could be reached

command terminated with exit code 1
```

**Comment by coutinhop** [comment]
@ruospalo from the output you posted it seems like the "right" FQDN is never queried? it tries `mongodb.deployment-omcsq.svc.cluster.local.deployment-omcsq.svc.cluster.local` and fails, then `mongodb.deployment-omcsq.svc.cluster.local.svc.cluster.local`, then `mongodb.deployment-omcsq.svc.cluster.local.cluster.local` and stops.

Could you try looking up with a trailing period, i.e. `nslookup mongodb.myrelease.svc.cluster.local.`, per https://unix.stackexchange.com/questions/422559/duplicate-domain-name-in-dns-query?

**Comment by ruospalo** [comment]
We found the root cause and was not related to CALICO. 
Our charts was making some request to 169.254.169.254, needed for getting the metadata per cloud. Whitelisting this ip, finally resolves FQDN and works as expected.

Sorry for the inconvenience

```
---
apiVersion: crd.projectcalico.org/v1
kind: GlobalNetworkPolicy
metadata:
  name: allow-inter-app-policy
spec:
  namespaceSelector: all()
  types:
    - Egress
  egress:
    - action: Allow
      destination:
        nets:
          - 10.0.0.0/8
          - 169.254.169.254/32 # Needed for getting the meta-data per cloud (GKE).
```
