### ISSUE TITLE
After migrating to Calico from Flannel, X-Forwarded-For headers set by the front proxy container are invalid

### ISSUE THREAD

**Issue by zaneclaes** [projectcalico/calico#7854]
My on-prem cluster uses `MetalLB` and a front proxy (Envoy) within a pod. Previously, when using Flannel, the front proxy was able to see the original source IP address because `externalTrafficPolicy: Local` is set on the Kubernetes service for the front proxy. Since switching to Calico, the front proxy instead reports either a `10.244.0.0/16` or a `169.254.0.0/16` IP in its `X-Forwarded-For` header.

## Expected Behavior
The Flannel migration should work the same as it did before.

## Current Behavior
Calico does not appear to properly report the originating IP address to the Envoy container.

## Possible Solution
I'm not sure how to fix this; I'm not familiar enough to know which Calico setting I even need to use here, despite reading docs — I can't make heads or tails of `ipipMode` and `vxlanMode`.

## Steps to Reproduce (for bugs)
Sample service:

```
apiVersion: v1
kind: Service
metadata:
  name: switchboard
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.100
  externalTrafficPolicy: Local # "pods can see the real source IP address of incoming connections."
  ports:
  - name: http
    port: 80
    targetPort: 80
```

And here is my pool:

```
apiVersion: projectcalico.org/v3
items:
- apiVersion: projectcalico.org/v3
  kind: IPPool
  metadata:
    creationTimestamp: "2023-07-10T20:54:28Z"
    name: default-ipv4-ippool
    resourceVersion: "123754290"
    uid: d11ad29c-938e-4719-acfd-c6dc4627e762
  spec:
    allowedUses:
    - Workload
    - Tunnel
    blockSize: 26
    cidr: 10.244.0.0/16
    ipipMode: Always
    natOutgoing: true
    nodeSelector: all()
    vxlanMode: Never
kind: IPPoolList
metadata:
  resourceVersion: "123865121"
```

## Context
This prevents me from using IP-based security in my network. Previously I had whitelisted the internal `192.168.1.0/24` range to allow my home network secure access to login to certain selfhosted services. 

## Your Environment
* Calico version: latest (?) just installed
* Orchestrator version (e.g. kubernetes, mesos, rkt): 1.27.3
* Operating System and version: Linux
