### ISSUE TITLE
No way to use existing secrets for imagePullSecrets in helm chart

### ISSUE THREAD

**Issue by bogdanzel** [projectcalico/calico#7876]
## Expected Behavior

We should have the ability to use existing secrets for the **imagePullSecrets** option in Helm charts, allowing users to leverage private registries for Docker images securely.
## Current Behavior

Currently, when we want to use a private registry for Docker images of Calico, we have to store sensitive tokens for Helm in Git, which is not recommended due to security concerns. This poses security risks and is not recommended practice.
```
  imagePullSecrets:
    dockertoken: '{"auths": {"private-registry.com": {"auth": "tokenData"}}}'
  installation:
    registry: "private-registry"
```
The current approach of using the **imagePullSecrets** block under the **installation** group seems ineffective and does not spread the image pull secrets across all relevant namespaces and pods.
```
  imagePullSecrets:
    dockertoken: '{"auths": {"private-registry.com": {"auth": "tokeData"}}}'
  installation:
    imagePullSecrets:
     - name: dockertoken
    registry: "private-registry"
```
The only way as I understand how to propagate image pull secret across all deployments, daemonsets, etc is to patch the **tigera-operator** service account in tigera-operator namespace
```
>kubectl get sa tigera-operator -n tigera-operator -o yaml
apiVersion: v1
imagePullSecrets:
- name: dockertoken
kind: ServiceAccount
metadata:
  annotations:
  ...........
```
It can be done only by adding **imagePullSecret** token with sensitive data over the Installation block
```
  imagePullSecrets:
    dockertoken: '{"auths": {"private-registry.com": {"auth": "tokeData"}}}'
  installation:
    registry: "private-registry"
```
## Possible Solution
To address this issue, it would be beneficial to introduce a new parameter for the **imagePullSecrets** option in the Helm charts that allows users to reuse existing secrets from Kubernetes. This will enhance security and ease the process of using private registries to pull Calico images. 
The proposed solution would involve introducing two new parameters: **existingSecret** and **existingSecretKey**, which will refer to an existing Kubernetes secret containing the required image pull secret
Example:
```
  imagePullSecrets:
      existingSecret: "secretName"
      existingSecretKey: "secretKey"
  installation:
    registry: "private-registry"
```
By implementing this solution, users can securely use their existing Kubernetes secrets for image pull operations, thereby eliminating the need to store sensitive token data in the Helm configuration.
## Your Environment

* Calico version: 3.26.1
* Kubernetes v1.25
* Operating System and version: Ubuntu 22.04.2 LTS
## Final words
I believe this enhancement will not only resolve the "docker.io rate limit issue" but also improve overall security and ease of use for Calico deployments using private registries.
