### ISSUE TITLE
external server (not in k8s but in network ) not accessible from inside of service pod (ping, curl tried)

### ISSUE THREAD

**Issue by aayushave** [projectcalico/calico#7878]
```
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: allow-egress-external
  namespace: dev
spec:
  selector: app == 'first-service'
  types:
    - Egress
  egress:
    - action: Allow
      destination:
        nets:
          - 192.168.20.17/32
```

i applied this egress policy

and calico network ippool that was installed yaml is
 
```
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  # Configures Calico networking.
  calicoNetwork:
    # Note: The ipPools section cannot be modified post-install.
    ipPools:
    - blockSize: 26
      cidr: 192.168.0.0/16
      encapsulation: VXLANCrossSubnet
      natOutgoing: Enabled
```

traffic to 192.168.20.17 is not allowed
i see cni.projectcalico.org/podIP: 192.168.235.157/32  assigned to the first-service pod 

## Current Behavior
ip 192.168.20.17 is an non kuberntes server and is in network is used to request files 
even with or without egress config it is not working, 

## Expected Behavior
ip 192.168.20.17 is an non kuberntes server and is in network is used to request files  should be accesible from inside the pod first service
