### ISSUE TITLE
floatingIP not working

### ISSUE THREAD

**Issue by gabrik** [projectcalico/calico#7894]
Hi all,

I was experimenting with the floating IPs but I didn't manage to have it working.
I did follow [the guide](https://docs.tigera.io/calico/latest/networking/ipam/add-floating-ip#configure-a-pod-to-use-a-floating-ip) but I cannot ping the pod, neither access to the service it is providing (a basic nginx just for testing)

I'm pretty sure I'm doing something wrong, but I was unable to debug further from the container/host. 
Any help would be more than appreciated. 

## Expected Behavior
I'm able to access the service exposed from outside the cluster

## Current Behavior
I cannot access the service provided by the pool

## Steps to Reproduce (for bugs)
1. Enable floating IPs
```
cni_network_config:
----
{
  "name": "k8s-pod-network",
  "cniVersion": "0.3.1",
  "plugins": [
    {
      "type": "calico",
      "log_level": "info",
      "log_file_path": "/var/log/calico/cni/cni.log",
      "datastore_type": "kubernetes",
      "nodename": "__KUBERNETES_NODE_NAME__",
      "mtu": __CNI_MTU__,
      "ipam": {
          "type": "calico-ipam"
      },
      "policy": {
          "type": "k8s"
      },
      "kubernetes": {
          "kubeconfig": "__KUBECONFIG_FILEPATH__"
      },
      "feature_control": {
          "floating_ips": true
      }
    },
    {
      "type": "portmap",
      "snat": true,
      "capabilities": {"portMappings": true}
    },
    {
      "type": "bandwidth",
      "capabilities": {"bandwidth": true}
    }
  ]
}
```

2.  Create IPv4 pool:
```
kubectl calico get ippools my.ippool-1 -o yaml
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  creationTimestamp: "2023-07-31T15:08:16Z"
  name: my.ippool-1
  resourceVersion: "4982"
  uid: 52436049-4c25-4bd8-9efe-a64df2b42363
spec:
  allowedUses:
  - Workload
  - Tunnel
  blockSize: 26
  cidr: 192.168.86.0/24
  ipipMode: Always
  natOutgoing: true
  nodeSelector: all()
  vxlanMode: Never

```

3. create a deployment
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        "cni.projectcalico.org/floatingIPs": "[\"192.168.86.222\"]"
        # "cni.projectcalico.org/ipAddrs": "[\"192.168.86.222\"]" tried with and without, no changes
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

```
4. from another machine: `curl http://192.168.86.222` 

## Context
I was trying to understand if calico and floating IP are a solution to my problem of exposing a service outside of K8s cluster
## Your Environment
* Calico version : v.3.26.1
* Orchestrator version: v1.27.3+k3s1
* Operating System and version: Ubuntu 22.04.2 
* k3s node ip is 192.168.86.97, connected to the 192.168.86.0/24 subnet, the machine trying to ping is attached to the same subnet.
```
kubectl get nodes -o wide
NAME         STATUS   ROLES                  AGE    VERSION        INTERNAL-IP     EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
k8s-master   Ready    control-plane,master   138m   v1.27.3+k3s1   192.168.86.97   <none>        Ubuntu 22.04.2 LTS   5.15.0-78-generic   containerd://1.7.1-k3s1
```
