### ISSUE TITLE
Calico NetworkPolicy doesn't seem to be able to take precedence over GlobalNetworkPolicy

### ISSUE THREAD

**Issue by Chahdro** [projectcalico/calico#7896]
## Expected Behavior

The Calico NetworkPolicy with a higher order should override any conflicting rules defined in the GlobalNetworkPolicy, giving us more fine-grained control over network policies at the namespace level. Here i'm trying to block ingress access from internet for all namespaces except `"kube-system", "calico-system", "calico-apiserver"` and allow  for `my-app` namespace
```yaml
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: default-allow-system
spec:
  namespaceSelector: has(projectcalico.org/name) && projectcalico.org/name in {"kube-system", "calico-system", "calico-apiserver"}
  order: 1000
  types:
  - Ingress
  ingress:
  - action: Allow
---
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: default-deny-internet
spec:
  order: 10
  types:
  - Ingress
  ingress:
  # Deny internet access
  - action: Deny
    protocol: TCP
    source:
      nets:
      - 0.0.0.0/0
  # Allow ingress in all kubernetes resources
  - action: Allow
    protocol: TCP
    source:
      selector: all()
---
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: default-policy-ingress
  namespace: my-app
spec:
  order: 100
  types:
    - Ingress
  ingress:
    - action: Allow
      protocol: TCP
      source:
        nets:
          - 0.0.0.0/0
```

## Current Behavior

When using Calico NetworkPolicy with a higher order value, it is expected to take precedence over GlobalNetworkPolicy rules. However, it seems that the GlobalNetworkPolicy is still enforcing its rules. Pods in namespace `my-app` doesn't received call from internet. 

## Your Environment

* CNI : calico
* Calico version : 3.26.1
* EKS 1.27

**Comment by caseydavenport** [comment]
```
  ingress:
  # Deny internet access
  - action: Deny
    protocol: TCP
    source:
      nets:
      - 0.0.0.0/0
  # Allow ingress in all kubernetes resources
  - action: Allow
    protocol: TCP
    source:
      selector: all()
```

^ This is going to deny all traffic and the second rule will never get hit.

Also, I think you `order` numbers are backwards - the higher order takes a lower priority. So in the example you gave, the policies will be executed in this order:

- 10: default-deny-internet GNP
- 100: default-policy-ingress NP
- 1000: default-allow-system GNP
