### ISSUE TITLE
No connectivity between pods across nodes

### ISSUE THREAD

**Issue by tusooa** [projectcalico/calico#7924]
Cannot ping pod ip on other nodes from either the host or inside a pod.

## Expected Behavior

Should be able to ping pod ip on other nodes from either the host or inside a pod.

## Current Behavior

Cannot ping pod ip on other nodes from either the host or inside a pod.

## Possible Solution

No idea.

## Steps to Reproduce (for bugs)

There are three nodes in question, all connected to public internet (eth0) and a private subnet, with ip addresses 10.0.0.4-6.

1. Bootstrap a cluster using kubeadm
```
# kubeadm-config.yaml
apiVersion: kubeadm.k8s.io/v1beta3
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: xxxxxx
  ttl: 24h0m0s
  usages:
  - signing
  - authentication
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 10.0.0.4
  bindPort: 6443
nodeRegistration:
  criSocket: unix:///var/run/containerd/containerd.sock
  imagePullPolicy: IfNotPresent
  name: xxxxxx
  taints: null
---
apiServer:
  timeoutForControlPlane: 4m0s
apiVersion: kubeadm.k8s.io/v1beta3
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controllerManager: {}
dns: {}
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: registry.k8s.io
kind: ClusterConfiguration
kubernetesVersion: 1.27.0
controlPlaneEndpoint: cluster-endpoint
networking:
  dnsDomain: cluster.local
  podSubnet: 10.97.0.0/16
  serviceSubnet: 10.96.0.0/16
scheduler: {}
---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: systemd
```
2. Using https://docs.tigera.io/calico/latest/getting-started/kubernetes/self-managed-onprem/onpremises to deploy calico on the cluster
```
# This section includes base Calico installation configuration.
# For more information, see: https://projectcalico.docs.tigera.io/master/reference/installation/api#operator.tigera.io/v1.Installation
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  # Configures Calico networking.
  calicoNetwork:
    # Note: The ipPools section cannot be modified post-install.
    ipPools:
    - blockSize: 26
      cidr: 10.97.0.0/16
      encapsulation: VXLANCrossSubnet
      natOutgoing: Enabled
      nodeSelector: all()
    nodeAddressAutodetectionV4:
      cidrs: ['10.0.0.0/16']
---

# This section configures the Calico API server.
# For more information, see: https://projectcalico.docs.tigera.io/master/reference/installation/api#operator.tigera.io/v1.APIServer
apiVersion: operator.tigera.io/v1
kind: APIServer
metadata:
  name: default
spec: {}
```

3. Create a deployment as specified in the docs
```
kubectl create deployment pingtest --image=busybox --replicas=3 -- sleep infinity
kubectl get pods --selector=app=pingtest --output=wide
```
4. Try to ping the pod on the current node, and it works. Trying to ping the pods on other nodes will fail:

```
$ ip route get 10.97.180.69 # pod on the same node
10.97.180.69 dev cali30c69fa7d70 src <public ip> uid 1000
    cache

$ ip route get 10.97.118.132 # pod on another node
10.97.118.132 via 172.31.1.1 dev eth0 src <public ip> uid 1000
    cache
```

```
$ sudo ~/calicoctl node status
Calico process is running.

IPv4 BGP status
+--------------+-------------------+-------+----------+-------------+
| PEER ADDRESS |     PEER TYPE     | STATE |  SINCE   |    INFO     |
+--------------+-------------------+-------+----------+-------------+
| 10.0.0.5     | node-to-node mesh | up    | 16:49:23 | Established |
| 10.0.0.6     | node-to-node mesh | up    | 16:49:25 | Established |
+--------------+-------------------+-------+----------+-------------+

IPv6 BGP status
No IPv6 peers found.
```

```
$ kubectl get po -A
NAMESPACE          NAME                                       READY   STATUS    RESTARTS        AGE
calico-apiserver   calico-apiserver-d4f88f6d8-pz9zv           1/1     Running   0               73m
calico-apiserver   calico-apiserver-d4f88f6d8-rwb77           1/1     Running   0               73m
calico-system      calico-kube-controllers-696567b496-br4km   1/1     Running   0               73m
calico-system      calico-node-44vzt                          1/1     Running   0               73m
calico-system      calico-node-dgtst                          1/1     Running   0               73m
calico-system      calico-node-k6bgm                          1/1     Running   0               73m
calico-system      calico-typha-6c9cd96d6f-2ztbl              1/1     Running   0               73m
calico-system      calico-typha-6c9cd96d6f-89hb5              1/1     Running   0               73m
calico-system      csi-node-driver-bjqpp                      2/2     Running   0               73m
calico-system      csi-node-driver-gpjg6                      2/2     Running   0               73m
calico-system      csi-node-driver-r2vdq                      2/2     Running   0               73m
default            pingtest-76c67875b5-9szds                  1/1     Running   0               73m
default            pingtest-76c67875b5-c7g9n                  1/1     Running   0               73m
default            pingtest-76c67875b5-qwvng                  1/1     Running   0               73m
kube-system        coredns-5d78c9869d-6pgw4                   1/1     Running   0               4h46m
kube-system        coredns-5d78c9869d-jzjm5                   1/1     Running   0               4h46m
kube-system        etcd-(xxxxxx)                             1/1     Running   3 (4h17m ago)   4h43m
kube-system        etcd-(xxxxxx)                            1/1     Running   2               4h46m
kube-system        etcd-(xxxxxx)                            1/1     Running   1 (4h19m ago)   4h36m
kube-system        kube-apiserver-(xxxxxx)                     1/1     Running   7 (4h17m ago)   4h43m
kube-system        kube-apiserver-(xxxxxx)                     1/1     Running   4 (4h17m ago)   4h46m
kube-system        kube-apiserver-(xxxxxx)                   1/1     Running   3 (4h17m ago)   4h36m
kube-system        kube-controller-manager-(xxxxxx)              1/1     Running   4 (4h17m ago)   4h43m
kube-system        kube-controller-manager-(xxxxxx)           1/1     Running   7 (4h18m ago)   4h46m
kube-system        kube-controller-manager-(xxxxxx)           1/1     Running   3 (4h17m ago)   4h36m
kube-system        kube-proxy-26cg2                           1/1     Running   1 (4h17m ago)   4h43m
kube-system        kube-proxy-djgxv                           1/1     Running   0               4h46m
kube-system        kube-proxy-g8lz6                           1/1     Running   1 (4h19m ago)   4h36m
kube-system        kube-scheduler-(xxxxxx)                      1/1     Running   5 (4h17m ago)   4h42m
kube-system        kube-scheduler-(xxxxxx)                  1/1     Running   8 (4h18m ago)   4h46m
kube-system        kube-scheduler-(xxxxxx)                   1/1     Running   3 (4h17m ago)   4h36m
tigera-operator    tigera-operator-5f4668786-9d9m6            1/1     Running   0               73m
```

## Context

Just to have connectivity across the cluster.

## Your Environment

* Calico version 3.26
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes 1.27.0
* Operating System and version: Ubuntu 22.04 (Linux 5.15.0-78-generic)
* Link to your project (optional):
