### ISSUE TITLE
 The network speed of the pod cannot reach the speed  of the baremetal, only half the speed of the baremetal server 

### ISSUE THREAD

**Issue by ming12713** [projectcalico/calico#7926]
calico version: v3.26.1
kubernetes version: v1.26.6
calico installation spec
```
spec:
  calicoNetwork:
    bgp: Enabled
    hostPorts: Enabled
    ipPools:
    - blockSize: 26
      cidr: 10.244.0.0/16
      disableBGPExport: false
      encapsulation: VXLANCrossSubnet
      natOutgoing: Enabled
      nodeSelector: all()
    linuxDataplane: Iptables
    multiInterfaceMode: None
    nodeAddressAutodetectionV4:
      firstFound: true
```
**iperf3 testing in pod** 
1. iperf3 server pod running on airflow01 node with 10g nic 
2. iperf3 client pod running on airflow02 node with 10g nic
![img_v2_a1669bf3-63cc-41ae-ab47-afaab52e998g](https://github.com/projectcalico/calico/assets/5196113/f5af438d-72f2-46da-a289-79e5b2b66be2)

**iperf3 testing in baremetal node** 
1. iperf3 server running on airflow01 node with 10g nic 
2. iperf3 client  running on airflow02 node with 10g nic
![img_v2_c71ffefa-8297-4501-af07-3611e88162ag](https://github.com/projectcalico/calico/assets/5196113/dabfc7b7-745d-4db5-836b-97a1134a3781)
