### ISSUE TITLE
The strange calico-kube-controller v3.26.1 behaviour in a cluster with s390x worker nodes.

### ISSUE THREAD

**Issue by liudalibj** [projectcalico/calico#7957]
When we use Tigera Operator to deploy calico to one cluster with s390x worker nodes. we found follow issue:
```
➜ kubectl get pods -n calico-system
NAME                                      READY   STATUS             RESTARTS        AGE
calico-kube-controllers-bd556c67b-x7djm   0/1     CrashLoopBackOff   339 (83s ago)   20h
calico-node-2gtvw                         1/1     Running            0               20h
calico-node-k4nh5                         1/1     Running            0               20h
calico-typha-7669668c5c-fcx9x             1/1     Running            0               20h
```
```
kubectl logs -f calico-kube-controllers-bd556c67b-x7djm -n calico-system
2023-08-23 08:52:05.818 [INFO][1] main.go 107: Loaded configuration from environment config=&config.Config{LogLevel:"info", WorkloadEndpointWorkers:1, ProfileWorkers:1, PolicyWorkers:1, NodeWorkers:1, Kubeconfig:"", DatastoreType:"kubernetes"}
W0823 08:52:05.819569       1 client_config.go:618] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
2023-08-23 08:52:05.819 [INFO][1] main.go 131: Ensuring Calico datastore is initialized
2023-08-23 08:52:05.819 [ERROR][1] status.go 130: Failed to prepare directory: mkdir /status: permission denied
2023-08-23 08:52:05.820 [WARNING][1] status.go 65: Failed to write status error=mkdir /status: permission denied
2023-08-23 08:52:05.969 [INFO][1] main.go 157: Calico datastore is initialized
2023-08-23 08:52:05.969 [ERROR][1] status.go 130: Failed to prepare directory: mkdir /status: permission denied
2023-08-23 08:52:05.969 [WARNING][1] status.go 65: Failed to write status error=mkdir /status: permission denied
2023-08-23 08:52:05.969 [INFO][1] main.go 194: Getting initial config snapshot from datastore
2023-08-23 08:52:06.124 [INFO][1] main.go 197: Got initial config snapshot
```
## Expected Behavior
the `calico-kube-controllers` is running status in a cluster with s390x worker nodes.

## Current Behavior
the `calico-kube-controllers` is not running status with error logs `mkdir /status: permission denied`

## Possible Solution
Compare https://github.com/projectcalico/calico/blob/master/kube-controllers/Dockerfile.s390x
vs
https://github.com/projectcalico/calico/blob/master/kube-controllers/Dockerfile.amd64
There are something are missed.
```
# Make sure the status and pprof files are owned by our user.
RUN mkdir /status /profiles
RUN touch /status/status.json && chown 999 /status/status.json
RUN touch /profiles/mem.pprof && chown 999 /profiles/mem.pprof
RUN touch /profiles/cpu.pprof && chown 999 /profiles/cpu.pprof
...
USER 999
```

https://github.com/projectcalico/calico/pull/7955
https://github.com/projectcalico/calico/pull/7956

## Steps to Reproduce (for bugs)

1. Create one IKS 1.27 cluster with Z worker nodes
3. Deploy test yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: calico-kube-controllers-verify
  name: calico-kube-controllers-verify
  namespace: kube-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      k8s-app: calico-kube-controllers-verify
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: calico-kube-controllers-verify
      name: calico-kube-controllers-verify
      namespace: kube-system
    spec:
      containers:
      - env:
        - name: ENABLED_CONTROLLERS
          value: node
        - name: DATASTORE_TYPE
          value: kubernetes
        image: quay.io/calico/kube-controllers:v3.26.1
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - /usr/bin/check-status
            - -l
          failureThreshold: 6
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: calico-kube-controllers-verify
        readinessProbe:
          exec:
            command:
            - /usr/bin/check-status
            - -r
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            memory: 3Gi
          requests:
            cpu: 10m
            memory: 25Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          runAsGroup: 0
          runAsNonRoot: true
          runAsUser: 999
          seccompProfile:
            type: RuntimeDefault
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      priorityClassName: system-cluster-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: calico-kube-controllers
      serviceAccountName: calico-kube-controllers
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
```

## Your Environment

* Calico version v3.26.1 
* Orchestrator version (e.g. kubernetes, mesos, rkt): IKS kubernetes v1.27
* Operating System and version: s390x worker node
* Link to your project (optional):
