### ISSUE TITLE
Tigera operator Installation CRD not updating the status of the BGPEnabled field on mixed OS clusters

### ISSUE THREAD

**Issue by jayunit100** [projectcalico/calico#7986]
Context: Windows clusters dont run BGP typically by default since BGP isnt something you can "just do" in a container (but this makes me wonder - could bgp run as a host process container?)

Note in this cluster i have one windows node, one linux node.  The windows node is happy, but the linux nodes are trying really hard to get BGP working   and that results in linux nodes being marked as not Ready (actually, they are ready in that they can indeed support CNI functionality)>

So, the goal would simply be for the tigera operator to not force BGPEnabled as the status on the clusters...


## Expected Behavior

```
kubo@uOFLhGS9YBJ3y:~/calico$ kubectl get  installation -o yaml | grep -i bgp -B 2 -A 2                                                                                                                                                                
  spec:                                                                                                                                                                                                                                               
    calicoNetwork:                                                                                                                                                                                                                                    
      bgp: Disabled                      <---------- set the BGP to disabled here                                                                                                                                                                                                              
      hostPorts: Enabled                                                                                                                                                                                                                              
      ipPools:                                                                                                                                                                                                                                        
      - blockSize: 26                                                                                                                                                                                                                                 
        cidr: 100.96.1.0/16                                                                                                                                                                                                                           
        disableBGPExport: false                                                                                                                                                                                                                       
        encapsulation: VXLANCrossSubnet                                                                                                                                                                                                               
        natOutgoing: Enabled        
```
I'd expect the **status** of this CRD to become **bgp: Disabled** immediately, but that doesnt happen... instead i see...



## Current Behavior


```                                                                                                                                                                                                                  
--                                  
                                                                                                                                                                                                                  
    computed:                                                                                                                                                                                                                                         
      calicoNetwork:                                                                                                                                                                                                                                  
        bgp: Enabled                     <----------------- However, the BGP is still in `Enabled` state here ?                                                                                                                                                                                                              
        hostPorts: Enabled                                                                                                                                                                                                                            
        ipPools:                                                                                                                                                                                                                                      
        - blockSize: 26                                                                                                                                                                                                                               
          cidr: 100.96.1.0/16                                                                                                                                                                                                                         
          disableBGPExport: false                                                                                                                                                                                                                     
          encapsulation: VXLANCrossSubnet                                                                                                                                                                                                             
          natOutgoing: Enabled 
```

## Version


```
      containers:                                                                                                                                                                                                                                     
        - name: tigera-operator                                                                                                                                                                                                                       
          image: quay.io/tigera/operator:v1.30.4                                                                                                                                                                                                      
          imagePullPolicy: IfNotPresent                                                                                                                                                                                                               
          command:                                                                                                                                                                                                                                    
            - operator                                                                                                                                                                                                                                
          volumeMounts:                                                                                                                                                                                                                               
            - name: var-lib-calico                                                                                                                                                                                                                    
              readOnly: true                                                                                                                                                                                                                          
              mountPath: /var/lib/calico                                                                                                                                                                                                              
          env:                                                                                                                                                                                                                                        
            - name: WATCH_NAMESPACE                                                                                                                                                                                                                   
              value: ""                                                                                                                                                                                                                               
            - name: POD_NAME                                                                                                                                                                                                                          
              valueFrom:                                                                                                                                                                                                                              
                fieldRef:                                                                                                                                                                                                                             
                  fieldPath: metadata.name                                                                                                                                                                                                            
            - name: OPERATOR_NAME                                                                                                                                                                                                                     
              value: "tigera-operator"                                                                                                                                                                                                                
            - name: TIGERA_OPERATOR_INIT_IMAGE_VERSION                                                                                                                                                                                                
              value: v1.30.4                                                                                                                                                                                                                          
          envFrom:                                                                                                                                                                                                                                    
            - configMapRef:                                                                                                                                                                                                                           
                name: kubernetes-services-endpoint                                                                                                                                                                                                    
                optional: true                                                                                                                                                                                                                        
      volumes:                         
```
