### ISSUE TITLE
Ping rule does not work for Calico v3.26.1

### ISSUE THREAD

**Issue by hasonhai** [projectcalico/calico#8008]
## Context
I'm currently using Calico v3.26.1
I have this rule:

```
apiVersion: crd.projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: allow-icmp-rhel8-nodes
spec:
  order: 10
  ingress:
    - action: Allow
      protocol: ICMP
      source: {}
      destination: {}
  selector: kubernetes.io/hostname='xxxxxxxxx'
  types:
  - Ingress
```
But I when I submit it, I have an error. I thought that calico v3.26.1 support this api version?
```
[ ~]$ kubectl apply -f icmp.yaml
error: resource mapping not found for name: "allow-icmp-rhel8-nodes" namespace: "" from "icmp.yaml": no matches for kind "GlobalNetworkPolicy" in version "crd.projectcalico.org/v3"
ensure CRDs are installed first
```
Because of the error, I switch the version to v1.
```
apiVersion: crd.projectcalico.org/v1
kind: GlobalNetworkPolicy
metadata:
  name: allow-icmp-rhel8-nodes
spec:
  order: 10
  ingress:
    - action: Allow
      protocol: ICMP
      source: {}
      destination: {}
  selector: kubernetes.io/hostname='xxxxxxxxx'
  types:
  - Ingress
```

Submiting is ok now. But the log shows that the policy is not applied.

    2023-09-12 08:36:59.223 [WARNING][69] felix/validation_filter.go 68: Validation failed; treating as missing error=error with field Selector = 'kubernetes.io/hostname='xxxxxxxxx'' key=Policy(name=allow-icmp-rhel8-nodes) value=order:10,selector:"kubernetes.io/hostname='xxxxxxxxx'",inbound:allow icmp,outbound:,untracked:false,pre_dnat:false,apply_on_forward:false,types:ingress
    2023-09-12 08:36:59.223 [INFO][69] felix/label_inheritance_index.go 188: Deleting selector Policy(name=allow-icmp-rhel8-nodes)

My question is:
* Is there anything wrong with my rules? why calico cannot validate the rule?
* Why the apiVersion "crd.projectcalico.org/v3" is not working?

## Your Environment

* Calico version: v3.26.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): 1.25.12 
* Operating System and version: RHEL8, nftables
* Link to your project (optional):

Thank you very much for your response.
