### ISSUE TITLE
request assist, how to do 2nd nic on each worker node

### ISSUE THREAD

**Issue by lknite** [projectcalico/calico#8074]
1st nic (ens33, 1 gig) is for the cluster as is normal
2nd nic (ens35, 10 gig) is a storage network, the worker nodes will be able to use this to interact with csi

## Expected Behavior
I had expected the first nic to be used by calico and everything would just work, with calico essentially ignoring the 2nd nic.

## Current Behavior
I'm not sure what happened, the cluster came up as ready, but things were off ... as if the nodes couldn't talk with each other.  'metallb' couldn't apply configuration with a validating webhook error.  Rolled the cluster, after all nodes showed as ready, applications began to experience dns failure such as an argocd pod being unable to dns resolve argocd-repo.argocd.svc .

On each worker node:
```
# route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         _gateway        0.0.0.0         UG    100    0        0 ens33
_gateway        0.0.0.0         255.255.255.255 UH    100    0        0 ens33
10.0.40.0       0.0.0.0         255.255.255.0   U     100    0        0 ens33
10.0.1.0        0.0.0.0         255.255.255.0   U     101    0        0 ens35
```

## Possible Solution
I shut the nodes down, disabled the 2nd nic, powered back up and now the cluster is working as expected.
But how to get it to let me use the 2nd nic?

## Context
A lab environment w/ dual-esxi host based deployment with k8s cluster stood up using kubeadm & storage on its own network w/ ceph.  Using esxi datastore via nfs w/ ceph server & worker nodes of k8s cluster accessing cephfs via csi & storage network.

## Your Environment
* Calico version: latest as of today
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubeadm
* Operating System and version: RHEL 9
* Link to your project (optional): n/a

**Comment by lknite** [comment]
Think I may have found the solution:
https://docs.tigera.io/calico/latest/networking/ipam/ip-autodetection

This looks right:
kubectl set env daemonset/calico-node -n kube-system IP_AUTODETECTION_METHOD=<autodetection-method>

**Comment by lknite** [comment]
I used the tigera operator to install calico, how can I specify to use the regex method in the values.yaml?

```
kind: Installation
apiVersion: operator.tigera.io/v1
metadata:
  name: default
spec:
  calicoNetwork:
    nodeAddressAutodetectionV4:
      interface: ens33
```

**Comment by lknite** [comment]
Ok, this I may have figured it out, testing adding this to yaml:

```
installation:
  calicoNetwork:
    nodeAddressAutodetectionV4:
      interface: ens33
```

**Comment by lknite** [comment]
The installation crd has this:
```
spec:
  calicoNetwork:
    bgp: Enabled
    hostPorts: Enabled
    ipPools:
    - blockSize: 26
      cidr: 172.16.0.0/16
      disableBGPExport: false
      encapsulation: IPIP
      natOutgoing: Enabled
      nodeSelector: all()
    linuxDataplane: Iptables
    multiInterfaceMode: None
    nodeAddressAutodetectionV4:
      firstFound: true
      interface: ens33
```

I edited it and removed 'firstFound', restarted the tigera operator pod and logs are looking good.  calico-node daemon set has the IP_AUTODETECTION_METHOD env now set as expected.  Going to restart the calico-node pods and then test.
