### ISSUE TITLE
Applying ingress calico network policy denies communication bewteen pods within same namespace

### ISSUE THREAD

**Issue by umeshauv** [projectcalico/calico#8092]
After applying following network policy, pods within the same namespace are unable to communicate using the loadbalancer ip address

```
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  annotations:
  name: incoming-network-policy
  namespace: fi2-https
spec:
  ingress:
  - action: Allow
    destination: {}
    protocol: TCP
    source:
      namespaceSelector: ns_name in {  'kube-system',  'default', 'fi2-https' }
  - action: Allow
    destination: {}
    source:
      nets:
      - 10.122.167.21/32
      - 10.122.167.20/32
      - 10.122.201.0/24
      - 10.122.200.0/24
      - 35.182.14.186/32
      - 10.44.200.0/24
      - 10.43.0.10/32
  types:
  - Ingress

```
## Expected Behavior

Pods should be able to communicate with each other after applying the network policy

## Current Behavior

I have multiple pods running in the namespace fi2-https.   I have a service keycloak load balancer service with external IP address 10.122.201.13 . After applying the above ingress policy, if I try to access keycloak service from the pod using this external ip address from another pod, I am unable to reach it.  However, if I add pod IP address in the nets, they are able to communicate with each other.  Note that all pods have a label ns_name equivalent to their namespace name.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version - 3.17.2
* Orchestrator version (e.g. kubernetes, mesos, rkt): RKE2
* Operating System and version:
* Link to your project (optional):
