### ISSUE TITLE
Offline Calico installation

### ISSUE THREAD

**Issue by ehemmerlin** [projectcalico/calico#8142]
Since installing Calico involves the use of Tigera Calico operator (which is the recommended way), all Calico's images are pulled from Cloud (DockerHub repository). How is it possible to install Calico offline on an on-premises Kubernetes cluster?
## Expected Behavior

Being able to install Calico on a cluster which has no access to Internet
## Current Behavior

Currently even if the Tigera Calico operator image is pulled from a private repository, during the installation Calico gets all its images from Cloud.
## Possible Solution

Downloading Calico's manifests or helm chart and pushing the images in an offline private repository, but where do we find them?
## Context

Deploy our application using Calico on offline on-premises Kubernetes clusters.
## Your Environment

* Calico version: v3.26.3
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes
* Operating System and version: Linux and Windows

**Comment by chauncyAAA** [comment]
Image format: `<registry><imagePath>/<imagePrefix><imageName>:<image-tag>`

Custome Resource yaml may help

Like This:
spec:
  registry: harbor.xxx.com
  imagePath: foo
  imagePrefix: bar

**Comment by MichalFupso** [comment]
Hi @ehemmerlin, you can configure Calico to pull images from your private repository. You can see more in the docs https://docs.tigera.io/calico/latest/operations/image-options/alternate-registry

**Comment by TarekMSayed** [comment]
> Hi @ehemmerlin, you can configure Calico to pull images from your private repository. You can see more in the docs https://docs.tigera.io/calico/latest/operations/image-options/alternate-registry

How to do this with the operator helm chart?
I am using values to update the operator image 
```yaml
# Image and registry configuration for the tigera/operator pod.
tigeraOperator:
  registry: registry.atun-master/quay.io
calicoctl:
  image:  registry.atun-master/calico/ctl
  ```
  but what about Calico images

**Comment by caseydavenport** [comment]
https://docs.tigera.io/calico/latest/operations/image-options/alternate-registry#configure-the-operator-to-use-images

You can modify the `installation` section of `values.yaml` to include the registry.

The `installation` section supports the full set of options defined here: https://docs.tigera.io/calico/latest/reference/installation/api#operator.tigera.io/v1.Installation

**Comment by TarekMSayed** [comment]
> https://docs.tigera.io/calico/latest/operations/image-options/alternate-registry#configure-the-operator-to-use-images
> 
> You can modify the `installation` section of `values.yaml` to include the registry.
> 
> The `installation` section supports the full set of options defined here: https://docs.tigera.io/calico/latest/reference/installation/api#operator.tigera.io/v1.Installation

I did a quick test 
```
helm template calico projectcalico/tigera-operator --set installation.registry=myregistry.com/
```
and looking works 
the output 
```yaml
# Source: tigera-operator/templates/crs/custom-resources.yaml
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  imagePullSecrets: []
  kubernetesProvider: ""
  registry: myregistry.com/
```
Greate Thanks
