### ISSUE TITLE
BGP not announcing LoadBalancer services with externalTrafficPolicy Local for prefixes /32 and using route-reflectors

### ISSUE THREAD

**Issue by AMacedoP** [projectcalico/calico#8162]
When announcing LoadBalancer services using BGP and route-reflectors, services using `externalTrafficPolicy: Local` are not announced if the pods are not running in the same nodes as the route-reflectors.

This looks like a edge case not covered in #6074 because we are also using /32 prefixes in BGPConfiguration.

## Expected Behavior

LoadBalancer service IPs with `externalTrafficPolicy: Local` are announced by the route-reflectors to external network devices

## Current Behavior

LoadBalancer service IPs are not announced by the route-reflectors, unless the route-reflector node has a pod that matches the service selectors

## Possible Solution
Route reflectors nodes should announce all service IPs with `externalTrafficPolicy: Local` regardless of whether a pod is scheduled there

## Steps to Reproduce (for bugs)

1. Setup a cluster with a node as a route reflector and disable to node-to-node mesh according to the [documentation](https://docs.tigera.io/calico/latest/networking/configuring/bgp#configure-a-node-to-act-as-a-route-reflector)
1. Configure the default BGPConfiguration to announce LoadBalancer IPs with /32 prefixes:
   ```yaml
   apiVersion: projectcalico.org/v3
   kind: BGPConfiguration
   metadata:
     name: default
   spec:
     asNumber: 65501
	 listenPort: 179
	 logSeverityScreen: Info
	 nodeToNodeMeshEnabled: false
	 serviceLoadBalancerIPs:
	 - cidr: "10.100.17.223/32"
	 - cidr: "10.100.17.72/32"
	 - cidr: "10.100.18.30/32"
   ```
1. Add an external network device as a BGPPeer only for the route-reflectors
   ```yaml
   apiVersion: projectcalico.org/v3
   kind: BGPPeer
   metadata:
     name: external-device
   spec:
     peerIP: 20.0.0.6
     asNumber: 65501
     nodeSelector: has(route-reflector)
   ```
1. Create a deployment and service with `externalTrafficPolicy: Local` and check that the pod was scheduled to a node not configured as a route reflector
1. Check that the new service is not present in the routing table of the external network device

## Your Environment

* Calico version: v.3.25.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes
* Operating System and version: Ubuntu 20.04
