### ISSUE TITLE
Calico on EKS - disable source/destination check

### ISSUE THREAD

**Issue by MatteoMori** [projectcalico/calico#8166]
Hey, I am sorry if this is a bit silly but I am trying to get Calico configured on my EKS cluster and I don't quite get what I am supposed to do about the AWS src/dest check setting

I am following the Tigera Operator approach and the doc has no reference to it. However, if I check the "manifests" approach, I see a reference to the below:

```

kubectl -n kube-system set env daemonset/calico-node FELIX_AWSSRCDSTCHECK=Disable

```

What should I do?

**Comment by MatteoMori** [comment]
For anyone who finds this in the future: I found the answer and I am happy to leave it in here.

- disabling src/dst checks is a prerequisite for using VXLAN-CrossSubnet but not for VXLAN

This means that using a Calico Installation manifest like the below (which is the one from the Calico docs), does not need changes on the AWS side:

```
kind: Installation
apiVersion: operator.tigera.io/v1
metadata:
  name: default
spec:
  kubernetesProvider: EKS
  cni:
    type: Calico
    ipam:
      type: Calico
  calicoNetwork:
    bgp: Disabled
    hostPorts: Enabled
    linuxDataplane: Iptables
    ipPools:
      - blockSize: 26
        cidr: 172.16.0.0/16
        encapsulation: VXLAN # <---------
        natOutgoing: Enabled
        nodeSelector: all()
``` 

This video helped me a lot: https://www.tigera.io/blog/everything-you-need-to-know-about-kubernetes-pod-networking-on-aws/
