### ISSUE TITLE
unknown field "spec.allowedEgressDomains"

### ISSUE THREAD

**Issue by medoedoff** [projectcalico/calico#8191]
I deployed tigera-operator using ArgoCD:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tigera-operator
  namespace: argocd
spec:
  project: third-party
  source:
    repoURL: 'https://docs.projectcalico.org/charts/'
    targetRevision: 3.26.3
    helm:
      values: |
        installation:
          # Configures Calico networking.
          calicoNetwork:
            # Note: The ipPools section cannot be modified post-install.
            ipPools:
            - blockSize: 24
              cidr: 100.64.0.0/16
              disableBGPExport : false
              encapsulation: VXLANCrossSubnet
              natOutgoing: Enabled
              nodeSelector: all()
    chart: tigera-operator
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: tigera-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
```

I want to create NetworkSet rule:
```
kind: NetworkSet
apiVersion: projectcalico.org/v3
metadata:
  name: google
  labels:
    destinations: google
  namespace: hipstershop
spec:
  nets: []
  allowedEgressDomains:
    - clouddebugger.googleapis.com
    - cloudtrace.googleapis.com
    - metadata.google.internal
    - monitoring.googleapis.com
```

Got this error:
```
Error from server (BadRequest): error when creating "GlobalNetworkSet.yaml": NetworkSet in version "v3" cannot be handled as a NetworkSet: strict decoding error: unknown field "spec.allowedEgressDomains"
```

**Comment by medoedoff** [comment]
also got similar error
```
Error from server (BadRequest): error when creating "GlobalNetworkSet.yaml": GlobalNetworkPolicy in version "v3" cannot be handled as a GlobalNetworkPolicy: strict decoding error: unknown field "spec.tier"
```

for this manifest
```
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: application.allow-egress-internet
spec:
  tier: application
  order: 0
  selector: all()
  egress:
    - action: Allow
      source: {}
      destination:
        selector: destinations == "internet"
  types:
    - Egress
```
