### ISSUE TITLE
Calico Kubernetes Hosted Install: no profiles found

### ISSUE THREAD

**Issue by reachlin** [projectcalico/calico#825]
Trying to install calico on top of kubernetes, followed this doc: http://docs.projectcalico.org/v2.2/getting-started/kubernetes/installation/hosted/

But after the install, calicoctl get profiles return nothing.

## Expected Behavior
get profiles should return sth.? 

## Current Behavior
```
lincai@montana:~/k8s0$ kubectl exec -ti -n kube-system calicoctl -- /calicoctl get policy -o wide
NAME                  ORDER   SELECTOR             
k8s-policy-no-match   2000    has(calico/k8s_ns)   

lincai@montana:~/k8s0$ kubectl exec -ti -n kube-system calicoctl -- /calicoctl get profiles -o wide
NAME   TAGS   

lincai@montana:~/k8s0$ kubectl exec -ti -n kube-system calicoctl -- /calicoctl get node -o wide
NAME      ASN       IPV4                IPV6   
montana   (64512)   192.168.99.100/24          
```
## Possible Solution
more doc. describe the verification of calico installation?

## Steps to Reproduce (for bugs)
1. git clone https://github.com/reachlin/k8s0
2. cd k8s0
3. ansible-playbook -i inventory/local images.yml
4. ansible-playbook -i inventory/local site.yml

## Context
I am trying to install k8s with calico on a single host ubuntu and travis: https://travis-ci.org/reachlin/k8s0/builds/238213911

## Your Environment
[my project](https://github.com/reachlin/k8s0)
[my travis project](https://travis-ci.org/reachlin/k8s0/builds/238213911)

**Comment by reachlin** [comment]
fyi, my calico related configs: https://github.com/reachlin/k8s0/tree/master/roles/calico/templates

**Comment by caseydavenport** [comment]
Yeah, I'd expect profiles to exist - one for each Namespace.

Those are created by the kube-policy-controller - have you checked the logs to see if it's healthy?

**Comment by reachlin** [comment]
@caseydavenport you're right, there's some errors in the log.

**Comment by reachlin** [comment]
fyi, my calico config:
```
# Calico Version v2.2.1
# http://docs.projectcalico.org/v2.2/releases#v2.2.1
# This manifest includes the following component versions:
#   calico/node:v1.2.1
#   calico/cni:v1.8.3
#   calico/kube-policy-controller:v0.6.0

# This ConfigMap is used to configure a self-hosted Calico installation.
kind: ConfigMap
apiVersion: v1
metadata:
  name: calico-config
  namespace: kube-system
data:
  # Configure this with the location of your etcd cluster.
  etcd_endpoints: "http://{{ etcd_ip }}:{{ etcd_port }}"

  # Configure the Calico backend to use.
  calico_backend: "bird"

  # The CNI network configuration to install on each node.
  cni_network_config: |-
    {
        "name": "k8s-pod-network",
        "cniVersion": "0.1.0",
        "type": "calico",
        "etcd_endpoints": "__ETCD_ENDPOINTS__",
        "etcd_key_file": "__ETCD_KEY_FILE__",
        "etcd_cert_file": "__ETCD_CERT_FILE__",
        "etcd_ca_cert_file": "__ETCD_CA_CERT_FILE__",
        "log_level": "info",
        "ipam": {
            "type": "calico-ipam"
        },
        "policy": {
            "type": "k8s",
            "k8s_api_root": "https://__KUBERNETES_SERVICE_HOST__:__KUBERNETES_SERVICE_PORT__",
            "k8s_auth_token": "__SERVICEACCOUNT_TOKEN__"
        },
        "kubernetes": {
            "kubeconfig": "__KUBECONFIG_FILEPATH__"
        }
    }

  # If you're using TLS enabled etcd uncomment the following.
  # You must also populate the Secret below with these files.
  etcd_ca: ""   # "/calico-secrets/etcd-ca"
  etcd_cert: "" # "/calico-secrets/etcd-cert"
  etcd_key: ""  # "/calico-secrets/etcd-key"

---

# The following contains k8s Secrets for use with a TLS enabled etcd cluster.
# For information on populating Secrets, see http://kubernetes.io/docs/user-guide/secrets/
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: calico-etcd-secrets
  namespace: kube-system
data:
  # Populate the following files with etcd TLS configuration if desired, but leave blank if
  # not using TLS for etcd.
  # This self-hosted install expects three files with the following names.  The values
  # should be base64 encoded strings of the entire contents of each file.
  # etcd-key: null
  # etcd-cert: null
  # etcd-ca: null

---

# This manifest installs the calico/node container, as well
# as the Calico CNI plugins and network config on
# each master and worker node in a Kubernetes cluster.
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: calico-node
  namespace: kube-system
  labels:
    k8s-app: calico-node
spec:
  selector:
    matchLabels:
      k8s-app: calico-node
  template:
    metadata:
      labels:
        k8s-app: calico-node
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        scheduler.alpha.kubernetes.io/tolerations: |
          [{"key": "dedicated", "value": "master", "effect": "NoSchedule" },
           {"key":"CriticalAddonsOnly", "operator":"Exists"}]
    spec:
      hostNetwork: true
      serviceAccountName: calico-node
      containers:
        # Runs calico/node container on each Kubernetes node.  This
        # container programs network policy and routes on each
        # host.
        - name: calico-node
          image: node:v1.2.1
          env:
            # The location of the Calico etcd cluster.
            - name: ETCD_ENDPOINTS
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_endpoints
            # Choose the backend to use.
            - name: CALICO_NETWORKING_BACKEND
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: calico_backend
            # Disable file logging so `kubectl logs` works.
            - name: CALICO_DISABLE_FILE_LOGGING
              value: "true"
            # Set Felix endpoint to host default action to ACCEPT.
            - name: FELIX_DEFAULTENDPOINTTOHOSTACTION
              value: "ACCEPT"
            # Configure the IP Pool from which Pod IPs will be chosen.
            - name: CALICO_IPV4POOL_CIDR
              value: "192.168.0.0/16"
            - name: CALICO_IPV4POOL_IPIP
              value: "always"
            # Disable IPv6 on Kubernetes.
            - name: FELIX_IPV6SUPPORT
              value: "false"
            # Set Felix logging to "info"
            - name: FELIX_LOGSEVERITYSCREEN
              value: "info"
            # Location of the CA certificate for etcd.
            - name: ETCD_CA_CERT_FILE
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_ca
            # Location of the client key for etcd.
            - name: ETCD_KEY_FILE
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_key
            # Location of the client certificate for etcd.
            - name: ETCD_CERT_FILE
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_cert
            # Auto-detect the BGP IP address.
            - name: IP
              value: ""
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: 250m
          volumeMounts:
            - mountPath: /lib/modules
              name: lib-modules
              readOnly: true
            - mountPath: /var/run/calico
              name: var-run-calico
              readOnly: false
            - mountPath: /calico-secrets
              name: etcd-certs
        # This container installs the Calico CNI binaries
        # and CNI network config file on each node.
        - name: install-cni
          image: cni:v1.8.3
          command: ["/install-cni.sh"]
          env:
            # The location of the Calico etcd cluster.
            - name: ETCD_ENDPOINTS
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_endpoints
            # The CNI network config to install on each node.
            - name: CNI_NETWORK_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: cni_network_config
          volumeMounts:
            - mountPath: /host/opt/cni/bin
              name: cni-bin-dir
            - mountPath: /host/etc/cni/net.d
              name: cni-net-dir
            - mountPath: /calico-secrets
              name: etcd-certs
      volumes:
        # Used by calico/node.
        - name: lib-modules
          hostPath:
            path: /lib/modules
        - name: var-run-calico
          hostPath:
            path: /var/run/calico
        # Used to install CNI.
        - name: cni-bin-dir
          hostPath:
            path: /opt/cni/bin
        - name: cni-net-dir
          hostPath:
            path: /etc/cni/net.d
        # Mount in the etcd TLS secrets.
        - name: etcd-certs
          secret:
            secretName: calico-etcd-secrets

---

# This manifest deploys the Calico policy controller on Kubernetes.
# See https://github.com/projectcalico/k8s-policy
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: calico-policy-controller
  namespace: kube-system
  labels:
    k8s-app: calico-policy
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ''
    scheduler.alpha.kubernetes.io/tolerations: |
      [{"key": "dedicated", "value": "master", "effect": "NoSchedule" },
       {"key":"CriticalAddonsOnly", "operator":"Exists"}]
spec:
  # The policy controller can only have a single active instance.
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      name: calico-policy-controller
      namespace: kube-system
      labels:
        k8s-app: calico-policy
    spec:
      # The policy controller must run in the host network namespace so that
      # it isn't governed by policy that would prevent it from working.
      hostNetwork: true
      serviceAccountName: calico-policy-controller
      containers:
        - name: calico-policy-controller
          image: kube-policy-controller:v0.6.0
          env:
            # The location of the Calico etcd cluster.
            - name: ETCD_ENDPOINTS
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_endpoints
            # Location of the CA certificate for etcd.
            - name: ETCD_CA_CERT_FILE
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_ca
            # Location of the client key for etcd.
            - name: ETCD_KEY_FILE
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_key
            # Location of the client certificate for etcd.
            - name: ETCD_CERT_FILE
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_cert
            # The location of the Kubernetes API.  Use the default Kubernetes
            # service for API access.
            - name: K8S_API
              value: "https://{{ api_ip }}:{{ api_ssl_port }}"
            # Since we're running in the host namespace and might not have KubeDNS
            # access, configure the container's /etc/hosts to resolve
            # kubernetes.default to the correct service clusterIP.
            - name: CONFIGURE_ETC_HOSTS
              value: "true"
          volumeMounts:
            # Mount in the etcd TLS secrets.
            - mountPath: /calico-secrets
              name: etcd-certs
      volumes:
        # Mount in the etcd TLS secrets.
        - name: etcd-certs
          secret:
            secretName: calico-etcd-secrets

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: calico-policy-controller
  namespace: kube-system

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: calico-node
  namespace: kube-system
```

**Comment by tmjd** [comment]
The kubernetes certificates are mounted by kubernetes into known locations, which is why they don't need to appear in the configuration.  Though I just noticed `WARNING No ServiceAccount token found on disk` in the logs you attached.  Could you try killing your calico-policy-controller pod and let it be recreated?  I'm wondering if there is a race condition (or wrong order) in the manifest since the ServiceAccount calico-policy-controller comes after the Deployment definition that uses it.

**Comment by tmjd** [comment]
@reachlin Is this still an issue for you? Did you attempt deleting your calico-policy-controller pod so it could be recreated?

**Comment by reachlin** [comment]
still the same issue...

```
lincai@montana:~$ kubectl get pods -n kube-system
NAME                                        READY     STATUS    RESTARTS   AGE
calico-node-xn7vr                           2/2       Running   0          2m
calico-policy-controller-1945986458-krg5g   1/1       Running   0          2m
calicoctl                                   1/1       Running   0          2m
kube-apiserver-montana                      1/1       Running   0          47s
kube-controller-manager-montana             1/1       Running   0          2m
kube-scheduler-montana                      1/1       Running   0          2m
lincai@montana:~$ kubectl exec -ti -n kube-system calicoctl -- /calicoctl get profiles -o wide
NAME   TAGS   

lincai@montana:~$ kubectl delete pod -n kube-system calico-policy-controller-1945986458-krg5g
pod "calico-policy-controller-1945986458-krg5g" deleted
lincai@montana:~$ kubectl get pods -n kube-system
NAME                                        READY     STATUS    RESTARTS   AGE
calico-node-xn7vr                           2/2       Running   0          2m
calico-policy-controller-1945986458-9mhth   1/1       Running   0          5s
calicoctl                                   1/1       Running   0          2m
kube-apiserver-montana                      1/1       Running   0          1m
kube-controller-manager-montana             1/1       Running   0          2m
kube-scheduler-montana                      1/1       Running   0          2m
lincai@montana:~$ kubectl exec -ti -n kube-system calicoctl -- /calicoctl get profiles -o wide
NAME   TAGS   

lincai@montana:~$
```

**Comment by caseydavenport** [comment]
From your logs I'm seeing this error repeated:

```
{"log":"2017-06-02 02:08:25,009 5 ERROR Unhandled exception killed Namespace manager\n","stream":"stderr","time":"2017-06-02T02:08:25.011152444Z"}
{"log":"Traceback (most recent call last):\n","stream":"stderr","time":"2017-06-02T02:08:25.011163331Z"}
{"log":"  File \"\u003cstring\u003e\", line 324, in _manage_resource\n","stream":"stderr","time":"2017-06-02T02:08:25.011166168Z"}
{"log":"  File \"\u003cstring\u003e\", line 441, in _sync_resources\n","stream":"stderr","time":"2017-06-02T02:08:25.011168762Z"}
{"log":"  File \"site-packages/requests/models.py\", line 866, in json\n","stream":"stderr","time":"2017-06-02T02:08:25.01117103Z"}
{"log":"  File \"site-packages/simplejson/__init__.py\", line 516, in loads\n","stream":"stderr","time":"2017-06-02T02:08:25.011173335Z"}
{"log":"  File \"site-packages/simplejson/decoder.py\", line 374, in decode\n","stream":"stderr","time":"2017-06-02T02:08:25.011175657Z"}
{"log":"  File \"site-packages/simplejson/decoder.py\", line 404, in raw_decode\n","stream":"stderr","time":"2017-06-02T02:08:25.01117974Z"}
{"log":"JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n","stream":"stderr","time":"2017-06-02T02:08:25.011193353Z"}
{"log":"2017-06-02 02:08:25,010 5 INFO Restarting watch on resource: Namespace\n","stream":"stderr","time":"2017-06-02T02:08:25.011196004Z"}
```

This is a problem - it looks like the apiserver is returning something that the controller is failing to parse.

```
            # The location of the Kubernetes API.  Use the default Kubernetes
            # service for API access.
            - name: K8S_API
              value: "https://{{ api_ip }}:{{ api_ssl_port }}"
```

Is there a reason you want to change this from the default?  I think this should be `https://kubernetes.default:443`

**Comment by caseydavenport** [comment]
> WARNING No ServiceAccount token found on disk

Yeah, that could be part of it as well.  Make sure the service account exists before the policy controller is created just to be sure.

Does this cluster have RBAC enabled?  If so, you'll also need to apply the ClusterRoles/Bindings.

**Comment by reachlin** [comment]
didn't enable RBAC, this is my api config, fyi
```
apiVersion: v1
kind: Pod
metadata:
  name: kube-apiserver
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-apiserver
    image: "hyperkube:{{ hyperkube_version }}"
    imagePullPolicy: IfNotPresent
    command:
    - /hyperkube
    - apiserver
    - --bind-address=0.0.0.0
    - --insecure-bind-address=127.0.0.1
    - --storage-backend=etcd3
    - --etcd-servers=http://{{ etcd_ip }}:{{ etcd_port }}
    - --allow-privileged=true
    - --service-cluster-ip-range={{ service_cluster_ip_range }}
    - --secure-port={{ api_ssl_port }}
    - --insecure-port={{ api_port }}
    - --tls-cert-file=/etc/kubernetes/cert/server.crt
    - --tls-private-key-file=/etc/kubernetes/cert/server.key
    - --client-ca-file=/etc/kubernetes/cert/ca.crt
    ports:
    - containerPort: {{ api_ssl_port }}
      hostPort: {{ api_ssl_port }}
      name: https
    - containerPort: {{ api_port }}
      hostPort: {{ api_port }}
      name: local
    volumeMounts:
    - mountPath: /etc/kubernetes
      name: kubernetes-config
      readOnly: true
    - mountPath: /etc/kubernetes/cert
      name: kubernetes-certs
      readOnly: true
  volumes:
  - hostPath:
      path: {{ kubelet_config_dir }}
    name: kubernetes-config
  - hostPath:
      path: {{ kubelet_config_dir }}/cert
    name: kubernetes-certs
```
