### ISSUE TITLE
Guidance on passing calico helm release values when installing the tigera operator

### ISSUE THREAD

**Issue by hlascelles** [projectcalico/calico#8288]
We are using the tigera-operator, and it installs and works well.

However, we want to enforce using only our own ECR (partly to avoid download limit issues) that arise when the calico pods start.

We know we can change the pod location for the initial operator pods here: https://github.com/projectcalico/calico/blob/d5f37a6684fcedf775a4c37d5d3d13f2dd6d7b29/charts/tigera-operator/values.yaml#L53

What we would like to do is pass in values to set the image locations for the calico pods. ie, the ones here: https://github.com/projectcalico/calico/blob/d5f37a6684fcedf775a4c37d5d3d13f2dd6d7b29/charts/calico/values.yaml#L6

## Expected Behavior
We would like a simple way in the tigera-operator helm yaml to set the calico chart yaml values.

## Current Behavior
We cannot see a way to do this, so we see pod image download rate limits.

## Possible Solution
Have a section in the tigera-operator values to pass through calico values please!

ie, we would like this to be possible. Note, this does not work, it is just an example of a solution.

Entire contents of a tigera-operator release value file used:
```yaml
# These do exist
tigeraOperator:
  image: mycompanyecr.com/tigera
calicoctl:
  image: mycompanyecr.com/calicoctl

# This key we want to exist
calico_values:
  node:
    image: mycompanyecr.com/node
  calicoctl:
    image: mycompanyecr.com/calicoctl
  typha:
    image: mycompanyecr.com/typha

```

## Your Environment
Tigera operation chart version: v3.25.0

**Comment by caseydavenport** [comment]
The way to do this is to set the image registry field in the `installation` section of values.yaml, discussed generally here: https://docs.tigera.io/calico/latest/operations/image-options/alternate-registry

Something like this:

```yaml
installation:
  registry: mycompanyecr.com/

tigeraOperator:
  image: mycompanyecr.com/tigera
calicoctl:
  image: mycompanyecr.com/calicoctl
```
