### ISSUE TITLE
Egress traffic only with wide mask 10.0.0.0/8

### ISSUE THREAD

**Issue by webchi** [projectcalico/calico#8317]
Hi, we use NetworkPolicy based on calico as CNI
## Expected Behavior

Traffic outgoing to the hosts
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
spec:
  podSelector: {}
  egress:
    - ports:
        - protocol: TCP
          port: 443
      to:
        - ipBlock:
            cidr: 10.21.112.13/32
        - ipBlock:
            cidr: 10.21.112.14/32
        - ipBlock:
            cidr: 10.21.112.15/32
```            

## Current Behavior

Connection timeout to the hosts with /32 /24 /16 masks. And only working with /8 mask
```
spec:
  podSelector: {}
  egress:
    - ports:
        - protocol: TCP
          port: 443
      to:
        - ipBlock:
            cidr: 10.0.0.0/8
```

Any ideas how to debug this?

## Your Environment

* Calico version v3.25.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): v1.26.3
* Operating System and version: Ubuntu 22.04.3 LTS
