### ISSUE TITLE
Tigera-Operator helm chart Installation spec kubeletVolumePluginPath missing

### ISSUE THREAD

**Issue by DreamingRaven** [projectcalico/calico#8335]
## Expected Behavior

Under Talos I need to override the kubeletVolumePluginPath since the root FS is immutable.
This prevents a continous crash of the CSI related container since it cannot write to this:

```
NAMESPACE                       NAME                                             READY   STATUS                 RESTARTS      AGE
calico-apiserver                calico-apiserver-7685dff6f9-k9dgm                1/1     Running                0             101s
calico-apiserver                calico-apiserver-7685dff6f9-rzdbf                1/1     Running                0             101s
calico-system                   calico-kube-controllers-6cc6d699cb-w5ln6         1/1     Running                0             2m20s
calico-system                   calico-node-449pw                                1/1     Running                0             2m20s
calico-system                   calico-typha-776864f99-wgnfx                     1/1     Running                0             2m20s
calico-system                   csi-node-driver-cx9pj                            1/2     CreateContainerError   2 (36s ago)   2m20s
tigera-operator                 tigera-operator-7f8cd97876-9t2bp                 1/1     Running                0             2m26s
```

Using the following values.yaml (tigera-operator as a subchart):

```yaml

tigera-operator:
  # https://github.com/tigera/operator/issues/2444#issuecomment-1482088343
  kubeletVolumePluginPath: None
  installation:
    registry: quay.io/
    imagePath: calico
    cni:
      type: Calico
    calicoNetwork:
      bgp: Disabled
      ipPools:
      - cidr: "172.16.0.0/14"
        encapsulation: VXLAN
      # look in the talos config for these two values:
      # pod subnet "172.16.0.0/14"
      # service subnet "172.20.0.0/14"

  tigeraOperator:
    image: tigera/operator
    registry: quay.io
  calicoctl:
    image: quay.io/calico/ctl

```

In this otherwise empty parent chart

```yaml

apiVersion: v2
name: calico
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
- name: tigera-operator
  version: 3.26.4
  repository: "https://docs.tigera.io/calico/charts"

```

I expected the generated helm Installation CRD to render the appropriate kubeleteVolumePluginPath:

```yaml

# Source: calico/charts/tigera-operator/templates/crs/custom-resources.yaml
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  kubeletVolumePluginPath: None # <--
  calicoNetwork:
    bgp: Disabled
    ipPools:
    - cidr: 172.16.0.0/14
      encapsulation: VXLAN
  cni:
    type: Calico
  imagePath: calico
  imagePullSecrets: []
  kubernetesProvider: ""
  registry: quay.io/

```

## Current Behavior

But instead the current chart renders:

```yaml

# Source: calico/charts/tigera-operator/templates/crs/custom-resources.yaml
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  calicoNetwork:
    bgp: Disabled
    ipPools:
    - cidr: 172.16.0.0/14
      encapsulation: VXLAN
  cni:
    type: Calico
  imagePath: calico
  imagePullSecrets: []
  kubernetesProvider: ""
  registry: quay.io/

```

Then you have to manually edit the installation resource to set the kubeletVolumePluginPath to None.

## Steps to Reproduce (for bugs)

1. Use the above values with the helm chart (stripping the top level key since you wont be doing it with a subchart)
2. helm install to a fresh cluster 
3. pod crash 1/2 if using Talos or other immutable rootfs
4. check "Installation" CRD to find kubeleteVolumePluginPath is set to an actual dir

## Context

On talos, or other immutable os, results in crash of calico-node since calico-node does not have permission to edit the default dir. Since it can't be overridden in the helm chart currently, which seems like unintended behaviour, you have to manually edit the Installation CRD.

## Your Environment

* Tigera-Operator version: 3.26.4
* Orchestrator version (e.g. kubernetes, mesos, rkt): 1.28.3
* Operating System and version: Talos 1.5.5
* Link to your project (optional):

**Comment by caseydavenport** [comment]
```yaml
tigera-operator:
  # https://github.com/tigera/operator/issues/2444#issuecomment-1482088343
  kubeletVolumePluginPath: None
  installation:
    registry: quay.io/
    imagePath: calico
```

^ I think this is wrong, and should instead be:

```yaml
installation:
  registry: quay.io/
  imagePath: calico
  kubeletVolumePluginPath: None

tigeraOperator:
  ...
```

See the example values.yaml for reference: https://github.com/projectcalico/calico/blob/master/charts/tigera-operator/values.yaml

There is no top-level `tigera-operator` section.

**Comment by DreamingRaven** [comment]
Hey @caseydavenport thanks for the quick response. Funnily enough, despite a few discrepancies, what you said does indeed solve the issue. For the sake of others I wanted to highlight two places of confusion.


- In the very example you pointed to [example, kubeletVolumePluginPath](https://github.com/projectcalico/calico/blob/1c2942178f08529da0e953fc3a61cb2df291ebf8/charts/tigera-operator/values.yaml#L61) the key is not under .Values.installation.kubeletVolumePluginPath but is at the root of the values. This might need moving and indenting properly so others dont get confused:

```yaml

imagePullSecrets: {}

installation:
  enabled: true
  kubernetesProvider: ""
  imagePullSecrets: []

...

kubeletVolumePluginPath: /var/lib/kubelet # <-- not a subkey of installation

```

- [This part of the helm template](https://github.com/projectcalico/calico/blob/1c2942178f08529da0e953fc3a61cb2df291ebf8/charts/tigera-operator/templates/crs/custom-resources.yaml#L4) Is also quite confusing as at first glance it would also appear to point to .Values.kubeletVolumePluginPath as a valid location for this key:value. What is the purpose of this line if not to take .Values.kubeletVolumePluginPath and modify the installSpec dict with its contents?

```yaml

{{ if .Values.installation.enabled }}
{{ $installSpec := omit .Values.installation "enabled" }}
{{ $_ := set $installSpec "imagePullSecrets" (include "tigera-operator.imagePullSecrets" . | fromYamlArray) }}
{{ $_ := set $installSpec "kubeletVolumePluginPath" .Values.kubeletVolumePluginPath }}

apiVersion: operator.tigera.io/v1
kind: Installation
...

```

Thanks again tho, this does indeed fix the issue, just that the associated documentation is confusing.
My final values is (for anyone installing the tigera helm chart directly strip the top level key and de-indent):

```yaml

tigera-operator:
  # https://github.com/tigera/operator/issues/2444#issuecomment-1482088343
  installation:
    kubeletVolumePluginPath: none
    registry: quay.io/
    imagePath: calico
    cni:
      type: Calico
    calicoNetwork:
      bgp: Disabled
      ipPools:
      - cidr: "172.16.0.0/14"
        encapsulation: VXLAN
      # look in the talos config for these two values:
      # pod subnet "172.16.0.0/14"
      # service subnet "172.20.0.0/14"

  tigeraOperator:
    image: tigera/operator
    registry: quay.io
  calicoctl:
    image: quay.io/calico/ctl


```

P.S there is a top level key. As I noted in my initial post, [tigera-operator is in a subchart in my instance](https://helm.sh/docs/helm/helm_dependency/)  and not the main chart. This is because I use a meta helm chart strategy in my gitops setup.
