### ISSUE TITLE
The use of a NetworkSet can inadvertently cause the scope of a NetworkPolicy to be expanded beyond it's target scope

### ISSUE THREAD

**Issue by MarkTopping** [projectcalico/calico#8348]
Bug report.

Given a Calico NetworkPolicy with label-scoped selector and an Allow rule being applied into a Namespace containing many Pods of which only 1 pod matches the label-selector, I've come across an issue whereby Calico is allowing network calls from all other Pods within the Namespace.

I've narrowed it down a little bit in that I've identified that the use of a NetworkSet seems to alter (or invalidate?) the scope of the NetworkPolicy. If my Calico NetworkPolicy specifies the destination IP address directly under the egress.destination.nets property then the scope of the policy is correctly applied and traffic is only allowed from the Pod in scope. However, when I move the destination IP into a NetworkSet, then all Pods in the Namespace obtain access to the destination IP. This is the bug I'm reporting. 

Unfortunately it's not as simple/clear-cut as this though. While i can reliably replicate this issue in one of the clusters I have access to; I've also failed to replicate it in another one. In both cases I'm using a Microsoft AKS cluster with Calico Network Policy enabled. Both clusters contain the same version the Calico components. There is however one possibly significant difference between these two clusters in that the one where I cannot replicate the issue is using Kubenet, whereas the one were I can replicate the issue is using Azure CNI. I certainly cannot assert that this is the route of the problem though - I'm just sharing the observation. 

## Expected Behavior
The scope of a NetworkPolicy selector should be applied regardless of whether or not the NetworkPolicy specifies the destination IPs directly, or indirectly via use of a NetworkSet

## Current Behavior
The scope of a NetworkPolicy is being wrongly extended to all pods in my Namespace if (and only if) the destination IP address is abstracted into a NetworkSet object

## Steps to Reproduce (for bugs)

Create an AKS cluster with Calico NetworkPolicy enabled. It's possibly material to use the AzureCNI Network Plugin (original not overlay)

In the environment where I can replicate this issue I have:
- A default-deny GlobalNetworkPolicy (it logs then denies both ingress and egress). Order: 9999 
- Several other GlobalNetworkPolicies which I believe to be irrelevant here

and either:
- A label-scoped Calico Network Policy which uses a NetworkSet as the selector in the egress.destination (buggy). OR
- A label-scoped Calico Network Policy which uses specifies an IP in the egress.destination (working)

While I've tweaked a couple of names/IP addresses as to not leak information; here the the manifests.

**Global Default Deny**
```
apiVersion: crd.projectcalico.org/v1
kind: GlobalNetworkPolicy
metadata:
  name: global-default-deny
spec:
  egress:
  - action: Log
  - action: Deny
  ingress:
  - action: Log
  - action: Deny
  namespaceSelector: has(kubernetes.io/metadata.name) && kubernetes.io/metadata.name
    not in { "kube-system", "calico-system", "tigera-operator" }
  order: 9999
  types:
  - Ingress
  - Egress
  ```

**Working Network Policy.** 

_Result when this is deployed: Target Pod is allowed egress. Other Pods are denied and the global deny emits logs_ 
```
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-to-some-destination
  namespace: my-namespace
spec:
  order: 1000
  selector: networkpolicy/allow-egress-to-some-destination == "true" # Note: Only the target Pod contains this label
  types:
    - Egress
  egress:
  - action: Allow
    protocol: TCP
    destination:
      nets:
      - 199.0.0.1/32
      ports:
      - 443
```

**Alternative and buggy Network Policy.** 

_Result when this policy is deployed: All pods in 'my-namespace' can egress to the target IP address. No logs emitted_
```
apiVersion: crd.projectcalico.org/v1
kind: NetworkSet
metadata:
  name: network-set-for-my-destination
  namespace: my-namespace
  labels:
    network-set-name: ns-my-destination
spec:
  nets:
  - 199.0.0.1/32
---
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-to-some-destination
  namespace: my-namespace
spec:
  order: 1000
  selector: networkpolicy/allow-egress-to-some-destination == "true" # Note: Only the Target Pod contains this label
  types:
    - Egress
  egress:
  - action: Allow
    protocol: TCP
    destination:
      selector: network-set-name == "ns-my-destination"
      ports:
      - 443
```

Note that I am aware that these are Calico v1 manifests but a Calico enabled AKS cluster does not provide access to v3. 

## Context
I'm trying to accomplish granular network control whereby approval to egress to a specific IP address is only granted to the specific workload which needs it. Furthermore I'm trying to use a NetworkSet while doing so because we might adopt a paid version of Calico and we'd like the target IP address to be labelled with a friendly name in the Calico UI Service Graph

## Your Environment

* Calico version: 3.24.6
* Orchestrator version (e.g. kubernetes, mesos, rkt): AKS. Kubernetes version 1.27.3

**Comment by caseydavenport** [comment]
> Note that I am aware that these are Calico v1 manifests but a Calico enabled AKS cluster does not provide access to v3.

FWIW, You can use calicoctl to access the validation and defaulting provided by the v3 API even in the absence of the API server running on the cluster. I'd recommend doing this to make sure the resources you're testing do in fact pass that validation, otherwise it might be a really subtle configuration error causing this. That said, nothing about those yamls is jumping out at me as being wrong.

**Comment by MarkTopping** [comment]
Hi @caseydavenport 

Sure. 

I've done this and calicoctl was happy to deploy my resources - therefore I assume validation passes. 

To be explicit on what I did:

I gathered all NetworkPolicy and NetworkSet manifests for the affected Namespace (which also includes some additional existing ones to those mentioned in the ticket). I put them all into the same YAML file and then changed the apiVersion property for each manifest to  `projectcalico.org/v3`.

I downloaded calicoctl as a binary install onto a windows host and set the HOME env-var which is missing on Windows but was required for calicoctl to find my kubeconfig and K8s context. 

I then executed `calicoctl apply -f .\calico-manifests-for-validation.yaml --namespace=helloworld`

The response I received to stdout was `Successfully applied 8 resource(s)`

In my cluster I can see the numerous resources appear. Note that I was a tad surprised they deployed as I (wrongly) anticipated complaints about the v3 CRDs not existing in my cluster but on inspection I can see that the actual deployed resources have `apiVersion: crd.projectcalico.org/v1` so it seems calicoctl converted them. 

Anyhow. In short.... calicoctl had no issue with the manifests.

**Comment by caseydavenport** [comment]
Great, thanks for confirming - that sounds like it's functioning as expected and means we can be confident the resources themselves aren't flawed in some way.

**Comment by caseydavenport** [comment]
@MarkTopping sorry for the delay here. One other thing jumped out at me:

> Several other GlobalNetworkPolicies which I believe to be irrelevant here

I think it would be good to include these if possible, and/or to re-test this in a way to isolates the scenario to _just_ the two policies in question - the default-deny and the allow-via-networkset. My thinking is that even if they may seem irrelevant, it's possible that the extended scope is occurring due to an unexpected inclusion of the network set in another policies rules.

**Comment by MarkTopping** [comment]
Hi @caseydavenport 

That's a bit tricky to stage, but I will look into if I can do something out of hours when it won't cause disruption. 

It's a good shout as something to test; although I have already cross-referenced said GNP's to ensure no overlaps and that the policy ordering checks out so I would be going into such a test with little hope of it changing behaviour - but then if something did change it would maybe assist in narrowing down the exact circumstances and cause. Cheers

**Comment by caseydavenport** [comment]
```
  - action: Allow
    destination:
      namespaceSelector: kubernetes.io/metadata.name == "my-namespace"
```

Ah, I think this is likely the cause. Namely, Calico selectors will also match NetworkSets in addition to pods. From here https://docs.tigera.io/calico/latest/reference/resources/networkpolicy#entityrule

> Selectors can match [workload endpoints](https://docs.tigera.io/calico/latest/reference/resources/workloadendpoint), [host endpoints](https://docs.tigera.io/calico/latest/reference/resources/hostendpoint) and ([namespaced](https://docs.tigera.io/calico/latest/reference/resources/networkset) or [global](https://docs.tigera.io/calico/latest/reference/resources/globalnetworkset)) network sets.

To restrict a match to only pods, you can do something like this:

```
  - action: Allow
    destination:
      namespaceSelector: kubernetes.io/metadata.name == "my-namespace"
      selector: projectcalico.org/orchestrator == "k8s"
```

Docs reference: https://docs.tigera.io/calico/latest/network-policy/get-started/calico-policy/calico-labels#labels-for-matching-workload-endpoints

Give that a try and let me know if that makes this policy work as expected.
