### ISSUE TITLE
Change operator defaults so that Typha no longer ignores node cordoning

### ISSUE THREAD

**Issue by SammyA** [projectcalico/calico#8371]
Typha deployment is created by the operator with very wide tolerations, ignoring node cordoning.

## Expected Behavior
If one or more nodes are cordoned, typha pods should reschedule on another non-cordoned node.

## Current Behavior
When nodes are drained, and therefore very lightly loaded, typha prefers to schedule on these cordoned nodes. When these nodes are eventually brought offline, typha deployment will not have the requested number of replicas, as new pods scheduled to satisfy the replicaset will be scheduled on these down nodes.

## Possible Solution
We're running the operator with these tolerations, which seems to result in much better behaviour
```yaml
- effect: NoSchedule
  key: node.kubernetes.io/not-ready
  operator: Exists
- effect: NoSchedule
  key: node.kubernetes.io/network-unavailable
  operator: Exists
- effect: NoExecute
  key: node.kubernetes.io/not-ready
  operator: Exists
  tolerationsSeconds: 300
- effect: NoExecute
  key: node.kubernetes.io/unreachable
  operator: Exists
  tolerationsSeconds: 300
```

## Steps to Reproduce (for bugs)
cordon and drain nodes on which typha pods are running

## Your Environment
* Calico version: v3.27.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubeadm
