### ISSUE TITLE
BGP: externalTrafficPolicy:Local endpoints of serviceExternalIPs are not getting advertised as /32

### ISSUE THREAD

**Issue by defo89** [projectcalico/calico#8375]
## Expected Behavior
Calico node advertises not only the configured `serviceExternalIPs` prefix `10.11.11.224/27` but also a more specific `/32` prefix if it hosts an endpoint of `externalTrafficPolicy:Local` service. Does not matter if type is configured to `LoadBalancer` or `NodePort`.

## Current Behavior
Calico node advertises only whole prefix `10.11.11.224/27`.

```
<kube-system› kgp | grep nginx
nginx-controller-58dc449b59-dpdt2       1/1     Running     0             33s     100.64.13.11    server3 <<<<
nginx-controller-58dc449b59-pq756       1/1     Running     0             3d12h   100.64.11.237   server2
nginx-controller-58dc449b59-qgbww       1/1     Running     0             3d12h   100.64.19.143   server1
```

```
server3 # netstat -rn
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         10.10.10.129    0.0.0.0         UG        0 0          0 if2
10.10.10.128    0.0.0.0         255.255.255.224 U         0 0          0 if2
100.64.13.2     0.0.0.0         255.255.255.255 UH        0 0          0 cali343cea7bb3a
100.64.13.3     0.0.0.0         255.255.255.255 UH        0 0          0 cali7cb9a43f1b0
100.64.13.4     0.0.0.0         255.255.255.255 UH        0 0          0 cali7d65444adde
100.64.13.5     0.0.0.0         255.255.255.255 UH        0 0          0 calie0b1fbb70f6
100.64.13.6     0.0.0.0         255.255.255.255 UH        0 0          0 cali06122732368
100.64.13.7     0.0.0.0         255.255.255.255 UH        0 0          0 cali3593906f27f
100.64.13.8     0.0.0.0         255.255.255.255 UH        0 0          0 calic95b1fbb2d3
100.64.13.11    0.0.0.0         255.255.255.255 UH        0 0          0 cali0b23d5a54d4   <<<<<<< nginx pod
```

```
switch # show bgp vrf net-mgmt:net-mgmt ipv4 unicast neighbors 10.10.10.136 routes

Peer 10.10.10.136 routes for address family IPv4 Unicast:
BGP table version is 1973, local router ID is 10.10.10.253
Status: s-suppressed, x-deleted, S-stale, d-dampened, h-history, *-valid, >-best
Path type: i-internal, e-external, c-confed, l-local, a-aggregate, r-redist, I-injected
Origin codes: i - IGP, e - EGP, ? - incomplete, | - multipath, & - backup

   Network            Next Hop            Metric     LocPrf     Weight Path
*>i10.11.11.224/27    10.10.10.136                      100          0 i
*>i100.64.13.2/32     10.10.10.136                      100          0 i
*>i100.64.13.3/32     10.10.10.136                      100          0 i
*>i100.64.13.4/32     10.10.10.136                      100          0 i
*>i100.64.13.5/32     10.10.10.136                      100          0 i
*>i100.64.13.6/32     10.10.10.136                      100          0 i
*>i100.64.13.7/32     10.10.10.136                      100          0 i
*>i100.64.13.8/32     10.10.10.136                      100          0 i
*>i100.64.13.11/32    10.10.10.136                      100          0 i  <<<<<<<<<<<
```

## Your Environment

* Calico version: v3.27.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes v1.28.4
* Operating System and version: Flatcar 3815.0.0

```
apiVersion: projectcalico.org/v3
kind: BGPConfiguration
metadata:
  name: default
spec:
  logSeverityScreen: Info
  nodeToNodeMeshEnabled: false
  asNumber: 65001
  serviceExternalIPs:
    - cidr: 10.11.11.224/27
  listenPort: 179
  bindMode: NodeIP
```

Service spec:
```
› kg svc nginx-controller -o yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-namespace: kube-system
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: ingress-nginx
    helm.sh/chart: ingress-nginx-4.5.2
  name: nginx-controller
  namespace: kube-system
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 100.120.27.236
  clusterIPs:
  - 100.120.27.236
  externalIPs:
  - 10.11.11.250                 <<<<<<<<<
  externalTrafficPolicy: Local   <<<<<<<<<
  healthCheckNodePort: 30337
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - appProtocol: http
    name: http
    nodePort: 30366
    port: 80
    protocol: TCP
    targetPort: http
  - appProtocol: https
    name: https
    nodePort: 32679
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: ingress-nginx
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
```

One of pods runs on calico node:

```
› kds nginx-controller
Name:                     nginx-controller
Namespace:                kube-system
--snip--
Type:                     LoadBalancer
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       100.120.27.236
IPs:                      100.120.27.236
External IPs:             10.11.11.250
Port:                     http  80/TCP
TargetPort:               http/TCP
NodePort:                 http  30366/TCP
Endpoints:                100.64.11.237:80,100.64.13.11:80,100.64.19.143:80
Port:                     https  443/TCP
TargetPort:               https/TCP
NodePort:                 https  32679/TCP
Endpoints:                100.64.11.237:443,100.64.13.11:443,100.64.19.143:443
Session Affinity:         None
External Traffic Policy:  Local
HealthCheck NodePort:     30337
Events:                   <none>
```
