### ISSUE TITLE
Allow to create generically global network policy that matches namespace "Self"

### ISSUE THREAD

**Issue by jsalatiel** [projectcalico/calico#8382]
## Context

Calico global network policies are just great, providing admins ways to create and enforce default behaviors.
One thing that I truly miss in calico global netpol is the ability to create a global policy that can generically match pods in a generic namespace.
Let's say I want all pods labeled frontend access all pods labeled backend as far as they are inside the same namespace.
Using VMWare antrea as CNI in kubernetes that can be achieved as:
```
apiVersion: crd.antrea.io/v1alpha1
kind: ClusterNetworkPolicy
metadata:
  name: frontend-backend-same-ns
spec:
      appliedTo:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              role: frontend
      to:
        - namespaces:
            match: Self
          podSelector:
            matchLabels:
              role: backend
```
Notice that with ONE singl rule I can let all pods labeled frontend to connect to all pod s labeled backend but only if both are in the same namespace. The key there is the namespaces: **Self**  matcher.
Currently to do that in calico I would need to have one different rule per namespace.

 

## Your Environment
* Calico version 3.27
* Orchestrator version (e.g. kubernetes, mesos, rkt): openshift
* Operating System and version: RHCOS
