### ISSUE TITLE
Terraform Error - "Unsupported value: "calico-csi": supported values: "csi-node-driver""

### ISSUE THREAD

**Issue by timetofaceit** [projectcalico/calico#8400]
Hi!

I think I found a bug! 

I want to add resource limits in my K8s cluster for csi-node-driver pods, but there is no such container name...

My code:

```
installation:
  csiNodeDriverDaemonSet:
    metadata:
      name: "csi-node-driver"
      namespace: "calico-system"
    spec:
      template:
        spec:
          containers:
            - name: "csi-node-driver"
              resources:
                requests:
                  cpu: "10m"
                  memory: "10Mi"
                limits:
                  cpu: "30m"
                  memory: "20Mi"
```

I'm working with terraform and calico helm chart. So I add this code lines to helm chart values.yaml file. 

Problem - when I check existing csi-node-driver daemonset, I see that there is container named "calico-csi" (you can also check this manifest - https://github.com/projectcalico/calico/blob/master/manifests/csi-driver.yaml) and when I try to use it I get this error - Unsupported value: "calico-csi": supported values: "csi-node-driver".

If I replace "calico-csi" with "csi-node-driver" in "container" name section, then calico operator spams errors that there are no such container with that name...

Any ideas how can I solve this?
