### ISSUE TITLE
Fail to deploy a kubeadm cluster with calico

### ISSUE THREAD

**Issue by sameo** [projectcalico/calico#852]
I'm following the following guide:
http://docs.projectcalico.org/v2.3/getting-started/kubernetes/installation/hosted/kubeadm/

to deploy a k8s cluster with calico, through kubeadm, and the calico-node pod fails to start

## Expected Behavior

I'd expect the calico pods to start.

## Current Behavior

Both the calico-node and the calico-policy-controller fail to start:

```
root@k8s-master:~# kubectl get pods --all-namespaces -o wide
NAMESPACE     NAME                                        READY     STATUS    RESTARTS   AGE       IP             NODE
kube-system   calico-etcd-jllmx                           1/1       Running   0          47m       192.168.1.27   k8s-master
kube-system   calico-node-lpkq1                           1/2       rpc error: code = 2 desc = container create failed: container_linux.go:265: starting container process caused "chdir to cwd (\"/opt/cni/bin\") set in config.json failed: no such file or directory"
              0                                           46m       192.168.1.27        k8s-master
kube-system   calico-policy-controller-1324707180-vgzj5   0/1       CrashLoopBackOff    14        46m       192.168.1.27   k8s-master
kube-system   etcd-k8s-master                             1/1       Running             0         47m       192.168.1.27   k8s-master
kube-system   kube-apiserver-k8s-master                   1/1       Running             0         47m       192.168.1.27   k8s-master
kube-system   kube-controller-manager-k8s-master          1/1       Running             0         47m       192.168.1.27   k8s-master
kube-system   kube-dns-3913472980-t95mg                   0/3       ContainerCreating   0         47m       <none>         k8s-master
kube-system   kube-proxy-3qhds                            1/1       Running             0         47m       192.168.1.27   k8s-master
kube-system   kube-scheduler-k8s-master                   1/1       Running             0         46m       192.168.1.27   k8s-master
```

When looking at the logs:

### calico-node logs
```
root@k8s-master:~# kubectl logs calico-node-lpkq1 -c install-cni -n kube-system
Error from server (BadRequest): container "install-cni" in pod "calico-node-lpkq1" is waiting to start: rpc error: code = 2 desc = container create failed: container_linux.go:265: starting container process caused "chdir to cwd (\"/opt/cni/bin\") set in config.json failed: no such file or directory"
```

### calico-policy-controller logs
```
root@k8s-master:~# kubectl logs calico-policy-controller-1324707180-vgzj5 -n kube-system
2017-06-14 10:20:29,274 6 INFO Configuring /etc/hosts
Traceback (most recent call last):
  File "<string>", line 559, in <module>
  File "<string>", line 535, in configure_etc_hosts
IOError: [Errno 30] Read-only file system: '/etc/hosts'
controller returned -1

```

Some more information:

```
root@k8s-master:~# kubeadm version
kubeadm version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.0.1163+5e29e1ee055568", GitCommit:"5e29e1ee05556800cd2fe0dc5341d5de54b4ab47", GitTreeState:"clean", BuildDate:"2017-03-13T22:37:31Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
root@k8s-master:~# kubelet --version
Kubernetes v1.6.4
```

## Steps to Reproduce (for bugs)

1. `kubeadm init --pod-network-cidr 192.168.0.0/16`
2. `kubectl apply -f http://docs.projectcalico.org/v2.3/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml `

## Your Environment

* Operating System and version: Ubuntu 16.04

**Comment by sameo** [comment]
cc @gtirloni @runcom

**Comment by runcom** [comment]
stupid guess:
since we don't ship /opt/cni/bin when we install CRI-O
could you `mkdir /opt/cni/bin` before deploying calico and see if it works?
I suspect that's just about it and we need to fix something about it in CRI-O (installation maybe)

**Comment by runcom** [comment]
```
        # This container installs the Calico CNI binaries
        # and CNI network config file on each node.
        - name: install-cni
          image: quay.io/calico/cni:v1.9.1
          command: ["/install-cni.sh"]
          env:
            # The location of the Calico etcd cluster.
            - name: ETCD_ENDPOINTS
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_endpoints
            # The CNI network config to install on each node.
            - name: CNI_NETWORK_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: cni_network_config
          volumeMounts:
            - mountPath: /host/opt/cni/bin
              name: cni-bin-dir
            - mountPath: /host/etc/cni/net.d
              name: cni-net-dir
      volumes:
        # Used by calico/node.
        - name: lib-modules
          hostPath:
            path: /lib/modules
        - name: var-run-calico
          hostPath:
            path: /var/run/calico
        # Used to install CNI.
        - name: cni-bin-dir
          hostPath:
            path: /opt/cni/bin
        - name: cni-net-dir
          hostPath:
            path: /etc/cni/net.d
```
this may be causing this for sure, I'm debugging this

**Comment by runcom** [comment]
this seems an issue with the image config and the kube yaml:
```
          volumeMounts:
            - mountPath: /host/opt/cni/bin
              name: cni-bin-dir
            - mountPath: /host/etc/cni/net.d
              name: cni-net-dir
```
1. calico's saying to mount host's `/opt/cni/bin`to `/host/opt/cni/bin`
2. the image `quay.io/calico/cni:v1.9.1` has the following config:
```
        "Config": {
            "Hostname": "971d7095b61b",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/cni/bin"
            ],
            "Cmd": [
                "/opt/cni/bin/calico"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:360798ae26ad48e6cc6ca16a612269a414b98608a40b48b83553cd0102ec2c69",
            "Volumes": {
                "/opt/cni": {}
            },
            "WorkingDir": "/opt/cni/bin",
            "Entrypoint": null,
            "OnBuild": [],
            "Labels": {}
        },
```
which means the container will start with a `/opt/cni` path in the container fs, but the `WorkingDir` says to chdir to `/opt/cni/bin` which isn't there and fails. So, I suspect `/host/opt/cni/bin` should just be `/opt/cni/bin`? or the image `WorkingDir` should be `/host/opt/cni/bin`
