### ISSUE TITLE
Linkerd GRPC load balancing doesn't work with Calico eBPF

### ISSUE THREAD

**Issue by nstrashevskii** [projectcalico/calico#8628]
Here https://github.com/projectcalico/calico/issues/6908 they recommended setting the parameters `bpfConnectTimeLoadBalancing=Disabled` and `bpfHostNetworkedNATWithoutCTLB=Enabled` ([docs](https://github.com/tigera/docs/commit/feb57d1d4f940f1fa37dadaede253dff9266490d)) , after adding the grpc balancing does not work, tell me what else could be wrong?

## Expected Behavior
uniform balancing of the grpc

## Current Behavior
uneven load distribution between servers during grpc requests
## Steps to Reproduce (for bugs)

```
apiVersion: crd.projectcalico.org/v1
kind: FelixConfiguration
spec:
  bpfConnectTimeLoadBalancing: Disabled
  bpfEnabled: true
  bpfExternalServiceMode: DSR
  bpfHostNetworkedNATWithoutCTLB: Enabled
  bpfLogLevel: ""
  logSeverityScreen: Info
  prometheusMetricsEnabled: true
  reportingInterval: 0s
  vxlanEnabled: true
  vxlanPort: 4789
  vxlanVNI: 4096
```

## Your Environment

* Calico version 3.27
* Orchestrator version (e.g. kubernetes, mesos, rkt): 1.22.15
