### ISSUE TITLE
tunnel interfaces created by Calico are not being removed upon node deletion on sles15 machines

### ISSUE THREAD

**Issue by riyazhakki** [projectcalico/calico#8662]
## Expected Behavior

clean up tunnel interface created by Calico network plugin on node deletion on SLES15 machine

## Current Behavior

tunnel interfaces created by Calico are not being removed upon node deletion on sles15 machines
## Steps to Reproduce (for bugs)

1. create a worker node using 
`sudo $(kubeadm token create --print-join-command)`
2. submit a pod
```
tee redis.yaml << EOF
apiVersion: v1
kind: Pod
metadata:
  name: redis1
spec:
  schedulerName:
  containers:
  - name: redis
    image: redis:latest
    resources:
      requests:
        cpu: "2m"
        memory: "100Mi"
      limits:
        cpu: "2m"
        memory: "100Mi"
EOF

kubectl apply -f redis.yaml
```

3. delete the pod
`kubectl delete pod redis1`

4. delete the node
`kubectl delete node`

## Your Environment

* Calico version docker.io/calico/node:v3.26.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes 1.29
* Operating System and version: centos15
* Link to your project (optional):
