### ISSUE TITLE
Newly created Pod doesn't get ARP response for 169.254.1.1 for 1 minute then succeeds

### ISSUE THREAD

**Issue by lubronzhan** [projectcalico/calico#8689]
## Expected Behavior

Curling k8s internal service succeeds immediately after creating a new pod
## Current Behavior

Before creating more nodes in the cluster, it was fine, but then

Curling the k8s internal service doesn't succeed inside a new pod, it only succeed until 1 minutes later. 

Start a dev pod 
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: network-tools-4
  name: network-tools-4
spec:
  containers:
  - name: network-tools-4
    image: <image>/network-tools
    resources: {}
    command: ["/bin/bash", "-c", "sleep 2000000000000"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  nodeSelector:
    kubernetes.io/hostname: <node name>
```
Keep running curl on it, only succeeded after a minute.
```
[ ~ ]$ date
Tue Apr  2 08:27:25 UTC 2024
[ ~ ]$ kubectl exec -it network-tools-4 -- curl -Ik https://100.64.0.1
curl: (7) Failed to connect to 100.64.0.1 port 443 after 3077 ms: Host is unreachable
command terminated with exit code 7
[ ~ ]$ date
Tue Apr  2 08:27:31 UTC 2024
[ ~ ]$ kubectl exec -it network-tools-4 -- curl -Ik https://100.64.0.1
curl: (7) Failed to connect to 100.64.0.1 port 443 after 3062 ms: Host is unreachable
command terminated with exit code 7
[ ~ ]$ date
Tue Apr  2 08:27:38 UTC 2024
[ ~ ]$ kubectl exec -it network-tools-4 -- curl -Ik https://100.64.0.1
curl: (7) Failed to connect to 100.64.0.1 port 443 after 3066 ms: Host is unreachable
command terminated with exit code 7
[ ~ ]$ date
Tue Apr  2 08:27:45 UTC 2024
[ ~ ]$ kubectl exec -it network-tools-4 -- curl -Ik https://100.64.0.1
curl: (7) Failed to connect to 100.64.0.1 port 443 after 3061 ms: Host is unreachable
command terminated with exit code 7
[ ~ ]$ date
Tue Apr  2 08:27:52 UTC 2024
[ ~ ]$ kubectl exec -it network-tools-4 -- curl -Ik https://100.64.0.1
curl: (7) Failed to connect to 100.64.0.1 port 443 after 3082 ms: Host is unreachable
command terminated with exit code 7
[ ~ ]$ date && kubectl exec -it network-tools-4 -- curl -Ik https://100.64.0.1
Tue Apr  2 08:28:01 UTC 2024
HTTP/2 403
audit-id: 0cdd0692-98fa-4ebe-8f59-70b4aa2359f2
cache-control: no-cache, private
content-type: application/json
x-content-type-options: nosniff
x-kubernetes-pf-flowschema-uid: d6ef7519-6937-4431-a367-d3b2750fbbf9
x-kubernetes-pf-prioritylevel-uid: 1de44c2a-9574-4629-965f-ff5f8fd47e39
content-length: 234
date: Tue, 02 Apr 2024 08:28:03 GMT
```

TCPdump on the pod interface from the node, there is a lot of request sent, after 1 minute, the ARP succeeded and got address for `169.254.1.1 `
```
[ ~ ]$ ip link |grep ^75
75: caliccf47853546@if4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1480 qdisc noqueue state UP mode DEFAULT group default
[ ~ ]$ sudo tcpdump -vv -i caliccf47853546
tcpdump: listening on caliccf47853546, link-type EN10MB (Ethernet), capture size 262144 bytes
08:27:05.167010 ARP, Ethernet (len 6), IPv4 (len 4), Request who-has 169.254.1.1 tell 100.122.5.198, length 28
08:27:06.186084 ARP, Ethernet (len 6), IPv4 (len 4), Request who-has 169.254.1.1 tell 100.122.5.198, length 28
...
08:27:14.826143 ARP, Ethernet (len 6), IPv4 (len 4), Request who-has 169.254.1.1 tell 100.122.5.198, length 28
08:27:14.922086 IP6 (hlim 255, next-header ICMPv6 (58) payload length: 16) fe80::dca6:b5ff:fe09:4685 > ff02::2: [icmp6 sum ok] ICMP6, router solicitation, length 16
          source link-address option (1), length 8 (1): de:a6:b5:09:46:85
            0x0000:  dea6 b509 4685
08:27:18.840072 ARP, Ethernet (len 6), IPv4 (len 4), Request who-has 169.254.1.1 tell 100.122.5.198, length 28
08:27:19.850080 ARP, Ethernet (len 6), IPv4 (len 4), Request who-has 169.254.1.1 tell 100.122.5.198, length 28
...
08:28:02.474109 ARP, Ethernet (len 6), IPv4 (len 4), Request who-has 169.254.1.1 tell 100.122.5.198, length 28
08:28:03.498077 ARP, Ethernet (len 6), IPv4 (len 4), Request who-has 169.254.1.1 tell 100.122.5.198, length 28
08:28:03.498106 ARP, Ethernet (len 6), IPv4 (len 4), Reply 169.254.1.1 is-at ee:ee:ee:ee:ee:ee (oui Unknown), length 28 <---------- finally succeeds
08:28:03.498110 IP (tos 0x0, ttl 64, id 41947, offset 0, flags [DF], proto TCP (6), length 60)
    100.122.5.198.35496 > 100.64.0.1.https: Flags [S], cksum 0xceaf (incorrect -> 0xf855), seq 1881565354, win 64800, options [mss 1440,sackOK,TS val 975299781 ecr 0,nop,wscale 8], length 0
```

I assume it's because of the failing ARP that causing this. But then where should I look next to debug this, can someone help give some hints?

## Context

Similar to this one https://github.com/projectcalico/calico/issues/4186 and https://github.com/projectcalico/calico/issues/4123.
But in our env, we don't have to manually add the route to 169.254.1.1, it just takes about 1 minute to get the correct mac address of .169.254.1.1

## Your Environment

* Calico version: 3.19.1, 3.24
* Orchestrator version (e.g. kubernetes, mesos, rkt): 1.22.9, 1.24.10 kubernetes
* Operating System and version: Photon 3
* Link to your project (optional):

**Comment by fasaxc** [comment]
* How big is your cluster?
* How many pods?
* How many network policies do you have?
* What CNI plugin are you using; is this Calico CNI + Calico Policy, or Canal (flannel + Calico Policy), or some other combination?

**Comment by lubronzhan** [comment]
Hi @fasaxc 
1. The cluster has 35 nodes
2. It has 639 pods
3. no network policies are available on the cluster
4. Just Calico CNI installed by the manifest [here](https://github.com/projectcalico/calico/blob/4b416f31b5db73ef3860ccc82aeaf745fb96642a/manifests/calico.yaml) 



The output of calico daemonset if you are interested
```
#capv@itbo2-nokia-ccs-cl-001-master-control-plane-ptxcm [ ~ ]$ kubectl get ds calico-node -n kube-system -oyaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  generation: 1
  labels:
    k8s-app: calico-node
  name: calico-node
  namespace: kube-system
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: calico-node
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: calico-node
    spec:
      containers:
      - env:
        - name: DATASTORE_TYPE
          value: kubernetes
        - name: WAIT_FOR_DATASTORE
          value: "true"
        - name: NODENAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: CALICO_NETWORKING_BACKEND
          valueFrom:
            configMapKeyRef:
              key: calico_backend
              name: calico-config
        - name: CLUSTER_TYPE
          value: k8s,bgp
        - name: IP
          value: autodetect
        - name: CALICO_IPV4POOL_IPIP
          value: Always
        - name: CALICO_IPV4POOL_VXLAN
          value: Never
        - name: FELIX_IPINIPMTU
          valueFrom:
            configMapKeyRef:
              key: veth_mtu
              name: calico-config
        - name: FELIX_VXLANMTU
          valueFrom:
            configMapKeyRef:
              key: veth_mtu
              name: calico-config
        - name: FELIX_WIREGUARDMTU
          valueFrom:
            configMapKeyRef:
              key: veth_mtu
              name: calico-config
        - name: CALICO_DISABLE_FILE_LOGGING
          value: "true"
        - name: FELIX_DEFAULTENDPOINTTOHOSTACTION
          value: ACCEPT
        - name: FELIX_IPV6SUPPORT
          value: "false"
        - name: FELIX_HEALTHENABLED
          value: "true"
        - name: CALICO_IPV4POOL_CIDR
          value: 100.96.0.0/11
        envFrom:
        - configMapRef:
            name: kubernetes-services-endpoint
            optional: true
        image: <calico-image>
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /bin/calico-node
            - -felix-live
            - -bird-live
          failureThreshold: 6
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: calico-node
        readinessProbe:
          exec:
            command:
            - /bin/calico-node
            - -felix-ready
            - -bird-ready
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 250m
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /lib/modules
          name: lib-modules
          readOnly: true
        - mountPath: /run/xtables.lock
          name: xtables-lock
        - mountPath: /var/run/calico
          name: var-run-calico
        - mountPath: /var/lib/calico
          name: var-lib-calico
        - mountPath: /var/run/nodeagent
          name: policysync
        - mountPath: /sys/fs/
          mountPropagation: Bidirectional
          name: sysfs
        - mountPath: /var/log/calico/cni
          name: cni-log-dir
          readOnly: true
      dnsPolicy: ClusterFirst
      hostNetwork: true
      initContainers:
      - command:
        - /opt/cni/bin/calico-ipam
        - -upgrade
        env:
        - name: KUBERNETES_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: CALICO_NETWORKING_BACKEND
          valueFrom:
            configMapKeyRef:
              key: calico_backend
              name: calico-config
        envFrom:
        - configMapRef:
            name: kubernetes-services-endpoint
            optional: true
        image: <calico-image>
        imagePullPolicy: IfNotPresent
        name: upgrade-ipam
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/cni/networks
          name: host-local-net-dir
        - mountPath: /host/opt/cni/bin
          name: cni-bin-dir
      - command:
        - /opt/cni/bin/install
        env:
        - name: CNI_CONF_NAME
          value: 10-calico.conflist
        - name: CNI_NETWORK_CONFIG
          valueFrom:
            configMapKeyRef:
              key: cni_network_config
              name: calico-config
        - name: KUBERNETES_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: CNI_MTU
          valueFrom:
            configMapKeyRef:
              key: veth_mtu
              name: calico-config
        - name: SLEEP
          value: "false"
        envFrom:
        - configMapRef:
            name: kubernetes-services-endpoint
            optional: true
        image: <calico-image>
        imagePullPolicy: IfNotPresent
        name: install-cni
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /host/opt/cni/bin
          name: cni-bin-dir
        - mountPath: /host/etc/cni/net.d
          name: cni-net-dir
      - image: <calico-image>
        imagePullPolicy: IfNotPresent
        name: flexvol-driver
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /host/driver
          name: flexvol-driver-host
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: calico-node
      serviceAccountName: calico-node
      terminationGracePeriodSeconds: 0
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoExecute
        operator: Exists
      volumes:
      - hostPath:
          path: /lib/modules
          type: ""
        name: lib-modules
      - hostPath:
          path: /var/run/calico
          type: ""
        name: var-run-calico
      - hostPath:
          path: /var/lib/calico
          type: ""
        name: var-lib-calico
      - hostPath:
          path: /run/xtables.lock
          type: FileOrCreate
        name: xtables-lock
      - hostPath:
          path: /sys/fs/
          type: DirectoryOrCreate
        name: sysfs
      - hostPath:
          path: /opt/cni/bin
          type: ""
        name: cni-bin-dir
      - hostPath:
          path: /etc/cni/net.d
          type: ""
        name: cni-net-dir
      - hostPath:
          path: /var/log/calico/cni
          type: ""
        name: cni-log-dir
      - hostPath:
          path: /var/lib/cni/networks
          type: ""
        name: host-local-net-dir
      - hostPath:
          path: /var/run/nodeagent
          type: DirectoryOrCreate
        name: policysync
      - hostPath:
          path: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds
          type: DirectoryOrCreate
        name: flexvol-driver-host
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
status:
  currentNumberScheduled: 38
  desiredNumberScheduled: 38
  numberAvailable: 38
  numberMisscheduled: 0
  numberReady: 38
  observedGeneration: 1
  updatedNumberScheduled: 38
```

And ip r did show correct answers at the beginning, but ip neigh shows the mac address after a minute because of the ARP delay
