### ISSUE TITLE
Inconsistent terminationGracePeriodSeconds set in different versions of calico-node daemonset

### ISSUE THREAD

**Issue by BenjaminHuang** [projectcalico/calico#8691]
The calico-node daemonset has terminationGracePeriodSeconds set.

In the manifest version, it's coded as 0:
` 
   terminationGracePeriodSeconds: 0
`

But in the version generated by tigera-operator, it's coded as 5:
` 
   terminationGracePeriodSeconds: 5
`

However,  both versions have prestop hook specified 
```
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/calico-node
              - -shutdown
```

- If terminationGracePeriodSeconds set to 0
  pre-stop hook will be unreachable, this makes the impact of calico-node deletion minimized.

- If terminationGracePeriodSeconds  set to non-zero
  pre-stop hook will cause NetworkUnavailable status set:

```
  conditions:
  - lastHeartbeatTime: "2024-04-03T08:18:42Z"
    lastTransitionTime: "2024-04-03T08:18:42Z"
    message: Calico is running on this node
    reason: CalicoIsUp
    status: "False"
    type: NetworkUnavailable
```

  and eventually cause a no-schedule taint added by kube-controller-manager:

```
  taints:
  - effect: NoSchedule
    key: node.kubernetes.io/network-unavailable
    timeAdded: "2024-04-03T07:17:46Z"
```

However, I'm not sure which is the desired behavior.

## Expected Behavior

terminationGracePeriodSeconds should be consistent in calico-node daemonset, both in manifest and tigera-operator-generated version.

## Current Behavior

terminationGracePeriodSeconds is inconsistent in calico-node daemonset, between manifest and tigera-operator-generated version.

## Possible Solution

set terminationGracePeriodSeconds to 0 in different version of calico-node daemonset

## Steps to Reproduce (for bugs)

1.  Go to installation guide, e.g. https://docs.tigera.io/calico/latest/getting-started/kubernetes/self-managed-onprem/onpremises
2.  Choose the way for installing: manifest or operator in a k8s cluster (optionally using kind)
3.  Follow up the instructions to comple the installation
4.  Try deleing calico-node instance and inspect coressponding node status/taints during deletion.
5.  Compare the different behaviour , in different installation, and focus on difference of terminationGracePeriodSeconds 

## Context

I want calico installation from manifest or from tigera operator has the same behavior, in calico-node deletion.

## Your Environment

* Calico version 3.20.6
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes 1.20.7
* Operating System and version: Ubuntu 20.04
* Link to your project (optional):
