### ISSUE TITLE
only ipv6 monitor error

### ISSUE THREAD

**Issue by AEGEGE** [projectcalico/calico#8765]
I am using helm to install tigera-operator. Because I need to monitor, I have opened nodeMetricsPort: 9091, but in the only ipv6 environment, __address__="fddd:3bcc:a689::66" is found in the Input Labels captured by prometheus, resulting in The monitoring rule failed. Normally it should be __address__="[fddd:3bcc:a689::66]:$port", so I hope to inject a port configuration into it:
```
    ports:
         - containerPort: 9091
           hostPort: 9091
           protocol:TCP
```
But the injection failed. I know it may be a problem with my configuration, but I can't find an example. My wrong configuration is:
```
installation:
   registry: aetest.com:5000
   calicoNetwork:
     ipPools:
     -blockSize: 122
       cidr: fcaa:8888::/64
       encapsulation: VXLAN
       natOutgoing: Enabled
       nodeSelector: all()
     mtu: 0
     nodeAddressAutodetectionV6:
       interface: eth.*|en.*
   enabled: true
   kubeletVolumePluginPath: /data/k8sbasedata/kubelet
   kubernetesProvider: ""
   nodeMetricsPort: 9091
   typhaMetricsPort: 9093
   CalicoNodeDaemonSet:
     template:
       containers:
         ports:
         - containerPort: 9091
           hostPort: 9091
           protocol:TCP
```
