### ISSUE TITLE
ClusterRole mismatching between calico v3.25.2 and v3.26.x or above

### ISSUE THREAD

**Issue by hadi2f244** [projectcalico/calico#8825]
Comparing [Calico v3.26.0](https://raw.githubusercontent.com/projectcalico/calico/v3.26.0/manifests/calico-typha.yaml) manifest with [v3.25.2](https://raw.githubusercontent.com/projectcalico/calico/v3.25.2/manifests/calico-typha.yaml) shows this different 

```
# Source: calico/templates/calico-node-rbac.yaml
# Include a clusterrole for the calico-node DaemonSet,
# and bind it to the calico-node serviceaccount.
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: calico-node
rules:
  # Used for creating service account tokens to be used by the CNI plugin
  - apiGroups: [""]
    resources:
      - serviceaccounts/token
    resourceNames:
      - calico-cni-plugin  <--> calico-node
    verbs:
      - create
```

## Possible Solution

Merging this part of manifests: 

```
# Source: calico/templates/calico-node-rbac.yaml
# Include a clusterrole for the calico-node DaemonSet,
# and bind it to the calico-node serviceaccount.
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: calico-node
rules:
  # Used for creating service account tokens to be used by the CNI plugin
  - apiGroups: [""]
    resources:
      - serviceaccounts/token
    resourceNames:
      - calico-cni-plugin
      - calico-node
    verbs:
      - create
```

## Your Environment

* Calico v3.25.2 and v3.26.0
