### ISSUE TITLE
HostEndpoint node selector + interface name regexp

### ISSUE THREAD

**Issue by jonas-jasas** [projectcalico/calico#8840]
## Feature request
To reduce `HostEndpoint` resource count in case of multiple node scenario, would be great to have `HostEndpoint` node selector (based on k8s labels) and interface name match using regexp.

**Comment by caseydavenport** [comment]
@jonas-jasas could you provide some more details about what you are looking for here? 

- How have you configured your cluster's host endpoints?
- How many host endpoints do you have?
- Are these host endpoints causing problems?

**Comment by JonasJasas** [comment]
- Using Calico Operator
- 10
- No

Each node has 4 network interfaces, so I have to create 40 `HostEndpoint` resources instead of 4.

**Comment by caseydavenport** [comment]
Have you considered Calico's auto host endpoint feature? https://docs.tigera.io/calico/latest/network-policy/hosts/kubernetes-nodes#automatic-host-endpoints

Calico can create a single host endpoint per-node that represents all interfaces on the node.

**Comment by JonasJasas** [comment]
Is it possible to classify which interface is external which internal using auto host endpoint feature? In my case I do this:
```
apiVersion: projectcalico.org/v3
kind: HostEndpoint
metadata:
  name: stag-hw1-eth1
  labels:
    role: worker-ext
spec:
  interfaceName: eth1
  node: stag-hw1

---

apiVersion: projectcalico.org/v3
kind: HostEndpoint
metadata:
  name: stag-hw1-eth3
  labels:
    role: worker-ext
spec:
  interfaceName: eth3
  node: stag-hw1

---

apiVersion: projectcalico.org/v3
kind: HostEndpoint
metadata:
  name: stag-hw2-eth1
  labels:
    role: worker-ext
spec:
  interfaceName: eth1
  node: stag-hw2

---

apiVersion: projectcalico.org/v3
kind: HostEndpoint
metadata:
  name: stag-hw2-eth3
  labels:
    role: worker-ext
spec:
  interfaceName: eth3
  node: stag-hw2
```
