### ISSUE TITLE
Tigera-operator helm chart unable to set csiNodeDriverDaemonSet resource memory/cpu requests & limits

### ISSUE THREAD

**Issue by mashiofu-cafex** [projectcalico/calico#8853]
I am unable to add resource limits/requests in my K8s cluster for csi-node-driver pods

Please see my config in my `values.yaml` file:

```
    csiNodeDriverDaemonSet: #Currently an issue and PR open to allow these values to be supported - https://github.com/projectcalico/calico/issues/8400
        spec:
            template:
                spec:
                    containers:
                    - name: csi-node-driver
                      resources:
                        limits:
                            memory: 100Mi
                        requests:
                            cpu: 75m
```

I am using [projectcalico/tigera-operator  v3.28.0](https://github.com/projectcalico/calico/tree/master/charts/tigera-operator) helm chart.

## Expected Behavior

When helm installing/upgrading for `csiNodeDriverDaemonSet` resource limits & request, the pods and daemonset should be configured afterwards.

## Current Behavior

Helm detects the change but the change is not configured, when running helm upgrade:

```
Comparing release=calico, chart=projectcalico/tigera-operator
tigera-operator, default, Installation (operator.tigera.io) has changed:
...
+   csiNodeDriverDaemonSet:
+     spec:
+       template:
+         spec:
+           containers:
+           - name: csi-node-driver
+             resources:
+               limits:
+                 memory: 100Mi
+               requests:
+                 cpu: 75m
    imagePullSecrets: []
...

Affected releases are:
  calico (projectcalico/tigera-operator) UPDATED

Do you really want to apply?
  Helmfile will apply all your changes, as shown above.

 [y/n]: y
Upgrading release=calico, chart=projectcalico/tigera-operator
Release "calico" has been upgraded. Happy Helming!
NAME: calico
LAST DEPLOYED: Wed May 22 18:08:40 2024
NAMESPACE: tigera-operator
STATUS: deployed
REVISION: 13
TEST SUITE: None

Listing releases matching ^calico$
calico  tigera-operator 13              2024-05-22 18:08:40.510076 -0500 CDT    deployed        tigera-operator-v3.28.0 v3.28.0    

UPDATED RELEASES:
NAME     CHART                           VERSION   DURATION
calico   projectcalico/tigera-operator   v3.28.0        50s
```

Yet after this is applied, the `csiNodeDriver` daemonSet & pods resource values are still not configured. Unfortunately, there are no errors in the logs indicating where the issue can be occurring.

There has been a couple of similar issues/PRs that claim this issue has been resolved, here are a couple:
- https://github.com/tigera/operator/pull/3254
- https://github.com/projectcalico/calico/issues/8400
- https://github.com/projectcalico/calico/issues/7561
