### ISSUE TITLE
host to service network not working after reboot/join after upgrade from v3.26.3 to v3.27.3 (v3.28.0) ebpf dataplane/vxlan/no kube-proxy/dsr

### ISSUE THREAD

**Issue by a-sorokin-sdg** [projectcalico/calico#8867]
host to service network not working after reboot/join after upgrade from v3.26.3 to v3.27.3 ebpfdataplane/vxlan/no kube-proxy/dsr
killing calico-node pod immediately fixing the problem

## Expected Behavior
host to service network working well after node reboot/join

## Current Behavior
host to kube service network not working after reboot/join node unless you kill calico-node pod
it start working after it

## Possible Solution
kill calico-node pod on restarted or joined node
```
kubectl delete pod -n calico-system calico-node-xxxxx
```

## Steps to Reproduce (for bugs)
1. reboot node
2. try to connect from the rebooted host to any kube service (kube-dns like example)
```
nslookup example.com {kube-dns svc ip}
```
3. fail

## Context
Any pods with a host network would fail to start after rebooting/joining node
Cluster network works fine

## Your Environment

* Calico version: v3.27.3 v3.28.0
* Helm chart: projectcalico/tigera-operator:v3.28.0
```yaml
  - chart: projectcalico/tigera-operator
    version: v3.28.0
    name: calico 
    namespace: tigera-operator
    values:
      - installation:
          calicoNetwork:
            linuxDataplane: BPF
            mtu: 8950
            bgp: Disabled
            ipPools:
              - cidr: 10.244.0.0/14
                blockSize: 20
                encapsulation: VXLAN
```
```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: kubernetes-services-endpoint
  namespace: tigera-operator
data:
  KUBERNETES_SERVICE_HOST: "172.24.1.15"
  KUBERNETES_SERVICE_PORT: "6443"
```
```yaml
apiVersion: projectcalico.org/v3
kind: FelixConfiguration
metadata:
  annotations:
    operator.tigera.io/bpfEnabled: "true"
  creationTimestamp: "2023-11-09T09:16:01Z"
  generation: 1
  name: default
  namespace: calico-system
  resourceVersion: "65934135"
  uid: 5d0de475-8603-4e7b-9282-baecc231e48e
spec:
  bpfEnabled: true
  bpfExternalServiceMode: DSR
  bpfLogLevel: ""
  floatingIPs: Disabled
  healthPort: 9099
  logSeverityScreen: Info
  reportingInterval: 0s
  vxlanMTU: 8950
  vxlanVNI: 4096
```
```
# /etc/NetworkManager/conf.d/calico.conf
[keyfile]
unmanaged-devices=interface-name:cali*;interface-name:bpf*.cali*;interface-name:tunl*;interface-name:vxlan.calico;interface-name:vxlan-v6.calico;interface-name:wireguard.cali;interface-name:wg-v6.cali
```
```yaml
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
certificateKey: ""
skipPhases:
  - addon/kube-proxy
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
networking:
  serviceSubnet: "10.243.0.0/16"
  podSubnet: "10.244.0.0/14"
  dnsDomain: "l8s.local"
controllerManager:
  extraArgs:
    "node-cidr-mask-size": "20"
    "allocate-node-cidrs": "false"
apiServer:
  certSANs:
    - "172.24.1.15"
    - "172.24.1.16"
    - "k8clust-lon01.l8s.space"
clusterName: "k8clust-lon01"
controlPlaneEndpoint: "k8clust-lon01.l8s.space:6443"
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
maxPods: 4000
cgroupDriver: systemd
serverTLSBootstrap: true
```
* Orchestrator version: 
kubernetes 1.29.5
* Operating System and version: 
```
# uname -r
5.14.0-452.el9.x86_64
# cat /etc/os-release
NAME="CentOS Stream"
VERSION="9"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="9"
PLATFORM_ID="platform:el9"
PRETTY_NAME="CentOS Stream 9"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:centos:centos:9"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://issues.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"
```
[calico-node log after new node join](https://github.com/user-attachments/files/15513189/calico-node.join.log.gz)
[calico-node install-cni log after new node join](https://github.com/user-attachments/files/15513192/calico-node-cni.join.log.gz)
[calico-node log after killling pod](https://github.com/user-attachments/files/15513193/calico-node.4.log.gz)
[ccalico-node install-cni log after killling pod](https://github.com/user-attachments/files/15513194/calico-node-cni.4.log.gz)

**Comment by tomastigera** [comment]
> killing calico-node pod immediately fixing the problem

What changes after killing the pod. Could you share your routing table before/after?

**Comment by tomastigera** [comment]
Did you have ctlb disabled before upgrade?

**Comment by a-sorokin-sdg** [comment]
> Did you have ctlb disabled before upgrade?

Nope
Can you provide additional parameters which I need to set up?
I think it is something with

bpfConnectTimeLoadBalancingEnabled
bpfConnectTimeLoadBalancing
bpfHostNetworkedNATWithoutCTLB

It's all not set up currently

**Comment by a-sorokin-sdg** [comment]
> > killing calico-node pod immediately fixing the problem
> 
> What changes after killing the pod. Could you share your routing table before/after?

Routes almost did not change
I am checkins via dns resolviong against kube-dns service and it is there after reboot (when it is not working) and after killing pod (when it is working).

```
10.243.0.10     169.254.1.1     255.255.255.255 UGH   0      0        0 bpfin.cali
```

**Comment by tomastigera** [comment]
> > > killing calico-node pod immediately fixing the problem
> > 
> > 
> > What changes after killing the pod. Could you share your routing table before/after?
> 
> Routes almost did not change I am checkins via dns resolviong against kube-dns service and it is there after reboot (when it is not working) and after killing pod (when it is working).
> 
> ```
> 10.243.0.10     169.254.1.1     255.255.255.255 UGH   0      0        0 bpfin.cali
> ```

That route is correct. Since iirc 3.27 we route traffic from host to UDP service via that device by default.

![CalicoCon 2024 - Calico eBPF](https://github.com/projectcalico/calico/assets/49207409/485ab8cf-ad35-4c62-830a-2e4537a402a8)

**Comment by tomastigera** [comment]
I wonder is some routes caching is in play. Could you dump `ip route show cached` ?

**Comment by a-sorokin-sdg** [comment]
> I wonder is some routes caching is in play. Could you dump `ip route show cached` ?
`ip route show cached`
it is empty before and after killing the pod

BTW
Apparently, I have a problem with only services pinned in the route table
And apparently, they are all UDP services (dns services)
There are no tcp services in the route table and they are working fine (tested kube api service via cservice api and nginx ingress)

**Comment by tomastigera** [comment]
Just to confirm, do you see the same problem from host-networked pods/processes or from regular pods as well?

I tried to reproduce the issue, I created a cluster in gcp with kubeadm and installed calico 3.26.4 and upgraded to 3.28 and my DNS did worked just fine.

Would you be able to tcpdump whether your traffic is reaching the service, what kind of packets are exiting from `bpfout.cali` on your test node?

If your cluster is not a production cluster we could dig deeper with enabling bpf logging to get some more useful logs. Ideally we could sync at calico users slack.

**Comment by a-sorokin-sdg** [comment]
> Just to confirm, do you see the same problem from host-networked pods/processes or from regular pods as well?

Regular pods don't have a problem. They work fine.

So only  host-networked pods/processes have problem

**Comment by a-sorokin-sdg** [comment]
> Would you be able to tcpdump whether your traffic is reaching the service, what kind of packets are exiting from `bpfout.cali` on your test node?

[bpfout.cali.pcap.gz](https://github.com/user-attachments/files/15789919/bpfout.cali.pcap.gz)

I tested with
```bash
nslookup openebs-api-rest.openebs.svc.l8s.local. 10.243.0.10
```

**Comment by tomastigera** [comment]
That doesn't seem to be a problem :arrow_up: Do you see packets returning to the client in both cases? `10.243.0.10` is a local pod or remote?

you could also enable :arrow_down:  in default `felixconfiguration` and provide bpf logs from the node using `bpftool prog tracelog > log.txt` for the case when it does not work. That should give us good insight.
```
bpfLogLevel: Debug
bpfLogFilters:
  - all: host 172.24.1.29 and udp port 53
```

**Comment by a-sorokin-sdg** [comment]
> `10.243.0.10` is a local pod or remote?

it's a service IP 
pods behind that IP are remote
BTW hostNetwoork -> pod IP has no issue

**Comment by a-sorokin-sdg** [comment]
> bpfLogLevel: Debug
> bpfLogFilters:
>   - all: host 172.24.1.29 and udp port 53

that does not work
this changes have been accepted by API
```yaml
  bpfLogLevel: Debug
  bpfLogFilters:
    all: host 172.24.1.29 and udp port 53
```
however bpfLogFilters property disappeared from object
so anyway here is a log probably not filtered

[bpflog.txt.gz](https://github.com/user-attachments/files/15800942/bpflog.txt.gz)
