### ISSUE TITLE
csi-node-driver pods get 10.88.0.2 ips

### ISSUE THREAD

**Issue by simonostendorf** [projectcalico/calico#8869]
## Expected Behavior

I want to use IPs from my podCIDR range (IPAM IPPool range) and not static `10.88.0.2` ip.

## Current Behavior

`csi-node-driver` pods and pods starting before calico pods are ready get 10.88.0.x as ip address.

![image](https://github.com/projectcalico/calico/assets/70595012/0bbc867a-906a-4607-9328-1fb272bde4f4)

After restarting the pods, they get an ip from the podCIDR.
Also new csi-node-driver pods will get these ips as long as the daemonset is not restarted using `kubectl rollout restart`.

![image](https://github.com/projectcalico/calico/assets/70595012/b37c0042-3f30-4dd8-8b5e-b9f19b8e1993)

## Possible Solution

I think I need to prevent containerd from starting the csi-node-driver pods before the calico-node pods are started. Because in the following screenshot you can see that they start before. And i read online that 10.88.0.2 is the ip that containerd uses if no cni is installed.

![image](https://github.com/projectcalico/calico/assets/70595012/8d24f188-238b-495f-b377-4fc6fc4c36a3)

## Steps to Reproduce (for bugs)

1. create fresh cluster with cluster-api using kubeadm
2. deploy calico with helm (see values below)
3. deploy coredns with helm
4. deploy vault-agent-injector with helm (because secret for hcloud-cloud-controller-manager will be injected using vault)
5. deploy hetzner-cloud-controller-manager with helm (with enabled routes-controller)
6. restart coredns and vault-injector deployment so that they get a valid ip address from the podCIDR

## Context

pods with 10.88.0.x IPs are not reachable and calico-kube-controller can't reach coredns with that ip.

## Your Environment

* Calico version v3.28.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes 1.30.1 using kubeadm
* Operating System and version: ubuntu 22.04
* Link to your project (optional): none

### Cilium Helm Values

```yaml
installation:
  cni:
    type: Calico # default, but must be set here if ipam is changed
    ipam:
      type: HostLocal # use podCIDR assigned by kube-controller-manager, that is also used by route-controller in hcloud-cloud-controller-manager
  calicoNetwork:
    bgp: Enabled # default
    linuxDataplane: BPF
    hostPorts: Disabled
    ipPools:
      - name: default-ipv4
        cidr: 10.100.0.0/16
        encapsulation: None # use native routing using routes created by hcloud-cloud-controller-manager
        blockSize: 24
        natOutgoing: Enabled
        nodeSelector: all()
  controlPlaneReplicas: 2
  controlPlaneNodeSelector:
    node-role.kubernetes.io/control-plane: ""
  typhaMetricsPort: 9093
  typhaDeployment:
    spec:
      template:
        spec:
          nodeSelector:
            node-role.kubernetes.io/control-plane: ""
  nonPrivileged: Disabled # not possible if using BPF
defaultFelixConfiguration:
  enabled: true
  prometheusMetricsEnabled: true
  bpfEnabled: true
  bpfExternalServiceMode: DSR
  bpfKubeProxyIptablesCleanupEnabled: true
resources: {}
apiServer:
  enabled: true # default
tigeraOperator:
  version: v1.34.0
calicoctl:
  tag: v3.28.0
kubernetesServiceEndpoint:
  host: api.mycluster.tld
  port: 6443
```
