### ISSUE TITLE
calico network policy does not work as expected

### ISSUE THREAD

**Issue by chenxinlong** [projectcalico/calico#8948]
## Steps to Reproduce (for bugs)

1. create two pod a and b on the same namespace : 

```yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: a
  labels:
    app: a
spec:
  containers:
  - name: netshot
    image: nicolaka/netshoot:latest
    command:
      - sleep
      - "infinity"

---
apiVersion: v1
kind: Pod
metadata:
  name: b
  labels:
    app: b
spec:
  containers:
  - name: netshot
    image: nicolaka/netshoot:latest
    command:
      - sleep
      - "infinity"
```

2. create two global netwok policy : 
```yaml
---
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: allow-all
spec:
  selector: all()
  order: 200000 # set a large order 
  types:
  - Egress
  - Ingress
  egress:
    - action: Log
    - action: Allow
  ingress:
    - action: Log
    - action: Allow

---
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: deny-b2a
spec:
  selector: app in {'a'}
  order: 10
  types:
  - Ingress
  ingress:
    - action: Deny
      protocol: TCP
      destination:
        selector: app in {'b'}
```

3. pod b visit a 
```
root@worker002:~# kubectl exec -it a -- bash
a:~# nc -l -k 8888
```
```
root@worker002:~# kubectl get po -o wide
NAME   READY   STATUS    RESTARTS   AGE    IP              NODE        NOMINATED NODE   READINESS GATES
a      1/1     Running   0          120m   100.67.254.19   worker002   <none>           <none>
b      1/1     Running   0          120m   100.67.254.26   worker002   <none>           <none>
root@worker002:~#
root@worker002:~# kubectl exec -it b -- bash
b:~#
b:~# echo "hello" | nc 100.67.254.19 8888
hello
```
pod b successfully send a tcp message "hello" to pod a. 

## Expected Behavior 

What I expected is that policy `allow-all` has a large order so it has lower priority than policy `deny-b2a`. So the traffic from b to a should match the rule as follow : 
```
  ingress:
    - action: Deny
      protocol: TCP
      destination:
        selector: app in {'b'}
```

so b cannot visit a by using TCP protcol.

## Your Environment

* Calico version : 
    ```
    root@worker002:~# calicoctl version
    Client Version:    v3.26.3
    Git commit:        bdb7878af
    Cluster Version:   v3.26.3
    Cluster Type:      typha,kdd,k8s,operator,bgp,kubeadm
    ```
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes v1.24.7
* Operating System and version: ubuntu 22.04 
* Link to your project (optional):
