### ISSUE TITLE
Full cone NAT

### ISSUE THREAD

**Issue by NinoSkopac** [projectcalico/calico#9008]
I did wanna post this in your slack, but one isn't able to join Calico slack without a @tigera.io email, which I don't have.

As the title says, I must have full cone nat in pods in a certain namespace.

I've never worked with Calico before, so I'll definitely get on it and start figuring it out, but any help is highly appreciated.

By default, pods have symmetric nat, at least in eks.

I've tested NAT on EC2 (without k8s):

    % pystun3
    NAT Type: Full Cone

Different story inside pods:

    % kubectl run natdisco --rm -i --tty --image=yarmak/natdisco --restart=Never
    NAT Type: Symmetric

Nino

**Comment by caseydavenport** [comment]
You can join the Calico Users slack with any email. Here's a link: https://slack.projectcalico.org/

**Comment by caseydavenport** [comment]
Could you share some more detail about your use-case?

**Comment by NinoSkopac** [comment]
Sure, and thank you for your response. 

My use case is a k8s pod which requires port forwarding on 50000-50100/udp.

It requires full or restricted cone nat. Definitely not symmetric. 

Have a great day!

Nino

**Comment by caseydavenport** [comment]
To make sure I understand, I'd like to talk about this in terms of connectivity requirements rather than generic classes of NAT, as that's typically how Kubernetes thinks about this.

Sounds like you need the ability to map UDP ports 50000-50100 on an external IP such that the traffic is DNAT'd to a particular pod IP (i.e., "restricted cone NAT")

Sounds like it would be nice-to-have (but not required) that egress traffic from the pod is SNAT's to the same external IP address (i.e., "full cone NAT")

For the former (ingress only) there are a variety of solutions that can provide stable addressing such as LoadBalancer / NodePort services, although as far as I know they do not currently support port ranges which means you would need to specify all 100 ports individually, which is a bit tedious.

**Comment by NinoSkopac** [comment]
@caseydavenport Yup, I think you nailed it.

Let me try to simplify it, let me show you a PoC I'm trying to get working.
(pystun3 is a NAT type detection utility.)

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pystun3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pystun3
  template:
    metadata:
      labels:
        app: pystun3
    spec:
      containers:
        - name: pystun3
          image: skopac/pystun3:latest
          imagePullPolicy: IfNotPresent
```

What I tried already:
1. `--network=host`
2.  run pod on instance which is in a public subnet
3. NodePort

How would you get this to output anything but symmetric nat in eks?
