### ISSUE TITLE
Calico Network Policy operator version 3.28.1  does not seem to work on IPv6 EKS version 1.30 

### ISSUE THREAD

**Issue by t29-cristian** [projectcalico/calico#9099]
## Expected Behavior
When I spin up a new IPv6 EKS cluster (v 1.30) and follow the official installation instructions for Install EKS with Amazon VPC networking (https://docs.tigera.io/calico/latest/getting-started/kubernetes/managed-public-cloud/eks) I expect the Network Policy engine to work just like it would on a IPv4 EKS cluster (v 1.30).
The steps outlined below work without any issues when ipFamily: IPv4 (eksctl default)
Operator version: 3.28.1

## Current Behavior
After I install the Operator, provide the Install CRD as per the docs and the ApiServer CRD (https://docs.tigera.io/calico/latest/operations/install-apiserver#install-the-api-server) when I create a default deny-all policy in a namespace, nothing is blocked (ingress or egress)

## Steps to Reproduce (for bugs)
Create IPv6 EKS cluster using following eks.yaml (eksctl create cluster -f eks.yaml)

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: netpolclust
  region: eu-central-1
  version: "1.30"

availabilityZones: ['eu-central-1a', 'eu-central-1b']

kubernetesNetworkConfig:
  ipFamily: IPv6

addons:
  - name: vpc-cni
  - name: coredns
  - name: kube-proxy

iam:
  withOIDC: true

managedNodeGroups:
- name: spots
  instanceTypes: ["c5a.large", "c6a.large"]
  spot: true
  desiredCapacity: 4
```

Install Operator
```
kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.28.1/manifests/tigera-operator.yaml
```
```
kubectl create -f - <<EOF
kind: Installation
apiVersion: operator.tigera.io/v1
metadata:
  name: default
spec:
  kubernetesProvider: EKS
  cni:
    type: AmazonVPC
  calicoNetwork:
    bgp: Disabled
EOF
```

Install API server
```
kubectl create -f - <<EOF
apiVersion: operator.tigera.io/v1
kind: APIServer
metadata:
  name: default
spec: {}
EOF
```

Create namespace and simple deployment
```
kubectl create namespace test
```

Then apply the following simple deployment
```
kubectl apply -f - <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: test
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: public.ecr.aws/nginx/nginx:1.21
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: test
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
EOF
```
Create deny all policy
```
kubectl apply -f - <<EOF
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: test
spec:
  selector: all()
  types:
    - Ingress
    - Egress
EOF
```

Use a simple pod to connect to the service from another namespace (default in my case)
```
kubectl run -it --rm curl-test --image=curlimages/curl -n default -- sh -c 'curl nginx-service.test'
```

## Context
I would like to use the Calico Network Policy engine instead of the AWS VPC-CNI engine due to it's rich features.

## What I also tried
Looking through the docs I found that you can patch the FelixConfiguration with ipv6Support (https://docs.tigera.io/calico/latest/reference/resources/felixconfig#sample-yaml) but on the calico-node I see no difference (it might be me misunderstanding the option in the context)

**Comment by frozenprocess** [comment]
Change your installation manifest with the following and give it a try.
```
kubectl replace -f - <<EOF
kind: Installation
apiVersion: operator.tigera.io/v1
metadata:
  name: default
spec:
  kubernetesProvider: EKS
  cni:
    type: AmazonVPC
  calicoNetwork:
    bgp: Disabled
    nodeAddressAutodetectionV6:
     kubernetes: NodeInternalIP
EOF
```
