### ISSUE TITLE
timed out waiting for interface matching the management IP (192.168.229.229) of network Calico，windows node

### ISSUE THREAD

**Issue by 13567436138** [projectcalico/calico#9236]
## Expected Behavior

allocate ip ok

## Current Behavior

firewall is closed in windows
```
root@k8s-master01:~# kubectl get node
NAME              STATUS   ROLES           AGE   VERSION
k8s-master01      Ready    control-plane   15d   v1.31.0
k8s-worker01      Ready    <none>          15d   v1.31.0
k8s-worker02      Ready    <none>          15d   v1.31.0
win-f1njfokn3tm   Ready    <none>          27m   v1.31.0
```
```
  Warning  FailedCreatePodSandBox  4s    kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "cf8199556fa7cd64da0971c6dfa030be43b42d0e9c20a2ccc8fb9c4831bc395b": plugin type="calico" name="Calico" failed (add): timed out waiting for interface matching the management IP (192.168.229.229) of network Calico
```

```
apiVersion: v1
kind: Pod
metadata:
  name: windows-pod
spec:
  containers:
  - name: windows-container
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    command: ["powershell.exe", "-Command", "while($true) { Write-Host 'Hello, Windows!' -ForegroundColor Green; Start-Sleep -Seconds 1 }"]
  nodeSelector:
    kubernetes.io/os: windows
  os:
    name: windows
```

## Steps to Reproduce (for bugs)

1.install windows node
2.apply the yaml above
3.
4.

## Your Environment

* Calico version v3.28.0
* Orchestrator version (e.g. kubernetes, mesos, rkt):k8s 1.31.0
* Operating System and version: ubuntu2404
* Link to your project (optional):
