### ISSUE TITLE
Configuring standard kubernetes networking policies to take priority over calico GlobalNetworkPolicy 

### ISSUE THREAD

**Issue by 1602077** [projectcalico/calico#9292]
Hi,

I am having some trouble configuring a `GlobalNetworkPolicy` to work within environments that already have plain kubernetes (`networking.k8s.io/v1`) policies installed.

I am the administer of a cluster and would like to block access to a number of IPs but otherwise not interfere with any of my users traffic. My understanding is that calico will treat `networking.k8s.io/v1` network policies with an order of `1000` and so if I use a `GlobalNetworkPolicy` with a lower order the kubernetes policy should take priority, is this correct?

The issue I am having is that the calico `GlobalNetworkPolicy` always appears to take priority over the kubernetes one. I expect this is an issue on my part with understanding the documentation, any pointers would be massively appreciated.

Converting users policy from kubernetes `NetworkPolicies` to calico `NetworkPolicies` in this case in unfortunately not immediately feasible, due to a large number of tenants.

## Current Behavior

In my environment I am applying the following policy:
```yaml
apiVersion: crd.projectcalico.org/v1
kind: GlobalNetworkPolicy
metadata:
  name: metadata-restriction-policy
spec:
  order: 999
  egress:
    - action: Deny
      destination:
        nets:
          - xxx.xxx.xxx.xxx/32
          - yyy:yyy::yyy/128
      protocol: TCP
      source:
        selector: all()
    - action: Deny
      destination:
        nets:
          - xxx.xxx.xxx.xxx/32
          - yyy:yyy::yyy/128
      protocol: UDP
      source:
        selector: all()
     - action: Allow
  types:
    - Egress
```

Implementing a default deny all policy (mimicking what users of the cluster may do).
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-egress
  namespace: app-1
spec:
  podSelector: {}
  policyTypes:
  - Egress
```

Applying some test resources:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: app-1
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
      name: http
    command: ["/bin/sh", "-c"]
    args:
    - |
      sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'
---
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  namespace: app-1
  labels:
    app: ubuntu
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command: ["/bin/sh", "-c", "sleep infinity"]
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: app-1
spec:
  ports:
  - port: 80
  selector:
    app: nginx
```

I would expect to *not* be able to connect from the ubuntu pod to nginx, as I believe I have nothing in my `GlobalNetworkPolicy` that should affect this request and I have a default deny all policy in my user namespace. However my request is accepted:

```bash
 kubectl exec --stdin --tty -n app-1 ubuntu -- /bin/bash
root@ubuntu:/# wget  nginx.app-1.svc.cluster.local:80/
--2024-09-30 08:26:44--  http://nginx.app-1.svc.cluster.local/
Resolving nginx.app-1.svc.cluster.local (nginx.app-1.svc.cluster.local)... 10.254.51.174
Connecting to nginx.app-1.svc.cluster.local (nginx.app-1.svc.cluster.local)|10.254.51.174|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 615 [text/html]
Saving to: 'index.html'

index.html.11                           100%[==============================================================================>]     615  --.-KB/s    in 0s

2024-09-30 08:26:44 (2.90 MB/s) - 'index.html' saved [615/615]
```

Cheers for your help with this!

## Your Environment

* Calico version: v3.27.3
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes (v1.30.2)
* Operating System and version: Fedora CoreOS 39 [2024-05-23]
