### ISSUE TITLE
pod2daemon-flexvol  as initContainer could not started in centos7.9 and nodeagent~uds/uds not installed

### ISSUE THREAD

**Issue by KubeKyrie** [projectcalico/calico#9338]
## Expected Behavior

calico-node running successfully

## Current Behavior

calico-node initContainer `flexvol-driver` could not be started and no container log to help debug.
I create cluster by kubespray and its calico has initContainer flexvol-driver

```
initContainers:
      - image: quay.io/calico/pod2daemon-flexvol:v3.28.1
        imagePullPolicy: IfNotPresent
        name: flexvol-driver
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /host/driver
          name: flexvol-driver-host
 .......
volumes:
      - hostPath:
          path: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds
          type: DirectoryOrCreate
        name: flexvol-driver-hos
```
However, uds not installed  into `/usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds`, which causes calico-node `Init:CrashLoopBackOff` 

```
[root@controller-node-1 calico]# kubectl get po -n kube-system
NAME                                        READY   STATUS                  RESTARTS        AGE
calico-kube-controllers-869bddc69-9bg2f     0/1     ContainerCreating       0               4h48m
calico-node-2cww8                           0/1     Init:CrashLoopBackOff   12 (91s ago)    38m
calico-node-5qkv6                           0/1     Init:CrashLoopBackOff   12 (111s ago)   38m
calico-node-6cwkw                           0/1     Init:CrashLoopBackOff   12 (98s ago)    38m
calico-node-mtcvl                           0/1     Init:CrashLoopBackOff   12 (117s ago)   38m
calico-node-tzqxl                           0/1     Init:CrashLoopBackOff   12 (87s ago)    38m
calico-node-vwkhp                           0/1     Init:CrashLoopBackOff   12 (109s ago)   38m
calico-node-xcxwl                           0/1     Init:CrashLoopBackOff   12 (108s ago)   38m
```
 
Note that, Calico v3.27.3 does not have this problem and I have tried.

## Steps to Reproduce (for bugs)

1. use centos7.9 to create cluster by kubespray lastest version 
2. check calico-node status

## Your Environment

* Calico version  v3.28.1
* Calico dataplane (iptables, windows etc.)
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version: centos 7.9  
* Link to your project (optional):
