### ISSUE TITLE
GC Stops Working, Leading to High IPAM Resource Usage

### ISSUE THREAD

**Issue by mahmoudghonimfinout** [projectcalico/calico#9371]
### Environment:
- Kubernetes Provider: EKS
- EKS Cluster Version: 1.30
- Calico Version: v3.28.0
- Calico Installation Method: Calico Operator
- Additional Detail: Frequent node rotation on the cluster 

### Installation Configuration:
```yaml
kind: Installation
apiVersion: operator.tigera.io/v1
metadata:
  name: default
spec:
  kubernetesProvider: EKS
  cni:
    type: Calico
  registry: quay.io
  calicoNetwork:
    bgp: Disabled
    ipPools:
      - cidr: 172.17.0.0/16
        encapsulation: VXLANCrossSubnet
        natOutgoing: Enabled
```

### Problem Description:
At some point, the garbage collection (GC) in Calico stops working, resulting in the accumulation of stale resources. This leads to the following issues:
- High IPAM Resource Usage:
  - IPAM blocks reach a count of 1024.
  - Block affinities and IPAM handles also show high numbers, indicating they are not being cleaned up.
- Impact on Pod Functionality:
  - DNS resolution issues occur on the pods.
  - To resolve the issue, I need to manually delete stale resources from IPAM blocks, block affinities, and handles.

### Steps to Reproduce:
1. Install Calico on an EKS cluster using the configuration provided above.
2. Run workloads on the cluster over an extended period.
3. Ensure that the environment has a high rotation of nodes (frequent addition and removal of nodes - ?spot?).
4. Observe the IPAM blocks and handles accumulation.

### Expected Behavior:
The Calico GC process should automatically clean up stale IPAM blocks, block affinities, and handles, ensuring resources are not exhausted.

### Actual Behavior:
The GC process appears to stop working, causing the buildup of stale IPAM resources. This leads to DNS resolution errors on pods, requiring manual intervention to delete these stale resources.

### Additional Information:
- The issue is confirmed by observing the ipam_allocations_gc_candidates metric. When the problem occurs, there is a noticeable increase in the number of GC candidates, which continues to rise until it reaches a very high number, indicating that the GC process is not functioning as expected.
- I can confirm that the issue is due to the GC stopping because I can see a significant increase in unused IPAM blocks, block affinities, and IPAM handles over time, which are not being cleaned up.
- Manual deletion of these stale resources temporarily resolves the issue but is not a sustainable long-term solution.

### Calico-kube-controllers log:
The log file is flooded with these entries - 
```
ipam.go 1131: Calico Node referenced in IPAM data does not exist error=resource does not exist: 
ipam.go 1032: Garbage collecting leaked IP address handle=
```
