### ISSUE TITLE
calico-node pod not ready with k8s 1.30 and calico 3.28.2 in dual-stack deployment

### ISSUE THREAD

**Issue by geotransformer** [projectcalico/calico#9373]
## Expected Behavior

calico-node pod will be running and ready
## Current Behavior

calico-node pod will be running, but not ready
## Possible Solution

1. kubectl edit felixconfigurations.crd.projectcalico.org default -n kube-system
```
xxxx@xxxx-cp:~$ kubectl get pods -A | grep cali
kube-system       calico-kube-controllers-65dcc554ff-bwmdv                     1/1     Running            0               17m
kube-system       calico-node-s99x7                                            0/1     Running            0               17m

$ kubectl get nodes xxxx -o go-template --template='{{range .status.addresses}}{{printf "%s: %s\n" .type .address}}{{end}}'

InternalIP: 10.192.1.14
InternalIP: fd32:e985:ce1:fff2::14
Hostname: xxxx@xxxx-cp

```
3. Update the logSeverityScreen from Info to Debug
4. the felix process might be restart 
5. calico-node logs
```
2024-10-21 17:48:11.211 [INFO][8176] felix/int_dataplane.go 1916: Received *proto.ServiceUpdate update from calculation graph msg=name:"istiod" namespace:"istio-system" type:"ClusterIP" cluster_ips:"xx.xx.xx.xx" ports:<Protocol:"TCP" Port:15010 > ports:<Protocol:"TCP" Port:15012 > ports:<Protocol:"TCP" Port:443 > ports:<Protocol:"TCP" Port:15014 > 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1b2888e]

goroutine 113 [running]:
github.com/projectcalico/calico/felix/calc.(*EventSequencer).flushHostIPv6Updates(0xc00025e588)
        /go/src/github.com/projectcalico/calico/felix/calc/event_sequencer.go:571 +0x10e
github.com/projectcalico/calico/felix/calc.(*EventSequencer).Flush(0xc00025e588)
        /go/src/github.com/projectcalico/calico/felix/calc/event_sequencer.go:835 +0x288
github.com/projectcalico/calico/felix/calc.(*AsyncCalcGraph).maybeFlush(0xc000942930)
        /go/src/github.com/projectcalico/calico/felix/calc/async_calc_graph.go:215 +0xbd
github.com/projectcalico/calico/felix/calc.(*AsyncCalcGraph).loop(0xc000942930)
        /go/src/github.com/projectcalico/calico/felix/calc/async_calc_graph.go:192 +0xf4
created by github.com/projectcalico/calico/felix/calc.(*AsyncCalcGraph).Start in goroutine 1
        /go/src/github.com/projectcalico/calico/felix/calc/async_calc_graph.go:259 +0x105 

```
## Steps to Reproduce (for bugs)

/etc/netplan/*
==== Netplan-1
```
network:
    bonds:
        bd0:
            dhcp4: false
            dhcp6: false
            interfaces:
            - eno5
            - eno6
            parameters:
                fail-over-mac-policy: active
                mii-monitor-interval: '100'
                mode: active-backup
    ethernets:
        eno1:
            addresses:
            - xxx.xx.xx.xx/8
            dhcp4: false
            dhcp6: false
        eno5:
            dhcp4: false
            dhcp6: false
        eno6:
            dhcp4: false
            dhcp6: false
    version: 2
    vlans:
        vlan01:
            addresses:
            - xxx.xx.xx.xx/24
            - xxx:xxx:ce1:xxxx::14/64
            dhcp4: false
            dhcp6: false
            id: 01
            link: bd0

==== Netplan-2
network:
  version: 2
  vlans:
    vlan03:
      addresses: [xxx.xx.xx.xx/26, 'xxx:420:xx:xx::xxx/64']
      dhcp4: false
      dhcp6: false
      gateway4: xxx.xx.xx.xx
      gateway6: xxx.xxx.xx..
      id: 03
      link: bd0
      nameservers:
        addresses: [xxx.xx.xx.xx]
```
======calico.yaml

## Context

Kubernetes 1.30 with Calcio 3.28.3, in dual-stack deployment

## Your Environment

* Calico version 3.28.3
* Calico dataplane (iptables, windows etc.) iptables
* Orchestrator version (e.g. kubernetes, mesos, rkt):kubernetes
* Operating System and version:Uuntu20
* Link to your project (optional):
