### ISSUE TITLE
New calico-typha pods fail to run due to missing resource, adminnetworkpolicies.policy.networking.k8s.io

### ISSUE THREAD

**Issue by morganwalker** [projectcalico/calico#9395]
We've deployed v3.28.2 of the tigera-operator via Helm into our EKS cluster while using our existing AWS VPC CNI. Most of the components are running fine, e.g. csi-node-driver, calico-node, calico-kube-controller, calico-apiserver, and the tigera-operator itself. However, the calico-typha deployment is in a state of flux.

## Expected Behavior
Once the tigera-operator is deployed the calico-typha deployment should have all pods running.

## Current Behavior
An old calico-typha replicaset has 1/1 containers running. The new calico-typha replicaset has 0/1 containers running and are complaining about:

```
2024-10-25 12:21:09.802 [INFO][1] typha/watchercache.go 181: Full resync is required ListRoot="/calico/resources/v3/projectcalico.org/kubernetesadminnetworkpolicies"
2024-10-25 12:21:09.803 [INFO][1] typha/watchercache.go 194: Failed to perform list of current data during resync ListRoot="/calico/resources/v3/projectcalico.org/kubernetesadminnetworkpolicies" error=resource does not exist: KubernetesAdminNetworkPolicy with error: the server could not find the requested resource (get adminnetworkpolicies.policy.networking.k8s.io)
```

Why wouldn't this prevent the older replicaset from starting?

## Possible Solution
I don't know enough about why this is happening to suggest a solution.

## Steps to Reproduce (for bugs)
1. deploy the tigera-operator via Helm

## Context
We're trying to deploy the tigera-operator for the first time to manage network policies within our EKS clusters and it isn't fully functional.

## Your Environment
* Calico version: 3.28.2
* AWS VPC CNI version: 1.18.3
* Calico dataplane: iptables
* Orchestrator version: EKS 1.29
* Operating System and version: AL2023

**Comment by fasaxc** [comment]
Admin network policie are a feature in Calico v3.29, which is not yet released.  It looks like you've somehow got a helm chart that is using unreleased nightly builds.  Can you share the exact steps you used to install?  What chart version are you using?

**Comment by fasaxc** [comment]
It's also help to know what image versions it's trying to install.  What is the image version of calico-typha pod?

**Comment by morganwalker** [comment]
And our values files:

```
tigera-operator:
  installation:
    enabled: false

  # Resource requests and limits for the tigera/operator pod.
  resources:
    requests:
      cpu: 3000m
      memory: 1Gi
    limits:
      memory: 1Gi

  # Common labels for all resources created by this chart
  additionalLabels: &labels
    alk-application: tigera-operator
    alk-role: third-party
    alk-team: cntnr

  # PriorityClassName for the tigera/operator pod.
  priorityClassName: "system-node-critical"

  # Custom annotations for the tigera/operator pod.
  podAnnotations: {}

  # Custom labels for the tigera/operator pod.
  podLabels: *labels

  # Image and registry configuration for the tigera/operator pod.
  tigeraOperator:
    image: tigera/operator
    version: master
    registry: quay.io
  calicoctl:
    image: docker.io/calico/ctl
    tag: master
```

We pass in the Installation as a template.

**Comment by morganwalker** [comment]
Removing:

```
  tigeraOperator:
    image: tigera/operator
    version: master
    registry: quay.io
  calicoctl:
    image: docker.io/calico/ctl
    tag: master
```
from our `values.yaml` resulted in `image: quay.io/tigera/operator:v1.34.5` being assigned to the operator. So maybe that's part of the problem?
