### ISSUE TITLE
Helm upgrade from 28.2 to 29.0 fails

### ISSUE THREAD

**Issue by Ergamon** [projectcalico/calico#9432]
I tested the upgrade now in multiple of our clusters and the result is always the same so I have to rollback.

## Expected Behavior
Everything keeps up and running just with the latest version

## Current Behavior
I upgrade via helm:
```
helm upgrade calico calico/tigera-operator -n tigera-operator
```
and the ApiServer pods reach the CrashLoopBackOff status.

From the logs I can see:
```
I1102 12:23:19.358857       1 plugins.go:157] Loaded 2 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,MutatingAdmissionWebhook.
I1102 12:23:19.358912       1 plugins.go:160] Loaded 2 validating admission controller(s) successfully in the following order: ValidatingAdmissionPolicy,ValidatingAdmissionWebhook.
E1102 12:23:19.365472       1 resource.go:106] Failed initializing client: "resource does not exist: Tier(default) with error: the server could not find the requested resource (post Tiers.crd.projectcalico.org)"
```

## Possible Solution
I can only guess. From the logs I expect that the Api servers are responsible for creating the CRDs, but as some CRDs are already there from the previous version, it fails to add the new ones.
(The old and working 28.2 installation has no Tiers objects)

## Steps to Reproduce (for bugs)
1. Install Calico 28.2 via helm
2. Upgrade to 28.0 via helm

## Your Environment
* Calico version 28.2
* Calico dataplane (iptables, windows etc.) All nodes Ubuntu 24.04
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes 1.31.2
* Operating System and version: Ubuntu 24.04

**Comment by ocp1006** [comment]
@Ergamon I think you have a typo. You probably meant "Upgrade to 29.0 via helm".
I found that applying
```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tiers.crd.projectcalico.org
spec:
  group: crd.projectcalico.org
  names:
    kind: Tier
    listKind: TierList
    plural: tiers
    singular: tier
  scope: Cluster
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              order:
                type: integer
            required:
            - order
            type: object
        type: object
    served: true
    storage: true
```
Solved my issue, but I wonder if it's suppose to be supplied as part of calico's `apiserver.yaml`
