### ISSUE TITLE
Documentation for IPAMConfiguration MaxBlocksPerHost has incorrect default value

### ISSUE THREAD

**Issue by asskss** [projectcalico/calico#9462]
calico version： 3.26.5
k8s version: 1.26.15
calico bgp

pod event
```
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "a95d922a5537871eb16854787a94b255226721d28f22017ed3ffd9cb74b82181": plugin type="calico" failed (add): cannot allocate new block due to per host block limit
```

calicoctl get ippool
default:
```
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: default-ipv4-ippool
spec:
  allowedUses:
  - Workload
  - Tunnel
  blockSize: 26
  cidr: 10.135.64.0/19
  ipipMode: Never
  nodeSelector: calico/ippool ==  'default'
```
test:
```
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: mce-ipv4-ippool
spec:
  allowedUses:
  - Workload
  - Tunnel
  blockSize: 32
  cidr: 100.68.80.0/20
  ipipMode: Never
  nodeSelector: calico/ippool == 'test'
  vxlanMode: Never
```

![image](https://github.com/user-attachments/assets/c85602f8-bf8f-4239-b984-e55fca4d9ab2)

When the blocksize is configured as/32, there are only 2 nodes. Testing found that one node seems to carry a maximum of 25 IPAM block segments. How to increase the node's carrying capacity limit？

**Comment by asskss** [comment]
![image](https://github.com/user-attachments/assets/ee8d104f-2c49-441d-b3af-91d0b1e2b92a)
The default parameter does not work, you need to configure it yourself.
![image](https://github.com/user-attachments/assets/7a501ccf-5652-45bb-a6fb-1031cf01c5ab)
IPAMConfiguration needs to be configured in this way
```
apiVersion: projectcalico.org/v3
kind: IPAMConfiguration
metadata:
  name: default
spec:
  maxBlocksPerHost: 100
  strictAffinity: false
```
