### ISSUE TITLE
If "KUBERNETES_SERVICE_HOST" is domain, initial installation is not possible. (tigera-operator for windows)

### ISSUE THREAD

**Issue by moonek** [projectcalico/calico#9536]
In an environment where tigera-operator is being installed for the first time considering the use of Windows, if `KUBERNETES_SERVICE_HOST` is a domain, the operator does not work properly.

```
kubectl apply -f - << EOF
kind: ConfigMap
apiVersion: v1
metadata:
  name: kubernetes-services-endpoint
  namespace: tigera-operator
data:
  KUBERNETES_SERVICE_HOST: myk8s.api-endpoint.com # example
  KUBERNETES_SERVICE_PORT: 6443
EOF
```
In the initial k8s environment, `coredns` is not run before tigera-operator installs calico-cni.
Because the `dnsPolicy` of tigera-operator deployment is set to `ClusterFirstWithHostNet`, the above domain cannot be lookup.
https://github.com/projectcalico/calico/blob/240c89fe44512db49957eea27c3bbf2d18f33785/manifests/tigera-operator.yaml#L24758-L24760

Therefore, an error occurs in tigera-operator and calico-cni is not installed.

## Expected Behavior

If `KUBERNETES_SERVICE_HOST` is a domain, an initial install must also be done.

## Current Behavior

A domain lookup failure error continues to occur in the tigera-operator pod.

## Possible Solution

If change tigera-operator's `dnsPolicy` to `Default`, it will not lookup coredns first, but will normally lookup the apiserver address from the dns nameserver set in the host.
After making this change, calico-cni was installed normally, but I am not sure if this is the correct method.
Please give me clear instructions on what to do.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version
* Calico dataplane (iptables, windows etc.)
* Tigera Operator: v1.34.5
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes v1.30.6
* Operating System and version:
* Link to your project (optional):
