### ISSUE TITLE
nftables dataplane does not work on Ubuntu 24.04 ARM

### ISSUE THREAD

**Issue by L2jLiga** [projectcalico/calico#9613]
Hello, switching dataplane from Iptables to Nftables breaks calico-node on my arm64 nodes - Orange Pi 5 and Raspberry Pi 4.
Both of them running Ubuntu 24.04, [official ubuntu image for Raspberry Pi](https://ubuntu.com/download/raspberry-pi) and [Joshua Ubuntu 24.04 image on Orange Pi](https://github.com/Joshua-Riek/ubuntu-rockchip/releases/tag/v2.4.0).

## Expected Behavior

Nftables dataplane works on all types of nodes

## Current Behavior

arm64 nodes not working
amd64 nodes are working

## Possible Solution
idk

## Steps to Reproduce (for bugs)

1. Install Ubuntu 24.04
2. Add as node to cluster
3. Install calico with Tigera
4. Switch dataplane to nftables

## Context

<details>
<summary>installation.yaml</summary>

```yaml
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  labels:
    app.kubernetes.io/instance: tigera-operator
  name: default
spec:
  calicoNetwork:
    bgp: Enabled
    hostPorts: Enabled
    ipPools:
      - allowedUses:
          - Workload
          - Tunnel
        blockSize: 24
        cidr: 10.244.0.0/16
        disableBGPExport: false
        disableNewAllocations: false
        encapsulation: IPIPCrossSubnet
        name: default-ipv4-ippool
        natOutgoing: Enabled
        nodeSelector: all()
      - allowedUses:
          - Workload
          - Tunnel
        blockSize: 120
        cidr: fd02:22:22::/64
        disableBGPExport: false
        disableNewAllocations: false
        encapsulation: None
        name: default-ipv6-ippool
        natOutgoing: Enabled
        nodeSelector: all()
    linuxDataplane: Nftables
    linuxPolicySetupTimeoutSeconds: 0
    mtu: 1500
    multiInterfaceMode: None
    nodeAddressAutodetectionV4:
      kubernetes: NodeInternalIP
    nodeAddressAutodetectionV6:
      kubernetes: NodeInternalIP
    windowsDataplane: Disabled
  cni:
    ipam:
      type: Calico
    type: Calico
  componentResources:
    - componentName: Node
      resourceRequirements:
        requests:
          cpu: 250m
  controlPlaneReplicas: 2
  flexVolumePath: None
  imagePullSecrets: []
  kubeletVolumePluginPath: /var/lib/kubelet
  kubernetesProvider: ''
  logging:
    cni:
      logFileMaxAgeDays: 30
      logFileMaxCount: 10
      logFileMaxSize: 100Mi
      logSeverity: Info
  nodeUpdateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  nonPrivileged: Disabled
  variant: Calico
```
</details>

<details>
<summary>Logs</summary>

```
2024-12-18 11:33:41.016 [PANIC][290715] felix/table.go 335: Failed to create knftables client error=could not run nftables command: /usr/sbin/nft: /lib64/libnftnl.so.11: version `LIBNFTNL_RHEL_14' not found (required by /lib64/libnftables.so.1)

panic: (*logrus.Entry) 0x40006633b0

goroutine 1 [running]:
github.com/sirupsen/logrus.(*Entry).log(0x4000663340, 0x0, {0x40000744e0, 0x21})
        /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:260 +0x488
github.com/sirupsen/logrus.(*Entry).Log(0x4000663340, 0x0, {0x4000d1c2a8?, 0x2e499a0?, 0x40006063a0?})
        /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:304 +0x60
github.com/sirupsen/logrus.(*Entry).Panic(...)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:342
github.com/projectcalico/calico/felix/nftables.NewTable({0x3307a47, 0x6}, 0x4, {0x3305f28, 0x5}, {0x38d6640, 0x4000362320}, {0x349a658, 0x29e8d60800, 0x0, ...})
        /go/src/github.com/projectcalico/calico/felix/nftables/table.go:335 +0x47c
github.com/projectcalico/calico/felix/dataplane/linux.NewIntDataplaneDriver({{0x4000078134, 0x3}, {0x0, 0x0}, 0x1, {0x0, 0x0}, 0x5dc, 0x5dc, 0x5dc, ...})
        /go/src/github.com/projectcalico/calico/felix/dataplane/linux/int_dataplane.go:510 +0xc74
github.com/projectcalico/calico/felix/dataplane.StartDataplaneDriver(0x4000b17b08, 0x40003bfad0, 0x4000479780, 0x40004797a0, 0x40001bbba0)
        /go/src/github.com/projectcalico/calico/felix/dataplane/driver.go:400 +0x1f70
github.com/projectcalico/calico/felix/daemon.Run({0x33403b8, 0x15}, {0x3891888, 0x7}, {0x38a09e0, 0x18}, {0x38cfb40, 0x28})
        /go/src/github.com/projectcalico/calico/felix/daemon/daemon.go:417 +0x1bec
main.main()
        /go/src/github.com/projectcalico/calico/node/cmd/calico-node/main.go:127 +0x778
```
</details>

## Your Environment

* Calico version: 3.29.1
* Calico dataplane (iptables, windows etc.): nftables (trying to switch)
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes (kubeadm)
* Operating System and version: Ubuntu 24.04
* Link to your project (optional): -

**Comment by caseydavenport** [comment]
@L2jLiga thanks for raising. Unfortunately we're going to need some more information. What exactly is not working? What are the symptoms you're seeing? What steps did you take to switch Calico from iptables -> nftables?

Right now, we don't have a documented procedure for this - nftables mode is in tech-preview and one of the limitations is that we don't have a migration procedure for live clusters. It's probably possible, but not thoroughly tested, and needs manual intervention to clean up old iptables rules on the node.

**Comment by L2jLiga** [comment]
Hi @caseydavenport,

I have home-lab cluster with mixed nodes - arm64 and amd64.
All nodes are running Kubernetes 1.32.0 on Ubuntu 24.04.
I also have working tigera operator installation:

<details>
<summary>installation.yaml</summary>

```yaml
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  calicoNetwork:
    bgp: Enabled
    hostPorts: Enabled
    ipPools:
    - allowedUses:
      - Workload
      - Tunnel
      blockSize: 24
      cidr: 10.244.0.0/16
      disableBGPExport: false
      disableNewAllocations: false
      encapsulation: IPIPCrossSubnet
      name: default-ipv4-ippool
      natOutgoing: Enabled
      nodeSelector: all()
    - allowedUses:
      - Workload
      - Tunnel
      blockSize: 120
      cidr: fd02:22:22::/64
      disableBGPExport: false
      disableNewAllocations: false
      encapsulation: None
      name: default-ipv6-ippool
      natOutgoing: Enabled
      nodeSelector: all()
    linuxDataplane: Iptables
    linuxPolicySetupTimeoutSeconds: 0
    mtu: 1500
    multiInterfaceMode: None
    nodeAddressAutodetectionV4:
      kubernetes: NodeInternalIP
    nodeAddressAutodetectionV6:
      kubernetes: NodeInternalIP
    windowsDataplane: Disabled
  cni:
    ipam:
      type: Calico
    type: Calico
  componentResources:
  - componentName: Node
    resourceRequirements:
      requests:
        cpu: 250m
  controlPlaneReplicas: 2
  flexVolumePath: None
  imagePullSecrets: []
  kubeletVolumePluginPath: /var/lib/kubelet
  kubernetesProvider: ""
  logging:
    cni:
      logFileMaxAgeDays: 30
      logFileMaxCount: 10
      logFileMaxSize: 100Mi
      logSeverity: Info
  nodeUpdateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  nonPrivileged: Disabled
  variant: Calico
```
</details>

When I'm try to switch `linuxDataplane` from `Iptables` to `Nftables`:

<details>
<summary>installation.yaml</summary>

```diff
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  calicoNetwork:
    bgp: Enabled
    hostPorts: Enabled
    ipPools:
    - allowedUses:
      - Workload
      - Tunnel
      blockSize: 24
      cidr: 10.244.0.0/16
      disableBGPExport: false
      disableNewAllocations: false
      encapsulation: IPIPCrossSubnet
      name: default-ipv4-ippool
      natOutgoing: Enabled
      nodeSelector: all()
    - allowedUses:
      - Workload
      - Tunnel
      blockSize: 120
      cidr: fd02:22:22::/64
      disableBGPExport: false
      disableNewAllocations: false
      encapsulation: None
      name: default-ipv6-ippool
      natOutgoing: Enabled
      nodeSelector: all()
-    linuxDataplane: Iptables
+    linuxDataplane: Nftables
-    linuxPolicySetupTimeoutSeconds: 0
    mtu: 1500
    multiInterfaceMode: None
    nodeAddressAutodetectionV4:
      kubernetes: NodeInternalIP
    nodeAddressAutodetectionV6:
      kubernetes: NodeInternalIP
    windowsDataplane: Disabled
  cni:
    ipam:
      type: Calico
    type: Calico
  componentResources:
  - componentName: Node
    resourceRequirements:
      requests:
        cpu: 250m
  controlPlaneReplicas: 2
  flexVolumePath: None
  imagePullSecrets: []
  kubeletVolumePluginPath: /var/lib/kubelet
  kubernetesProvider: ""
  logging:
    cni:
      logFileMaxAgeDays: 30
      logFileMaxCount: 10
      logFileMaxSize: 100Mi
      logSeverity: Info
  nodeUpdateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  nonPrivileged: Disabled
  variant: Calico
```
</details>

Then after some time (to apply config) I see that nodes on arm64 devices not working, logs are:

<details>
<summary>kubectl logs -n calico-system calico-node-gvqxt</summary>

```
2024-12-30 18:39:11.663 [PANIC][411952] felix/table.go 335: Failed to create knftables client error=could not run nftables command: /usr/sbin/nft: /lib64/libnftnl.so.11: version `LIBNFTNL_RHEL_14' not found (required by /lib64/libnftables.so.1)

panic: (*logrus.Entry) 0x4000193b20

goroutine 1 [running]:
github.com/sirupsen/logrus.(*Entry).log(0x4000193a40, 0x0, {0x40005b37a0, 0x21})
        /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:260 +0x488
github.com/sirupsen/logrus.(*Entry).Log(0x4000193a40, 0x0, {0x4000ada2a8?, 0x2e499a0?, 0x40000706c0?})
        /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:304 +0x60
github.com/sirupsen/logrus.(*Entry).Panic(...)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:342
github.com/projectcalico/calico/felix/nftables.NewTable({0x3307a47, 0x6}, 0x4, {0x3305f28, 0x5}, {0x38d6640, 0x400013b9f0}, {0x349a658, 0x29e8d60800, 0x0, ...})
        /go/src/github.com/projectcalico/calico/felix/nftables/table.go:335 +0x47c
github.com/projectcalico/calico/felix/dataplane/linux.NewIntDataplaneDriver({{0x4000078134, 0x3}, {0x0, 0x0}, 0x1, {0x0, 0x0}, 0x5dc, 0x5dc, 0x5dc, ...})
        /go/src/github.com/projectcalico/calico/felix/dataplane/linux/int_dataplane.go:510 +0xc74
github.com/projectcalico/calico/felix/dataplane.StartDataplaneDriver(0x40003dc008, 0x4000868f30, 0x4000238c90, 0x4000238ca0, 0x4000122340)
        /go/src/github.com/projectcalico/calico/felix/dataplane/driver.go:400 +0x1f70
github.com/projectcalico/calico/felix/daemon.Run({0x33403b8, 0x15}, {0x3891888, 0x7}, {0x38a09e0, 0x18}, {0x38cfb40, 0x28})
        /go/src/github.com/projectcalico/calico/felix/daemon/daemon.go:417 +0x1bec
main.main()
        /go/src/github.com/projectcalico/calico/node/cmd/calico-node/main.go:127 +0x778
```
</details>


same time on amd64 nodes dataplane switched correctly
