### ISSUE TITLE
Calico wireguard doesn't allow pod to pod-on-host traffic

### ISSUE THREAD

**Issue by igcherkaev** [projectcalico/calico#9751]
## Expected Behavior

Traffic initiated by regular pods to in-cluster services backed by pods using host network (e.g. kube-apiserver) is allowed and flowing.

## Current Behavior

Traffic initiated by regular pods to in-cluster services backed by pods using host network (e.g. kube-apiserver) is dropped by wireguard allowed IPs policies set by calico for each peer on wireguard.cali interface.

## Possible Solution

Possible solution is to allow users adjust the allowed-ips for peers on the wireguard interface.
```
  wireguardEnabled: true
  wireguardAllowedIPs: '10.142.53.31/32,10.142.53.32/32'
```
An optional field for FelixConfiguration (or maybe IPPool?), which would be concatenated with the list of computed CIDR blocks that calico configures peers with on the wireguard interface.

## Steps to Reproduce (for bugs)

Note: __Reza-Tigera__ (in Slack) was able to reproduce this issue.

1. Enable wireguard debug on kubernetes nodes. (`echo module wireguard +p > /sys/kernel/debug/dynamic_debug/control`)
2. Run kube-apiserver pods or any other pods using host network.
3. Run regular pods and try to contact the host-network pods.
4. On the node with the regular pod you'll notice errors in dmesg similar to:
```
[13590.173457] wireguard: wireguard.cali: Packet has unallowed src IP (10.142.53.61) from peer 12 (10.142.53.61:51820)
[13590.182499] wireguard: wireguard.cali: Packet has unallowed src IP (10.142.53.32) from peer 15 (10.142.53.32:51820)
[13590.230851] wireguard: wireguard.cali: Packet has unallowed src IP (10.142.53.35) from peer 13 (10.142.53.35:51820)
```

## Context

Once wireguard is enabled, no pods can talk to in-cluster kubernetes api service.

## Your Environment

* Calico version: 3.29.1
* Calico dataplane (iptables, windows etc.): ebpf, linux
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes 1.29.12
* Operating System and version: Flatcar Container Linux by Kinvolk 4081.2.1 (Oklo)   6.6.65-flatcar   containerd://1.7.21

Felix Configuration:
```
apiVersion: projectcalico.org/v3
kind: FelixConfiguration
metadata:
  name: default
spec:
  bpfEnabled: true
  bpfExternalServiceMode: DSR
  bpfKubeProxyIptablesCleanupEnabled: true
  bpfLogLevel: ""
  logSeverityScreen: Info
  reportingInterval: 0s
  ipipEnabled: false
  vxlanEnabled: false
  wireguardEnabled: true
  bpfEnforceRPF: Disabled
```
IPPools configuration:
```
kind: IPPoolList
apiVersion: projectcalico.org/v3
items:
- apiVersion: projectcalico.org/v3
  kind: IPPool
  metadata:
    name: 10-161-128-0-17
  spec:
    allowedUses:
    - Workload
    - Tunnel
    blockSize: 26
    cidr: 10.161.128.0/17
    ipipMode: Never
    nodeSelector: all()
    natOutgoing: false

```

BGP is in use, DSR is on, vxlan is likely a no-go option.
