### ISSUE TITLE
RKE2 blocks Calico operator from renewing certificates

### ISSUE THREAD

**Issue by FredNass** [projectcalico/calico#9807]
Hi,

I've been facing a situation similar to this one here #9228 with calico-node pods unable to start on RKE2 K8s 1.28 nodes due to an expired certificate.

`2025-02-07 11:42:05.673 [WARNING][32807] tunnel-ip-allocator/sync_client.go 158: error connecting to typha endpoint (3 of 3) 100.74.155.140:5473 connID=0x0 error=x509: certificate has expired or is not yet valid: current time 2025-02-07T11:42:05Z is after 2024-12-22T14:22:15Z type="tunnel-ip-allocation"
`

2024-12-22T14:22:15Z is the end date of the certificate present in Secret named 'typha-certs' in 'tigera-operator' namespace.

Deleting the Secret and rolling out/restarting the calico components didn't help, nor did restarting rke2-{server,agent}.

I got around this by:

- stopping chronyd on all nodes
- setting the nodes to a date before the certificate expiration (date -s '2024-12-20 12:00:00')
- restarting rke2-{server,agent}
- waiting 5-10 minutes
- restarting chronyd to force the date/time update
- restarting rke2-{server,agent}

But... the tls.crt in 'typha-certs' secret (namespace 'calico-system') was not renewed and still shows a date in the past.

I wasn't able to get this certificate to regenerate by deleting the 'typha-certs' secret and restarting the calico and tigera-operator components.

Can someone please explain how one can force the renewal of this certificate?

**Comment by caseydavenport** [comment]
My understanding is that this certificate should be automatically updated as the expiry approaches, so if that isn't happening it sounds like a bug or misconfiguration. 

That said, I would have expected simply deleting the `typha-certs` Secret in the `tigera-operator` Namespace would trigger regeneration of the secret (the tigera-operator Namespace is the source-of-truth for this secret, the calico-system one is a reflection of that)

**Comment by FredNass** [comment]
Hey Casey, thanks a lot for your help.

After thorough investigation, we discovered that the tigera-operator was not allowed to renew the cert by rancher-webhook v0.6.1 deployed by Rancher v2.10 in downstream clusters. Workaround for now is to either create CR and CRB for tigera-operator OR edit webhooks filter rules  as described [here](https://github.com/rancher/rancher/issues/41191).

Once both CR and CRB were created in the cluster, the tigera-operator successfully renewed typha-certs.

**Comment by caseydavenport** [comment]
Interesting. Thanks for reporting back! I'll take a look and see if there's anything we can do on our side for that.

**Comment by caseydavenport** [comment]
Actually, going to leave this open. I think we should probably look into shipping the RBAC ourselves, given the lack of movement on the other issue.

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tigera-operator-psa
rules:
- apiGroups:
  - management.cattle.io
  resources:
  - projects
  verbs:
  - updatepsa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tigera-operator-psa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tigera-operator-psa
subjects:
- kind: ServiceAccount
  name: tigera-operator
  namespace: tigera-operator
```

This is what was suggested in that linked issue, for future reference.
