### ISSUE TITLE
Pods cant reach eachother or the kubernetes service ip

### ISSUE THREAD

**Issue by maxomizer** [projectcalico/calico#9854]
## Expected Behavior

Deployed pods can communicate with each other and are able to ping the kubernetes service IP.
## Current Behavior

I installed kubernetes and used calico operator installation.

For kubeadm i used:

`sudo kubeadm init --control-plane-endpoint=10.0.253.125:6443 --pod-network-cidr=192.168.0.0/16 --upload-certs`

for tigera operator:

`kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.29.2/manifests/tigera-operator.yaml`

```
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  # Configures Calico networking.
  calicoNetwork:
    ipPools:
    - name: default-ipv4-ippool
      blockSize: 26
      cidr: 192.168.0.0/16
      encapsulation: None
      natOutgoing: Enabled
      nodeSelector: all()

---

# This section configures the Calico API server.
# For more information, see: https://docs.tigera.io/calico/latest/reference/installation/api#operator.tigera.io/v1.APIServer
apiVersion: operator.tigera.io/v1
kind: APIServer
metadata:
  name: default
spec: {}
```

Then everything was up and running, i joined all the other control-plane and worker nodes.

After that i deployed the pods and tried to ping each other or get a connection to kubernetes-service, but nothing worked. I don't know where my mistake or misconfiguration is.

## Possible Solution

Maybe I need another ippool or something is misconfigured ?

I didn't add any networkpolicy, just the default one created by the operator is active:
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: "2025-02-14T19:55:14Z"
  generation: 6
  name: allow-apiserver
  namespace: calico-apiserver
  ownerReferences:
  - apiVersion: operator.tigera.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: APIServer
    name: default
    uid: a03c6fbe-9296-4b72-89b7-893827eecb72
  resourceVersion: "10711856"
  uid: 00b6f917-e2b7-4b9c-9e18-0c1d6368524b
spec:
  ingress:
  - ports:
    - port: 443
      protocol: TCP
  podSelector:
    matchLabels:
      apiserver: "true"
  policyTypes:
  - Ingress
```

## Steps to Reproduce (for bugs)

```
kubectl get svc -o wide
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE   SELECTOR
kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   17h   <none>
$ kubectl get pods -o wide -n test-ns-1
NAME         READY   STATUS    RESTARTS      AGE   IP                NODE    NOMINATED NODE   READINESS GATES
test-pod-1   1/1     Running   1 (21m ago)   82m   192.168.143.193   k8sn2   <none>           <none>
$ kubectl get pods -o wide -n test-ns-2
NAME         READY   STATUS    RESTARTS      AGE   IP                NODE    NOMINATED NODE   READINESS GATES
test-pod-2   1/1     Running   1 (22m ago)   82m   192.168.143.194   k8sn2   <none>           <none>
$ kubectl exec -n test-ns-1 -it test-pod-1 -- sh
/ # ping 192.168.143.194
PING 192.168.143.194 (192.168.143.194): 56 data bytes
^C
--- 192.168.143.194 ping statistics ---
10 packets transmitted, 0 packets received, 100% packet loss
/ # ping 10.96.0.1
PING 10.96.0.1 (10.96.0.1): 56 data bytes
^C
--- 10.96.0.1 ping statistics ---
7 packets transmitted, 0 packets received, 100% packet loss

kubectl exec -n test-ns-1 -it test-pod-1 -- sh
/ # traceroute 10.96.0.1
traceroute to 10.96.0.1 (10.96.0.1), 30 hops max, 46 byte packets
 1  MyWorker2NodeIP (MyWorker2NodeIP)  0.006 ms  0.023 ms  0.003 ms
 2  MyWorker2NodeIP (MyWorker2NodeIP)  0.003 ms  0.012 ms  0.006 ms
/ # traceroute 192.168.143.194
traceroute to 192.168.143.194 (192.168.143.194), 30 hops max, 46 byte packets
 1  MyWorker2NodeIP (MyWorker2NodeIP)  0.006 ms  0.023 ms  0.003 ms
 2  MyWorker2NodeIP (MyWorker2NodeIP)  0.003 ms  0.012 ms  0.006 ms
/ #

```

Kubeapiserver logs say:
W0215 13:10:27.052594       1 handler_proxy.go:99] no RequestInfo found in the context
E0215 13:10:27.052640       1 controller.go:146] "Unhandled Error" err=<
        Error updating APIService "v3.projectcalico.org" with err: failed to download v3.projectcalico.org: failed to retrieve openAPI spec, http error: ResponseCode: 503, Body: service unavailable
        , Header: map[Content-Type:[text/plain; charset=utf-8] X-Content-Type-Options:[nosniff]]

## Context

I want to build a functional cluster with calico, where i can demonstrate network policies, rbac, ingress, kubernetes gateway api,services and co 

## Your Environment

* Calico version
* v.3.29.2
* Calico dataplane (iptables, windows etc.)
* iptables
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* v1.31.3
* Operating System and version:
* debian 12, hardened
* Link to your project (optional):
