### ISSUE TITLE
NetworkPolicy behavior is different for NodePort services depending on whether pods are on same or different nodes

### ISSUE THREAD

**Issue by jennydaman** [projectcalico/calico#9869]
## Steps to Reproduce (for bugs)

I first noticed this bug on my production cluster installed using Kubespray, though I was able to reproduce it minimally using KinD. First, follow the official documentation to install Kubernetes and Calico using KinD: https://docs.tigera.io/calico/latest/getting-started/kubernetes/kind

We have a cluster with two worker nodes in the subnet `172.18.0.0/24`.

```
$ kubectl get nodes -o wide
NAME                STATUS   ROLES           AGE     VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                         KERNEL-VERSION   CONTAINER-RUNTIME
dev-control-plane   Ready    control-plane   5h48m   v1.32.0   172.18.0.3    <none>        Debian GNU/Linux 12 (bookworm)   6.13.2-arch1-1   containerd://1.7.24
dev-worker          Ready    <none>          5h48m   v1.32.0   172.18.0.2    <none>        Debian GNU/Linux 12 (bookworm)   6.13.2-arch1-1   containerd://1.7.24
dev-worker2         Ready    <none>          5h48m   v1.32.0   172.18.0.4    <none>        Debian GNU/Linux 12 (bookworm)   6.13.2-arch1-1   containerd://1.7.24
```

To set up the experiment, we create:

- a "hello world" HTTP server
- a NodePort service
- two "client" pods with `curl` installed, one on each worker node
- a NetworkPolicy which allows ingress from `curl` pods to the NodePort service

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  labels:
    app: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: ghcr.io/knative/helloworld-go:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello
spec:
  selector:
    app: hello
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allowlist
spec:
  policyTypes:
  - Egress
  podSelector:
    matchLabels:
      app: curl
  egress:
  - to:
    - ipBlock:
        cidr: 172.18.0.0/24
---
apiVersion: v1
kind: Pod
metadata:
  name: curl-1
  labels:
    app: curl
spec:
  containers:
  - name: curl
    image: quay.io/curl/curl:latest
    command: [ 'sleep', '99999999' ]
  terminationGracePeriodSeconds: 1
  nodeSelector:
    kubernetes.io/hostname: dev-worker
---
apiVersion: v1
kind: Pod
metadata:
  name: curl-2
  labels:
    app: curl
spec:
  containers:
  - name: curl
    image: quay.io/curl/curl:latest
    command: [ 'sleep', '99999999' ]
  terminationGracePeriodSeconds: 1
  nodeSelector:
    kubernetes.io/hostname: dev-worker2
```

## Expected Behavior

NetworkPolicy behavior should not be affected by whether the client and server pods are on the same node or different nodes.

I also tried the experiment using cilium instead of calico. Using cilium, the `ipBlock`-based NetworkPolicy works as expected.

## Current Behavior

With the `ipBlock` NetworkPolicy in effect, networking only works when the client pod is on a different node from the server pod.

```shell
# dev-worker2 -> dev-worker
kubectl exec curl-2 -- curl -i http://172.18.0.2:30080
# dev-worker -> dev-worker2
kubectl exec curl-1 -- curl -i http://172.18.0.4:30080
```

However, networking does not work (timeout error) when the client pod is on the same node as the server pod.

```shell
# dev-worker2 -> dev-worker2
kubectl exec curl-2 -- curl -i http://172.18.0.4:30080
# dev-worker -> dev-worker
kubectl exec curl-1 -- curl -i http://172.18.0.2:30080
```

A different behavior is observed after changing the NetworkPolicy to use `podSelector` instead of `ipBlock`:

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allowlist
spec:
  policyTypes:
  - Egress
  podSelector:
    matchLabels:
      app: curl
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: hello
```

With the `podSelector` NetworkPolicy in effect, the opposite behavior is observed: networking works only when pods are on the same node. Networking times out when pods are on different nodes.

In a cluster using cilium instead of calico, this `podSelector`-based NetworkPolicy does not work in either case.

For calico, the desired behavior can be achieved by creating a NetworkPolicy with both the `ipBlock` rule and the `podSelector` rule:

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allowlist
spec:
  policyTypes:
  - Egress
  podSelector:
    matchLabels:
      app: curl
  egress:
  - to:
    - ipBlock:
        cidr: 172.18.0.0/24
  - to:
    - podSelector:
        matchLabels:
          app: hello
```

## Context

NodePort services aren't ideal, much less so when used for pod-to-pod traffic in the same cluster. However, in some situation NodePort is all you got, and sometimes it is necessary for a service to be accessible from both inside the cluster and outside the cluster by the same URL. Such is the case when configuring a web application with a callback URL for OIDC authentication.
